package v5

// dataActions contains all action definitions
var dataActions = map[string]Action{
	// Unclassified Actions
	"delaying_action": {
		Name:        "Delaying Action",
		Type:        ActionTypeUnclassified,
		Description: "A character can delay their action to act later in the Initiative Pass. Must be declared during Step 3A. Character can choose to go before, after, or at the same time as a currently acting character at a specific Initiative Score. Actions taken receive a –1 dice pool penalty. Character keeps their initial Initiative Score. If character does not act before the end of the Initiative Pass, they incur the standard reduction of 10 at the end of the Initiative Pass.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"walking": {
		Name:        "Walking",
		Type:        ActionTypeUnclassified,
		Description: "A character can move up to their Walking rate (Agility×2) per Combat Turn without taking any actions. Moving beyond this rate requires the character to Run or Sprint.",
		Source:      &SourceReference{Source: "SR5"},
	},
	// Free Actions
	"call_a_shot": {
		Name:        "Call a Shot",
		Type:        ActionTypeFree,
		Description: "A character may call a shot (aim for a vulnerable portion of a target) with this Free Action. This action must be combined with a Fire Weapon, Throw Weapon, or Melee Attack Action. See Called Shots.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"change_linked_device_mode": {
		Name:        "Change Linked Device Mode",
		Type:        ActionTypeFree,
		Description: "A character may use a Free Action to activate, deactivate, or switch the mode on any device that they are linked to by a direct neural interface through either a wired or wireless link. This includes activating cyberware, changing a smartgun's firing mode, changing a smartlinked shotgun's choke, deactivating thermographic vision, switching a commlink to hidden mode, turning a device's wireless functionality off, and so on.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"deactivate_focus": {
		Name:        "Deactivate Focus",
		Type:        ActionTypeFree,
		Description: "You can deactivate a focus at any time with a Free Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"drop_object": {
		Name:        "Drop Object",
		Type:        ActionTypeFree,
		Description: "A character may drop a held object as a Free Action. If holding an object in each hand, they may drop both objects as a single Free Action. At the gamemaster's discretion, dropped items may suffer damage from being dropped if they are fragile or dropped in a hostile environment.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"drop_prone": {
		Name:        "Drop Prone",
		Type:        ActionTypeFree,
		Description: "A character may kneel or drop prone as a Free Action, as long as they are not surprised. A character who is surprised may not drop prone.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"eject_smartgun_clip": {
		Name:        "Eject Smartgun Clip",
		Type:        ActionTypeFree,
		Description: "A character linked to a ready smartgun may use a mental command to eject the weapon's clip. It still takes a separate Simple Action to insert a new, fresh clip.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"gesture": {
		Name:        "Gesture",
		Type:        ActionTypeFree,
		Description: "A character may communicate with a few quick gestures as a Free Action. Characters unfamiliar with the gestures may make an Intuition (2) Test to determine what the gesture means.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"multiple_attacks": {
		Name:        "Multiple Attacks",
		Type:        ActionTypeFree,
		Description: "A character may use a Free Action to attack multiple targets in a single action by splitting their dice pool. This action must be combined with a Fire Weapon Action, Throw Weapon Action, Melee Attack Action, Reckless Spellcasting, or Cast Spell Action. See Multiple Attacks (p. 196).",
		Source:      &SourceReference{Source: "SR5"},
	},
	"run": {
		Name:        "Run",
		Type:        ActionTypeFree,
		Description: "Running uses a Free Action and inflicts Running movement modifiers. Running is any movement that exceeds the character's Walking Movement Rate in a single Combat Turn.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"speak_text_transmit_phrase": {
		Name:        "Speak/Text/Transmit Phrase",
		Type:        ActionTypeFree,
		Description: "One short phrase of verbal communication is a Free Action. If the character wants to speak more, each additional phrase or sentence requires a Free Action. The gamemaster should be careful to control excessive, unrealistic conversations within the span of a single action during a 3-second Combat Turn. Characters who are equipped to send text messages through a direct neural interface connection with their commlink may also send short messages as a Free Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	// Simple Actions
	"activate_focus": {
		Name:        "Activate Focus",
		Type:        ActionTypeSimple,
		Description: "A character may activate a focus they are carrying with a Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"call_spirit": {
		Name:        "Call Spirit",
		Type:        ActionTypeSimple,
		Description: "This action is used to call a spirit that has already been summoned and placed on standby.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"change_device_mode": {
		Name:        "Change Device Mode",
		Type:        ActionTypeSimple,
		Description: "A character may use a Simple Action to activate, deactivate, or change the mode on any device with a simple switch, a virtual button, or a command from a commlink or other control device through either a wired or wireless link. This includes changing a gun's firing mode, changing a shotgun's choke, changing vision systems, switching a commlink to hidden mode, turning a device's wireless functionality off, and so on. It takes longer to interact with some devices; check individual gear descriptions.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"change_gun_mode": {
		Name:        "Change Gun Mode",
		Type:        ActionTypeSimple,
		Description: "A character holding a ready firearm can change its firing mode via a Simple Action. If the weapon is a properly linked smartgun, it costs only a Free Action to change the mode with a Change Linked Device Mode action. This includes changing a shotgun's choke if the gun does not have a smartlink.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"command_spirit": {
		Name:        "Command Spirit",
		Type:        ActionTypeSimple,
		Description: "This action is used to command a spirit that has already been summoned.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"dismiss_spirit": {
		Name:        "Dismiss Spirit",
		Type:        ActionTypeSimple,
		Description: "This action is used to dismiss a spirit that has been summoned.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"fire_bow": {
		Name:        "Fire Bow",
		Type:        ActionTypeSimple,
		Description: "A character may fire a readied bow with a Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"fire_semi_auto_single_shot_burst_fire_or_full_auto": {
		Name:        "Fire Semi-Auto, Single Shot, Burst Fire, or Full-Auto",
		Type:        ActionTypeSimple,
		Description: "A character may fire a readied firearm in Semi-Auto, Single Shot, Burst Fire, or Full-Auto fire mode via a Simple Action (see Firearms, p. 424).",
		Source:      &SourceReference{Source: "SR5"},
	},
	"insert_clip": {
		Name:        "Insert Clip",
		Type:        ActionTypeSimple,
		Description: "A character may insert a clip into a ready firearm with a Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"observe_in_detail": {
		Name:        "Observe in Detail",
		Type:        ActionTypeSimple,
		Description: "A character may make a detailed observation of a target or area with a Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"pick_up_put_down_object": {
		Name:        "Pick Up/Put Down Object",
		Type:        ActionTypeSimple,
		Description: "A character may pick up or put down an object with a Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"quick_draw": {
		Name:        "Quick Draw",
		Type:        ActionTypeSimple,
		Description: "A character may draw a weapon with a Quick Draw Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"ready_weapon": {
		Name:        "Ready Weapon",
		Type:        ActionTypeSimple,
		Description: "A character may ready a weapon with a Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"reckless_spellcasting": {
		Name:        "Reckless Spellcasting",
		Type:        ActionTypeSimple,
		Description: "A character may cast a spell recklessly with a Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"remove_clip": {
		Name:        "Remove Clip",
		Type:        ActionTypeSimple,
		Description: "A character may remove a clip from a ready firearm with a Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"shift_perception": {
		Name:        "Shift Perception",
		Type:        ActionTypeSimple,
		Description: "A character may shift their perception (e.g., from normal vision to astral perception) with a Simple Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"stand_up": {
		Name:        "Stand Up",
		Type:        ActionTypeSimple,
		Description: "A character may stand up from a prone or kneeling position with a Simple Action. A character who is surprised may not stand up.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"take_aim": {
		Name:        "Take Aim",
		Type:        ActionTypeSimple,
		Description: "A character may take aim at a target with a Simple Action, gaining bonuses to their attack test.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"take_cover": {
		Name:        "Take Cover",
		Type:        ActionTypeSimple,
		Description: "A character may use this Simple Action to gain a cover bonus to their defense test, as long as they are not surprised (see Surprise, p. 192). A character who is surprised may not take cover.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"throw_weapon": {
		Name:        "Throw Weapon",
		Type:        ActionTypeSimple,
		Description: "A character may throw a ready throwing weapon (see Ready Weapon) by taking a Simple Action. The character may not take any other attack actions in the same Action Phase. Multiple readied throwing weapons can be thrown at a target within Short or Medium range by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 196).",
		Source:      &SourceReference{Source: "SR5"},
	},
	"use_simple_device": {
		Name:        "Use Simple Device",
		Type:        ActionTypeSimple,
		Description: "A character can use any simple device with a Simple Action. Simple devices are those that are activated with a simple movement like a thumb trigger, pressing a single key, or tapping a single icon.",
		Source:      &SourceReference{Source: "SR5"},
	},
	// Complex Actions
	"astral_projection": {
		Name:        "Astral Projection",
		Type:        ActionTypeComplex,
		Description: "A character capable of Astral Projection may shift their consciousness to the astral plane as a Complex Action (see p. 313).",
		Source:      &SourceReference{Source: "SR5"},
	},
	"banish_spirit": {
		Name:        "Banish Spirit",
		Type:        ActionTypeComplex,
		Description: "A character may enter into a Banishing contest with a spirit as a Complex Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"cast_spell": {
		Name:        "Cast Spell",
		Type:        ActionTypeComplex,
		Description: "A character may cast a spell as a Complex Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"fire_full_auto_weapons": {
		Name:        "Fire Full-Auto Weapons",
		Type:        ActionTypeComplex,
		Description: "A character may fire a readied firearm in Full-Auto fire mode via a Complex Action (see Firearms, p. 424). If a character has one weapon in each hand, they may fire once with each weapon by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 196). Off-hand modifier applies (see Attacker Using Off-Hand Weapon, p. 178). When fired as a Complex Action, Full-Auto uses 10 bullets. Remember the effects of cumulative recoil when using these fire modes.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"fire_long_burst_or_semi_auto_burst": {
		Name:        "Fire Long Burst or Semi-Auto Burst",
		Type:        ActionTypeComplex,
		Description: "A character may fire a readied firearm in Long Burst or Semi-Auto Burst via a Complex Action (see Firearms, p. 424). A character may attack multiple targets within Short or Medium range by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 196). If a character has one weapon in each hand, they may fire once with each weapon by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 167). Off-hand modifier applies (see Attacker Using Off-Hand Weapon, p. 178). Remember the effects of cumulative recoil when using these fire modes.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"fire_mounted_or_vehicle_weapon": {
		Name:        "Fire Mounted or Vehicle Weapon",
		Type:        ActionTypeComplex,
		Description: "Fire a previously readied mounted or vehicle weapon by taking a Complex Action (see Vehicle Combat, p. 198).",
		Source:      &SourceReference{Source: "SR5"},
	},
	"load_and_fire_bow": {
		Name:        "Load and Fire Bow",
		Type:        ActionTypeComplex,
		Description: "With this action a character can load and fire a bow with a single Complex Action. The two activities can be reversed, Fire and Load Bow, if the bow had been readied using a Simple Action already.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"melee_attack": {
		Name:        "Melee Attack",
		Type:        ActionTypeComplex,
		Description: "A character may make a melee attack by taking a Complex Action (see Melee Combat, p. 184). A character may also attack multiple targets within melee range by adding a Multiple Attacks Free Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"reload_firearm": {
		Name:        "Reload Firearm",
		Type:        ActionTypeComplex,
		Description: "Weapons that are belt fed (belt), break action (b), cylinder (cy), drum (d), internal magazine (m), muzzle loaders, or use a speed loader are reloaded using a Complex Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"rigger_jump_in": {
		Name:        "Rigger Jump In",
		Type:        ActionTypeComplex,
		Description: "A character with a control rig and rigger adapted vehicle may jump in to control the vehicle with a Complex Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"sprint": {
		Name:        "Sprint",
		Type:        ActionTypeComplex,
		Description: "Sprinting allows a character to increase their Running rate by using a Complex Action and making a Running Test (see Movement, p. 161).",
		Source:      &SourceReference{Source: "SR5"},
	},
	"summoning": {
		Name:        "Summoning",
		Type:        ActionTypeComplex,
		Description: "A character may summon a spirit to assist them with a Complex Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"use_skill": {
		Name:        "Use Skill",
		Type:        ActionTypeComplex,
		Description: "A character may use an appropriate skill by taking a Complex Action.",
		Source:      &SourceReference{Source: "SR5"},
	},
	// Interrupt Actions
	"block": {
		Name:           "Block",
		Type:           ActionTypeInterrupt,
		InitiativeCost: intPtr(-5),
		Description:    "A character may choose to use their own unarmed combat skill to block incoming melee attacks as an Interrupt Action. By decreasing their Initiative Score, the defending character can add their Unarmed Combat skill to their defense test. This is a one-time add, unlike going on Full Defense which lasts for an entire Combat Turn.",
		Source:         &SourceReference{Source: "SR5"},
	},
	"dodge": {
		Name:           "Dodge",
		Type:           ActionTypeInterrupt,
		InitiativeCost: intPtr(-5),
		Description:    "A character may choose to use their own skill to dodge incoming attacks as an Interrupt Action. By decreasing their Initiative Score, the defending character can add their Gymnastics skill to the defense test. This is a one-time add, unlike going on Full Defense which lasts for an entire Combat Turn.",
		Source:         &SourceReference{Source: "SR5"},
	},
	"full_defense": {
		Name:           "Full Defense",
		Type:           ActionTypeInterrupt,
		InitiativeCost: intPtr(-10),
		Description:    "A character may choose to focus on deliberately avoiding incoming attacks as an Interrupt Action. This action adds the character's Willpower to their Defense tests for the entire Combat Turn. Full Defense actions may be taken at any time, even before the character's Action Phase as an Interrupt Action, as long as the character is not surprised. Characters may only go on Full Defense if they have enough Initiative Score left in that Combat Turn. The bonus gained in this manner is kept until the end of the Combat Turn so a character can choose to fight defensively early in the round by decreasing their Initiative Score to increase their defense. This bonus is also cumulative with other Interrupt Actions.",
		Source:         &SourceReference{Source: "SR5"},
	},
	"hit_the_dirt": {
		Name:           "Hit the Dirt",
		Type:           ActionTypeInterrupt,
		InitiativeCost: intPtr(-5),
		Description:    "A character who has already used their Free Action may choose to drop prone when caught by suppressive fire using this action. The defending character doesn't need to make the Reaction + Edge test but is considered prone on their next Action Phase. If the suppressive fire continues, the defending character needs to use a Stand Up Simple Action to get back up, risking getting shot, or fight from the ground. If the suppressive fire has stopped the prone character still needs to use a Stand Up Simple Action to get back up.",
		Source:         &SourceReference{Source: "SR5"},
	},
	"intercept": {
		Name:           "Intercept",
		Type:           ActionTypeInterrupt,
		InitiativeCost: intPtr(-5),
		Description:    "A character may take an Interrupt Action to intercept an opponent who attempts to move past them within 1 meter (+1 meter per point of Reach) or break out of melee combat with them. The Intercept Action allows a character to make a melee attack out of turn. If the character does not have enough Initiative Score left that Action Phase, they cannot intercept. If the opponent has a melee weapon ready, they use their normal melee weapon skill rating; otherwise, they use the Unarmed Combat skill. If the character is wielding a firearm they may choose to use the weapon as a club and attack with the Club skill. This attack follows all of the normal rules for Melee Combat. If, after their Resistance Test, the character attempting to pass takes damage equal to their Body, they are intercepted and cannot continue their movement. Prone combatants cannot intercept. With a little room to move, agile characters can avoid the Interception attempts of their opponents without engaging in combat. Using a Complex Action with their movement, they can make an Agility + Gymnastics [Physical] Test. Each hit above the threshold allows the character to move past one opponent.",
		Source:         &SourceReference{Source: "SR5"},
	},
	"parry": {
		Name:           "Parry",
		Type:           ActionTypeInterrupt,
		InitiativeCost: intPtr(-5),
		Description:    "A character may choose to use their own melee weapon skill to deflect incoming melee attacks as an Interrupt Action. By decreasing their Initiative Score, the defending character can add their melee weapon skill to their defense test. This is a one-time add, unlike going on Full Defense, which lasts for an entire Combat Turn. Bonus die, such as die from a relevant weapon foci, can be added to this test.",
		Source:         &SourceReference{Source: "SR5"},
	},
}

