package v5

// dataActiveSkills contains all active skill definitions
var dataActiveSkills = map[string]Skill{
// Active skills data
	// Combat Active Skills
	"archery": {
		Name:            "Archery",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Archery is used to fire string-loaded projectile weapons. An archer is familiar with many different styles of bow and the multitude of arrows that can be used to maximum effect.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Bow", "Crossbow", "Non-Standard Ammunition", "Slingshot"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"automatics": {
		Name:            "Automatics",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "The Automatics skill covers a specific subset of firearms larger than handheld pistols but smaller than rifles. This category includes submachine guns and other fully automatic carbines.",
		CanDefault:      true,
		SkillGroup:      "Firearms",
		Specializations: []string{"Assault Rifles", "Cyber-Implant", "Machine Pistols", "Submachine Guns"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"blades": {
		Name:            "Blades",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Slice and dice! The Blades skill includes the use of all handheld slashing and stabbing weapons. You can use a range of edged weapons including daggers, swords, and axes.",
		CanDefault:      true,
		SkillGroup:      "Close Combat",
		Specializations: []string{"Axes", "Knives", "Swords", "Parrying"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"clubs": {
		Name:            "Clubs",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Clubs governs the use of all hand-held bludgeoning instruments. With this skill you can turn any blunt item, be it a baseball bat, crutch, or mace, into a weapon.",
		CanDefault:      true,
		SkillGroup:      "Close Combat",
		Specializations: []string{"Batons", "Hammers", "Saps", "Staves", "Parrying"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"exotic_ranged_weapon": {
		Name:            "Exotic Ranged Weapon",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Sometimes a regular gun or blade won't do the job and you need something fancier. Or weirder. This skill must be taken once for each unusual ranged weapon you want to use. Some examples include blowguns, gyrojet pistols, flamethrowers, and lasers.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"heavy_weapons": {
		Name:            "Heavy Weapons",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "The term heavy weapon is designated for all projectile weaponry larger than an assault rifle, such as grenade launchers, machine guns, and assault cannons. This skill is exclusive to handheld and non-vehicle-mounted weaponry—if you've got a gun mounted on or in a vehicle, use Gunnery.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Assault Cannons", "Grenade Launchers", "Guided Missiles", "Machine Guns", "Rocket Launchers"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"longarms": {
		Name:            "Longarms",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "The Longarms skill is for firing extended-barrel weapons such as sporting rifles and sniper rifles. This grouping also includes weapons like shotguns that are designed to be braced against the shoulder.",
		CanDefault:      true,
		SkillGroup:      "Firearms",
		Specializations: []string{"Extended-Range Shots", "Long-Range Shots", "Shotguns", "Sniper Rifles"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"pistols": {
		Name:            "Pistols",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "This skill category includes all types of handheld pistols, including tasers, single-shots, semi-automatics, and revolvers.",
		CanDefault:      true,
		SkillGroup:      "Firearms",
		Specializations: []string{"Holdouts", "Revolvers", "Semi-Automatics", "Tasers"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"throwing_weapons": {
		Name:            "Throwing Weapons",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Throwing Weapons is a broad-based attack skill that can be used for any handheld item that is thrown by the user as a weapon.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Aerodynamic", "Blades", "Non-Aerodynamic"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"unarmed_combat": {
		Name:            "Unarmed Combat",
		Type:            SkillTypeActive,
		Category:        SkillCategoryCombatActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Unarmed Combat covers the various self-defense and attack moves that employ the body as a primary weapon. This includes a wide array of martial arts along with the use of cybernetic implant weaponry and the fighting styles that sprung up around those implants.",
		CanDefault:      true,
		SkillGroup:      "Close Combat",
		Specializations: []string{"Blocking", "Cyber Implants", "Subduing Combat", "or by specific Martial Art"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	// Physical Active Skills
	"disguise": {
		Name:            "Disguise",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeIntuition,
		Description:     "Disguise covers non-magical forms of masking your identity, including makeup and enhancement. See Using Disguise and Impersonation, p. 136.",
		CanDefault:      true,
		SkillGroup:      "Stealth",
		Specializations: []string{"Camouflage", "Cosmetic", "Theatrical", "Trideo & Video"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"diving": {
		Name:            "Diving",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeBody,
		Description:     "Diving brings together a wide array of actions performed underwater. This skill can be applied when diving, swimming underwater, using complex diving equipment, and holding your breath.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"By breathing apparatus (Liquid Breathing Apparatus, Mixed Gas, Oxygen Extraction, SCUBA)", "by condition (Arctic, Cave, Commercial, Military, etc.)", "Controlled Hyperventilation"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"escape_artist": {
		Name:            "Escape Artist",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Escape Artist measures the character's ability to escape from bindings by using body contortion and manual dexterity. See Using Escape Artist, p. 135.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"By restraint (Cuffs, Ropes, Zip Ties, etc.)", "Contortionism"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"free_fall": {
		Name:            "Free-Fall",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeBody,
		Description:     "This skill covers any jump from height, including leaps from a third-floor window to jumps from a plane at high altitude. If it involves any kind of attempt to slow or control your fall, this covers it, so it includes skydiving with a parachute, flying a wingsuit, or descending on a line, bungee cord, or zipline.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"BASE Jumping", "Break-Fall", "Bungee", "HALO", "Low Altitude", "Parachute", "Static Line", "Wingsuit", "Zipline"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"gymnastics": {
		Name:            "Gymnastics",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Gymnastics measures your balance, general athleticism, and all-around ability to use your body. For more information on ways Gymnastics may be applied in-game, see Jumping, p. 134.",
		CanDefault:      true,
		SkillGroup:      "Athletics",
		Specializations: []string{"Balance", "Climbing", "Dance", "Leaping", "Parkour", "Rolling"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"palming": {
		Name:            "Palming",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Palming is sleight-of-hand skill that gives a character the ability to snag, hide, and pass off small objects.",
		CanDefault:      false,
		SkillGroup:      "Stealth",
		Specializations: []string{"Legerdemain", "Pickpocket", "Pilfering"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"perception": {
		Name:            "Perception",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeIntuition,
		Description:     "Perception refers to the ability to spot anomalies in everyday situations, making it one of the key skills a shadowrunner needs. See Using Perception, p. 135.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Hearing", "Scent", "Searching", "Taste", "Touch", "Visual"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"running": {
		Name:            "Running",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeStrength,
		Description:     "Running, as you may guess, is about how much ground you can cover quickly. For more information see Using Running, p. 136.",
		CanDefault:      true,
		SkillGroup:      "Athletics",
		Specializations: []string{"Distance", "Sprinting", "by terrain (Desert, Urban, Wilderness, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"sneaking": {
		Name:            "Sneaking",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeAgility,
		Description:     "Need to get where you're not supposed to be? This skill allows you to remain inconspicuous in various situations. See Using Stealth Skills, p. 136.",
		CanDefault:      true,
		SkillGroup:      "Stealth",
		Specializations: []string{"Location type (Jungle, Urban, Desert, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"survival": {
		Name:            "Survival",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeWillpower,
		Description:     "In the desert with nothing more than a tin cup, a poncho, and an iron rod? You'll need this skill to help you get out alive. Survival is the ability to stay alive in extreme environmental conditions for extended periods of time. The skill governs a character's ability to perform vital outdoor tasks such as start a fire, build a shelter, scrounge for food, etc. in hostile environments. See Using Survival, p. 136.",
		CanDefault:      true,
		SkillGroup:      "Outdoors",
		Specializations: []string{"Desert", "Forest", "Jungle", "Mountain", "Polar", "Urban", "or other terrain"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"swimming": {
		Name:            "Swimming",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeStrength,
		Description:     "This skill determines the character's ability to swim in various bodies of water. The skill level affects the distance and speed at which a character can swim. See Using Swimming, p. 137",
		CanDefault:      true,
		SkillGroup:      "Athletics",
		Specializations: []string{"Dash", "Long Distance"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"tracking": {
		Name:            "Tracking",
		Type:            SkillTypeActive,
		Category:        SkillCategoryPhysicalActive,
		LinkedAttribute: AttributeIntuition,
		Description:     "This skill confers the ability to detect the passage of metahumans and other game through terrain and use those clues to follow that individual. This skill also allows you to identify unmarked trails and common game paths is various environments. See Using Tracking, p. 137.",
		CanDefault:      true,
		SkillGroup:      "Outdoors",
		Specializations: []string{"Desert", "Forest", "Jungle", "Mountain", "Polar", "Urban", "another terrain type"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	// Social Skills
	"con": {
		Name:            "Con",
		Type:            SkillTypeActive,
		Category:        SkillCategorySocial,
		LinkedAttribute: AttributeCharisma,
		Description:     "Con governs the ability to manipulate or fool an NPC during a social encounter. This skill covers a range of confidence games as well as the principles behind those cons.",
		CanDefault:      true,
		SkillGroup:      "Acting",
		Specializations: []string{"Fast Talking", "Seduction"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"etiquette": {
		Name:            "Etiquette",
		Type:            SkillTypeActive,
		Category:        SkillCategorySocial,
		LinkedAttribute: AttributeCharisma,
		Description:     "Etiquette represents the level of understanding and awareness of proper social rituals. The skill works as a sort of social version of Sneak, allowing you to move unimpeded through various social situations. Etiquette also serves as a social safety net in case a player botches a social situation in a way a skilled character would not. See Using Etiquette, p. 141.",
		CanDefault:      true,
		SkillGroup:      "Influence",
		Specializations: []string{"By culture or subculture (Corporate, High Society, Media, Mercenary, Street, Yakuza, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"impersonation": {
		Name:            "Impersonation",
		Type:            SkillTypeActive,
		Category:        SkillCategorySocial,
		LinkedAttribute: AttributeCharisma,
		Description:     "Impersonation is the ability to assume the identity of another person, including voice and physical mannerisms. The skill is limited by the physical abilities of the character. A dwarf might be able to impersonate a troll over a commlink, but the illusion shatters when he is face to face with his target.",
		CanDefault:      true,
		SkillGroup:      "Acting",
		Specializations: []string{"By metahuman type (Dwarf, Elf, Human, Ork, Troll)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"instruction": {
		Name:            "Instruction",
		Type:            SkillTypeActive,
		Category:        SkillCategorySocial,
		LinkedAttribute: AttributeCharisma,
		Description:     "Instruction governs the ability to teach people. The skill level helps determine how comfortable the instructor is delivering new material as well as how complex of a skill may be taught. See Using Instruction, p. 141.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"By Active or Knowledge skill category (Combat, Language, Magical, Academic Knowledge, Street Knowledge, etc."},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"intimidation": {
		Name:            "Intimidation",
		Type:            SkillTypeActive,
		Category:        SkillCategorySocial,
		LinkedAttribute: AttributeCharisma,
		Description:     "Intimidation is about creating the impression that you are more menacing than another person in order to get them to do what you want. The skill may be applied multiple ways, from negotiation to interrogation. Intimidation is an Opposed Intimidation + Charisma [Social] Test against the target's Charisma + Willpower, modified by the appropriate entries on the Social Modifiers Table (p. 140).",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Interrogation", "Mental", "Physical", "Torture"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"leadership": {
		Name:            "Leadership",
		Type:            SkillTypeActive,
		Category:        SkillCategorySocial,
		LinkedAttribute: AttributeCharisma,
		Description:     "Leadership is the ability to direct and motivate others. It's like Con, except rather than using deception you're using a position of authority. This skill is especially helpful in situations where the will of a teammate is shaken or someone is being asked to do something uncomfortable. The Leadership skill is not meant to replace or make up for poor teamwork. When using Leadership make an opposed test Charisma + Leadership. See Using Social Influence Skills, at right, for test modifiers.",
		CanDefault:      true,
		SkillGroup:      "Influence",
		Specializations: []string{"Command", "Direct", "Inspire", "Rally"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"negotiation": {
		Name:            "Negotiation",
		Type:            SkillTypeActive,
		Category:        SkillCategorySocial,
		LinkedAttribute: AttributeCharisma,
		Description:     "Negotiation governs a character's ability to apply their charisma, tactics, and knowledge of situational psychology in order to create a better position when making deals.",
		CanDefault:      true,
		SkillGroup:      "Influence",
		Specializations: []string{"Bargaining", "Contracts", "Diplomacy"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"performance": {
		Name:            "Performance",
		Type:            SkillTypeActive,
		Category:        SkillCategorySocial,
		LinkedAttribute: AttributeCharisma,
		Description:     "This skill governs the ability to execute a performing art. Performance is to the arts what Artisan is to craft. The performer uses her skill to entertain or even captivate an audience. See Using Performance, p. 141.",
		CanDefault:      true,
		SkillGroup:      "Acting",
		Specializations: []string{"By performance art (Presentation, Acting, Comedy, specific Musical Instrument, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	// Magical Skills
	"alchemy": {
		Name:            "Alchemy",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeMagic,
		Description:     "Alchemy is used to create substances that store spells. Alchemy is most commonly used to brew potions, distill magical reagents, and even create orichalcum.",
		CanDefault:      false,
		SkillGroup:      "Enchanting",
		Specializations: []string{"By trigger (Command, Contact, Time)", "by spell type (Combat Spells, Detection Spells, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"arcana": {
		Name:            "Arcana",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeLogic,
		Description:     "Arcana governs the creation of magical formulae used to create spells, foci, and all other manner of magical manipulations. Arcana is required to understand formulae that may be purchased over the counter or discovered by other means.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{"Spell Design", "Focus Design", "Spirit Formula"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"artificing": {
		Name:            "Artificing",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeMagic,
		Description:     "Artificing is the process of crafting magical foci. The skill may also be used forensically, in order to assense qualities about an existing focus' creation and purpose. See Artificing p. 306.",
		CanDefault:      false,
		SkillGroup:      "Enchanting",
		Specializations: []string{"Focus Analysis", "Crafting (by focus type)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"assensing": {
		Name:            "Assensing",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeIntuition,
		Description:     "Assensing is a magic user's ability to read and interpret fluctuations in the astral world. This skill allows practitioners to learn information by reading astral auras. Only characters capable of astral perception may take this skill. For more information, see Astral Perception, p. 312",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{"Aura Reading", "Astral Signatures", "by aura type (Metahumans, Spirits, Foci, Wards, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"astral_combat": {
		Name:            "Astral Combat",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeWillpower,
		Description:     "Fighting in Astral Space requires the Astral Combat skill. Combat in the Astral World relies on a very different set of abilities and attributes than physical combatants. See Astral Combat, p. 315.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{"By specific weapon focus type", "by opponents (Magicians, Spirits, Mana Barriers, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"banishing": {
		Name:            "Banishing",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeMagic,
		Description:     "Banishing is used to disrupt the link between spirits and the physical world. Banished spirits are forced to return to their native plane and are no longer required to complete unfulfilled services.",
		CanDefault:      false,
		SkillGroup:      "Conjuring",
		Specializations: []string{"By spirit type (Spirits of Air, Spirits of Man, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"binding": {
		Name:            "Binding",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeMagic,
		Description:     "Binding is used to compel a summoned spirit to perform a number of additional services. See Binding, p. 300.",
		CanDefault:      false,
		SkillGroup:      "Conjuring",
		Specializations: []string{"By spirit type (Spirits of Fire, Spirits of Earth, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"counterspelling": {
		Name:            "Counterspelling",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeMagic,
		Description:     "Counterspelling is a defensive skill used to defend against magical attacks and dispel sustained magical spells. See Counterspelling, p. 294.",
		CanDefault:      false,
		SkillGroup:      "Sorcery",
		Specializations: []string{"By spell type (Combat Spells, Detection Spells, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"disenchanting": {
		Name:            "Disenchanting",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeMagic,
		Description:     "This skill governs a character's ability to remove the enchantment from an item. See Disenchanting, p. 307.",
		CanDefault:      false,
		SkillGroup:      "Enchanting",
		Specializations: []string{"By type (Alchemical Preparations, Power Foci, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"ritual_spellcasting": {
		Name:            "Ritual Spellcasting",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeMagic,
		Description:     "Ritual spellcasting is a spellcasting skill used to cast ritual spells. See Ritual Spellcasting, p. 295.",
		CanDefault:      false,
		SkillGroup:      "Sorcery",
		Specializations: []string{"By keyword (Anchored, Spell, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"spellcasting": {
		Name:            "Spellcasting",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeMagic,
		Description:     "The Spellcasting skill permits the character to channel mana into effects known as spells. See Spellcasting, p. 281.",
		CanDefault:      false,
		SkillGroup:      "Sorcery",
		Specializations: []string{"By spell type (Combat Spells, Detection Spells, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"summoning": {
		Name:            "Summoning",
		Type:            SkillTypeActive,
		Category:        SkillCategoryMagical,
		LinkedAttribute: AttributeMagic,
		Description:     "This skill is used to summon spirits. See Summoning, p. 300).",
		CanDefault:      false,
		SkillGroup:      "Conjuring",
		Specializations: []string{"By spirit type (Spirits of Earth, Spirits of Man, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	// Resonance Skills
	"compiling": {
		Name:            "Compiling",
		Type:            SkillTypeActive,
		Category:        SkillCategoryResonance,
		LinkedAttribute: AttributeResonance,
		Description:     "Compiling involves the ability to translate the complex 0s and 1s of machine source language and the rhythms of the resonance into sprites. See Sprites, p. 254.",
		CanDefault:      false,
		SkillGroup:      "Tasking",
		Specializations: []string{"By sprite type (Data Sprites, Machine Sprites, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"decompiling": {
		Name:            "Decompiling",
		Type:            SkillTypeActive,
		Category:        SkillCategoryResonance,
		LinkedAttribute: AttributeResonance,
		Description:     "Decompiling is a character's ability to effectively delete previously compiled sprites. See Sprites, p. 254.",
		CanDefault:      false,
		SkillGroup:      "Tasking",
		Specializations: []string{"By sprite type (Courier Sprites, Fault Sprites, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"registering": {
		Name:            "Registering",
		Type:            SkillTypeActive,
		Category:        SkillCategoryResonance,
		LinkedAttribute: AttributeResonance,
		Description:     "This skill allows a technomancer to register sprites on the Matrix, thereby convincing the grids that they are legitimate. See Sprites, p. 254.",
		CanDefault:      false,
		SkillGroup:      "Tasking",
		Specializations: []string{"By sprite type (Crack Sprites, Data Sprites, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	// Technical Skills
	"aeronautics_mechanic": {
		Name:            "Aeronautics Mechanic",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Aeronautics mechanics have the ability to repair a variety of aerospace vehicles, provided the proper tools and parts are available. See Building & Repairing, p. 145.",
		CanDefault:      false,
		SkillGroup:      "Engineering",
		Specializations: []string{"Aerospace", "Fixed Wing", "LTA (blimp)", "Rotary Wing", "Tilt Wing", "Vector Thrust"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"animal_handling": {
		Name:            "Animal Handling",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeCharisma,
		Description:     "This skill governs the training, care, riding (if they're big enough), and control of non-sentient animals. Competent trainers have the ability to handle multiple animals. It is even possible to approach an untrained animal and get it to trust you, or at least not eat you.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"By animal (Cat, Bird, Hell Hound, Horse, Dolphin, etc.)", "Herding", "Riding", "Training"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"armorer": {
		Name:            "Armorer",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Armorer encompasses the broad array of skills required to build and maintain weapons and armor. As with all mechanics-based skills, the proper tools and equipment are required to perform any repair or build operation. For thresholds and information on determining success results, see Building & Repairing, p. 145.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Armor", "Artillery", "Explosives", "Firearms", "Melee Weapons", "Heavy Weapons", "Weapon Accessories"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"artisan": {
		Name:            "Artisan",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeIntuition,
		Description:     "This skill includes several different forms of artistic impression as well as the handcrafting of fine objects that would otherwise be produced on an assembly line. The world's top artists and crafters are considered artisans.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{"By discipline (Cooking, Sculpting, Drawing, Carpentry, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"automotive_mechanic": {
		Name:            "Automotive Mechanic",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Automotive mechanics are tasked with fixing all types of ground-based vehicles ranging from commercial automobiles to wheeled drones to tanks. Repairs require the proper tools and time. See Building & Repairing, p. 145.",
		CanDefault:      false,
		SkillGroup:      "Engineering",
		Specializations: []string{"Walker", "Hover", "Tracked", "Wheeled"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"biotechnology": {
		Name:            "Biotechnology",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Biotechnology is a wide-ranging skill primarily used by doctors and scientists to grow organic body parts. This skill is the basis for cloning as well as all forms of bioware. Provided the right equipment is available, biotechnology can be used to repair damaged bioware, clone new tissue, or detect any bioware in a subject's body. This skill does not allow characters to install or remove bioware.",
		CanDefault:      false,
		SkillGroup:      "Biotech",
		Specializations: []string{"Bioinformatics", "Bioware", "Cloning", "Gene Therapy", "Vat Maintenance"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"chemistry": {
		Name:            "Chemistry",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Chemistry permits the character to create chemical reactions and develop chemical compounds ranging from drugs, to perfumes, to biopolymers like NuSkin. Chemistry can also be used to analyze chemical compounds to determine what they are.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{"Analytical", "Biochemistry", "Inorganic", "Organic", "Physical"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"computer": {
		Name:            "Computer",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Computer is the base skill for interacting with the Matrix. It represents the ability to use computers and other Matrix-connected devices. The Computer skill focuses on understanding multiple operating systems. It does not allow the character to exploit code (Hacking) or strip down mainframes (Hardware). See Using Computer, p. 226.",
		CanDefault:      true,
		SkillGroup:      "Electronics",
		Specializations: []string{"By action (Edit File, Matrix Perception, Matrix Search, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"cybercombat": {
		Name:            "Cybercombat",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Cybercombat is the skill used by hackers to engage in combat on the Matrix. See Using Cybercombat, p. 226",
		CanDefault:      true,
		SkillGroup:      "Cracking",
		Specializations: []string{"By target type (Devices, Grids, IC, Personas, Sprites, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"cybertechnology": {
		Name:            "Cybertechnology",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Cybertechnology is the ability to create, maintain, and repair cybernetic parts. A character with the proper tools and parts may repair or even build new cybernetics. Cybertechnology is not a surgical skill. Characters cannot attach or re-attach cybernetics to organic material with this skill. This skill may be used to modify or upgrade cybernetics within cyberlimbs. See Building and Repairing, p. 145.",
		CanDefault:      false,
		SkillGroup:      "Biotech",
		Specializations: []string{"Bodyware", "Cyberlimbs", "Headware", "Repair"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"demolitions": {
		Name:            "Demolitions",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Demolitions is used to prepare, plant, detonate, and often defuse chemical-based explosives. See Explosives, p. 436.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Commercial Explosives", "Defusing", "Improvised Explosives", "Plastic Explosives"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"electronic_warfare": {
		Name:            "Electronic Warfare",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Electronic Warfare is the basis of military signals intelligence. It governs the encoding, disruption, spoofing, and decoding of communication systems. Providing the user has the proper equipment, the skill can be used to manipulate or even take over the signal of any item's communication system. See Using Electronic Warfare, p. 226.",
		CanDefault:      false,
		SkillGroup:      "Cracking",
		Specializations: []string{"Communications", "Encryption", "Jamming", "Sensor Operations"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"first_aid": {
		Name:            "First Aid",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "First Aid is the ability to provide emergency medical assistance similar to that of a paramedic. This skill may be used to stabilize wounds and prevent characters from dying. First Aid cannot be used to perform surgery or repair damaged implants. For more information, see Healing, p. 205.",
		CanDefault:      true,
		SkillGroup:      "Biotech",
		Specializations: []string{"By treatment (Gunshot Wounds, Resuscitation, Broken Bones, Burns, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"forgery": {
		Name:            "Forgery",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Forgery is used to produce counterfeit items or alter existing items to a specific purpose. Depending on the type of forgery, the forger may need specific tools or schematics to complete the task. See Using Forgery, p. 145.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Counterfeiting", "Credstick Forgery", "False ID", "Image Doctoring", "Paper Forgery"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"hacking": {
		Name:            "Hacking",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Hacking is used to discover and exploit security flaws in computers and other electronics. For more on how Hacking is used, see Using Hacking, p. 226.",
		CanDefault:      true,
		SkillGroup:      "Cracking",
		Specializations: []string{"Devices", "Files", "Hosts", "Personas"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"hardware": {
		Name:            "Hardware",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Hardware reflects a characters ability to build and repair electronic devices. A workspace, proper materials, and sufficient build time are required to enact a repair or to build a new device. See Building & Repairing, at right.",
		CanDefault:      false,
		SkillGroup:      "Electronics",
		Specializations: []string{"By hardware type (Commlinks, Cyberdecks, Smartguns, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"industrial_mechanic": {
		Name:            "Industrial Mechanic",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "An industrial mechanic is tasked with repairing or modifying large-scale machines, such as assembly line equipment, power generators, HVAC units, industrial robots, etc. See Building and Repairing, at right.",
		CanDefault:      false,
		SkillGroup:      "Engineering",
		Specializations: []string{"Electrical Power Systems", "Hydraulics", "HVAC", "Industrial Robotics", "Structural", "Welding"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"locksmith": {
		Name:            "Locksmith",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeAgility,
		Description:     "This skill covers building, repairing, and opening mechanical and electronic locks. While largely banished to antiquity, traditional mechanical locking mechanisms are still in use around the globe, often as throwbacks or backups. Electronic locks are far more common and quite susceptible to your ministrations. See Doors, Windows, & Locks, p. 363.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{"By type (Combination, Keypad, Maglock, Tumbler, Voice Recognition, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"medicine": {
		Name:            "Medicine",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Medicine is used to perform advanced medical procedures such as surgeries. It includes long-term medical support for disease and illness, and the skill can be used to diagnose a character's medical condition. This skill is used to implant or remove cybernetics and bioware but cannot be used to repair or maintain implanted devices. For more information, see Healing, p. 205.",
		CanDefault:      false,
		SkillGroup:      "Biotech",
		Specializations: []string{"Cosmetic Surgery", "Extended Care", "Implant Surgery", "Magical Health", "Organ Culture", "Trauma Surgery"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"nautical_mechanic": {
		Name:            "Nautical Mechanic",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Nautical Mechanic is concerned with the maintenance and repair of watercraft. This skill is only effective if the necessary equipment and time are available. See Building & Repairing below.",
		CanDefault:      false,
		SkillGroup:      "Engineering",
		Specializations: []string{"Motorboat", "Sailboat", "Ship", "Submarine"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"navigation": {
		Name:            "Navigation",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeIntuition,
		Description:     "Navigation governs the use of technology and natural instinct to navigate through territory. This skill enables characters to read maps, use GPS devices, follow AR nav points, or follow a course by landmarks or general direction sense. Navigation applies to both AR and non-AR-enhanced environments.",
		CanDefault:      true,
		SkillGroup:      "Outdoors",
		Specializations: []string{"Augmented Reality Markers", "Celestial", "Compass", "Maps", "GPS"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"software": {
		Name:            "Software",
		Type:            SkillTypeActive,
		Category:        SkillCategoryTechnical,
		LinkedAttribute: AttributeLogic,
		Description:     "Software is the skill used to create and manipulate programming in the Matrix. See Using Software, p. 226. It's also what technomancers use when they create their complex forms (Threading, p. 251).",
		CanDefault:      false,
		SkillGroup:      "Electronics",
		Specializations: []string{"Data Bombs or by complex form (Editor, Resonance Spike, Tattletale, etc.)"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	// Vehicle Skills
	"gunnery": {
		Name:            "Gunnery",
		Type:            SkillTypeActive,
		Category:        SkillCategoryVehicle,
		LinkedAttribute: AttributeAgility,
		Description:     "Gunnery is used when firing any vehicle-mounted weapon, regardless of how or where the weapon is mounted. This skill extends to manual and sensor-enhanced gunnery.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Artillery", "Ballistic", "Energy", "Guided Missile", "Rocket"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"pilot_aerospace": {
		Name:            "Pilot Aerospace",
		Type:            SkillTypeActive,
		Category:        SkillCategoryVehicle,
		LinkedAttribute: AttributeReaction,
		Description:     "Aerospace vehicles include all reduced- and zero-gravity aircraft capable of suborbital or extra-orbital flight.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{"Deep Space", "Launch Craft", "Remote Operation", "Semiballistic", "Suborbital"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"pilot_aircraft": {
		Name:            "Pilot Aircraft",
		Type:            SkillTypeActive,
		Category:        SkillCategoryVehicle,
		LinkedAttribute: AttributeReaction,
		Description:     "This skill is used to pilot any manned or unmanned aircraft operating solely within planetary atmosphere.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{"Fixed-Wing", "Lighter-Than-Air", "Remote Operation", "Rotary Wing", "Tilt Wing", "Vectored Thrust"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"pilot_walker": {
		Name:            "Pilot Walker",
		Type:            SkillTypeActive,
		Category:        SkillCategoryVehicle,
		LinkedAttribute: AttributeReaction,
		Description:     "Any vehicle that walks on two or more legs is piloted through this skill. Characters may control the walker physically or remotely.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{"Biped", "Multiped", "Quadruped", "Remote"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"pilot_exotic_vehicle": {
		Name:            "Pilot Exotic Vehicle",
		Type:            SkillTypeActive,
		Category:        SkillCategoryVehicle,
		LinkedAttribute: AttributeReaction,
		Description:     "Characters must take this skill one time for each specific exotic vehicle. Characters may control the vehicle remotely with this skill where possible.",
		CanDefault:      false,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"pilot_ground_craft": {
		Name:            "Pilot Ground Craft",
		Type:            SkillTypeActive,
		Category:        SkillCategoryVehicle,
		LinkedAttribute: AttributeReaction,
		Description:     "This skill is used to pilot any ground-based vehicle, excluding legged vehicles. This skill applies whether the pilot is in the vehicle or controlling the vehicle via remote access.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Bike", "Hovercraft", "Remote Operation", "Tracked", "Wheeled"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"pilot_watercraft": {
		Name:            "Pilot Watercraft",
		Type:            SkillTypeActive,
		Category:        SkillCategoryVehicle,
		LinkedAttribute: AttributeReaction,
		Description:     "This skill is used to pilot any waterborne vehicle, whether from inside it or by remote control.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Hydrofoil", "Motorboat", "Remote Operation", "Sail", "Ship", "Submarine"},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
}