package v5

// DataCategories contains armor categories keyed by category name
var DataCategories = map[string]Category{
	"Armor": {
		Name:        "Armor",
		BlackMarket: "Armor",
	},
	"Clothing": {
		Name:        "Clothing",
		BlackMarket: "Armor",
	},
	"Cloaks": {
		Name:        "Cloaks",
		BlackMarket: "Armor",
	},
	"High-Fashion Armor Clothing": {
		Name:        "High-Fashion Armor Clothing",
		BlackMarket: "Armor",
	},
	"Specialty Armor": {
		Name:        "Specialty Armor",
		BlackMarket: "Armor",
	},
}

// DataModCategories contains armor mod categories keyed by category name
var DataModCategories = map[string]Category{
	"Customized Ballistic Mask": {
		Name:        "Customized Ballistic Mask",
		BlackMarket: "Armor",
	},
	"Full Body Armor Mods": {
		Name:        "Full Body Armor Mods",
		BlackMarket: "Armor",
	},
	"General": {
		Name:        "General",
		BlackMarket: "Armor,Electronics,Magic,Software",
	},
	"Globetrotter Clothing Liners": {
		Name:        "Globetrotter Clothing Liners",
		BlackMarket: "Armor",
	},
	"Globetrotter Jacket Liners": {
		Name:        "Globetrotter Jacket Liners",
		BlackMarket: "Armor",
	},
	"Globetrotter Vest Liners": {
		Name:        "Globetrotter Vest Liners",
		BlackMarket: "Armor",
	},
	"Nightshade IR": {
		Name:        "Nightshade IR",
		BlackMarket: "Armor",
	},
	"Rapid Transit Detailing": {
		Name:        "Rapid Transit Detailing",
		BlackMarket: "Armor",
	},
	"Urban Explorer Jumpsuit Accessories": {
		Name:        "Urban Explorer Jumpsuit Accessories",
		BlackMarket: "Armor",
	},
	"Victory Liners": {
		Name:        "Victory Liners",
		BlackMarket: "Armor",
	},
}

// DataArmors contains armor records keyed by their ID (lowercase with underscores)
var DataArmors = map[string]Armor{
	"clothing": {
		Name:          "Clothing",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "Variable(20-100000)",
		Source:        "SR5",
	},
	"actioneer_business_clothes": {
		Name:          "Actioneer Business Clothes",
		Category:      "Armor",
		Armor:         "8",
		ArmorCapacity: "8",
		Avail:         "8",
		Cost:          "1500",
		Source:        "SR5",
		Gears: &Gears{
			UseGear: []string{"concealable_holster"},
		},
	},
	"armor_clothing": {
		Name:          "Armor Clothing",
		Category:      "Armor",
		Armor:         "6",
		ArmorCapacity: "6",
		Avail:         "2",
		Cost:          "450",
		Source:        "SR5",
	},
	"armor_jacket": {
		Name:          "Armor Jacket",
		Category:      "Armor",
		Armor:         "12",
		ArmorCapacity: "12",
		Avail:         "2",
		Cost:          "1000",
		Source:        "SR5",
	},
	"armor_vest": {
		Name:          "Armor Vest",
		Category:      "Armor",
		Armor:         "9",
		ArmorCapacity: "9",
		Avail:         "4",
		Cost:          "500",
		Source:        "SR5",
	},
	"chameleon_suit": {
		Name:          "Chameleon Suit",
		Category:      "Armor",
		Armor:         "9",
		ArmorCapacity: "9",
		Avail:         "10R",
		Cost:          "1700",
		Source:        "SR5",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "2", Condition: "LimitCondition_SkillsActiveSneakingVisible",
			},
		},
	},
	"full_body_armor": {
		Name:           "Full Body Armor",
		Category:       "Armor",
		Armor:          "15",
		ArmorCapacity:  "15",
		Avail:          "14R",
		Cost:           "2000",
		Source:         "SR5",
		AddModCategory: "Full Body Armor Mods",
	},
	"lined_coat": {
		Name:          "Lined Coat",
		Category:      "Armor",
		Armor:         "9",
		ArmorCapacity: "9",
		Avail:         "4",
		Cost:          "900",
		Source:        "SR5",
	},
	"urban_explorer_jumpsuit": {
		Name:           "Urban Explorer Jumpsuit",
		Category:       "Armor",
		Armor:          "9",
		ArmorCapacity:  "9",
		Avail:          "8",
		Cost:           "650",
		Source:         "SR5",
		AddModCategory: "Urban Explorer Jumpsuit Accessories",
		Gears: &Gears{
			UseGear: []string{"Biomonitor", "Music Player"},
		},
	},
	"helmet": {
		Name:          "Helmet",
		Category:      "Armor",
		Armor:         "+2",
		ArmorCapacity: "6",
		Avail:         "2",
		Cost:          "100",
		Source:        "SR5",
	},
	"ballistic_shield": {
		Name:          "Ballistic Shield",
		Category:      "Armor",
		Armor:         "+6",
		ArmorCapacity: "6",
		Avail:         "12R",
		Cost:          "1200",
		Source:        "SR5",
		AddWeapon:     "Ballistic Shield",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "-1", Condition: "LimitCondition_ShieldPhysicalPenalty",
			},
		},
	},
	"riot_shield": {
		Name:          "Riot Shield",
		Category:      "Armor",
		Armor:         "+6",
		ArmorCapacity: "6",
		Avail:         "10R",
		Cost:          "1500",
		Source:        "SR5",
		AddWeapon:     "Riot Shield",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "-1", Condition: "LimitCondition_ShieldPhysicalPenalty",
			},
		},
	},
	"armanté_suit": {
		Name:          "Armanté Suit",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "4",
		Avail:         "10",
		Cost:          "2500",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
	},
	"armanté_dress": {
		Name:          "Armanté Dress",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "4",
		Avail:         "10",
		Cost:          "2500",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
	},
	"mortimer_of_london_berwick_suit": {
		Name:          "Mortimer of London: Berwick Suit",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "9",
		ArmorCapacity: "5",
		Avail:         "9",
		Cost:          "2600",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Concealability"},
		},
	},
	"mortimer_of_london_berwick_dress": {
		Name:          "Mortimer of London: Berwick Dress",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "4",
		Avail:         "8",
		Cost:          "2300",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Concealability"},
		},
	},
	"mortimer_of_london_crimson_sky_suit": {
		Name:          "Mortimer of London: Crimson Sky Suit",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "5",
		Avail:         "6",
		Cost:          "2400",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Concealability"},
		},
	},
	"mortimer_of_london_summit_suit": {
		Name:          "Mortimer of London: Summit Suit",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "6",
		Avail:         "7",
		Cost:          "2500",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Concealability"},
		},
	},
	"mortimer_of_london_summit_dress": {
		Name:          "Mortimer of London: Summit Dress",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "7",
		ArmorCapacity: "5",
		Avail:         "7",
		Cost:          "2200",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Concealability"},
		},
	},
	"mortimer_of_london_greatcoat_coat": {
		Name:          "Mortimer of London: Greatcoat Coat",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "10",
		ArmorCapacity: "10",
		Avail:         "8",
		Cost:          "3000",
		Source:        "RG",
		ArmorOverride: "+3",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit (Stack)", "Concealability"},
		},
	},
	"mortimer_of_london_ulysses_coat": {
		Name:          "Mortimer of London: Ulysses Coat",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "10",
		ArmorCapacity: "12",
		Avail:         "8",
		Cost:          "3100",
		Source:        "RG",
		ArmorOverride: "+3",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit (Stack)", "Concealability"},
		},
	},
	"mortimer_of_london_argentum_coat": {
		Name:          "Mortimer of London: Argentum Coat",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "12",
		ArmorCapacity: "14",
		Avail:         "10",
		Cost:          "3600",
		Source:        "RG",
		ArmorOverride: "+4",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit (Stack)", "Concealability"},
		},
	},
	"vashon_island_ace_of_cups": {
		Name:          "Vashon Island: Ace of Cups",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "9",
		ArmorCapacity: "8",
		Avail:         "6",
		Cost:          "1600",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
	},
	"vashon_island_ace_of_swords": {
		Name:          "Vashon Island: Ace of Swords",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "7",
		ArmorCapacity: "8",
		Avail:         "6",
		Cost:          "1300",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
	},
	"vashon_island_ace_of_wands": {
		Name:          "Vashon Island: Ace of Wands",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "6",
		ArmorCapacity: "8",
		Avail:         "6",
		Cost:          "1200",
		Source:        "RG",
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: "Gear Access",
		},
	},
	"vashon_island_ace_of_coins": {
		Name:          "Vashon Island: Ace of Coins",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "7",
		ArmorCapacity: "10",
		Avail:         "4",
		Cost:          "2100",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "3", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
	},
	"vashon_island_ace_of_spades": {
		Name:          "Vashon Island: Ace of Spades",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "7",
		ArmorCapacity: "6",
		Avail:         "6",
		Cost:          "1000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
	},
	"vashon_island_ace_of_clubs": {
		Name:          "Vashon Island: Ace of Clubs",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "7",
		ArmorCapacity: "6",
		Avail:         "6",
		Cost:          "1000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
	},
	"vashon_island_ace_of_hearts": {
		Name:          "Vashon Island: Ace of Hearts",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "7",
		ArmorCapacity: "6",
		Avail:         "6",
		Cost:          "1000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
	},
	"vashon_island_ace_of_diamonds": {
		Name:          "Vashon Island: Ace of Diamonds",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "6",
		Avail:         "8",
		Cost:          "1400",
		Source:        "RG",
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: "Concealability",
		},
	},
	"vashon_island_steampunk": {
		Name:          "Vashon Island: Steampunk",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "10",
		ArmorCapacity: "14",
		Avail:         "7",
		Cost:          "2250",
		Source:        "RG",
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"vashon_island_synergist_business_line": {
		Name:          "Vashon Island: Synergist Business Line",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "9",
		ArmorCapacity: "5",
		Avail:         "8",
		Cost:          "1500",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"vashon_island_synergist_business_line_longcoat": {
		Name:          "Vashon Island: Synergist Business Line Longcoat",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "10",
		ArmorCapacity: "6",
		Avail:         "8",
		Cost:          "2300",
		Source:        "RG",
		ArmorOverride: "+3",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: "Custom Fit (Stack)",
		},
	},
	"vashon_island_sleeping_tiger": {
		Name:          "Vashon Island: Sleeping Tiger",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "13",
		ArmorCapacity: "10",
		Avail:         "10",
		Cost:          "13500",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Newest Model", ModNameEntry{
				Content: "Ruthenium Polymer Coating", Rating: "3",
			}},
		},
	},
	"zoé_executive_suite": {
		Name:          "Zoé: Executive Suite",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "12",
		ArmorCapacity: "4",
		Avail:         "12",
		Cost:          "2000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Newest Model"},
		},
	},
	"zoé_heritage_4": {
		Name:          "Zoé: Heritage 4",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "4",
		ArmorCapacity: "2",
		Avail:         "16",
		Cost:          "4000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Newest Model"},
		},
	},
	"zoé_heritage_6": {
		Name:          "Zoé: Heritage 6",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "6",
		ArmorCapacity: "3",
		Avail:         "16",
		Cost:          "5000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Newest Model"},
		},
	},
	"zoé_heritage_8": {
		Name:          "Zoé: Heritage 8",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "4",
		Avail:         "16",
		Cost:          "6000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Newest Model"},
		},
	},
	"zoé_heritage_10": {
		Name:          "Zoé: Heritage 10",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "10",
		ArmorCapacity: "5",
		Avail:         "16",
		Cost:          "7000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Newest Model"},
		},
	},
	"zoé_heritage_12": {
		Name:          "Zoé: Heritage 12",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "12",
		ArmorCapacity: "6",
		Avail:         "16",
		Cost:          "8000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Newest Model"},
		},
	},
	"zoé_nightshademoonsilver": {
		Name:           "Zoé: Nightshade/Moonsilver",
		Category:       "High-Fashion Armor Clothing",
		Armor:          "7",
		ArmorCapacity:  "2",
		Avail:          "10",
		Cost:           "8500",
		Source:         "RG",
		AddModCategory: "Nightshade IR",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"zoé_second_skin": {
		Name:          "Zoé: Second Skin",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "6",
		ArmorCapacity: "2",
		Avail:         "14",
		Cost:          "12000",
		Source:        "RG",
		ArmorOverride: "+2",
		Mods: &Mods{
			Name: []interface{}{"Custom Fit (Stack)", "Newest Model", ModNameEntry{
				Content: "Ruthenium Polymer Coating", Rating: "4",
			}},
		},
	},
	"ares_victory_globetrotter_jacket": {
		Name:          "Ares Victory: Globetrotter Jacket",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "12",
		ArmorCapacity: "10",
		Avail:         "10",
		Cost:          "1300",
		Source:        "RG",
		SelectModsFromCategory: &SelectModsCategory{
			Category: "Globetrotter Jacket Liners",
		},
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			SpecificSkill: SkillCategoryBonus{
				Name: "Survival", Bonus: 1,
			},
		},
	},
	"ares_victory_globetrotter_vest": {
		Name:          "Ares Victory: Globetrotter Vest",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "9",
		ArmorCapacity: "10",
		Avail:         "7",
		Cost:          "900",
		Source:        "RG",
		SelectModsFromCategory: &SelectModsCategory{
			Category: "Globetrotter Vest Liners",
		},
		WirelessBonus: &Bonus{
			SpecificSkill: SkillCategoryBonus{
				Name: "Survival", Bonus: 1,
			},
		},
	},
	"ares_victory_globetrotter_clothing": {
		Name:          "Ares Victory: Globetrotter Clothing",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "7",
		ArmorCapacity: "10",
		Avail:         "6",
		Cost:          "600",
		Source:        "RG",
		SelectModsFromCategory: &SelectModsCategory{
			Category: "Globetrotter Clothing Liners",
		},
		WirelessBonus: &Bonus{
			SpecificSkill: SkillCategoryBonus{
				Name: "Survival", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: "Gear Access",
		},
	},
	"ares_victory_wild_hunt": {
		Name:          "Ares Victory: Wild Hunt",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "12",
		ArmorCapacity: "10",
		Avail:         "12",
		Cost:          "3000",
		Source:        "RG",
		SelectModsFromCategory: &SelectModsCategory{
			Category: "Victory Liners",
		},
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			SpecificSkill: SkillCategoryBonus{
				Name: "Survival", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: "Gear Access",
		},
	},
	"ares_victory_industrious": {
		Name:          "Ares Victory: Industrious",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "9",
		ArmorCapacity: "6",
		Avail:         "6",
		Cost:          "1100",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_CorporationVisible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social Active", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: "Gear Access",
		},
	},
	"ares_victory_big_game_hunter": {
		Name:          "Ares Victory: Big Game Hunter",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "14",
		ArmorCapacity: "12",
		Avail:         "12",
		Cost:          "5000",
		Source:        "RG",
		SelectModsFromCategory: &SelectModsCategory{
			Category: "Victory Liners",
		},
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		WirelessBonus: &Bonus{
			SpecificSkill: SkillCategoryBonus{
				Name: "Survival", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Gear Access"},
		},
	},
	"ares_victory_rapid_transit": {
		Name:           "Ares Victory: Rapid Transit",
		Category:       "High-Fashion Armor Clothing",
		Armor:          "9",
		ArmorCapacity:  "6",
		Avail:          "10",
		Cost:           "400",
		Source:         "RG",
		AddModCategory: "Rapid Transit Detailing",
	},
	"form_fitting_body_armor": {
		Name:          "Form-Fitting Body Armor",
		Category:      "Specialty Armor",
		Armor:         "8",
		ArmorCapacity: "3",
		Avail:         "8",
		Cost:          "1300",
		Source:        "RG",
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Concealability"},
		},
	},
	"hardened_mil_spec_battle_armor_light": {
		Name:          "Hardened Mil-Spec Battle Armor: Light",
		Category:      "Specialty Armor",
		Armor:         "15",
		ArmorCapacity: "15",
		Avail:         "16F",
		Cost:          "15000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Gear Access", "Restrictive"},
		},
	},
	"hardened_mil_spec_battle_armor_medium": {
		Name:          "Hardened Mil-Spec Battle Armor: Medium",
		Category:      "Specialty Armor",
		Armor:         "18",
		ArmorCapacity: "18",
		Avail:         "18F",
		Cost:          "20000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Gear Access", "Restrictive"},
		},
	},
	"hardened_mil_spec_battle_armor_heavy": {
		Name:          "Hardened Mil-Spec Battle Armor: Heavy",
		Category:      "Specialty Armor",
		Armor:         "20",
		ArmorCapacity: "20",
		Avail:         "22F",
		Cost:          "25000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Gear Access", "Restrictive"},
		},
	},
	"hardened_mil_spec_battle_armor_helmet": {
		Name:          "Hardened Mil-Spec Battle Armor: Helmet",
		Category:      "Specialty Armor",
		Armor:         "+3",
		ArmorCapacity: "8",
		Avail:         "8F",
		Cost:          "10000",
		Source:        "RG",
	},
	"security_armor_light": {
		Name:          "Security Armor: Light",
		Category:      "Specialty Armor",
		Armor:         "15",
		ArmorCapacity: "12",
		Avail:         "14R",
		Cost:          "8000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Gear Access", "Restrictive"},
		},
	},
	"security_armor_medium": {
		Name:          "Security Armor: Medium",
		Category:      "Specialty Armor",
		Armor:         "18",
		ArmorCapacity: "14",
		Avail:         "16R",
		Cost:          "14000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Gear Access", "Restrictive"},
		},
	},
	"security_armor_heavy": {
		Name:          "Security Armor: Heavy",
		Category:      "Specialty Armor",
		Armor:         "20",
		ArmorCapacity: "16",
		Avail:         "18R",
		Cost:          "20000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Gear Access", "Restrictive"},
		},
	},
	"security_armor_helmet": {
		Name:          "Security Armor: Helmet",
		Category:      "Specialty Armor",
		Armor:         "+3",
		ArmorCapacity: "5",
		Avail:         "8R",
		Cost:          "5000",
		Source:        "RG",
	},
	"bike_racing_armor": {
		Name:          "Bike Racing Armor",
		Category:      "Specialty Armor",
		Armor:         "8",
		ArmorCapacity: "8",
		Avail:         "6",
		Cost:          "500",
		Source:        "RG",
	},
	"bike_racing_helmet": {
		Name:          "Bike Racing Helmet",
		Category:      "Specialty Armor",
		Armor:         "+2",
		ArmorCapacity: "6",
		Avail:         "6",
		Cost:          "200",
		Source:        "RG",
	},
	"bunker_gear": {
		Name:          "Bunker Gear",
		Category:      "Specialty Armor",
		Armor:         "6",
		ArmorCapacity: "6",
		Avail:         "6",
		Cost:          "3000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_BunkerGearVisible",
			},
		},
		WirelessBonus: &Bonus{
			SkillCategory: SkillCategoryBonus{
				Name: "Social", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: []interface{}{ModNameEntry{
				Content: "Fire Resistance", Rating: "8",
			}, "Restrictive"},
		},
	},
	"bunker_gear_helmet": {
		Name:          "Bunker Gear Helmet",
		Category:      "Specialty Armor",
		Armor:         "+2",
		ArmorCapacity: "3",
		Avail:         "6",
		Cost:          "750",
		Source:        "RG",
	},
	"riot_control_armor": {
		Name:          "Riot Control Armor",
		Category:      "Specialty Armor",
		Armor:         "14",
		ArmorCapacity: "8",
		Avail:         "10R",
		Cost:          "5000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Padded", "Restrictive"},
		},
	},
	"riot_control_helmet": {
		Name:          "Riot Control Helmet",
		Category:      "Specialty Armor",
		Armor:         "+2",
		ArmorCapacity: "6",
		Avail:         "6R",
		Cost:          "1000",
		Source:        "RG",
	},
	"swat_armor": {
		Name:          "SWAT Armor",
		Category:      "Specialty Armor",
		Armor:         "15",
		ArmorCapacity: "15",
		Avail:         "16R",
		Cost:          "8000",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: []interface{}{LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_IntimidationVisible",
			}, LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_ExcludeIntimidationVisible",
			}},
		},
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "3", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		Mods: &Mods{
			Name: "Gear Access",
		},
	},
	"swat_helmet": {
		Name:          "SWAT Helmet",
		Category:      "Specialty Armor",
		Armor:         "+3",
		ArmorCapacity: "8",
		Avail:         "10R",
		Cost:          "1500",
		Source:        "RG",
	},
	"securetech_ppp_arms_kit": {
		Name:          "Securetech PPP: Arms Kit",
		Category:      "Specialty Armor",
		Armor:         "+1",
		ArmorCapacity: "1",
		Avail:         "6",
		Cost:          "250",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_Visible",
			},
		},
	},
	"securetech_ppp_legs_kit": {
		Name:          "Securetech PPP: Legs Kit",
		Category:      "Specialty Armor",
		Armor:         "+1",
		ArmorCapacity: "1",
		Avail:         "6",
		Cost:          "300",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_Visible",
			},
		},
	},
	"securetech_ppp_vitals_kit": {
		Name:          "Securetech PPP: Vitals Kit",
		Category:      "Specialty Armor",
		Armor:         "+1",
		ArmorCapacity: "1",
		Avail:         "6",
		Cost:          "350",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_Visible",
			},
		},
	},
	"body_armor_bag": {
		Name:          "Body Armor Bag",
		Category:      "Specialty Armor",
		Armor:         "8",
		ArmorCapacity: "4",
		Avail:         "8",
		Cost:          "750",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Concealability", "Restrictive"},
		},
	},
	"chain_mail": {
		Name:          "Chain Mail",
		Category:      "Specialty Armor",
		Armor:         "8",
		ArmorCapacity: "2",
		Avail:         "8",
		Cost:          "900",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: []interface{}{LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_PublicVisible",
			}, LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_GangVisible",
			}},
		},
	},
	"padded_leather": {
		Name:          "Padded Leather",
		Category:      "Specialty Armor",
		Armor:         "7",
		ArmorCapacity: "2",
		Avail:         "8",
		Cost:          "600",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: []interface{}{LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_PublicVisible",
			}, LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_GangVisible",
			}},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Padded"},
		},
	},
	"ares_flashield": {
		Name:          "Ares FlaShield",
		Category:      "Specialty Armor",
		Armor:         "+6",
		ArmorCapacity: "4",
		Avail:         "12R",
		Cost:          "4000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Grenade: Flash-Pak"},
		},
	},
	"murder_armor": {
		Name:          "Murder Armor",
		Category:      "Specialty Armor",
		Armor:         "13",
		ArmorCapacity: "4",
		Avail:         "12R",
		Cost:          "5000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Biomonitor", "Holster"},
		},
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"forearm_guards": {
		Name:          "Forearm Guards",
		Category:      "Specialty Armor",
		Armor:         "+1",
		ArmorCapacity: "3",
		Avail:         "6",
		Cost:          "300",
		Source:        "RG",
	},
	"ballistic_mask": {
		Name:           "Ballistic Mask",
		Category:       "Specialty Armor",
		Armor:          "+2",
		ArmorCapacity:  "8",
		Avail:          "6",
		Cost:           "150",
		Source:         "RG",
		AddModCategory: "Ballistic Mask",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_IntimidationVisible",
			},
		},
	},
	"custom_ballistic_mask": {
		Name:           "Custom Ballistic Mask",
		Category:       "Specialty Armor",
		Armor:          "+2",
		ArmorCapacity:  "8",
		Avail:          "6",
		Cost:           "300",
		Source:         "RG",
		AddModCategory: "Ballistic Mask",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_IntimidationVisible",
			},
		},
	},
	"ghillie_suit": {
		Name:          "Ghillie Suit",
		Category:      "Specialty Armor",
		Armor:         "4",
		ArmorCapacity: "4",
		Avail:         "6",
		Cost:          "600",
		Source:        "RG",
		Mods: &Mods{
			Name: "Restrictive",
		},
	},
	"ares_armored_survivalist": {
		Name:          "Ares Armored Survivalist",
		Category:      "Specialty Armor",
		Armor:         "8",
		ArmorCapacity: "6",
		Avail:         "10",
		Cost:          "1500",
		Source:        "RG",
		SelectModsFromCategory: &SelectModsCategory{
			Category: "Globetrotter Jacket Liners",
		},
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_Visible",
			},
		},
		WirelessBonus: &Bonus{
			SpecificSkill: SkillCategoryBonus{
				Name: "Survival", Bonus: 1,
			},
		},
	},
	"desert_suit": {
		Name:          "Desert Suit",
		Category:      "Specialty Armor",
		Armor:         "3",
		ArmorCapacity: "2",
		Avail:         "8",
		Cost:          "1000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Flare Compensation"},
		},
		WirelessBonus: &Bonus{
			SpecificSkill: SkillCategoryBonus{
				Name: "Survival", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"snake_mesh_socks": {
		Name:          "Snake Mesh Socks",
		Category:      "Specialty Armor",
		Armor:         "+2",
		ArmorCapacity: "0",
		Avail:         "6",
		Cost:          "50",
		Source:        "RG",
	},
	"coldsuit": {
		Name:          "Coldsuit",
		Category:      "Specialty Armor",
		Armor:         "0",
		ArmorCapacity: "4",
		Avail:         "4",
		Cost:          "800",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Flare Compensation"},
		},
		WirelessBonus: &Bonus{
			SpecificSkill: SkillCategoryBonus{
				Name: "Survival", Bonus: 1,
			},
		},
		Mods: &Mods{
			Name: ModNameEntry{
				Content: "Insulation", Rating: "4",
			},
		},
	},
	"polar_survival_suit": {
		Name:          "Polar Survival Suit",
		Category:      "Specialty Armor",
		Armor:         "6",
		ArmorCapacity: "6",
		Avail:         "8",
		Cost:          "2000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Flare Compensation"},
		},
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "1", Condition: "LimitCondition_ClimbingTests",
			},
		},
		Mods: &Mods{
			Name: []interface{}{ModNameEntry{
				Content: "Insulation", Rating: "6",
			}, ModNameEntry{
				Content: "Thermal Damping", Rating: "4",
			}},
		},
	},
	"ares_arctic_forces_suit": {
		Name:          "Ares Arctic Forces Suit",
		Category:      "Specialty Armor",
		Armor:         "15",
		ArmorCapacity: "14",
		Avail:         "16R",
		Cost:          "11000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Gas Mask", "Flare Compensation"},
		},
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "1", Condition: "LimitCondition_SkillsActiveGymnasticsClimbing",
			},
		},
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "1", Condition: "LimitCondition_ClimbingTests",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", ModNameEntry{
				Content: "Insulation", Rating: "5",
			}, ModNameEntry{
				Content: "Thermal Damping", Rating: "4",
			}, "Gear Access"},
		},
	},
	"ares_armored_coldsuit": {
		Name:          "Ares Armored Coldsuit",
		Category:      "Specialty Armor",
		Armor:         "9",
		ArmorCapacity: "6",
		Avail:         "6",
		Cost:          "1200",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Flare Compensation"},
		},
		Bonus: &Bonus{
			FatigueResist: "-2",
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", ModNameEntry{
				Content: "Insulation", Rating: "4",
			}, "Restrictive"},
		},
	},
	"ares_polar_sneak_suit": {
		Name:          "Ares Polar Sneak Suit",
		Category:      "Specialty Armor",
		Armor:         "6",
		ArmorCapacity: "4",
		Avail:         "16F",
		Cost:          "10000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Flare Compensation"},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", ModNameEntry{
				Content: "Ruthenium Polymer Coating", Rating: "3",
			}},
		},
	},
	"enclosed_breathing_helmet": {
		Name:          "Enclosed Breathing Helmet",
		Category:      "Specialty Armor",
		Armor:         "+0",
		ArmorCapacity: "6",
		Avail:         "8",
		Cost:          "900",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Low Light"},
		},
	},
	"full_face_mask": {
		Name:          "Full Face Mask",
		Category:      "Specialty Armor",
		Armor:         "+0",
		ArmorCapacity: "4",
		Avail:         "8",
		Cost:          "300",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Gas Mask"},
		},
	},
	"drysuit": {
		Name:          "Drysuit",
		Category:      "Specialty Armor",
		Armor:         "+0",
		ArmorCapacity: "4",
		Avail:         "6",
		Cost:          "2500",
		Source:        "RG",
		Mods: &Mods{
			Name: []interface{}{"Chemical Seal", ModNameEntry{
				Content: "Insulation", Rating: "4",
			}},
		},
	},
	"diving_armor": {
		Name:          "Diving Armor",
		Category:      "Specialty Armor",
		Armor:         "7",
		ArmorCapacity: "4",
		Avail:         "6",
		Cost:          "1750",
		Source:        "RG",
		Mods: &Mods{
			Name: ModNameEntry{
				Content: "Chemical Protection", Rating: "4",
			},
		},
	},
	"arctic_diving_suit": {
		Name:          "Arctic Diving Suit",
		Category:      "Specialty Armor",
		Armor:         "1",
		ArmorCapacity: "4",
		Avail:         "8",
		Cost:          "3000",
		Source:        "RG",
		Mods: &Mods{
			Name: ModNameEntry{
				Content: "Insulation", Rating: "8",
			},
		},
	},
	"evo_hel_suit": {
		Name:          "Evo HEL Suit",
		Category:      "Specialty Armor",
		Armor:         "8",
		ArmorCapacity: "5",
		Avail:         "10",
		Cost:          "3000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Gas Mask"},
		},
		Mods: &Mods{
			Name: []interface{}{ModNameEntry{
				Content: "Insulation", Rating: "4",
			}, ModNameEntry{
				Content: "Fire Resistance", Rating: "2",
			}, ModNameEntry{
				Content: "Radiation Shielding", Rating: "3",
			}, ModNameEntry{
				Content: "Chemical Protection", Rating: "2",
			}, "Custom Fit"},
		},
	},
	"spacesuit": {
		Name:          "Spacesuit",
		Category:      "Specialty Armor",
		Armor:         "12",
		ArmorCapacity: "6",
		Avail:         "16",
		Cost:          "12000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Renraku Sensei", "Flare Compensation", "Biomonitor"},
		},
		Mods: &Mods{
			Name: []interface{}{"Chemical Seal", ModNameEntry{
				Content: "Insulation", Rating: "6",
			}, ModNameEntry{
				Content: "Thermal Damping", Rating: "4",
			}, "Custom Fit"},
		},
	},
	"security_spacesuit": {
		Name:          "Security Spacesuit",
		Category:      "Specialty Armor",
		Armor:         "15",
		ArmorCapacity: "10",
		Avail:         "24",
		Cost:          "25000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Renraku Sensei", "Flare Compensation", "Biomonitor"},
		},
		Mods: &Mods{
			Name: []interface{}{"Chemical Seal", ModNameEntry{
				Content: "Insulation", Rating: "6",
			}, ModNameEntry{
				Content: "Thermal Damping", Rating: "4",
			}, "Custom Fit"},
		},
	},
	"evo_armadillo_armored_spacesuit": {
		Name:          "Evo Armadillo Armored Spacesuit",
		Category:      "Specialty Armor",
		Armor:         "16",
		ArmorCapacity: "10",
		Avail:         "24R",
		Cost:          "35000",
		Source:        "RG",
		Gears: &Gears{
			UseGear: []string{"Renraku Sensei", "Biomonitor"},
		},
		Mods: &Mods{
			Name: []interface{}{"Chemical Seal", ModNameEntry{
				Content: "Insulation", Rating: "6",
			}, ModNameEntry{
				Content: "Fire Resistance", Rating: "4",
			}, ModNameEntry{
				Content: "Thermal Damping", Rating: "4",
			}, "Custom Fit"},
		},
	},
	"magnetic_boots": {
		Name:          "Magnetic Boots",
		Category:      "Specialty Armor",
		Armor:         "+0",
		ArmorCapacity: "4",
		Avail:         "12",
		Cost:          "2500",
		Source:        "RG",
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"survival_bubble_rating_1": {
		Name:          "Survival Bubble, Rating 1",
		Category:      "Specialty Armor",
		Armor:         "4",
		ArmorCapacity: "4",
		Avail:         "3",
		Cost:          "2000",
		Source:        "RG",
	},
	"survival_bubble_rating_2": {
		Name:          "Survival Bubble, Rating 2",
		Category:      "Specialty Armor",
		Armor:         "4",
		ArmorCapacity: "4",
		Avail:         "6",
		Cost:          "2000",
		Source:        "RG",
	},
	"survival_bubble_rating_3": {
		Name:          "Survival Bubble, Rating 3",
		Category:      "Specialty Armor",
		Armor:         "4",
		ArmorCapacity: "4",
		Avail:         "9",
		Cost:          "2000",
		Source:        "RG",
	},
	"survival_bubble_rating_4": {
		Name:          "Survival Bubble, Rating 4",
		Category:      "Specialty Armor",
		Armor:         "4",
		ArmorCapacity: "4",
		Avail:         "12",
		Cost:          "2000",
		Source:        "RG",
	},
	"survival_bubble_rating_5": {
		Name:          "Survival Bubble, Rating 5",
		Category:      "Specialty Armor",
		Armor:         "4",
		ArmorCapacity: "4",
		Avail:         "15",
		Cost:          "2000",
		Source:        "RG",
	},
	"survival_bubble_rating_6": {
		Name:          "Survival Bubble, Rating 6",
		Category:      "Specialty Armor",
		Armor:         "4",
		ArmorCapacity: "4",
		Avail:         "18",
		Cost:          "2000",
		Source:        "RG",
	},
	"mct_ee_suit": {
		Name:          "MCT EE Suit",
		Category:      "Specialty Armor",
		Armor:         "6",
		ArmorCapacity: "5",
		Avail:         "10",
		Cost:          "2500",
		Source:        "RG",
		Mods: &Mods{
			Name: []interface{}{"Chemical Seal", ModNameEntry{
				Content: "Fire Resistance", Rating: "4",
			}, ModNameEntry{
				Content: "Radiation Shielding", Rating: "6",
			}},
		},
	},
	"pneumatic_anti_shock_garments": {
		Name:          "Pneumatic Anti-Shock Garments",
		Category:      "Specialty Armor",
		Armor:         "3",
		ArmorCapacity: "4",
		Avail:         "6",
		Cost:          "500",
		Source:        "BB",
	},
	"shiawase_arms_simoom": {
		Name:          "Shiawase Arms Simoom",
		Category:      "Specialty Armor",
		Armor:         "+1",
		ArmorCapacity: "0",
		Avail:         "14R",
		Cost:          "1500",
		Source:        "HT",
		AddWeapon:     "Shiawase Arms Simoom",
	},
	"cloak": {
		Name:          "Cloak",
		Category:      "Cloaks",
		Armor:         "0",
		ArmorCapacity: "Rating",
		Avail:         "1",
		Cost:          "100 * Rating",
		Source:        "HT",
		Rating:        6,
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social",
				Value: "-1",
			},
		},
	},
	"designer_cloak": {
		Name:          "Designer Cloak",
		Category:      "Cloaks",
		Armor:         "0",
		ArmorCapacity: "Rating",
		Avail:         "1",
		Cost:          "(100 * Rating) + 300",
		Source:        "HT",
		Rating:        6,
	},
	"ruthenium_polymer_cloak": {
		Name:          "Ruthenium Polymer Cloak",
		Category:      "Cloaks",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "14F",
		Cost:          "4000 * Rating",
		Source:        "HT",
		Rating:        4,
	},
	"one_use_shoes": {
		Name:          "One-Use Shoes",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "2",
		Source:        "RF",
	},
	"one_use_pants": {
		Name:          "One-Use Pants",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "2",
		Source:        "RF",
	},
	"one_use_shirt": {
		Name:          "One-Use Shirt",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "2",
		Source:        "RF",
	},
	"one_use_skirt": {
		Name:          "One-Use Skirt",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "2",
		Source:        "RF",
	},
	"cheap_shoes": {
		Name:          "Cheap Shoes",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "RF",
	},
	"cheap_pants": {
		Name:          "Cheap Pants",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "RF",
	},
	"cheap_shirt": {
		Name:          "Cheap Shirt",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "RF",
	},
	"cheap_skirt": {
		Name:          "Cheap Skirt",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "RF",
	},
	"good_shoes": {
		Name:          "Good Shoes",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"good_pants": {
		Name:          "Good Pants",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"good_shirt": {
		Name:          "Good Shirt",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"good_skirt": {
		Name:          "Good Skirt",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"nice_shoes": {
		Name:          "Nice Shoes",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "200",
		Source:        "RF",
	},
	"nice_pants": {
		Name:          "Nice Pants",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "200",
		Source:        "RF",
	},
	"nice_shirt": {
		Name:          "Nice Shirt",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "200",
		Source:        "RF",
	},
	"nice_skirt": {
		Name:          "Nice Skirt",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "200",
		Source:        "RF",
	},
	"cheap_dress": {
		Name:          "Cheap Dress",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "200",
		Source:        "RF",
	},
	"cheap_suit": {
		Name:          "Cheap Suit",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "200",
		Source:        "RF",
	},
	"good_dress": {
		Name:          "Good Dress",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "4",
		Cost:          "1000",
		Source:        "RF",
	},
	"good_suit": {
		Name:          "Good Suit",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "4",
		Cost:          "1000",
		Source:        "RF",
	},
	"nice_dress": {
		Name:          "Nice Dress",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "8",
		Cost:          "10000",
		Source:        "RF",
	},
	"nice_suit": {
		Name:          "Nice Suit",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "8",
		Cost:          "10000",
		Source:        "RF",
	},
	"tuxedo_rental": {
		Name:          "Tuxedo Rental",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "75",
		Source:        "RF",
	},
	"hat": {
		Name:          "Hat",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "20",
		Source:        "RF",
	},
	"ski_mask": {
		Name:          "Ski Mask",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "5",
		Source:        "RF",
	},
	"coveralls": {
		Name:          "Coveralls",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"cheap_socks": {
		Name:          "Cheap Socks",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "2",
		Source:        "RF",
	},
	"cheap_undergarments": {
		Name:          "Cheap Undergarments",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "2",
		Source:        "RF",
	},
	"good_socks": {
		Name:          "Good Socks",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "RF",
	},
	"good_undergarments": {
		Name:          "Good Undergarments",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "RF",
	},
	"nice_socks": {
		Name:          "Nice Socks",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"nice_undergarments": {
		Name:          "Nice Undergarments",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"one_use_gloves": {
		Name:          "One-Use Gloves",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "2",
		Source:        "RF",
	},
	"cheap_gloves": {
		Name:          "Cheap Gloves",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "RF",
	},
	"cheap_watch": {
		Name:          "Cheap Watch",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "RF",
	},
	"cheap_jewelry": {
		Name:          "Cheap Jewelry",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "RF",
	},
	"good_gloves": {
		Name:          "Good Gloves",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"good_watch": {
		Name:          "Good Watch",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"good_jewelry": {
		Name:          "Good Jewelry",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "RF",
	},
	"nice_gloves": {
		Name:          "Nice Gloves",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "200",
		Source:        "RF",
	},
	"nice_watch": {
		Name:          "Nice Watch",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "200",
		Source:        "RF",
	},
	"nice_jewelry": {
		Name:          "Nice Jewelry",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "200",
		Source:        "RF",
	},
	"decent_diamond_ring": {
		Name:          "Decent Diamond Ring",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "500",
		Source:        "RF",
	},
	"large_diamond_ring": {
		Name:          "Large Diamond Ring",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "5000",
		Source:        "RF",
	},
	"sensor_collar": {
		Name:          "Sensor Collar",
		Category:      "Specialty Armor",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "2",
		Cost:          "200",
		Source:        "HS",
		Gears: &Gears{
			UseGear: []string{"Camera", "Microphone, Omni-Directional"},
		},
	},
	"critter_body_armor": {
		Name:          "Critter Body Armor",
		Category:      "Specialty Armor",
		Armor:         "Rating",
		ArmorCapacity: "Rating",
		Avail:         "6",
		Cost:          "50 * Rating",
		Source:        "HS",
		Rating:        24,
	},
	"team_jersey_licensed": {
		Name:          "Team Jersey (Licensed)",
		Category:      "Specialty Armor",
		Armor:         "8",
		ArmorCapacity: "8",
		Avail:         "4",
		Cost:          "750",
		Source:        "CA",
		Bonus: &Bonus{
			LimitModifier: []interface{}{LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_SportsFans",
			}, LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_SportsRivals",
			}},
			SelectText: &[]bool{true}[0],
		},
	},
	"team_jersey_unlicensed": {
		Name:          "Team Jersey (Unlicensed)",
		Category:      "Specialty Armor",
		Armor:         "6",
		ArmorCapacity: "6",
		Avail:         "2",
		Cost:          "500",
		Source:        "CA",
		Bonus: &Bonus{
			LimitModifier: []interface{}{LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_SportsFans",
			}, LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_SportsRivals",
			}},
			SelectText: &[]bool{true}[0],
		},
	},
	"ares_briefcase_shield": {
		Name:          "Ares Briefcase Shield",
		Category:      "Armor",
		Armor:         "+4",
		ArmorCapacity: "0",
		Avail:         "14R",
		Cost:          "1800",
		Source:        "CA",
		AddWeapon:     "Ares Briefcase Shield",
	},
	"catsuit": {
		Name:          "Catsuit",
		Category:      "Specialty Armor",
		Armor:         "9",
		ArmorCapacity: "10",
		Avail:         "6",
		Cost:          "900",
		Source:        "CA",
	},
	"scouts_tux": {
		Name:          "Scout's Tux",
		Category:      "Specialty Armor",
		Armor:         "8",
		ArmorCapacity: "6",
		Avail:         "10",
		Cost:          "2000",
		Source:        "CA",
		Bonus: &Bonus{
			SocialLimit: "1",
		},
	},
	"form_fitting_shirt_2050": {
		Name:          "Form Fitting, Shirt (2050)",
		Category:      "Armor",
		Armor:         "+1",
		ArmorCapacity: "0",
		Avail:         "3",
		Cost:          "150",
		Source:        "2050",
	},
	"form_fitting_half_suit_2050": {
		Name:          "Form Fitting, Half Suit (2050)",
		Category:      "Armor",
		Armor:         "+2",
		ArmorCapacity: "0",
		Avail:         "4",
		Cost:          "250",
		Source:        "2050",
	},
	"form_fitting_full_suit_2050": {
		Name:          "Form Fitting, Full Suit (2050)",
		Category:      "Armor",
		Armor:         "+3",
		ArmorCapacity: "0",
		Avail:         "5",
		Cost:          "500",
		Source:        "2050",
	},
	"lined_coat_2050": {
		Name:          "Lined Coat (2050)",
		Category:      "Armor",
		Armor:         "9",
		ArmorCapacity: "9",
		Avail:         "2",
		Cost:          "700",
		Source:        "2050",
	},
	"helmet_2050": {
		Name:          "Helmet (2050)",
		Category:      "Armor",
		Armor:         "+2",
		ArmorCapacity: "9",
		Avail:         "12",
		Cost:          "200",
		Source:        "2050",
	},
	"clothing_ordinary_2050": {
		Name:          "Clothing, Ordinary (2050)",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "50",
		Source:        "2050",
	},
	"clothing_fine_2050": {
		Name:          "Clothing, Fine (2050)",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "500",
		Source:        "2050",
	},
	"clothing_tres_chic_2050": {
		Name:          "Clothing, Tres Chic (2050)",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "Variable(1000-100000)",
		Source:        "2050",
	},
	"leather_synthetic_2050": {
		Name:          "Leather, Synthetic (2050)",
		Category:      "Armor",
		Armor:         "3",
		ArmorCapacity: "3",
		Avail:         "0",
		Cost:          "250",
		Source:        "2050",
	},
	"leather_real_2050": {
		Name:          "Leather, Real (2050)",
		Category:      "Armor",
		Armor:         "4",
		ArmorCapacity: "4",
		Avail:         "0",
		Cost:          "750",
		Source:        "2050",
	},
	"armor_jacket_2050": {
		Name:          "Armor Jacket (2050)",
		Category:      "Armor",
		Armor:         "12",
		ArmorCapacity: "12",
		Avail:         "3",
		Cost:          "900",
		Source:        "2050",
	},
	"armor_clothing_2050": {
		Name:          "Armor Clothing (2050)",
		Category:      "Armor",
		Armor:         "6",
		ArmorCapacity: "6",
		Avail:         "2",
		Cost:          "500",
		Source:        "2050",
	},
	"armor_vest_2050": {
		Name:          "Armor Vest (2050)",
		Category:      "Armor",
		Armor:         "9",
		ArmorCapacity: "9",
		Avail:         "2",
		Cost:          "200",
		Source:        "2050",
	},
	"heavy_armor_full_2050": {
		Name:           "Heavy Armor, Full (2050)",
		Category:       "Armor",
		Armor:          "18",
		ArmorCapacity:  "18",
		Avail:          "16R",
		Cost:           "20000",
		Source:         "2050",
		AddModCategory: "Full Body Armor Mods",
	},
	"heavy_armor_partial_2050": {
		Name:          "Heavy Armor, Partial (2050)",
		Category:      "Armor",
		Armor:         "15",
		ArmorCapacity: "15",
		Avail:         "8R",
		Cost:          "10000",
		Source:        "2050",
	},
	"elyzée_elio_bras_suit": {
		Name:          "E'lyzée Elio: Bra's Suit",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "4",
		Avail:         "8",
		Cost:          "3500",
		Source:        "SAG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"elyzée_elio_thail_dress": {
		Name:          "E'lyzée Elio: Tha'il Dress",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "6",
		ArmorCapacity: "2",
		Avail:         "10",
		Cost:          "4500",
		Source:        "SAG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"elyzée_elio_bras_cape": {
		Name:          "E'lyzée Elio: Bra's Cape",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "10",
		ArmorCapacity: "12",
		Avail:         "10",
		Cost:          "4000",
		Source:        "SAG",
		ArmorOverride: "+2",
		Mods: &Mods{
			Name: "Custom Fit (Stack)",
		},
	},
	"elyzée_elio_thail_cape": {
		Name:          "E'lyzée Elio: Tha'il Cape",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "4",
		Avail:         "8",
		Cost:          "1500",
		Source:        "SAG",
		ArmorOverride: "+2",
		Mods: &Mods{
			Name: "Custom Fit (Stack)",
		},
	},
	"franzinger_fashion_tenor_tailcoat_combination": {
		Name:          "Franzinger Fashion Tenor: Tailcoat Combination",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "5",
		Avail:         "8",
		Cost:          "2400",
		Source:        "SAG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"franzinger_fashion_tenor_coat": {
		Name:          "Franzinger Fashion Tenor: Coat",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "10",
		ArmorCapacity: "8",
		Avail:         "8",
		Cost:          "3200",
		Source:        "SAG",
		ArmorOverride: "+2",
		Mods: &Mods{
			Name: "Custom Fit (Stack)",
		},
	},
	"rheingold_pro_tec_plus_suit": {
		Name:          "Rheingold Pro Tec Plus: Suit",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "9",
		ArmorCapacity: "5",
		Avail:         "8",
		Cost:          "2700",
		Source:        "SAG",
		Mods: &Mods{
			Name: "Custom Fit",
		},
	},
	"rheingold_pro_tec_plus_coat": {
		Name:          "Rheingold Pro Tec Plus: Coat",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "10",
		ArmorCapacity: "10",
		Avail:         "10",
		Cost:          "3500",
		Source:        "SAG",
		ArmorOverride: "+3",
		Mods: &Mods{
			Name: "Custom Fit (Stack)",
		},
	},
	"stattkrieg_armor_vest": {
		Name:          "StattKrieg: Armor Vest",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "4",
		Avail:         "4",
		Cost:          "550",
		Source:        "SAG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_ExcludeFansGangers",
			},
		},
	},
	"stattkrieg_armor_jacket": {
		Name:          "StattKrieg: Armor Jacket",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "10",
		ArmorCapacity: "5",
		Avail:         "4",
		Cost:          "800",
		Source:        "SAG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_ExcludeFansGangers",
			},
		},
	},
	"stattkrieg_padded_overall": {
		Name:          "StattKrieg: Padded Overall",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "8",
		ArmorCapacity: "8",
		Avail:         "6",
		Cost:          "550",
		Source:        "SAG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_ExcludeFansGangers",
			},
		},
	},
	"stattkrieg_helmet": {
		Name:          "StattKrieg: Helmet",
		Category:      "High-Fashion Armor Clothing",
		Armor:         "+2",
		ArmorCapacity: "2",
		Avail:         "4",
		Cost:          "150",
		Source:        "SAG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "-1", Condition: "LimitCondition_ExcludeFansGangers",
			},
		},
	},
	"rockblood_old_school_line": {
		Name:          "Rockblood Old School Line",
		Category:      "Armor",
		Armor:         "8",
		ArmorCapacity: "10",
		Avail:         "8",
		Cost:          "1900",
		Source:        "TCT",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
	},
	"rockblood_signature_armored_shirt": {
		Name:          "Rockblood Signature Armored Shirt",
		Category:      "Armor",
		Armor:         "6",
		ArmorCapacity: "4",
		Avail:         "14",
		Cost:          "800",
		Source:        "TCT",
		Bonus: &Bonus{
			SpecificSkill: []interface{}{SkillCategoryBonus{
				Name: "Etiquette", Bonus: 1,
			}, SkillCategoryBonus{
				Name: "Intimidation", Bonus: 1,
			}},
		},
	},
	"urban_explorer_daedalus": {
		Name:          "Urban Explorer Daedalus",
		Category:      "Specialty Armor",
		Armor:         "9",
		ArmorCapacity: "4",
		Avail:         "8",
		Cost:          "3200",
		Source:        "SL",
		Mods: &Mods{
			Name: "Parachute (Urban Explorer Daedalus)",
		},
	},
	"urban_explorer_daedalus_helmet": {
		Name:          "Urban Explorer Daedalus: Helmet",
		Category:      "Specialty Armor",
		Armor:         "+2",
		ArmorCapacity: "6",
		Avail:         "0",
		Cost:          "100",
		Source:        "SL",
	},
	"ares_arms_bug_stomper_custom_armor": {
		Name:          "Ares Arms Bug Stomper Custom Armor",
		Category:      "Armor",
		Armor:         "20",
		ArmorCapacity: "20",
		Avail:         "30F",
		Cost:          "35000",
		Source:        "SL",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_IntimidationVisible",
			},
		},
		Mods: &Mods{
			Name: []interface{}{"Custom Fit", "Gear Access"},
		},
	},
	"yamatetsu_naval_technologies_rampart": {
		Name:          "Yamatetsu Naval Technologies Rampart",
		Category:      "Armor",
		Armor:         "+10",
		ArmorCapacity: "10",
		Avail:         "12F",
		Cost:          "3000",
		Source:        "SL",
	},
	"pantheon_industries_hard_case_ccob": {
		Name:          "Pantheon Industries Hard Case CCOB",
		Category:      "Armor",
		Armor:         "12",
		ArmorCapacity: "8",
		Avail:         "12R",
		Cost:          "1700",
		Source:        "KC",
		Gears: &Gears{
			UseGear: []string{"Holster"},
		},
		Mods: &Mods{
			Name: []interface{}{"Drag Handle", "Pantheon Armored Shell", "Micro-Hardpoint", "Micro-Hardpoint", "Micro-Hardpoint", "Pantheon Quick-Charge Battery Pack"},
		},
	},
	"generic_ccob": {
		Name:          "Generic CCOB",
		Category:      "Armor",
		Armor:         "8",
		ArmorCapacity: "8",
		Avail:         "10",
		Cost:          "1000",
		Source:        "KC",
		Gears: &Gears{
			UseGear: []string{"Holster", "Medkit"},
		},
		Mods: &Mods{
			Name: []interface{}{"Drag Handle", "Micro-Hardpoint"},
		},
	},
	"fleethead_kappe": {
		Name:          "FleetHead Kappe",
		Category:      "Armor",
		Armor:         "0",
		ArmorCapacity: "3",
		Avail:         "4",
		Cost:          "200",
		Source:        "HAMG",
		Gears: &Gears{
			UseGear: []string{"Image Link"},
		},
	},
	"rheingold_friesennerz": {
		Name:          "Rheingold Friesennerz",
		Category:      "Armor",
		Armor:         "8",
		ArmorCapacity: "6",
		Avail:         "6",
		Cost:          "850",
		Source:        "HAMG",
		Mods: &Mods{
			Name: ModNameEntry{
				Content: "Chemical Protection", Rating: "3",
			},
		},
	},
	"ares_victory_friesennerz": {
		Name:          "Ares Victory Friesennerz",
		Category:      "Armor",
		Armor:         "6",
		ArmorCapacity: "5",
		Avail:         "7",
		Cost:          "920",
		Source:        "HAMG",
		Mods: &Mods{
			Name: []interface{}{ModNameEntry{
				Content: "Chemical Protection", Rating: "3",
			}, "Internal Air Tank (5 Minutes)"},
		},
	},
	"trenchcoat": {
		Name:          "Trenchcoat",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "100",
		Source:        "NF",
	},
	"fedora": {
		Name:          "Fedora",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "30",
		Source:        "NF",
	},
	"trilby": {
		Name:          "Trilby",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "20",
		Source:        "NF",
	},
	"homburg": {
		Name:          "Homburg",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "40",
		Source:        "NF",
	},
	"bowler": {
		Name:          "Bowler",
		Category:      "Clothing",
		Armor:         "0",
		ArmorCapacity: "0",
		Avail:         "0",
		Cost:          "10",
		Source:        "NF",
	},
}

// DataArmorMods contains armor mod records keyed by their ID (lowercase with underscores)
var DataArmorMods = map[string]ArmorMod{
	"electrochromic_clothing": {
		Name:          "Electrochromic Clothing",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "+2",
		Cost:          "500",
		Source:        "SR5",
	},
	"feedback_clothing": {
		Name:          "Feedback Clothing",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[3]",
		Avail:         "8",
		Cost:          "500",
		Source:        "SR5",
	},
	"synthleather": {
		Name:          "(Synth)Leather",
		Category:      "Clothing",
		Armor:         "4",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "200",
		Source:        "SR5",
	},
	"chemical_protection": {
		Name:          "Chemical Protection",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "FixedValues([1],[2],[3],[4],[5],[6])",
		Avail:         "6",
		Cost:          "Rating * 250",
		Source:        "SR5",
		Bonus: &Bonus{
			ToxinContactResist:    "Rating",
			PathogenContactResist: "Rating",
			Unique:                "chemicalprotection",
		},
	},
	"chemical_seal": {
		Name:          "Chemical Seal",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[6]",
		Avail:         "12R",
		Cost:          "3000",
		Source:        "SR5",
		Bonus: &Bonus{
			ToxinContactImmune:       &[]bool{true}[0],
			ToxinInhalationImmune:    &[]bool{true}[0],
			PathogenContactImmune:    &[]bool{true}[0],
			PathogenInhalationImmune: &[]bool{true}[0],
		},
	},
	"fire_resistance": {
		Name:          "Fire Resistance",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "FixedValues([1],[2],[3],[4],[5],[6])",
		Avail:         "6",
		Cost:          "Rating * 250",
		Source:        "SR5",
		Bonus: &Bonus{
			FireArmor: "Rating",
			Unique:    "fireresistance",
		},
	},
	"insulation": {
		Name:          "Insulation",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "FixedValues([1],[2],[3],[4],[5],[6])",
		Avail:         "6",
		Cost:          "Rating * 250",
		Source:        "SR5",
		Bonus: &Bonus{
			ColdArmor: "Rating",
			Unique:    "insulation",
		},
	},
	"nonconductivity": {
		Name:          "Nonconductivity",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "FixedValues([1],[2],[3],[4],[5],[6])",
		Avail:         "6",
		Cost:          "Rating * 250",
		Source:        "SR5",
		Bonus: &Bonus{
			ElectricityArmor: "Rating",
			Unique:           "nonconductivity",
		},
	},
	"thermal_damping": {
		Name:          "Thermal Damping",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "FixedValues([1],[2],[3],[4],[5],[6])",
		Avail:         "10R",
		Cost:          "Rating * 500",
		Source:        "SR5",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "Rating", Condition: "LimitCondition_TestSneakingThermal",
			},
		},
	},
	"full_body_armor_helmet": {
		Name:          "Full Body Armor: Helmet",
		Category:      "General",
		Armor:         "+3",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "500",
		Source:        "SR5",
		GearCapacity:  &[]int{6}[0],
		Required: &Required{
			ParentDetails: &ParentDetails{
				Name: "Full Body Armor",
			},
		},
	},
	"full_body_armor_chemical_seal": {
		Name:          "Full Body Armor: Chemical Seal",
		Category:      "Full Body Armor Mods",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "+6",
		Cost:          "6000",
		Source:        "SR5",
		Required: &Required{
			ParentDetails: &ParentDetails{
				Name: "Full Body Armor",
			},
		},
		Bonus: &Bonus{
			ToxinContactImmune:       &[]bool{true}[0],
			ToxinInhalationImmune:    &[]bool{true}[0],
			PathogenContactImmune:    &[]bool{true}[0],
			PathogenInhalationImmune: &[]bool{true}[0],
		},
	},
	"full_body_armor_environment_adaptation": {
		Name:          "Full Body Armor: Environment Adaptation",
		Category:      "Full Body Armor Mods",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "+3",
		Cost:          "1000",
		Source:        "SR5",
		Required: &Required{
			ParentDetails: &ParentDetails{
				Name: "Full Body Armor",
			},
		},
	},
	"urban_explorer_jumpsuit_helmet": {
		Name:          "Urban Explorer Jumpsuit: Helmet",
		Category:      "Urban Explorer Jumpsuit Accessories",
		Armor:         "+2",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "100",
		Source:        "SR5",
		GearCapacity:  &[]int{6}[0],
	},
	"shock_frills": {
		Name:          "Shock Frills",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[2]",
		Avail:         "6R",
		Cost:          "250",
		Source:        "SR5",
	},
	"liner_fire_resistance_4": {
		Name:          "Liner - Fire Resistance (4)",
		Category:      "Globetrotter Jacket Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			FireArmor: "4",
			Unique:    "fireresistance",
		},
	},
	"liner_chemical_protection_4": {
		Name:          "Liner - Chemical Protection (4)",
		Category:      "Globetrotter Jacket Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			ToxinContactResist:    "4",
			PathogenContactResist: "4",
			Unique:                "chemicalprotection",
		},
	},
	"liner_insulation_4": {
		Name:          "Liner - Insulation (4)",
		Category:      "Globetrotter Jacket Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			ColdArmor: "4",
			Unique:    "insulation",
		},
	},
	"liner_fire_resistance_3": {
		Name:          "Liner - Fire Resistance (3)",
		Category:      "Globetrotter Vest Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
	},
	"liner_chemical_protection_3": {
		Name:          "Liner - Chemical Protection (3)",
		Category:      "Globetrotter Vest Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			ToxinContactResist:    "3",
			PathogenContactResist: "3",
			Unique:                "chemicalprotection",
		},
	},
	"liner_insulation_3": {
		Name:          "Liner - Insulation (3)",
		Category:      "Globetrotter Vest Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			ColdArmor: "3",
			Unique:    "insulation",
		},
	},
	"liner_fire_resistance_2": {
		Name:          "Liner - Fire Resistance (2)",
		Category:      "Globetrotter Clothing Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			FireArmor: "2",
			Unique:    "fireresistance",
		},
	},
	"liner_chemical_protection_2": {
		Name:          "Liner - Chemical Protection (2)",
		Category:      "Globetrotter Clothing Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			ToxinContactResist:    "2",
			PathogenContactResist: "2",
			Unique:                "chemicalprotection",
		},
	},
	"liner_insulation_2": {
		Name:          "Liner - Insulation (2)",
		Category:      "Globetrotter Clothing Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			ColdArmor: "2",
			Unique:    "insulation",
		},
	},
	"liner_fire_resistance_6": {
		Name:          "Liner - Fire Resistance (6)",
		Category:      "Victory Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			FireArmor: "6",
			Unique:    "fireresistance",
		},
	},
	"liner_chemical_protection_6": {
		Name:          "Liner - Chemical Protection (6)",
		Category:      "Victory Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			ToxinContactResist:    "6",
			PathogenContactResist: "6",
			Unique:                "chemicalprotection",
		},
	},
	"liner_insulation_6": {
		Name:          "Liner - Insulation (6)",
		Category:      "Victory Liners",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "SR5",
		Bonus: &Bonus{
			ColdArmor: "6",
			Unique:    "insulation",
		},
	},
	"custom_fit": {
		Name:          "Custom Fit",
		Category:      "General",
		Armor:         "0",
		MaxRating:     0,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "RG",
		Hide:          &[]bool{true}[0],
	},
	"custom_fit_stack": {
		Name:          "Custom Fit (Stack)",
		Category:      "General",
		Armor:         "0",
		MaxRating:     0,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "RG",
		Hide:          &[]bool{true}[0],
		Bonus: &Bonus{
			SelectArmor: &[]bool{true}[0],
		},
	},
	"gear_access": {
		Name:          "Gear Access",
		Category:      "General",
		Armor:         "0",
		MaxRating:     0,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "RG",
		Hide:          &[]bool{true}[0],
	},
	"newest_model": {
		Name:          "Newest Model",
		Category:      "General",
		Armor:         "0",
		MaxRating:     0,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "RG",
		Hide:          &[]bool{true}[0],
	},
	"illuminating": {
		Name:          "Illuminating",
		Category:      "General",
		Armor:         "0",
		MaxRating:     0,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "RG",
	},
	"restrictive": {
		Name:          "Restrictive",
		Category:      "General",
		Armor:         "0",
		MaxRating:     0,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "RG",
		Hide:          &[]bool{true}[0],
	},
	"padded": {
		Name:          "Padded",
		Category:      "General",
		Armor:         "0",
		MaxRating:     0,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "RG",
		Hide:          &[]bool{true}[0],
	},
	"concealability": {
		Name:          "Concealability",
		Category:      "General",
		Armor:         "0",
		MaxRating:     0,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "RG",
		Hide:          &[]bool{true}[0],
	},
	"rapid_transit_elite": {
		Name:          "Rapid Transit: Elite",
		Category:      "Rapid Transit Detailing",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "600",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_Visible",
			},
		},
	},
	"rapid_transit_platinum": {
		Name:          "Rapid Transit: Platinum",
		Category:      "Rapid Transit Detailing",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "1100",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_Visible",
			},
		},
	},
	"rapid_transit_diamond": {
		Name:          "Rapid Transit: Diamond",
		Category:      "Rapid Transit Detailing",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "2400",
		Source:        "RG",
		Bonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Social", Value: "3", Condition: "LimitCondition_Visible",
			},
		},
	},
	"nightshade_ir_and_contacts": {
		Name:          "Nightshade IR and Contacts",
		Category:      "Nightshade IR",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "1500",
		Source:        "RG",
	},
	"ballistic_mask": {
		Name:          "Ballistic Mask",
		Category:      "Customized Ballistic Mask",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "150",
		Source:        "RG",
	},
	"auto_injector": {
		Name:          "Auto-Injector",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[2]",
		Avail:         "4",
		Cost:          "1500",
		Source:        "RG",
		GearCapacity:  &[]int{1}[0],
		AddonCategory: []string{"Drugs", "Toxins"},
	},
	"fresnel_fabric": {
		Name:          "Fresnel Fabric",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "[2]",
		Avail:         "14R",
		Cost:          "Rating * 1000",
		Source:        "RG",
	},
	"pulse_weave": {
		Name:          "Pulse Weave",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "[3]",
		Avail:         "+8R",
		Cost:          "Rating * 3000",
		Source:        "RG",
	},
	"shock_weave": {
		Name:          "Shock Weave",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[3]",
		Avail:         "8",
		Cost:          "1000",
		Source:        "RG",
	},
	"universal_mirror_material": {
		Name:          "Universal Mirror Material",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "[3]",
		Avail:         "4",
		Cost:          "Rating * 250",
		Source:        "RG",
	},
	"ynt_softweave_armor": {
		Name:          "YNT Softweave Armor",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[-(Capacity * 0.5 + 0.5*number((Capacity mod 2) = 1))]",
		Avail:         "+4",
		Cost:          "Armor Cost",
		Source:        "RG",
	},
	"ruthenium_polymer_coating": {
		Name:          "Ruthenium Polymer Coating",
		Category:      "General",
		Armor:         "0",
		MaxRating:     4,
		ArmorCapacity: "[4]",
		Avail:         "16F",
		Cost:          "Rating * 5000",
		Source:        "RG",
	},
	"radiation_shielding": {
		Name:          "Radiation Shielding",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "FixedValues([1],[2],[3],[4],[5],[6])",
		Avail:         "Rating * 2",
		Cost:          "Rating * 200",
		Source:        "RG",
		Bonus: &Bonus{
			RadiationResist: "Rating",
		},
	},
	"gel_packs": {
		Name:          "Gel Packs",
		Category:      "General",
		Armor:         "+2",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "6",
		Cost:          "1500",
		Source:        "RG",
	},
	"responsive_interface_gear_armor": {
		Name:          "Responsive Interface Gear: Armor",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[4]",
		Avail:         "8",
		Cost:          "2500",
		Source:        "RG",
		WirelessBonus: &Bonus{
			LimitModifier: LimitModifier{
				Limit: "Mental", Value: "1", Condition: "LimitCondition_SkillsActivePerception",
			},
		},
	},
	"responsive_interface_gear_helmet": {
		Name:          "Responsive Interface Gear: Helmet",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[2]",
		Avail:         "0",
		Cost:          "0",
		Source:        "RG",
		Required: &Required{
			OneOf: &OneOf{
				ArmorMod: &ArmorModRef{
					Content: "Responsive Interface Gear: Armor", SameParent: "True",
				},
			},
		},
	},
	"pneumatic_anti_shock_garment": {
		Name:          "Pneumatic Anti-Shock Garment",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[6]",
		Avail:         "6",
		Cost:          "500",
		Source:        "BB",
	},
	"drag_handle": {
		Name:          "Drag Handle",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[1]",
		Avail:         "0",
		Cost:          "50",
		Source:        "BB",
	},
	"concealed_pocket": {
		Name:          "Concealed Pocket",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[1]",
		Avail:         "4",
		Cost:          "40",
		Source:        "HT",
	},
	"attachable_gear_access": {
		Name:          "Attachable Gear Access",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[4]",
		Avail:         "4",
		Cost:          "150",
		Source:        "HT",
	},
	"faraday_pocket": {
		Name:          "Faraday Pocket",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[1]",
		Avail:         "7R",
		Cost:          "50",
		Source:        "HT",
	},
	"biofiber_pocket": {
		Name:          "Biofiber Pocket",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[2]",
		Avail:         "10F",
		Cost:          "700",
		Source:        "HT",
	},
	"voidblack_coating": {
		Name:          "Voidblack Coating",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[6]",
		Avail:         "14F",
		Cost:          "3000",
		Source:        "CA",
	},
	"ar_fashion": {
		Name:          "AR Fashion",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "50",
		Source:        "CA",
	},
	"parachute_urban_explorer_daedalus": {
		Name:          "Parachute (Urban Explorer Daedalus)",
		Category:      "General",
		Armor:         "0",
		MaxRating:     0,
		ArmorCapacity: "[0]",
		Avail:         "8",
		Cost:          "0",
		Source:        "SL",
		Hide:          &[]bool{true}[0],
	},
	"pantheon_armored_shell": {
		Name:          "Pantheon Armored Shell",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "4",
		Cost:          "0",
		Source:        "KC",
		Hide:          &[]bool{true}[0],
		AddonCategory: []string{"Cyberdecks", "Commlinks", "Rigger Command Consoles"},
	},
	"pantheon_quick_charge_battery_pack": {
		Name:          "Pantheon Quick-Charge Battery Pack",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "4",
		Cost:          "0",
		Source:        "KC",
		Hide:          &[]bool{true}[0],
	},
	"micro_hardpoint": {
		Name:          "Micro-Hardpoint",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "KC",
		GearCapacity:  &[]int{1}[0],
		Hide:          &[]bool{true}[0],
	},
	"internal_air_tank_5_minutes": {
		Name:          "Internal Air Tank (5 Minutes)",
		Category:      "General",
		Armor:         "0",
		MaxRating:     1,
		ArmorCapacity: "[0]",
		Avail:         "0",
		Cost:          "0",
		Source:        "HAMG",
		Hide:          &[]bool{true}[0],
	},
	"grey_mana_integration": {
		Name:          "Grey Mana Integration",
		Category:      "General",
		Armor:         "0",
		MaxRating:     6,
		ArmorCapacity: "[Rating]",
		Avail:         "FixedValues(6F,6F,6F,9F,9F,9F)",
		Cost:          "FixedValues(Rating*1000,Rating*1000,Rating*1000,Rating*2000,Rating*2000,Rating*2000)",
		Source:        "BTB",
	},
}
