package v5

import (
	"strconv"
	"strings"
)

// parseCostString parses a cost string and returns a CostFormula
// Handles: fixed costs ("1,000"), rating formulas ("Rating*1000"), and special cases
func parseCostString(costStr string) *CostFormula {
	costStr = strings.TrimSpace(costStr)
	if costStr == "" || costStr == "-" {
		return nil
	}

	// Check if it's a rating formula
	if strings.Contains(strings.ToLower(costStr), "rating") {
		return &CostFormula{
			Formula:    costStr,
			IsFixed:    false,
			IsVariable: true,
		}
	}

	// Check for special cases like "Commlink + 2,000" or "Deck Cost + 5,000"
	// These reference other costs, so we'll store as formula for now
	if strings.Contains(costStr, "+") || strings.Contains(costStr, "Cost") {
		return &CostFormula{
			Formula:    costStr,
			IsFixed:    false,
			IsVariable: true,
		}
	}

	// Handle prefix like "+1,000"
	if strings.HasPrefix(costStr, "+") {
		costStr = strings.TrimPrefix(costStr, "+")
	}

	// Parse fixed cost (remove commas and currency symbols)
	costStr = strings.ReplaceAll(costStr, ",", "")
	costStr = strings.TrimRight(costStr, "¥")
	costStr = strings.TrimSpace(costStr)

	value, err := strconv.Atoi(costStr)
	if err != nil {
		// If we can't parse it, treat as formula
		return &CostFormula{
			Formula:    costStr,
			IsFixed:    false,
			IsVariable: true,
		}
	}

	return &CostFormula{
		BaseCost:   intPtr(value),
		IsFixed:    true,
		IsVariable: false,
	}
}

// parseAvailabilityString parses an availability string and returns a RatingFormula
// Handles: fixed values ("5R", "12F", "8"), rating formulas ("Rating*2", "(Rating*4)R")
func parseAvailabilityString(availStr string) *RatingFormula {
	availStr = strings.TrimSpace(availStr)
	if availStr == "" || availStr == "-" {
		return nil
	}

	// Check if it's a rating formula
	if strings.Contains(strings.ToLower(availStr), "rating") {
		return &RatingFormula{
			Formula: availStr,
			IsFixed: false,
		}
	}

	// Check if it has R or F suffix (restricted/forbidden)
	// For fixed values with suffixes, we'll store as formula to preserve the suffix
	if strings.HasSuffix(strings.ToUpper(availStr), "R") || strings.HasSuffix(strings.ToUpper(availStr), "F") {
		// Store as formula to preserve suffix
		return &RatingFormula{
			Formula: availStr,
			IsFixed: false,
		}
	}

	// Parse fixed numeric value
	value, err := strconv.ParseFloat(availStr, 64)
	if err != nil {
		// If we can't parse it, treat as formula
		return &RatingFormula{
			Formula: availStr,
			IsFixed: false,
		}
	}

	return &RatingFormula{
		FixedValue: floatPtr(value),
		IsFixed:    true,
	}
}

// dataCyberware contains all cyberware definitions
var dataCyberware = map[string]Cyberware{
	"commlink": {
		Part:                "Head",
		Device:              "Commlink",
		Essence:             "0.2",
		Capacity:            "[2]",
		Availability:        "-",
		AvailabilityFormula: parseAvailabilityString("-"),
		Cost:                "Commlink + 2,000", // TODO: when purchasing this cyberware the user must choose a commlink that will be implanted then +2000 nuyen will be the cost.
		CostFormula:         parseCostString("Commlink + 2,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"control_rig_r1": {
		Part:                "Head",
		Device:              "Control Rig R1",
		Essence:             "1",
		Capacity:            "-",
		Availability:        "5R",
		AvailabilityFormula: parseAvailabilityString("5R"),
		Cost:                "43,000",
		CostFormula:         parseCostString("43,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"control_rig_r2": {
		Part:                "Head",
		Device:              "Control Rig R2",
		Essence:             "2",
		Capacity:            "-",
		Availability:        "10R",
		AvailabilityFormula: parseAvailabilityString("10R"),
		Cost:                "97,000",
		CostFormula:         parseCostString("97,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"control_rig_r3": {
		Part:                "Head",
		Device:              "Control Rig R3",
		Essence:             "3",
		Capacity:            "-",
		Availability:        "15R",
		AvailabilityFormula: parseAvailabilityString("15R"),
		Cost:                "208,000",
		CostFormula:         parseCostString("208,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cortex_bomb_kink": {
		Part:                "Head",
		Device:              "Cortex Bomb (Kink)",
		Essence:             "-",
		Capacity:            "[1]",
		Availability:        "12F",
		AvailabilityFormula: parseAvailabilityString("12F"),
		Cost:                "10,000",
		CostFormula:         parseCostString("10,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cortex_bomb_microbomb": {
		Part:                "Head",
		Device:              "Cortex Bomb (Microbomb)",
		Essence:             "-",
		Capacity:            "[2]",
		Availability:        "16F",
		AvailabilityFormula: parseAvailabilityString("16F"),
		Cost:                "25,000",
		CostFormula:         parseCostString("25,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cortex_bomb_area_bomb": {
		Part:                "Head",
		Device:              "Cortex Bomb (Area Bomb)",
		Essence:             "-",
		Capacity:            "[3]",
		Availability:        "20F",
		AvailabilityFormula: parseAvailabilityString("20F"),
		Cost:                "40,000",
		CostFormula:         parseCostString("40,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cyberdeck": {
		Part:                "Head",
		Device:              "Cyberdeck",
		Essence:             "0.4",
		Capacity:            "[4]",
		Availability:        "5R",
		AvailabilityFormula: parseAvailabilityString("5R"),
		Cost:                "Deck Cost + 5,000", // TODO: when purchasing this cyberware the user must choose a cyberdeck that will be implanted then +5000 nuyen will be the cost.
		CostFormula:         parseCostString("Deck Cost + 5,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"datajack": {
		Part:                "Head",
		Device:              "Datajack",
		Essence:             "0.1",
		Capacity:            "-",
		Availability:        "2",
		AvailabilityFormula: parseAvailabilityString("2"),
		Cost:                "1,000",
		CostFormula:         parseCostString("1,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"data_lock": {
		Part:                "Head",
		Device:              "Data Lock (R 1-12)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 12},
		Essence:             "0.1",
		Capacity:            "-",
		Availability:        "Rating*2",
		AvailabilityFormula: parseAvailabilityString("Rating*2"),
		Cost:                "Rating*1000",
		CostFormula:         parseCostString("Rating*1000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"olfactory_booster": {
		Part:                "Head",
		Device:              "Olfactory Booster (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "0.2",
		Capacity:            "-",
		Availability:        "Rating*3",
		AvailabilityFormula: parseAvailabilityString("Rating*3"),
		Cost:                "Rating*4000",
		CostFormula:         parseCostString("Rating*4000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"simrig": {
		Part:                "Head",
		Device:              "Simrig",
		Essence:             "0.2",
		Capacity:            "-",
		Availability:        "12R",
		AvailabilityFormula: parseAvailabilityString("12R"),
		Cost:                "4,000",
		CostFormula:         parseCostString("4,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"skilljack": {
		Part:                "Head",
		Device:              "Skilljack (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "Rating*0.1",
		Capacity:            "-",
		Availability:        "Rating*2",
		AvailabilityFormula: parseAvailabilityString("Rating*2"),
		Cost:                "Rating*20000",
		CostFormula:         parseCostString("Rating*20000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"taste_booster": {
		Part:                "Head",
		Device:              "Taste Booster (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "0.2",
		Capacity:            "-",
		Availability:        "Rating*3",
		AvailabilityFormula: parseAvailabilityString("Rating*3"),
		Cost:                "Rating*3000",
		CostFormula:         parseCostString("Rating*3000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"tooth_compartment": {
		Part:                "Head",
		Device:              "Tooth Compartment",
		Essence:             "-",
		Capacity:            "-",
		Availability:        "8",
		AvailabilityFormula: parseAvailabilityString("8"),
		Cost:                "800",
		CostFormula:         parseCostString("800"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"ultrasound_sensor": {
		Part:                "Head",
		Device:              "Ultrasound Sensor (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "0.25",
		Capacity:            "[2]",
		Availability:        "10",
		AvailabilityFormula: parseAvailabilityString("10"),
		Cost:                "Rating*12000",
		CostFormula:         parseCostString("Rating*12000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"voice_modulator": {
		Part:                "Head",
		Device:              "Voice Modulator (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "0.2",
		Capacity:            "-",
		Availability:        "Rating*3F",
		AvailabilityFormula: parseAvailabilityString("Rating*3F"),
		Cost:                "Rating*5000",
		CostFormula:         parseCostString("Rating*5000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cybereyes_r1": {
		Part:                "Eye",
		Device:              "Cybereyes R1",
		Essence:             "0.2",
		Capacity:            "4",
		Availability:        "3",
		AvailabilityFormula: parseAvailabilityString("3"),
		Cost:                "4,000",
		CostFormula:         parseCostString("4,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cybereyes_r2": {
		Part:                "Eye",
		Device:              "Cybereyes R2",
		Essence:             "0.3",
		Capacity:            "8",
		Availability:        "6",
		AvailabilityFormula: parseAvailabilityString("6"),
		Cost:                "6,000",
		CostFormula:         parseCostString("6,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cybereyes_r3": {
		Part:                "Eye",
		Device:              "Cybereyes R3",
		Essence:             "0.4",
		Capacity:            "12",
		Availability:        "9",
		AvailabilityFormula: parseAvailabilityString("9"),
		Cost:                "10,000",
		CostFormula:         parseCostString("10,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cybereyes_r4": {
		Part:                "Eye",
		Device:              "Cybereyes R4",
		Essence:             "0.5",
		Capacity:            "16",
		Availability:        "12",
		AvailabilityFormula: parseAvailabilityString("12"),
		Cost:                "14,000",
		CostFormula:         parseCostString("14,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"flare_compensation": {
		Part:                "Eye",
		Device:              "Flare Compensation",
		Essence:             "0.1",
		Capacity:            "[1]",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "1,000",
		CostFormula:         parseCostString("1,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"image_link": {
		Part:                "Eye",
		Device:              "Image Link",
		Essence:             "0.1",
		Capacity:            "*",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "1,000",
		CostFormula:         parseCostString("1,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"low_light_vision": {
		Part:                "Eye",
		Device:              "Low-Light Vision",
		Essence:             "0.1",
		Capacity:            "[2]",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "1,500",
		CostFormula:         parseCostString("1,500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"ocular_drone": {
		Part:                "Eye",
		Device:              "Ocular Drone",
		Essence:             "-",
		Capacity:            "[6]",
		Availability:        "6",
		AvailabilityFormula: parseAvailabilityString("6"),
		Cost:                "6,000",
		CostFormula:         parseCostString("6,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"retinal_duplication": {
		Part:                "Eye",
		Device:              "Retinal Duplication (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "0.1",
		Capacity:            "[1]",
		Availability:        "16F",
		AvailabilityFormula: parseAvailabilityString("16F"),
		Cost:                "Rating*20000",
		CostFormula:         parseCostString("Rating*20000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"smartlink": {
		Part:                "Eye",
		Device:              "Smartlink",
		Essence:             "0.2",
		Capacity:            "[3]",
		Availability:        "8R",
		AvailabilityFormula: parseAvailabilityString("8R"),
		Cost:                "4,000",
		CostFormula:         parseCostString("4,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"thermographic_vision": {
		Part:                "Eye",
		Device:              "Thermographic Vision",
		Essence:             "0.1",
		Capacity:            "[2]",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "1,500",
		CostFormula:         parseCostString("1,500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"vision_enhancement": {
		Part:                "Eye",
		Device:              "Vision Enhancement (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "0.1",
		Capacity:            "[Rating]",
		Availability:        "Rating*3",
		AvailabilityFormula: parseAvailabilityString("Rating*3"),
		Cost:                "Rating*4000",
		CostFormula:         parseCostString("Rating*4000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"vision_magnification": {
		Part:                "Eye",
		Device:              "Vision Magnification",
		Essence:             "0.1",
		Capacity:            "[2]",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "2,000",
		CostFormula:         parseCostString("2,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cyberears_r1": {
		Part:                "Ear",
		Device:              "Cyberears R1",
		Essence:             "0.2",
		Capacity:            "4",
		Availability:        "3",
		AvailabilityFormula: parseAvailabilityString("3"),
		Cost:                "3,000",
		CostFormula:         parseCostString("3,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cyberears_r2": {
		Part:                "Ear",
		Device:              "Cyberears R2",
		Essence:             "0.3",
		Capacity:            "8",
		Availability:        "6",
		AvailabilityFormula: parseAvailabilityString("6"),
		Cost:                "4,500",
		CostFormula:         parseCostString("4,500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cyberears_r3": {
		Part:                "Ear",
		Device:              "Cyberears R3",
		Essence:             "0.4",
		Capacity:            "12",
		Availability:        "9",
		AvailabilityFormula: parseAvailabilityString("9"),
		Cost:                "7,500",
		CostFormula:         parseCostString("7,500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cyberears_r4": {
		Part:                "Ear",
		Device:              "Cyberears R4",
		Essence:             "0.5",
		Capacity:            "16",
		Availability:        "12",
		AvailabilityFormula: parseAvailabilityString("12"),
		Cost:                "11,000",
		CostFormula:         parseCostString("11,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"audio_enhancement": {
		Part:                "Ear",
		Device:              "Audio Enhancement (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "0.1",
		Capacity:            "[Rating]",
		Availability:        "Rating*3",
		AvailabilityFormula: parseAvailabilityString("Rating*3"),
		Cost:                "Rating*4000",
		CostFormula:         parseCostString("Rating*4000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"balance_augmenter": {
		Part:                "Ear",
		Device:              "Balance Augmenter",
		Essence:             "0.1",
		Capacity:            "[4]",
		Availability:        "8",
		AvailabilityFormula: parseAvailabilityString("8"),
		Cost:                "8,000",
		CostFormula:         parseCostString("8,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"damper": {
		Part:                "Ear",
		Device:              "Damper",
		Essence:             "0.1",
		Capacity:            "[1]",
		Availability:        "6",
		AvailabilityFormula: parseAvailabilityString("6"),
		Cost:                "2,250",
		CostFormula:         parseCostString("2,250"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"select_sound_filter": {
		Part:                "Ear",
		Device:              "Select Sound Filter (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "0.1",
		Capacity:            "[Rating]",
		Availability:        "Rating*3",
		AvailabilityFormula: parseAvailabilityString("Rating*3"),
		Cost:                "Rating*3500",
		CostFormula:         parseCostString("Rating*3500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"sound_link": {
		Part:                "Ear",
		Device:              "Sound Link",
		Essence:             "0.1",
		Capacity:            "*",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "1,000",
		CostFormula:         parseCostString("1,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"spatial_recognizer": {
		Part:                "Ear",
		Device:              "Spatial Recognizer",
		Essence:             "0.1",
		Capacity:            "[2]",
		Availability:        "8",
		AvailabilityFormula: parseAvailabilityString("8"),
		Cost:                "4,000",
		CostFormula:         parseCostString("4,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"bone_lacing_plastic": {
		Part:                "Body",
		Device:              "Bone Lacing (Plastic)",
		Essence:             "0.5",
		Capacity:            "-",
		Availability:        "8R",
		AvailabilityFormula: parseAvailabilityString("8R"),
		Cost:                "8,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"bone_lacing_aluminum": {
		Part:                "Body",
		Device:              "Bone Lacing (Aluminum)",
		Essence:             "1",
		Capacity:            "-",
		Availability:        "12R",
		AvailabilityFormula: parseAvailabilityString("12R"),
		Cost:                "18,000",
		CostFormula:         parseCostString("18,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"bone_lacing_titanium": {
		Part:                "Body",
		Device:              "Bone Lacing (Titanium)",
		Essence:             "1.5",
		Capacity:            "-",
		Availability:        "16R",
		AvailabilityFormula: parseAvailabilityString("16R"),
		Cost:                "30,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"dermal_plating": {
		Part:                "Body",
		Device:              "Dermal Plating (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "Rating*0.5",
		Capacity:            "-",
		Availability:        "(Rating*4)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*4)R"),
		Cost:                "Rating*3000",
		CostFormula:         parseCostString("Rating*3000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"fingertip_compartment": {
		Part:                "Body",
		Device:              "Fingertip Compartment",
		Essence:             "0.1",
		Capacity:            "[1]",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "3,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"grapple_gun": {
		Part:                "Body",
		Device:              "Grapple Gun",
		Essence:             "0.5",
		Capacity:            "[4]",
		Availability:        "8",
		AvailabilityFormula: parseAvailabilityString("8"),
		Cost:                "5,000",
		CostFormula:         parseCostString("5,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"internal_air_tank": {
		Part:                "Body",
		Device:              "Internal Air Tank (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "0.25",
		Capacity:            "[3]",
		Availability:        "Rating",
		AvailabilityFormula: parseAvailabilityString("Rating"),
		Cost:                "Rating*4500",
		CostFormula:         parseCostString("Rating*4500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"muscle_replacement": {
		Part:                "Body",
		Device:              "Muscle Replacement (R 1-4)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 4},
		Essence:             "Rating",
		Capacity:            "-",
		Availability:        "(Rating*5)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*5)R"),
		Cost:                "Rating*25000",
		CostFormula:         parseCostString("Rating*25000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"reaction_enhancers": {
		Part:                "Body",
		Device:              "Reaction Enhancers (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "Rating*0.3",
		Capacity:            "-",
		Availability:        "(Rating*5)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*5)R"),
		Cost:                "Rating*13000",
		CostFormula:         parseCostString("Rating*13000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"skillwires": {
		Part:                "Body",
		Device:              "Skillwires (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "Rating*0.1",
		Capacity:            "-",
		Availability:        "Rating*4",
		AvailabilityFormula: parseAvailabilityString("Rating*4"),
		Cost:                "Rating*20000",
		CostFormula:         parseCostString("Rating*20000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"smuggling_compartment": {
		Part:                "Body",
		Device:              "Smuggling Compartment",
		Essence:             "0.2",
		Capacity:            "[2]",
		Availability:        "6",
		AvailabilityFormula: parseAvailabilityString("6"),
		Cost:                "7,500",
		CostFormula:         parseCostString("7,500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"wired_reflexes_r1": {
		Part:                "Body",
		Device:              "Wired Reflexes R1",
		Essence:             "2",
		Capacity:            "-",
		Availability:        "8R",
		AvailabilityFormula: parseAvailabilityString("8R"),
		Cost:                "39,000",
		CostFormula:         parseCostString("39,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"wired_reflexes_r2": {
		Part:                "Body",
		Device:              "Wired Reflexes R2",
		Essence:             "3",
		Capacity:            "-",
		Availability:        "12R",
		AvailabilityFormula: parseAvailabilityString("12R"),
		Cost:                "149,000",
		CostFormula:         parseCostString("149,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"wired_reflexes_r3": {
		Part:                "Body",
		Device:              "Wired Reflexes R3",
		Essence:             "5",
		Capacity:            "-",
		Availability:        "20R",
		AvailabilityFormula: parseAvailabilityString("20R"),
		Cost:                "217,000",
		CostFormula:         parseCostString("217,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"obvious_full_arm": {
		Part:                "Limb",
		Device:              "Obvious Full Arm",
		Essence:             "1",
		Capacity:            "15",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "15,000",
		CostFormula:         parseCostString("15,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"obvious_full_leg": {
		Part:                "Limb",
		Device:              "Obvious Full Leg",
		Essence:             "1",
		Capacity:            "20",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "15,000",
		CostFormula:         parseCostString("15,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"obvious_hand_foot": {
		Part:                "Limb",
		Device:              "Obvious Hand/Foot",
		Essence:             "0.25",
		Capacity:            "4",
		Availability:        "2",
		AvailabilityFormula: parseAvailabilityString("2"),
		Cost:                "5,000",
		CostFormula:         parseCostString("5,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"obvious_lower_arm": {
		Part:                "Limb",
		Device:              "Obvious Lower Arm",
		Essence:             "0.45",
		Capacity:            "10",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "10,000",
		CostFormula:         parseCostString("10,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"obvious_lower_leg": {
		Part:                "Limb",
		Device:              "Obvious Lower Leg",
		Essence:             "0.45",
		Capacity:            "12",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "10,000",
		CostFormula:         parseCostString("10,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"obvious_torso": {
		Part:                "Limb",
		Device:              "Obvious Torso",
		Essence:             "1.5",
		Capacity:            "10",
		Availability:        "12",
		AvailabilityFormula: parseAvailabilityString("12"),
		Cost:                "20,000",
		CostFormula:         parseCostString("20,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"obvious_skull": {
		Part:                "Limb",
		Device:              "Obvious Skull",
		Essence:             "0.75",
		Capacity:            "4",
		Availability:        "16",
		AvailabilityFormula: parseAvailabilityString("16"),
		Cost:                "10,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"synthetic_full_arm": {
		Part:                "Limb",
		Device:              "Synthetic Full Arm",
		Essence:             "1",
		Capacity:            "8",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "20,000",
		CostFormula:         parseCostString("20,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"synthetic_full_leg": {
		Part:                "Limb",
		Device:              "Synthetic Full Leg",
		Essence:             "1",
		Capacity:            "10",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "20,000",
		CostFormula:         parseCostString("20,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"synthetic_hand_foot": {
		Part:                "Limb",
		Device:              "Synthetic Hand/Foot",
		Essence:             "0.25",
		Capacity:            "2",
		Availability:        "2",
		AvailabilityFormula: parseAvailabilityString("2"),
		Cost:                "6,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"synthetic_lower_arm": {
		Part:                "Limb",
		Device:              "Synthetic Lower Arm",
		Essence:             "0.45",
		Capacity:            "5",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "12,000",
		CostFormula:         parseCostString("12,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"synthetic_lower_leg": {
		Part:                "Limb",
		Device:              "Synthetic Lower Leg",
		Essence:             "0.45",
		Capacity:            "6",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "12,000",
		CostFormula:         parseCostString("12,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"synthetic_torso": {
		Part:                "Limb",
		Device:              "Synthetic Torso",
		Essence:             "1.5",
		Capacity:            "5",
		Availability:        "12",
		AvailabilityFormula: parseAvailabilityString("12"),
		Cost:                "25,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"synthetic_skull": {
		Part:                "Limb",
		Device:              "Synthetic Skull",
		Essence:             "0.75",
		Capacity:            "2",
		Availability:        "16",
		AvailabilityFormula: parseAvailabilityString("16"),
		Cost:                "15,000",
		CostFormula:         parseCostString("15,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"agility_enhancement": {
		Part:                "Limb",
		Device:              "Agility (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "-",
		Capacity:            "Rating",
		Availability:        "(Rating*3)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*3)R"),
		Cost:                "Rating*6500",
		Source:              &SourceReference{Source: "SR5"},
	},
	"armor_enhancement": {
		Part:                "Limb",
		Device:              "Armor (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "-",
		Capacity:            "Rating",
		Availability:        "Rating*5",
		AvailabilityFormula: parseAvailabilityString("Rating*5"),
		Cost:                "Rating*3000",
		CostFormula:         parseCostString("Rating*3000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"strength_enhancement": {
		Part:                "Limb",
		Device:              "Strength (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "-",
		Capacity:            "Rating",
		Availability:        "(Rating*3)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*3)R"),
		Cost:                "Rating*6500",
		Source:              &SourceReference{Source: "SR5"},
	},
	"cyberarm_gyromount": {
		Part:                "Limb Accessories",
		Device:              "Cyberarm Gyromount",
		Essence:             "-",
		Capacity:            "[8]",
		Availability:        "12F",
		AvailabilityFormula: parseAvailabilityString("12F"),
		Cost:                "6,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"cyberarm_slide": {
		Part:                "Limb Accessories",
		Device:              "Cyberarm Slide",
		Essence:             "-",
		Capacity:            "[3]",
		Availability:        "12R",
		AvailabilityFormula: parseAvailabilityString("12R"),
		Cost:                "3,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"cyber_holster": {
		Part:                "Limb Accessories",
		Device:              "Cyber Holster",
		Essence:             "-",
		Capacity:            "[5]",
		Availability:        "8R",
		AvailabilityFormula: parseAvailabilityString("8R"),
		Cost:                "2,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"hydraulic_jacks": {
		Part:                "Limb Accessories",
		Device:              "Hydraulic Jacks (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "-",
		Capacity:            "[Rating]",
		Availability:        "9",
		AvailabilityFormula: parseAvailabilityString("9"),
		Cost:                "Rating*2500",
		Source:              &SourceReference{Source: "SR5"},
	},
	"large_smuggling_compartment": {
		Part:                "Limb Accessories",
		Device:              "Large Smuggling Compartment",
		Essence:             "-",
		Capacity:            "[5]",
		Availability:        "6",
		AvailabilityFormula: parseAvailabilityString("6"),
		Cost:                "8,000",
		CostFormula:         parseCostString("8,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"hold_out_pistol": {
		Part:                "Weapon",
		Device:              "Hold-Out Pistol",
		Essence:             "0.1",
		Capacity:            "[2]",
		Availability:        "8R",
		AvailabilityFormula: parseAvailabilityString("8R"),
		Cost:                "2,000",
		Source:              &SourceReference{Source: "SR5"},
	},
	"light_pistol": {
		Part:                "Weapon",
		Device:              "Light Pistol",
		Essence:             "0.25",
		Capacity:            "[4]",
		Availability:        "10R",
		AvailabilityFormula: parseAvailabilityString("10R"),
		Cost:                "3,900",
		CostFormula:         parseCostString("3,900"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"machine_pistol": {
		Part:                "Weapon",
		Device:              "Machine Pistol",
		Essence:             "0.5",
		Capacity:            "[6]",
		Availability:        "12R",
		AvailabilityFormula: parseAvailabilityString("12R"),
		Cost:                "3,500",
		Source:              &SourceReference{Source: "SR5"},
	},
	"heavy_pistol": {
		Part:                "Weapon",
		Device:              "Heavy Pistol",
		Essence:             "0.5",
		Capacity:            "[6]",
		Availability:        "12R",
		AvailabilityFormula: parseAvailabilityString("12R"),
		Cost:                "4,300",
		CostFormula:         parseCostString("4,300"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"submachine_gun": {
		Part:                "Weapon",
		Device:              "Submachine Gun",
		Essence:             "1",
		Capacity:            "[8]",
		Availability:        "12R",
		AvailabilityFormula: parseAvailabilityString("12R"),
		Cost:                "4,800",
		CostFormula:         parseCostString("4,800"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"shotgun": {
		Part:                "Weapon",
		Device:              "Shotgun",
		Essence:             "1.25",
		Capacity:            "[10]",
		Availability:        "12R",
		AvailabilityFormula: parseAvailabilityString("12R"),
		Cost:                "8,500",
		Source:              &SourceReference{Source: "SR5"},
	},
	"grenade_launcher": {
		Part:                "Weapon",
		Device:              "Grenade Launcher",
		Essence:             "1.5",
		Capacity:            "[15]",
		Availability:        "20F",
		AvailabilityFormula: parseAvailabilityString("20F"),
		Cost:                "30,000",
		CostFormula:         parseCostString("30,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"external_clip_port": {
		Part:                "Weapon",
		Device:              "External Clip Port",
		Essence:             "0.1",
		Capacity:            "[1]",
		Availability:        "-",
		AvailabilityFormula: parseAvailabilityString("-"),
		Cost:                "+1,000",
		CostFormula:         parseCostString("+1,000"), // TOOD: this is an addition to the cyber implment weapon so it should be treated as a weapon mod.
		Source:              &SourceReference{Source: "SR5"},
	},
	"laser_sight": {
		Part:                "Weapon",
		Device:              "Laser Sight",
		Essence:             "-",
		Capacity:            "[1]",
		Availability:        "-",
		AvailabilityFormula: parseAvailabilityString("-"),
		Cost:                "+1,000",
		CostFormula:         parseCostString("+1,000"), // TOOD: this is an addition to the cyber implment weapon so it should be treated as a weapon mod.
		Source:              &SourceReference{Source: "SR5"},
	},
	"silencer_suppressor": {
		Part:                "Weapon",
		Device:              "Silencer/Suppressor",
		Essence:             "-",
		Capacity:            "[2]",
		Availability:        "-",
		AvailabilityFormula: parseAvailabilityString("-"),
		Cost:                "+1,000",
		CostFormula:         parseCostString("+1,000"), // TOOD: this is an addition to the cyber implment weapon so it should be treated as a weapon mod.
		Source:              &SourceReference{Source: "SR5"},
	},
	"hand_blade": {
		Part:                "Weapon",
		Device:              "Hand Blade (Retractable)",
		Essence:             "0.25",
		Capacity:            "[2]",
		Availability:        "10F",
		AvailabilityFormula: parseAvailabilityString("10F"),
		Cost:                "2,500",
		CostFormula:         parseCostString("2,500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"hand_razors": {
		Part:                "Weapon",
		Device:              "Hand Razors (Retractable)",
		Essence:             "0.2",
		Capacity:            "[2]",
		Availability:        "8F",
		AvailabilityFormula: parseAvailabilityString("8F"),
		Cost:                "1,250",
		Source:              &SourceReference{Source: "SR5"},
	},
	"spurs": {
		Part:                "Weapon",
		Device:              "Spurs (Retractable)",
		Essence:             "0.3",
		Capacity:            "[3]",
		Availability:        "12F",
		AvailabilityFormula: parseAvailabilityString("12F"),
		Cost:                "5,000",
		CostFormula:         parseCostString("5,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"shock_hand": {
		Part:                "Weapon",
		Device:              "Shock Hand",
		Essence:             "0.25",
		Capacity:            "[4]",
		Availability:        "8R",
		AvailabilityFormula: parseAvailabilityString("8R"),
		Cost:                "5,000",
		CostFormula:         parseCostString("5,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
}

// dataBioware contains all bioware definitions
var dataBioware = map[string]Bioware{
	"adrenaline_pump": {
		Type:                "Basic",
		Device:              "Adrenaline Pump (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "Rating*0.75",
		Availability:        "(Rating*6)F",
		AvailabilityFormula: parseAvailabilityString("(Rating*6)F"),
		Cost:                "Rating*55000",
		CostFormula:         parseCostString("Rating*55000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"bone_density_augmentation": {
		Type:                "Basic",
		Device:              "Bone Density Augmentation (R 1-4)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 4},
		Essence:             "Rating*0.3",
		Availability:        "Rating*4",
		AvailabilityFormula: parseAvailabilityString("Rating*4"),
		Cost:                "Rating*5000",
		CostFormula:         parseCostString("Rating*5000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cats_eye": {
		Type:                "Basic",
		Device:              "Cat's Eye",
		Essence:             "0.1",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "4,000",
		CostFormula:         parseCostString("4,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"enhanced_articulation": {
		Type:                "Basic",
		Device:              "Enhanced Articulation",
		Essence:             "0.3",
		Availability:        "12",
		AvailabilityFormula: parseAvailabilityString("12"),
		Cost:                "24,000",
		CostFormula:         parseCostString("24,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"muscle_augmentation": {
		Type:                "Basic",
		Device:              "Muscle Augmentation (R 1-4)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 4},
		Essence:             "Rating*0.2",
		Availability:        "(Rating*5)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*5)R"),
		Cost:                "Rating*31000",
		CostFormula:         parseCostString("Rating*31000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"muscle_toner": {
		Type:                "Basic",
		Device:              "Muscle Toner (R 1-4)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 4},
		Essence:             "Rating*0.2",
		Availability:        "(Rating*5)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*5)R"),
		Cost:                "Rating*32000",
		CostFormula:         parseCostString("Rating*32000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"orthoskin": {
		Type:                "Basic",
		Device:              "Orthoskin (R 1-4)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 4},
		Essence:             "Rating*0.25",
		Availability:        "(Rating*4)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*4)R"),
		Cost:                "Rating*6000",
		CostFormula:         parseCostString("Rating*6000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"pathogenic_defense": {
		Type:                "Basic",
		Device:              "Pathogenic Defense (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "Rating*0.1",
		Availability:        "Rating*2",
		AvailabilityFormula: parseAvailabilityString("Rating*2"),
		Cost:                "Rating*4500",
		CostFormula:         parseCostString("Rating*4500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"platelet_factories": {
		Type:                "Basic",
		Device:              "Platelet Factories",
		Essence:             "0.2",
		Availability:        "12",
		AvailabilityFormula: parseAvailabilityString("12"),
		Cost:                "17,000",
		CostFormula:         parseCostString("17,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"skin_pocket": {
		Type:                "Basic",
		Device:              "Skin Pocket",
		Essence:             "0.1",
		Availability:        "4",
		AvailabilityFormula: parseAvailabilityString("4"),
		Cost:                "12,000",
		CostFormula:         parseCostString("12,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"suprathyroid_gland": {
		Type:                "Basic",
		Device:              "Suprathyroid Gland",
		Essence:             "0.7",
		Availability:        "20R",
		AvailabilityFormula: parseAvailabilityString("20R"),
		Cost:                "140,000",
		CostFormula:         parseCostString("140,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"symbiotes": {
		Type:                "Basic",
		Device:              "Symbiotes (R 1-4)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 4},
		Essence:             "Rating*0.2",
		Availability:        "Rating*5",
		AvailabilityFormula: parseAvailabilityString("Rating*5"),
		Cost:                "Rating*3500",
		CostFormula:         parseCostString("Rating*3500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"synthacardium": {
		Type:                "Basic",
		Device:              "Synthacardium (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "Rating*0.1",
		Availability:        "Rating*4",
		AvailabilityFormula: parseAvailabilityString("Rating*4"),
		Cost:                "Rating*30000",
		CostFormula:         parseCostString("Rating*30000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"tailored_pheromones": {
		Type:                "Basic",
		Device:              "Tailored Pheromones (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "Rating*0.2",
		Availability:        "(Rating*4)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*4)R"),
		Cost:                "31,000",
		CostFormula:         parseCostString("31,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"toxin_extractor": {
		Type:                "Basic",
		Device:              "Toxin Extractor (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "Rating*0.2",
		Availability:        "Rating*3",
		AvailabilityFormula: parseAvailabilityString("Rating*3"),
		Cost:                "Rating*4800",
		CostFormula:         parseCostString("Rating*4800"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"tracheal_filter": {
		Type:                "Basic",
		Device:              "Tracheal Filter (R 1-6)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 6},
		Essence:             "Rating*0.1",
		Availability:        "Rating*3",
		AvailabilityFormula: parseAvailabilityString("Rating*3"),
		Cost:                "Rating*4500",
		CostFormula:         parseCostString("Rating*4500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"cerebral_booster": {
		Type:                "Cultured",
		Device:              "Cerebral Booster (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "Rating*0.2",
		Availability:        "Rating*6",
		AvailabilityFormula: parseAvailabilityString("Rating*6"),
		Cost:                "Rating*31500",
		CostFormula:         parseCostString("Rating*31500"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"damage_compensators": {
		Type:                "Cultured",
		Device:              "Damage Compensators (R 1-12)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 12},
		Essence:             "Rating*0.1",
		Availability:        "(Rating*3)F",
		AvailabilityFormula: parseAvailabilityString("(Rating*3)F"),
		Cost:                "Rating*2000",
		CostFormula:         parseCostString("Rating*2000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"mnemonic_enhancer": {
		Type:                "Cultured",
		Device:              "Mnemonic Enhancer (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "Rating*0.1",
		Availability:        "Rating*5",
		AvailabilityFormula: parseAvailabilityString("Rating*5"),
		Cost:                "Rating*9000",
		CostFormula:         parseCostString("Rating*9000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"pain_editor": {
		Type:                "Cultured",
		Device:              "Pain Editor",
		Essence:             "0.3",
		Availability:        "18F",
		AvailabilityFormula: parseAvailabilityString("18F"),
		Cost:                "48,000",
		CostFormula:         parseCostString("48,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"reflex_recorder": {
		Type:                "Cultured",
		Device:              "Reflex Recorder (Skill)",
		Essence:             "0.1",
		Availability:        "10",
		AvailabilityFormula: parseAvailabilityString("10"),
		Cost:                "14,000",
		CostFormula:         parseCostString("14,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"sleep_regulator": {
		Type:                "Cultured",
		Device:              "Sleep Regulator",
		Essence:             "0.1",
		Availability:        "6",
		AvailabilityFormula: parseAvailabilityString("6"),
		Cost:                "12,000",
		CostFormula:         parseCostString("12,000"),
		Source:              &SourceReference{Source: "SR5"},
	},
	"synaptic_booster": {
		Type:                "Cultured",
		Device:              "Synaptic Booster (R 1-3)",
		Rating:              RatingStructure{HasRating: true, MaxRating: 3},
		Essence:             "Rating*0.5",
		Availability:        "(Rating*6)R",
		AvailabilityFormula: parseAvailabilityString("(Rating*6)R"),
		Cost:                "Rating*95000",
		CostFormula:         parseCostString("Rating*95000"),
		Source:              &SourceReference{Source: "SR5"},
	},
}
