package v5

// DataGrades contains bioware grades keyed by their ID (lowercase with underscores)
var DataGrades = map[string]Grade{
	"none": {
		Name:         "None",
		Ess:          "1",
		Cost:         "1",
		DeviceRating: "0",
		Avail:        "0",
		Source:       "SR5",
	},
	"standard": {
		Name:         "Standard",
		Ess:          "1",
		Cost:         "1",
		DeviceRating: "0",
		Avail:        "0",
		Source:       "SR5",
	},
	"standard_burnouts_way": {
		Name:         "Standard (Burnout's Way)",
		Ess:          "0.8",
		Cost:         "1",
		DeviceRating: "0",
		Avail:        "0",
		Source:       "SG",
	},
	"used": {
		Name:         "Used",
		Ess:          "1.25",
		Cost:         "0.75",
		DeviceRating: "0",
		Avail:        "-4",
		Source:       "SR5",
	},
	"alphaware": {
		Name:         "Alphaware",
		Ess:          "0.8",
		Cost:         "1.2",
		DeviceRating: "0",
		Avail:        "+2",
		Source:       "SR5",
	},
	"betaware": {
		Name:         "Betaware",
		Ess:          "0.7",
		Cost:         "1.5",
		DeviceRating: "0",
		Avail:        "+4",
		Source:       "SR5",
	},
	"deltaware": {
		Name:         "Deltaware",
		Ess:          "0.5",
		Cost:         "2.5",
		DeviceRating: "0",
		Avail:        "+8",
		Source:       "SR5",
	},
	"gammaware": {
		Name:         "Gammaware",
		Ess:          "0.4",
		Cost:         "5",
		DeviceRating: "0",
		Avail:        "+12",
		Source:       "CF",
	},
	"omegaware": {
		Name:         "Omegaware",
		Ess:          "1",
		Cost:         "0.75",
		DeviceRating: "0",
		Avail:        "-4",
		Source:       "CF",
	},
}

// DataBiowareCategories contains bioware categories keyed by their ID (lowercase with underscores)
var DataBiowareCategories = map[string]BiowareCategory{
	"basic": {
		Name: "Basic", BlackMarket: "Bioware",
	},
	"biosculpting": {
		Name: "Biosculpting", BlackMarket: "Bioware",
	},
	"bio_weapons": {
		Name: "Bio-Weapons", BlackMarket: "Bioware",
	},
	"chemical_gland_modifications": {
		Name: "Chemical Gland Modifications", BlackMarket: "Bioware",
	},
	"cosmetic_bioware": {
		Name: "Cosmetic Bioware", BlackMarket: "Bioware",
	},
	"cultured": {
		Name: "Cultured", BlackMarket: "Bioware",
	},
	"orthoskin_upgrades": {
		Name: "Orthoskin Upgrades", BlackMarket: "Bioware",
	},
	"symbionts": {
		Name: "Symbionts", BlackMarket: "Bioware",
	},
	"genetic_restoration": {
		Name: "Genetic Restoration", BlackMarket: "Geneware",
	},
	"phenotype_adjustment": {
		Name: "Phenotype Adjustment", BlackMarket: "Geneware",
	},
	"exotic_metagenetics": {
		Name: "Exotic Metagenetics", BlackMarket: "Geneware",
	},
	"transgenics": {
		Name: "Transgenics", BlackMarket: "Geneware",
	},
	"environmental_microadaptation": {
		Name: "Environmental Microadaptation", BlackMarket: "Geneware",
	},
	"immunization": {
		Name: "Immunization", BlackMarket: "Geneware",
	},
	"transgenic_alteration": {
		Name: "Transgenic Alteration", BlackMarket: "Geneware",
	},
	"complimentary_genetics": {
		Name: "Complimentary Genetics", BlackMarket: "Geneware",
	},
}

// DataBiowares contains bioware records keyed by their ID (lowercase with underscores)
var DataBiowares = map[string]Bioware{
	"adrenaline_pump": {
		Name:     "Adrenaline Pump",
		Category: "Basic",
		Ess:      "Rating * 0.75",
		Capacity: "0",
		Avail:    "(Rating * 6)F",
		Cost:     "Rating * 55000",
		Source:   "SR5",
		Rating:   3,
	},
	"bone_density_augmentation": {
		Name:     "Bone Density Augmentation",
		Category: "Basic",
		Ess:      "Rating * 0.3",
		Capacity: "0",
		Avail:    "(Rating * 4)",
		Cost:     "Rating * 5000",
		Source:   "SR5",
		Rating:   4,
		Bonus: &BiowareBonus{
			UnarmedDVPhysical: &[]bool{true}[0],
			DamageResistance:  "Rating",
			UnarmedDV:         "Rating-1",
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Cyberware: []interface{}{"Bone Lacing (Titanium)", "Bone Lacing (Aluminum)", "Bone Lacing (Plastic)"},
			},
		},
	},
	"cats_eyes": {
		Name:     "Cat's Eyes",
		Category: "Basic",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "4000",
		Source:   "SR5",
	},
	"cerebral_booster": {
		Name:     "Cerebral Booster",
		Category: "Cultured",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "Rating * 6",
		Cost:     "Rating * 31500",
		Source:   "SR5",
		Rating:   3,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "LOG", Val: "Rating",
			},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"damage_compensators": {
		Name:     "Damage Compensators",
		Category: "Cultured",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "(Rating * 3)F",
		Cost:     "Rating * 2000",
		Source:   "SR5",
		Rating:   12,
		Bonus: &BiowareBonus{
			ConditionMonitor: &ConditionMonitorBonus{
				SharedThresholdOffset: "Rating",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "High Pain Tolerance",
			},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"enhanced_articulation": {
		Name:     "Enhanced Articulation",
		Category: "Basic",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "12",
		Cost:     "24000",
		Source:   "SR5",
		Bonus: &BiowareBonus{
			SpecificSkill: SpecificSkillBonus{
				Name: "Escape Artist", Bonus: 1,
			},
			PhysicalLimit: "1",
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Cyberware: "Smart Articulation", Bioware: "Elastic Joints",
			},
		},
	},
	"mnemonic_enhancer": {
		Name:     "Mnemonic Enhancer",
		Category: "Cultured",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "Rating * 5",
		Cost:     "Rating * 9000",
		Source:   "SR5",
		Rating:   3,
		Bonus: &BiowareBonus{
			SkillCategory: []interface{}{BiowareSkillCategoryBonus{
				Name: "Academic", Bonus: "Rating",
			}, BiowareSkillCategoryBonus{
				Name: "Interest", Bonus: "Rating",
			}, BiowareSkillCategoryBonus{
				Name: "Language", Bonus: "Rating",
			}, BiowareSkillCategoryBonus{
				Name: "Professional", Bonus: "Rating",
			}, BiowareSkillCategoryBonus{
				Name: "Street", Bonus: "Rating",
			}},
			MentalLimit: "Rating",
			Memory:      "Rating",
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"muscle_augmentation": {
		Name:     "Muscle Augmentation",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "(Rating * 5)R",
		Cost:     "Rating * 31000",
		Source:   "SR5",
		Rating:   4,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "STR", Val: "Rating",
			},
			DisableQuality: "Celerity",
			Unique:         "muscle",
		},
	},
	"muscle_toner": {
		Name:     "Muscle Toner",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "(Rating * 5)R",
		Cost:     "Rating * 32000",
		Source:   "SR5",
		Rating:   4,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "AGI", Val: "Rating",
			},
			DisableQuality: "Celerity",
			Unique:         "muscle",
		},
	},
	"orthoskin": {
		Name:     "Orthoskin",
		Category: "Basic",
		Ess:      "Rating * 0.25",
		Capacity: "0",
		Avail:    "(Rating * 4)R",
		Cost:     "Rating * 6000",
		Source:   "SR5",
		Rating:   4,
		Bonus: &BiowareBonus{
			Armor: &ArmorBonus{
				Content: "Rating", Group: "0",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Cyberware: "Dermal Plating",
			},
		},
	},
	"pain_editor": {
		Name:     "Pain Editor",
		Category: "Cultured",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "18F",
		Cost:     "48000",
		Source:   "SR5",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"pathogenic_defense": {
		Name:     "Pathogenic Defense",
		Category: "Basic",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "(Rating * 2)",
		Cost:     "Rating * 4500",
		Source:   "SR5",
		Rating:   6,
		Bonus: &BiowareBonus{
			PathogenContactResist:    "Rating",
			PathogenIngestionResist:  "Rating",
			PathogenInhalationResist: "Rating",
			PathogenInjectionResist:  "Rating",
		},
	},
	"platelet_factories": {
		Name:     "Platelet Factories",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12",
		Cost:     "17000",
		Source:   "SR5",
	},
	"reflex_recorder": {
		Name:     "Reflex Recorder",
		Category: "Cultured",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "10",
		Cost:     "14000",
		Source:   "SR5",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectSkill: &SelectSkill{
				Val: "1", LimitToAttribute: "BOD,AGI,REA,STR",
			},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"skin_pocket": {
		Name:     "Skin Pocket",
		Category: "Basic",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "12000",
		Source:   "SR5",
		Limit:    "False",
	},
	"sleep_regulator": {
		Name:     "Sleep Regulator",
		Category: "Cultured",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "12000",
		Source:   "SR5",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"suprathyroid_gland": {
		Name:     "Suprathyroid Gland",
		Category: "Basic",
		Ess:      "0.7",
		Capacity: "0",
		Avail:    "20R",
		Cost:     "140000",
		Source:   "SR5",
		Bonus: &BiowareBonus{
			SpecificAttribute: []interface{}{&SpecificAttributeBonus{
				Name: "BOD", Val: "1",
			}, &SpecificAttributeBonus{
				Name: "AGI", Val: "1",
			}, &SpecificAttributeBonus{
				Name: "REA", Val: "1",
			}, &SpecificAttributeBonus{
				Name: "STR", Val: "1",
			}},
			LifestyleCost: "25",
		},
	},
	"symbiotes": {
		Name:     "Symbiotes",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "Rating * 5",
		Cost:     "Rating * 3500",
		Source:   "SR5",
		Rating:   4,
		Bonus: &BiowareBonus{
			StunCMRecovery:     "Rating",
			PhysicalCMRecovery: "Rating",
		},
	},
	"synaptic_booster": {
		Name:     "Synaptic Booster",
		Category: "Cultured",
		Ess:      "Rating * 0.5",
		Capacity: "0",
		Avail:    "(Rating * 6)R",
		Cost:     "Rating * 95000",
		Source:   "SR5",
		Rating:   3,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "REA", Val: "Rating",
			},
			InitiativePass: &InitiativePassBonus{
				Content: "Rating", Precedence: "0",
			},
			DisableQuality: "3564b678-7721-4a8d-ac79-1600cf92dc14",
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"synthacardium": {
		Name:     "Synthacardium",
		Category: "Basic",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "Rating * 4",
		Cost:     "Rating * 30000",
		Source:   "SR5",
		Rating:   3,
		Bonus: &BiowareBonus{
			SkillGroup: SkillGroupBonus{
				Name: "Athletics", Bonus: "Rating", Condition: "",
			},
		},
	},
	"tailored_pheromones": {
		Name:     "Tailored Pheromones",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "(Rating * 4)R",
		Cost:     "Rating * 31000",
		Source:   "SR5",
		Rating:   3,
		Bonus: &BiowareBonus{
			SkillGroup: []interface{}{SkillGroupBonus{
				Name: "Acting", Bonus: "Rating", Condition: "People who can smell you",
			}, SkillGroupBonus{
				Name: "Influence", Bonus: "Rating", Condition: "People who can smell you",
			}},
			SocialLimit: "Rating",
		},
	},
	"toxin_extractor": {
		Name:     "Toxin Extractor",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "Rating * 3",
		Cost:     "Rating * 4800",
		Source:   "SR5",
		Rating:   6,
		Bonus: &BiowareBonus{
			ToxinContactResist:    "Rating",
			ToxinIngestionResist:  "Rating",
			ToxinInhalationResist: "Rating",
			ToxinInjectionResist:  "Rating",
		},
	},
	"tracheal_filter": {
		Name:     "Tracheal Filter",
		Category: "Basic",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "Rating * 3",
		Cost:     "Rating * 4500",
		Source:   "SR5",
		Rating:   6,
		Bonus: &BiowareBonus{
			ToxinInhalationResist: "Rating",
		},
	},
	"chemical_gland_internal_release_or_gradual_release": {
		Name:     "Chemical Gland (Internal Release or Gradual Release)",
		Category: "Basic",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "12R or Gear",
		Cost:     "20000 + (99 * Gear Cost)",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
		AllowGear: &AllowGear{
			GearCategory: []string{"Chemicals", "Custom Drug", "Drugs", "Toxins", "Custom"},
		},
		AllowSubsystems: &AllowSubsystems{
			Category: "Chemical Gland Modifications",
		},
		Notes: "Bonus is for whether this is Internal Release or Gradual Release, not the cost of the chemical.",
	},
	"chemical_gland_exhalation_sprayer": {
		Name:     "Chemical Gland (Exhalation Sprayer)",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12R or Gear",
		Cost:     "26000 + (99 * Gear Cost)",
		Source:   "CF",
		Limit:    "False",
		AllowGear: &AllowGear{
			GearCategory: []string{"Chemicals", "Custom Drug", "Drugs", "Toxins", "Custom"},
		},
		AllowSubsystems: &AllowSubsystems{
			Category: "Chemical Gland Modifications",
		},
	},
	"chemical_gland_spitter": {
		Name:     "Chemical Gland (Spitter)",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12R or Gear",
		Cost:     "26000 + (99 * Gear Cost)",
		Source:   "CF",
		Limit:    "False",
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Bioware: "Chemical Gland (Spitter)",
			},
		},
		AllowGear: &AllowGear{
			GearCategory: []string{"Chemicals", "Custom Drug", "Drugs", "Toxins", "Custom"},
		},
		AllowSubsystems: &AllowSubsystems{
			Category: "Chemical Gland Modifications",
		},
	},
	"chemical_gland_weapon_reservoir": {
		Name:     "Chemical Gland (Weapon Reservoir)",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12F or Gear",
		Cost:     "24000 + (99 * Gear Cost)",
		Source:   "CF",
		Limit:    "False",
		AllowGear: &AllowGear{
			GearCategory: []string{"Chemicals", "Custom Drug", "Drugs", "Toxins", "Custom"},
		},
		AllowSubsystems: &AllowSubsystems{
			Category: "Chemical Gland Modifications",
		},
	},
	"chemical_gland_expanded_reservoir": {
		Name:     "Chemical Gland Expanded Reservoir",
		Category: "Chemical Gland Modifications",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "12",
		Cost:     "2000 + (4 * Parent Gear Cost)",
		Source:   "CF",
		Limit:    "False",
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: []interface{}{"Chemical Gland (Internal Release or Gradual Release)", "Chemical Gland (Exhalation Sprayer)", "Chemical Gland (Spitter)", "Chemical Gland (Weapon Reservoir)"},
			},
		},
		AllowGear: &AllowGear{
			GearCategory: []string{"Chemicals", "Custom Drug", "Drugs", "Toxins", "Custom"},
		},
		AddToParentEss: &[]bool{true}[0],
		RequireParent:  &[]bool{true}[0],
	},
	"chemical_repulsion": {
		Name:     "Chemical Repulsion",
		Category: "Orthoskin Upgrades",
		Ess:      "0.25",
		Capacity: "0",
		Avail:    "12R",
		Cost:     "20000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ToxinContactResist: "2",
			FatigueResist:      "-2",
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Orthoskin",
			},
		},
	},
	"dragon_hide": {
		Name:     "Dragon Hide",
		Category: "Orthoskin Upgrades",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "2000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			FireArmor: "2",
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Orthoskin",
			},
		},
	},
	"insulation": {
		Name:     "Insulation",
		Category: "Orthoskin Upgrades",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ElectricityArmor: "2",
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Bioware: "Electroshock",
			},
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Orthoskin",
			},
		},
	},
	"electroshock": {
		Name:     "Electroshock",
		Category: "Orthoskin Upgrades",
		Ess:      "0.25",
		Capacity: "0",
		Avail:    "8",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ElectricityArmor: "-2",
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Bioware: "Insulation",
			},
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Orthoskin",
			},
		},
	},
	"penguin_blubber": {
		Name:     "Penguin Blubber",
		Category: "Orthoskin Upgrades",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "2000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ColdArmor: "2",
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Orthoskin",
			},
		},
	},
	"sealskin": {
		Name:     "Sealskin",
		Category: "Orthoskin Upgrades",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "2000",
		Source:   "CF",
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Orthoskin",
			},
		},
	},
	"sharkskin": {
		Name:     "Sharkskin",
		Category: "Orthoskin Upgrades",
		Ess:      "0.25",
		Capacity: "0",
		Avail:    "8",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			UnarmedReach: "1",
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Orthoskin",
			},
		},
	},
	"elastic_joints": {
		Name:     "Elastic Joints",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "8",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "1", Condition: "LimitCondition_SkillsActiveEscapeArtist",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Cyberware: "Smart Articulation", Bioware: []interface{}{"Elastic Joints", "Enhanced Articulation"},
			},
		},
	},
	"gills": {
		Name:     "Gills",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "8",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			FatigueResist: "-2",
		},
	},
	"hand_and_foot_webbing_hands": {
		Name:     "Hand and Foot Webbing (Hands)",
		Category: "Basic",
		Ess:      "0.05",
		Capacity: "0",
		Avail:    "8",
		Cost:     "1000",
		Source:   "CF",
		Limit:    "{arm}",
		Bonus: &BiowareBonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "1", Condition: "LimitCondition_SkillsActiveSwimming",
			},
		},
		SelectSide: &[]bool{true}[0],
		PairBonus: &PairBonus{
			WalkMultiplier: &WalkMultiplier{
				Val: "1", Category: "Swim",
			},
		},
	},
	"hand_and_foot_webbing_feet": {
		Name:     "Hand and Foot Webbing (Feet)",
		Category: "Basic",
		Ess:      "0.05",
		Capacity: "0",
		Avail:    "8",
		Cost:     "1000",
		Source:   "CF",
		Limit:    "{leg}",
		Bonus: &BiowareBonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "1", Condition: "LimitCondition_SkillsActiveSwimming",
			},
		},
		SelectSide: &[]bool{true}[0],
		PairBonus: &PairBonus{
			WalkMultiplier: &WalkMultiplier{
				Val: "1", Category: "Swim",
			},
		},
	},
	"hearing_enhancement": {
		Name:     "Hearing Enhancement",
		Category: "Basic",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "4000",
		Source:   "CF",
	},
	"hearing_expansion": {
		Name:     "Hearing Expansion",
		Category: "Basic",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "4000",
		Source:   "CF",
	},
	"joint_replacement": {
		Name:     "Joint Replacement",
		Category: "Basic",
		Ess:      "0.05",
		Capacity: "0",
		Avail:    "2",
		Cost:     "1000",
		Source:   "CF",
		Limit:    "False",
	},
	"spidersilk_gland": {
		Name:     "Spidersilk Gland",
		Category: "Basic",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "35000",
		Source:   "CF",
		Limit:    "False",
	},
	"spinal_realignment": {
		Name:     "Spinal Realignment",
		Category: "Basic",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "4000",
		Source:   "CF",
		Limit:    "False",
	},
	"tactile_sensitivity": {
		Name:     "Tactile Sensitivity",
		Category: "Basic",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "12",
		Cost:     "8000",
		Source:   "CF",
	},
	"tail": {
		Name:     "Tail",
		Category: "Basic",
		Ess:      "0.25",
		Capacity: "0",
		Avail:    "4",
		Cost:     "2000",
		Source:   "CF",
		Limit:    "False",
	},
	"tail_prehensile": {
		Name:     "Tail, Prehensile",
		Category: "Basic",
		Ess:      "0.5",
		Capacity: "0",
		Avail:    "8",
		Cost:     "8000",
		Source:   "CF",
		Limit:    "False",
	},
	"troll_eyes": {
		Name:     "Troll Eyes",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "8",
		Cost:     "10000",
		Source:   "CF",
	},
	"vocal_range_enhancer": {
		Name:     "Vocal Range Enhancer",
		Category: "Basic",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "10000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			LimitModifier: []interface{}{LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_TestSpeech",
			}, LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_SkillsActivePerformanceSinging",
			}},
		},
	},
	"vocal_range_expander": {
		Name:     "Vocal Range Expander",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12R",
		Cost:     "30000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			LimitModifier: []interface{}{LimitModifier{
				Limit: "Social", Value: "1", Condition: "LimitCondition_TestSpeech",
			}, LimitModifier{
				Limit: "Social", Value: "2", Condition: "LimitCondition_SkillsActivePerformanceSinging",
			}},
		},
	},
	"nephritic_screen": {
		Name:     "Nephritic screen",
		Category: "Basic",
		Ess:      "Rating * 0.05",
		Capacity: "0",
		Avail:    "Rating * 2",
		Cost:     "Rating * 4000",
		Source:   "CF",
		Rating:   6,
		Bonus: &BiowareBonus{
			ToxinContactResist:                    "Rating",
			ToxinIngestionResist:                  "Rating",
			ToxinInhalationResist:                 "Rating",
			ToxinInjectionResist:                  "Rating",
			PathogenContactResist:                 "Rating",
			PathogenIngestionResist:               "Rating",
			PathogenInhalationResist:              "Rating",
			PathogenInjectionResist:               "Rating",
			PhysiologicalAddictionFirstTime:       "Rating",
			PsychologicalAddictionFirstTime:       "Rating",
			PhysiologicalAddictionAlreadyAddicted: "Rating",
			PsychologicalAddictionAlreadyAddicted: "Rating",
		},
	},
	"nictitating_membranes": {
		Name:     "Nictitating Membranes",
		Category: "Basic",
		Ess:      "0.05",
		Capacity: "0",
		Avail:    "6",
		Cost:     "1000",
		Source:   "CF",
	},
	"tailored_critter_pheromones": {
		Name:     "Tailored Critter Pheromones",
		Category: "Basic",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "Rating * 4",
		Cost:     "Rating * 2000",
		Source:   "CF",
		Rating:   3,
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"expanded_volume": {
		Name:     "Expanded Volume",
		Category: "Basic",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "Rating * 4",
		Cost:     "Rating * 2000",
		Source:   "CF",
		Rating:   4,
		Bonus: &BiowareBonus{
			FatigueResist: "Rating",
		},
	},
	"amplified_immune_system": {
		Name:     "Amplified Immune System",
		Category: "Basic",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "Rating * 7",
		Cost:     "Rating * 4000",
		Source:   "CF",
		Rating:   4,
		Bonus: &BiowareBonus{
			PathogenContactResist:    "Rating",
			PathogenIngestionResist:  "Rating",
			PathogenInhalationResist: "Rating",
			PathogenInjectionResist:  "Rating",
		},
	},
	"minor_biosculpting_modification": {
		Name:     "Minor Biosculpting Modification",
		Category: "Biosculpting",
		Ess:      "0",
		Capacity: "0",
		Avail:    "2",
		Cost:     "Variable(50-500)",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"moderate_biosculpting_modification": {
		Name:     "Moderate Biosculpting Modification",
		Category: "Biosculpting",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "Variable(500-2000)",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"severe_biosculpting_modification": {
		Name:     "Severe Biosculpting Modification",
		Category: "Biosculpting",
		Ess:      "0.25",
		Capacity: "0",
		Avail:    "8",
		Cost:     "Variable(2000-10000)",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"troll_reduction": {
		Name:     "Troll Reduction",
		Category: "Biosculpting",
		Ess:      "FixedValues(0.2,0.5)",
		Capacity: "0",
		Avail:    "FixedValues(8,12)",
		Cost:     "FixedValues(15000,25000)",
		Source:   "CF",
		Rating:   2,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "CHA",
				Max:  "Rating",
			},
			Armor: "-1",
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Metatype: "Troll",
			},
		},
	},
	"troll_reduction_ork": {
		Name:     "Troll Reduction (Ork)",
		Category: "Biosculpting",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "8",
		Cost:     "15000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "CHA",
				Max:  "1",
			},
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Metatype: "Ork",
			},
		},
	},
	"ethnicitysex_change": {
		Name:     "Ethnicity/Sex Change",
		Category: "Biosculpting",
		Ess:      "0",
		Capacity: "0",
		Avail:    "4",
		Cost:     "10000",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"metatype_modification": {
		Name:     "Metatype Modification",
		Category: "Biosculpting",
		Ess:      "0",
		Capacity: "0",
		Avail:    "8",
		Cost:     "20000",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"claws": {
		Name:      "Claws",
		Category:  "Bio-Weapons",
		Ess:       "0.1*Rating",
		Capacity:  "0",
		Avail:     "4R",
		Cost:      "500",
		Source:    "CF",
		Rating:    2,
		Limit:     "False",
		AddWeapon: "Claws (Bio-Weapon)",
		Notes:     "Rating is used to indicate number of claws.",
	},
	"claws_retractable": {
		Name:      "Claws (Retractable)",
		Category:  "Bio-Weapons",
		Ess:       "0.15*Rating",
		Capacity:  "0",
		Avail:     "6R",
		Cost:      "Rating * 1000",
		Source:    "CF",
		Rating:    2,
		Limit:     "False",
		AddWeapon: "Retractable Claws (Bio-Weapon)",
		Notes:     "Rating is used to indicate number of claws.",
	},
	"striking_callus": {
		Name:     "Striking Callus",
		Category: "Bio-Weapons",
		Ess:      "0.05*Rating",
		Capacity: "0",
		Avail:    "2",
		Cost:     "Rating*250",
		Source:   "CF",
		Rating:   4,
		Bonus: &BiowareBonus{
			UnarmedDVPhysical: &[]bool{true}[0],
			UnarmedDV:         "Rating*0.5",
		},
		Notes: "Rating is used to represent hands and feet. Every 2 Rating will grant +1 Unarmed damage.",
	},
	"tusks_small": {
		Name:     "Tusk(s), Small",
		Category: "Bio-Weapons",
		Ess:      "0",
		Capacity: "0",
		Avail:    "2",
		Cost:     "Rating*100",
		Source:   "CF",
		Rating:   2,
		Limit:    "False",
		Notes:    "Rating is used to indicate number of tusks.",
	},
	"tusks_medium": {
		Name:      "Tusk(s), Medium",
		Category:  "Bio-Weapons",
		Ess:       "0.1*Rating",
		Capacity:  "0",
		Avail:     "2",
		Cost:      "Rating*500",
		Source:    "CF",
		Rating:    2,
		Limit:     "False",
		AddWeapon: "Medium Tusk(s)",
		Notes:     "Rating is used to indicate number of tusks.",
	},
	"tusks_large": {
		Name:      "Tusk(s), Large",
		Category:  "Bio-Weapons",
		Ess:       "0.2*Rating",
		Capacity:  "0",
		Avail:     "8R",
		Cost:      "Rating*1000",
		Source:    "CF",
		Rating:    2,
		Limit:     "False",
		AddWeapon: "Large Tusk(s)",
		Notes:     "Rating is used to indicate number of tusks.",
	},
	"claws_fixed_hands": {
		Name:         "Claws, Fixed (Hands)",
		Category:     "Bio-Weapons",
		Ess:          "0.1",
		Capacity:     "0",
		Avail:        "4R",
		Cost:         "500",
		Source:       "CF",
		Limit:        "{arm}",
		AddWeapon:    "Claws (Bio-Weapon)",
		SelectSide:   &[]bool{true}[0],
		BlocksMounts: "wrist,elbow,shoulder",
		PairBonus: &PairBonus{
			UnarmedReach: "1",
		},
	},
	"claws_retractable_hands": {
		Name:         "Claws, Retractable (Hands)",
		Category:     "Bio-Weapons",
		Ess:          "0.15",
		Capacity:     "0",
		Avail:        "6R",
		Cost:         "1000",
		Source:       "CF",
		Limit:        "{arm}",
		AddWeapon:    "Retractable Claws (Bio-Weapon)",
		SelectSide:   &[]bool{true}[0],
		BlocksMounts: "wrist,elbow,shoulder",
		PairBonus: &PairBonus{
			Reach: &ReachBonus{
				Content: "1", Name: "Retractable Claws (Bio-Weapon)",
			},
		},
	},
	"claws_fixed_feet": {
		Name:         "Claws, Fixed (Feet)",
		Category:     "Bio-Weapons",
		Ess:          "0.1",
		Capacity:     "0",
		Avail:        "4R",
		Cost:         "500",
		Source:       "CF",
		Limit:        "{leg}",
		AddWeapon:    "Claws (Bio-Weapon)",
		SelectSide:   &[]bool{true}[0],
		BlocksMounts: "ankle,knee,hip",
		PairBonus: &PairBonus{
			Reach: &ReachBonus{
				Content: "1", Name: "Claws (Bio-Weapon)",
			},
		},
	},
	"claws_retractable_feet": {
		Name:         "Claws, Retractable (Feet)",
		Category:     "Bio-Weapons",
		Ess:          "0.15",
		Capacity:     "0",
		Avail:        "6R",
		Cost:         "1000",
		Source:       "CF",
		Limit:        "{leg}",
		AddWeapon:    "Retractable Claws (Bio-Weapon)",
		SelectSide:   &[]bool{true}[0],
		BlocksMounts: "ankle,knee,hip",
		PairBonus: &PairBonus{
			Reach: &ReachBonus{
				Content: "1", Name: "Retractable Claws (Bio-Weapon)",
			},
		},
	},
	"striking_callus_hands": {
		Name:     "Striking Callus (Hands)",
		Category: "Bio-Weapons",
		Ess:      "0.05",
		Capacity: "0",
		Avail:    "2",
		Cost:     "250",
		Source:   "CF",
		Limit:    "{arm}",
		Bonus: &BiowareBonus{
			UnarmedDVPhysical: &[]bool{true}[0],
		},
		SelectSide:   &[]bool{true}[0],
		BlocksMounts: "wrist,elbow,shoulder",
		PairBonus: &PairBonus{
			UnarmedDV: "1",
		},
		PairInclude: &PairInclude{
			Name: "Striking Callus (Feet)",
		},
	},
	"striking_callus_feet": {
		Name:     "Striking Callus (Feet)",
		Category: "Bio-Weapons",
		Ess:      "0.05",
		Capacity: "0",
		Avail:    "2",
		Cost:     "250",
		Source:   "CF",
		Limit:    "{leg}",
		Bonus: &BiowareBonus{
			UnarmedDVPhysical: &[]bool{true}[0],
		},
		SelectSide:   &[]bool{true}[0],
		BlocksMounts: "ankle,knee,hip",
		PairBonus: &PairBonus{
			UnarmedDV: "1",
		},
		PairInclude: &PairInclude{
			Name: "Striking Callus (Hands)",
		},
	},
	"tusks_small_1": {
		Name:     "Tusk(s), Small",
		Category: "Bio-Weapons",
		Ess:      "0",
		Capacity: "0",
		Avail:    "2",
		Cost:     "100",
		Source:   "CF",
		Limit:    "False",
	},
	"tusks_medium_1": {
		Name:      "Tusk(s), Medium",
		Category:  "Bio-Weapons",
		Ess:       "0.1",
		Capacity:  "0",
		Avail:     "4",
		Cost:      "500",
		Source:    "CF",
		Limit:     "False",
		AddWeapon: "Medium Tusk(s)",
	},
	"tusks_large_1": {
		Name:      "Tusk(s), Large",
		Category:  "Bio-Weapons",
		Ess:       "0.2",
		Capacity:  "0",
		Avail:     "8R",
		Cost:      "1000",
		Source:    "CF",
		Limit:     "False",
		AddWeapon: "Large Tusk(s)",
	},
	"replacement_tusks_small": {
		Name:     "Replacement Tusk(s), Small",
		Category: "Bio-Weapons",
		Ess:      "0",
		Capacity: "0",
		Avail:    "2",
		Cost:     "100",
		Source:   "CF",
		Limit:    "False",
		Required: &BiowareRequired{
			AllOf: &BiowareRequiredAllOf{
				Metatype: "Ork",
			},
		},
	},
	"replacement_tusks_medium": {
		Name:     "Replacement Tusk(s), Medium",
		Category: "Bio-Weapons",
		Ess:      "0",
		Capacity: "0",
		Avail:    "4",
		Cost:     "500",
		Source:   "CF",
		Limit:    "False",
		Required: &BiowareRequired{
			AllOf: &BiowareRequiredAllOf{
				Metatype: "Ork",
			},
		},
		AddWeapon: "Medium Tusk(s)",
	},
	"electrical_discharge": {
		Name:      "Electrical Discharge",
		Category:  "Bio-Weapons",
		Ess:       "0.3",
		Capacity:  "0",
		Avail:     "8",
		Cost:      "10000",
		Source:    "CF",
		Limit:     "False",
		AddWeapon: "Electrical Discharge",
	},
	"fangs": {
		Name:      "Fangs",
		Category:  "Bio-Weapons",
		Ess:       "0.1",
		Capacity:  "0",
		Avail:     "4",
		Cost:      "500",
		Source:    "CF",
		Limit:     "False",
		AddWeapon: "Fangs (Bio-Weapon)",
	},
	"fangs_retractable": {
		Name:      "Fangs (Retractable)",
		Category:  "Bio-Weapons",
		Ess:       "0.15",
		Capacity:  "0",
		Avail:     "6",
		Cost:      "1000",
		Source:    "CF",
		Limit:     "False",
		AddWeapon: "Retractable Fangs (Bio-Weapon)",
	},
	"horns": {
		Name:      "Horns",
		Category:  "Bio-Weapons",
		Ess:       "0.1",
		Capacity:  "0",
		Avail:     "4",
		Cost:      "500",
		Source:    "CF",
		Limit:     "False",
		AddWeapon: "Horns (Bio-Weapon)",
	},
	"muzzle": {
		Name:     "Muzzle",
		Category: "Bio-Weapons",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "8R",
		Cost:     "2000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			WeaponAccuracy: &WeaponAccuracyBonus{
				Name: "[contains]Fangs", Value: "2",
			},
		},
	},
	"sprayer": {
		Name:      "Sprayer",
		Category:  "Bio-Weapons",
		Ess:       "0.25",
		Capacity:  "0",
		Avail:     "8",
		Cost:      "4000",
		Source:    "CF",
		AddWeapon: "",
	},
	"stinger_tiny": {
		Name:     "Stinger, Tiny",
		Category: "Bio-Weapons",
		Ess:      "0.05",
		Capacity: "0",
		Avail:    "8",
		Cost:     "100",
		Source:   "CF",
		Limit:    "False",
	},
	"stinger_medium": {
		Name:      "Stinger, Medium",
		Category:  "Bio-Weapons",
		Ess:       "0.1",
		Capacity:  "0",
		Avail:     "8R",
		Cost:      "2000",
		Source:    "CF",
		Limit:     "False",
		AddWeapon: "Medium Stinger",
	},
	"stinger_large": {
		Name:      "Stinger, Large",
		Category:  "Bio-Weapons",
		Ess:       "0.2",
		Capacity:  "0",
		Avail:     "12F",
		Cost:      "8000",
		Source:    "CF",
		Limit:     "False",
		AddWeapon: "Large Stinger",
	},
	"bio_tattoos": {
		Name:     "Bio-Tattoos",
		Category: "Cosmetic Bioware",
		Ess:      "FixedValues(0,0.01,0.02)",
		Capacity: "0",
		Avail:    "FixedValues(4,5,6)",
		Cost:     "FixedValues(500,1000,1500)",
		Source:   "CF",
		Rating:   3,
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"chameleon_skin": {
		Name:     "Chameleon Skin",
		Category: "Cosmetic Bioware",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "6",
		Cost:     "2000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "1", Condition: "LimitCondition_SkillGroupStealthNaked",
			},
		},
	},
	"chameleon_skin_dynamic": {
		Name:     "Chameleon Skin (Dynamic)",
		Category: "Cosmetic Bioware",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "8",
		Cost:     "4000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "2", Condition: "LimitCondition_SkillGroupStealthNaked",
			},
		},
	},
	"clean_metabolism": {
		Name:     "Clean Metabolism",
		Category: "Cosmetic Bioware",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "1000",
		Source:   "CF",
	},
	"chloroplast_skin": {
		Name:     "Chloroplast Skin",
		Category: "Cosmetic Bioware",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "4",
		Cost:     "2000",
		Source:   "CF",
	},
	"dietware": {
		Name:     "Dietware",
		Category: "Cosmetic Bioware",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "1000",
		Source:   "CF",
	},
	"hair_growth": {
		Name:     "Hair Growth",
		Category: "Cosmetic Bioware",
		Ess:      "0",
		Capacity: "0",
		Avail:    "4",
		Cost:     "200",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"hair_growth_full_body": {
		Name:     "Hair Growth (Full-Body)",
		Category: "Cosmetic Bioware",
		Ess:      "0",
		Capacity: "0",
		Avail:    "5",
		Cost:     "500",
		Source:   "CF",
		Limit:    "False",
	},
	"perfect_eyes": {
		Name:     "Perfect Eyes",
		Category: "Cosmetic Bioware",
		Ess:      "0",
		Capacity: "0",
		Avail:    "4",
		Cost:     "1000",
		Source:   "CF",
		Limit:    "False",
	},
	"sensitive_skin": {
		Name:     "Sensitive Skin",
		Category: "Cosmetic Bioware",
		Ess:      "0",
		Capacity: "0",
		Avail:    "4",
		Cost:     "Rating * 500",
		Source:   "CF",
		Rating:   20,
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"silky_skin": {
		Name:     "Silky Skin",
		Category: "Cosmetic Bioware",
		Ess:      "0",
		Capacity: "0",
		Avail:    "4",
		Cost:     "500",
		Source:   "CF",
		Limit:    "False",
	},
	"skin_pigmentation": {
		Name:     "Skin Pigmentation",
		Category: "Cosmetic Bioware",
		Ess:      "0",
		Capacity: "0",
		Avail:    "8",
		Cost:     "200",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"skin_pigmentation_permanent": {
		Name:     "Skin Pigmentation (Permanent)",
		Category: "Cosmetic Bioware",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "1000",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
	},
	"cerebellum_booster": {
		Name:     "Cerebellum Booster",
		Category: "Cultured",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "Rating * 8",
		Cost:     "Rating * 50000",
		Source:   "CF",
		Rating:   2,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "INT", Val: "Rating",
			},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"boosted_reflexes": {
		Name:     "Boosted Reflexes",
		Category: "Cultured",
		Ess:      "1",
		Capacity: "0",
		Avail:    "8R",
		Cost:     "10000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			InitiativePass: &InitiativePassBonus{
				Content: "1", Precedence: "0",
			},
			DisableQuality: "3564b678-7721-4a8d-ac79-1600cf92dc14",
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"knowledge_infusion": {
		Name:     "Knowledge Infusion",
		Category: "Cultured",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "12",
		Cost:     "2000",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectSkill: &SelectSkill{
				Val: "1", MaximumRating: "0", KnowledgeSkills: "True", ApplyToRating: "True",
			},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"limb_replacement_fingertoe": {
		Name:     "Limb replacement (Finger/Toe)",
		Category: "Cultured",
		Ess:      "0.02",
		Capacity: "0",
		Avail:    "4",
		Cost:     "2000",
		Source:   "CF",
		Limit:    "False",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
		SelectSide: &[]bool{true}[0],
	},
	"limb_replacement_handfoot": {
		Name:     "Limb replacement (Hand/foot)",
		Category: "Cultured",
		Ess:      "0.02",
		Capacity: "0",
		Avail:    "8",
		Cost:     "20000",
		Source:   "CF",
		Limit:    "False",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
		SelectSide: &[]bool{true}[0],
	},
	"limb_replacement_half_armleg": {
		Name:     "Limb replacement (Half arm/leg)",
		Category: "Cultured",
		Ess:      "0.02",
		Capacity: "0",
		Avail:    "12",
		Cost:     "40000",
		Source:   "CF",
		Limit:    "False",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
		SelectSide: &[]bool{true}[0],
	},
	"limb_replacement_full_armleg": {
		Name:     "Limb replacement (Full arm/leg)",
		Category: "Cultured",
		Ess:      "0.02",
		Capacity: "0",
		Avail:    "12",
		Cost:     "80000",
		Source:   "CF",
		Limit:    "False",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
		SelectSide: &[]bool{true}[0],
	},
	"neuro_retention_amplification": {
		Name:     "Neuro Retention Amplification",
		Category: "Cultured",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "10000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			AddQualities: &AddQualities{
				AddQuality: "Photographic Memory",
			},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"reproductive_replacement_male": {
		Name:     "Reproductive Replacement, Male",
		Category: "Cultured",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "8000",
		Source:   "CF",
		Limit:    "False",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"reproductive_replacement_female": {
		Name:     "Reproductive Replacement, Female",
		Category: "Cultured",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "4",
		Cost:     "20000",
		Source:   "CF",
		Limit:    "False",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"trauma_damper": {
		Name:     "Trauma Damper",
		Category: "Cultured",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "(Rating * 4)R",
		Cost:     "Rating * 4000",
		Source:   "CF",
		Rating:   4,
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"tremor_reducer": {
		Name:     "Tremor Reducer",
		Category: "Cultured",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "Rating * 6",
		Cost:     "Rating * 10000",
		Source:   "CF",
		Rating:   3,
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"reception_enhancer": {
		Name:     "Reception Enhancer",
		Category: "Cultured",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "4",
		Cost:     "10000",
		Source:   "CF",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"genewipe": {
		Name:       "Genewipe",
		Category:   "Phenotype Adjustment",
		Ess:        "0.2",
		Capacity:   "0",
		Avail:      "16F",
		Cost:       "57000",
		Source:     "CF",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"masque": {
		Name:       "Masque",
		Category:   "Phenotype Adjustment",
		Ess:        "0.1",
		Capacity:   "0",
		Avail:      "10F",
		Cost:       "40000",
		Source:     "CF",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"reprint": {
		Name:       "Reprint",
		Category:   "Phenotype Adjustment",
		Ess:        "0.1",
		Capacity:   "0",
		Avail:      "12F",
		Cost:       "30000",
		Source:     "CF",
		Limit:      "False",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"shuffle": {
		Name:       "Shuffle",
		Category:   "Phenotype Adjustment",
		Ess:        "0.2",
		Capacity:   "0",
		Avail:      "12F",
		Cost:       "20000",
		Source:     "CF",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"elastic_stomach": {
		Name:       "Elastic Stomach",
		Category:   "Exotic Metagenetics",
		Ess:        "0.1",
		Capacity:   "0",
		Avail:      "6",
		Cost:       "10000",
		Source:     "CF",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"hyperthymesia": {
		Name:     "Hyperthymesia",
		Category: "Exotic Metagenetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "10",
		Cost:     "15000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			Memory: "2",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"lung_expansion": {
		Name:     "Lung Expansion",
		Category: "Exotic Metagenetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "16500",
		Source:   "CF",
		Bonus: &BiowareBonus{
			FatigueResist: "1",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"increased_myelination": {
		Name:     "Increased Myelination",
		Category: "Exotic Metagenetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "12000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ElectricityArmor: "1",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"myostatin_inhibitor": {
		Name:     "Myostatin Inhibitor",
		Category: "Exotic Metagenetics",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "30500",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "STR", Val: "1",
			},
			AttributeKarmaCost: &AttributeKarmaCostBonus{
				Name: "STR", Val: "-2",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"narco": {
		Name:     "Narco",
		Category: "Exotic Metagenetics",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12F",
		Cost:     "16420",
		Source:   "CF",
		Bonus: &BiowareBonus{
			PhysiologicalAddictionFirstTime:       "-2",
			PsychologicalAddictionFirstTime:       "-2",
			PhysiologicalAddictionAlreadyAddicted: "2",
			PsychologicalAddictionAlreadyAddicted: "2",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"selective_hearing": {
		Name:       "Selective Hearing",
		Category:   "Exotic Metagenetics",
		Ess:        "0.1",
		Capacity:   "0",
		Avail:      "6",
		Cost:       "17000",
		Source:     "CF",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"thickened_digestive_tract_lining": {
		Name:     "Thickened Digestive Tract Lining",
		Category: "Exotic Metagenetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ToxinContactResist:    "1",
			ToxinIngestionResist:  "1",
			ToxinInhalationResist: "1",
			ToxinInjectionResist:  "1",
			LifestyleCost:         "-10",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"adapsin": {
		Name:     "Adapsin",
		Category: "Transgenics",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "16",
		Cost:     "30000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			Adapsin: &[]bool{true}[0],
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"dareadrenaline": {
		Name:     "Dareadrenaline",
		Category: "Transgenics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "61000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SkillAttribute: &SkillAttributeBonus{
				Name: "WIL", Bonus: "1",
			},
			AddQualities: &AddQualities{
				AddQuality: "Poor Self Control (Thrill Seeker) (Dareadrenaline)",
			},
			DrainResist:                           "1",
			FadingResist:                          "1",
			DirectManaSpellResist:                 "1",
			DetectionSpellResist:                  "1",
			ManaIllusionResist:                    "1",
			MentalManipulationResist:              "1",
			DecreaseBODResist:                     "1",
			DecreaseAGIResist:                     "1",
			DecreaseREAResist:                     "1",
			DecreaseSTRResist:                     "1",
			DecreaseCHAResist:                     "1",
			DecreaseINTResist:                     "1",
			DecreaseLOGResist:                     "1",
			DecreaseWILResist:                     "1",
			Composure:                             "1",
			JudgeIntentionsDefense:                "1",
			PhysiologicalAddictionFirstTime:       "1",
			PsychologicalAddictionFirstTime:       "1",
			PhysiologicalAddictionAlreadyAddicted: "1",
			PsychologicalAddictionAlreadyAddicted: "1",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"double_elastin": {
		Name:     "Double Elastin",
		Category: "Transgenics",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12",
		Cost:     "18000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			FatigueResist: "-1",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"hyper_glucagon": {
		Name:     "Hyper-Glucagon",
		Category: "Transgenics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			LifestyleCost: "10",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"magnesense": {
		Name:     "Magnesense",
		Category: "Transgenics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "7000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificSkill: SpecificSkillBonus{
				Name: "Navigation", Bonus: 1,
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"neo_epo": {
		Name:     "Neo-EPO",
		Category: "Transgenics",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "6",
		Cost:     "38000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SkillGroup: SkillGroupBonus{
				Name: "Athletics", Bonus: "1", Condition: "",
			},
			PhysicalLimit:      "1",
			FatigueResist:      "1",
			StunCMRecovery:     "1",
			PhysicalCMRecovery: "1",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"pushed": {
		Name:     "PuSHed",
		Category: "Transgenics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "14",
		Cost:     "62000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SkillLinkedAttribute: &SkillLinkedAttributeBonus{
				Name: "LOG", Bonus: "1",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"qualia": {
		Name:     "Qualia",
		Category: "Transgenics",
		Ess:      "0.4",
		Capacity: "0",
		Avail:    "14",
		Cost:     "65000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SkillLinkedAttribute: &SkillLinkedAttributeBonus{
				Name: "INT", Bonus: "1",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"reakt": {
		Name:     "Reakt",
		Category: "Transgenics",
		Ess:      "0.4",
		Capacity: "0",
		Avail:    "10",
		Cost:     "73000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			Dodge: "2",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"skeletal_pneumaticity": {
		Name:     "Skeletal Pneumaticity",
		Category: "Transgenics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "5",
		Cost:     "9000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificSkill: SpecificSkillBonus{
				Name: "Gymnastics", Bonus: 2,
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"solus": {
		Name:     "Solus",
		Category: "Transgenics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			LifestyleCost: "-10",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"synaptic_acceleration": {
		Name:     "Synaptic Acceleration",
		Category: "Transgenics",
		Ess:      "0.4",
		Capacity: "0",
		Avail:    "8",
		Cost:     "78000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			Initiative: &InitiativeBonus{
				Content: "1", Precedence: "0",
			},
			InitiativePass: &InitiativePassBonus{
				Content: "1", Precedence: "0",
			},
			Dodge:          "1",
			DisableQuality: "3564b678-7721-4a8d-ac79-1600cf92dc14",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"synch": {
		Name:     "Synch",
		Category: "Transgenics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "14000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificSkill: SpecificSkillBonus{
				Name: "Perception", Bonus: 1,
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"tetrachromacy": {
		Name:     "Tetrachromacy",
		Category: "Transgenics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "10",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificSkill: SpecificSkillBonus{
				Name: "Perception", Bonus: 3,
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"vasocon": {
		Name:       "Vasocon",
		Category:   "Transgenics",
		Ess:        "0.1",
		Capacity:   "0",
		Avail:      "6",
		Cost:       "15000",
		Source:     "CF",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"allergen_tolerance": {
		Name:     "Allergen Tolerance",
		Category: "Environmental Microadaptation",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "20000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			Unique: "microadaptation",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"cold_adaptation": {
		Name:     "Cold Adaptation",
		Category: "Environmental Microadaptation",
		Ess:      "0.5",
		Capacity: "0",
		Avail:    "5",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ColdArmor: "2",
			Unique:    "microadaptation",
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Bioware: "Heat Adaptation",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"cryo_tolerance": {
		Name:     "Cryo Tolerance",
		Category: "Environmental Microadaptation",
		Ess:      "0.5",
		Capacity: "0",
		Avail:    "18",
		Cost:     "50000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			Unique: "microadaptation",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"heat_adaptation": {
		Name:     "Heat Adaptation",
		Category: "Environmental Microadaptation",
		Ess:      "0.5",
		Capacity: "0",
		Avail:    "5",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			FireArmor: "2",
			Unique:    "microadaptation",
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Bioware: "Cold Adaptation",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"low_oxygen_adaptation": {
		Name:     "Low Oxygen Adaptation",
		Category: "Environmental Microadaptation",
		Ess:      "0.5",
		Capacity: "0",
		Avail:    "4",
		Cost:     "8000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			LifestyleCost: "10",
			Unique:        "microadaptation",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"microgravity_adaptation": {
		Name:     "Microgravity Adaptation",
		Category: "Environmental Microadaptation",
		Ess:      "0.5",
		Capacity: "0",
		Avail:    "4",
		Cost:     "30000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			Unique: "microadaptation",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"pollution_tolerance": {
		Name:     "Pollution Tolerance",
		Category: "Environmental Microadaptation",
		Ess:      "0.5",
		Capacity: "0",
		Avail:    "5",
		Cost:     "15000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ToxinContactResist:    "2",
			ToxinIngestionResist:  "2",
			ToxinInhalationResist: "2",
			Unique:                "microadaptation",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"radiation_tolerance": {
		Name:     "Radiation Tolerance",
		Category: "Environmental Microadaptation",
		Ess:      "0.5",
		Capacity: "0",
		Avail:    "6",
		Cost:     "15000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			RadiationResist: "2",
			Unique:          "microadaptation",
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"transgenic_alteration": {
		Name:     "Transgenic Alteration",
		Category: "Transgenic Alteration",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "Variable(30000-1000000)",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"control_rig_optimization": {
		Name:     "Control Rig Optimization",
		Category: "Complimentary Genetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "7",
		Cost:     "4600",
		Source:   "CF",
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Cyberware: "Control Rig",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"reaction_optimization": {
		Name:     "Reaction Optimization",
		Category: "Complimentary Genetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "6600",
		Source:   "CF",
		Bonus: &BiowareBonus{
			Initiative: &InitiativeBonus{
				Content: "1",
			},
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Cyberware: "Reaction Enhancers",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"reflex_recorder_optimization": {
		Name:     "Reflex Recorder Optimization",
		Category: "Complimentary Genetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "11",
		Cost:     "3800",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ReflexRecorderOptimization: &[]bool{true}[0],
		},
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Reflex Recorder",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"wired_reflex_optimization": {
		Name:     "Wired Reflex Optimization",
		Category: "Complimentary Genetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "9R",
		Cost:     "9000",
		Source:   "CF",
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Cyberware: "Wired Reflexes",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"adrenaline_pump_optimization": {
		Name:     "Adrenaline Pump Optimization",
		Category: "Complimentary Genetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "7F",
		Cost:     "6000",
		Source:   "CF",
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Adrenaline Pump",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"enhanced_symbiosis": {
		Name:     "Enhanced Symbiosis",
		Category: "Complimentary Genetics",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "4000",
		Source:   "CF",
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Symbiotes",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"genetic_optimization_body": {
		Name:     "Genetic Optimization (Body)",
		Category: "Phenotype Adjustment",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "47000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "BOD",
				Max:  "1",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "Phenotypic Variation - Genetic Optimization (Body)",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"genetic_optimization_agility": {
		Name:     "Genetic Optimization (Agility)",
		Category: "Phenotype Adjustment",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "47000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "AGI",
				Max:  "1",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "Phenotypic Variation - Genetic Optimization (Agility)",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"genetic_optimization_reaction": {
		Name:     "Genetic Optimization (Reaction)",
		Category: "Phenotype Adjustment",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "47000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "REA",
				Max:  "1",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "Phenotypic Variation - Genetic Optimization (Reaction)",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"genetic_optimization_strength": {
		Name:     "Genetic Optimization (Strength)",
		Category: "Phenotype Adjustment",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "47000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "STR",
				Max:  "1",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "Phenotypic Variation - Genetic Optimization (Strength)",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"genetic_optimization_charisma": {
		Name:     "Genetic Optimization (Charisma)",
		Category: "Phenotype Adjustment",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "47000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "CHA",
				Max:  "1",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "Phenotypic Variation - Genetic Optimization (Charisma)",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"genetic_optimization_intuition": {
		Name:     "Genetic Optimization (Intuition)",
		Category: "Phenotype Adjustment",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "47000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "INT",
				Max:  "1",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "Phenotypic Variation - Genetic Optimization (Intuition)",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"genetic_optimization_logic": {
		Name:     "Genetic Optimization (Logic)",
		Category: "Phenotype Adjustment",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "47000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "LOG",
				Max:  "1",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "Phenotypic Variation - Genetic Optimization (Logic)",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"genetic_optimization_willpower": {
		Name:     "Genetic Optimization (Willpower)",
		Category: "Phenotype Adjustment",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "10",
		Cost:     "47000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "WIL",
				Max:  "1",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "Phenotypic Variation - Genetic Optimization (Willpower)",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"cosmetic_alteration": {
		Name:     "Cosmetic Alteration",
		Category: "Phenotype Adjustment",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "35000",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"print_removal": {
		Name:       "Print Removal",
		Category:   "Phenotype Adjustment",
		Ess:        "0.1",
		Capacity:   "0",
		Avail:      "10F",
		Cost:       "18000",
		Source:     "CF",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"metaposeur": {
		Name:     "Metaposeur",
		Category: "Phenotype Adjustment",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "38000",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{
				XML: "metatypes.xml", XPath: "/chummer/metatypes/metatype | /chummer/metatypes/metatype/metavariants/metavariant", AllowEdit: "True",
			},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"immunization": {
		Name:     "Immunization",
		Category: "Immunization",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "20000",
		Source:   "CF",
		Limit:    "{BODUnaug}",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"therapeutic_genetics": {
		Name:     "Therapeutic Genetics",
		Category: "Genetic Restoration",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "10",
		Cost:     "90000",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectText: &SelectTextBonus{},
		},
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"leónization": {
		Name:       "Leónization",
		Category:   "Genetic Restoration",
		Ess:        "1",
		Capacity:   "0",
		Avail:      "15",
		Cost:       "2000000",
		Source:     "CF",
		Limit:      "False",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"lifespan_extension": {
		Name:       "Lifespan Extension",
		Category:   "Genetic Restoration",
		Ess:        "0.5",
		Capacity:   "0",
		Avail:      "12",
		Cost:       "300000",
		Source:     "CF",
		Limit:      "False",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"physical_vigor": {
		Name:       "Physical Vigor",
		Category:   "Genetic Restoration",
		Ess:        "0.5",
		Capacity:   "0",
		Avail:      "13",
		Cost:       "250000",
		Source:     "CF",
		Limit:      "False",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"augmented_healing": {
		Name:       "Augmented Healing",
		Category:   "Genetic Restoration",
		Ess:        "0",
		Capacity:   "0",
		Avail:      "10",
		Cost:       "35000",
		Source:     "CF",
		Limit:      "False",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"cellular_repair": {
		Name:       "Cellular Repair",
		Category:   "Genetic Restoration",
		Ess:        "0",
		Capacity:   "0",
		Avail:      "10",
		Cost:       "65000",
		Source:     "CF",
		Limit:      "False",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"revitilization": {
		Name:       "Revitilization",
		Category:   "Genetic Restoration",
		Ess:        "-0.1",
		Capacity:   "0",
		Avail:      "14",
		Cost:       "110000",
		Source:     "CF",
		Limit:      "False",
		ForceGrade: "None",
		IsGeneware: &[]bool{true}[0],
	},
	"cleaner_leech": {
		Name:     "Cleaner Leech",
		Category: "Symbionts",
		Ess:      "0",
		Capacity: "0",
		Avail:    "4",
		Cost:     "100",
		Source:   "CF",
		Limit:    "False",
		Bonus: &BiowareBonus{
			StunCMRecovery:     "1",
			PhysicalCMRecovery: "1",
		},
	},
	"booster_endosont": {
		Name:     "Booster Endosont",
		Category: "Symbionts",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12",
		Cost:     "10000",
		Source:   "CF",
	},
	"digester_endosont": {
		Name:     "Digester Endosont",
		Category: "Symbionts",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12",
		Cost:     "10000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			LifestyleCost: "-10",
		},
	},
	"electroreceptor_endosont": {
		Name:     "Electroreceptor Endosont",
		Category: "Symbionts",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12",
		Cost:     "10000",
		Source:   "CF",
	},
	"mild_allergy_resistance": {
		Name:     "Mild Allergy Resistance",
		Category: "Symbionts",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "8",
		Cost:     "10000",
		Source:   "CF",
		Limit:    "False",
	},
	"moderate_allergy_resistance": {
		Name:     "Moderate Allergy Resistance",
		Category: "Symbionts",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12",
		Cost:     "30000",
		Source:   "CF",
		Limit:    "False",
	},
	"severe_allergy_resistance": {
		Name:     "Severe Allergy Resistance",
		Category: "Symbionts",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "16",
		Cost:     "50000",
		Source:   "CF",
		Limit:    "False",
	},
	"lactose_tolerance": {
		Name:     "Lactose Tolerance",
		Category: "Symbionts",
		Ess:      "0",
		Capacity: "0",
		Avail:    "2",
		Cost:     "50",
		Source:   "CF",
	},
	"mender_endosont": {
		Name:     "Mender Endosont",
		Category: "Symbionts",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12",
		Cost:     "30000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			StunCMRecovery:     "1",
			PhysicalCMRecovery: "2",
		},
	},
	"slimworm": {
		Name:     "Slimworm",
		Category: "Symbionts",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "4",
		Cost:     "1000",
		Source:   "CF",
		Bonus: &BiowareBonus{
			ToxinIngestionResist: "1",
		},
	},
	"stalwart_endosont": {
		Name:     "Stalwart Endosont",
		Category: "Symbionts",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "12",
		Cost:     "10000",
		Source:   "CF",
	},
	"bilateral_coordination_co_processor": {
		Name:     "Bilateral Coordination Co-processor",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "6",
		Cost:     "4500",
		Source:   "HT",
		Bonus: &BiowareBonus{
			Ambidextrous: &[]bool{true}[0],
		},
	},
	"bone_spike_no_bone_density": {
		Name:     "Bone Spike (No Bone Density)",
		Category: "Bio-Weapons",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "14F",
		Cost:     "20000",
		Source:   "HT",
		Limit:    "False",
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Bioware: "Bone Density Augmentation",
			},
		},
		AddWeapon: "Bone Spike I",
	},
	"bone_spike_bone_density_2_3": {
		Name:     "Bone Spike (Bone Density 2-3)",
		Category: "Bio-Weapons",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "14F",
		Cost:     "20000",
		Source:   "HT",
		Limit:    "False",
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Bone Density Augmentation",
			},
		},
		AddWeapon: "Bone Spike II",
	},
	"bone_spike_bone_density_4": {
		Name:     "Bone Spike (Bone Density 4)",
		Category: "Bio-Weapons",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "14F",
		Cost:     "20000",
		Source:   "HT",
		Limit:    "False",
		Required: &BiowareRequired{
			OneOf: &BiowareRequiredOneOf{
				Bioware: "Bone Density Augmentation",
			},
		},
		AddWeapon: "Bone Spike III",
	},
	"spur_pocket": {
		Name:     "Spur Pocket",
		Category: "Cultured",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "8000",
		Source:   "HT",
		Limit:    "False",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"adrenaline_pump_2050": {
		Name:     "Adrenaline Pump (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.75",
		Capacity: "0",
		Avail:    "10F",
		Cost:     "Rating * 50000",
		Source:   "2050",
		Rating:   3,
	},
	"enhanced_articulation_2050": {
		Name:     "Enhanced Articulation (2050)",
		Category: "Basic",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "5",
		Cost:     "40000",
		Source:   "2050",
		Bonus: &BiowareBonus{
			LimitModifier: LimitModifier{
				Limit: "Physical", Value: "1", Condition: "LimitCondition_SkillsActiveEscapeArtist",
			},
			SpecificSkill: SpecificSkillBonus{
				Name: "Escape Artist", Bonus: 1,
			},
		},
	},
	"suprathyroid_gland_2050": {
		Name:     "Suprathyroid Gland (2050)",
		Category: "Basic",
		Ess:      "0.7",
		Capacity: "0",
		Avail:    "8F",
		Cost:     "50000",
		Source:   "2050",
		Bonus: &BiowareBonus{
			SpecificAttribute: []interface{}{&SpecificAttributeBonus{
				Name: "BOD", Val: "1",
			}, &SpecificAttributeBonus{
				Name: "AGI", Val: "1",
			}, &SpecificAttributeBonus{
				Name: "REA", Val: "1",
			}, &SpecificAttributeBonus{
				Name: "STR", Val: "1",
			}},
			LifestyleCost: "25",
		},
	},
	"tracheal_filter_2050": {
		Name:     "Tracheal Filter (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "Rating * 30000",
		Source:   "2050",
		Rating:   6,
	},
	"tailored_pheromones_2050": {
		Name:     "Tailored Pheromones (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "12",
		Cost:     "Rating * 22000",
		Source:   "2050",
		Rating:   3,
		Bonus: &BiowareBonus{
			SocialLimit: "Rating",
		},
	},
	"mnemonic_enhancer_2050": {
		Name:     "Mnemonic Enhancer (2050)",
		Category: "Cultured",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "6",
		Cost:     "Rating * 15000",
		Source:   "2050",
		Rating:   3,
		Bonus: &BiowareBonus{
			SkillCategory: []interface{}{BiowareSkillCategoryBonus{
				Name: "Academic", Bonus: "Rating",
			}, BiowareSkillCategoryBonus{
				Name: "Interest", Bonus: "Rating",
			}, BiowareSkillCategoryBonus{
				Name: "Language", Bonus: "Rating",
			}, BiowareSkillCategoryBonus{
				Name: "Professional", Bonus: "Rating",
			}, BiowareSkillCategoryBonus{
				Name: "Street", Bonus: "Rating",
			}},
			MentalLimit: "Rating",
			Memory:      "Rating",
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"muscle_toner_2050": {
		Name:     "Muscle Toner (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "(Rating * 5)R",
		Cost:     "Rating * 25000",
		Source:   "2050",
		Rating:   4,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "AGI", Val: "Rating",
			},
			DisableQuality: "Celerity",
			Unique:         "muscle",
		},
	},
	"muscle_augmentation_2050": {
		Name:     "Muscle Augmentation (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "(Rating * 5)R",
		Cost:     "Rating * 20000",
		Source:   "2050",
		Rating:   4,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "STR", Val: "Rating",
			},
			DisableQuality: "Celerity",
			Unique:         "muscle",
		},
	},
	"nephritic_screen_2050": {
		Name:     "Nephritic Screen (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "4",
		Cost:     "Rating * 24000",
		Source:   "2050",
		Rating:   6,
		Bonus: &BiowareBonus{
			ToxinContactResist:                    "Rating",
			ToxinIngestionResist:                  "Rating",
			ToxinInhalationResist:                 "Rating",
			ToxinInjectionResist:                  "Rating",
			PathogenContactResist:                 "Rating",
			PathogenIngestionResist:               "Rating",
			PathogenInhalationResist:              "Rating",
			PathogenInjectionResist:               "Rating",
			PhysiologicalAddictionFirstTime:       "Rating",
			PsychologicalAddictionFirstTime:       "Rating",
			PhysiologicalAddictionAlreadyAddicted: "Rating",
			PsychologicalAddictionAlreadyAddicted: "Rating",
		},
	},
	"orthoskin_2050": {
		Name:     "Orthoskin (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.25",
		Capacity: "0",
		Avail:    "8R",
		Cost:     "Rating * 30000",
		Source:   "2050",
		Rating:   3,
		Bonus: &BiowareBonus{
			Armor: &ArmorBonus{
				Content: "Rating", Group: "0",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Bioware: "Bone Density Augmentation",
			},
		},
	},
	"pathogenic_defense_2050": {
		Name:     "Pathogenic Defense (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "8",
		Cost:     "Rating * 10000",
		Source:   "2050",
		Rating:   6,
		Bonus: &BiowareBonus{
			PathogenContactResist:    "Rating",
			PathogenIngestionResist:  "Rating",
			PathogenInhalationResist: "Rating",
			PathogenInjectionResist:  "Rating",
		},
	},
	"reflex_recorder_2050": {
		Name:     "Reflex Recorder (2050)",
		Category: "Cultured",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "5",
		Cost:     "10000",
		Source:   "2050",
		Limit:    "False",
		Bonus: &BiowareBonus{
			SelectSkill: &SelectSkill{
				Val: "1", LimitToAttribute: "BOD,AGI,REA,STR",
			},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"damage_compensators_2050": {
		Name:     "Damage Compensators (2050)",
		Category: "Cultured",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "10F",
		Cost:     "Rating * 50000",
		Source:   "2050",
		Rating:   12,
		Bonus: &BiowareBonus{
			ConditionMonitor: &ConditionMonitorBonus{
				SharedThresholdOffset: "Rating",
			},
		},
		Forbidden: &Forbidden{
			OneOf: &ForbiddenOneOf{
				Quality: "High Pain Tolerance",
			},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"pain_editor_2050": {
		Name:     "Pain Editor (2050)",
		Category: "Cultured",
		Ess:      "0.3",
		Capacity: "0",
		Avail:    "6F",
		Cost:     "60000",
		Source:   "2050",
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"symbiotes_2050": {
		Name:     "Symbiotes (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "5",
		Cost:     "Rating * 20000",
		Source:   "2050",
		Rating:   3,
	},
	"synaptic_accelerator_2050": {
		Name:     "Synaptic Accelerator (2050)",
		Category: "Cultured",
		Ess:      "Rating * 0.5",
		Capacity: "0",
		Avail:    "6R",
		Cost:     "Rating * 100000",
		Source:   "2050",
		Rating:   3,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "REA", Val: "Rating",
			},
			InitiativePass: &InitiativePassBonus{
				Content: "Rating", Precedence: "0",
			},
			DisableQuality: "3564b678-7721-4a8d-ac79-1600cf92dc14",
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"synthacardium_2050": {
		Name:     "Synthacardium (2050)",
		Category: "Basic",
		Ess:      "Rating * 0.1",
		Capacity: "0",
		Avail:    "4",
		Cost:     "Rating * 10000",
		Source:   "2050",
		Rating:   3,
		Bonus: &BiowareBonus{
			SkillGroup: SkillGroupBonus{
				Name: "Athletics", Bonus: "Rating", Condition: "",
			},
		},
	},
	"platelet_factories_2050": {
		Name:     "Platelet Factories (2050)",
		Category: "Basic",
		Ess:      "0.2",
		Capacity: "0",
		Avail:    "5",
		Cost:     "30000",
		Source:   "2050",
	},
	"cerebral_booster_2050": {
		Name:     "Cerebral Booster (2050)",
		Category: "Cultured",
		Ess:      "Rating * 0.2",
		Capacity: "0",
		Avail:    "6",
		Cost:     "Rating * 55000",
		Source:   "2050",
		Rating:   3,
		Bonus: &BiowareBonus{
			SpecificAttribute: &SpecificAttributeBonus{
				Name: "LOG", Val: "Rating",
			},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Used (Adapsin)"},
		},
	},
	"mct_biolink": {
		Name:     "MCT BioLink",
		Category: "Basic",
		Ess:      "0.5",
		Capacity: "0",
		Avail:    "10",
		Cost:     "15000",
		Source:   "KC",
	},
	"vocal_expansion": {
		Name:     "Vocal Expansion",
		Category: "Basic",
		Ess:      "0.1",
		Capacity: "0",
		Avail:    "Rating*6",
		Cost:     "Rating*8000",
		Source:   "NF",
		Rating:   3,
		Limit:    "1",
		Bonus: &BiowareBonus{
			LimitModifier: []interface{}{LimitModifier{
				Limit: "Social", Value: "Rating", Condition: "LimitCondition_SkillsActiveLeadership",
			}, LimitModifier{
				Limit: "Social", Value: "Rating", Condition: "LimitCondition_SkillsActivePerformanceSinging",
			}},
		},
		BannedGrades: &BannedGrades{
			Grade: []string{"Used", "Standard", "Standard (Burnout's Way)", "Alphaware", "Omegaware"},
		},
	},
	"adrenaline_filter": {
		Name:     "Adrenaline Filter",
		Category: "Basic",
		Ess:      "(Rating)*0.5",
		Capacity: "0",
		Avail:    "(Rating*3)R",
		Cost:     "Rating*35000",
		Source:   "DTR",
		Rating:   3,
		Limit:    "1",
	},
}
