package v5

// DataBooks contains book records keyed by their ID (lowercase with underscores)
var DataBooks = map[string]Book{
	"ap": {
		ID:        "289bc41d-6dd5-4216-9bc7-e6f0cabae9ac",
		Name:      "Assassin's Primer",
		Code:      "AP",
		Permanent: nil,
		Matches:   &BookMatches{Match: []interface{}{BookMatch{Language: "en-us", Text: "Whether we want to admit it or not,", Page: "2"}, BookMatch{Language: "de-de", Text: "Soweit die Historiker das sagen k\u00f6nnen,", Page: "2"}}},
	},
	"gh3": {
		ID:        "b68175bc-e10f-4e11-9361-ed62bb371c8d",
		Name:      "Gun Heaven 3",
		Code:      "GH3",
		Permanent: nil,
		Matches:   &BookMatches{Match: []interface{}{BookMatch{Language: "en-us", Text: "The weapon is designed to be hand loaded", Page: "3"}, BookMatch{Language: "de-de", Text: "Mit dem New Model Revolver kehrt", Page: "4"}}},
	},
	"rg": {
		ID:        "5d6626a2-2400-44b5-b777-d7dac6cb512f",
		Name:      "Run and Gun",
		Code:      "RG",
		Permanent: nil,
		Matches:   &BookMatches{Match: []interface{}{BookMatch{Language: "en-us", Text: "The whole run was a setup. It had to be", Page: "6"}, BookMatch{Language: "de-de", Text: "In seinem Kommandozentrum sah Sicherheitschef", Page: "6"}}},
	},
	"sr5": {
		ID:        "f5ec713c-98cd-41f6-a0a4-4a8eaed55b66",
		Name:      "Shadowrun 5th Edition",
		Code:      "SR5",
		Permanent: nil,
		Matches:   &BookMatches{Match: []interface{}{BookMatch{Language: "en-us", Text: "Welcome to Shadowrun, Fifth Edition. Welcome to the", Page: "8"}, BookMatch{Language: "de-de", Text: "Die Luft war voller Rauch, durchschnitten", Page: "8"}}},
	},
	"sg": {
		ID:        "3976dc50-f7db-481d-9372-fc2a5c1178ce",
		Name:      "Street Grimoire",
		Code:      "SG",
		Permanent: nil,
		Matches:   &BookMatches{Match: []interface{}{BookMatch{Language: "en-us", Text: "Sixth World that has developed a taste for Awakened", Page: "5"}, BookMatch{Language: "de-de", Text: "In der Sechsten Welt sind Erwachte Personen", Page: "5"}}},
	},
	"sge": {
		ID:        "ee63bbc5-2abd-4543-8371-457044bc7c63",
		Name:      "Street Grimoire Errata",
		Code:      "SGE",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "PROTECT VEHICLE SUB-HEADER", Page: "2"}},
	},
	"bb": {
		ID:        "d7b60868-41ee-4970-b9f2-f1a2a81b6d1a",
		Name:      "Bullets & Bandages",
		Code:      "BB",
		Permanent: nil,
		Matches:   &BookMatches{Match: []interface{}{BookMatch{Language: "en-us", Text: "an average troll to stand in. He was lying among a pile of", Page: "3"}, BookMatch{Language: "de-de", Text: "Kanai erwachte von dem Sirenengeheul in seinen", Page: "3"}}},
	},
	"sass": {
		ID:        "7c37e671-9d0c-48f6-aa61-891a38be18d8",
		Name:      "Sail Away, Sweet Sister",
		Code:      "SASS",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Cut to the damn chase, Eddie", Page: "2"}},
	},
	"ss": {
		ID:        "ab9fd70c-6b79-4780-ae3d-dfa5f1624c9d",
		Name:      "Stolen Souls",
		Code:      "SS",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Freedom is a prison all its own", Page: "4"}},
	},
	"rf": {
		ID:        "0b2e86c9-98b7-4265-800f-9f1b98ce7f96",
		Name:      "Run Faster",
		Code:      "RF",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Less than a day before", Page: "6"}},
	},
	"ssp": {
		ID:        "01994ce6-832f-4e29-aded-e16c1bf139bd",
		Name:      "Shadow Spells",
		Code:      "SSP",
		Permanent: nil,
		Matches:   &BookMatches{Match: []interface{}{BookMatch{Language: "en-us", Text: "The subject of magic is broad enough", Page: "3"}, BookMatch{Language: "de-de", Text: "Die nordischen Legenden sind bei den Einwohnern", Page: "4"}}},
	},
	"np": {
		ID:        "07bfdff7-1331-4791-9334-6b299548f8f4",
		Name:      "Nothing Personal",
		Code:      "NP",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "I let the warm water trickle down my body. Not warm", Page: "2"}},
	},
	"dt": {
		ID:        "c8358d1c-2eb0-461b-9e2f-b3490ad0011d",
		Name:      "Data Trails",
		Code:      "DT",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "The Matrix is the vast, wild, and wooly frontier", Page: "3"}},
	},
	"dtd": {
		ID:        "0b082117-8eb2-42d1-82e3-11454536c480",
		Name:      "Data Trails (Dissonant Echoes)",
		Code:      "DTD",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "The Matrix is the vast, wild, and wooly frontier", Page: "3"}},
	},
	"cf": {
		ID:        "cea24b81-209b-49b2-afe4-62f1286e508e",
		Name:      "Chrome Flesh",
		Code:      "CF",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "The tragedy of a shadowrunner", Page: "3"}},
	},
	"ht": {
		ID:        "B6642AC0-7E72-44C4-B954-3E224EBB2E64",
		Name:      "Hard Targets",
		Code:      "HT",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Shadowrunners will punch you in the face", Page: "5"}},
	},
	"blb": {
		ID:        "73cbd0f7-9a44-480b-8143-5c93d0b1cdf3",
		Name:      "Bloody Business",
		Code:      "BLB",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Operations in bad times are pretty much the same", Page: "5"}},
	},
	"shb": {
		ID:        "bb5c7e4e-431b-404f-89da-e69cf3b75d50",
		Name:      "Schattenhandbuch (German Handbook)",
		Code:      "SHB",
		Permanent: nil,
		Matches:   nil,
	},
	"shb2": {
		ID:        "8798c923-8118-448e-b201-53d299d7e58c",
		Name:      "Schattenhandbuch 2 (German Handbook)",
		Code:      "SHB2",
		Permanent: nil,
		Matches:   nil,
	},
	"shb3": {
		ID:        "08dea2f1-3add-4516-bdbe-b47ab9a5e31f",
		Name:      "Schattenhandbuch 3 (German Handbook)",
		Code:      "SHB3",
		Permanent: nil,
		Matches:   nil,
	},
	"r5": {
		ID:        "a1055d3f-7bc1-4ca3-a005-681c54a046a1",
		Name:      "Rigger 5.0",
		Code:      "R5",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "There are obvious uses for riggers", Page: "5"}},
	},
	"hs": {
		ID:        "38de6863-2911-4fa6-9a43-70db72ab8a22",
		Name:      "Howling Shadows",
		Code:      "HS",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "In the Sixth World, people usually assume that the thing", Page: "5"}},
	},
	"tvg": {
		ID:        "2fba52dd-bc97-450f-9d07-e1d86885911d",
		Name:      "The Vladivostok Gauntlet",
		Code:      "TVG",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "They grinned like wolves", Page: "2"}},
	},
	"sps": {
		ID:        "6b37230a-dd55-4c3f-882d-0a1c6324a457",
		Name:      "Splintered State",
		Code:      "SPS",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "FBI Agent Seth Dietrich had seen plenty of danger or", Page: "3"}},
	},
	"sfb": {
		ID:        "58b3ffae-7320-4b11-8c50-db92b7f0452b",
		Name:      "Shadows In Focus: Butte",
		Code:      "SFB",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "This isn\u2019t a run, this is a high school prank", Page: "3"}},
	},
	"hks": {
		ID:        "7186ed14-e0b8-456e-b923-f77933f1762e",
		Name:      "Hong Kong Sourcebook",
		Code:      "HKS",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Hong Kong: Neon Contrails fleshes out the sprawl", Page: "3"}},
	},
	"lcd": {
		ID:        "540cfaa8-823f-46c7-b93b-79191a894bd1",
		Name:      "Lockdown",
		Code:      "LCD",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "A breakdown of civilization, new threats, crazy danger, corporate desperation, and secrets", Page: "8"}},
	},
	"sfm": {
		ID:        "81c02566-af38-45e3-9e46-3b1d083f84f2",
		Name:      "Shadows In Focus: San Francisco Metroplex",
		Code:      "SFM",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Known for the fog rolling in off the water", Page: "3"}},
	},
	"sfme": {
		ID:        "ad384a90-33c2-40bd-b128-37117d02f36c",
		Name:      "Shadows In Focus: Metropole",
		Code:      "SFME",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "And he was ugly", Page: "3"}},
	},
	"ca": {
		ID:        "40515dbc-fec6-4530-ba79-959cc8c54c61",
		Name:      "Cutting Aces",
		Code:      "CA",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Real con artists know they never have to ask anyone", Page: "3"}},
	},
	"2050": {
		ID:        "71a6304e-03dc-41db-be01-a86acab1517b",
		Name:      "Shadowrun 2050 (5th Edition)",
		Code:      "2050",
		Permanent: nil,
		Matches:   nil,
	},
	"botl": {
		ID:        "485cc0ae-8221-4d5e-a527-33df76fd1f21",
		Name:      "Book of the Lost",
		Code:      "BOTL",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Of course there are risks!", Page: "5"}},
	},
	"fa": {
		ID:        "6e447106-e250-41b1-855a-2dd1d2075f6d",
		Name:      "Forbidden Arcana",
		Code:      "FA",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "The world of magic is infinite", Page: "6"}},
	},
	"sag": {
		ID:        "c6b7136f-e461-457b-b6f7-09e95c2f6313",
		Name:      "State of the Art ADL (German Handbook)",
		Code:      "SAG",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "de-de", Text: "ihre Hauer oftmals etwas einsch\u00fcchternd auf Norms wirkten", Page: "6"}},
	},
	"tct": {
		ID:        "c4392cc2-8edd-4ae3-8198-b8c00e693c8b",
		Name:      "The Complete Trog",
		Code:      "TCT",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "That\u2019s why trogs are taking it back.", Page: "6"}},
	},
	"sfcc": {
		ID:        "e894804c-2e11-489e-acc8-f9691a79b261",
		Name:      "Shadows In Focus: Sioux Nation: Counting Coup",
		Code:      "SFCC",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Motherfucking dammit, Charlie!", Page: "3"}},
	},
	"dtr": {
		ID:        "c74e950e-3554-4a44-9060-5a2840302538",
		Name:      "Dark Terrors",
		Code:      "DTR",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Knowing your opponent is a critical part of", Page: "6"}},
	},
	"tsg": {
		ID:        "42d5ed10-66e8-47de-8685-851fdfdcae35",
		Name:      "The Seattle Gambit",
		Code:      "TSG",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Hey, what you got in there, old man?", Page: "2"}},
	},
	"sl": {
		ID:        "bfe6c53b-1c68-4d7a-b11d-9d47461df1cd",
		Name:      "Street Lethal",
		Code:      "SL",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "There is no better way to get a shadowrunner", Page: "6"}},
	},
	"kc": {
		ID:        "35f513da-865a-45ce-a8f9-eb0336e47427",
		Name:      "Kill Code",
		Code:      "KC",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "The Matrix is not a place, but it is everywhere", Page: "6"}},
	},
	"hamg": {
		ID:        "6c97c3e8-8f13-43aa-b692-6218983c9396",
		Name:      "Hamburg (German-exclusive)",
		Code:      "HAMG",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "de-de", Text: "Willkommen in Hamburg. Willkommen in einem Sprawl voller Gefahren und M\u00f6glichkeiten.", Page: "7"}},
	},
	"btb": {
		ID:        "612af603-65e6-442c-91b8-8b8cc0c77e4a",
		Name:      "Better Than Bad",
		Code:      "BTB",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "This book is not about them", Page: "6"}},
	},
	"aet": {
		ID:        "be47e4b5-cc4f-427a-b4cd-cb5c1c8821ce",
		Name:      "Aetherology",
		Code:      "AET",
		Permanent: nil,
		Matches:   &BookMatches{Match: []interface{}{BookMatch{Language: "en-us", Text: "Once Big D offered all that nuyen for the study of danger", Page: "3"}, BookMatch{Language: "de-de", Text: "Die Ebene der Feen ist ein endloses Tal, das sich", Page: "5"}}},
	},
	"nf": {
		ID:        "e65d69fd-8717-4e2b-88b0-73bf7a22bca0",
		Name:      "No Future",
		Code:      "NF",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "There is no future", Page: "6"}},
	},
	"sotg": {
		ID:        "b20a20e5-e9d4-4f54-9caa-57a001cb904e",
		Name:      "Datapuls SOTA 2080 (German-exclusive)",
		Code:      "SOTG",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "de-de", Text: "Laserwaffen sto\u00dfen bei der Energieversorgung (noch) an ihre Grenzen", Page: "4"}},
	},
	"dpvg": {
		ID:        "3ece5592-c3c1-4cf8-97a2-ef773388289d",
		Name:      "Datapuls Verschlusssache (German-exclusive)",
		Code:      "DPVG",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "de-de", Text: "Das Verh\u00e4ltnis der Deutschen zu ihren Geheimdiensten ist kompliziert", Page: "4"}},
	},
	"kk": {
		ID:        "e997ea2e-916b-4482-a381-bf8c49cb08ff",
		Name:      "Krime Katalog",
		Code:      "KK",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "KRIME!!!!!!!", Page: "2"}},
	},
	"srm0803": {
		ID:        "2ca3c7ce-3cdb-4bf2-b430-32ecef09fda1",
		Name:      "Shadowrun Missions 0803: 10 Block Tango",
		Code:      "SRM0803",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "SRM 08-03: 10 Block Tango is a Shadowrun Missions", Page: "3"}},
	},
	"srm0804": {
		ID:        "9d69b598-4f46-46d0-be44-dd3fd8a915b0",
		Name:      "Shadowrun Missions 0804: Dirty Laundry",
		Code:      "SRM0804",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "SRM 08-04 Dirty Laundry is a Shadowrun Missions living", Page: "3"}},
	},
	"qsr": {
		ID:        "dd13ad69-51d3-4938-b4e9-703da8ee8e41",
		Name:      "Shadowrun Quick-Start Rules",
		Code:      "QSR",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "We have specifically designed these quick-start rules", Page: "2"}},
	},
	"ge": {
		ID:        "d7ac8252-fc5d-42d2-afca-2cf98ec14287",
		Name:      "Grimmes Erwachen (German-exclusive)",
		Code:      "GE",
		Permanent: nil,
		Matches:   nil,
	},
	"sw": {
		ID:        "775703af-df57-4ee2-b8e7-c6b829b80539",
		Name:      "Sprawl Wilds",
		Code:      "SW",
		Permanent: nil,
		Matches:   &BookMatches{Match: BookMatch{Language: "en-us", Text: "Gamemastering is more of an art than a science", Page: "4"}},
	},
}
