package v5

import "shadowmaster/pkg/shadowrun/edition/v5/common"

// Code generated from contacts.xml. DO NOT EDIT.

var contactsData = &ContactsChummer{
	Contacts: ContactTypesList{
		Contact: []string{
			"Amerindian Tribesperson",
			"Antiquities and Oddities Dealer",
			"Armorer",
			"Bartender",
			"Beat Cop",
			"Blogger",
			"Bodyguard",
			"Bookie",
			"Cleaner",
			"Club Hopper",
			"Club Owner",
			"Company Man",
			"Corporate Headhunter",
			"Corporate Manager",
			"Corporate Scientist",
			"Corporate Secretary",
			"Corporate Wage Slave",
			"Coyote",
			"Cult Member",
			"Dockworker",
			"Fence",
			"Firefighter",
			"Fixer",
			"Freedom Fighter",
			"Forensics Expert",
			"Gambler",
			"Gang Leader",
			"Go-Ganger",
			"Grassroots Politician",
			"Hate Group Member",
			"Hermetic Academic",
			"High Stakes Negotiator",
			"ID Manufacturer",
			"Infobroker",
			"Janitor",
			"Mafia Consiglieri",
			"Mechanic",
			"Mercenary Alchemist",
			"Mr. Johnson",
			"Nomad",
			"Ork Nation Organizer",
			"Parabotanist",
			"Parabiologist",
			"Paramed",
			"Paramed Shaman",
			"Parasecurity Expert",
			"Pawn Broker",
			"Pimp",
			"Pirate",
			"Police Chief",
			"Political Intern",
			"Radical",
			"Rent-a-Cop",
			"Shark Lawyer",
			"Simsense Star",
			"Slumlord",
			"Smuggler",
			"Snitch",
			"Spider",
			"Squatter",
			"Street Doc",
			"Street Vendor",
			"Stripper",
			"Supply Sergeant",
			"Talent Scout",
			"Talislegger",
			"Talismonger",
			"Tamanous Member",
			"Taxi Driver",
			"TerraFirst! Activist",
			"Trid Pirate",
			"Troll Street Dealer",
			"Urban Anthropologist",
			"Vory Shestiorka",
			"Wiz Kid Ganger",
		},
	},
	Genders: Genders{
		Gender: []string{
			"Female",
			"Male",
			"Unknown",
		},
	},
	Ages: Ages{
		Age: []string{
			"Young",
			"Middle-Aged",
			"Old",
			"Unknown",
		},
	},
	PersonalLives: PersonalLives{
		PersonalLife: []common.PersonalLife{
			common.PersonalLife("Divorced"),
			common.PersonalLife("Familial Relationship"),
			common.PersonalLife("In Relationship"),
			common.PersonalLife("None of Your Damn Business"),
			common.PersonalLife("Single"),
			common.PersonalLife("Widowed"),
			common.PersonalLife("Unknown"),
		},
	},
	Types: ContactTypes{
		Type: []string{
			"Legwork",
			"Networking",
			"Swag",
			"Shadow Services",
			"Personal Favors",
			"Support",
		},
	},
	PreferredPayments: PreferredPayments{
		PreferredPayment: []string{
			"Barter (Easy-to-Sell Items)",
			"Barter (Hobby/Vice Items)",
			"Barter (Profession Items)",
			"Cash (Corp Scrip)",
			"Cash (Credstick)",
			"Cash (Hard Currency)",
			"Cash (ECC)",
			"Service (Drek Jobs)",
			"Service (Free-Labor Jobs)",
			"Service (Shadowrunner Job)",
		},
	},
	HobbiesVices: HobbiesVices{
		HobbyVice: []string{
			"Animals (Paracritters)",
			"Bad Habit (Dream Chips)",
			"Bad Habit (Novacoke)",
			"Bad Habit (Trip Chips)",
			"Entertainment (Trid Shows)",
			"Entertainment (Movies)",
			"Entertainment (Music)",
			"Entertainment (Trid Show 'Odd Coven')",
			"Entertainment (Trid Reality Shows)",
			"Entertainment (RPGs, ARLARP, Graphic Novels)",
			"Entertainment (Artwork)",
			"Entertainment (Action Trideos)",
			"Family Obligations (Brother)",
			"Family Obligations (Sister)",
			"Family Obligations (Kids)",
			"Family Obligations (Parents)",
			"Gambling (Cards)",
			"Gambling (Horses)",
			"Nothing of Interest",
			"Personal Grooming (Clothes)",
			"Personal Grooming (Fashion)",
			"Personal Grooming (Shoes)",
			"Social Habit (Alcohol)",
			"Social Habit (Cigarettes)",
			"Social Habit (Cigars)",
			"Social Habit (Elven Wines)",
			"Vehicles (Cars)",
			"Vehicles (Drones)",
			"Vehicles (Antique Cars)",
			"Vehicles (Sports Cars)",
			"Weapons (Guns)",
			"Weapons (Blades)",
			"Weapons (Military)",
		},
	},
}

// GetContactsData returns the loaded contacts data.
func GetContactsData() *ContactsChummer {
	return contactsData
}
