package v5

// ContactsData contains all contact-related data from the Chummer contacts.json file.
// This data is embedded directly in the code for performance and reliability.
var ContactsData = struct {
	Contacts          []string
	Genders           []string
	Ages              []string
	PersonalLives     []string
	Types             []string
	PreferredPayments []string
	HobbiesVices      []string
}{
	Contacts: []string{
		"Amerindian Tribesperson",
		"Antiquities and Oddities Dealer",
		"Armorer",
		"Bartender",
		"Beat Cop",
		"Blogger",
		"Bodyguard",
		"Bookie",
		"Cleaner",
		"Club Hopper",
		"Club Owner",
		"Company Man",
		"Corporate Headhunter",
		"Corporate Manager",
		"Corporate Scientist",
		"Corporate Secretary",
		"Corporate Wage Slave",
		"Coyote",
		"Cult Member",
		"Dockworker",
		"Fence",
		"Firefighter",
		"Fixer",
		"Freedom Fighter",
		"Forensics Expert",
		"Gambler",
		"Gang Leader",
		"Go-Ganger",
		"Grassroots Politician",
		"Hate Group Member",
		"Hermetic Academic",
		"High Stakes Negotiator",
		"ID Manufacturer",
		"Infobroker",
		"Janitor",
		"Mafia Consiglieri",
		"Mechanic",
		"Mercenary Alchemist",
		"Mr. Johnson",
		"Nomad",
		"Ork Nation Organizer",
		"Parabotanist",
		"Parabiologist",
		"Paramed",
		"Paramed Shaman",
		"Parasecurity Expert",
		"Pawn Broker",
		"Pimp",
		"Pirate",
		"Police Chief",
		"Political Intern",
		"Radical",
		"Rent-a-Cop",
		"Shark Lawyer",
		"Simsense Star",
		"Slumlord",
		"Smuggler",
		"Snitch",
		"Spider",
		"Squatter",
		"Street Doc",
		"Street Vendor",
		"Stripper",
		"Supply Sergeant",
		"Talent Scout",
		"Talislegger",
		"Talismonger",
		"Tamanous Member",
		"Taxi Driver",
		"TerraFirst! Activist",
		"Trid Pirate",
		"Troll Street Dealer",
		"Urban Anthropologist",
		"Vory Shestiorka",
		"Wiz Kid Ganger",
	},
	Genders: []string{
		"Female",
		"Male",
		"Unknown",
	},
	Ages: []string{
		"Young",
		"Middle-Aged",
		"Old",
		"Unknown",
	},
	PersonalLives: []string{
		"Divorced",
		"Familial Relationship",
		"In Relationship",
		"None of Your Damn Business",
		"Single",
		"Widowed",
		"Unknown",
	},
	Types: []string{
		"Legwork",
		"Networking",
		"Swag",
		"Shadow Services",
		"Personal Favors",
		"Support",
	},
	PreferredPayments: []string{
		"Barter (Easy-to-Sell Items)",
		"Barter (Hobby/Vice Items)",
		"Barter (Profession Items)",
		"Cash (Corp Scrip)",
		"Cash (Credstick)",
		"Cash (Hard Currency)",
		"Cash (ECC)",
		"Service (Drek Jobs)",
		"Service (Free-Labor Jobs)",
		"Service (Shadowrunner Job)",
	},
	HobbiesVices: []string{
		"Animals (Paracritters)",
		"Bad Habit (Dream Chips)",
		"Bad Habit (Novacoke)",
		"Bad Habit (Trip Chips)",
		"Entertainment (Trid Shows)",
		"Entertainment (Movies)",
		"Entertainment (Music)",
		"Entertainment (Trid Show 'Odd Coven')",
		"Entertainment (Trid Reality Shows)",
		"Entertainment (RPGs, ARLARP, Graphic Novels)",
		"Entertainment (Artwork)",
		"Entertainment (Action Trideos)",
		"Family Obligations (Brother)",
		"Family Obligations (Sister)",
		"Family Obligations (Kids)",
		"Family Obligations (Parents)",
		"Gambling (Cards)",
		"Gambling (Horses)",
		"Nothing of Interest",
		"Personal Grooming (Clothes)",
		"Personal Grooming (Fashion)",
		"Personal Grooming (Shoes)",
		"Social Habit (Alcohol)",
		"Social Habit (Cigarettes)",
		"Social Habit (Cigars)",
		"Social Habit (Elven Wines)",
		"Vehicles (Cars)",
		"Vehicles (Drones)",
		"Vehicles (Antique Cars)",
		"Vehicles (Sports Cars)",
		"Weapons (Guns)",
		"Weapons (Blades)",
		"Weapons (Military)",
	},
}

// ExampleContacts are three example contacts demonstrating different ways to create contacts.
// These can be used as templates or examples of the Contact structure.
var (
	// ExampleContact1 is a fully random contact with all fields randomly generated
	ExampleContact1 = &Contact{
		Name:             "Johnny 'Smooth' Rodriguez",
		Type:             "Fixer",
		Level:            4,
		Loyalty:          3,
		Gender:           "Male",
		Age:              "Middle-Aged",
		PersonalLife:     "Single",
		TypeCategory:     "Networking",
		PreferredPayment: "Cash (Credstick)",
		HobbyVice:        "Gambling (Cards)",
		Notes:            "Known for setting up high-stakes runs in the downtown district.",
	}

	// ExampleContact2 is a Street Doc contact with high loyalty
	ExampleContact2 = &Contact{
		Name:             "Dr. Sarah Chen",
		Type:             "Street Doc",
		Level:            3,
		Loyalty:          5,
		Gender:           "Female",
		Age:              "Young",
		PersonalLife:     "In Relationship",
		TypeCategory:     "Support",
		PreferredPayment: "Service (Shadowrunner Job)",
		HobbyVice:        "Entertainment (Music)",
		Notes:            "Specializes in cyberware installation and emergency medical care.",
	}

	// ExampleContact3 is an Infobroker with high connection but low loyalty
	ExampleContact3 = &Contact{
		Name:             "Data Stream",
		Type:             "Infobroker",
		Level:            6,
		Loyalty:          2,
		Gender:           "Unknown",
		Age:              "Unknown",
		PersonalLife:     "None of Your Damn Business",
		TypeCategory:     "Legwork",
		PreferredPayment: "Cash (ECC)",
		HobbyVice:        "Nothing of Interest",
		Notes:            "Elusive matrix contact, only communicates through encrypted channels.",
	}
)
