package v5

// DataImprovements contains improvement records keyed by their ID (lowercase with underscores)
var DataImprovements = map[string]Improvement{
	"enable_special_attribute": {
		Name:     "Enable Special Attribute",
		ID:       "enableattribute",
		Internal: "enableattribute",
		Page:     "Unlocks the controls for an attribute, allowing the values to be increased. Expected values are MAG, RES or DEP for Magic, Resonance and Depth respectively.",
		Fields:   &ImprovementFields{Field: "SelectSpecialAttribute"},
		XML:      &[]string{"<name>{select}</name>"}[0],
	},
	"attribute": {
		Name:     "Attribute",
		ID:       "specificattribute",
		Internal: "specificattribute",
		Page:     "Adjusts the values for one of the character's Attributes. Positive numbers increase an Attribute. Negative numbers decrease an Attribute. Select an Attribute to affect by clicking the Select Value button. Value adjusts the Attribute's current value. Minimum adjusts the Metatype's minimum value for the Attribute. Maximum adjusts the Metatype's maximum value for the Attribute. Augmented Maximum Maximum adjusts the Metatype's augmented maximum value for the Attribute. Fields may be left at 0 if you do not want to affect that particular aspect of the Attribute.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectAttribute", "val", "min", "max", "aug"}},
		XML:      &[]string{"<name>{select}</name><val>{val}</val><min>{min}</min><max>{max}</max><aug>{aug}</aug>"}[0],
	},
	"replace_attribute": {
		Name:     "Replace Attribute",
		ID:       "replaceattribute",
		Internal: "replaceattributes",
		Page:     "Overrides the Metatype limitations for an attribute. Minimum adjusts the Metatype's minimum value for the Attribute. Maximum adjusts the Metatype's maximum value for the Attribute. Augmented Maximum Maximum adjusts the Metatype's augmented maximum value for the Attribute. Fields may be left at 0 if you do not want to affect that particular aspect of the Attribute.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectAttribute", "min", "max", "aug"}},
		XML:      &[]string{"<replaceattribute><name>{select}</name><min>{min}</min><max>{max}</max><aug>{aug}</aug></replaceattribute>"}[0],
	},
	"enable_spells_and_spirits_tab": {
		Name:     "Enable Spells and Spirits Tab",
		ID:       "enablemagiciantab",
		Internal: "enabletab",
		Page:     "Enables the character's Spells and Spirits tab, allowing them to buy spells and bind spirits. The character is flagged as a Magician for the purposes of quality requirements, but does not receive access to the Initiation tab, unlock their Magic attribute or receive any of the Magical skills. Incompatible with improvements that enable the Complex Forms and Sprites tab.",
		XML:      &[]string{"<name>magician</name>"}[0],
	},
	"enable_technomancer_tab": {
		Name:     "Enable Technomancer Tab",
		ID:       "enabletechnomancertab",
		Internal: "enabletab",
		Page:     "Enables the character's 'Complex Forms and Sprites' tab, allowing them to purchase Complex Forms and compile Sprites. The character is flagged as a Technomancer for the purposes of quality requirements, but does not receive access to the Submersion tab, unlock their Resonance attribute or receive any of the Resonance skills. Incompatible with improvements that enable the Spells and Spirits tab.",
		XML:      &[]string{"<name>technomancer</name>"}[0],
	},
	"force_disable_initiationsubmersion_tab": {
		Name:     "Force Disable Initiation/Submersion Tab",
		ID:       "disableinitiationtab",
		Internal: "disabletab",
		Page:     "Forcibly disables the character's Initiation or Submersion tab, forbidding them from getting metamagics or echoes.",
		XML:      &[]string{"<name>initiation</name>"}[0],
	},
	"enable_critter_tab": {
		Name:     "Enable Critter Tab",
		ID:       "enablecrittertab",
		Internal: "enabletab",
		Page:     "Enables the character's Critter Powers tab, allowing them to buy critter powers. The character is flagged as a Critter.",
		XML:      &[]string{"<name>critter</name>"}[0],
	},
	"cyber_singularity_seekerredliner_attribute": {
		Name:     "Cyber-Singularity Seeker/Redliner (Attribute)",
		ID:       "cyberseeker",
		Internal: "cyberseeker",
		Page:     "Grants bonuses to the specified attribute based on the number of cyberlimbs a character has. Special attributes are invalid",
		Fields:   &ImprovementFields{Field: "SelectAttribute"},
		XML:      &[]string{"{select}"}[0],
	},
	"cyber_singularity_seekerredliner_condition_monitor": {
		Name:     "Cyber-Singularity Seeker/Redliner (Condition Monitor)",
		ID:       "cyberseeker",
		Internal: "cyberseeker",
		Page:     "Grants bonuses to the character's physical Condition Monitor based on the number of cyberlimbs a character has. See Redliner in Chrome Flesh for more details.",
		XML:      &[]string{"BOX"}[0],
	},
	"condition_monitor_physical": {
		Name:     "Condition Monitor, Physical",
		ID:       "conditionmonitorphysical",
		Internal: "conditionmonitor",
		Page:     "Adjusts the number of boxes the character has in their Physical Condition Monitor. Positive numbers increase the number of boxes in the Condition Monitor. Negative numbers reduce the number of boxes in the Condition Monitor.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<physical>{val}</physical>"}[0],
	},
	"condition_monitor_stun": {
		Name:     "Condition Monitor, Stun",
		ID:       "conditionmonitorstun",
		Internal: "conditionmonitor",
		Page:     "Adjusts the number of boxes the character has in their Stun Condition Monitor. Positive numbers increase the number of boxes in the Condition Monitor. Negative numbers reduce the number of boxes in the Condition Monitor.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<stun>{val}</stun>"}[0],
	},
	"condition_monitor_threshold": {
		Name:     "Condition Monitor, Threshold",
		ID:       "conditionmonitorthreshold",
		Internal: "conditionmonitor",
		Page:     "Adjusts the number of boxes between each Condition Monitor Threshold. Positive numbers increase the number of boxes between each Threshold. Negative numbers reduce the number of boxes between each Threshold.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<threshold>{val}</threshold>"}[0],
	},
	"condition_monitor_threshold_offset": {
		Name:     "Condition Monitor, Threshold Offset",
		ID:       "conditionmonitoroffset",
		Internal: "conditionmonitor",
		Page:     "Adjusts the number of boxes between the start of each Condition Monitor and the first Threshold. Positive numbers increase the starting position of the first Threshold. Negative numbers reduce the starting position of each Threshold.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<thresholdoffset>{val}</thresholdoffset>"}[0],
	},
	"block_skillgroup_defaulting": {
		Name:     "Block Skillgroup Defaulting",
		ID:       "blockskillgroupdefaulting",
		Internal: "blockskillgroupdefaulting",
		Page:     "Prevents the character from seeing dicepool values for skills in the selected skillgroup.",
		Fields:   &ImprovementFields{Field: "SelectSkillGroup"},
	},
	"attribute_level": {
		Name:     "Attribute Level",
		ID:       "attributelevel",
		Internal: "attributelevel",
		Page:     "Adds to the selected attribute's base Value, increasing Karma costs for subsequent purchases.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectAttribute", "val"}},
		XML:      &[]string{"<name>{select}</name><val>{val}</val>"}[0],
	},
	"skill_level": {
		Name:     "Skill Level",
		ID:       "skilllevel",
		Internal: "skilllevel",
		Page:     "Adds to the selected attribute's base Value, increasing Karma costs for subsequent purchases.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectSkill", "val"}},
		XML:      &[]string{"<name>{select}</name><val>{val}</val>"}[0],
	},
	"knowsoft": {
		Name:     "KnowSoft",
		ID:       "knowsoft",
		Internal: "knowsoft",
		Page:     "Creates a Knowledge Skill that requires the skillsoftaccess improvement to be activated.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectKnowSkill", "val"}},
		XML:      &[]string{"<name>{select}</name><val>{val}</val><require>skilljack</require>"}[0],
	},
	"adept_power": {
		Name:     "Adept Power",
		ID:       "specificpower",
		Internal: "specificpower",
		Page:     "Creates a free Adept Power. If the selected power already exists, the power will either be marked as free, or have free levels added to it.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectAdeptPower", "val", "free"}},
		XML:      &[]string{"<name>{select}</name><val>{val}</val><free>{free}</free>"}[0],
	},
	"living_persona_device_rating": {
		Name:     "Living Persona, Device Rating",
		ID:       "livingpersonadevicerating",
		Internal: "livingpersona",
		Page:     "Adjusts the Living Persona's Device Rating by the value entered. Positive numbers improve the Device Rating. Negative numbers reduce the Device Rating. You may enter XPath operations as well. This has no effect on characters that do not have a Living Persona.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<devicerating>{val}</devicerating>"}[0],
	},
	"living_persona_program_limit": {
		Name:     "Living Persona, Program Limit",
		ID:       "livingpersonaprogramlimit",
		Internal: "livingpersona",
		Page:     "Adjusts the Living Persona's Program Limit by the value entered. Positive numbers improve the Program Limit. Negative numbers reduce the Program Limit. You may enter XPath operations as well. This has no effect on characters that do not have a Living Persona.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<programlimit>{val}</programlimit>"}[0],
	},
	"living_persona_attack": {
		Name:     "Living Persona, Attack",
		ID:       "livingpersonaattack",
		Internal: "livingpersona",
		Page:     "Adjusts the Living Persona's Attack by the value entered. Positive numbers improve Attack. Negative numbers reduce Attack. You may enter XPath operations as well. This has no effect on characters that do not have a Living Persona.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<attack>{val}</attack>"}[0],
	},
	"living_persona_sleaze": {
		Name:     "Living Persona, Sleaze",
		ID:       "livingpersonasleaze",
		Internal: "livingpersona",
		Page:     "Adjusts the Living Persona's Sleaze by the value entered. Positive numbers improve Sleaze. Negative numbers reduce Sleaze. You may enter XPath operations as well. This has no effect on characters that do not have a Living Persona.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<sleaze>{val}</sleaze>"}[0],
	},
	"living_persona_data_processing": {
		Name:     "Living Persona, Data Processing",
		ID:       "livingpersonadataprocessing",
		Internal: "livingpersona",
		Page:     "Adjusts the Living Persona's Data Processing by the value entered. Positive numbers improve Data Processing. Negative numbers reduce Data Processing. You may enter XPath operations as well. This has no effect on characters that do not have a Living Persona.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<dataprocessing>{val}</dataprocessing>"}[0],
	},
	"living_persona_firewall": {
		Name:     "Living Persona, Firewall",
		ID:       "livingpersonafirewall",
		Internal: "livingpersona",
		Page:     "Adjusts the Living Persona's Firewall by the value entered. Positive numbers improve Firewall. Negative numbers reduce Firewall. You may enter XPath operations as well. This has no effect on characters that do not have a Living Persona.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"<firewall>{val}</firewall>"}[0],
	},
	"skill": {
		Name:     "Skill",
		ID:       "specificskill",
		Internal: "specificskill",
		Page:     "Adjusts the value for one of the character's Skills by the value entered. Positive numbers increase the Skill. Negative numbers decrease the Skill. Select a Skill to affect by clicking the Select Value button. The modifier can be applied to the Skill's Rating by selecting Apply to Rating, otherwise the modifier is applied as a dice pool modifier.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectSkill", "val", "applytorating"}},
		XML:      &[]string{"<name>{select}</name><bonus>{val}</bonus>{applytorating}"}[0],
	},
	"skills_in_category": {
		Name:     "Skills in Category",
		ID:       "skillcategory",
		Internal: "skillcategory",
		Page:     "Adjusts the value for all of the Skills in one category by the value entered. Positive numbers increase the Skills. Negative numbers decrease the Skills. Select a Skill category to affect by clicking the Select Value button. The modifier can be applied to the Skills' Ratings by selecting Apply to Rating, otherwise the modifier is applied as a dice pool modifier.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectSkillCategory", "val", "applytorating"}},
		XML:      &[]string{"<name>{select}</name><bonus>{val}</bonus>{applytorating}"}[0],
	},
	"skills_in_group": {
		Name:     "Skills in Group",
		ID:       "skillgroup",
		Internal: "skillgroup",
		Page:     "Adjusts the value for all of the Skills in a Skill Group by the value entered. Positive numbers increase the Skills. Negative numbers decrease the Skills. Select a Skill Group to affect by clicking the Select Value button. The modifier can be applied to the Skills' Ratings by selecting Apply to Rating, otherwise the modifier is applied as a dice pool modifier.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectSkillGroup", "val", "applytorating"}},
		XML:      &[]string{"<name>{select}</name><bonus>{val}</bonus>{applytorating}"}[0],
	},
	"skills_linked_to_attribute": {
		Name:     "Skills linked to Attribute",
		ID:       "skillattribute",
		Internal: "skillattribute",
		Page:     "Adjusts the value for all of the Skills linked to an Attribute by the value entered. Positive numbers increase the Skills. Negative numbers decrease the Skills. Select a linked Attribute to affect by clicking the Select Value button. The modifier can be applied to the Skills' Ratings by selecting Apply to Rating, otherwise the modifier is applied as a dice pool modifier.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectAttribute", "val", "applytorating"}},
		XML:      &[]string{"<name>{select}</name><bonus>{val}</bonus>{applytorating}"}[0],
	},
	"armor": {
		Name:     "Armor",
		ID:       "armor",
		Internal: "armor",
		Page:     "Adjusts the character's Armor Rating by the value entered. Positive numbers improve Armor. Negative numbers reduce Armor.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"reach": {
		Name:     "Reach",
		ID:       "reach",
		Internal: "reach",
		Page:     "Adjusts the character's Reach by the value entered. Positive numbers increase Reach. Negative numbers reduce Reach.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"unarmed_dv": {
		Name:     "Unarmed DV",
		ID:       "unarmeddv",
		Internal: "unarmeddv",
		Page:     "Adjusts the Damage Value for a character's Unarmed Attacks by the value entered. Positive numbers increase the Damage Value. Negative numbers decrease the Damage Value.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"unarmed_dv_physical": {
		Name:     "Unarmed DV Physical",
		ID:       "unarmeddvphysical",
		Internal: "unarmeddvphysical",
		Page:     "All of the character's Unarmed Attacks will do Physical damage instead of Stun damage.",
	},
	"unarmed_ap": {
		Name:     "Unarmed AP",
		ID:       "unarmedap",
		Internal: "unarmedap",
		Page:     "Adjusts the Armor Penetration value for a character's Unarmed Attacks by the value entered. Positive numbers reduce Armor Penetration. Negative numbers increase Armor Penetration.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"initiative": {
		Name:     "Initiative",
		ID:       "initiative",
		Internal: "initiative",
		Page:     "Adjusts the character's Initiative by the value entered. Positive numbers increase Initiative. Negative numbers reduce Initiative.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"initiative_dice": {
		Name:     "Initiative Dice",
		ID:       "initiativediceadd",
		Internal: "initiativediceadd",
		Page:     "Adjusts the number of Initiative Dice the character receives by the value entered. Positive numbers increase the number of Initiative Dice. Negative numbers reduce the number of Initiative Dice.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"matrix_initiative": {
		Name:     "Matrix Initiative",
		ID:       "matrixinitiative",
		Internal: "matrixinitiative",
		Page:     "Adjusts the character's Matrix Initiative by the value entered. Positive numbers increase Matrix Initiative. Negative numbers reduce Matrix Initiative.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"matrix_initiative_passes": {
		Name:     "Matrix Initiative Passes",
		ID:       "matrixinitiativediceadd",
		Internal: "matrixinitiativediceadd",
		Page:     "Adjusts the number of Matrix Initiative Passes the character receives by the value entered. Positive numbers increase the number of Matrix Initiative Passes. Negative numbers reduce the number of Matrix Initiative Passes.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"lifestyle_cost": {
		Name:     "Lifestyle Cost",
		ID:       "lifestylecost",
		Internal: "lifestylecost",
		Page:     "Adjusts the Nuyen cost of all Lifestyles by the percent value entered. All Lifestyles will now cost an additional X% per month. Positive number increase the Lifestyle's monthly Nuyen cost. Negative numbers reduce the Lifestyle's monthly Nuyen cost.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"genetech_cost": {
		Name:     "Genetech Cost",
		ID:       "genetechcostmultiplier",
		Internal: "genetechcostmultiplier",
		Page:     "Adjusts the Nuyen cost of Bioware in the Genetech categories by the percent value entered. All Genetech Nuyen costs will now be X% of their original value. Numbers lower than 100 reduce the Nuyen cost. Numbers higher than 100 increase the Nuyen cost.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"basic_bioware_essence_cost": {
		Name:     "Basic Bioware Essence Cost",
		ID:       "basicbiowareessmultiplier",
		Internal: "basicbiowareessmultiplier",
		Page:     "Adjusts the Essence cost of Bioware in the Basic category by the percent value entered. All Basic Bioware Essence costs will now be X% of their original value. Numbers lower than 100 reduce the Essence cost. Numbers higher than 100 increase the Essence cost.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"bioware_essence_cost": {
		Name:     "Bioware Essence Cost",
		ID:       "biowareessmultiplier",
		Internal: "biowareessmultiplier",
		Page:     "Adjusts the Essence cost of Bioware by the percent value entered. All Bioware Essence costs will now be X% of their original value. Numbers lower than 100 reduce the Essence cost. Numbers higher than 100 increase the Essence cost.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"genetech_essence_cost": {
		Name:     "Genetech Essence Cost",
		ID:       "genetechessmultiplier",
		Internal: "genetechessmultiplier",
		Page:     "Adjusts the Essence cost of Genetech by the percent value entered. All Genetech Essence costs will now be X% of their original value. Numbers lower than 100 reduce the Essence cost. Numbers higher than 100 increase the Essence cost.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"cyberware_essence_cost": {
		Name:     "Cyberware Essence Cost",
		ID:       "cyberwareessmultiplier",
		Internal: "cyberwareessmultiplier",
		Page:     "Adjusts the Essence cost of Cyberware by the percent value entered. All Cyberware Essence costs will now be X% of their original value. Numbers lower than 100 reduce the Essence cost. Numbers higher than 100 increase the Essence cost.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"weapon_category_dv": {
		Name:     "Weapon Category DV",
		ID:       "weaponcategorydv",
		Internal: "weaponcategorydv",
		Page:     "Adjusts the Damage Value of all Weapons in the selected category by the value entered. Positive numbers increase Weapon Damage Value. Negative numbers decrease Weapon Damage Value.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectWeaponCategory", "val"}},
		XML:      &[]string{"<name>{select}</name><bonus>{val}</bonus>"}[0],
	},
	"power_points_free_spirit": {
		Name:     "Power Points, Free Spirit",
		ID:       "freespiritpowerpoints",
		Internal: "freespiritpowerpoints",
		Page:     "Adjusts the number of Power Points a Free Spirit receives to spend on Critter Powers by the value entered. Positive numbers increase the number of Power Points. Negative numbers decrease the number of Power Points. This has no effect on non-Free Spirit characters.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"power_points_adept": {
		Name:     "Power Points, Adept",
		ID:       "adeptpowerpoints",
		Internal: "adeptpowerpoints",
		Page:     "Adjusts the number of Power Points an Adept receives to spend on Adept Powers by the value entered. Positive numbers increase the number of Power Points. Negative numbers decrease the number of Power Points. This has no effect on non-Adept characters.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"armor_encumbrance_penalty": {
		Name:     "Armor Encumbrance Penalty",
		ID:       "armorencumbrancepenalty",
		Internal: "armorencumbrancepenalty",
		Page:     "Adjusts the character's Armor Encumbrance penalty by the value entered. Positive numbers increase the Armor Encumbrance penalty (bad). Negative numbers decrease the Armor Encumbrance penalty (good).",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"damage_resistance": {
		Name:     "Damage Resistance",
		ID:       "damageresistance",
		Internal: "damageresistance",
		Page:     "Adjusts the size of the character's Damage Resistance Test dice pool by the value entered. Positive numbers increase the size of the pool. Negative numbers decrease the size of the pool.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"judge_intentions": {
		Name:     "Judge Intentions",
		ID:       "judgeintentions",
		Internal: "judgeintentions",
		Page:     "Adjusts the character's Judge Intentions Special Attribute by the value entered. Positive numbers improve Judge Intentions. Negative numbers reduce Judge Intentions.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"composure": {
		Name:     "Composure",
		ID:       "composure",
		Internal: "composure",
		Page:     "Adjusts the character's Composure Special Attribute by the value entered. Positive numbers improve Composure. Negative numbers reduce Composure.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"lift_and_carry": {
		Name:     "Lift and Carry",
		ID:       "liftandcarry",
		Internal: "liftandcarry",
		Page:     "Adjusts the character's Lift and Carry Special Attribute by the value entered. Positive numbers improve Lift and Carry. Negative numbers reduce Lift and Carry.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"memory": {
		Name:     "Memory",
		ID:       "memory",
		Internal: "memory",
		Page:     "Adjusts the character's Memory Special Attribute by the value entered. Positive numbers improve Memory. Negative numbers reduce Memory.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"concealability": {
		Name:     "Concealability",
		ID:       "concealability",
		Internal: "concealability",
		Page:     "Adjusts the character's ability to conceal Weapons by the value entered. This bonus applies to the Concealability of all Weapons. Positive values improve Concealability. Negative values reduce Concealability.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"drain_resistance": {
		Name:     "Drain Resistance",
		ID:       "drainresist",
		Internal: "drainresist",
		Page:     "Adjusts the size of the character's Drain Resistance pool by the value entered. Positive values increase the size of the pool. Negative values decrease the size of the pool.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"fading_resistance": {
		Name:     "Fading Resistance",
		ID:       "fadingresist",
		Internal: "fadingresist",
		Page:     "Adjusts the size of the character's Fading Resistance pool by the value entered. Positive values increase the size of the pool. Negative values decrease the size of the pool.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"spells_in_category": {
		Name:     "Spells in Category",
		ID:       "spellcategory",
		Internal: "spellcategory",
		Page:     "Adjusts the size of the character's Spellcasting pool when casting Spell in the selected category. Positive values improve Spellcasting. Negative values reduce Spellcasting.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectSpellCategory", "val"}},
		XML:      &[]string{"<name>{select}</name><val>{val}</val>"}[0],
	},
	"specific_spell_dicepool": {
		Name:     "Specific Spell Dicepool",
		ID:       "spelldicepool",
		Internal: "spelldicepool",
		Page:     "Adjusts the size of the character's Spellcasting pool when casting the Spell with the selected name. Positive values improve Spellcasting. Negative values reduce Spellcasting.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectSpell", "val"}},
		XML:      &[]string{"<name>{select}</name><val>{val}</val>"}[0],
	},
	"skillsoft_access": {
		Name:     "Skillsoft Access",
		ID:       "skillsoftaccess",
		Internal: "skillsoftaccess",
		Page:     "The character can use Knowsoft and Linguasoft Skillsofts as though they had a direct neural link.",
	},
	"essence_maximum": {
		Name:     "Essence Maximum",
		ID:       "essencemax",
		Internal: "essencemax",
		Page:     "Adjusts the character's Maximum Essence by the value entered. Positive values increase Maximum Essence. Negative values decrease Maximum Essence.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"throwing_weapon_range": {
		Name:     "Throwing Weapon Range",
		ID:       "throwrange",
		Internal: "throwrange",
		Page:     "Adjusts a character's STR for the purpose of determining the range of Throwing Weapons. Positive numbers increase the character's effective STR. Negative numbers reduce the character's effective STR.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"skillwire_rating": {
		Name:     "Skillwire Rating",
		ID:       "skillwire",
		Internal: "skillwire",
		Page:     "Grants the character access to Skillwires at the specified Rating which limits the effective Rating of all Skillsofts the character takes.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"swap_skill_attribute_physical_for_mental": {
		Name:     "Swap Skill Attribute (Physical for Mental)",
		ID:       "swapskillattribute",
		Internal: "swapskillattribute",
		Page:     "Swaps the Physical Attribute used by Active Skills with the corresponding Mental Attribute as described in the Astral Attributes table on SR4 192. (AGI/LOG; BOD/WIL; REA/INT; STR/CHA)",
		Fields:   &ImprovementFields{Field: "SelectPhysicalAttribute"},
		XML:      &[]string{"<attribute>{select}</attribute>"}[0],
	},
	"quickening": {
		Name:     "Quickening",
		ID:       "quickeningmetamagic",
		Internal: "quickeningmetamagic",
		Page:     "Grants the character access to Quickening in the same manner as the Quickening Metamagic.",
	},
	"basic_lifestyle_cost": {
		Name:     "Basic Lifestyle Cost",
		ID:       "basiclifestylecost",
		Internal: "basiclifestylecost",
		Page:     "Adjusts the Nuyen cost of all basic Lifestyles by the percent value entered. All basic Lifestyles will now cost an additional X% per month. Basic Lifestyles are only those found in the SR4 book and do not include Advanced Lifestyles, Safehouses, or Bolt Holes. Positive number increase the basic Lifestyle's monthly Nuyen cost. Negative numbers reduce the basic Lifestyle's monthly Nuyen cost.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"throwing_weapon_str": {
		Name:     "Throwing Weapon STR",
		ID:       "throwstr",
		Internal: "throwstr",
		Page:     "Adjusts a character's STR for the purpose of determining the DV of Throwing Weapons. Positive numbers increase the character's effective STR. Negative numbers reduce the character's effective STR.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"knowledge_skill": {
		Name:     "Knowledge Skill",
		ID:       "specificknowskill",
		Internal: "specificskill",
		Page:     "Adjusts the value for one of the character's Knowledge Skills by the value entered. Positive numbers increase the Knowledge Skill. Negative numbers decrease the Knowledge Skill. Select a Knowledge Skill to affect by clicking the Select Value button. The modifier can be applied to the Knowledge Skill's Rating by selecting Apply to Rating, otherwise the modifier is applied as a dice pool modifier.",
		Fields:   &ImprovementFields{Field: []interface{}{"SelectKnowSkill", "val", "applytorating"}},
		XML:      &[]string{"<name>{select}</name><bonus>{val}</bonus>{applytorating}"}[0],
	},
	"ignore_condition_monitor_penalty_stun": {
		Name:     "Ignore Condition Monitor Penalty, Stun",
		ID:       "ignorecmpenaltystun",
		Internal: "ignorecmpenaltystun",
		Page:     "Reduces the characters Stun Condition Monitor Penalty to 0 while the Improvement is active.",
	},
	"ignore_condition_monitor_penalty_physical": {
		Name:     "Ignore Condition Monitor Penalty, Physical",
		ID:       "ignorecmpenaltyphysical",
		Internal: "ignorecmpenaltyphysical",
		Page:     "Reduces the characters Physical Condition Monitor Penalty to 0 while the Improvement is active.",
	},
	"street_cred_multiplier": {
		Name:     "Street Cred Multiplier",
		ID:       "streetcredmultiplier",
		Internal: "streetcredmultiplier",
		Page:     "Increases or reduces the multiplier used to calculate Street Cred.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"bonus_street_cred": {
		Name:     "Bonus Street Cred",
		ID:       "streetcred",
		Internal: "streetcred",
		Page:     "Increases the character's Street Cred by the listed value.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"dodge": {
		Name:     "Dodge",
		ID:       "dodge",
		Internal: "dodge",
		Page:     "Increases the character's Dodge pool by the listed value.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"enable_cyberzombie_conversion": {
		Name:     "Enable Cyberzombie Conversion",
		ID:       "enablecyberzombie",
		Internal: "enablecyberzombie",
		Page:     "Allows the character to be converted into a Cyberzombie.",
	},
	"free_spells": {
		Name:     "Free Spells",
		ID:       "freespells",
		Internal: "freespells",
		Page:     "Allows the character to mark some spells as Free, avoiding Karma costs.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"mental_limit": {
		Name:     "Mental Limit",
		ID:       "mentallimit",
		Internal: "mentallimit",
		Page:     "Adjusts the character's Mental Limit by the listed value.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"physical_limit": {
		Name:     "Physical Limit",
		ID:       "physicallimit",
		Internal: "physicallimit",
		Page:     "Adjusts the character's Physical Limit by the listed value.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"social_limit": {
		Name:     "Social Limit",
		ID:       "sociallimit",
		Internal: "sociallimit",
		Page:     "Adjusts the character's Social Limit by the listed value.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
	"walk_multiplier": {
		Name:     "Walk Multiplier",
		ID:       "walkmultiplier",
		Internal: "walkmultiplier",
		Page:     "Increases the walking speed of a character for a particular category of movement. Positive numbers increase the factor by which attributes are multiplied to get walking speeds. Negative numbers decrease the factor by which attributes are multiplied to get walking speeds. Category can be Ground, Swim, or Fly for walking speed on land, in water, and in the air respectively. Value increases the walking factor by a fixed amount. Percent increases the walking factor by a percentage amount. Fields may be left at 0 if you do not want to affect walking speed in that particular way.",
		Fields:   &ImprovementFields{Field: []interface{}{"category", "val", "percent"}},
		XML:      &[]string{"<category>{category}</category><val>{val}</val><percent>{percent}</percent>"}[0],
	},
	"run_multiplier": {
		Name:     "Run Multiplier",
		ID:       "runmultiplier",
		Internal: "runmultiplier",
		Page:     "Increases the running speed of a character for a particular category of movement. Positive numbers increase the factor by which attributes are multiplied to get running speeds. Negative numbers decrease the factor by which attributes are multiplied to get running speeds. Category can be Ground, Swim, or Fly for running speed on land, in water, and in the air respectively. Value increases the running factor by a fixed amount. Percent increases the running factor by a percentage amount. Fields may be left at 0 if you do not want to affect running speed in that particular way.",
		Fields:   &ImprovementFields{Field: []interface{}{"category", "val", "percent"}},
		XML:      &[]string{"<category>{category}</category><val>{val}</val><percent>{percent}</percent>"}[0],
	},
	"sprint_bonus": {
		Name:     "Sprint Bonus",
		ID:       "sprintbonus",
		Internal: "sprintbonus",
		Page:     "Increases the sprinting speed of a character for a particular category of movement. Positive numbers increase the number of meters sprinted per hit. Negative numbers decrease the number of meters sprinted per hit. Category can be Ground, Swim, or Fly for sprinting speed on land, in water, and in the air respectively. Value increases sprinted meters per hit by a fixed amount. Percent increases the sprinted meters per hit by a percentage amount. Fields may be left at 0 if you do not want to affect sprinting speed in that particular way.",
		Fields:   &ImprovementFields{Field: []interface{}{"category", "val", "percent"}},
		XML:      &[]string{"<category>{category}</category><val>{val}</val><percent>{percent}</percent>"}[0],
	},
	"add_metamagic": {
		Name:     "Add Metamagic",
		ID:       "addmetamagic",
		Internal: "addmetamagic",
		Page:     "Adds a free metamagic to the character. Any metamagic can be added, even ones for which the character would not be normally eligible.",
		Fields:   &ImprovementFields{Field: "SelectMetamagic"},
	},
	"add_echo": {
		Name:     "Add Echo",
		ID:       "addecho",
		Internal: "addecho",
		Page:     "Adds a free echo to the character. Any echo can be added, even ones for which the character would not be normally eligible.",
		Fields:   &ImprovementFields{Field: "SelectEcho"},
	},
	"add_spell": {
		Name:     "Add Spell",
		ID:       "addspell",
		Internal: "addspell",
		Page:     "Adds a free spell to the character. Any spell can be added, even ones for which the character would not be normally eligible.",
		Fields:   &ImprovementFields{Field: "SelectSpell"},
	},
	"add_complex_form": {
		Name:     "Add Complex Form",
		ID:       "addcomplexform",
		Internal: "addcomplexform",
		Page:     "Adds a free Complex Form to the character. Any Complex Form can be added, even ones for which the character would not be normally eligible.",
		Fields:   &ImprovementFields{Field: "SelectComplexForm"},
	},
	"surprise": {
		Name:     "Surprise",
		ID:       "surprise",
		Internal: "surprise",
		Page:     "Adjusts the character's Surprise dicepool by the value entered. Positive numbers improve the dicepool. Negative numbers reduce the dicepool.",
		Fields:   &ImprovementFields{Field: "val"},
		XML:      &[]string{"{val}"}[0],
	},
}
