package v5

// dataKnowledgeSkills contains all knowledge skill definitions
var dataKnowledgeSkills = map[string]Skill{
	// Knowledge Skills
	"black_market_pipelines": {
		Name:            "Black Market Pipelines",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Knowledge of black market networks, smuggling routes, and how to move illegal goods through the shadows. This skill covers understanding who moves what, where, and how to access these networks.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"organized_crime": {
		Name:            "Organized Crime",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Knowledge of organized crime syndicates, their structures, territories, key figures, and operations. This skill helps identify crime families, understand their hierarchies, and navigate criminal networks.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"smugglers": {
		Name:            "Smugglers",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Knowledge of smugglers, their methods, routes, and contacts. This skill helps identify who moves contraband, how they operate, and where to find them.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"city_knowledge": {
		Name:            "[City] Knowledge",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Knowledge of a specific city, including its neighborhoods, landmarks, local customs, power structures, and notable locations. This skill must be taken once per city.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"magic_groups": {
		Name:            "Magic Groups",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Knowledge of magical organizations, traditions, secret societies, and magical groups. This skill covers understanding different magical traditions, their practices, and key figures in the magical community.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"runner_hangouts": {
		Name:            "Runner Hangouts",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Knowledge of shadowrunner meeting places, safe houses, bars, and locations where shadowrunners gather. This skill helps identify where to find work, contacts, and other runners.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"street_gang_identification": {
		Name:            "Street Gang Identification",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Knowledge of street gangs, their territories, colors, symbols, and members. This skill helps identify gang affiliations, understand gang hierarchies, and navigate gang-controlled areas.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"dragons": {
		Name:            "Dragons",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Knowledge of dragons, their histories, known dragons, their activities, and draconic culture. This skill covers understanding the great dragons and their impact on the Sixth World.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"mr_johnsons": {
		Name:            "Mr. Johnsons",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Knowledge of fixers, Mr. Johnsons, and those who hire shadowrunners. This skill helps identify who's hiring, their reputations, typical pay rates, and how to find work.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"corporate_politics": {
		Name:            "Corporate Politics",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Professional knowledge of corporate structures, politics, alliances, and rivalries. This skill covers understanding how megacorporations operate, their internal politics, and inter-corporate relationships.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"parazoology": {
		Name:            "Parazoology",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Academic knowledge of parazoological creatures, their behaviors, habitats, and characteristics. This skill covers understanding awakened animals, critters, and magical creatures.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"corporate_security": {
		Name:            "Corporate Security",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Professional knowledge of corporate security procedures, systems, and protocols. This skill covers understanding how corporations protect their assets, typical security measures, and how to bypass them.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"national_politics": {
		Name:            "National Politics",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Professional knowledge of national governments, political systems, key political figures, and international relations. This skill covers understanding how nations operate and interact in the Sixth World.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"vices": {
		Name:            "Vices",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Street knowledge of vices, illegal substances, gambling, and other illicit activities. This skill covers understanding what's available, where to find it, and who deals in various vices.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"fixers": {
		Name:            "Fixers",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Street knowledge of fixers, their networks, specialties, and how to work with them. This skill helps identify reliable fixers, understand their operations, and navigate the shadow economy.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"magical_theory": {
		Name:            "Magical Theory",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Academic knowledge of magical theory, principles, and how magic works. This skill covers understanding mana, astral space, magical traditions, and theoretical aspects of magic.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"wilderness_survival": {
		Name:            "Wilderness Survival",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeIntuition,
		Description:     "Knowledge of surviving in wilderness environments, including finding food, water, shelter, and navigating natural hazards. This skill covers understanding different biomes and survival techniques.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"riggers": {
		Name:            "Riggers",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Professional knowledge of riggers, their equipment, techniques, and the rigger community. This skill covers understanding vehicle modifications, drone operations, and rigger culture.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"magic_threats": {
		Name:            "Magic Threats",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Academic knowledge of magical threats, including toxic spirits, blood magic, dangerous magical phenomena, and how to identify and deal with them. This skill covers understanding various magical dangers in the Sixth World.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"chemistry": {
		Name:            "Chemistry",
		Type:            SkillTypeKnowledge,
		Category:        SkillCategoryKnowledge,
		LinkedAttribute: AttributeLogic,
		Description:     "Academic knowledge of chemical compounds, reactions, and properties. This skill covers understanding how chemicals interact, identifying substances, and theoretical chemistry principles.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{},
		IsSpecific:      false,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
}
