package v5

// dataLanguageSkills contains all language skill definitions
var dataLanguageSkills = map[string]Skill{
	// Language Skills
	"sperethiel": {
		Name:            "Sperethiel",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Sperethiel is the elven language, used by elves throughout the Sixth World. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"russian": {
		Name:            "Russian",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Russian is a language spoken in Russia and parts of Eastern Europe. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"orzet": {
		Name:            "Or'zet",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Or'zet is the ork language, developed by orks in the Sixth World. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"french": {
		Name:            "French",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "French is a language spoken in France, Quebec, and other regions. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"english": {
		Name:            "English",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "English is a widely spoken language in the Sixth World, particularly in North America and the United Kingdom. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"italian": {
		Name:            "Italian",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Italian is a language spoken in Italy and other regions. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"japanese": {
		Name:            "Japanese",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Japanese is a language spoken in Japan and by Japanese corporations worldwide. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"german": {
		Name:            "German",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "German is a language spoken in Germany, Austria, and other regions. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"mandarin": {
		Name:            "Mandarin",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Mandarin is a Chinese language spoken in China and by Chinese communities worldwide. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"aztlaner_spanish": {
		Name:            "Aztlaner Spanish",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Aztlaner Spanish is a variant of Spanish spoken in Aztlan. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"spanish": {
		Name:            "Spanish",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Spanish is a language spoken in Spain, Latin America, and other regions. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"lakota": {
		Name:            "Lakota",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Lakota is a Native American language spoken by the Lakota people. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"dakota": {
		Name:            "Dakota",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Dakota is a Native American language spoken by the Dakota people. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
	"dine": {
		Name:            "Diné",
		Type:            SkillTypeLanguage,
		Category:        SkillCategoryLanguage,
		LinkedAttribute: AttributeIntuition,
		Description:     "Diné (Navajo) is a Native American language spoken by the Diné people. Characters who speak multiple languages must purchase a separate language skill for each language.",
		CanDefault:      true,
		SkillGroup:      "",
		Specializations: []string{"Read/Write", "Speak", "by dialect", "by lingo"},
		IsSpecific:      true,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "",
		},
	},
}
