package v5

// DataLifeModuleStages contains life module stage records keyed by their ID (lowercase with underscores)
var DataLifeModuleStages = map[string]LifeModuleStage{
	"nationality": {
		Content: "Nationality",
		Order:   "1",
	},
	"formative_years": {
		Content: "Formative Years",
		Order:   "2",
	},
	"teen_years": {
		Content: "Teen Years",
		Order:   "3",
	},
	"further_education": {
		Content: "Further Education",
		Order:   "4",
	},
	"real_life": {
		Content: "Real Life",
		Order:   "5",
	},
}

// DataLifeModules contains life module records keyed by their ID (lowercase with underscores)
var DataLifeModules = map[string]LifeModule{
	"united_canadian_american_states": {
		ID:       "f35ba316-dd0f-48ab-9f06-d7329305a44e",
		Stage:    "Nationality",
		Category: "LifeModule",
		Name:     "United Canadian American States",
		Karma:    "15",
		Source:   "RF",
		Page:     "66",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil},
		Story:    "Allan, please add story UCAS",
	},
	"confederation_of_american_states": {
		ID:       "85f1c4ab-5f3c-411c-8c01-8ee54e2d4f89",
		Stage:    "Nationality",
		Category: "LifeModule",
		Name:     "Confederation of American States",
		Karma:    "15",
		Source:   "RF",
		Page:     "66",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil},
		Story:    "$real was born in the Confederation of American States, a nation formed after the south finally got around to rising again.",
	},
	"tír_tairngire": {
		ID:       "83c132b5-fcf5-4a43-b9de-6c8ab206a586",
		Stage:    "Nationality",
		Category: "LifeModule",
		Name:     "T\u00edr Tairngire",
		Karma:    "15",
		Source:   "RF",
		Page:     "67",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AddQualities: nil},
		Story:    "$real was born in Tir Tairngire, $TIRDESC .",
	},
	"native_american_nations": {
		ID:       "67023613-54af-4950-9a6e-a33bee9ecf59",
		Stage:    "Nationality",
		Category: "LifeModule",
		Name:     "Native American Nations",
		Karma:    "15",
		Source:   "RF",
		Page:     "67",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil},
		Story:    "$real was born in the northern part of America, in the Native American Nations",
	},
	"arcology_living": {
		ID:       "924ccfd0-136c-4385-94fe-a8d7be2eb7ed",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Arcology Living",
		Karma:    "40",
		Source:   "RF",
		Page:     "67",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was  $LUCK  enough to grow up in an Arcology: a corporate fortress city that $ARCOLOGY.",
	},
	"corp_drone": {
		ID:       "14c2accf-2875-4239-a5be-47dce27312eb",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Corp Drone",
		Karma:    "40",
		Source:   "RF",
		Page:     "68",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real was  $LUCK  enough to be the child of wageslaves, who via endless hours of toil managed to keep a roof over $real 's head.",
	},
	"farm_living": {
		ID:       "111f66cd-be47-4e1e-8ee7-15cc67ed2cc8",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Farm Living",
		Karma:    "40",
		Source:   "RF",
		Page:     "68",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real spent their formative years on a farm, not moving around hay like the farmhands of yesteryear, but instead $FARMDESC.",
	},
	"fugitive": {
		ID:       "f98daafb-cf5f-4d83-976b-8cb9a49f1c4f",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Fugitive",
		Karma:    "40",
		Source:   "RF",
		Page:     "68",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real spent their formative years with their parents as they ran away from $FLEE.",
	},
	"isolated_rural_upbringing": {
		ID:       "f2435c28-5bf9-4c72-8f6d-f5d02439833b",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Isolated Rural Upbringing",
		Karma:    "40",
		Source:   "RF",
		Page:     "68",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real grew up in an isolated portion of the wilderness like the rednecks of old.",
	},
	"military_brat": {
		ID:       "7acbd745-50d4-4fb1-839c-65a6f07e1e50",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Military Brat",
		Karma:    "40",
		Source:   "RF",
		Page:     "69",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real grew up almost everywhere, shifted from place to place by their $PARRENT 's military duties.",
	},
	"orphan": {
		ID:       "06b4cc0f-3008-4209-ac32-04614a3dc354",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Orphan",
		Karma:    "40",
		Source:   "RF",
		Page:     "69",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real was an orphan, growing up either in a $ORPHAN or on the streets.",
	},
	"rich_kid": {
		ID:       "4f078a7f-bfa5-4eba-97f9-a97f06eab6e8",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Rich Kid",
		Karma:    "40",
		Source:   "RF",
		Page:     "69",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was literally born with a gold spoon in their mouth, and looked down on those with silver spoons, as those could tarnish.",
	},
	"street_urchin": {
		ID:       "fe3d36d3-6e0a-4d65-8516-3350f1b5b812",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Street Urchin",
		Karma:    "40",
		Source:   "RF",
		Page:     "69",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was a child of the streets, best described with words like plucky or $INSULTA.",
	},
	"white_collar": {
		ID:       "1521128b-0b5e-41ce-a2dd-61512f2dff2c",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "White Collar",
		Karma:    "40",
		Source:   "RF",
		Page:     "69",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real had fairly well off parents who paid for a better than average education.",
	},
	"corporate_education": {
		ID:       "f0393b9e-2698-4955-bd31-112b619ac7b8",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Corporate Education",
		Karma:    "50",
		Source:   "RF",
		Page:     "70",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real was educated by a megacorp so that he might make a better wageslave when he graduated.",
	},
	"farm_living_1": {
		ID:       "07797a05-d7a7-4f49-b69f-3f79aec242f3",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Farm Living",
		Karma:    "50",
		Source:   "RF",
		Page:     "70",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real spent their teenage years on a farm, $FARMTASK .",
	},
	"gang_warfare": {
		ID:       "8d4a26a0-8280-42d8-b61d-052591f84edd",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Gang Warfare",
		Karma:    "50",
		Source:   "RF",
		Page:     "70",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real spent their teenage years shooting at other teenagers just to gain control over a few city blocks. Just to be clear, $real was in a gang, not the Battle of Stalingrad.",
	},
	"high_school": {
		ID:       "abf41e28-123f-bb00-da29-124ce213dca2",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "High School",
		Karma:    "50",
		Source:   "RF",
		Page:     "71",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real went to high school like a normal person.",
	},
	"home_tutored": {
		ID:       "68fdb83d-5447-4414-b2ff-2377873521b5",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Home Tutored",
		Karma:    "50",
		Source:   "RF",
		Page:     "70",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was taught at home, by $HOMEDESC . While they managed to avoid the main pitfall of homeschooling and somehow ended up with a better education than their peers, $real was left emotionally stunted due to the lack of contact with others.",
	},
	"isolated_rural_upbringing_1": {
		ID:       "0f415a05-5a6f-4279-9fb4-c43e0435bab5",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Isolated Rural Upbringing",
		Karma:    "50",
		Source:   "RF",
		Page:     "71",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real spent their teenage years in the middle of nowhere, leaving them with very little knowledge of the outside world, but a lot of knowledge about $OUTDOOR .",
	},
	"magical_education_magician": {
		ID:       "ccf41ccc-f752-469b-ad92-5bdc38e6714f",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Magical Education (Magician)",
		Karma:    "50",
		Source:   "RF",
		Page:     "71",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was identified as awakened at an early age and was sent off to a wizarding school that, sadly, was much less awesome than Hogwarts.",
	},
	"magical_education_aspected": {
		ID:       "1d2a61a6-3fd0-4c07-9a9e-8db5da92590e",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Magical Education (Aspected)",
		Karma:    "50",
		Source:   "RF",
		Page:     "71",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was identified as awakened at an early age and was sent off to a wizarding school that, sadly, was much less awesome than Hogwarts.",
	},
	"magical_education_mystic_adept": {
		ID:       "abbd6496-e90f-4159-a677-e4b35ccd05f9",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Magical Education (Mystic Adept)",
		Karma:    "50",
		Source:   "RF",
		Page:     "71",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was identified as awakened at an early age and was sent off to a wizarding school that, sadly, was much less awesome than Hogwarts.",
	},
	"magical_education_adept": {
		ID:       "603bead6-2827-4468-a69b-4e8a7a93c2ee",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Magical Education (Adept)",
		Karma:    "50",
		Source:   "RF",
		Page:     "71",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was identified as awakened at an early age and was sent off to a wizarding school that, sadly, was much less awesome than Hogwarts.",
	},
	"military_school": {
		ID:       "15bd4283-f287-4be7-b174-9e5ab97bda1a",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Military School",
		Karma:    "50",
		Source:   "RF",
		Page:     "71",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was educated at a military school designed to instill discipline and patriotism in those  $LUCK  to be sent there.",
	},
	"preparatory_school": {
		ID:       "b3b641d1-70e2-46c9-99b3-b89b7b84e24c",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Preparatory School",
		Karma:    "50",
		Source:   "RF",
		Page:     "71",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was $LUCK enough to go to a respected private school.",
	},
	"street_kid": {
		ID:       "21c3cb79-e0d9-49b8-9ad3-9232bab4f12b",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Street Kid",
		Karma:    "50",
		Source:   "RF",
		Page:     "72",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real graduated summa cum laude from the school of hard knocks, with a major in $STREETDESC and a minor in women's studies.",
	},
	"skipped_further_education": {
		ID:       "5a2eee69-cedb-403e-9649-fdc9a1377374",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Skipped Further Education",
		Karma:    "0",
		Source:   "RF",
		Page:     "0",
		Story:    "$real either never received the opportunity for a further education, or decided it wasn't for them. Either way, the wide range of life's choices spread before them!",
	},
	"community_college": {
		ID:       "9e601908-df9a-4fe1-b58e-74bfd6f5d7b5",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Community College",
		Karma:    "55",
		Source:   "RF",
		Page:     "72",
		Versions: &LifeModuleVersions{Version: nil},
		Story:    "$real wanted to get something that resembled higher education, but couldn't afford to go to a real college. The solution: community college.",
	},
	"ivy_league_university": {
		ID:       "1156fac7-e8d2-4599-94c3-64b8464037d7",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Ivy League University",
		Karma:    "80",
		Source:   "RF",
		Page:     "73",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real either had a scholarship or money to burn, because they managed to get into one of the most exclusive institutions in the country, gaining them a first class education, as well as something nice to put on their resume.",
	},
	"military_academy": {
		ID:       "87ad3d80-8d96-4c16-aa62-d63eb2575ff3",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Military Academy",
		Karma:    "115",
		Source:   "RF",
		Page:     "73",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real got into a military academy, where they trained to become a commissioned officer in the army of their country.",
	},
	"state_university": {
		ID:       "142d7a1b-c676-4bf6-a71f-bc2d29617a14",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "State University",
		Karma:    "65",
		Source:   "RF",
		Page:     "75",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real was either not intelligent enough for the ivy league, or unable to afford it. Either way, they got into one of the many other colleges out there.",
	},
	"tradetechnical_school": {
		ID:       "3f82fc4f-9cbf-4baf-a8a2-51ab9c75a7f6",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Trade/Technical School",
		Karma:    "40",
		Source:   "RF",
		Page:     "75",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil},
		Story:    "Not even capable of making it into a community college, $real had to settle for a trade school, which taught practical things they could use in their future life.",
	},
	"bounty_hunter": {
		ID:       "47bf63cf-9a2a-4008-b455-c8ab68add581",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Bounty Hunter",
		Karma:    "100",
		Source:   "RF",
		Page:     "76",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real became a bounty hunter, stalking people who skip out on their bail. On the plus side, they might have gotten to star in a shitty reality trideo.",
	},
	"celebrity": {
		ID:       "efae10db-297b-4355-97f0-e64b4bb21a23",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Celebrity",
		Karma:    "100",
		Source:   "RF",
		Page:     "76",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real became famous because they $FAMOUSDESC .",
	},
	"combat_correspondent": {
		ID:       "47f4572b-8199-47dd-a997-77e7c1bbc297",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Combat Correspondent",
		Karma:    "100",
		Source:   "RF",
		Page:     "76",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real decided that muckraking with the Corp's filth was too likely to get them silenced, so they decided to go for an easier job: covering foreign wars.",
	},
	"corporate": {
		ID:       "adeea2d5-ef7a-4852-81da-627197a31dd2",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Corporate",
		Karma:    "100",
		Source:   "RF",
		Page:     "77",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real got a job at $RMEGA , becoming another gear in the corporate machine.",
	},
	"cover_operations": {
		ID:       "81e2f441-c13d-4cfd-815f-d27daf1dfc82",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Cover Operations",
		Karma:    "100",
		Source:   "RF",
		Page:     "77",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was an genuine secret agent, spying on $ENTITY for $ENTITY",
	},
	"drifter": {
		ID:       "8b103553-5ad9-4183-a09b-d17983dc5df6",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Drifter",
		Karma:    "100",
		Source:   "RF",
		Page:     "77",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real decided getting a job just wasn't for them, instead choosing to couchsurf, or possibly live in their mother's basement.",
	},
	"ganger": {
		ID:       "a29aa9fa-d06e-4d5d-9d82-ae8a386fa4a4",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Ganger",
		Karma:    "100",
		Source:   "RF",
		Page:     "78",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real became a criminal, their main income coming from selling other people's cyber-VCRs, and occasionally mugging people and stealing the money they got by selling cyber-VCRs.",
	},
	"government_agent": {
		ID:       "3fb24f67-9d15-49d8-a598-5abbea335e8b",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Government Agent",
		Karma:    "100",
		Source:   "RF",
		Page:     "78",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real somehow managed to get a job with one of the few government organizations that hasn't yet been privatized. Be it with the FBI, MI5, NSA, TAO, Unit 61398, or some other organization, they get to be paid less than normal people in return for working longer hours and being hated by everyone.",
	},
	"law_enforcement": {
		ID:       "92eb874c-f932-403c-a33d-00f3f083c3cc",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Law Enforcement",
		Karma:    "100",
		Source:   "RF",
		Page:     "78",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real  $COPDESC",
	},
	"organized_crime": {
		ID:       "0f4b3ba5-c4db-4906-8d39-c2afe92c5c65",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Organized Crime",
		Karma:    "100",
		Source:   "RF",
		Page:     "78",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AddQualities: nil},
		Story:    "$real decided the best way to wealth and power was also the most brutal: organized crime. Specializing in $GANGDESC , $real became well known in the $GANGTYPE",
	},
	"political_activist": {
		ID:       "a2fb0e59-3921-432c-ac9c-ae4c3ac0145a",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Political Activist",
		Karma:    "100",
		Source:   "RF",
		Page:     "79",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was one of the most dangerous things in the world: an idealist. Working for a small policlub or interest group, they got arrested multiple times in their quest to make the world a better place.",
	},
	"postgraduate_studies": {
		ID:       "304aa6bb-031b-4042-9258-4b4c4de09fc3",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Postgraduate Studies",
		Karma:    "100",
		Source:   "RF",
		Page:     "79",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real surfaced from the waters of academia, looked at the real world, said nope, and went straight back into academia.",
	},
	"private_investigatordetective": {
		ID:       "5e300502-2485-4cde-9aff-21c50d120738",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Private Investigator/Detective",
		Karma:    "100",
		Source:   "RF",
		Page:     "79",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real overdosed on $CRIMEDESC decided to become a private investigator.",
	},
	"regular_job": {
		ID:       "85d549a0-4057-426f-b146-c2fd3dde5c9b",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Regular Job",
		Karma:    "100",
		Source:   "RF",
		Page:     "79",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real got a job, exchanging labor for currency like a normal person.",
	},
	"shadow_work_shadowrunner": {
		ID:       "406ee650-fa40-4bf0-9e5f-77b7f9b37b23",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Shadow Work (Shadowrunner)",
		Karma:    "100",
		Source:   "RF",
		Page:     "80",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{AttributeLevel: nil},
		Story:    "$real is more than a criminal for hire: they're a very expensive criminal for hire, with multiple break-ins, kidnappings, and assassinations on their resume.",
	},
	"street_magic": {
		ID:       "30179edf-9494-498a-bdba-52947e011585",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Street Magic",
		Karma:    "100",
		Source:   "RF",
		Page:     "80",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{AttributeLevel: nil},
		Story:    "$real decided to put his awakened talents to some other use than for the corps.",
	},
	"terrorist": {
		ID:       "011c1897-2bde-47f4-89d3-c28df64501ba",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Terrorist",
		Karma:    "100",
		Source:   "RF",
		Page:     "81",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real decided activism is for fools. The only way to get your voice heard is force. Blowing up pubs, executing civilians, assassinations, $real has done it all.",
	},
	"think_tank": {
		ID:       "81b605dd-dd60-4a41-bf77-e7fe706b04f6",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Think Tank",
		Karma:    "100",
		Source:   "RF",
		Page:     "81",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real is an intellectual whore, paid by megacorps to explain why $MEGAWHORE .",
	},
	"tour_of_duty_mercenary": {
		ID:       "da7c24fa-689a-4bd2-b83a-85196024ba44",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Tour of Duty (Mercenary)",
		Karma:    "100",
		Source:   "RF",
		Page:     "82",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real worked as a mercenary, fighting for fun and profit instead of for freedom or prophets.",
	},
	"tour_of_duty_nan": {
		ID:       "c81a2706-4b08-4ce4-bc0d-adb42634c59f",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Tour of Duty (NAN)",
		Karma:    "100",
		Source:   "RF",
		Page:     "82",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real signed on with the armed forces of one of the NANs, fighting to defend their freedom from $WARNAN .",
	},
	"tour_of_duty_tír_tairngire": {
		ID:       "61b6f290-95d2-4cfd-b7d6-336782a42c1b",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Tour of Duty (T\u00edr Tairngire)",
		Karma:    "100",
		Source:   "RF",
		Page:     "83",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was a greenshirt in service of the Tir, fighting to preserve quite possibly the most dysfunctional nation on the continent.",
	},
	"tour_of_duty_ucas_cas_and_cfs": {
		ID:       "f1770715-63ea-45cb-bc08-061996dbb6be",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Tour of Duty (UCAS, CAS and CFS)",
		Karma:    "100",
		Source:   "RF",
		Page:     "82",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was a soldier in service of the UCAS, CAS or CFS, training and drilling for the day the Azzies push north through the NANs so that they might be ready to\u2026 liberate them.",
	},
	"early_emergence": {
		ID:       "4b56f994-84d5-4acc-8d6f-278eae90f624",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Early Emergence",
		Karma:    "40",
		Source:   "DT",
		Page:     "51",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real was coding before other kids could read, emerging as a technomancer around the age normal kids are working out that $ALPHABET",
	},
	"part_of_the_machine": {
		ID:       "eb8c935b-6e60-475b-b909-27f6d7f54a8f",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Part of the Machine",
		Karma:    "40",
		Source:   "DT",
		Page:     "51",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real grew up among mechanics, and some of their skill brushed off on him. On the downside, so did a lot of $STICKY.",
	},
	"hacker_club": {
		ID:       "cb023d87-0312-4a50-a17d-87444fed10da",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Hacker Club",
		Karma:    "50",
		Source:   "DT",
		Page:     "51",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real grew up in a commune of hackers, who taught him the basics of hacking, and nothing else.",
	},
	"technomancer_boarding_school": {
		ID:       "91abc09e-7564-4126-9c03-15d26989dcf8",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Technomancer Boarding School",
		Karma:    "50",
		Source:   "DT",
		Page:     "51",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real was lucky enough that their Emergence was noticed by one of the more techno friendly corporations, who gave them a free scholarship to a school that taught them how to use their powers instead of just black bagging and vivisecting them to see how they tick.",
	},
	"escaped_technomancer": {
		ID:       "e40f60aa-2269-4d3d-a34b-e2be24af496d",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Escaped Technomancer",
		Karma:    "100",
		Source:   "DT",
		Page:     "52",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was blackbagged by a corp who wanted to take $real apart and see how they tick. Fortunately, they managed to escape, and even got to keep most of their organs.",
	},
	"hacker_assassin": {
		ID:       "aaa6ec70-467e-4345-b5e1-f14ce038ef51",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Hacker Assassin",
		Karma:    "100",
		Source:   "DT",
		Page:     "52",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real serves the Old Man of the Mountain via the matrix, hitting their enemies with enough biofeedback to leave their enemies brain leaking out of their ears.",
	},
	"hacker_hobbyist": {
		ID:       "b8aea58a-e447-46f6-b96d-cf3bf3ff19e4",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Hacker Hobbyist",
		Karma:    "100",
		Source:   "DT",
		Page:     "53",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real hacks as a hobby, cracking code with nothing but sheer willpower and a lot of mountain dew.",
	},
	"high_profile_hack": {
		ID:       "3d08b696-1c7c-4bb6-af37-1b4d68fd985c",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "High-Profile Hack",
		Karma:    "100",
		Source:   "DT",
		Page:     "53",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real pulled off a big job. How big? I shit you not, they $HACKDESC .",
	},
	"it_ace": {
		ID:       "ac0eb0cc-bae1-41e4-bffd-e684c5f51b2b",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "IT Ace",
		Karma:    "100",
		Source:   "DT",
		Page:     "53",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real had the misfortune to work as a sysadmin, an unappreciated job where one has to somehow fulfill requests made by people without even the most basic computer knowledge.",
	},
	"matrix_ghost": {
		ID:       "243b126d-a71e-4398-b646-76780b6e7379",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Matrix Ghost",
		Karma:    "100",
		Source:   "DT",
		Page:     "53",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real is an expert at staying unseen in the matrix, especially when it comes to $MATRIXHIDE .",
	},
	"otaku_time": {
		ID:       "3c0549e6-d58a-4658-a7e5-4593ac8f1388",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Otaku Time",
		Karma:    "100",
		Source:   "DT",
		Page:     "53",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was an Otaku. No, not a Japanese nerd, but instead a child of the Matrix. Thankfully, Crash 2.0 hit before they suffered Fading, leaving them as a Technomancer, allowing them to keep their odd connection to the matrix for the rest of their life.",
	},
	"slave": {
		ID:       "c211d6f3-c773-4ff7-a1a1-64b16f47757e",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Slave",
		Karma:    "40",
		Source:   "CF",
		Page:     "60",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was a slave, and spent their childhood $SLAVE",
	},
	"bag_of_organs": {
		ID:       "d91ba242-11bb-43a9-abed-4cb5c6b34819",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Bag of Organs",
		Karma:    "40",
		Source:   "CF",
		Page:     "60",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was used as a host for bioware, as implanting it in a metahuman is cheaper than keeping it on ice. One day, $real knew they would be killed, and their organs $BAGORGAN . On the other hand, free bioware! Score!",
	},
	"child_of_the_shadows": {
		ID:       "f8413f32-3ed3-488f-989a-2fe961e94dee",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Child of the Shadows",
		Karma:    "40",
		Source:   "CF",
		Page:     "61",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real 's parents were shadowrunners. At a young age, $real was learning important skills such as $SHADOWCHILD .",
	},
	"test_subject": {
		ID:       "a576c25e-2ca1-4d53-83de-1b58e9f72082",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Test Subject",
		Karma:    "50",
		Source:   "CF",
		Page:     "61",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real grew up a lab rat, used by mad scientists to test augmentations. On one hand, $real essence was irreparably shredded. On the other hand free ware! Score!",
	},
	"factory_child_worker": {
		ID:       "737d188a-85b5-47d8-91f2-39863983b464",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Factory Child Worker",
		Karma:    "50",
		Source:   "CF",
		Page:     "61",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real was a child laborer in one of the few factories that hadn't fully mechanized. Their pay almost managed to pay for limbs to replace those they lost via work. Almost.",
	},
	"pit_fighter": {
		ID:       "70fe2ad0-1311-486c-b183-8b2620fc5056",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Pit Fighter",
		Karma:    "100",
		Source:   "CF",
		Page:     "61",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real fought in a blood sport, punching the shit out of other people for fun and profit.",
	},
	"urban_brawler": {
		ID:       "4e6da910-e160-4aec-8dfb-caafda2e952e",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Urban Brawler",
		Karma:    "100",
		Source:   "CF",
		Page:     "61",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real fought in Urban Brawl, which, despite all appearances, is somehow not a blood sport. It did, however, teach them quite a lot of things about $URBANBRAWL .",
	},
	"street_doc": {
		ID:       "b94d89fc-7ade-4942-9f85-b56c2f78847e",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Street Doc",
		Karma:    "100",
		Source:   "CF",
		Page:     "61",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real may very well only have a doctorate in fine arts, if they have one at all, but they still somehow manage to make it as a street doc, as asking no questions and working on the cheap is considered more important than actual medical training in some circles. Zoidberg would be proud.",
	},
	"caribbean_league": {
		ID:       "efdee4d0-f6fb-4d75-816e-859e85ec29d4",
		Stage:    "Nationality",
		Category: "LifeModule",
		Name:     "Caribbean League",
		Karma:    "15",
		Source:   "HT",
		Page:     "138",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil},
	},
	"shanghaied": {
		ID:       "cf75cd28-5992-40d4-a9b4-837f3b3c4867",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Shanghaied",
		Karma:    "50",
		Source:   "HT",
		Page:     "138",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was conscripted onto a ship.",
	},
	"pirate_captain": {
		ID:       "445984f2-d607-4124-afd3-b7c536016caa",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Pirate Captain",
		Karma:    "100",
		Source:   "HT",
		Page:     "138",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was a crime boss of the sea.",
	},
	"pirate_crewmember": {
		ID:       "caf84e62-05cd-4638-81d2-6d788f303e36",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Pirate Crewmember",
		Karma:    "100",
		Source:   "HT",
		Page:     "139",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real was a pirate on the high seas.",
	},
	"bocor_slave": {
		ID:       "923cf93a-7892-43b5-8b2a-9b2cfba11acd",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Bocor Slave",
		Karma:    "100",
		Source:   "HT",
		Page:     "139",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was imprisoned with vodou, living life as a zombie.",
	},
	"assassins_apprentice": {
		ID:       "469157a3-d76d-46d9-9562-031a48baa2be",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Assassin's Apprentice",
		Karma:    "100",
		Source:   "HT",
		Page:     "200",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real spent time as a triggerman's assistant.",
	},
	"guardian_angel": {
		ID:       "67f740bd-b3a8-40d0-9590-2a3d0d90d0da",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Guardian Angel",
		Karma:    "100",
		Source:   "HT",
		Page:     "200",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real had a change of heart and instead of killing people for money protected people for free.",
	},
	"ritual_killer": {
		ID:       "716c4baf-5944-46da-8c1e-905ccd8962fc",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Ritual Killer",
		Karma:    "100",
		Source:   "HT",
		Page:     "200",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real used ritual magic to complete contracts.  Quite scary.",
	},
	"minor_wheelman": {
		ID:       "95b89172-5189-4841-9e89-c14754336382",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Minor Wheelman",
		Karma:    "40",
		Source:   "R5",
		Page:     "34",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was driving before other kids could read the street signs, emerging as one of the best getaway drivers around the age normal kids were learning traffic signals",
	},
	"shop_kid": {
		ID:       "195a5953-42ee-40ab-80fd-8c5e4c9d5fac",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Shop Kid",
		Karma:    "40",
		Source:   "R5",
		Page:     "35",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "Tinkering was what $real lived for. It started with simply identifying the limited cars in the neighborhood. From there scavenging parts and putting them back together. Totally self taught $real worked their way into shops if they weren't chased off",
	},
	"booster": {
		ID:       "cc16eb63-8930-42ed-ac1a-390bd5ccc2d3",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Booster",
		Karma:    "50",
		Source:   "R5",
		Page:     "35",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "By the time $real was a teen, they were stealing cars to order, driving the boosts to any one of the chop shops in the city. Now, when $real sees a new car in the 'hood, what $real sees is the fee in Nuyen",
	},
	"drone_hobbyist": {
		ID:       "95504862-5150-4360-87fa-9086269cbdce",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Drone Hobbyist",
		Karma:    "100",
		Source:   "R5",
		Page:     "35",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real flies drones in competitions around the city. Taking jobs using their drones on the side to help pay for upgrades",
	},
	"getaway_driver": {
		ID:       "e070e446-b3fd-4446-aa3a-35e73417ef06",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Getaway Driver",
		Karma:    "100",
		Source:   "R5",
		Page:     "35",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "Need a driver for that job you want doing? Feel the need for a getaway? Contact $real at getawaydriver.me for all your driving needs, flat rates for routes inside [CITY]",
	},
	"trid_stunt_driver": {
		ID:       "e7ec9b76-54c0-4dfd-8329-741bcc6abce8",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Trid Stunt Driver",
		Karma:    "100",
		Source:   "R5",
		Page:     "35",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "Need a driver for that TRI-D you're financing? Contact $real at actor-driver.me for all your driving needs.",
	},
	"brothel_child": {
		ID:       "e80c51ca-d71e-47e5-91e4-22bff1a0d330",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Brothel Child",
		Karma:    "40",
		Source:   "CA",
		Page:     "103",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real was brought up in a syndicate-run brothel with the help of $real's many \"aunts\". They taught $real to be polite and discreet, so as to never be seen by the clients, and some of the many languages $real heard during this time stuck with $real.",
	},
	"con_prop": {
		ID:       "8f17dd9b-6dc4-419a-94be-584ef6f24e41",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Con Prop",
		Karma:    "40",
		Source:   "CA",
		Page:     "103",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil},
		Story:    "$real's parents were con artists, and the best thing to happen to them was $real. Who would ever suspect two doting parents and their lovely child? Who wouldn't pay attention to a terrified child that had \"lost their parents\"? With a cute animal or two added to the mix, $real could distract the best of them.",
	},
	"the_easiest_mark": {
		ID:       "8da867a2-29cd-440f-b567-ef32cbe0da30",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "The Easiest Mark",
		Karma:    "50",
		Source:   "CA",
		Page:     "103",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real's parents never saw it coming. $real sold them out and milked them for all they had. $real was the invincible, the best in the world... at least, according to $real's assessment. It wasn't a walk in the park to constantly stay under the law's radar, but $real managed, even with the occasional unwelcome thoughts about $real's parents creeping into $real's mind.",
	},
	"mr_johnson": {
		ID:       "e04175cd-7fde-4e10-83e3-4952a209f956",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Mr. Johnson",
		Karma:    "100",
		Source:   "CA",
		Page:     "103",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real is a professional Johnson. $real's job is to be the line between civilization - $real's corporation - and the necessary evil of the wild men, the savages of the street.",
	},
	"spy": {
		ID:       "814c5115-d978-4a20-8123-7e746ce52983",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Spy",
		Karma:    "100",
		Source:   "CA",
		Page:     "104",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real is a real spy, a working spy. $real is embedded where they need to be, undercover, and keeps an eye out for documents their handlers want, always being cautious, discreet, and misleading.",
	},
	"escort": {
		ID:       "01438e64-30aa-4555-8b24-0833dfdcad99",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Escort",
		Karma:    "100",
		Source:   "CA",
		Page:     "104",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "An escort is nothing as vulgar as a prostitute: prostitutes sell their flesh, $real sells an experience. $real knows how to set the mood, to build something up, to be something the rich and powerful must seem to have to earn and conquer.",
	},
	"street_preacher": {
		ID:       "9ac85595-f57c-4197-86c2-e2c9e8b37ea0",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Street Preacher",
		Karma:    "100",
		Source:   "CA",
		Page:     "104",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "A flood is coming that will wash away the filth from the streets, and $real has a message of salvation to deliver. Their mission is paramount, they know it. $real understands that salvation comes from odd angles in these godless times, and that they might have to do unconventional things for the greater good. $real's body is strong, and their resolve is stronger.",
	},
	"amazonian": {
		ID:       "36b14645-f416-4598-ae10-f60f80d93155",
		Stage:    "Nationality",
		Category: "LifeModule",
		Name:     "Amazonian",
		Karma:    "15",
		Source:   "SFME",
		Page:     "31",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{KnowledgeSkillLevel: nil},
		Story:    "$real was born in eastern South America, in the country now known as Amazonia.",
	},
	"anarchist_brat": {
		ID:       "7b009ba2-dbd6-47a2-a13f-28709a625374",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Anarchist Brat",
		Karma:    "40",
		Source:   "SAG",
		Page:     "148",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was brought up consistently exposed to the Anarchist's way of seeing the world.",
	},
	"life_on_the_coast": {
		ID:       "66b0b6d9-1afb-4218-92b9-54d529905639",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Life on the Coast",
		Karma:    "40",
		Source:   "SAG",
		Page:     "148",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was brought up in one of the few small coastal towns around the world.",
	},
	"life_by_the_toxic_sea": {
		ID:       "99b853b4-62f5-40ba-9d61-e6f853f6d0c1",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Life by the Toxic Sea",
		Karma:    "40",
		Source:   "SAG",
		Page:     "148",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was brought up in proximity to of the world's many blighted coasts.",
	},
	"migratory_background": {
		ID:       "169485e7-4598-44c6-816a-d9282c18c9a0",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Migratory Background",
		Karma:    "40",
		Source:   "SAG",
		Page:     "148",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real and their family may have been war refugees or hoping for a better life elsewhere, as they where leaving their home country. You are part of the next generation, brought in between two cultures.",
	},
	"religious_upbringing": {
		ID:       "32f753ce-0696-45e2-8a65-9f62d583feb9",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Religious Upbringing",
		Karma:    "40",
		Source:   "SAG",
		Page:     "148",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was brought up in a strictly religious family.",
	},
	"anarcho_teen": {
		ID:       "746cde0e-1ca3-46ae-96b6-cb3971656673",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Anarcho-Teen",
		Karma:    "50",
		Source:   "SAG",
		Page:     "150",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real spent their teen years living the anarchist life.",
	},
	"life_on_the_coast_1": {
		ID:       "feaaa9a3-774e-4a6c-9a83-968da043c06d",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Life on the Coast",
		Karma:    "50",
		Source:   "SAG",
		Page:     "150",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real spent his teen years living in a small coastal town, working in the fishing industry.",
	},
	"life_by_the_toxic_sea_1": {
		ID:       "f0523ed1-9d9b-48fe-957c-1f64079d4e41",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Life by the Toxic Sea",
		Karma:    "50",
		Source:   "SAG",
		Page:     "150",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real spent his teen years helping his small community at the toxic coast.",
	},
	"religious_school": {
		ID:       "cb3be5ba-587f-4009-a19b-0b6b40ab6bda",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Religious School",
		Karma:    "50",
		Source:   "SAG",
		Page:     "151",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
		Story:    "$real spent his teen years in a private, religious school.",
	},
	"religious_study": {
		ID:       "256848e3-c5eb-4e5f-b8b1-85efcc52d596",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Religious Study",
		Karma:    "80",
		Source:   "RF",
		Page:     "72",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{AttributeLevel: nil},
		Story:    "$real achieved their higher education via their religious community.",
	},
	"craft_apprenticeship": {
		ID:       "7eef2cb1-e0f7-4e99-8fdb-92bd453f1a7c",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Craft Apprenticeship",
		Karma:    "55",
		Source:   "RF",
		Page:     "72",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{AttributeLevel: nil},
		Story:    "$real achieved their higher education via their religious community.",
	},
	"orktroll_slum_dweller": {
		ID:       "db8443eb-94e0-4922-a2a2-f3824e4f6e2c",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Ork/Troll Slum Dweller",
		Karma:    "40",
		Source:   "TCG",
		Page:     "189",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real lived in the sprawl and learned how to survive in difficult circumstances.",
	},
	"black_forest_baby": {
		ID:       "054a1a00-7745-495b-86b0-301c7917ac76",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Black Forest Baby",
		Karma:    "40",
		Source:   "TCG",
		Page:     "190",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was born in the Black Forest Kingdom and saw it evolve into the Black Forest Troll Republic.",
	},
	"trog_ganger": {
		ID:       "ce6dbac8-6016-44dc-90f0-719a8928bf98",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Trog Ganger",
		Karma:    "50",
		Source:   "TCG",
		Page:     "190",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was involved in trog gangs.",
	},
	"survivor": {
		ID:       "a9007966-38dd-429f-a661-cff06a776729",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Survivor",
		Karma:    "50",
		Source:   "TCG",
		Page:     "190",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real had a tough set of teen years but managed to survive.",
	},
	"biloxi_technical_institute": {
		ID:       "9220f169-be3f-48f1-bfa3-cb7fb4dec985",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Biloxi Technical Institute",
		Karma:    "65",
		Source:   "TCG",
		Page:     "190",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real had a tough set of teen years but managed to survive.",
	},
	"trog_professional": {
		ID:       "6b55f9a1-257f-4ee2-b735-7a61772c8a3c",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Trog Professional",
		Karma:    "100",
		Source:   "TCG",
		Page:     "191",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real worked for a corp.",
	},
	"trog_rebel": {
		ID:       "d20c08f7-0e54-4a48-bd61-31279d99689f",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Trog Rebel",
		Karma:    "100",
		Source:   "TCG",
		Page:     "191",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real spent time rebelling against society with explosives.",
	},
	"student_athlete": {
		ID:       "c674ae2c-e5ef-4bfa-8993-884769560644",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Student Athlete",
		Karma:    "55",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
		Story:    "$real was a student athlete.",
	},
	"professional_athlete": {
		ID:       "51a990d8-3e7b-497e-b6dc-6b85ab3d1fe6",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Professional Athlete",
		Karma:    "100",
		Source:   "NF",
		Page:     "178",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"teen_diva": {
		ID:       "392b5600-34ac-40a9-a246-f3b5a11689ee",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Teen Diva",
		Karma:    "100",
		Source:   "NF",
		Page:     "179",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"azanian_confederation": {
		ID:       "baa9a6cc-2fb8-49d3-b503-d1f74bd0d915",
		Stage:    "Nationality",
		Category: "LifeModule",
		Name:     "Azanian Confederation",
		Karma:    "15",
		Source:   "BTB",
		Page:     "162",
		Versions: &LifeModuleVersions{Version: nil},
		Bonus:    &LifeModuleBonus{KnowledgeSkillLevel: nil},
	},
	"devout": {
		ID:       "476490f9-24d8-4eef-b397-22cad0d578f6",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Devout",
		Karma:    "40",
		Source:   "BTB",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"pastors_kid": {
		ID:       "4c51d90e-7bcd-486f-b119-3adcc4cfd050",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Pastor's Kid",
		Karma:    "40",
		Source:   "BTB",
		Page:     "163",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"raised_by_hooders": {
		ID:       "39fe4e90-e3ba-463d-9a6d-410c863c41a4",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Raised By Hooders",
		Karma:    "40",
		Source:   "BTB",
		Page:     "163",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"tribal": {
		ID:       "550d0752-da63-400d-a8bb-4f0778abafc5",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Tribal",
		Karma:    "40",
		Source:   "BTB",
		Page:     "163",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"poor_kid": {
		ID:       "b5d7eafe-1d7e-493a-b0de-7e8dfc1502b8",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Poor Kid",
		Karma:    "40",
		Source:   "BTB",
		Page:     "163",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"framed": {
		ID:       "cc2de2db-31c3-470d-b209-3ef019bd797b",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Framed",
		Karma:    "100",
		Source:   "BTB",
		Page:     "163",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"dead": {
		ID:       "64250875-5ffe-425e-9651-f09737f2bb2b",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Dead",
		Karma:    "100",
		Source:   "BTB",
		Page:     "164",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"merc_kid": {
		ID:       "5b8db9d6-4a23-435a-8ec0-2749b23cbec6",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Merc Kid",
		Karma:    "40",
		Source:   "SL",
		Page:     "179",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"dock_rat": {
		ID:       "00a565e8-4094-46fc-a9e0-6b8a9468b68d",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Dock Rat",
		Karma:    "40",
		Source:   "SL",
		Page:     "179",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"corp_kid": {
		ID:       "0b6d0f7d-79e5-48c7-acc1-493344d8f363",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Corp Kid",
		Karma:    "40",
		Source:   "SL",
		Page:     "127",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"corp_silver_spooner": {
		ID:       "8b05f9be-4713-4d96-9c8b-25952b538b3a",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Corp Silver Spooner",
		Karma:    "40",
		Source:   "SL",
		Page:     "128",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"corp_teen": {
		ID:       "5b6feab4-e5dc-4c71-aa06-8303faf010a3",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Corp Teen",
		Karma:    "50",
		Source:   "SL",
		Page:     "128",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"merc_teen": {
		ID:       "e5af6b42-a73c-4580-ab46-ac98718369cb",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Merc Teen",
		Karma:    "50",
		Source:   "SL",
		Page:     "179",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"boat_brat": {
		ID:       "0ce0e867-5fa9-4492-8452-1459ecf392a2",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Boat Brat",
		Karma:    "50",
		Source:   "SL",
		Page:     "179",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"corp_college_student": {
		ID:       "d886934b-b937-4791-9512-cd7257ca721d",
		Stage:    "Further Education",
		Category: "LifeModule",
		Name:     "Corp College Student",
		Karma:    "65",
		Source:   "SL",
		Page:     "128",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"warm_body": {
		ID:       "14dfb0c8-4748-490c-876d-f65f55e81d95",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Warm Body",
		Karma:    "100",
		Source:   "SL",
		Page:     "129",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"rising_star": {
		ID:       "9b9f3b96-10ed-497c-816c-9692cfe3e523",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Rising Star",
		Karma:    "100",
		Source:   "SL",
		Page:     "129",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"company_troubleshooter": {
		ID:       "d847b2bc-1ff6-4fce-a799-17129fef4ff7",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Company Troubleshooter",
		Karma:    "100",
		Source:   "SL",
		Page:     "129",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"corpsec_officer_basic": {
		ID:       "040e3551-315a-41b4-aceb-181479ef9841",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Corpsec Officer, Basic",
		Karma:    "100",
		Source:   "SL",
		Page:     "128",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"lost_at_sea": {
		ID:       "5544cbc8-d77e-43fa-ab07-dbc160f9b403",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Lost At Sea",
		Karma:    "100",
		Source:   "SL",
		Page:     "180",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"environmental_combat_specialist_by_type": {
		ID:       "7349cc93-667b-4b36-8cc7-f42134c2b319",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Environmental Combat Specialist (By Type)",
		Karma:    "100",
		Source:   "SL",
		Page:     "180",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"tour_of_duty_desert_wars": {
		ID:       "45057214-38fd-4824-ba7c-985a3da22ef5",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Tour of Duty (Desert Wars)",
		Karma:    "100",
		Source:   "SL",
		Page:     "180",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"in_the_thick": {
		ID:       "ad4fea0f-037e-43c2-a153-55ea606d46a2",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "In The Thick",
		Karma:    "100",
		Source:   "SL",
		Page:     "180",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"gone_awol": {
		ID:       "0f4e4c01-f781-44a7-a630-a92e59b63a28",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Gone AWOL",
		Karma:    "100",
		Source:   "SL",
		Page:     "181",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"gone_native": {
		ID:       "991a62d3-456e-4c86-94a2-2c20ea11c7e1",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Gone Native",
		Karma:    "100",
		Source:   "SL",
		Page:     "180",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"lost_in_the_wilds": {
		ID:       "3e6efacd-4503-45f7-a5a8-4fbed9c2f5bc",
		Stage:    "Real Life",
		Category: "LifeModule",
		Name:     "Lost In The Wilds",
		Karma:    "100",
		Source:   "SL",
		Page:     "180",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"bootstrap_cliche": {
		ID:       "bab07751-2d37-4079-aa0d-274cf1038c92",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Bootstrap Cliche",
		Karma:    "40",
		Source:   "KC",
		Page:     "79",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"hacking_savant": {
		ID:       "516ece95-6b51-48b6-9806-24087dc344c2",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Hacking Savant",
		Karma:    "40",
		Source:   "KC",
		Page:     "80",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
	},
	"have_you_heard_the_good_word": {
		ID:       "22d06d59-ccf0-49ce-a17d-5bb3431a03cf",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "Have You Heard The Good Word?",
		Karma:    "40",
		Source:   "KC",
		Page:     "80",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"the_itsy_bitsy_spider": {
		ID:       "ed378222-f6c4-4d7f-971c-6d6b2d01a6b3",
		Stage:    "Formative Years",
		Category: "LifeModule",
		Name:     "The Itsy-Bitsy Spider",
		Karma:    "40",
		Source:   "KC",
		Page:     "80",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil},
	},
	"ath133t": {
		ID:       "2dff667c-7d61-496c-9999-cffdebb56007",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "ATH133T",
		Karma:    "50",
		Source:   "KC",
		Page:     "80",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"destined_for_greatness": {
		ID:       "8e34871f-d1e0-4c3b-8c63-5c06b21553f0",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Destined For Greatness",
		Karma:    "50",
		Source:   "KC",
		Page:     "80",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"hack_a_thon_medalist": {
		ID:       "4ba4b426-c333-4216-af95-58c1114c447a",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Hack-A-Thon Medalist",
		Karma:    "50",
		Source:   "KC",
		Page:     "80",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"the_flow": {
		ID:       "30f5af48-0df1-431e-9ae7-6d5266e0ab92",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "The Flow",
		Karma:    "50",
		Source:   "KC",
		Page:     "81",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"jacked_out": {
		ID:       "fc502702-45f4-4b70-9e09-cb3c6cad5da0",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Jacked Out",
		Karma:    "50",
		Source:   "KC",
		Page:     "79",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"matrix_royalty": {
		ID:       "c1133c0e-1c5a-4ba0-a207-0274cd90b25c",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Matrix Royalty",
		Karma:    "50",
		Source:   "KC",
		Page:     "81",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
	"techno_rigger_quest_que_cest": {
		ID:       "801d6ce7-080b-4a87-b49e-cc83c467a1bf",
		Stage:    "Teen Years",
		Category: "LifeModule",
		Name:     "Techno-Rigger, Qu'est Que C'est",
		Karma:    "50",
		Source:   "KC",
		Page:     "81",
		Bonus:    &LifeModuleBonus{SkillLevel: nil, KnowledgeSkillLevel: nil, AttributeLevel: nil, AddQualities: nil},
	},
}

// Note: StoryBuilder macros are not included as they are application-specific configuration
