package v5

// DataLifestyleCategories contains lifestyle categories
var DataLifestyleCategories = []string{
	"Entertainment - Asset",
	"Entertainment - Service",
	"Entertainment - Outing",
	"Positive",
	"Negative",
	"Contracts",
}

// DataLifestyles contains lifestyle records keyed by their ID (lowercase with underscores)
var DataLifestyles = map[string]Lifestyle{
	"id_error_re_add_life_style_to_fix": {
		ID:         "00000000-0000-0000-0000-000000000000",
		Name:       "ID ERROR. Re-add life style to fix",
		Cost:       "1",
		Dice:       "1",
		LP:         "0",
		Multiplier: "0",
		Source:     "SR5",
		Page:       "1",
	},
	"street": {
		ID:              "559653df-a9af-44e2-9e04-3044c1d1b421",
		Name:            "Street",
		Cost:            "0",
		Dice:            "1",
		LP:              "2",
		Multiplier:      "20",
		Source:          "SR5",
		Page:            "369",
		FreeGrids:       &FreeGrids{FreeGrid: FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}},
		CostForArea:     "50",
		CostForComforts: "50",
		CostForSecurity: "50",
	},
	"squatter": {
		ID:         "9367556e-f82f-4f9d-840e-24c8f824ca68",
		Name:       "Squatter",
		Cost:       "500",
		Dice:       "2",
		LP:         "2",
		Multiplier: "40",
		Source:     "SR5",
		Page:       "369",
		FreeGrids:  &FreeGrids{FreeGrid: FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}},
	},
	"low": {
		ID:         "451eef87-d18e-4bee-a972-1ee165b08522",
		Name:       "Low",
		Cost:       "2000",
		Dice:       "3",
		LP:         "3",
		Multiplier: "60",
		Source:     "SR5",
		Page:       "369",
		FreeGrids:  &FreeGrids{FreeGrid: FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}},
	},
	"medium": {
		ID:         "9cb0222c-14c1-4bea-bf83-055513a1f33e",
		Name:       "Medium",
		Cost:       "5000",
		Dice:       "4",
		LP:         "4",
		Multiplier: "100",
		Source:     "SR5",
		Page:       "369",
		FreeGrids:  &FreeGrids{FreeGrid: []interface{}{FreeGrid{Content: "Grid Subscription", Select: "Local Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}}},
	},
	"high": {
		ID:         "4a37d519-c9be-4ecc-97bb-e9d78708c374",
		Name:       "High",
		Cost:       "10000",
		Dice:       "5",
		LP:         "6",
		Multiplier: "500",
		Source:     "SR5",
		Page:       "369",
		FreeGrids:  &FreeGrids{FreeGrid: []interface{}{FreeGrid{Content: "Grid Subscription", Select: "Global Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Local Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}}},
	},
	"luxury": {
		ID:         "4b513ac9-9eb3-471b-931b-839a04873b84",
		Name:       "Luxury",
		Cost:       "100000",
		Dice:       "6",
		LP:         "12",
		Multiplier: "1000",
		Source:     "SR5",
		Page:       "369",
		FreeGrids:  &FreeGrids{FreeGrid: []interface{}{FreeGrid{Content: "Grid Subscription", Select: "Global Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Local Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}}},
	},
	"commercial": {
		ID:         "b7b15c35-596d-4e00-92ee-2e999f062924",
		Name:       "Commercial",
		Cost:       "8000",
		Dice:       "4",
		LP:         "4",
		Multiplier: "100",
		Source:     "RF",
		Page:       "218",
		FreeGrids:  &FreeGrids{FreeGrid: []interface{}{FreeGrid{Content: "Grid Subscription", Select: "Local Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}}},
	},
	"bolt_hole": {
		ID:         "1a231a81-4985-4b57-83cf-659ad920cfb7",
		Name:       "Bolt Hole",
		Cost:       "1000",
		Dice:       "1",
		LP:         "4",
		Multiplier: "0",
		Source:     "RF",
		Page:       "216",
		FreeGrids:  &FreeGrids{FreeGrid: FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}},
	},
	"hospitalized_basic": {
		ID:         "4be85958-af8f-4404-812f-0d8a426f01d6",
		Name:       "Hospitalized, Basic",
		Cost:       "500",
		Dice:       "0",
		LP:         "0",
		Multiplier: "0",
		Source:     "SR5",
		Page:       "369",
		FreeGrids:  &FreeGrids{FreeGrid: []interface{}{FreeGrid{Content: "Grid Subscription", Select: "Global Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Local Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}}},
		Increment:  "day",
	},
	"hospitalized_intensive": {
		ID:         "2be1a0f7-6133-4966-be57-720ed9b927a9",
		Name:       "Hospitalized, Intensive",
		Cost:       "1000",
		Dice:       "0",
		LP:         "0",
		Multiplier: "0",
		Source:     "SR5",
		Page:       "369",
		FreeGrids:  &FreeGrids{FreeGrid: []interface{}{FreeGrid{Content: "Grid Subscription", Select: "Global Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Local Grid"}, FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}}},
		Increment:  "day",
	},
	"traveler": {
		ID:           "ed775c22-8f0c-40a0-bc6f-5dbb980cedba",
		Name:         "Traveler",
		Cost:         "3000",
		Dice:         "3",
		LP:           "2",
		Multiplier:   "60",
		Source:       "RF",
		Page:         "218",
		FreeGrids:    &FreeGrids{FreeGrid: FreeGrid{Content: "Grid Subscription", Select: "Public Grid"}},
		AllowBonusLP: "True",
	},
}

// DataComforts contains comfort records keyed by name (lowercase with underscores)
var DataComforts = map[string]Comfort{
	"bolt_hole": {
		Name:    "Bolt Hole",
		Minimum: "1",
		Limit:   "2",
	},
	"street": {
		Name:    "Street",
		Minimum: "0",
		Limit:   "1",
	},
	"squatter": {
		Name:    "Squatter",
		Minimum: "1",
		Limit:   "2",
	},
	"low": {
		Name:    "Low",
		Minimum: "2",
		Limit:   "3",
	},
	"medium": {
		Name:    "Medium",
		Minimum: "3",
		Limit:   "4",
	},
	"high": {
		Name:    "High",
		Minimum: "4",
		Limit:   "6",
	},
	"luxury": {
		Name:    "Luxury",
		Minimum: "5",
		Limit:   "8",
	},
	"commercial": {
		Name:    "Commercial",
		Minimum: "3",
		Limit:   "4",
	},
	"traveler": {
		Name:    "Traveler",
		Minimum: "2",
		Limit:   "4",
	},
}

// DataNeighborhoods contains neighborhood records keyed by name (lowercase with underscores)
var DataNeighborhoods = map[string]Neighborhood{
	"bolt_hole": {
		Name:    "Bolt Hole",
		Minimum: "1",
		Limit:   "4",
	},
	"street": {
		Name:    "Street",
		Minimum: "0",
		Limit:   "1",
	},
	"squatter": {
		Name:    "Squatter",
		Minimum: "1",
		Limit:   "2",
	},
	"low": {
		Name:    "Low",
		Minimum: "2",
		Limit:   "3",
	},
	"medium": {
		Name:    "Medium",
		Minimum: "4",
		Limit:   "5",
	},
	"high": {
		Name:    "High",
		Minimum: "5",
		Limit:   "6",
	},
	"luxury": {
		Name:    "Luxury",
		Minimum: "5",
		Limit:   "7",
	},
	"commercial": {
		Name:    "Commercial",
		Minimum: "4",
		Limit:   "6",
	},
	"traveler": {
		Name:    "Traveler",
		Minimum: "2",
		Limit:   "4",
	},
}

// DataSecurities contains security records keyed by name (lowercase with underscores)
var DataSecurities = map[string]Security{
	"bolt_hole": {
		Name:    "Bolt Hole",
		Minimum: "1",
		Limit:   "4",
	},
	"street": {
		Name:    "Street",
		Minimum: "0",
		Limit:   "1",
	},
	"squatter": {
		Name:    "Squatter",
		Minimum: "1",
		Limit:   "2",
	},
	"low": {
		Name:    "Low",
		Minimum: "2",
		Limit:   "3",
	},
	"medium": {
		Name:    "Medium",
		Minimum: "3",
		Limit:   "4",
	},
	"high": {
		Name:    "High",
		Minimum: "4",
		Limit:   "6",
	},
	"luxury": {
		Name:    "Luxury",
		Minimum: "5",
		Limit:   "8",
	},
	"commercial": {
		Name:    "Commercial",
		Minimum: "3",
		Limit:   "7",
	},
	"traveler": {
		Name:    "Traveler",
		Minimum: "2",
		Limit:   "4",
	},
}

// DataLifestyleQualities contains lifestyle quality records keyed by their ID (lowercase with underscores)
var DataLifestyleQualities = map[string]LifestyleQuality{
	"armory": {
		ID:       "91ac54bf-0f7d-40f3-81bf-dc32e62fd94e",
		Name:     "Armory",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "2000",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "220",
	},
	"cleaning_service_standard": {
		ID:       "af5b1436-abc9-4f3d-9521-64cf58724e0a",
		Name:     "Cleaning Service (Standard)",
		Category: "Entertainment - Service",
		LP:       "1",
		Cost:     "100",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "220",
	},
	"cleaning_service_mage_sensitive": {
		ID:       "6f638af3-39c0-4d29-8a5d-1e0bc67ea922",
		Name:     "Cleaning Service (Mage Sensitive)",
		Category: "Entertainment - Service",
		LP:       "1",
		Cost:     "200",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "220",
	},
	"cleaning_service_pollution_sensitive": {
		ID:       "1fd70570-e89d-4c85-bfe7-6b56aac7c7df",
		Name:     "Cleaning Service (Pollution Sensitive)",
		Category: "Entertainment - Service",
		LP:       "1",
		Cost:     "400",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "220",
	},
	"discreet_cleaning_service": {
		ID:       "080401ff-1470-4b32-86bb-bd615fd63b86",
		Name:     "Discreet Cleaning Service",
		Category: "Entertainment - Service",
		LP:       "4",
		Cost:     "10000",
		Source:   "RF",
		Page:     "221",
	},
	"discreet_deliveryman": {
		ID:       "7e721535-3827-4a85-9771-9d20cf348d11",
		Name:     "Discreet Deliveryman",
		Category: "Entertainment - Service",
		LP:       "3",
		Cost:     "100",
		Source:   "RF",
		Page:     "221",
	},
	"discreet_candyman": {
		ID:       "cc6f6198-a330-43f1-8c23-56ef9cb1f9ea",
		Name:     "Discreet Candyman",
		Category: "Entertainment - Service",
		LP:       "3",
		Cost:     "1000",
		Source:   "RF",
		Page:     "221",
	},
	"cramped_garage_airplane": {
		ID:       "280535d6-9e2a-4831-8b22-b2fb0647cff7",
		Name:     "Cramped Garage (Airplane)",
		Category: "Entertainment - Asset",
		LP:       "4",
		Cost:     "18000",
		Allowed:  "Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"cramped_garage_boat": {
		ID:       "df7d2669-2af5-475b-853d-819498b3badc",
		Name:     "Cramped Garage (Boat)",
		Category: "Entertainment - Asset",
		LP:       "3",
		Cost:     "4500",
		Allowed:  "High, Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"cramped_garage_car_body_4_or_less": {
		ID:       "efe7c46c-b863-4696-a750-015837861f81",
		Name:     "Cramped Garage (Car (Body 4 or Less))",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "45",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"cramped_garage_car_body_5_or_more": {
		ID:       "3d62f25c-8c84-476f-907d-a95073711b44",
		Name:     "Cramped Garage (Car (Body 5 or More))",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "90",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"cramped_garage_helicopter": {
		ID:       "10a65174-a6a3-467b-b66e-6a837bf0e11b",
		Name:     "Cramped Garage (Helicopter)",
		Category: "Entertainment - Asset",
		LP:       "4",
		Cost:     "9000",
		Allowed:  "Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"garage_airplane": {
		ID:       "efb63888-ad49-44e0-8bd7-491532c8c179",
		Name:     "Garage (Airplane)",
		Category: "Entertainment - Asset",
		LP:       "4",
		Cost:     "20000",
		Allowed:  "Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"garage_boat": {
		ID:       "981f4509-06db-430e-9845-b3a5268f14f5",
		Name:     "Garage (Boat)",
		Category: "Entertainment - Asset",
		LP:       "3",
		Cost:     "5000",
		Allowed:  "High, Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"garage_car_body_4_or_less": {
		ID:       "a45f7fc8-ec90-4a65-8705-c931c408c9cc",
		Name:     "Garage (Car (Body 4 or Less))",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "50",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"garage_car_body_5_or_more": {
		ID:       "9e7cea76-8f2e-4d87-a5ce-60395a8d701f",
		Name:     "Garage (Car (Body 5 or More))",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "100",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"garage_helicopter": {
		ID:       "67e41d1f-78a9-417b-88d4-94eeb58fa4ff",
		Name:     "Garage (Helicopter)",
		Category: "Entertainment - Asset",
		LP:       "4",
		Cost:     "10000",
		Allowed:  "Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"greenhouse": {
		ID:       "0ab77035-0b81-4fe0-8e16-8674501a3782",
		Name:     "Greenhouse",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "500",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "221",
	},
	"grid_subscription": {
		ID:       "adaf6b3d-874a-42e5-b08b-37adf1222f23",
		Name:     "Grid Subscription",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "50",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "222",
	},
	"gym": {
		ID:       "23c785d3-e086-46a6-8491-603fa1e6963d",
		Name:     "Gym",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "300",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "222",
	},
	"indoor_arboretum": {
		ID:       "3e5339c7-42e3-484b-8839-66ea942e509b",
		Name:     "Indoor Arboretum",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "500",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "222",
	},
	"local_bar_patron": {
		ID:       "7348e613-3f05-413a-b8eb-a27e480d9f88",
		Name:     "Local Bar Patron",
		Category: "Entertainment - Outing",
		LP:       "1",
		Cost:     "25",
		Allowed:  "Low,Medium,High,Luxury",
		Source:   "RF",
		Page:     "222",
	},
	"merchandise_goods_specific_item_avail_3": {
		ID:       "c63bcf5f-fcb7-4193-bdae-2b32cdf50032",
		Name:     "Merchandise: Goods (Specific Item) (Avail 3)",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "10000",
		Allowed:  "Commercial",
		Source:   "RF",
		Page:     "222",
	},
	"merchandise_goods_specific_item_avail_5": {
		ID:       "544760af-1c45-4de7-a198-f9f7f86ec4b2",
		Name:     "Merchandise: Goods (Specific Item) (Avail 5)",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "10000",
		Allowed:  "Commercial",
		Source:   "RF",
		Page:     "222",
	},
	"merchandise_goods_specific_item_avail_7": {
		ID:       "5a7f93eb-7297-49a0-904e-466be3f3f454",
		Name:     "Merchandise: Goods (Specific Item) (Avail 7)",
		Category: "Entertainment - Asset",
		LP:       "3",
		Cost:     "10000",
		Allowed:  "Commercial",
		Source:   "RF",
		Page:     "222",
	},
	"merchandise_goods_specific_item_avail_9": {
		ID:       "1ab883f5-3392-41c6-b4e3-b26dfc4b8aba",
		Name:     "Merchandise: Goods (Specific Item) (Avail 9)",
		Category: "Entertainment - Asset",
		LP:       "4",
		Cost:     "10000",
		Allowed:  "Commercial",
		Source:   "RF",
		Page:     "222",
	},
	"merchandise_pawn_shopthrift_store": {
		ID:       "35d712d8-ea04-4853-8b1f-89e079e043ce",
		Name:     "Merchandise: Pawn Shop/Thrift Store",
		Category: "Entertainment - Service",
		LP:       "2",
		Cost:     "10000",
		Allowed:  "Commercial",
		Source:   "RF",
		Page:     "222",
	},
	"merchandise_used_goods_specific_item": {
		ID:       "b8c84dbb-b59e-43e1-a07f-fa03802fe5af",
		Name:     "Merchandise: Used Goods (Specific Item)",
		Category: "Entertainment - Service",
		LP:       "2",
		Cost:     "10000",
		Allowed:  "Commercial",
		Source:   "RF",
		Page:     "222",
	},
	"panic_room": {
		ID:       "9db8b664-4fba-4e66-8875-54c54324d93d",
		Name:     "Panic Room",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "1000",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "222",
	},
	"patron_of_the_arts_concertsevents": {
		ID:       "5e7c3001-03de-41ed-b2d2-03c3175669d4",
		Name:     "Patron of the Arts (Concerts/Events)",
		Category: "Entertainment - Outing",
		LP:       "1",
		Cost:     "100",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "223",
	},
	"patron_of_the_arts_private_club": {
		ID:       "903b7d38-d844-4473-8454-4e8f4875880d",
		Name:     "Patron of the Arts (Private Club)",
		Category: "Entertainment - Outing",
		LP:       "1",
		Cost:     "200",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "223",
	},
	"patron_of_the_arts_zoomuseum": {
		ID:       "0bbec525-178b-4712-b36f-6549ea8274c2",
		Name:     "Patron of the Arts (Zoo/Museum)",
		Category: "Entertainment - Outing",
		LP:       "1",
		Cost:     "75",
		Allowed:  "Low,Medium,High,Luxury",
		Source:   "RF",
		Page:     "223",
	},
	"patron_of_the_arts_theme_parks": {
		ID:       "39f7afff-173b-4c14-91b6-de2c8d315cc6",
		Name:     "Patron of the Arts (Theme Parks)",
		Category: "Entertainment - Outing",
		LP:       "1",
		Cost:     "100",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "223",
	},
	"private_room": {
		ID:       "679b8200-2f4a-45f8-b7cb-c91fdcd94f2d",
		Name:     "Private Room",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "20",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "RF",
		Page:     "223",
	},
	"public_transportation": {
		ID:       "20c5e92c-deb7-4d88-9972-507ecccb1e50",
		Name:     "Public Transportation",
		Category: "Entertainment - Service",
		LP:       "1",
		Cost:     "50",
		Allowed:  "Low,Medium,High,Luxury",
		Source:   "RF",
		Page:     "223",
	},
	"railway_pass": {
		ID:       "35e2e527-2c63-4193-abe3-1c72063c8d6f",
		Name:     "Railway Pass",
		Category: "Entertainment - Service",
		LP:       "1",
		Cost:     "75",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "222",
	},
	"shooting_range": {
		ID:       "ee56a5de-dfb0-41c3-8de7-67041a627df9",
		Name:     "Shooting Range",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "500",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "223",
	},
	"soy_processing_unit": {
		ID:       "d26a39a7-cc09-4476-a5f0-eeb55e737641",
		Name:     "Soy Processing Unit",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "20",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "223",
	},
	"sports_court_small": {
		ID:       "2e845204-d9b3-40a9-9d24-4b5aa9673486",
		Name:     "Sports Court - Small",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "300",
		Allowed:  "High,Luxury",
		Source:   "RF",
		Page:     "224",
	},
	"swimming_pool": {
		ID:       "0503f768-dc6b-4e79-adbe-69907dd79e1b",
		Name:     "Swimming Pool",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "100",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "224",
	},
	"walk_in_freezer": {
		ID:       "71428a84-70d1-4c9c-89c3-227509cfbc25",
		Name:     "Walk-In Freezer",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "1000",
		Allowed:  "Commercial",
		Source:   "RF",
		Page:     "224",
	},
	"workshopfacility": {
		ID:       "af8ac67a-7603-48b2-8ee4-940e5dcd5f29",
		Name:     "Workshop/Facility",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "2500",
		Allowed:  "Commercial",
		Source:   "RF",
		Page:     "224",
	},
	"cramped_workshopfacility": {
		ID:       "867f7c74-8e6e-4467-b49c-10f4bf17fa8d",
		Name:     "Cramped Workshop/Facility",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "2250",
		Allowed:  "Commercial",
		Source:   "RF",
		Page:     "224",
	},
	"yard": {
		ID:       "3dfb9fd3-c58d-4cc8-9e6b-f17fa18474b6",
		Name:     "Yard",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "50",
		Allowed:  "Low,Medium,High,Luxury",
		Source:   "RF",
		Page:     "224",
	},
	"zen_den": {
		ID:       "03092f1a-4018-413b-a11f-144383472c18",
		Name:     "Zen Den",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "100",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "224",
	},
	"bat_cave": {
		ID:       "cc3abead-ab2a-4023-8a63-d64536ccf5e5",
		Name:     "Bat Cave",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "100",
		Allowed:  "Medium,High,Luxury",
		Source:   "RF",
		Page:     "224",
	},
	"angry_drunk_reputation": {
		ID:       "910b0a59-59cb-422b-b9a4-7b8d12912c91",
		Name:     "Angry Drunk Reputation",
		Category: "Negative",
		LP:       "-1",
		Source:   "RF",
		Page:     "224",
	},
	"corporate_owned": {
		ID:       "6c47713d-46ba-495d-800c-f77c306cf9df",
		Name:     "Corporate Owned",
		Category: "Positive",
		LP:       "3",
		Source:   "RF",
		Page:     "225",
	},
	"cramped": {
		ID:       "ff0cb981-4459-46e7-ab75-d8c5bcb0c486",
		Name:     "Cramped",
		Category: "Negative",
		LP:       "1",
		Source:   "SR5",
		Page:     "370",
	},
	"extra_secure": {
		ID:       "4fb84713-6171-409d-ad7c-ccbc44b891ad",
		Name:     "Extra Secure",
		Category: "Positive",
		LP:       "1",
		Source:   "SR5",
		Page:     "370",
	},
	"dangerous_area": {
		ID:       "ae63d09f-22a1-4c27-bc99-d82887fcef15",
		Name:     "Dangerous Area",
		Category: "Negative",
		LP:       "-1",
		Source:   "SR5",
		Page:     "370",
	},
	"hotel_california": {
		ID:       "8cc2d931-becd-40d7-a0bd-705412037f38",
		Name:     "Hotel California",
		Category: "Negative",
		LP:       "-1",
		Source:   "RF",
		Page:     "226",
	},
	"maid_is_out": {
		ID:       "ce96f8e7-42a5-4745-8e3d-1f04c72b0385",
		Name:     "Maid is Out",
		Category: "Negative",
		LP:       "-1",
		Source:   "RF",
		Page:     "226",
	},
	"not_a_home": {
		ID:       "9a8da447-b05f-4f4a-8d7c-537344d77557",
		Name:     "Not a Home",
		Category: "Negative",
		LP:       "-1",
		Source:   "RF",
		Page:     "226",
	},
	"obscuredifficult_to_find": {
		ID:       "4aff94a9-6699-4355-81ea-ff66ee5ecca1",
		Name:     "Obscure/Difficult to Find",
		Category: "Negative",
		LP:       "-1",
		Source:   "SR5",
		Page:     "370",
	},
	"one_good_thing_about_this_place": {
		ID:       "a808bcae-68c5-4e96-8bfc-f432ea63cc11",
		Name:     "One Good Thing About This Place",
		Category: "Positive",
		LP:       "1",
		Allowed:  "Traveler",
		Source:   "RF",
		Page:     "226",
	},
	"safehouse": {
		ID:       "0eee0e10-078e-4f07-ac57-14f9b83f1a36",
		Name:     "Safehouse",
		Category: "Positive",
		LP:       "0",
		Cost:     "500",
		Source:   "RF",
		Page:     "226",
	},
	"safety_third": {
		ID:       "c4d4c6db-7314-4a23-951d-31126514af8d",
		Name:     "Safety Third",
		Category: "Negative",
		LP:       "-1",
		Source:   "RF",
		Page:     "226",
	},
	"special_work_area": {
		ID:       "24c33e2d-bb97-4f82-a68d-dfa7c89a69d7",
		Name:     "Special Work Area",
		Category: "Positive",
		LP:       "0",
		Cost:     "1000",
		Source:   "SR5",
		Page:     "370",
	},
	"thrifty": {
		ID:       "61e7bb21-cb25-44ff-a332-639fe9dac893",
		Name:     "Thrifty",
		Category: "Negative",
		LP:       "2",
		Cost:     "-1000",
		Allowed:  "Traveler",
		Source:   "RF",
		Page:     "226",
	},
	"w_zone": {
		ID:       "d508fc24-6cbd-488f-a5f8-5282cfb58f9a",
		Name:     "W Zone",
		Category: "Negative",
		LP:       "-1",
		Source:   "RF",
		Page:     "226",
	},
	"skillsoft_network_basic": {
		ID:       "d4f23b83-d884-47e0-9bbf-7c04341e1894",
		Name:     "Skillsoft Network, Basic",
		Category: "Contracts",
		LP:       "0",
		Cost:     "2000",
		Source:   "CF",
		Page:     "78",
	},
	"skillsoft_network_silver": {
		ID:       "5e090a22-119a-4922-ada5-c8d634399797",
		Name:     "Skillsoft Network, Silver",
		Category: "Contracts",
		LP:       "0",
		Cost:     "10000",
		Source:   "CF",
		Page:     "78",
	},
	"skillsoft_network_gold": {
		ID:       "fbd64602-f7c5-410f-8ec8-5c5cd7fde945",
		Name:     "Skillsoft Network, Gold",
		Category: "Contracts",
		LP:       "0",
		Cost:     "15000",
		Source:   "CF",
		Page:     "78",
	},
	"skillsoft_network_platinum": {
		ID:       "1fc363ff-b577-4e5b-b3e7-ae87bbab0fe9",
		Name:     "Skillsoft Network, Platinum",
		Category: "Contracts",
		LP:       "0",
		Cost:     "20000",
		Source:   "CF",
		Page:     "78",
	},
	"datahost_subscription": {
		ID:       "4d2bac20-5051-4035-8959-2286c0879686",
		Name:     "Datahost Subscription",
		Category: "Contracts",
		LP:       "0",
		Cost:     "250",
		Source:   "CF",
		Page:     "80",
	},
	"shopsoft_network_subscription": {
		ID:       "5d2d66a4-29b5-4055-859a-9471de62774b",
		Name:     "Shopsoft Network Subscription",
		Category: "Contracts",
		LP:       "0",
		Cost:     "250",
		Source:   "CF",
		Page:     "80",
	},
	"mapping_system_subscription_basic": {
		ID:       "dea3d03c-9441-400c-a512-d8840f6f40d5",
		Name:     "Mapping System Subscription, Basic",
		Category: "Contracts",
		LP:       "0",
		Cost:     "50",
		Source:   "CF",
		Page:     "81",
	},
	"mapping_system_subscription_silver": {
		ID:       "516c286b-b233-43f4-96d0-19e8295f9f88",
		Name:     "Mapping System Subscription, Silver",
		Category: "Contracts",
		LP:       "0",
		Cost:     "150",
		Source:   "CF",
		Page:     "81",
	},
	"mapping_system_subscription_gold": {
		ID:       "53b8cea1-aa63-4e12-8a04-b7ba72aa1cbe",
		Name:     "Mapping System Subscription, Gold",
		Category: "Contracts",
		LP:       "0",
		Cost:     "500",
		Source:   "CF",
		Page:     "81",
	},
	"docwagon_contract_basic": {
		ID:       "4f41448a-7d44-4a5f-a99a-e2cc1e2cc2b1",
		Name:     "DocWagon Contract, Basic",
		Category: "Contracts",
		LP:       "0",
		Cost:     "5000 div 12",
		Source:   "SR5",
		Page:     "450",
	},
	"docwagon_contract_gold": {
		ID:       "4f2d39cd-fbc7-4d02-a3eb-f8decdb9a415",
		Name:     "DocWagon Contract, Gold",
		Category: "Contracts",
		LP:       "0",
		Cost:     "25000 div 12",
		Source:   "SR5",
		Page:     "450",
	},
	"docwagon_contract_platinum": {
		ID:       "26476ddb-52f6-4c31-b1f0-949d0ef95495",
		Name:     "DocWagon Contract, Platinum",
		Category: "Contracts",
		LP:       "0",
		Cost:     "50000 div 12",
		Source:   "SR5",
		Page:     "450",
	},
	"docwagon_contract_super_platinum": {
		ID:       "0a58f493-a12e-4c08-b8b8-baac4c5e6591",
		Name:     "DocWagon Contract, Super-Platinum",
		Category: "Contracts",
		LP:       "0",
		Cost:     "100000 div 12",
		Source:   "SR5",
		Page:     "450",
	},
	"local_grid_subscription": {
		ID:       "5f272787-e3f6-4cd7-949b-ce1ed786ef61",
		Name:     "Local Grid Subscription",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "50",
		Allowed:  "Medium,High,Luxury",
		Source:   "HT",
		Page:     "140",
	},
	"global_grid_subscription": {
		ID:       "9ad9decb-b52d-4993-9ef6-4768727c3d75",
		Name:     "Global Grid Subscription",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "250",
		Allowed:  "High,Luxury",
		Source:   "HT",
		Page:     "140",
	},
	"subsistence_huntinggathering_i": {
		ID:       "cb265e4e-b13a-487b-8c0f-b2b855138a66",
		Name:     "Subsistence Hunting/Gathering I",
		Category: "Entertainment - Outing",
		LP:       "1",
		Cost:     "15",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "HT",
		Page:     "140",
	},
	"subsistence_huntinggathering_ii": {
		ID:       "c0051319-9565-49f1-b59d-ee1f835cf1df",
		Name:     "Subsistence Hunting/Gathering II",
		Category: "Entertainment - Outing",
		LP:       "2",
		Cost:     "30",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "HT",
		Page:     "140",
	},
	"subsistence_huntinggathering_iii": {
		ID:       "3aca0284-8e7f-4329-83e7-9819bf73a13e",
		Name:     "Subsistence Hunting/Gathering III",
		Category: "Entertainment - Outing",
		LP:       "3",
		Cost:     "45",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "HT",
		Page:     "140",
	},
	"subsistence_huntinggathering_iv": {
		ID:       "f2c146ea-302e-444b-8082-3cc47d165669",
		Name:     "Subsistence Hunting/Gathering IV",
		Category: "Entertainment - Outing",
		LP:       "4",
		Cost:     "60",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "HT",
		Page:     "140",
	},
	"drone_maidsmanservants": {
		ID:       "e667f652-c908-4548-adf9-7b969d587e43",
		Name:     "Drone Maids/Manservants",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "7000",
		Allowed:  "High,Luxury",
		Source:   "HT",
		Page:     "141",
	},
	"maidsmanservants": {
		ID:       "1b2218d6-d4a3-4978-b941-8358159e4e3b",
		Name:     "Maids/Manservants",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "15000",
		Allowed:  "Luxury",
		Source:   "HT",
		Page:     "141",
	},
	"zombie_maidsmanservants": {
		ID:       "7e962b91-51c3-4a88-a7da-70044ef665db",
		Name:     "Zombie Maids/Manservants",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "20000",
		Allowed:  "High",
		Source:   "HT",
		Page:     "141",
	},
	"household_gremlins_i": {
		ID:       "826b324f-9dd3-4fc3-8c80-b4680587f9f6",
		Name:     "Household Gremlins I",
		Category: "Negative",
		LP:       "0",
		Cost:     "-300",
		Source:   "HT",
		Page:     "141",
	},
	"household_gremlins_ii": {
		ID:       "a7d85c5f-74b9-4f02-ab00-916cd7337d47",
		Name:     "Household Gremlins II",
		Category: "Negative",
		LP:       "0",
		Cost:     "-600",
		Source:   "HT",
		Page:     "141",
	},
	"dug_a_hole": {
		ID:       "093e24c5-1f87-4cb3-8a9e-1dc701081dfb",
		Name:     "Dug a Hole",
		Category: "Positive",
		LP:       "0",
		Cost:     "2000",
		Source:   "HT",
		Page:     "141",
	},
	"lax_security": {
		ID:       "1fa52cd4-4342-4511-91dc-6d452032d2c7",
		Name:     "Lax Security",
		Category: "Negative",
		LP:       "-1",
		Cost:     "0",
		Source:   "HT",
		Page:     "141",
	},
	"limited_building_space": {
		ID:       "0a41dfd4-67f7-4d8d-80e5-15db2fc64f09",
		Name:     "Limited Building Space",
		Category: "Negative",
		LP:       "-1",
		Cost:     "0",
		Source:   "HT",
		Page:     "141",
	},
	"rough_neighborhood": {
		ID:       "7868fea6-f3b9-4db8-baee-60fd16f322cc",
		Name:     "Rough Neighborhood",
		Category: "Negative",
		LP:       "-1",
		Cost:     "0",
		Source:   "HT",
		Page:     "141",
	},
	"no_masters": {
		ID:       "23dcd584-9650-44b0-9273-896873ba6f61",
		Name:     "No Masters",
		Category: "Negative",
		LP:       "-1",
		Source:   "HT",
		Page:     "141",
	},
	"escape_tunnel_100_meters": {
		ID:       "79de178b-6064-468f-bb8d-72b510dc0239",
		Name:     "Escape Tunnel, 100 Meters",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "200",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "SFB",
		Page:     "20",
	},
	"escape_tunnel_200_meters": {
		ID:       "f5b675ed-2d7f-4325-b301-a63deb81356c",
		Name:     "Escape Tunnel, 200 Meters",
		Category: "Entertainment - Asset",
		LP:       "2",
		Cost:     "200",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "SFB",
		Page:     "20",
	},
	"escape_tunnel_300_meters": {
		ID:       "e548ba65-e403-4cd5-bc70-3d45478ad76c",
		Name:     "Escape Tunnel, 300 Meters",
		Category: "Entertainment - Asset",
		LP:       "3",
		Cost:     "200",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "SFB",
		Page:     "20",
	},
	"escape_tunnel_400_meters": {
		ID:       "7f8bdcb0-b5c6-4741-86b1-e48cff81709e",
		Name:     "Escape Tunnel, 400 Meters",
		Category: "Entertainment - Asset",
		LP:       "4",
		Cost:     "200",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "SFB",
		Page:     "20",
	},
	"escape_tunnel_500_meters": {
		ID:       "fdb2718d-a88d-45f3-ba54-6ed6937321bc",
		Name:     "Escape Tunnel, 500 Meters",
		Category: "Entertainment - Asset",
		LP:       "5",
		Cost:     "200",
		Allowed:  "Squatter,Low,Medium,High,Luxury",
		Source:   "SFB",
		Page:     "20",
	},
	"cramped_garage_stable": {
		ID:       "ffb7fb04-77ee-4a12-8823-7012aa272dbf",
		Name:     "Cramped Garage (Stable)",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "180",
		Allowed:  "Medium,High,Luxury",
		Source:   "SFB",
		Page:     "20",
	},
	"garage_stable": {
		ID:       "24435fe5-2791-40e2-8ca1-6e397b6982d8",
		Name:     "Garage (Stable)",
		Category: "Entertainment - Asset",
		LP:       "1",
		Cost:     "200",
		Allowed:  "Medium,High,Luxury",
		Source:   "SFB",
		Page:     "20",
	},
	"haunted": {
		ID:       "665c46a9-4726-4e57-963f-392c30f653e9",
		Name:     "Haunted",
		Category: "Negative",
		LP:       "0",
		Source:   "SFB",
		Page:     "20",
	},
	"ar_fashion_subscription_casual": {
		ID:       "b722458f-b0af-45c4-b5c7-b3c7e2ef48f6",
		Name:     "AR Fashion Subscription, Casual",
		Category: "Contracts",
		LP:       "0",
		Cost:     "25",
		Source:   "CA",
		Page:     "138",
	},
	"ar_fashion_subscription_business": {
		ID:       "fc4d530e-a832-4437-b022-cdf35a22fc78",
		Name:     "AR Fashion Subscription, Business",
		Category: "Contracts",
		LP:       "0",
		Cost:     "100",
		Source:   "CA",
		Page:     "138",
	},
	"ar_fashion_subscription_formal": {
		ID:       "1607bf0d-1a75-4582-8496-ffd92289f2b3",
		Name:     "AR Fashion Subscription, Formal",
		Category: "Contracts",
		LP:       "0",
		Cost:     "500",
		Source:   "CA",
		Page:     "138",
	},
	"ar_fashion_subscription_designer": {
		ID:       "da100dfd-dcaa-4b1a-a76e-ad38539612a4",
		Name:     "AR Fashion Subscription, Designer",
		Category: "Contracts",
		LP:       "0",
		Cost:     "1500",
		Source:   "CA",
		Page:     "138",
	},
	"carnivoregold": {
		ID:       "190ba01c-f04e-45a8-a0d1-d6fd073d61c1",
		Name:     "CarnivoreGold",
		Category: "Contracts",
		LP:       "0",
		Cost:     "250",
		Source:   "CA",
		Page:     "144",
	},
	"monalisa": {
		ID:       "fe33b1e6-ad0f-44e4-b156-7c435f335682",
		Name:     "MonaLisa",
		Category: "Contracts",
		LP:       "0",
		Cost:     "250",
		Source:   "CA",
		Page:     "144",
	},
	"pheromone_detection": {
		ID:       "eeb6f3b7-70b3-478b-88c6-af47bb233b44",
		Name:     "Pheromone Detection",
		Category: "Contracts",
		LP:       "0",
		Cost:     "250",
		Source:   "CA",
		Page:     "144",
	},
	"speech_template_comparison": {
		ID:       "7417c7e7-8940-47cf-9bd2-9f7193b5fbbf",
		Name:     "Speech Template Comparison",
		Category: "Contracts",
		LP:       "0",
		Cost:     "250",
		Source:   "CA",
		Page:     "144",
	},
	"target_tracking_software": {
		ID:       "49b01e13-4228-4390-a0c3-ffb6c6276e49",
		Name:     "Target Tracking Software",
		Category: "Contracts",
		LP:       "0",
		Cost:     "250",
		Source:   "CA",
		Page:     "144",
	},
	"thermal_mood_reading": {
		ID:       "d5239d1e-04ef-47a6-8065-a1559559a669",
		Name:     "Thermal Mood Reading",
		Category: "Contracts",
		LP:       "0",
		Cost:     "250",
		Source:   "CA",
		Page:     "144",
	},
	"vocal_tension_lie_detection": {
		ID:       "c5eef5c6-288a-47c0-8d2a-42353a896077",
		Name:     "Vocal Tension Lie Detection",
		Category: "Contracts",
		LP:       "0",
		Cost:     "250",
		Source:   "CA",
		Page:     "144",
	},
}

// DataCities contains city records keyed by name (lowercase with underscores)
var DataCities = map[string]City{
	"seattle": {
		Name:   "Seattle",
		Source: "",
		Page:   "",
	},
	"pretoria_witwatersrand_vaal": {
		Name:   "Pretoria-Witwatersrand-Vaal",
		Source: "",
		Page:   "",
	},
	"denver": {
		Name:   "Denver",
		Source: "",
		Page:   "",
	},
	"fdc": {
		Name:   "FDC",
		Source: "",
		Page:   "",
	},
	"portland": {
		Name:   "Portland",
		Source: "",
		Page:   "",
	},
	"chicago": {
		Name:   "Chicago",
		Source: "",
		Page:   "",
	},
	"los_angeles": {
		Name:   "Los Angeles",
		Source: "",
		Page:   "",
	},
	"cheyenne": {
		Name:   "Cheyenne",
		Source: "",
		Page:   "",
	},
	"new_york_city": {
		Name:   "New York City",
		Source: "",
		Page:   "",
	},
	"atlanta": {
		Name:   "Atlanta",
		Source: "",
		Page:   "",
	},
	"berlin": {
		Name:   "Berlin",
		Source: "",
		Page:   "",
	},
	"hong_kong": {
		Name:   "Hong Kong",
		Source: "",
		Page:   "",
	},
	"dubai": {
		Name:   "Dubai",
		Source: "",
		Page:   "",
	},
	"europort": {
		Name:   "Europort",
		Source: "",
		Page:   "",
	},
	"nairobi": {
		Name:   "Nairobi",
		Source: "",
		Page:   "",
	},
	"tenochtitlán": {
		Name:   "Tenochtitl\u00e1n",
		Source: "",
		Page:   "",
	},
	"neo_tokyo": {
		Name:   "Neo-Tokyo",
		Source: "",
		Page:   "",
	},
}
