package v5

// DataMartialArts contains martial art records keyed by their ID (lowercase with underscores)
var DataMartialArts = map[string]MartialArt{
	"52_blocks": {
		ID:         "de351d4e-4384-4dda-a37f-e0e4537e1445",
		Name:       "52 Blocks",
		Source:     "RG",
		Page:       "128",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "52 Blocks"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Disarm)"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Multiple Opponent Defense (Defender has Defended)"}, MartialArtTechnique{Name: "Pouncing Dragon"}, MartialArtTechnique{Name: "Randori (Dirty Trick)"}, MartialArtTechnique{Name: "Rooted Tree"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"aikido": {
		ID:         "f0b55f24-a184-4d91-a4c2-71b480bace0b",
		Name:       "Aikido",
		Source:     "RG",
		Page:       "128",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Aikido"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Disarm)"}, MartialArtTechnique{Name: "Constrictor's Crush"}, MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Throw Person"}, MartialArtTechnique{Name: "Yielding Force (Counterstrike)"}, MartialArtTechnique{Name: "Yielding Force (Throw)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"arnis_de_mano": {
		ID:         "906a51fa-584d-4d5d-8608-f28e08d61902",
		Name:       "Arnis De Mano",
		Source:     "RG",
		Page:       "128",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Clubs", Spec: "Arnis De Mano"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Close Quarter Defense Against Firearms"}, MartialArtTechnique{Name: "Multiple Opponent Combat"}, MartialArtTechnique{Name: "Opposing Force (Parry)"}, MartialArtTechnique{Name: "Randori (Vitals)"}, MartialArtTechnique{Name: "Two-Weapon Style Attack"}, MartialArtTechnique{Name: "Two-Weapon Style Defense"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"bartitsu": {
		ID:         "d866e4b6-01fe-4ec6-b7b9-292d06015fc0",
		Name:       "Bartitsu",
		Source:     "RG",
		Page:       "128",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Clubs", Spec: "Bartitsu"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Ballestra"}, MartialArtTechnique{Name: "Bending of the Reed"}, MartialArtTechnique{Name: "Called Shot (Disarm)"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Riposte"}, MartialArtTechnique{Name: "Sweep"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"boxing_brawler_style": {
		ID:         "03c1ba09-e8b5-492d-8752-bb9fb2ab438d",
		Name:       "Boxing (Brawler Style)",
		Source:     "RG",
		Page:       "129",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Boxing (Brawler Style)"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Full Offense"}, MartialArtTechnique{Name: "Haymaker"}, MartialArtTechnique{Name: "Opposing Force (Block)"}, MartialArtTechnique{Name: "Stagger"}, MartialArtTechnique{Name: "Thunder Strike"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"boxing_classic_style": {
		ID:         "5e02ce33-4cbd-4003-bc93-5d5971749eae",
		Name:       "Boxing (Classic Style)",
		Source:     "RG",
		Page:       "129",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Boxing (Classic Style)"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Bending of the Reed"}, MartialArtTechnique{Name: "Called Shot (Feint)"}, MartialArtTechnique{Name: "Haymaker"}, MartialArtTechnique{Name: "Oaken Stance (Defense Against Being Knocked Down)"}, MartialArtTechnique{Name: "Opposing Force (Block)"}, MartialArtTechnique{Name: "Silken Storm"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"boxing_swarmer_style": {
		ID:         "39b7d61b-b95e-4787-b3b0-df3c2a8bec5c",
		Name:       "Boxing (Swarmer Style)",
		Source:     "RG",
		Page:       "129",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Boxing (Swarmer Style)"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Bending of the Reed"}, MartialArtTechnique{Name: "Called Shot (Feint)"}, MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Haymaker"}, MartialArtTechnique{Name: "Silken Storm"}, MartialArtTechnique{Name: "Two-Headed Snake"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"capoeira": {
		ID:         "5debcf68-304d-4ce6-97ee-9c00fc47f449",
		Name:       "Capoeira",
		Source:     "RG",
		Page:       "129",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Capoeira"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Bending of the Reed"}, MartialArtTechnique{Name: "Called Shot (Feint)"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Kip-Up"}, MartialArtTechnique{Name: "Sweep"}, MartialArtTechnique{Name: "Tricking"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"carromeleg": {
		ID:         "6ff0927a-ba0c-44cf-abea-0d180768f73b",
		Name:       "Carromeleg",
		Source:     "RG",
		Page:       "129",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Carromeleg"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Iaijutsu"}, MartialArtTechnique{Name: "Imposing Stone"}, MartialArtTechnique{Name: "Riposte"}, MartialArtTechnique{Name: "Shadow Block"}, MartialArtTechnique{Name: "Stagger"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"chakram_fighting": {
		ID:         "5170a688-54a0-4a71-899a-edfea5dec0a2",
		Name:       "Chakram Fighting",
		Source:     "RG",
		Page:       "129",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Pin)"}, MartialArtTechnique{Name: "Close Quarter Firearms (Thrown Weapons)"}, MartialArtTechnique{Name: "Knucklebreaker (Disarm)"}, MartialArtTechnique{Name: "Multiple Opponent Defense (Friends in Melee)"}, MartialArtTechnique{Name: "Opposing Force (Block)"}, MartialArtTechnique{Name: "Ti Khao"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"drunken_boxing": {
		ID:         "2327a330-3b9c-49a9-a392-8f34579e5bce",
		Name:       "Drunken Boxing",
		Source:     "RG",
		Page:       "130",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Drunken Boxing"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Disarm)"}, MartialArtTechnique{Name: "Called Shot (Feint)"}, MartialArtTechnique{Name: "Defiant Dance"}, MartialArtTechnique{Name: "Full Offense"}, MartialArtTechnique{Name: "Karmic Response"}, MartialArtTechnique{Name: "Two-Headed Snake"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"fiore_dei_liberi": {
		ID:         "15ea5191-d615-4320-84e5-bffa90f8873e",
		Name:       "Fiore Dei Liberi",
		Source:     "RG",
		Page:       "130",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Blades", Spec: "Fiore dei Liberi"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Break Weapon)"}, MartialArtTechnique{Name: "Opposing Force (Parry)"}, MartialArtTechnique{Name: "Riposte"}, MartialArtTechnique{Name: "Two-Weapon Style Attack"}, MartialArtTechnique{Name: "Two-Weapon Style Defense"}, MartialArtTechnique{Name: "Yielding Force (Riposte)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"firefight": {
		ID:         "3a16d253-73cb-41e0-8c52-8f5b79d27a58",
		Name:       "Firefight",
		Source:     "RG",
		Page:       "130",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Close Quarter Defense Against Firearms"}, MartialArtTechnique{Name: "Close Quarter Firearms (Pistols)"}, MartialArtTechnique{Name: "Multiple Opponent Defense (Friends in Melee)"}, MartialArtTechnique{Name: "Oaken Stance (Defense Against Being Knocked Down)"}, MartialArtTechnique{Name: "Oaken Stance (Defense Against Being Charged)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"gun_kata": {
		ID:         "23c0c9dc-da26-40ab-a578-7cd1a2231ba1",
		Name:       "Gun Kata",
		Source:     "RG",
		Page:       "130",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Close Quarter Firearms (Pistols)"}, MartialArtTechnique{Name: "Kip-Up"}, MartialArtTechnique{Name: "Multiple Opponent Defense (Friends in Melee)"}, MartialArtTechnique{Name: "Opposing Force (Block)"}, MartialArtTechnique{Name: "Tricking"}, MartialArtTechnique{Name: "Stagger"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"jeet_kune_do": {
		ID:         "8940f70e-e81d-4e64-b8e0-52256ee28cf9",
		Name:       "Jeet Kune Do",
		Source:     "RG",
		Page:       "130",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Jeet Kune Do"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Bending of the Reed"}, MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Opposing Force (Block)"}, MartialArtTechnique{Name: "Randori (Vitals)"}, MartialArtTechnique{Name: "Yielding Force (Counterstrike)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"jogo_du_pau": {
		ID:         "fa11a3e1-a658-4353-8d74-71337e3e1f29",
		Name:       "Jogo Du Pau",
		Source:     "RG",
		Page:       "130",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Clubs", Spec: "Jogo Du Pau"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Barbed Hooks"}, MartialArtTechnique{Name: "Herding"}, MartialArtTechnique{Name: "Oaken Stance (Defense Against Being Charged)"}, MartialArtTechnique{Name: "Oaken Stance (Defense Against Being Knocked Down)"}, MartialArtTechnique{Name: "Opposing Force (Parry)"}, MartialArtTechnique{Name: "Pouncing Dragon"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"jujitsu": {
		ID:         "7415286a-11b7-41b6-ad18-a4c72067cb71",
		Name:       "Jujitsu",
		Source:     "RG",
		Page:       "131",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Jujitsu"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Disarm)"}, MartialArtTechnique{Name: "Chin Na"}, MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Sacrificial Throw"}, MartialArtTechnique{Name: "Sweep"}, MartialArtTechnique{Name: "Throw Person"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"karate": {
		ID:         "16391532-2476-4a9f-b5d8-ae058b7e0f27",
		Name:       "Karate",
		Source:     "RG",
		Page:       "131",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Karate"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Kip-Up"}, MartialArtTechnique{Name: "Opposing Force (Block)"}, MartialArtTechnique{Name: "Sweep"}, MartialArtTechnique{Name: "Yielding Force (Counterstrike)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"kenjutsu": {
		ID:         "922b9b42-6e88-4ab6-a255-00fe2b025f2a",
		Name:       "Kenjutsu",
		Source:     "RG",
		Page:       "131",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Blades", Spec: "Kenjutsu"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Bending of the Reed"}, MartialArtTechnique{Name: "Finishing Move"}, MartialArtTechnique{Name: "Iaijutsu"}, MartialArtTechnique{Name: "Multiple Opponent Combat"}, MartialArtTechnique{Name: "Multiple Opponent Defense (Friends in Melee)"}, MartialArtTechnique{Name: "Opposing Force (Parry)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"knight_errant_tactical": {
		ID:         "57a1e6dd-a78c-4fb7-94e0-db4a7b8b7f63",
		Name:       "Knight Errant Tactical",
		Source:     "RG",
		Page:       "132",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Barbed Hooks"}, MartialArtTechnique{Name: "Broken Fang"}, MartialArtTechnique{Name: "Called Shot (Break Weapon)"}, MartialArtTechnique{Name: "Close Quarter Defense Against Firearms"}, MartialArtTechnique{Name: "Hammerfist"}, MartialArtTechnique{Name: "Imposing Stone"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"krav_maga": {
		ID:         "3b3c2299-5a76-4cf4-962f-160fecbdd38b",
		Name:       "Krav Maga",
		Source:     "RG",
		Page:       "132",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Krav Maga"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Disarm)"}, MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Constrictor's Crush"}, MartialArtTechnique{Name: "Imposing Stone"}, MartialArtTechnique{Name: "Releasing Talons"}, MartialArtTechnique{Name: "Ti Khao"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"kunst_des_fechtens": {
		ID:         "69097cfa-cfdd-49d9-b65a-e866d2296b7e",
		Name:       "Kunst Des Fechtens",
		Source:     "RG",
		Page:       "132",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Blades", Spec: "Kunst Des Fechtens (Long Sword Fighting)"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Half Sword"}, MartialArtTechnique{Name: "Multiple Opponent Combat"}, MartialArtTechnique{Name: "Opposing Force (Parry)"}, MartialArtTechnique{Name: "Pouncing Dragon"}, MartialArtTechnique{Name: "Riposte"}, MartialArtTechnique{Name: "Yielding Force (Riposte)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"kyujutsu": {
		ID:         "7a2eb5f6-fbb5-4952-95dc-352570c00e52",
		Name:       "Kyujutsu",
		Source:     "RG",
		Page:       "132",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Archery", Spec: "Kyujutsu"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Pin)"}, MartialArtTechnique{Name: "Close Quarter Firearms (Archery)"}, MartialArtTechnique{Name: "Hammerfist"}, MartialArtTechnique{Name: "Knucklebreaker (Blast Out of Hands)"}, MartialArtTechnique{Name: "Soaring Shackles"}, MartialArtTechnique{Name: "Tricking"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"la_verdadera_destreza": {
		ID:         "21bc338f-7b28-49df-9d11-e4db076404be",
		Name:       "La Verdadera Destreza",
		Source:     "RG",
		Page:       "132",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Blades", Spec: "La Verdadera Destreza (Rapier Fighting)"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Ballestra"}, MartialArtTechnique{Name: "Multiple Opponent Combat"}, MartialArtTechnique{Name: "Multiple Opponent Defense (Friends in Melee)"}, MartialArtTechnique{Name: "Multiple Opponent Defense (Defender has Defended)"}, MartialArtTechnique{Name: "Opposing Force (Parry)"}, MartialArtTechnique{Name: "Riposte"}, MartialArtTechnique{Name: "Yielding Force (Riposte)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"lone_star_tactical": {
		ID:         "5366bd5d-ff0a-4277-b02d-24e10ac76319",
		Name:       "Lone Star Tactical",
		Source:     "RG",
		Page:       "132",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Break Weapon)"}, MartialArtTechnique{Name: "Close Quarter Defense Against Firearms"}, MartialArtTechnique{Name: "Herding"}, MartialArtTechnique{Name: "Multiple Opponent Defense (Defender has Defended)"}, MartialArtTechnique{Name: "Oaken Stance (Defense Against Being Charged)"}, MartialArtTechnique{Name: "Rooted Tree"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"muay_thai": {
		ID:         "af544c56-2c65-403a-a83b-e861e02c72bb",
		Name:       "Muay Thai",
		Source:     "RG",
		Page:       "133",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Muay Thai"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Crushing Jaws"}, MartialArtTechnique{Name: "Finishing Move"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Thunder Strike"}, MartialArtTechnique{Name: "Ti Khao"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"ninjutsu": {
		ID:         "0b2aba07-cd8e-40b8-8bd5-a89b0c7d9699",
		Name:       "Ninjutsu",
		Source:     "RG",
		Page:       "133",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Dim Mak"}, MartialArtTechnique{Name: "Flying Kick"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Randori (Dirty Trick)"}, MartialArtTechnique{Name: "Tricking"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"okichitaw": {
		ID:         "f8c89602-b72f-4613-81b8-72951dcad4c9",
		Name:       "Okichitaw",
		Source:     "RG",
		Page:       "133",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Clubs", Spec: "Okichitaw"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Pin)"}, MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Opposing Force (Parry)"}, MartialArtTechnique{Name: "Randori (Vitals)"}, MartialArtTechnique{Name: "Shadow Block"}, MartialArtTechnique{Name: "Sweep"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"parkour": {
		ID:         "e613f285-bc8d-40a2-a968-da4aa567cbcc",
		Name:       "Parkour",
		Source:     "RG",
		Page:       "133",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Gymnastics", Spec: "Parkour"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Bending of the Reed"}, MartialArtTechnique{Name: "Kip-Up"}, MartialArtTechnique{Name: "Leaping Mantis"}, MartialArtTechnique{Name: "Monkey Climb"}, MartialArtTechnique{Name: "Rolling Clouds"}, MartialArtTechnique{Name: "Shadow Block"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"pentjak_silat": {
		ID:         "0b792f6c-c12e-4e93-b830-1f201e267bbc",
		Name:       "Pentjak-Silat",
		Source:     "RG",
		Page:       "133",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Blades", Spec: "Pentjak-Silat"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Break Weapon)"}, MartialArtTechnique{Name: "Called Shot (Disarm)"}, MartialArtTechnique{Name: "Dim Mak"}, MartialArtTechnique{Name: "Jiao Di (Charge)"}, MartialArtTechnique{Name: "Randori (Vitals)"}, MartialArtTechnique{Name: "Silken Storm"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"quarterstaff_fighting": {
		ID:         "36e8103e-a362-49d5-959b-689d06dac350",
		Name:       "Quarterstaff Fighting",
		Source:     "RG",
		Page:       "133",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Clubs", Spec: "Quarterstaff Fighting"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Jiao Di (Knock Down)"}, MartialArtTechnique{Name: "Multiple Opponent Combat"}, MartialArtTechnique{Name: "Opposing Force (Parry)"}, MartialArtTechnique{Name: "Sweep"}, MartialArtTechnique{Name: "Stagger"}, MartialArtTechnique{Name: "Thunder Strike"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"sangre_y_acero": {
		ID:         "3771abcc-6307-4ddf-9ab5-df86bc591da6",
		Name:       "Sangre Y Acero",
		Source:     "RG",
		Page:       "133",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Sangre Y Acero"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Break Weapon)"}, MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Crushing Jaws"}, MartialArtTechnique{Name: "Finishing Move"}, MartialArtTechnique{Name: "Pouncing Dragon"}, MartialArtTechnique{Name: "Tricking"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"tae_kwon_do": {
		ID:         "3e0d63a0-b784-4315-aa66-89b92818a267",
		Name:       "Tae Kwon Do",
		Source:     "RG",
		Page:       "133",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Tae Kwon Do"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Flying Kick"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Opposing Force (Block)"}, MartialArtTechnique{Name: "Sweep"}, MartialArtTechnique{Name: "Tricking"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"the_cowboy_way": {
		ID:         "f5829122-0973-4e27-98b4-f54c9343a57c",
		Name:       "The Cowboy Way",
		Source:     "RG",
		Page:       "133",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Entanglement)"}, MartialArtTechnique{Name: "Hammerfist"}, MartialArtTechnique{Name: "Haymaker"}, MartialArtTechnique{Name: "Knucklebreaker (Blast Out of Hands)"}, MartialArtTechnique{Name: "Stagger"}, MartialArtTechnique{Name: "Tricking"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"turkish_archery": {
		ID:         "6b5ae017-9fb1-46df-839b-4548ad360534",
		Name:       "Turkish Archery",
		Source:     "RG",
		Page:       "134",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Archery", Spec: "Turkish Archery"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Pin)"}, MartialArtTechnique{Name: "Close Quarter Defense Against Firearms"}, MartialArtTechnique{Name: "Hammerfist"}, MartialArtTechnique{Name: "Silken Storm"}, MartialArtTechnique{Name: "Soaring Shackles"}, MartialArtTechnique{Name: "Thunder Strike"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"whip_fighting": {
		ID:         "18c44152-1ca8-435c-a72d-e443d3f1e7c6",
		Name:       "Whip Fighting",
		Source:     "RG",
		Page:       "134",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Bending of the Reed"}, MartialArtTechnique{Name: "Called Shot (Entanglement)"}, MartialArtTechnique{Name: "Hammerfist"}, MartialArtTechnique{Name: "Herding"}, MartialArtTechnique{Name: "Multiple Opponent Defense (Friends in Melee)"}, MartialArtTechnique{Name: "Multiple Opponent Combat"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"wildcat": {
		ID:         "df0b9bb0-bad9-4bb9-b543-eb73edfe34e8",
		Name:       "Wildcat",
		Source:     "RG",
		Page:       "134",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Wildcat"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Dim Mak"}, MartialArtTechnique{Name: "Finishing Move"}, MartialArtTechnique{Name: "Multiple Opponent Combat"}, MartialArtTechnique{Name: "Ti Khao"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"wrestling_sport_style": {
		ID:         "24ee13d8-9b6d-4fc0-908c-d9904db364c7",
		Name:       "Wrestling (Sport Style)",
		Source:     "RG",
		Page:       "134",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Wrestling (Sport Style)"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Constrictor's Crush"}, MartialArtTechnique{Name: "Jiao Di (Knock Down)"}, MartialArtTechnique{Name: "Karmic Response"}, MartialArtTechnique{Name: "Sweep"}, MartialArtTechnique{Name: "Throw Person"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"wrestling_sumo_style": {
		ID:         "03e7e806-2bf6-43d2-ae51-9a724aca67fc",
		Name:       "Wrestling (Sumo Style)",
		Source:     "RG",
		Page:       "134",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Wrestling (Sumo Style)"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Barbed Hooks"}, MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Herding"}, MartialArtTechnique{Name: "Jiao Di (Knock Down)"}, MartialArtTechnique{Name: "Rooted Tree"}, MartialArtTechnique{Name: "Throw Person"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"wrestling_professional_style": {
		ID:         "06d5eac3-1ec1-4164-8014-e8f6ae47de0f",
		Name:       "Wrestling (Professional Style)",
		Source:     "RG",
		Page:       "134",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Wrestling (Professional Style)"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Jiao Di (Charge)"}, MartialArtTechnique{Name: "Karmic Response"}, MartialArtTechnique{Name: "Sacrifice Throw"}, MartialArtTechnique{Name: "Tricking"}, MartialArtTechnique{Name: "Yielding Force (Throw)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"wrestling_mma_style": {
		ID:         "43aedfbf-c4ef-4682-a8a3-9f53363a3e60",
		Name:       "Wrestling (MMA Style)",
		Source:     "RG",
		Page:       "135",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Wrestling (MMA Style)"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Constrictor's Crush"}, MartialArtTechnique{Name: "Crushing Jaws"}, MartialArtTechnique{Name: "Jiao Di (Knock Down)"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Pouncing Dragon"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"wudang_sword": {
		ID:         "bd876c27-26b0-4b37-a236-b5da99d5c503",
		Name:       "Wudang Sword",
		Source:     "RG",
		Page:       "135",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Blades", Spec: "Wudang Sword"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Ballestra"}, MartialArtTechnique{Name: "Finishing Move"}, MartialArtTechnique{Name: "Flying Kick"}, MartialArtTechnique{Name: "Hammerfist"}, MartialArtTechnique{Name: "Iaijutsu"}, MartialArtTechnique{Name: "Riposte"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"one_trick_pony": {
		ID:     "0325b2c8-0a48-497f-92b1-2830a5ac467f",
		Name:   "One Trick Pony",
		Source: "RG",
		Page:   "127",
	},
	"way_of_unified_mana_hapsum_do": {
		ID:         "116723ab-ef17-4078-9b6b-609c24861c96",
		Name:       "Way of Unified Mana (Hapsum-Do)",
		Source:     "FA",
		Page:       "101",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Disarm)"}, MartialArtTechnique{Name: "Mana Choke"}, MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Yielding Force (Counterstrike)"}, MartialArtTechnique{Name: "Yielding Force (Throw)"}, MartialArtTechnique{Name: "Mana Strike"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"alpine_wrestling": {
		ID:         "d1baf7a8-d65b-46d0-b5dc-2bb4a3f18c80",
		Name:       "Alpine Wrestling",
		Source:     "SAG",
		Page:       "17",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Oaken Stance"}, MartialArtTechnique{Name: "Rooted Tree"}, MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Karmic Response"}, MartialArtTechnique{Name: "Throw Person"}, MartialArtTechnique{Name: "Imposing Stone"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"german_jujitsu": {
		ID:         "7bbd5565-5020-4ef1-8ff0-9329cbffcfa9",
		Name:       "German Jujitsu",
		Source:     "SAG",
		Page:       "17",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Disarm)"}, MartialArtTechnique{Name: "Sweep"}, MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Throw Person"}, MartialArtTechnique{Name: "Defiant Dance"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"esdo": {
		ID:         "616efc1e-65cf-44fb-96ef-a312108c5419",
		Name:       "Esdo",
		Source:     "SAG",
		Page:       "17",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Oaken Stance"}, MartialArtTechnique{Name: "Bending of the Reed"}, MartialArtTechnique{Name: "Counterstrike"}, MartialArtTechnique{Name: "Kick Attack"}, MartialArtTechnique{Name: "Stagger"}, MartialArtTechnique{Name: "Yielding Force (Counterstrike)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"urban_brawl_parkour": {
		ID:         "d932cfb7-2a62-4878-9c17-4697998f9447",
		Name:       "Urban Brawl Parkour",
		Source:     "SAG",
		Page:       "17",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Tricking"}, MartialArtTechnique{Name: "Monkey Climb"}, MartialArtTechnique{Name: "Close Quarter Firearms (Pistols)"}, MartialArtTechnique{Name: "Close Quarter Defense Against Firearms"}, MartialArtTechnique{Name: "Rolling Clouds"}, MartialArtTechnique{Name: "Leaping Mantis"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"sternschutz_tactical": {
		ID:         "85623e1c-53da-43cb-b873-2357e9c5020d",
		Name:       "Sternschutz Tactical",
		Source:     "SAG",
		Page:       "17",
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Oaken Stance"}, MartialArtTechnique{Name: "Called Shot (Break Weapon)"}, MartialArtTechnique{Name: "Broken Fang"}, MartialArtTechnique{Name: "Hammerfist"}, MartialArtTechnique{Name: "Opposing Force (Parry)"}, MartialArtTechnique{Name: "Close Quarter Defense Against Firearms"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"arbeitskreis_ini": {
		ID:         "e253fc2a-87f5-4a20-9f2c-c0b9e54e0f6e",
		Name:       "Arbeitskreis INI",
		Source:     "SOTG",
		Page:       "6",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Blades", Spec: "Arbeitskreis INI"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Finishing Move"}, MartialArtTechnique{Name: "Half-Sword"}, MartialArtTechnique{Name: "Hammer Fist"}, MartialArtTechnique{Name: "Jiao Di"}, MartialArtTechnique{Name: "Knucklebreaker"}, MartialArtTechnique{Name: "Full Offense"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"circle_fencing": {
		ID:         "e78deb30-4e17-4b86-b084-897009c55a15",
		Name:       "Circle Fencing",
		Source:     "SOTG",
		Page:       "5",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Blades", Spec: "Circle Fencing"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Called Shot (Feint)"}, MartialArtTechnique{Name: "Called Shot (Break Weapon)"}, MartialArtTechnique{Name: "Broken Fang"}, MartialArtTechnique{Name: "Herding"}, MartialArtTechnique{Name: "Multiple Opponent Combat"}, MartialArtTechnique{Name: "Two-Headed Snake"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"kreussler_fencing": {
		ID:         "70f75f97-ba03-41a6-b591-7c3ae24953a2",
		Name:       "Kreussler Fencing",
		Source:     "SOTG",
		Page:       "5",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Blades", Spec: "Kreussler Fencing"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Ballestra"}, MartialArtTechnique{Name: "Hammerfist"}, MartialArtTechnique{Name: "Iaijutsu"}, MartialArtTechnique{Name: "Knucklebreaker"}, MartialArtTechnique{Name: "Riposte"}, MartialArtTechnique{Name: "Yielding Force (Riposte)"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
	"asthenologica": {
		ID:         "736db820-cbe4-4a0b-b6c3-d90471117731",
		Name:       "Asthenologica",
		Source:     "SOTG",
		Page:       "6",
		Bonus:      &MartialArtBonus{AddSkillSpecializationOption: &AddSkillSpecializationOption{Skill: "Unarmed Combat", Spec: "Asthenologica"}},
		Techniques: &MartialArtTechniques{Technique: []interface{}{MartialArtTechnique{Name: "Clinch"}, MartialArtTechnique{Name: "Dim Mak"}, MartialArtTechnique{Name: "Multiple Opponent Combat"}, MartialArtTechnique{Name: "Defiant Dance"}, MartialArtTechnique{Name: "Stagger"}, MartialArtTechnique{Name: "Karmic Response"}, MartialArtTechnique{Name: "Neijia"}, MartialArtTechnique{Name: "Strike the Darkness"}}},
	},
}

// DataTechniques contains technique definition records keyed by their ID (lowercase with underscores)
var DataTechniques = map[string]Technique{
	"ballestra": {
		ID:     "d2234863-297d-4a61-a939-ff263381e209",
		Name:   "Ballestra",
		Source: "RG",
		Page:   "119",
	},
	"barbed_hooks": {
		ID:     "c46f550f-3148-4b91-a0fa-299a57e7879c",
		Name:   "Barbed Hooks",
		Source: "RG",
		Page:   "135",
	},
	"bending_of_the_reed": {
		ID:     "378a6f47-9375-4810-8324-4a6230cd6914",
		Name:   "Bending of the Reed",
		Source: "RG",
		Page:   "135",
	},
	"broken_fang": {
		ID:     "8ba77379-ee89-49ab-a2a5-37194d9a992e",
		Name:   "Broken Fang",
		Source: "RG",
		Page:   "135",
	},
	"called_shot_break_weapon": {
		ID:     "eb766a12-66c7-44f4-bdc8-a3ae6f8f6770",
		Name:   "Called Shot (Break Weapon)",
		Source: "RG",
		Page:   "111",
	},
	"called_shot_disarm": {
		ID:     "56ec87e6-d962-4b97-88e8-947cd09ea161",
		Name:   "Called Shot (Disarm)",
		Source: "RG",
		Page:   "111",
	},
	"called_shot_entanglement": {
		ID:     "d9e3774b-4b68-4dff-8c0b-3234a6a3f878",
		Name:   "Called Shot (Entanglement)",
		Source: "RG",
		Page:   "111",
	},
	"called_shot_feint": {
		ID:     "57bc4b34-1f4d-4a19-8413-54f2ddafecd9",
		Name:   "Called Shot (Feint)",
		Source: "RG",
		Page:   "111",
	},
	"called_shot_pin": {
		ID:     "a24a6c9f-6edd-4852-9d3d-785c51a40f25",
		Name:   "Called Shot (Pin)",
		Source: "RG",
		Page:   "112",
	},
	"chin_na": {
		ID:     "3d22777f-39c5-472f-b54a-703ed042d8b3",
		Name:   "Chin Na",
		Source: "RG",
		Page:   "136",
	},
	"clinch": {
		ID:     "e2bedc2b-59c3-45a1-9e0f-2e4f0234a0cf",
		Name:   "Clinch",
		Source: "RG",
		Page:   "119",
	},
	"close_quarter_firearms_archery": {
		ID:     "0f324bd2-3fad-4721-9335-f82aaaee86cf",
		Name:   "Close Quarter Firearms (Archery)",
		Source: "RG",
		Page:   "136",
	},
	"close_quarter_firearms_thrown_weapons": {
		ID:     "05666129-d102-469f-a957-a6456027c9c9",
		Name:   "Close Quarter Firearms (Thrown Weapons)",
		Source: "RG",
		Page:   "136",
	},
	"close_quarter_firearms_automatics": {
		ID:     "c04ce0ed-32d8-4e00-9d50-7be7b5e250fc",
		Name:   "Close Quarter Firearms (Automatics)",
		Source: "RG",
		Page:   "136",
	},
	"close_quarter_firearms_exotic_ranged_weapon": {
		ID:     "8022a74f-547c-4b1e-82b2-e1ce42dbae62",
		Name:   "Close Quarter Firearms (Exotic Ranged Weapon)",
		Source: "RG",
		Page:   "136",
	},
	"close_quarter_firearms_heavy_weapons": {
		ID:     "34dcd6bd-dce4-43b9-bee8-ae18ab3a52b9",
		Name:   "Close Quarter Firearms (Heavy Weapons)",
		Source: "RG",
		Page:   "136",
	},
	"close_quarter_firearms_longarms": {
		ID:     "1d0afa0f-416a-4075-abbd-cc5112429639",
		Name:   "Close Quarter Firearms (Longarms)",
		Source: "RG",
		Page:   "136",
	},
	"close_quarter_firearms_pistols": {
		ID:     "44e0f0bb-2f30-4513-beab-1e0a6c033dd5",
		Name:   "Close Quarter Firearms (Pistols)",
		Source: "RG",
		Page:   "136",
	},
	"close_quarter_defense_against_firearms": {
		ID:     "e6e3ef1e-9bbc-408a-b2c0-1ac1d4143e9c",
		Name:   "Close Quarter Defense Against Firearms",
		Source: "RG",
		Page:   "137",
	},
	"constrictors_crush": {
		ID:     "06a17020-5b3a-409b-b8bf-19c4365fd594",
		Name:   "Constrictor's Crush",
		Source: "RG",
		Page:   "137",
	},
	"counterstrike": {
		ID:     "11a90b83-af42-4972-a028-0ab4c60e1c33",
		Name:   "Counterstrike",
		Source: "RG",
		Page:   "124",
	},
	"crushing_jaws": {
		ID:     "ec74b517-5c0d-46e6-a61b-5ab1b7316d5d",
		Name:   "Crushing Jaws",
		Source: "RG",
		Page:   "137",
	},
	"defiant_dance": {
		ID:     "1b1dc37d-daf1-430c-a352-50f9b2cbe68e",
		Name:   "Defiant Dance",
		Source: "RG",
		Page:   "137",
	},
	"dim_mak": {
		ID:     "cf776709-ffd2-4871-8a63-35efb5b73dbb",
		Name:   "Dim Mak",
		Source: "RG",
		Page:   "137",
	},
	"finishing_move": {
		ID:     "3aba0ece-6ced-48ab-a873-3787c58df995",
		Name:   "Finishing Move",
		Source: "RG",
		Page:   "120",
	},
	"flying_kick": {
		ID:     "601d98dd-5897-4974-af2e-72b5053bde62",
		Name:   "Flying Kick",
		Source: "RG",
		Page:   "121",
	},
	"full_offense": {
		ID:     "d98d277b-a727-4381-9512-e8f64ad275ff",
		Name:   "Full Offense",
		Source: "RG",
		Page:   "121",
	},
	"grasping_vines": {
		ID:     "1df1bc89-a5d5-47e6-8685-7c09078ba17f",
		Name:   "Grasping Vines",
		Source: "RG",
		Page:   "137",
	},
	"half_sword": {
		ID:     "f79771b2-067e-4fa4-b295-b5e6a48fc5f0",
		Name:   "Half Sword",
		Source: "RG",
		Page:   "121",
	},
	"hammerfist": {
		ID:     "2a28146f-cbd9-4cdd-98ba-59bd6eb65ded",
		Name:   "Hammerfist",
		Source: "RG",
		Page:   "138",
	},
	"haymaker": {
		ID:     "dbeae1ec-ebb5-4283-b80e-e66ab08c892d",
		Name:   "Haymaker",
		Source: "RG",
		Page:   "121",
	},
	"herding": {
		ID:     "971cac23-8ac2-4419-8d6b-f1de2641d7b3",
		Name:   "Herding",
		Source: "RG",
		Page:   "121",
	},
	"iaijutsu": {
		ID:     "6de0cc4b-d9b5-485c-9b4a-c6e4abeaf7d4",
		Name:   "Iaijutsu",
		Source: "RG",
		Page:   "122",
	},
	"imposing_stone": {
		ID:     "e812caf9-7e6b-4963-bb9b-ea7ce8e46ea3",
		Name:   "Imposing Stone",
		Source: "RG",
		Page:   "138",
	},
	"jiao_di_charge": {
		ID:     "8a457d21-cc45-4f60-b9d3-0891f0c47c10",
		Name:   "Jiao Di (Charge)",
		Source: "RG",
		Page:   "138",
	},
	"jiao_di_knock_down": {
		ID:     "84036a28-53d6-426f-935f-1f176964fc8a",
		Name:   "Jiao Di (Knock Down)",
		Source: "RG",
		Page:   "138",
	},
	"karmic_response": {
		ID:     "256bab6a-236d-4f76-93b1-d1dfe3b6df13",
		Name:   "Karmic Response",
		Source: "RG",
		Page:   "138",
	},
	"kick_attack": {
		ID:     "5a29bdb8-5233-44ab-b5e0-5cf892559fc1",
		Name:   "Kick Attack",
		Source: "RG",
		Page:   "138",
	},
	"kip_up": {
		ID:     "daa9edc5-d5dd-466a-8df9-7abb6a358db1",
		Name:   "Kip-Up",
		Source: "RG",
		Page:   "122",
	},
	"knucklebreaker_disarm": {
		ID:     "d89b18bb-9146-4ad4-8aef-efcb25a537a2",
		Name:   "Knucklebreaker (Disarm)",
		Source: "RG",
		Page:   "139",
	},
	"knucklebreaker_blast_out_of_hands": {
		ID:     "4e3d4a86-d949-40dc-83c1-3358b42fc1f8",
		Name:   "Knucklebreaker (Blast Out of Hands)",
		Source: "RG",
		Page:   "139",
	},
	"leaping_mantis": {
		ID:     "5d25f0c8-1bfe-476d-b7b5-672f4ea36c80",
		Name:   "Leaping Mantis",
		Source: "RG",
		Page:   "139",
	},
	"monkey_climb": {
		ID:     "96191a29-30c4-4973-bb45-8e267f0e221a",
		Name:   "Monkey Climb",
		Source: "RG",
		Page:   "139",
	},
	"multiple_opponent_combat": {
		ID:     "a1ef3f0f-a36d-493b-b251-6385a15c51f7",
		Name:   "Multiple Opponent Combat",
		Source: "RG",
		Page:   "139",
	},
	"multiple_opponent_defense_friends_in_melee": {
		ID:     "bf72ba84-4301-486c-9c9e-f6179fd5f297",
		Name:   "Multiple Opponent Defense (Friends in Melee)",
		Source: "RG",
		Page:   "139",
	},
	"multiple_opponent_defense_defender_has_defended": {
		ID:     "d5ca554c-fb2b-480c-ab0c-ad6c05fa919b",
		Name:   "Multiple Opponent Defense (Defender has Defended)",
		Source: "RG",
		Page:   "139",
	},
	"oaken_stance_defense_against_being_knocked_down": {
		ID:     "1ff734f2-094f-482f-9b52-3583f8d589bb",
		Name:   "Oaken Stance (Defense Against Being Knocked Down)",
		Source: "RG",
		Page:   "139",
	},
	"oaken_stance_defense_against_being_charged": {
		ID:     "371d0b75-f8a4-4fc8-90ee-9728d27eaca4",
		Name:   "Oaken Stance (Defense Against Being Charged)",
		Source: "RG",
		Page:   "139",
	},
	"opposing_force_block": {
		ID:     "1f772fd3-7fd6-4c42-a17f-fd363f46f9fa",
		Name:   "Opposing Force (Block)",
		Source: "RG",
		Page:   "139",
	},
	"opposing_force_parry": {
		ID:     "017a0f4c-6581-4f59-9c7d-52b11f51d365",
		Name:   "Opposing Force (Parry)",
		Source: "RG",
		Page:   "139",
	},
	"releasing_talons": {
		ID:     "53a18dd7-a2bd-46fd-a27e-eceafe406154",
		Name:   "Releasing Talons",
		Source: "RG",
		Page:   "139",
	},
	"randori_dirty_trick": {
		ID:     "3abe5ad7-c735-4f7b-ae38-f7df1081c248",
		Name:   "Randori (Dirty Trick)",
		Source: "RG",
		Page:   "140",
	},
	"randori_vitals": {
		ID:     "2747d8d5-022d-4477-a7ce-43d88806bb35",
		Name:   "Randori (Vitals)",
		Source: "RG",
		Page:   "140",
	},
	"randori_specific_location": {
		ID:     "5d543914-9c0c-4245-a212-9d5383e7221a",
		Name:   "Randori (Specific Location)",
		Source: "RG",
		Page:   "140",
	},
	"riposte": {
		ID:     "a620e473-4127-4863-b9da-ac8e96c84535",
		Name:   "Riposte",
		Source: "RG",
		Page:   "125",
	},
	"rooted_tree": {
		ID:     "456dfdc7-d1e5-4ec2-86bd-85bf82d81e46",
		Name:   "Rooted Tree",
		Source: "RG",
		Page:   "140",
	},
	"sacrifice_throw": {
		ID:     "845d010e-036b-488c-8ff6-5eec6c2b7c21",
		Name:   "Sacrifice Throw",
		Source: "RG",
		Page:   "125",
	},
	"shadow_block": {
		ID:     "a10cc1a4-c5cb-492d-aa87-448ace3d7f88",
		Name:   "Shadow Block",
		Source: "RG",
		Page:   "125",
	},
	"silken_storm": {
		ID:     "d728ad1e-259a-4af3-ba52-383ffa3e90b4",
		Name:   "Silken Storm",
		Source: "RG",
		Page:   "140",
	},
	"soaring_shackles": {
		ID:     "730318d1-9a03-4925-bd54-27d53dbb1769",
		Name:   "Soaring Shackles",
		Source: "RG",
		Page:   "141",
	},
	"stagger": {
		ID:     "693a1fb7-0c33-4959-87fc-a7f0d3bfd7bc",
		Name:   "Stagger",
		Source: "RG",
		Page:   "141",
	},
	"pouncing_dragon": {
		ID:     "81b9073d-305e-4bcf-90a9-56855f4076f4",
		Name:   "Pouncing Dragon",
		Source: "RG",
		Page:   "122",
	},
	"rolling_clouds": {
		ID:     "5e00496f-5e91-4fb7-96d9-9c176ff8b80f",
		Name:   "Rolling Clouds",
		Source: "RG",
		Page:   "141",
	},
	"sweep": {
		ID:     "5be9b72c-1de5-49ca-9e63-73c9c58c3cac",
		Name:   "Sweep",
		Source: "RG",
		Page:   "141",
	},
	"throw_person": {
		ID:     "9d355a11-5e68-4c03-9676-9a3f555f977f",
		Name:   "Throw Person",
		Source: "RG",
		Page:   "123",
	},
	"thunder_strike": {
		ID:     "335d2151-9137-4071-af91-3e0688ef67d9",
		Name:   "Thunder Strike",
		Source: "RG",
		Page:   "141",
	},
	"ti_khao": {
		ID:     "43351aef-fbed-4a9e-a699-455a495ea2cb",
		Name:   "Ti Khao",
		Source: "RG",
		Page:   "141",
	},
	"tricking": {
		ID:     "8d8e3afb-7538-47e1-91e7-fc1a8d50dbc7",
		Name:   "Tricking",
		Source: "RG",
		Page:   "141",
	},
	"two_headed_snake": {
		ID:     "ea44f12a-0280-4d2b-8f1f-dc5006167872",
		Name:   "Two-Headed Snake",
		Source: "RG",
		Page:   "141",
	},
	"two_weapon_style_attack": {
		ID:     "db67e642-c74e-4780-a44b-b85524251240",
		Name:   "Two-Weapon Style Attack",
		Source: "RG",
		Page:   "141",
	},
	"two_weapon_style_defense": {
		ID:     "8938ff95-3c3a-48f5-8a46-f6962e1b16cf",
		Name:   "Two-Weapon Style Defense",
		Source: "RG",
		Page:   "141",
	},
	"yielding_force_riposte": {
		ID:     "e714b868-49df-465f-8ae0-89b7d150341c",
		Name:   "Yielding Force (Riposte)",
		Source: "RG",
		Page:   "141",
	},
	"yielding_force_counterstrike": {
		ID:     "091f71eb-75d7-4a5c-8d4e-8ec5ff075ff2",
		Name:   "Yielding Force (Counterstrike)",
		Source: "RG",
		Page:   "141",
	},
	"yielding_force_throw": {
		ID:     "0dfdfe1c-a6ce-4233-a36a-d7856d655290",
		Name:   "Yielding Force (Throw)",
		Source: "RG",
		Page:   "141",
	},
	"neijia": {
		ID:     "c512a3e7-5711-438e-b1e7-e02dbf996b85",
		Name:   "Neijia",
		Source: "RG",
		Page:   "140",
	},
	"strike_the_darkness": {
		ID:     "1ff5100c-6b10-453c-a05a-9af9110581e9",
		Name:   "Strike the Darkness",
		Source: "RG",
		Page:   "141",
	},
	"sacrificial_throw": {
		ID:     "1ff5110c-6b10-453c-a05a-faf9410581e0",
		Name:   "Sacrificial Throw",
		Source: "RG",
		Page:   "131",
	},
	"mana_choke": {
		ID:     "4376ad31-af14-4204-86d1-e1a31b9cda6d",
		Name:   "Mana Choke",
		Source: "FA",
		Page:   "102",
	},
	"mana_strike": {
		ID:     "18400527-4b06-47fb-88fc-5d31100ae8d4",
		Name:   "Mana Strike",
		Source: "FA",
		Page:   "102",
	},
}
