package v5

// DataMentors contains mentor spirit records keyed by their ID (lowercase with underscores)
var DataMentors = map[string]Mentor{
	"bear": {
		ID:           "136a3dc5-d9c4-45ad-bc24-705f54692590",
		Name:         "Bear",
		Advantage:    "All: +2 dice for tests to resist damage (not including drain).",
		Disadvantage: "You might go berserk when you take Physical damage in combat or if someone under your care is badly injured. Make a Simple Charisma + Willpower Test (wound modifiers apply). You go berserk for 3 turns minus 1 turn per hit, so 3 or more hits averts the berserk rage entirely. If you're already going berserk, increase the duration. When you're berserk, you go after your attacker(s) without regard for your own safety. If you incapacitate the target(s) before the time is up, the berserk fury dissipates.",
		Source:       "SR5",
		Page:         "321",
		Bonus:        &MentorBonus{DamageResistance: "2"},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Health spells", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Rapid Healing", Bonus: nil}}},
	},
	"cat": {
		ID:           "f32b8b69-0f6b-417d-bd06-6a85e1076a36",
		Name:         "Cat",
		Advantage:    "All: +2 dice to either Gymnastics or Sneaking Tests (choose one).",
		Disadvantage: "Cat magicians toy with their prey. Unless you succeed in a Charisma + Willpower (3) Test at the start of combat, you cannot make an attack that incapacitates your target. If you take any Physical damage, all this playing around stops.",
		Source:       "SR5",
		Page:         "321",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 dice on Gymnastics Tests", Bonus: nil}, MentorChoice{Name: "+2 dice on Sneaking Tests", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice for Illusion spells", Set: "2", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Light Body", Set: "2", Bonus: nil}}},
	},
	"dog": {
		ID:           "98785f59-5739-4998-b334-ec4501c75cf8",
		Name:         "Dog",
		Advantage:    "All: +2 dice for Tracking tests.",
		Disadvantage: "A Dog magician is stubbornly loyal. You can never leave someone behind, betray your comrades, or let another sacrifice themselves in your place without making a successful Charisma + Willpower (3) Test.",
		Source:       "SR5",
		Page:         "321",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Detection spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 free Improved Sense powers", Bonus: nil}}},
	},
	"dragonslayer": {
		ID:           "dc7ce567-18c7-4101-b16c-0d4930f3af81",
		Name:         "Dragonslayer",
		Advantage:    "All: +2 dice pool modifier for one social skill of choice.",
		Disadvantage: "If you break a promise, whether by choice or by accident, you take a \u20131 dice pool modifier to all actions until you make good on your promise.",
		Source:       "SR5",
		Page:         "321",
		Bonus:        &MentorBonus{SelectSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Combat spells", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Enhanced Accuracy and Danger Sense", Bonus: nil}}},
	},
	"eagle": {
		ID:           "9e38a8c0-f11c-461d-a489-ba1432f4551f",
		Name:         "Eagle",
		Advantage:    "All: +2 dice to Perception Tests.",
		Disadvantage: "You get the Allergy (pollutants, mild) quality (p. 322; no bonus Karma for this negative quality).",
		Source:       "SR5",
		Page:         "322",
		Bonus:        &MentorBonus{SpecificSkill: nil, AddQualities: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice summoning spirits of air", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Combat Sense", Bonus: nil}}},
	},
	"fire_bringer": {
		ID:           "bd0d6ff0-8af1-4689-8997-7bcfbbd642ff",
		Name:         "Fire-Bringer",
		Advantage:    "All: +2 dice to Artisan skill tests or Alchemy skill tests (choose one).",
		Disadvantage: "When someone sincerely asks you for help, you can't refuse without succeeding in a Simple Charisma + Willpower (3) Test.",
		Source:       "SR5",
		Page:         "322",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 dice on Artisan Tests", Bonus: nil}, MentorChoice{Name: "+2 dice on Alchemy Tests", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice for Manipulation spells", Set: "2", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Improved Ability on a non-combat skill", Set: "2", Bonus: nil}}},
	},
	"mountain": {
		ID:           "a1faab23-0214-4c83-96ac-d5bb71d4aebb",
		Name:         "Mountain",
		Advantage:    "All: +2 dice to Survival Tests.",
		Disadvantage: "When a Mountain magician makes a plan, she sticks to it. You must make a Charisma + Willpower (3) Test to abandon a planned course of action in favor of a new one. If you fail, you must endeavor to continue with your original plan, even if it means going on alone. Similarly, you must succeed in a Charisma + Willpower (3) Test to proceed in anything without a plan.",
		Source:       "SR5",
		Page:         "322",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Counterspelling and anchored rituals", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Mystic Armor", Bonus: nil}}},
	},
	"rat": {
		ID:           "4a37e26d-e6f1-4e97-b305-e4aed048fcad",
		Name:         "Rat",
		Advantage:    "All: +2 dice for Sneaking Tests.",
		Disadvantage: "A Rat magician must make a Charisma + Willpower (3) Test to not immediately flee or seek cover whenever caught in a combat situation. If there is nowhere to flee, she is forced to fight.",
		Source:       "SR5",
		Page:         "323",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 to Alchemy for harvesting, and you may use any reagents"}, MentorChoice{Name: "Adept: 2 free levels of Natural Immunity", Bonus: nil}}},
	},
	"raven": {
		ID:           "168a0db8-0676-4a7d-86ce-99a43bf0f2bc",
		Name:         "Raven",
		Advantage:    "All: +2 dice for Con tests.",
		Disadvantage: "You must make a Charisma + Willpower (3) Test to avoid exploiting someone else's misfortune to your own advantage or to pull a clever trick or prank even if it's to the disadvantage of your friends.",
		Source:       "SR5",
		Page:         "323",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Manipulation spells", Bonus: nil}, MentorChoice{Name: "Adept: Free Traceless Walk and 1 level of Voice Control", Bonus: nil}}},
	},
	"sea": {
		ID:           "0242ba67-f93b-44e1-a1ad-b0d6f9051525",
		Name:         "Sea",
		Advantage:    "All: +2 dice for Swimming Tests.",
		Disadvantage: "You must make a Charisma + Willpower (3) Test to give away something you own or be charitable in some way.",
		Source:       "SR5",
		Page:         "323",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice summoning spirits of water", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Improved Ability on an athletic skill", Bonus: nil}}},
	},
	"seducer": {
		ID:           "fa343b9a-6e4d-49cd-8c5a-68002ddf244b",
		Name:         "Seducer",
		Advantage:    "All: +2 dice for Con Tests.",
		Disadvantage: "You must succeed in a Charisma + Willpower (3) Test to avoid pursuing a vice or indulgence (drugs, BTLs, sex, and so on) when it is made available.",
		Source:       "SR5",
		Page:         "323",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Illusion spells", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Improved Ability for a skill in the Acting or Influence skill group", Bonus: nil}}},
	},
	"shark": {
		ID:           "db8a0489-fe87-4223-bc02-3639911429a7",
		Name:         "Shark",
		Advantage:    "All: +2 dice to Unarmed Combat tests.",
		Disadvantage: "You might go berserk when you take Physical damage in combat. Every time it happens, make a Simple Charisma + Willpower Test (wound modifiers apply). You go berserk for 3 turns minus 1 turn per hit, so 3 or more hits averts the berserk rage entirely. If you're already going berserk, increase the duration. When you're berserk, you go after your attacker(s) without regard for your own safety. If you run out of targets before the time's up, you keep attacking their bodies.",
		Source:       "SR5",
		Page:         "323",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Combat spells", Bonus: nil}, MentorChoice{Name: "Adept: Free Killing Hands", Bonus: nil}}},
	},
	"snake": {
		ID:           "17ee9f01-ebe2-43ba-a4fe-741053973444",
		Name:         "Snake",
		Advantage:    "All: +2 to Arcana tests.",
		Disadvantage: "You must succeed in a Charisma + Willpower (3) Test to avoid pursuing secrets or knowledge that few people know about when you receive hints of its existence.",
		Source:       "SR5",
		Page:         "324",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Detection spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Kinesics", Bonus: nil}}},
	},
	"thunderbird": {
		ID:           "a805cc41-3dc3-49cc-b290-887a3203158e",
		Name:         "Thunderbird",
		Advantage:    "All: +2 dice for Intimidation Tests.",
		Disadvantage: "A Thunderbird magician must succeed in a Charisma + Willpower (3) Test to avoid responding to an insult in kind.",
		Source:       "SR5",
		Page:         "324",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for summoning spirits of air", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Critical Strike", Bonus: nil}}},
	},
	"wise_warrior": {
		ID:           "5d27ec80-e4c0-4bb7-af9c-d7499cfa6c24",
		Name:         "Wise Warrior",
		Advantage:    "All: +2 to dice to Leadership or Instruction skill tests (choose one).",
		Disadvantage: "If you act dishonorably or without courtesy, whether by choice or by accident, you take a \u20131 dice pool modifier to all actions until you atone for your behavior.",
		Source:       "SR5",
		Page:         "324",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 dice for Leadership skill tests", Bonus: nil}, MentorChoice{Name: "+2 dice for Instruction skill tests", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice for Combat spells", Set: "2", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Improved Ability on a Combat skill", Set: "2", Bonus: nil}}},
	},
	"wolf": {
		ID:           "b5211e08-4be0-4e18-9186-7412f4e9e74f",
		Name:         "Wolf",
		Advantage:    "All: +2 dice to Tracking tests.",
		Disadvantage: "You must succeed in a Charisma + Willpower (3) Test to retreat from a fight.",
		Source:       "SR5",
		Page:         "324",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Combat spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Attribute Boost (Agility)", Bonus: nil}}},
	},
	"berserker": {
		ID:           "796d5046-572e-427e-a49d-3fb66972d07e",
		Name:         "Berserker",
		Advantage:    "All: +2 dice pool modifier for Composure Tests",
		Disadvantage: "Berserker's followers have very short fuses. Whenever someone strongly disagrees with you (gamemaster's discretion), you must pass a Charisma + Willpower (3) Test to keep from striking out against the offender. If the test fails, the attack can be in any form you choose (fist, spell, etc.), but it must have the intent to cause damage.",
		Source:       "SG",
		Page:         "199",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Physical-type Combat Spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Mystic Armor", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Pain Resistance", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Mystic Armor and Pain Resistance", Bonus: nil}}},
	},
	"chaos": {
		ID:           "2c6a5ac3-0d61-46dd-86a3-a630ebc91070",
		Name:         "Chaos",
		Advantage:    "All: +2 dice pool modifier for Con Tests",
		Disadvantage: "You are an inveterate gossip trying to stir up trouble, especially between friends, and thus cannot keep damaging secrets to yourself. Also, anytime you encounter a public situation deemed too quiet or stable (gamemaster's discretion), make a Willpower + Intuition (3) Test. Failure means that you are compelled to stir the pot in any way you desire, be it attacking, telling lies, or throwing a drink on someone nearby.",
		Source:       "SG",
		Page:         "200",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Illusion Spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Improved Potential", Bonus: nil}}},
	},
	"peacemaker": {
		ID:           "68e34866-96d6-420e-a595-10bdbf37f011",
		Name:         "Peacemaker",
		Advantage:    "All: +2 dice pool modifier for Negotiation Tests",
		Disadvantage: "You see even enemies as potential friends and go out of your way to keep from hurting anyone unless the situation truly warrants it. At the very beginning of combat, you must pass a Charisma + Intuition (3) Test; failure means you are unable to take actions that cause Physical damage for the duration of combat. At the beginning of a new Combat Turn, you may choose to retake the test if you failed the first time and you or a member of your team suffered damage in the previous Combat Turn.",
		Source:       "SG",
		Page:         "200",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Detection Spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Enhanced Perception", Bonus: nil}}},
	},
	"oracle": {
		ID:           "f7f30f82-babe-419a-b7df-8dcc98dcada3",
		Name:         "Oracle",
		Advantage:    "All: +2 dice pool modifier for Arcana Tests",
		Disadvantage: "You hate mysteries with a passion and can disappear for days trying to track down the answer. When confronted by a particularly haunting question (gamemaster's discretion), you must take a Willpower + Intuition (3) Test. Failure means you must undertake an Intuition + Logic [Mental] (5, 1 hour) Extended Test to try researching the answer. Completion of the Extended Test does not necessarily mean you found the answer, but it at least silences the question in your mind for the time being. When a follower of Oracle becomes a Grade 1 initiate, she must choose Divination for her first metamagic rather than a Power Point or any other benefit.",
		Source:       "SG",
		Page:         "200",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Detection Spells", Bonus: nil}, MentorChoice{Name: "Adept: Free Astral Perception", Bonus: nil}}},
	},
	"doom": {
		ID:           "97c804c5-4107-495b-a821-29d1fc3aa4f5",
		Name:         "Doom",
		Advantage:    "All: +2 to Demolitions or a single Combat Skill",
		Disadvantage: "Followers of Doom must succeed in a Willpower + Charisma (3) Test to avoid a fight once it has begun, or to not enact a plan to do violence. If they fail, they must engage in combat until all opponents are defeated or flee.",
		Source:       "SG",
		Page:         "86",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 to Demolitions", Bonus: nil}, MentorChoice{Name: "+2 to a Combat Skill", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice for Combat spells", Set: "2", Bonus: nil}, MentorChoice{Name: "Adept: free Killing Hands", Set: "2", Bonus: nil}}},
	},
	"disease": {
		ID:           "dc5c1f63-743f-475d-9a94-02fcbfbb437f",
		Name:         "Disease",
		Advantage:    "All: +2 to resist all pathogens and toxins",
		Disadvantage: "Followers of Disease must make a Charisma + Willpower (3) Test to not flee or seek cover whenever in a combat situation, unless they outnumber their opponents. If they begin a fight with greater numbers but then their side is reduced so that they no longer outnumber their opponents, they must make a test to avoid fleeing.",
		Source:       "SG",
		Page:         "86",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Summoning or Binding plague spirits", Bonus: nil}, MentorChoice{Name: "Adept: Free Plague Cloud", Bonus: nil}}},
	},
	"mutation": {
		ID:           "f58d7493-864f-430d-b75c-a4f78575ed44",
		Name:         "Mutation",
		Advantage:    "All: +2 dice to a Physical skill",
		Disadvantage: "If a follower of Mutation finds themselves inferior to an opponent, they suffer a \u20131 penalty on all actions until they defeat their rival in that area, or overcome or compensate for the weakness in another way (such as acquiring a new power, spell, or augmentation).",
		Source:       "SG",
		Page:         "86",
		Bonus:        &MentorBonus{SelectSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Health Spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Attribute Boost", Bonus: nil}}},
	},
	"pollution": {
		ID:           "424398e1-8909-4237-8315-48b6e06d62b5",
		Name:         "Pollution",
		Advantage:    "All: +2 for Chemistry Tests when dealing with pollutants",
		Disadvantage: "If they are in an area cleaner than their normal habitation, followers of Pollution must make a Willpower + Charisma (3) Test every day. If they fail, they must spend at least eight hours that day actively despoiling the land, regardless of any other plans they had for that time.",
		Source:       "SG",
		Page:         "86",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for summoning or binding toxic spirits", Bonus: nil}, MentorChoice{Name: "Adept: Free Toxic Strike", Bonus: nil}}},
	},
	"great_mother": {
		ID:           "7a837193-2b58-49be-9dbb-c1c0c108ca6e",
		Name:         "Great Mother",
		Advantage:    "All: +2 to First Aid or Medicine Tests",
		Disadvantage: "Followers of the Great Mother are lovers and healers, not fighters. As a result, they suffer a \u20131 dice pool modifier for any combat-related actions (using a combat skill, or casting a spell from the Combat category).",
		Source:       "SASS",
		Page:         "33",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 to First Aid", Bonus: nil}, MentorChoice{Name: "+2 to Medicine", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice for Health spells, preparations and rituals", Set: "2", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Rapid Healing", Set: "2", Bonus: nil}}},
	},
	"the_adversary": {
		ID:           "b58c7771-bc30-48c7-aa3d-694c8bbba00a",
		Name:         "The Adversary",
		Advantage:    "All: +2 dice to demolitions tests.",
		Disadvantage: "Because of their deep-seated hatred for authority, a teammate's use of leadership skill is counterproductive to followers of Adversary, invoking either a negative dice penalty or loss of initiative. If the plan doesn't go the way that the adversary follower wants it to go, it takes a Charisma + Willpower (3) Test for him to get him to cooperate.",
		Source:       "HT",
		Page:         "136",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Counterspelling and disenchanting", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Iron Will", Bonus: nil}}},
	},
	"alligator": {
		ID:           "f841b9f1-bc80-4fd5-a94d-6f76d2c59518",
		Name:         "Alligator",
		Advantage:    "All: +2 dice to intimidation tests.",
		Disadvantage: "A follower of Alligator is stubborn about changing a plan or action to which he is committed. When the rest of the team goes to Plan B, the magician must succeed in a Charisma + Willpower (3) Test for the magician to stop trying Plan A.",
		Source:       "HT",
		Page:         "137",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for conjuring Spirits of Water.", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice for conjuring Spirits of Man.", Bonus: nil}, MentorChoice{Name: "Adept: Free Inertia Strike", Bonus: nil}}},
	},
	"bat": {
		ID:           "640c4d50-f64d-42d3-9529-55d756f0ec4f",
		Name:         "Bat",
		Advantage:    "All: +2 dice to navigation tests.",
		Disadvantage: "A follower of Bat is easily distracted and becomes irritable during enforced inaction. She prefers spontaneity to routine. Every week that the magician stays in the same place, she takes a \u20131 penalty to all actions until she finds a new place to stay. Also, unless she succeeds in a Charisma + Willpower (3) Test, she cannot enter a hangout (bar, club, restaurant) more than once in a week without suffering a \u20131 to all Magic tests for the next twenty-four hours.",
		Source:       "HT",
		Page:         "137",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +1 dice for conjuring spirits.", Bonus: nil}, MentorChoice{Name: "Adept: Free motion sense", Bonus: nil}}},
	},
	"monkey": {
		ID:           "c0f82a89-584c-48b2-b0f1-3acd8b6d6e89",
		Name:         "Monkey",
		Advantage:    "All: +2 dice to gymnastics tests involving climbing.",
		Disadvantage: "Because Monkey is not an assassin, the magician must succeed in a Charisma + Willpower (3) Test in order to strike a surprised opponent. Monkey must be able to watch his prank go off or see the look on the opponent's face after taunting them, otherwise he suffers \u20131 to all Magic tests until the next sunrise/sunset.",
		Source:       "HT",
		Page:         "137",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for spells, preparations, and rituals of the manipulation type.", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Hang Time.", Bonus: nil}}},
	},
	"coyote": {
		ID:           "a9f0231a-2354-44a9-864b-630bf3d58ddb",
		Name:         "Coyote",
		Advantage:    "All: +2 dice pool to all Con tests.",
		Disadvantage: "Coyote has a hard time with head-on attacks or brute force methods, unless it's part of a larger con or misdirection. Anytime he is forced into such actions, he must make a Willpower + Charisma [Mental] (4) Test. If he fails, then he decides to do things another way, which means he may exit a combat instead of participating in it.",
		Source:       "SFCC",
		Page:         "24",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +1 to all Manipulation and Illusion spell tests, preparations, and rituals.", Bonus: nil}, MentorChoice{Name: "Adept: Danger Sense level 2.", Bonus: nil}}},
	},
	"oak_shb": {
		ID:           "9f020eb4-975f-4449-9ba1-c1242159d774",
		Name:         "Oak (SHB)",
		Advantage:    "All: +2 dice to memory test.",
		Disadvantage: "A follower of Oak has to succeed in a CHA+WIL (3) test to retreat from a dangerous area instead of waiting till the danger passes.",
		Source:       "SHB2",
		Page:         "179",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Detection spells.", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Mystic Armor.", Bonus: nil}}},
	},
	"artist": {
		ID:           "f8f32157-2dbf-42b3-9ea6-2e60640875c7",
		Name:         "Artist",
		Advantage:    "All: +2 dice to Artisan or Forgery.",
		Disadvantage: "If for more than two weeks the Artist fails to find an audience for a presentation of her ability, she has to make a WIL+ CHA (3) test. Should she fail, she fall into depression (-2 dice for every skill linked to LOG, INT or CHA) for 1d6 days. After that (or if she succeeded in the the WIL+CHA test) a new 14 day period begins in which she has to show off her skills.",
		Source:       "SHB2",
		Page:         "179",
		Bonus:        &MentorBonus{SelectSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Illusion spells.", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Improved Potential.", Bonus: nil}}},
	},
	"blacksmith": {
		ID:           "66f968d6-96da-404e-b1ef-a4d7377ac3cf",
		Name:         "Blacksmith",
		Advantage:    "All: +2 dice to Artisan or Alchemy tests.",
		Disadvantage: "You have to pass a CHA + WIL (3) check to refrain from instantaneously avenging an insult.",
		Source:       "SHB2",
		Page:         "179",
		Bonus:        &MentorBonus{SelectSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for summoning spirits of fire.", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Enhanced Accuracy (skill)", Bonus: nil}}},
	},
	"gambler": {
		ID:           "f152ddfc-13b2-46fa-b8d0-77e2a518acf5",
		Name:         "Gambler",
		Advantage:    "All: +2 to Etiquette or Palming.",
		Disadvantage: "Gain the Distinctive Style negative quality.",
		Source:       "SHB2",
		Page:         "179",
		Bonus:        &MentorBonus{SelectSkill: nil, AddQualities: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Manipulation Spells.", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Danger Sense.", Bonus: nil}}},
	},
	"boar": {
		ID:           "16bd99dd-49df-41aa-a8a2-9b8962fac44c",
		Name:         "Boar",
		Advantage:    "All: Home Ground Quality is gained for free.",
		Disadvantage: "A follower of Boar does not like it if there are others intruding in his space or disrupting his routine. At best, the follower protects the bar and employees of the bar he always goes to. At worst, he will start a fight for a specific table or stool that he thinks is his. A warning is optional and usually proffered by the follower's friends. It takes a Charisma + Willpower (3) Test for a follower of Boar to leave his home, safehouse, or routine permanently, otherwise he will keep coming back, even at the risk of his own safety. If the Boar does leave, he receives a \u20131 penalty to all active skill tests for three weeks until he finally settles into a new place and routine.",
		Source:       "HS",
		Page:         "41",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +1 to the number of services gained when successfully summoning a spirit"}, MentorChoice{Name: "Adept: Gains Rooting (2) power for free.", Bonus: nil}}},
	},
	"giraffe": {
		ID:           "19154c75-9fa9-4e7e-aeee-da1faaaca3e2",
		Name:         "Giraffe",
		Advantage:    "All: +2 Assensing skill tests or +2 to Judge Intentions test (choose one)",
		Disadvantage: "A follower of Giraffe stumbles through social etiquette, as she believes the small talk and chitchat that are the core of social chatter are fundamentally dishonest and not worthy of her efforts. She can make a wide range of situations awkward and receives \u20132 dice for Etiquette skill tests.",
		Source:       "HS",
		Page:         "42",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 dice on Assensing Tests", Bonus: nil}, MentorChoice{Name: "+2 on Judge Intentions Tests", Bonus: nil}, MentorChoice{Name: "Magician: +2 to Conjuring skill tests of air spirits", Set: "2"}, MentorChoice{Name: "Adept: 2 free levels of Piercing Senses", Set: "2", Bonus: nil}}},
	},
	"dolphin": {
		ID:           "e8e25c51-bca0-4647-b345-f7f1d7a06be3",
		Name:         "Dolphin",
		Advantage:    "All: +2 dice on Artisan skill tests or Pilot Watercraft skill tests (choose one)",
		Disadvantage: "Followers are altruistic when it comes to helping people and cannot turn a blind eye to those who they believe deserve their help. It is difficult for them not to get involved when they see someone being bullied or obviously polluting the environment. If they see such a situation, it takes a Charisma + Willpower (3) Test for a follower of Dolphin not to intervene. If the job that the follower of Dolphin is on involves polluting the environment or becoming the bully/enforcer on those less deserving, then the follower loses 2 dice after each such deed until she atones. Atonement is up to the gamemaster but can involve time and money spent with charities.",
		Source:       "HS",
		Page:         "43",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 dice on Artisan tests", Bonus: nil}, MentorChoice{Name: "+2 on Pilot Watercraft Tests", Bonus: nil}, MentorChoice{Name: "Magician: +2 for health spells, preparations, and spell rituals.", Set: "2", Bonus: nil}, MentorChoice{Name: "Adept: Gain Flexibility (2) power for free", Set: "2", Bonus: nil}}},
	},
	"whale": {
		ID:           "cf290b67-e417-4cd6-a36e-d28f35bdc18d",
		Name:         "Whale",
		Advantage:    "All: +2 dice to Swimming or Pilot Watercraft skill tests (choose one)",
		Disadvantage: "Because of their personal sense of ethics, followers of the whale must honor any agreement they enter into. This can be an oath to an organization or a verbal contract with a corporation. Failing to honor the contract or oath results in a loss of a point of Magic. The Whale mentor spirit understands if circumstances to complete the contract are out of the Awakened's hands. For everything else, the follower can attempt to atone, but at the gamemaster's discretion.",
		Source:       "HS",
		Page:         "43",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 dice on Swimming tests", Bonus: nil}, MentorChoice{Name: "+2 on Pilot Watercraft Tests", Bonus: nil}, MentorChoice{Name: "Magician: +2 to Conjuring skill tests for spirits of water", Set: "2"}, MentorChoice{Name: "Adept: Receive 2 ranks in Iron Lungs or free.", Set: "2", Bonus: nil}}},
	},
	"horse": {
		ID:           "9ca5be05-1420-4592-81a5-1b59bb93545d",
		Name:         "Horse",
		Advantage:    "All: +2 dice to Running or Pilot Ground Craft tests (choose one)",
		Disadvantage: "Followers of the Horse can't sit still for long nor be confined indoors. They must spend at least four hours a day outside and be able to run or drive around (any method of travel faster than walking). If followers are not able to meet this condition, they suffer \u20131 die to all action skill tests. This penalty is cumulative, meaning if the follower is stuck at a desk all day (indoors and not moving around) for two days in a a row, they suffer \u20132 to all actions until they get that free time in.",
		Source:       "HS",
		Page:         "46",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 dice on Running tests", Bonus: nil}, MentorChoice{Name: "+2 on Pilot Ground Craft Tests", Bonus: nil}, MentorChoice{Name: "Magician: Reduce Drain Value from Reckless Summoning by 1", Set: "2"}, MentorChoice{Name: "Adept: May learn to use the Movement critter power as a metamagic (self only, 3 times a day)", Set: "2"}}},
	},
	"raccoon": {
		ID:           "dd6aa95d-5112-493e-9ba1-557dc43b6708",
		Name:         "Raccoon",
		Advantage:    "All: +2 to Palming skill tests",
		Disadvantage: "The Raccoon is commonly one of the Thief totems, so the followers can tend to err on the side of greed. A follower of Raccoon must make a Charisma + Willpower (3) Test to resist the urge to open that next locked door to look for something to steal, or to follow that Matrix rabbit trail in the quest for more paydata.",
		Source:       "HS",
		Page:         "46",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for spells, preparations, and spell rituals in the Manipulation category.", Bonus: nil}, MentorChoice{Name: "Adept: 2 Improved Sense powers", Bonus: nil}}},
	},
	"spider": {
		ID:           "924e0d72-a83a-44c2-90ba-24455c389207",
		Name:         "Spider",
		Advantage:    "All: +2 dice to Computer skill tests",
		Disadvantage: "Followers of Spider are already paranoid about people having any misconceptions about them being insect shamans. They will keep such details from casual conversation. Followers of Spider also have taken advantage of the Matrix more than more traditional shamans in creating connections. This makes followers more agoraphobic as they avoid uncontrolled social situations and unfamiliar environments. They receive a \u20131 dice pool modifier to Magic tests while out in the open (this includes very large indoor rooms such as auditoriums, theaters, and stadiums). The penalty doubles if there is a large crowd of people to deal with.",
		Source:       "HS",
		Page:         "47",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Illusion spells", Bonus: nil}, MentorChoice{Name: "Adept: Hang time (2)", Bonus: nil}}},
	},
	"goddess": {
		ID:           "a83f0580-9783-401b-8249-bb39843fe0c7",
		Name:         "Goddess",
		Advantage:    "All: +2 dice pool modifier for Instruction Tests.",
		Disadvantage: "The Goddess refuses to take a backseat to any male counterparts. Unless you succeed in a Charisma + Willpower Test (3), you will not take orders from a male, or if a male disrespects you, you must respond with equal measure",
		Source:       "BOTL",
		Page:         "129",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Ritual Spellcasting Tests", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Authoritative Tone", Bonus: nil}}},
	},
	"lion": {
		ID:           "c9b8f607-43f7-4707-aaac-60da183f22ac",
		Name:         "Lion",
		Advantage:    "All: +2 dice pool modifier for Survival Tests, Running Tests, or Tracking Tests (Choose One)",
		Disadvantage: "In combat situations, a Lion will never leave a comrade behind, and will fight to the death to protect an ally. Unless you succeed in a Charisma + Willpower Test (3), you cannot flee combat before your team members are safe. Further, whenever taking actions that don't benefit the team somehow, your physical and mental limits are reduced by 2.",
		Source:       "BOTL",
		Page:         "132",
		Bonus:        &MentorBonus{SelectSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice to Combat spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Attribute Boost (Strength)", Bonus: nil}}},
	},
	"raven_alt": {
		ID:           "d1089dd2-68b8-4e2a-977e-718e720f44d3",
		Name:         "Raven (Alt)",
		Advantage:    "All: +2 dice pool modifier for knowledge skill tests.",
		Disadvantage: "Followers of Raven share their mentor's love of collecting. When presented with data, knowledge, or other gear that would be valuable (gamemaster's discretion), you must pass a Charisma + Willpower Test (3), or be unable to resist trying to acquiring it.",
		Source:       "BOTL",
		Page:         "121",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice to Detection spells, preparations, and rituals.", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice to summoning spirits if summoner also has Code of Honor: Harmony with Nature, The Shaman's Code and bargains with the summoned spirit.", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Enhanced Perception.", Bonus: nil}}},
	},
	"dove": {
		ID:           "bd56ecdf-ebba-4b66-8e39-445831744496",
		Name:         "Dove",
		Advantage:    "All: +2 dice pool modifier for Negotiation tests.",
		Disadvantage: "Dove discourages combat whenever possible. As such, those who follow Dove are at \u20132 dice pool modifier to cast Combat spells or when using lethal force.",
		Source:       "FA",
		Page:         "94",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +1 dice pool modifier for casting Health spells, +1 dice pool modifier to summon air spirits", Bonus: nil}, MentorChoice{Name: "Adept: Gain 1 free level of Enhanced Perception.", Bonus: nil}}},
	},
	"planar_entity": {
		ID:           "0fc002e4-c130-4ca8-8719-487941e86863",
		Name:         "Planar Entity",
		Advantage:    "All: Determined by spirit type and gamemaster approval.",
		Disadvantage: "Taking on an extraplanar entity into one's soul is not without its drawbacks. Much of their mental ability is taken up keeping themselves from losing their identity as a result of their shared existence. Mages suffer a \u20132 dice pool penalty when making tests involving Willpower",
		Source:       "FA",
		Page:         "95",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: Determined by spirit type and gamemaster approval."}, MentorChoice{Name: "Adept: Determined by spirit type and gamemaster approval."}}},
	},
	"arcana": {
		ID:           "19d69029-259a-4ed6-b66b-944b4ddbc172",
		Name:         "Arcana",
		Advantage:    "All: Once per day, when making a decision or test influenced by a Tarot reading/card, may re-roll misses as if they had used Edge.",
		Disadvantage: "Followers of the Arcana must use Tarot decks or individual cards as foci and fetishes, or else take \u20132 when attempting to use them. The Tarot Arcana plays such a major part in the lives of its adherents that when a follower of Arcana becomes a grade 1 initiate, they must choose centering or adept centering for their first benefit, with the cards of Tarot being the focus of their centering.",
		Source:       "FA",
		Page:         "95",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +1 dice pool modifier for casting Detection spells, an additional +2 dice pool modifier to cast Clairvoyance spells.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 free levels of Danger Sense", Bonus: nil}}},
	},
	"holy_text": {
		ID:           "2dcbe44e-3789-4cf2-b51b-0337c239ce7c",
		Name:         "Holy Text",
		Advantage:    "Gain +4 ranks of (Choose Holy Text) Knowledge Skill.",
		Disadvantage: "When a follower of a Holy Text wishes to take an action that is contrary to the teaching of the text (whatever that text is), they must pass a Charisma + Willpower (4) Test to take the action.",
		Source:       "FA",
		Page:         "95",
		Bonus:        &MentorBonus{SelectSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when using the Banishing skill.", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice pool modifier when casting Health spells.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 1 free level of Mystic Armor or Empathic Healing (choose one).", Bonus: nil}}},
	},
	"death": {
		ID:           "833ce699-081b-454d-ac93-5c2bd2c61862",
		Name:         "Death",
		Advantage:    "All: +4 ranks of the Knowledge Skill Anatomy, Disease, Infected, or Undead (choose one).",
		Disadvantage: "In order for a follower of Death to attempt to help someone who is dying or injured, they must first pass a Charisma + Willpower (3) Test.",
		Source:       "FA",
		Page:         "96",
		Bonus:        &MentorBonus{SelectSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting the spells Death Touch, Manaball, Manabolt, One Less, Slaughter, Slay.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 1 free level of Killing Hands", Bonus: nil}, MentorChoice{Name: "Adept: Gain 1 free level of Plague Cloud", Bonus: nil}}},
	},
	"war": {
		ID:           "c3f3cf4d-3e99-4395-9d24-0b4492ecf45c",
		Name:         "War",
		Advantage:    "All: After character creation, may purchase combat skills at rank 3 or higher for 1 less Karma",
		Disadvantage: "If it looks as if they are going to lose a battle, those with the War mentor must pass a Charisma + Willpower (4) Test, or else use all means necessary\u2014including the lives, nuyen, and honor of their teammates\u2014to overcome their adversary.",
		Source:       "FA",
		Page:         "97",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting Combat spells, preparations, and rituals.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 1 free level of Critical Strike.", Bonus: nil}}},
	},
	"tohu_wa_bohu": {
		ID:           "12a4d51d-1d4c-405f-b62e-1ba5ad0aaf01",
		Name:         "Tohu Wa-Bohu",
		Advantage:    "All: +2 dice pool modifier for Intimidation or Demolitions tests (choose one)",
		Disadvantage: "Followers gain the Driven quality, in which the focus is the opportunity to destroy something meaningful. Further, they fnd it hard to work in groups given their destructive nature. They can never benefit from teamwork or leadership bonuses.",
		Source:       "FA",
		Page:         "97",
		Bonus:        &MentorBonus{SelectSkill: nil, AddQualities: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: Gain the Witness My Hate quality for free.", Bonus: nil}, MentorChoice{Name: "Adept: Gain the Adept Accident power for free.", Bonus: nil}}},
	},
	"green_man": {
		ID:           "0855eb9d-65b2-4168-ae58-6b07c38b86c3",
		Name:         "Green Man",
		Advantage:    "All: +2 dice pool modifier for Negotiation Tests.",
		Disadvantage: "When significant damage is being done to vegetation, they must pass a Charisma + Willpower (3) Test or use all means possible to stop the destruction.",
		Source:       "FA",
		Page:         "98",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier to summon Plant Spirits.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 free levels of Rooting.", Bonus: nil}}},
	},
	"sun": {
		ID:           "79346916-7987-4332-b031-4b8bd59700d7",
		Name:         "Sun",
		Advantage:    "All: +2 dice pool modifier for Perception tests when outside during the day.",
		Disadvantage: "Followers of Sun must pass a Charisma + Willpower (4) Test in order to purposefully deceive others.",
		Source:       "FA",
		Page:         "98",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting Sun- or Fire-based spells.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 3 free levels of Temperature Tolerance", Bonus: nil}}},
	},
	"dark_king": {
		ID:           "31a16d45-74a1-451e-998c-d9ed9c369f1e",
		Name:         "Dark King",
		Advantage:    "All: +2 dice to Intimidation tests.",
		Disadvantage: "Followers receive a \u20131 dice pool penalty when resisting physical damage.",
		Source:       "FA",
		Page:         "98",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice to Contractual Rituals.", Bonus: nil}, MentorChoice{Name: "Adept: Gain Spirit Ram for free.", Bonus: nil}}},
	},
	"moon": {
		ID:           "a40f9df8-9303-4f3b-9088-b9bd60c43f72",
		Name:         "Moon",
		Advantage:    "All: +2 dice to Negotiation tests.",
		Disadvantage: "Followers of Moon must make a Charisma + Willpower (4) Test in order to engage in direct confrontation; failure means they cannot make any action considered as such. Negotiation is not considered confrontation (Moon loves discussion), but arguments fall into that category.",
		Source:       "FA",
		Page:         "98",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Illusion and transformation-focused Manipulation spells, preparations, and spell rituals.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 3 levels of Stillness for free.", Bonus: nil}}},
	},
	"oak": {
		ID:           "b1a5d0cd-b4f1-4de2-86ee-3965f1c36034",
		Name:         "Oak",
		Advantage:    "All: +1 to Damage Resistance tests.",
		Disadvantage: "Must have a natural (meaning un-augmented) Body and Strength of 4 or greater to select this mentor spirit.",
		Source:       "FA",
		Page:         "99",
		Bonus:        &MentorBonus{DamageResistance: "1"},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool bonus when summoning plant spirits.", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice pool bonus when summoning air spirits.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 levels of Stillness for free", Bonus: nil}}},
	},
	"stag": {
		ID:           "6ff55926-3ea8-4e8c-8cd2-a114595d159b",
		Name:         "Stag",
		Advantage:    "All: +2 to Blades tests.",
		Disadvantage: "Followers of the Stag demand respect, especially to those they give it to. Once disrespected, they must succeed in a Charisma + Willpower (3) Test, or they will demand satisfaction against the slight.",
		Source:       "FA",
		Page:         "99",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 to summoning earth spirits.", Bonus: nil}, MentorChoice{Name: "Adept: Gain +2 levels of Light Body for free.", Bonus: nil}}},
	},
	"great_mother_alt": {
		ID:           "4d15a346-8f27-42c5-be8c-33a7bd56067d",
		Name:         "Great Mother (alt)",
		Advantage:    "All: When not in an urban area, gain +1 to any skill test with skills in the Outdoors skill group.",
		Disadvantage: "Treat any background count due to pollution or twisted element as twice the actual rating.",
		Source:       "FA",
		Page:         "99",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 for health spells, preparations, and spell rituals.", Bonus: nil}, MentorChoice{Name: "Adept: Gain Empathic Healing for free.", Bonus: nil}}},
	},
	"spider_alt": {
		ID:           "26eed20e-86c6-4245-be55-231370fff939",
		Name:         "Spider (Alt)",
		Advantage:    "All: +2 dice pool modifier for tests using the Stealth skill group.",
		Disadvantage: "When not following a plan or a plan doesn't go according to plan, followers of Spider must pass a Charisma + Willpower (4) Test or suffer \u20132 to all rolls until a new plan is established.",
		Source:       "FA",
		Page:         "100",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting Manipulation spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 free levels of Spirit Claw (although in this case, it manifests as a fang).", Bonus: nil}}},
	},
	"wolf_alt": {
		ID:           "a7532966-cdeb-4732-b486-59cbf5552f83",
		Name:         "Wolf (Alt)",
		Advantage:    "All: +1 dice pool modifier for tests using the Sneaking, Perception, Survival, and Tracking skills.",
		Disadvantage: "Whenever a follower of Wolf sees an opportunity to survive by attacking or sacrificing the weak, they must pass a Charisma + Willpower (4) Test or attempt to seize the opportunity. This does not apply to those the Wolf considers friends or family.",
		Source:       "FA",
		Page:         "100",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +1 dice pool modifier when casting Combat spells, preparations, and rituals.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 free levels of Danger Sense.", Bonus: nil}}},
	},
	"rat_alt": {
		ID:           "e27fd190-c19f-4d86-8e99-7552df1e8be3",
		Name:         "Rat (Alt)",
		Advantage:    "All: +1 dice pool modifier for tests using the Perception and Sneaking skills.",
		Disadvantage: "Followers of Rat cannot receive aid or aid others with a Teamwork test unless they trust the individuals they are teaming with. Further, if they do trust the individuals, but that trust is broken through incompetence or betrayal, they must pass a Charisma + Willpower (4) Test to be able to use teamwork with that individual each time in the future.",
		Source:       "FA",
		Page:         "100",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +1 dice pool modifier when casting Health spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain 1 free level of Analytics.", Bonus: nil}}},
	},
	"eurasian_jay": {
		ID:           "3244e940-4666-4510-b1a1-c34df97797fe",
		Name:         "Eurasian Jay",
		Advantage:    "All: +1 dice pool modifier for tests using the Perception and Palming skills.",
		Disadvantage: "Eurasian Jay loves to split his possessions. If a follower of Eurasian Jay receives a splittable reward, she must make a Charisma + Willpower (3) test to not spread the reward over different accounts or rooms.",
		Source:       "SAG",
		Page:         "120",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting Illusion spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice pool modifier when casting Manipulation spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain 1 free level of Voice Control.", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 free levels of Danger Sense.", Bonus: nil}}},
	},
	"squirrel": {
		ID:           "bcf60ea4-577a-4487-9996-6c40a86294c5",
		Name:         "Squirrel",
		Advantage:    "All: +2 dice pool modifier for tests using the Gymnastics skill.",
		Disadvantage: "When followers of Squirrel are in confined spaces, they must make a Willpower + Charisma (3) Tests or take a -1 dice pool modifier on all tests while feeling cramped.",
		Source:       "SAG",
		Page:         "121",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting Detection spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 free levels of Light Body.", Bonus: nil}}},
	},
	"fox": {
		ID:           "50b20b8c-8cf4-4b92-95ea-b0c8bbf560b0",
		Name:         "Fox",
		Advantage:    "All: +2 dice pool modifier for tests using the Perception skill.",
		Disadvantage: "If Fox fights, it'll fight to kill. A follower of this mentor spirit must make a Willpower + Intuition (3) Test to spare an overpowered foe.",
		Source:       "SAG",
		Page:         "121",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting Illusion spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 free levels of Combat Sense.", Bonus: nil}}},
	},
	"tide": {
		ID:           "b83bab65-bbda-4367-aa50-3069def5b2e4",
		Name:         "Tide",
		Advantage:    "All: +2 dice pool modifier for tests using the Ritual Spellcasting skill.",
		Disadvantage: "Followers of Tide live in transition, but in the consistency of a cycle. They also design their lives this way. If their normal life cycle is lastingly impaired by Sleep deprivation or illness, they suffer a -1 dice pool modifier on all tests until the cycle is restored.",
		Source:       "SAG",
		Page:         "121",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice summoning spirits of water or earth (The type of spirit for which this bonus applies changes every 6 hours).", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 free levels of Heightened Concentration.", Bonus: nil}}},
	},
	"heinzelmännchen": {
		ID:           "62188234-323a-4c8e-96c4-b8b8a750e272",
		Name:         "Heinzelm\u00e4nnchen",
		Advantage:    "All: +2 dice pool modifier for tests using the Artisan skill and the Engineering skill group.",
		Disadvantage: "Heinzelm\u00e4nnchen works in secret. If a follower of Heinzelm\u00e4nnchen wants to perform magic in public or under close observation, they'll have to make a Willpower + Charisma (3) Test or else their magic cease to function for the moment.",
		Source:       "SAG",
		Page:         "121",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting Manipulation spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain 1 free level of Improved Ability (Artisan or a skill from the Engineering group).", Bonus: nil}}},
	},
	"groundhog": {
		ID:           "128ba60a-7825-4d29-8b94-8dd291fdc468",
		Name:         "Groundhog",
		Advantage:    "All: +1 dice pool modifier for tests using the Perception and Etiquette skills.",
		Disadvantage: "If a follower of Groundhog get into a fight (intentionally or unintentionally), they'll have to make a Willpower + Charisma (3) Test to not flee immediately.",
		Source:       "SAG",
		Page:         "122",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting Detection spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain 2 free levels of Attribute Boost (Reaction).", Bonus: nil}, MentorChoice{Name: "Adept: Gain the Motion Sense power for free.", Bonus: nil}}},
	},
	"seal": {
		ID:           "ad1bc54f-1f59-4972-8791-a1c36860f196",
		Name:         "Seal",
		Advantage:    "All: +2 dice pool modifier for Judge Intentions tests.",
		Disadvantage: "Seal has compassion, but she is lacking in tact dealing with the feelings of others. Whenever a follower of Seal gains insight into the emotional world of an other, it's difficult for him to respect private boundaries and not address the subject. In order to remain discreet in such situations, they must make a Charisma + Willpower (3) test. Glitches in social test are automatically critical.",
		Source:       "SAG",
		Page:         "122",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice summoning spirits of water.", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice pool modifier when casting Illusion spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain the Astral Perception Power for free.", Bonus: nil}}},
	},
	"pig": {
		ID:           "255affd2-1a85-422e-bb64-3dd7ab2faa77",
		Name:         "Pig",
		Advantage:    "All: +2 dice pool modifier for tests using the Con skill.",
		Disadvantage: "A follower of Pig must make a Willpower + Charisma (3) Test to break free from pleasurable activities like sleeping, eating, drinking or consuming drugs.",
		Source:       "SAG",
		Page:         "122",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice pool modifier when casting Manipulation spells, preparations, and rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain 1 free level of Improved Ability for a skill from the Influence or Acting group.", Bonus: nil}}},
	},
	"capricorn": {
		ID:           "7c904908-81e5-448b-a60e-9b7b3af53842",
		Name:         "Capricorn",
		Advantage:    "All: +2 dice pool modifier for tests using the Gymnastics skill.",
		Disadvantage: "Capricorn may not be stubborn, but he decides and acts quickly. He has neither tolerance nor time for hesitation. If a follower of Capricorn is confronted with long decision-making processes, discussions, or indecision, he must make a Charisma + Willpower (3) test in order not to immediately choose the in his opinion best decision available and to put it into practice immediately.",
		Source:       "SAG",
		Page:         "123",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice summoning spirits of earth.", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Hang Time.", Bonus: nil}}},
	},
	"wild_hunt": {
		ID:           "88b517e3-a3c8-4028-9a69-d947f3384aab",
		Name:         "Wild Hunt",
		Advantage:    "All: +2 dice pool modifier for tests using the Pilot Ground Craft or Intimidation skill.",
		Disadvantage: "A follower of the Wild Hunt always leaves behind a swath of devastation. If objects or uninvolved persons could be harmed in the fight, he wouldn't take any consideration. If a follower of the Wild Hunt is consciously considerate in the fight, he must succeed in a Charisma + Willpower (3) test, otherwise he is so inhibited that he suffers a -2 dicepool modifier on all actions.",
		Source:       "SAG",
		Page:         "123",
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "+2 dice on Pilot Ground Craft Tests", Bonus: nil}, MentorChoice{Name: "+2 dice on Intimidation Tests", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice summoning spirits of man.", Set: "2", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice summoning guardian spirits.", Set: "2", Bonus: nil}, MentorChoice{Name: "Adept: Gain the Berserk power for free.", Set: "2", Bonus: nil}}},
	},
	"guanyin": {
		ID:           "7397da6e-29b8-400f-9708-c99bd04d5c07",
		Name:         "Guanyin",
		Advantage:    "All: +2 dice for First Aid tests.",
		Disadvantage: "A Guanyin magician is highly motivated to save other beings. If the Magician is offered a run that doesn't involve hooding, she must make a Charisma + Willpower (3) test before she can accept the run. Failure on this test means she turns down the job.",
		Source:       "BTB",
		Page:         "139",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Health spells", Bonus: nil}, MentorChoice{Name: "Adept: Free Empathic Healing power", Bonus: nil}}},
	},
	"architect": {
		ID:           "5593f724-7b72-4927-a8c8-2c73844cc1b1",
		Name:         "Architect",
		Advantage:    "All: +2 dice to Leadership",
		Disadvantage: "Followers of this spirit like to stay in charge. Should the circumstances of a run force them to go on the defensive, make a WIL + INT (3) test. Failure imposes a -2 penalty to all tests until the follower regains control of the situation.",
		Source:       "SOTG",
		Page:         "29",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Combat spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 free levels of Analytics", Bonus: nil}}},
	},
	"german_shepherd": {
		ID:           "db42c229-3403-4947-8626-3f70f87c8a3c",
		Name:         "German Shepherd",
		Advantage:    "All: +1 to dice to Leadership and Perception",
		Disadvantage: "Sometimes, German shepherd followers show impatience. Should their patience be tested (GM discretion), they must succeed at a WIL + CHA (3) test not to react harshly.",
		Source:       "SOTG",
		Page:         "29",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +1 die for Combat and Detection spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 levels of Danger Sense", Bonus: nil}}},
	},
	"doberman": {
		ID:           "bdb4fa0b-3c9d-4164-b2d6-76b7c04c43d8",
		Name:         "Doberman",
		Advantage:    "All: +1 die to Perception and one combat skill (choose one)",
		Disadvantage: "Doberman is very self-confident. In order to accept a subordinate role to someone or follow a stranger's plans, they have to succeed on a WIL + CHA (3) test.",
		Source:       "SOTG",
		Page:         "29",
		Bonus:        &MentorBonus{SelectSkill: nil, SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Combat spells", Set: "2", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Combat Sense", Set: "2", Bonus: nil}}},
	},
	"weimaraner": {
		ID:           "240ab0aa-6be1-452b-88c2-f10f6f6eabfb",
		Name:         "Weimaraner",
		Advantage:    "All: +1 die to Running and Tracking",
		Disadvantage: "Should a follower find themselves unable to use their skills for longer than 12 hours, they must succeed  a WIL + CHA (3) test, otherwise they suffer a -1 penalty to all actions until they can use their abilities again.",
		Source:       "SOTG",
		Page:         "31",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Detection spells", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Enhanced Perception", Bonus: nil}}},
	},
	"badger": {
		ID:           "5c465bf3-665f-41f2-865e-41abb879ee1f",
		Name:         "Badger",
		Advantage:    "All: 2 levels of Perceptive quality are gained for free",
		Disadvantage: "Badger relentlessly guards his territory. Should enemies invade an area guarded by a follower, for instance a building, or steal an object under their protection, must succeed at a WIL + CHA (3) test to not immediately go after the culprits.",
		Source:       "SOTG",
		Page:         "31",
		Bonus:        &MentorBonus{AddQualities: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +1 die for Counterspelling and Combat Spells", Bonus: nil}, MentorChoice{Name: "Adept: 2 levels of Danger Sense", Bonus: nil}}},
	},
	"mystic_guardian": {
		ID:           "b01976a5-2343-4308-846e-da5fb12328a8",
		Name:         "Mystic Guardian",
		Advantage:    "All: +2 dice to one melee combat skill (choose one)",
		Disadvantage: "What does a mystic guardian do when there is nothing to guard? As long as the follower does not have a specific task, an employer or a ward (or does not carry out their self-imposed duties), they suffer a -2 penalty on every test.",
		Source:       "SOTG",
		Page:         "31",
		Bonus:        &MentorBonus{SelectSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for summoning guardian spirits.", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice for summoning beast spirits.", Bonus: nil}, MentorChoice{Name: "Adept: Magic Sense", Bonus: nil}}},
	},
	"little_red_riding_hood": {
		ID:           "296dc353-df11-4c94-a101-04bc501edf5e",
		Name:         "Little Red Riding Hood",
		Advantage:    "All: +2 to dice to Con",
		Disadvantage: "In their unbridled curiosity, followers of Little Red Riding Hood sometimes overlook the important and obvious things. They receive a -1 penalty to Perception tests in unknown areas.",
		Source:       "SOTG",
		Page:         "32",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice to Contractual Rituals", Bonus: nil}, MentorChoice{Name: "Adept: Gain Linguist for free", Bonus: nil}}},
	},
	"treasure_hunter": {
		ID:           "bea9796a-c5d3-4388-97ec-14969db470fe",
		Name:         "Treasure Hunter",
		Advantage:    "All: +1 die to Navigation and Locksmith",
		Disadvantage: "A follower of this spirit devotes their full attention to the desired object, as a result, slacking or tackling tasks not directly related to obtaining it in a halfhearted fashion. After the meet with the J, they must succeed at a WIL + WIL (3) test or incur a -1 penalty to all tests which don't directly involve the object of their desire.",
		Source:       "SOTG",
		Page:         "32",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for Detection spells", Bonus: nil}, MentorChoice{Name: "Adept: Gain Three-Dimensional Memory for free", Bonus: nil}}},
	},
	"brother_at_arms": {
		ID:           "f2cc5e2b-6538-4271-9f7f-5434076f9a6b",
		Name:         "Brother at Arms",
		Advantage:    "All: +1 die to Etiquette and Instruction",
		Disadvantage: "Every run, followers choose three persons - PCs or key NPCs - of direct relevance to the plot to whom they pledge their loyalty for the duration of the mission. Taking advantage of, lying to or abandoning any of them requires succeeding at a WIL + INT (3) test. Even if they can bring themselves to do so, they suffer a -2 penalty to all tests until they atone.",
		Source:       "SOTG",
		Page:         "32",
		Bonus:        &MentorBonus{SpecificSkill: nil},
		Choices:      &MentorChoices{Choice: []interface{}{MentorChoice{Name: "Magician: +2 dice for summoning guardian spirits.", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice for summoning task spirits.", Bonus: nil}, MentorChoice{Name: "Magician: +2 dice for summoning spirits of man.", Bonus: nil}, MentorChoice{Name: "Adept: 1 free level of Mystic Armor", Bonus: nil}}},
	},
}
