package v5

// dataMetatypes contains all metatype definitions
var dataMetatypes = map[string]Metatype{
	"human": {
		Name:      "Human",
		Category:  MetatypeCategoryStandard,
		Body:      AttributeRange{Min: 1, Max: 6},
		Agility:   AttributeRange{Min: 1, Max: 6},
		Reaction:  AttributeRange{Min: 1, Max: 6},
		Strength:  AttributeRange{Min: 1, Max: 6},
		Willpower: AttributeRange{Min: 1, Max: 6},
		Logic:     AttributeRange{Min: 1, Max: 6},
		Intuition: AttributeRange{Min: 1, Max: 6},
		Charisma:  AttributeRange{Min: 1, Max: 6},
		Edge:      &AttributeRange{Min: 2, Max: 7},
		Essence:   AttributeRange{Min: 1, Max: 6},
		Initiative: InitiativeCalculation{
			Formula: "REA+INT",
		},
		RacialTraits: []RacialTrait{},
		Source:       &SourceReference{Source: "SR5"},
	},
	"elf": {
		Name:      "Elf",
		Category:  MetatypeCategoryStandard,
		Body:      AttributeRange{Min: 1, Max: 6},
		Agility:   AttributeRange{Min: 2, Max: 7},
		Reaction:  AttributeRange{Min: 1, Max: 6},
		Strength:  AttributeRange{Min: 1, Max: 6},
		Willpower: AttributeRange{Min: 1, Max: 6},
		Logic:     AttributeRange{Min: 1, Max: 6},
		Intuition: AttributeRange{Min: 1, Max: 6},
		Charisma:  AttributeRange{Min: 3, Max: 8},
		Edge:      &AttributeRange{Min: 1, Max: 6},
		Essence:   AttributeRange{Min: 1, Max: 6},
		Initiative: InitiativeCalculation{
			Formula: "REA+INT",
		},
		RacialTraits: []RacialTrait{
			{Name: "Low-Light Vision"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"dwarf": {
		Name:      "Dwarf",
		Category:  MetatypeCategoryStandard,
		Body:      AttributeRange{Min: 3, Max: 8},
		Agility:   AttributeRange{Min: 1, Max: 6},
		Reaction:  AttributeRange{Min: 1, Max: 5},
		Strength:  AttributeRange{Min: 3, Max: 8},
		Willpower: AttributeRange{Min: 2, Max: 7},
		Logic:     AttributeRange{Min: 1, Max: 6},
		Intuition: AttributeRange{Min: 1, Max: 6},
		Charisma:  AttributeRange{Min: 1, Max: 6},
		Edge:      &AttributeRange{Min: 1, Max: 6},
		Essence:   AttributeRange{Min: 1, Max: 6},
		Initiative: InitiativeCalculation{
			Formula: "REA+INT",
		},
		RacialTraits: []RacialTrait{
			{Name: "Thermographic Vision"},
			{Name: "Pathogen and Toxin Resistance", Description: "+2 dice for pathogen and toxin resistance"},
			{Name: "Increased Lifestyle Cost", Description: "+20% increased Lifestyle cost"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"ork": {
		Name:      "Ork",
		Category:  MetatypeCategoryStandard,
		Body:      AttributeRange{Min: 4, Max: 9},
		Agility:   AttributeRange{Min: 1, Max: 6},
		Reaction:  AttributeRange{Min: 1, Max: 6},
		Strength:  AttributeRange{Min: 3, Max: 8},
		Willpower: AttributeRange{Min: 1, Max: 6},
		Logic:     AttributeRange{Min: 1, Max: 5},
		Intuition: AttributeRange{Min: 1, Max: 6},
		Charisma:  AttributeRange{Min: 1, Max: 6},
		Edge:      &AttributeRange{Min: 1, Max: 5},
		Essence:   AttributeRange{Min: 1, Max: 6},
		Initiative: InitiativeCalculation{
			Formula: "REA+INT",
		},
		RacialTraits: []RacialTrait{
			{Name: "Low-Light Vision"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"troll": {
		Name:      "Troll",
		Category:  MetatypeCategoryStandard,
		Body:      AttributeRange{Min: 5, Max: 10},
		Agility:   AttributeRange{Min: 1, Max: 5},
		Reaction:  AttributeRange{Min: 1, Max: 6},
		Strength:  AttributeRange{Min: 5, Max: 10},
		Willpower: AttributeRange{Min: 1, Max: 6},
		Logic:     AttributeRange{Min: 1, Max: 5},
		Intuition: AttributeRange{Min: 1, Max: 5},
		Charisma:  AttributeRange{Min: 1, Max: 4},
		Edge:      &AttributeRange{Min: 1, Max: 6},
		Essence:   AttributeRange{Min: 1, Max: 6},
		Initiative: InitiativeCalculation{
			Formula: "REA+INT",
		},
		RacialTraits: []RacialTrait{
			{Name: "Thermographic Vision"},
			{Name: "Reach", Description: "+1 Reach"},
			{Name: "Dermal Armor", Description: "+1 dermal armor"},
			{Name: "Increased Lifestyle Cost", Description: "double Lifestyle costs"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
}
