package v5

// DataPackCategories contains pack category names
var DataPackCategories = []string{
	"Core Packs",
	"Weapon and Ammo Packs",
	"Armor Packs",
	"Cyber Packs",
	"Lifestyle Packs",
	"Color Packs",
	"Vehicle Packs",
	"Decker Packs",
	"Drone Packs",
	"Magic Packs",
	"Community Packs",
	"Custom",
}

// DataPacks contains pack records keyed by their ID (lowercase with underscores)
var DataPacks = map[string]Pack{
	"intro_runner_pack": {
		Name:     "Intro Runner Pack",
		Category: "Core Packs",
		NuyenBP:  "2",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Armor Vest"}},
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"basic_runner_pack": {
		Name:     "Basic Runner Pack",
		Category: "Core Packs",
		NuyenBP:  "5",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Armor Vest"}},
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "Knife"}},
	},
	"advanced_runner_pack": {
		Name:     "Advanced Runner Pack",
		Category: "Core Packs",
		NuyenBP:  "10",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Armor Vest"}},
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "Knife"}},
	},
	"clasic_samurai_pack": {
		Name:     "Clasic Samurai Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "2",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Clothing"}},
		Gears:    &PackGears{Gear: PackGear{Name: nil, Category: "Software"}},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"up_close_personal_pack": {
		Name:     "Up Close & Personal Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "3",
		Gears:    &PackGears{Gear: PackGear{Name: "Throwing Knife", Category: "Ammunition", Qty: "4"}},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"blademaster_pack": {
		Name:     "Blademaster Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"monowhip_pack": {
		Name:     "Monowhip Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "10",
		Gears:    &PackGears{Gear: PackGear{Name: "DocWagon Contract, Basic", Category: "DocWagon Contract"}},
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "Monofilament Whip"}},
	},
	"basic_bowman_pack": {
		Name:     "Basic Bowman Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"advanced_bowman_pack": {
		Name:     "Advanced Bowman Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"ares_pistol_pack": {
		Name:     "Ares Pistol Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"big_boom_pistol_pack": {
		Name:     "Big Boom Pistol Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"browning_and_beretta_pistol_pack": {
		Name:     "Browning And Beretta Pistol Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"colt_pistol_pack": {
		Name:     "Colt Pistol Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"subtle_pistol_pack": {
		Name:     "Subtle Pistol Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"light_security_pack": {
		Name:     "Light Security Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"japanacorp_light_security_pack": {
		Name:     "Japanacorp Light Security Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"smartgun_pack": {
		Name:     "Smartgun Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"street_slugger_pack": {
		Name:     "Street Slugger Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"heavy_security_pack": {
		Name:     "Heavy Security Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: PackGear{Name: nil, Category: "Ammunition", Qty: "210"}},
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "FN HAR", Accessories: &PackWeaponAccessories{Accessory: nil}}},
	},
	"cheap_soldier_pack": {
		Name:     "Cheap Soldier Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"ares_alpha_gunner_pack": {
		Name:     "Ares Alpha Gunner Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "4",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "Ares Alpha", Accessories: &PackWeaponAccessories{Accessory: nil}}},
	},
	"sportsman_pack": {
		Name:     "Sportsman Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "2",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"tranq_darter_pack": {
		Name:     "Tranq Darter Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "Parashield Dart Rifle"}},
	},
	"tranq_pistol_darter_kit": {
		Name:     "Tranq Pistol Darter Kit",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"squad_weapon_assault_pack": {
		Name:     "Squad Weapon Assault Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "3",
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "Ingram Valiant", Accessories: &PackWeaponAccessories{Accessory: PackWeaponAccessory{Name: "Bipod", Mount: &[]string{"Under"}[0]}}}},
	},
	"medium_machine_gunner_pack": {
		Name:     "Medium Machine Gunner Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "4",
		Gears:    &PackGears{Gear: PackGear{Name: nil, Category: "Ammunition", Qty: "250"}},
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "Stoner-Ares M202", Accessories: &PackWeaponAccessories{Accessory: PackWeaponAccessory{Name: "Tripod", Mount: &[]string{"Under"}[0]}}}},
	},
	"rocketeer_pack": {
		Name:     "Rocketeer Pack",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "8",
		Gears:    &PackGears{Gear: PackGear{Name: "Rocket: Fragmentation", Category: "Ammunition", Qty: "5"}},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"box_of_grenades_1": {
		Name:     "Box of Grenades #1",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"box_of_grenades_2": {
		Name:     "Box of Grenades #2",
		Category: "Weapon and Ammo Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"city_slicker_pack": {
		Name:     "City Slicker Pack",
		Category: "Armor Packs",
		NuyenBP:  "1",
		Armors:   &PackArmors{Armor: nil},
		Gears:    &PackGears{Gear: PackGear{Name: "Respirator", Category: "Survival Gear", Rating: "3"}},
	},
	"go_anywhere_jacket_pack": {
		Name:     "Go Anywhere Jacket Pack",
		Category: "Armor Packs",
		NuyenBP:  "2",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Armor Jacket"}},
	},
	"neon_nights_pack": {
		Name:     "Neon Nights Pack",
		Category: "Armor Packs",
		NuyenBP:  "1",
		Armors:   &PackArmors{Armor: nil},
	},
	"nightbird_pack": {
		Name:     "Nightbird Pack",
		Category: "Armor Packs",
		NuyenBP:  "2",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Chameleon Suit"}},
		Gears:    &PackGears{Gear: nil},
	},
	"stylish_suit_pack": {
		Name:     "Stylish Suit Pack",
		Category: "Armor Packs",
		NuyenBP:  "1",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Actioneer Business Clothes"}},
	},
	"tacticool_helmet_pack": {
		Name:     "Tacticool Helmet Pack",
		Category: "Armor Packs",
		NuyenBP:  "3",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Helmet"}},
		Gears:    &PackGears{Gear: PackGear{Name: "Hermes Ikon", Category: "Commlinks"}},
	},
	"tusker_toughskin_pack": {
		Name:     "Tusker Toughskin Pack",
		Category: "Armor Packs",
		NuyenBP:  "1",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Armor Jacket"}},
	},
	"sim_setional_pack": {
		Name:     "Sim-Setional Pack",
		Category: "Cyber Packs",
		NuyenBP:  "6",
	},
	"basic_combat_eyes_pack": {
		Name:     "Basic Combat Eyes Pack",
		Category: "Cyber Packs",
		NuyenBP:  "4",
	},
	"advanced_combat_eyes_pack": {
		Name:     "Advanced Combat Eyes Pack",
		Category: "Cyber Packs",
		NuyenBP:  "7",
	},
	"eagle_eyes_pack": {
		Name:     "Eagle Eyes Pack",
		Category: "Cyber Packs",
		NuyenBP:  "7",
	},
	"rabbit_ears_pack": {
		Name:     "Rabbit Ears Pack",
		Category: "Cyber Packs",
		NuyenBP:  "9",
	},
	"bulletproof_jeff_pack": {
		Name:     "Bulletproof Jeff Pack",
		Category: "Cyber Packs",
		NuyenBP:  "12",
	},
	"basic_razorboi_pack": {
		Name:     "Basic Razorboi Pack",
		Category: "Cyber Packs",
		NuyenBP:  "2",
		Gears:    &PackGears{Gear: PackGear{Name: nil, Category: "Tools"}},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"advanced_razorboi_pack": {
		Name:     "Advanced Razorboi Pack",
		Category: "Cyber Packs",
		NuyenBP:  "6",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"basic_speedboost_pack": {
		Name:     "Basic Speedboost Pack",
		Category: "Cyber Packs",
		NuyenBP:  "20",
	},
	"advanced_speedboost_pack": {
		Name:     "Advanced Speedboost Pack",
		Category: "Cyber Packs",
		NuyenBP:  "75",
	},
	"basic_vatjob_pack": {
		Name:     "Basic Vatjob Pack",
		Category: "Cyber Packs",
		NuyenBP:  "14",
	},
	"advanced_vatjob_pack": {
		Name:     "Advanced Vatjob Pack",
		Category: "Cyber Packs",
		NuyenBP:  "28",
	},
	"basic_rigger_pack": {
		Name:     "Basic Rigger Pack",
		Category: "Cyber Packs",
		NuyenBP:  "28",
	},
	"advanced_rigger_pack": {
		Name:     "Advanced Rigger Pack",
		Category: "Cyber Packs",
		NuyenBP:  "52",
	},
	"street_samurai_classic_pack": {
		Name:     "Street Samurai Classic Pack",
		Category: "Cyber Packs",
		NuyenBP:  "100",
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"bioware_cat_packcatgirl_pack": {
		Name:     "Bioware Cat Pack(Catgirl pack)",
		Category: "Cyber Packs",
		NuyenBP:  "14",
	},
	"bio_computer_pack": {
		Name:     "Bio-Computer Pack",
		Category: "Cyber Packs",
		NuyenBP:  "41",
	},
	"bioware_company_man_pack": {
		Name:     "Bioware Company Man Pack",
		Category: "Cyber Packs",
		NuyenBP:  "50",
	},
	"basic_cyberdeck_programs_pack": {
		Name:     "Basic Cyberdeck Programs Pack",
		Category: "Decker Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"bug_out_bag": {
		Name:     "Bug-out Bag",
		Category: "Lifstyle Packs",
		NuyenBP:  "2",
		Armors:   &PackArmors{Armor: PackArmor{Name: "Armor Clothing"}},
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
	"cocktail_kid_pack": {
		Name:     "Cocktail Kid Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"drone_mechanic_pack": {
		Name:     "Drone Mechanic Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"mechanic_shop_pack": {
		Name:     "Mechanic Shop Pack",
		Category: "Color Packs",
		NuyenBP:  "3",
		Gears:    &PackGears{Gear: nil},
	},
	"eavesdropper_pack": {
		Name:     "Eavesdropper Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"surveillance_pack": {
		Name:     "Surveillance Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"breaking_and_entering_pack": {
		Name:     "Breaking and Entering Pack",
		Category: "Color Packs",
		NuyenBP:  "3",
		Gears:    &PackGears{Gear: nil},
	},
	"jammer_pack": {
		Name:     "Jammer Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"medic_pack": {
		Name:     "Medic Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"medical_patches_pack": {
		Name:     "Medical Patches Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"mountaineering_pack": {
		Name:     "Mountaineering Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"infiltration_pack": {
		Name:     "Infiltration Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"demolitionist_pack": {
		Name:     "Demolitionist Pack",
		Category: "Color Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"racing_bike_pack": {
		Name:     "Racing Bike Pack",
		Category: "Vehicle Packs",
		NuyenBP:  "5",
		Armors:   &PackArmors{Armor: nil},
		Gears:    &PackGears{Gear: nil},
	},
	"off_road_pack": {
		Name:     "Off Road Pack",
		Category: "Vehicle Packs",
		NuyenBP:  "20",
	},
	"basic_decker_pack": {
		Name:     "Basic Decker Pack",
		Category: "Decker Packs",
		NuyenBP:  "62",
		Gears:    &PackGears{Gear: nil},
	},
	"advanced_decker_pack": {
		Name:     "Advanced Decker Pack",
		Category: "Decker Packs",
		NuyenBP:  "100",
		Gears:    &PackGears{Gear: nil},
	},
	"advanced_cyberdeck_programs_pack": {
		Name:     "Advanced Cyberdeck Programs Pack",
		Category: "Decker Packs",
		NuyenBP:  "1",
		Gears:    &PackGears{Gear: nil},
	},
	"basic_spy_drone_pack": {
		Name:     "Basic Spy Drone Pack",
		Category: "Drone Packs",
		NuyenBP:  "2",
	},
	"advanced_spy_drone_pack": {
		Name:     "Advanced Spy Drone Pack",
		Category: "Drone Packs",
		NuyenBP:  "11",
	},
	"basic_combat_drone_pack": {
		Name:     "Basic Combat Drone Pack",
		Category: "Drone Packs",
		NuyenBP:  "3",
		Gears:    &PackGears{Gear: PackGear{Name: nil, Category: "Ammunition", Qty: "170"}},
	},
	"advanced_combat_drone_pack": {
		Name:     "Advanced Combat Drone Pack",
		Category: "Drone Packs",
		NuyenBP:  "14",
	},
	"runnerhub_basic_gear_pack": {
		Name:     "Runnerhub Basic Gear Pack",
		Category: "Community Packs",
		NuyenBP:  "21",
		Armors:   &PackArmors{Armor: nil},
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "Steyr TMP", Accessories: &PackWeaponAccessories{Accessory: nil}}},
	},
	"runnerhub_pennypincher_pack": {
		Name:     "Runnerhub Pennypincher Pack",
		Category: "Community Packs",
		NuyenBP:  "5",
		Armors:   &PackArmors{Armor: nil},
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: PackWeapon{Name: "Steyr TMP", Accessories: &PackWeaponAccessories{Accessory: nil}}},
	},
	"shadownet_starter_pack": {
		Name:     "ShadowNET starter pack",
		Category: "Community Packs",
		NuyenBP:  "10",
		Armors:   &PackArmors{Armor: nil},
		Gears:    &PackGears{Gear: nil},
		Weapons:  &PackWeapons{Weapon: nil},
	},
}
