package v5

// DataParagonCategory contains the paragon category name
var DataParagonCategory = "Resonance"

// DataParagons contains paragon records keyed by their ID (lowercase with underscores)
var DataParagons = map[string]Paragon{
	"01_the_world_tree": {
		ID:           "acadd628-ebb5-4c79-a3c2-953ce7fa1885",
		Name:         "01 (The World Tree)",
		Category:     "Resonance",
		Advantage:    "If a follower of 01 has at least one mark on a target, they may act as if they have an extra mark on it.",
		Disadvantage: "\u20131 limit and \u20131 dice pool penalty when acting only in AR.",
		Source:       "KC",
		Page:         "103",
	},
	"architect": {
		ID:           "46f88748-8c6c-4230-ad59-2eccb463cc35",
		Name:         "Architect",
		Category:     "Resonance",
		Advantage:    "+1 limit and +1 dice pool bonus for Edit actions.",
		Disadvantage: "\u20131 limit and \u20131 dice for Snoop actions.",
		Source:       "KC",
		Page:         "103",
		Bonus:        &ParagonBonus{SpecificSkill: nil},
	},
	"archivist_the_record_keeper": {
		ID:           "690ccad8-3f42-4d62-a358-e099747fc4e4",
		Name:         "Archivist (The Record Keeper)",
		Category:     "Resonance",
		Advantage:    "+1 limit and +1 dice pool bonus for Browse actions and digital legwork.",
		Disadvantage: "\u20131 limit for Edit actions designed to destroy data.",
		Source:       "KC",
		Page:         "177",
		Bonus:        &ParagonBonus{SpecificSkill: nil},
	},
	"black_hat_the_cracker": {
		ID:           "117e7c69-abea-4637-b5e7-3a927ae0ad60",
		Name:         "Black Hat (The Cracker)",
		Category:     "Resonance",
		Advantage:    "+2 limit for gaining marks on a target.",
		Disadvantage: "-1 limit and \u20131 die when setting a Data Bomb.",
		Source:       "KC",
		Page:         "103",
	},
	"daedalus_the_inventor": {
		ID:           "b74d032e-5d39-4e4a-b043-0707ffa00b5e",
		Name:         "Daedalus (The Inventor)",
		Category:     "Resonance",
		Advantage:    "+1 dice pool bonus for Hardware tests, +1 limit on Pilot skill tests when jumped in.",
		Disadvantage: "\u20131 dice and limit for all actions in the Deep Resonance.",
		Source:       "KC",
		Page:         "103",
		Bonus:        &ParagonBonus{SpecificSkill: nil},
	},
	"delphi_the_oracle": {
		ID:           "c45c123c-06c7-42b3-a2ee-01e37f2f7bf8",
		Name:         "Delphi (The Oracle)",
		Category:     "Resonance",
		Advantage:    "+1 bonus to dice pool and limit when threading complex forms.",
		Disadvantage: "\u20132 modifier to the technomancer's Initiative Score.",
		Source:       "KC",
		Page:         "104",
		Bonus:        &ParagonBonus{ActionDicePool: nil, Initiative: "-2", MatrixInitiative: "-2"},
	},
	"intrusion_countermeasure_the_guardian": {
		ID:           "df42911f-0542-4fae-80d1-39573547ff68",
		Name:         "Intrusion Countermeasure (The Guardian)",
		Category:     "Resonance",
		Advantage:    "+1 bonus to dice pool and limit in cybercombat, +1 to firewall.",
		Disadvantage: "\u20131 dice pool penalty when attacking IC in cybercombat.",
		Source:       "KC",
		Page:         "104",
		Bonus:        &ParagonBonus{SpecificSkill: nil, LivingPersona: nil},
	},
	"probe_the_scout": {
		ID:           "da2f3bad-d934-461a-aa92-60fc6e5c3ef7",
		Name:         "Probe (The Scout)",
		Category:     "Resonance",
		Advantage:    "+2 dice pool bonus and +1 limit on all actions when directly connected to an isolated system.",
		Disadvantage: "\u20131 limit penalty when logged into more than one grid.",
		Source:       "KC",
		Page:         "104",
	},
	"shooter_the_soldier": {
		ID:           "de755412-5cae-4859-880f-75a7bd68d5a4",
		Name:         "Shooter (The Soldier)",
		Category:     "Resonance",
		Advantage:    "+1 bonus to dice pool and limit in cybercombat, +1 limit to all attack actions (physical and Matrix)",
		Disadvantage: "\u20132 dice pool penalty and \u20131 limit when compiling sprites.",
		Source:       "KC",
		Page:         "104",
		Bonus:        &ParagonBonus{SpecificSkill: nil, WeaponSkillAccuracy: nil},
	},
}
