package v5

// dataPrograms contains all Matrix program definitions
var dataPrograms = map[string]Program{
	// Agents
	"agent_1_3": {
		Name:         "Agent",
		Type:         ProgramTypeAgent,
		Description:  "Agents are autonomous programs rated from 1 to 6. Each agent occupies one program slot on your deck. Agents use the Matrix attributes of the device they run on, and their rating (up to 6) for attributes. Agents also have the Computer, Hacking, and Cybercombat skills at a rating equal to their own. An agent runs as a program and can use programs running on the same device as them. You can have your agent perform Matrix actions for you. When an agent is running, it has its own persona (and icon). An agent is about as smart as a pilot program of the same rating. Any attack on an agent damages the device on which it is running, rather than the agent itself (which is, after all, merely a program). This means that if you're running an agent on your deck, you and it share the same Matrix Condition Monitor.",
		RatingRange:  &AgentRatingRange{MinRating: 1, MaxRating: 3},
		Availability: &AgentAvailabilityFormula{AvailabilityPerRating: 3, Formula: "Rating × 3"},
		Cost:         &AgentCostFormula{CostPerRating: 1000, Formula: "Rating × 1000¥"},
		Source:       &SourceReference{Source: "SR5"},
	},
	"agent_4_6": {
		Name:         "Agent",
		Type:         ProgramTypeAgent,
		Description:  "Agents are autonomous programs rated from 1 to 6. Each agent occupies one program slot on your deck. Agents use the Matrix attributes of the device they run on, and their rating (up to 6) for attributes. Agents also have the Computer, Hacking, and Cybercombat skills at a rating equal to their own. An agent runs as a program and can use programs running on the same device as them. You can have your agent perform Matrix actions for you. When an agent is running, it has its own persona (and icon). An agent is about as smart as a pilot program of the same rating. Any attack on an agent damages the device on which it is running, rather than the agent itself (which is, after all, merely a program). This means that if you're running an agent on your deck, you and it share the same Matrix Condition Monitor.",
		RatingRange:  &AgentRatingRange{MinRating: 4, MaxRating: 6},
		Availability: &AgentAvailabilityFormula{AvailabilityPerRating: 3, Formula: "Rating × 3"},
		Cost:         &AgentCostFormula{CostPerRating: 2000, Formula: "Rating × 2000¥"},
		Source:       &SourceReference{Source: "SR5"},
	},
	// Commlink Apps
	"ar_games": {
		Name:        "AR Games",
		Type:        ProgramTypeCommlinkApp,
		Description: "Casual games displayed in augmented reality, allowing a user to enjoy them as a pastime while also still somewhat paying attention to reality.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"diagnostics": {
		Name:        "Diagnostics",
		Type:        ProgramTypeCommlinkApp,
		Description: "An ongoing self-evaluation system that monitors all the devices in a user's PAN, giving constant vital statistics on their behavior. Popular with computer-literate users and useful for keeping people aware of attacks against their PAN.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"p2_1": {
		Name:        "P2.1",
		Type:        ProgramTypeCommlinkApp,
		Description: "A dramatic update to the old P2.0 system put into place by Horizon, this social networking app monitors and supports all other social networks that a person might use, incorporating it all into a dramatic web of information. It also generates a P-Score that is a major piece of status in a lot of virtual places and within Horizon as a whole.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"theme_music": {
		Name:        "Theme Music",
		Type:        ProgramTypeCommlinkApp,
		Description: "An algorithm that constantly monitors the owner of the PAN in all their interactions with devices. Taking this data, it attempts to determine the emotional state of the person and generates a playlist of songs to better support said user, either enhancing the feelings or dampening them. Essentially the mood ring of the Sixth World.",
		Source:      &SourceReference{Source: "SR5"},
	},
	"ticker": {
		Name:        "Ticker",
		Type:        ProgramTypeCommlinkApp,
		Description: "A series of commlink apps that provide an information feed from a specified source, the vast majority being legitimate, such as stock markets and news organizations. Some shadow services also use these apps to give details on other shadowrunners, fixers, Mr. Johnsons, police response times, and current payment rates for a variety of services and bribes. Ticker reduces the time for subject-related Matrix Searches in half.",
		Effects: []ProgramEffect{
			{Action: "Matrix Search Action", Effect: "Halve Time"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	// Common Programs
	"bootstrap": {
		Name:         "Bootstrap",
		Type:         ProgramTypeCommon,
		ActionEffect: "Format Device",
		Description:  "Set up a variety of tasks in the boot record. Allows for hidden commands to be input into the device after the next reboot. Popular options include announcing the location of the device when it connects to the Matrix, adjusting the processing of the device so that the default device attributes are the choice of the user, annoying the user with constant demands for ownership permissions, and making a record of every action on the device.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"browse": {
		Name:         "Browse",
		Type:         ProgramTypeCommon,
		ActionEffect: "Matrix Search Action - Halve Time",
		Description:  "This handy browser and search engine cuts the time for a Matrix Search action in half.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"configurator": {
		Name:         "Configurator",
		Type:         ProgramTypeCommon,
		ActionEffect: "Swap Two Attributes / Change to preset configuration / Un/Load Program",
		Description:  "Load preset program configurations, swap two attributes, or change to a preset configuration.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"edit": {
		Name:         "Edit",
		Type:         ProgramTypeCommon,
		ActionEffect: "Edit File",
		Description:  "Standard file editing program.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"encryption": {
		Name:         "Encryption",
		Type:         ProgramTypeCommon,
		ActionEffect: "Encrypt/Decrypt File",
		Description:  "Standard encryption/decryption program.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"search": {
		Name:         "Search",
		Type:         ProgramTypeCommon,
		ActionEffect: "Matrix Search",
		Description:  "Standard Matrix search program.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"shredder": {
		Name:         "Shredder",
		Type:         ProgramTypeCommon,
		ActionEffect: "Delete File",
		Description:  "Standard file deletion program.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"signal_scrub": {
		Name:         "Signal Scrub",
		Type:         ProgramTypeCommon,
		ActionEffect: "Reduce Noise",
		Description:  "Reduces noise in Matrix connections.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"toolbox": {
		Name:         "Toolbox",
		Type:         ProgramTypeCommon,
		ActionEffect: "Repair",
		Description:  "Assists in repairing devices.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"virtual_machine": {
		Name:         "Virtual Machine",
		Type:         ProgramTypeCommon,
		ActionEffect: "Run Programs",
		Description:  "Allows running programs in an isolated environment.",
		Source:       &SourceReference{Source: "SR5"},
	},
	// Hacking Programs
	"armor": {
		Name:         "Armor",
		Type:         ProgramTypeHacking,
		ActionEffect: "Matrix Damage",
		Description:  "+1 dice pool modifier to resist Matrix damage. This modifier stacks with similar modifiers from other programs.",
		Effects: []ProgramEffect{
			{DicePoolBonus: "+1 dice pool modifier to resist Matrix damage"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"baby_monitor": {
		Name:         "Baby Monitor",
		Type:         ProgramTypeHacking,
		ActionEffect: "Matrix Perception",
		Description:  "+2 dice pool modifier to Matrix Perception tests.",
		Effects: []ProgramEffect{
			{DicePoolBonus: "+2 dice pool modifier to Matrix Perception tests"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"biofeedback": {
		Name:         "Biofeedback",
		Type:         ProgramTypeHacking,
		ActionEffect: "Biofeedback Damage",
		Description:  "+1 DV biofeedback damage caused.",
		Effects: []ProgramEffect{
			{DamageBonus: "+1 DV biofeedback damage caused"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"biofeedback_filter": {
		Name:         "Biofeedback Filter",
		Type:         ProgramTypeHacking,
		ActionEffect: "Biofeedback Damage",
		Description:  "+1 dice pool modifier to resist biofeedback damage. This modifier stacks with similar modifiers from other programs.",
		Effects: []ProgramEffect{
			{DicePoolBonus: "+1 dice pool modifier to resist biofeedback damage"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"blackout": {
		Name:         "Blackout",
		Type:         ProgramTypeHacking,
		ActionEffect: "Reboot Device",
		Description:  "+2 to Attack attribute for Reboot Device attempts.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+2 to Attack attribute for Reboot Device attempts"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"cats_paw": {
		Name:         "Cat's Paw",
		Type:         ProgramTypeHacking,
		ActionEffect: "Brute Force",
		Description:  "+2 to Attack attribute for Brute Force attempts.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+2 to Attack attribute for Brute Force attempts"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"cloudless": {
		Name:         "Cloudless",
		Type:         ProgramTypeHacking,
		ActionEffect: "Noise",
		Description:  "Reduces noise by 1.",
		Effects: []ProgramEffect{
			{OtherEffects: "Reduces noise by 1"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"crash": {
		Name:         "Crash",
		Type:         ProgramTypeHacking,
		ActionEffect: "Crash Program",
		Description:  "+2 to Attack attribute for Crash Program attempts.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+2 to Attack attribute for Crash Program attempts"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"decryption": {
		Name:         "Decryption",
		Type:         ProgramTypeHacking,
		ActionEffect: "Decrypt File",
		Description:  "+2 to Data Processing attribute for Decrypt File attempts.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+2 to Data Processing attribute for Decrypt File attempts"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"defuse": {
		Name:         "Defuse",
		Type:         ProgramTypeHacking,
		ActionEffect: "Disarm Data Bomb",
		Description:  "+2 dice pool modifier to Disarm Data Bomb attempts.",
		Effects: []ProgramEffect{
			{DicePoolBonus: "+2 dice pool modifier to Disarm Data Bomb attempts"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"demolition": {
		Name:         "Demolition",
		Type:         ProgramTypeHacking,
		ActionEffect: "Data Bomb",
		Description:  "+2 to Attack attribute for Data Bomb attempts.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+2 to Attack attribute for Data Bomb attempts"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detonator": {
		Name:         "Detonator",
		Type:         ProgramTypeHacking,
		ActionEffect: "Data Bomb",
		Description:  "+1 DV damage from Data Bomb.",
		Effects: []ProgramEffect{
			{DamageBonus: "+1 DV damage from Data Bomb"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"exploit": {
		Name:         "Exploit",
		Type:         ProgramTypeHacking,
		ActionEffect: "Hack on the Fly",
		Description:  "+2 to Sleaze attribute when attempting a Hack on the Fly action. This program analyzes and scans a target for weaknesses in its Firewall.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+2 to Sleaze attribute when attempting a Hack on the Fly action"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"evaluate": {
		Name:         "Evaluate",
		Type:         ProgramTypeHacking,
		ActionEffect: "Paydata",
		Description:  "Calculates how much a certain amount of paydata might be worth, allowing the decker to only take an amount that would limit the amount of heat they would generate in stealing a little extra while on the job.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"fly_on_a_wall": {
		Name:         "Fly on a Wall",
		Type:         ProgramTypeHacking,
		ActionEffect: "Hide",
		Description:  "While this program is running, and the decker is performing no actions other than Matrix Perception tests, the Overwatch Score only increases by 1D6 per half-hour (rolled in secret by the gamemaster as normal). The program requires a Hide action in order to activate properly, and it does not assist in any way in preventing any other icon from noticing the decker.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"fork": {
		Name:         "Fork",
		Type:         ProgramTypeHacking,
		ActionEffect: "Single Matrix Action",
		Description:  "You can perform a single Matrix action on two targets with this program. You make a single test, with modifiers from each target both counting toward your dice pool. Each of the targets defend with their own dice pools. Determine the result of the actions separately against each target.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"guard": {
		Name:         "Guard",
		Type:         ProgramTypeHacking,
		ActionEffect: "Mark Damage",
		Description:  "-1 DV Matrix Damage Received Per Mark. This program keeps an eye out for weaknesses the same way an attacker would, reducing the extra damage you take from marks by 1 DV per mark.",
		Effects: []ProgramEffect{
			{DamageBonus: "-1 DV Matrix Damage Received Per Mark"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"hammer": {
		Name:         "Hammer",
		Type:         ProgramTypeHacking,
		ActionEffect: "Matrix Damage",
		Description:  "+2 DV Matrix Damage caused. Whenever you cause Matrix damage with an action, this offensive program lets you inflict +2 DV worth of Matrix Damage. This does not apply against targets that take damage from failing an Attack action against you.",
		Effects: []ProgramEffect{
			{DamageBonus: "+2 DV Matrix Damage caused"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"hitchhiker": {
		Name:         "Hitchhiker",
		Type:         ProgramTypeHacking,
		ActionEffect: "Special",
		Description:  "There are some special parts of the Matrix where you can take others with you--and where you definitely don't want to be alone. Grab this program to take your non-hacker friends to foundations and UV hosts.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"lockdown": {
		Name:         "Lockdown",
		Type:         ProgramTypeHacking,
		ActionEffect: "Link-Lock",
		Description:  "Matrix Damage to persona link-locks them. When you cause damage to a persona, he or she is link-locked until you stop running this program or they successfully Jack Out.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"mugger": {
		Name:         "Mugger",
		Type:         ProgramTypeHacking,
		ActionEffect: "Mark Damage",
		Description:  "+1 DV Matrix Damage Caused Per Mark. By actively tracking your marks, the bonus damage from them is increased by 1 DV per mark.",
		Effects: []ProgramEffect{
			{DamageBonus: "+1 DV Matrix Damage Caused Per Mark"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"nuke_from_orbit": {
		Name:         "Nuke-from-Orbit",
		Type:         ProgramTypeHacking,
		ActionEffect: "Edit File",
		Description:  "A hugely powerful file destruction program that requires frequent updates as adjustments in file recovery technology continue to progress. This upgraded and outright illegal program is designed to ensure that no one will ever be able to recover a file that it destroys. If used to delete a file (the Edit File action should be used), this program ensures that no one will ever be able to recover the file from the Matrix. A brutal and decidedly unsubtle cyberprogram, any Overwatch Score generated from the Opposed Test is doubled. Offline back-ups and the Resonance realms are the only options for getting the file back.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"paintjob": {
		Name:         "Paintjob",
		Type:         ProgramTypeHacking,
		ActionEffect: "Erase Marks",
		Description:  "+2 to Attack attribute for the purpose of making Erase Mark tests. Resprays and textures a persona's icon, assisting in erasing or knocking off marks as it does so, ensuring the decker is able to trust in the fact that his cyberdeck is not being affected by outsiders.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+2 to Attack attribute for the purpose of making Erase Mark tests"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"shell": {
		Name:         "Shell",
		Type:         ProgramTypeHacking,
		ActionEffect: "Matrix Damage / Biofeedback Damage",
		Description:  "+1 dice pool modifier to resist both Matrix and biofeedback damage. This modifier stacks with similar modifiers from other programs. This program uses a set of filtering algorithms.",
		Effects: []ProgramEffect{
			{DicePoolBonus: "+1 dice pool modifier to resist both Matrix and biofeedback damage"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"smoke_and_mirrors": {
		Name:         "Smoke-and-Mirrors",
		Type:         ProgramTypeHacking,
		ActionEffect: "All actions",
		Description:  "Adds significant amounts of misleading location information in order to keep the decker from being located IRL. This program increases the cyberdeck's Sleaze attribute between 1 and 5 (user's choice) with an equivalent amount of noise added to any tests performed with the deck. The noise also affects Trace Icon tests performed against the deck using the program. This program has no effect against convergence (p. 231, SR5), as GOD and all the demiGODs cannot be distracted by so simple a trick.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"sneak": {
		Name:         "Sneak",
		Type:         ProgramTypeHacking,
		ActionEffect: "Trace User",
		Description:  "+2 dice pool modifier to defend against Trace User actions. Additionally, if a demiGOD converges on you while this program is running, they don't get your physical location, although you're still hit with all the other bad stuff they throw at you. This utility bounces your Matrix traffic through unnecessary routes.",
		Effects: []ProgramEffect{
			{DicePoolBonus: "+2 dice pool modifier to defend against Trace User actions"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"stealth": {
		Name:         "Stealth",
		Type:         ProgramTypeHacking,
		ActionEffect: "Sleaze",
		Description:  "+1 to Sleaze attribute. This clever program gives you a +1 bonus to your Sleaze attribute.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+1 to Sleaze attribute"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"swerve": {
		Name:         "Swerve",
		Type:         ProgramTypeHacking,
		ActionEffect: "Firewall",
		Description:  "Add +1 to Firewall when resisting Reboot Device attempts for any device in the PAN. Just as deckers have seen the benefits of forcing other devices to reboot, they have seen a need to keep their devices safe from those efforts. Swerve adds redundant code to the OS of the cyberdeck and any connected devices in the decker's PAN, making it easier for the devices to resist crash attacks.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+1 to Firewall when resisting Reboot Device attempts for any device in the PAN"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"tantrum": {
		Name:         "Tantrum",
		Type:         ProgramTypeHacking,
		ActionEffect: "Data Spike",
		Description:  "Does no damage. A living target in VR suffers Nausea for 3 turns. This program overlays cold simsense sensations on top of a Data Spike action, hitting the target with a quick and disgusting sensation if even a single box of Matrix Damage is scored. The program is effective against all technomancers, as well as cold sim or hot sim deckers, but it does nothing to users working in the Matrix in AR, any form of IC, and agents. The program does no damage from the Data Spike; instead, the targeted user experiences Nausea (p. 409, SR5) for three Combat Turns due to the sensory input. Popular options this program uses to make targets feel queasy include the smell of a dirty diaper or the feeling of being punched in the junk.",
		Source:       &SourceReference{Source: "SR5"},
	},
	"tarball": {
		Name:         "Tarball",
		Type:         ProgramTypeHacking,
		ActionEffect: "Crash Program",
		Description:  "+2 to Attack attribute and +1 to Crash Program tests (both of these bonuses only apply to Crash Program attempts), but its broader-based attack affects a random program rather than a chosen one. A powerful but inaccurate combat program based on the old tar-based IC used for decades.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+2 to Attack attribute and +1 to Crash Program tests (both of these bonuses only apply to Crash Program attempts)"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"track": {
		Name:         "Track",
		Type:         ProgramTypeHacking,
		ActionEffect: "Trace User",
		Description:  "+2 to Data Processing attribute when making Trace User tests with Track running. Alternately, if the target is running Sneak, Track negates the +2 dice pool bonus from that program. Note that the program delivers one of the listed benefits, not both. The Track program keeps an eye on your targets for you, making it easier to find their meat world equivalents.",
		Effects: []ProgramEffect{
			{AttributeBonus: "+2 to Data Processing attribute when making Trace User tests with Track running"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"wrapper": {
		Name:         "Wrapper",
		Type:         ProgramTypeHacking,
		ActionEffect: "Change Icon",
		Description:  "This program overrides the Matrix's protocols for icons. While this program is running, your icons can be anything you want them to be when you use the Change Icon action. From the lens of the Matrix, your Hammer program could look like a music file, your Ares Predator icon could look like a credstick, and your own persona could look like a Mitsubishi Nightsky. Another persona can see what the disguised icon really is with a Matrix Perception Test, but they need to at least suspect enough to check (Matrix Perception, p. 241).",
		Source:       &SourceReference{Source: "SR5"},
	},
}
