package v5

// DataRangeModifiers contains range modifier values
var DataRangeModifiers = map[string]string{
	"extreme": "-6",
	"long":    "-3",
	"medium":  "-1",
	"short":   "0",
}

// DataRanges contains range table records keyed by their ID (lowercase with underscores)
var DataRanges = map[string]Range{
	"tasers": {
		Name:    "Tasers",
		Min:     "0",
		Short:   "5",
		Medium:  "10",
		Long:    "15",
		Extreme: "20",
	},
	"holdouts": {
		Name:    "Holdouts",
		Min:     "0",
		Short:   "5",
		Medium:  "15",
		Long:    "30",
		Extreme: "50",
	},
	"light_pistols": {
		Name:    "Light Pistols",
		Min:     "0",
		Short:   "5",
		Medium:  "15",
		Long:    "30",
		Extreme: "50",
	},
	"heavy_pistols": {
		Name:    "Heavy Pistols",
		Min:     "0",
		Short:   "5",
		Medium:  "20",
		Long:    "40",
		Extreme: "60",
	},
	"machine_pistols": {
		Name:    "Machine Pistols",
		Min:     "0",
		Short:   "5",
		Medium:  "15",
		Long:    "30",
		Extreme: "50",
	},
	"submachine_guns": {
		Name:    "Submachine Guns",
		Min:     "0",
		Short:   "10",
		Medium:  "40",
		Long:    "80",
		Extreme: "150",
	},
	"assault_rifles": {
		Name:    "Assault Rifles",
		Min:     "0",
		Short:   "25",
		Medium:  "150",
		Long:    "350",
		Extreme: "550",
	},
	"shotguns": {
		Name:    "Shotguns",
		Min:     "0",
		Short:   "10",
		Medium:  "40",
		Long:    "80",
		Extreme: "150",
	},
	"shotguns_slug": {
		Name:    "Shotguns (slug)",
		Min:     "0",
		Short:   "10",
		Medium:  "40",
		Long:    "80",
		Extreme: "150",
	},
	"shotguns_flechette": {
		Name:    "Shotguns (flechette)",
		Min:     "0",
		Short:   "15",
		Medium:  "30",
		Long:    "45",
		Extreme: "60",
	},
	"sniper_rifles": {
		Name:    "Sniper Rifles",
		Min:     "0",
		Short:   "50",
		Medium:  "350",
		Long:    "800",
		Extreme: "1500",
	},
	"sporting_rifles": {
		Name:    "Sporting Rifles",
		Min:     "0",
		Short:   "50",
		Medium:  "250",
		Long:    "500",
		Extreme: "750",
	},
	"light_machine_guns": {
		Name:    "Light Machine Guns",
		Min:     "0",
		Short:   "25",
		Medium:  "200",
		Long:    "400",
		Extreme: "800",
	},
	"mediumheavy_machinegun": {
		Name:    "Medium/Heavy Machinegun",
		Min:     "0",
		Short:   "40",
		Medium:  "250",
		Long:    "750",
		Extreme: "1200",
	},
	"assault_cannons": {
		Name:    "Assault Cannons",
		Min:     "0",
		Short:   "50",
		Medium:  "300",
		Long:    "750",
		Extreme: "1500",
	},
	"grenade_launchers": {
		Name:    "Grenade Launchers",
		Min:     "5",
		Short:   "50",
		Medium:  "100",
		Long:    "150",
		Extreme: "500",
	},
	"missile_launchers": {
		Name:    "Missile Launchers",
		Min:     "20",
		Short:   "70",
		Medium:  "150",
		Long:    "450",
		Extreme: "1500",
	},
	"bows": {
		Name:    "Bows",
		Min:     "0",
		Short:   "{STR}",
		Medium:  "{STR}*10",
		Long:    "{STR}*30",
		Extreme: "{STR}*60",
	},
	"light_crossbows": {
		Name:    "Light Crossbows",
		Min:     "0",
		Short:   "6",
		Medium:  "24",
		Long:    "60",
		Extreme: "120",
	},
	"medium_crossbows": {
		Name:    "Medium Crossbows",
		Min:     "0",
		Short:   "9",
		Medium:  "36",
		Long:    "90",
		Extreme: "150",
	},
	"heavy_crossbows": {
		Name:    "Heavy Crossbows",
		Min:     "0",
		Short:   "15",
		Medium:  "45",
		Long:    "120",
		Extreme: "180",
	},
	"thrown_knife": {
		Name:    "Thrown Knife",
		Min:     "0",
		Short:   "{STR}",
		Medium:  "{STR}*2",
		Long:    "{STR}*3",
		Extreme: "{STR}*5",
	},
	"net": {
		Name:    "Net",
		Min:     "0",
		Short:   "{STR}/2",
		Medium:  "{STR}",
		Long:    "{STR}*1.5",
		Extreme: "{STR}*2.5",
	},
	"shuriken": {
		Name:    "Shuriken",
		Min:     "0",
		Short:   "{STR}",
		Medium:  "{STR}*2",
		Long:    "{STR}*5",
		Extreme: "{STR}*7",
	},
	"standard_grenade": {
		Name:    "Standard Grenade",
		Min:     "0",
		Short:   "{STR}*2",
		Medium:  "{STR}*4",
		Long:    "{STR}*6",
		Extreme: "{STR}*10",
	},
	"aerodynamic_grenade": {
		Name:    "Aerodynamic Grenade",
		Min:     "0",
		Short:   "{STR}*2",
		Medium:  "{STR}*4",
		Long:    "{STR}*8",
		Extreme: "{STR}*15",
	},
	"harpoon_gun": {
		Name:    "Harpoon Gun",
		Min:     "0",
		Short:   "5",
		Medium:  "20",
		Long:    "40",
		Extreme: "60",
	},
	"harpoon_gun_underwater": {
		Name:    "Harpoon Gun (Underwater)",
		Min:     "0",
		Short:   "6",
		Medium:  "24",
		Long:    "60",
		Extreme: "120",
	},
	"flamethrowers": {
		Name:    "Flamethrowers",
		Min:     "0",
		Short:   "15",
		Medium:  "20",
		Long:    "-1",
		Extreme: "-1",
	},
	"carbines": {
		Name:    "Carbines",
		Min:     "0",
		Short:   "10",
		Medium:  "40",
		Long:    "80",
		Extreme: "150",
	},
}
