package v5

// DataSkillGroups contains skill group names
var DataSkillGroups = []string{
	"Acting",
	"Athletics",
	"Biotech",
	"Close Combat",
	"Conjuring",
	"Cracking",
	"Electronics",
	"Enchanting",
	"Firearms",
	"Influence",
	"Engineering",
	"Outdoors",
	"Sorcery",
	"Stealth",
	"Tasking",
}

// DataSkillCategories contains skill categories keyed by their ID (lowercase with underscores)
var DataSkillCategories = map[string]SkillCategory{
	"combat_active": {
		Name: "Combat Active", Type: "active",
	},
	"physical_active": {
		Name: "Physical Active", Type: "active",
	},
	"social_active": {
		Name: "Social Active", Type: "active",
	},
	"magical_active": {
		Name: "Magical Active", Type: "active",
	},
	"pseudo_magical_active": {
		Name: "Pseudo-Magical Active", Type: "active",
	},
	"resonance_active": {
		Name: "Resonance Active", Type: "active",
	},
	"technical_active": {
		Name: "Technical Active", Type: "active",
	},
	"vehicle_active": {
		Name: "Vehicle Active", Type: "active",
	},
	"academic": {
		Name: "Academic", Type: "knowledge",
	},
	"interest": {
		Name: "Interest", Type: "knowledge",
	},
	"language": {
		Name: "Language", Type: "knowledge",
	},
	"professional": {
		Name: "Professional", Type: "knowledge",
	},
	"street": {
		Name: "Street", Type: "knowledge",
	},
}

// DataSkills contains active skills keyed by their ID (lowercase with underscores)
var DataSkills = map[string]Skill{
	"aeronautics_mechanic": {
		Name:       "Aeronautics Mechanic",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Engineering"}[0],
		Specs: &Specs{
			Spec: []string{"Aerospace", "Fixed Wing", "LTA (blimp)", "Rotary Wing", "Tilt Wing", "Vector Thrust"},
		},
		Page: "143",
	},
	"alchemy": {
		Name:       "Alchemy",
		Attribute:  "MAG",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Enchanting"}[0],
		Specs: &Specs{
			Spec: []string{"Combat", "Command", "Contact", "Detection", "Health", "Illusion", "Manipulation", "Time", "[Trigger]"},
		},
		Page: "142",
	},
	"animal_handling": {
		Name:       "Animal Handling",
		Attribute:  "CHA",
		Category:   "Technical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Herding", "Riding", "Training", "[Animal Type]"},
		},
		Page: "143",
	},
	"arcana": {
		Name:       "Arcana",
		Attribute:  "LOG",
		Category:   "Pseudo-Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Focus Design", "Magical Artifacts", "Spell Design", "Spirit Formula", "Spirit Theory"},
		},
		Page: "142",
	},
	"archery": {
		Name:       "Archery",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Bow", "Crossbow", "Non-Standard Ammunition", "Slingshot"},
		},
		Page: "130",
	},
	"armorer": {
		Name:       "Armorer",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Armor", "Artillery", "Explosives", "Firearms", "Melee Weapons", "Heavy Weapons", "Weapon Accessories"},
		},
		Page: "143",
	},
	"artificing": {
		Name:       "Artificing",
		Attribute:  "MAG",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Enchanting"}[0],
		Specs: &Specs{
			Spec: []string{"Focus Analysis", "[Focus Type]"},
		},
		Page: "142",
	},
	"artisan": {
		Name:       "Artisan",
		Attribute:  "INT",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Carpentry", "Cooking", "Drawing", "Sculpting", "Fashion", "Writing", "[Discipline]"},
		},
		Page: "143",
	},
	"assensing": {
		Name:       "Assensing",
		Attribute:  "INT",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Aura Reading", "Astral Signatures", "Psychometry", "[Aura Type]"},
		},
		Page: "142",
	},
	"astral_combat": {
		Name:       "Astral Combat",
		Attribute:  "WIL",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Magicians", "Mana Barriers", "Spirits", "[Weapon Focus Type]", "[Other Opponent Type]"},
		},
		Page: "142",
	},
	"automatics": {
		Name:       "Automatics",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Firearms"}[0],
		Specs: &Specs{
			Spec: []string{"Assault Rifles", "Cyber-Implant", "Machine Pistols", "Submachine Guns", "Carbines"},
		},
		Page: "130",
	},
	"automotive_mechanic": {
		Name:       "Automotive Mechanic",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Engineering"}[0],
		Specs: &Specs{
			Spec: []string{"Hover", "Tracked", "Walker", "Wheeled"},
		},
		Page: "143",
	},
	"banishing": {
		Name:       "Banishing",
		Attribute:  "MAG",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Conjuring"}[0],
		Specs: &Specs{
			Spec: []string{"Spirits of Air", "Spirits of Beasts", "Spirits of Earth", "Spirits of Fire", "Spirits of Man", "Spirits of Water", "Guardian Spirit", "Guidance Spirit", "Plant Spirit", "Task Spirit"},
		},
		Page: "142",
	},
	"binding": {
		Name:       "Binding",
		Attribute:  "MAG",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Conjuring"}[0],
		Specs: &Specs{
			Spec: []string{"Spirits of Air", "Spirits of Beasts", "Spirits of Earth", "Spirits of Fire", "Spirits of Man", "Spirits of Water", "Guardian Spirit", "Guidance Spirit", "Plant Spirit", "Task Spirit"},
		},
		Page: "142",
	},
	"biotechnology": {
		Name:       "Biotechnology",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Biotech"}[0],
		Specs: &Specs{
			Spec: []string{"Bioinformatics", "Bioware", "Cloning", "Gene Therapy", "Vat Maintenance"},
		},
		Page: "144",
	},
	"blades": {
		Name:       "Blades",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Close Combat"}[0],
		Specs: &Specs{
			Spec: []string{"Axes", "Knives", "Swords", "Parrying"},
		},
		Page: "130",
	},
	"chemistry": {
		Name:       "Chemistry",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Analytical", "Biochemistry", "Drugs", "Inorganic", "Organic", "Physical", "Toxins"},
		},
		Page: "144",
	},
	"clubs": {
		Name:       "Clubs",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Close Combat"}[0],
		Specs: &Specs{
			Spec: []string{"Batons", "Hammers", "Saps", "Staves", "Parrying"},
		},
		Page: "131",
	},
	"compiling": {
		Name:       "Compiling",
		Attribute:  "RES",
		Category:   "Resonance Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Tasking"}[0],
		Specs: &Specs{
			Spec: []string{"[Sprite Type]"},
		},
		Page: "143",
	},
	"computer": {
		Name:       "Computer",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Electronics"}[0],
		Specs: &Specs{
			Spec: []string{"Edit File", "Matrix Perception", "Matrix Search", "[Computer Matrix Action]"},
		},
		Page: "144",
	},
	"con": {
		Name:       "Con",
		Attribute:  "CHA",
		Category:   "Social Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Acting"}[0],
		Specs: &Specs{
			Spec: []string{"Fast Talk", "Seduction"},
		},
		Page: "138",
	},
	"counterspelling": {
		Name:       "Counterspelling",
		Attribute:  "MAG",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Sorcery"}[0],
		Specs: &Specs{
			Spec: []string{"Combat", "Detection", "Health", "Illusion", "Manipulation"},
		},
		Page: "142",
	},
	"cybercombat": {
		Name:       "Cybercombat",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Cracking"}[0],
		Specs: &Specs{
			Spec: []string{"Devices", "Grids", "IC", "Personas", "Sprites", "[Target Type]"},
		},
		Page: "144",
	},
	"cybertechnology": {
		Name:       "Cybertechnology",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Biotech"}[0],
		Specs: &Specs{
			Spec: []string{"Bodyware", "Cyberlimbs", "Headware", "Nanoware", "Repair"},
		},
		Page: "144",
	},
	"decompiling": {
		Name:       "Decompiling",
		Attribute:  "RES",
		Category:   "Resonance Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Tasking"}[0],
		Specs: &Specs{
			Spec: []string{"[Sprite Type]"},
		},
		Page: "143",
	},
	"demolitions": {
		Name:       "Demolitions",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Commercial Explosives", "Defusing", "Improvised Explosives", "Plastic Explosives"},
		},
		Page: "144",
	},
	"disenchanting": {
		Name:       "Disenchanting",
		Attribute:  "MAG",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Enchanting"}[0],
		Specs: &Specs{
			Spec: []string{"[Type]"},
		},
		Page: "142",
	},
	"disguise": {
		Name:       "Disguise",
		Attribute:  "INT",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Stealth"}[0],
		Specs: &Specs{
			Spec: []string{"Camouflage", "Cosmetic", "Theatrical", "Trideo & Video"},
		},
		Page: "133",
	},
	"diving": {
		Name:       "Diving",
		Attribute:  "BOD",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Arctic", "Cave", "Commercial", "Controlled Hyperventilation", "Liquid Breathing Apparatus", "Military", "Mixed Gas", "Oxygen Extraction", "SCUBA", "[Other Breathing Apparatus]", "[Other Condition]"},
		},
		Page: "133",
	},
	"electronic_warfare": {
		Name:       "Electronic Warfare",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Cracking"}[0],
		Specs: &Specs{
			Spec: []string{"Communications", "Encryption", "Jamming", "Sensor Operations", "[Electronic Warfare Matrix Action]"},
		},
		Page: "144",
	},
	"escape_artist": {
		Name:       "Escape Artist",
		Attribute:  "AGI",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Contortionism", "Cuffs", "Ropes", "Zip Ties", "[Other Restraint]"},
		},
		Page: "133",
	},
	"etiquette": {
		Name:       "Etiquette",
		Attribute:  "CHA",
		Category:   "Social Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Influence"}[0],
		Specs: &Specs{
			Spec: []string{"Catholic Church", "Corporate", "High Society", "Mafia", "Magic", "Matrix", "Media", "Mercenary", "Street", "Yakuza", "[Culture or Subculture]"},
		},
		Page: "138",
	},
	"exotic_melee_weapon": {
		Name:       "Exotic Melee Weapon",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs:      nil,
		Exotic:     &[]bool{true}[0],
		Page:       "131",
	},
	"exotic_ranged_weapon": {
		Name:       "Exotic Ranged Weapon",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Blowguns", "Gyrojet Pistols", "Flamethrowers", "Lasers", "Spidersilk"},
		},
		Exotic: &[]bool{true}[0],
		Page:   "131",
	},
	"pilot_exotic_vehicle": {
		Name:       "Pilot Exotic Vehicle",
		Attribute:  "REA",
		Category:   "Vehicle Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Festo Pigeon 2.0"},
		},
		Exotic: &[]bool{true}[0],
		Page:   "131",
	},
	"first_aid": {
		Name:       "First Aid",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Biotech"}[0],
		Specs: &Specs{
			Spec: []string{"Broken Bones", "Burns", "Gunshot Wounds", "Resuscitation", "[Type of Treatment]"},
		},
		Page: "144",
	},
	"flight": {
		Name:       "Flight",
		Attribute:  "AGI",
		Category:   "Physical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Athletics"}[0],
		Specs: &Specs{
			Spec: []string{"Desert", "Distance", "Sprinting", "Urban", "Wilderness", "[Terrain]"},
		},
		Page:                "394",
		RequiresFlyMovement: &[]bool{true}[0],
	},
	"forgery": {
		Name:       "Forgery",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Counterfeiting", "Credstick Forgery", "False ID", "Image Doctoring", "Paper Forgery"},
		},
		Page: "144",
	},
	"free_fall": {
		Name:       "Free-Fall",
		Attribute:  "BOD",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"BASE Jumping", "Break-Fall", "Bungee", "HALO", "Low Altitude", "Parachute", "Rappelling", "Static Line", "Wingsuit", "Zipline"},
		},
		Page: "133",
	},
	"gunnery": {
		Name:       "Gunnery",
		Attribute:  "AGI",
		Category:   "Vehicle Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Artillery", "Ballistic", "Energy", "Guided Missile", "Rocket"},
		},
		Page: "146",
	},
	"gymnastics": {
		Name:       "Gymnastics",
		Attribute:  "AGI",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Athletics"}[0],
		Specs: &Specs{
			Spec: []string{"Balance", "Climbing", "Dance", "Dodging", "Leaping", "Parkour", "Rolling"},
		},
		Page: "133",
	},
	"hacking": {
		Name:       "Hacking",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Cracking"}[0],
		Specs: &Specs{
			Spec: []string{"Devices", "Files", "Hosts", "Personas"},
		},
		Page: "145",
	},
	"hardware": {
		Name:       "Hardware",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Electronics"}[0],
		Specs: &Specs{
			Spec: []string{"Commlinks", "Cyberdecks", "Jack Out", "Smartguns", "[Hardware Type]", "[Hardware Matrix Action]"},
		},
		Page: "145",
	},
	"heavy_weapons": {
		Name:       "Heavy Weapons",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Assault Cannons", "Grenade Launchers", "Guided Missiles", "Machine Guns", "Rocket Launchers"},
		},
		Page: "132",
	},
	"impersonation": {
		Name:       "Impersonation",
		Attribute:  "CHA",
		Category:   "Social Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Acting"}[0],
		Specs: &Specs{
			Spec: []string{"Dwarf", "Elf", "Human", "Ork", "Troll"},
		},
		Page: "138",
	},
	"industrial_mechanic": {
		Name:       "Industrial Mechanic",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Engineering"}[0],
		Specs: &Specs{
			Spec: []string{"Electrical Power Systems", "Hydraulics", "HVAC", "Industrial Robotics", "Structural", "Welding"},
		},
		Page: "145",
	},
	"instruction": {
		Name:       "Instruction",
		Attribute:  "CHA",
		Category:   "Social Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"[Active or Knowledge Skill Category]"},
		},
		Page: "138",
	},
	"intimidation": {
		Name:       "Intimidation",
		Attribute:  "CHA",
		Category:   "Social Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Interrogation", "Mental", "Physical", "Torture"},
		},
		Page: "139",
	},
	"leadership": {
		Name:       "Leadership",
		Attribute:  "CHA",
		Category:   "Social Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Influence"}[0],
		Specs: &Specs{
			Spec: []string{"Command", "Direct", "Inspire", "Rally"},
		},
		Page: "139",
	},
	"locksmith": {
		Name:       "Locksmith",
		Attribute:  "AGI",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Combination", "Keypad", "Maglock", "Tumbler", "Voice Recognition", "[Lock Type]"},
		},
		Page: "145",
	},
	"longarms": {
		Name:       "Longarms",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Firearms"}[0],
		Specs: &Specs{
			Spec: []string{"Extended-Range Shots", "Long-Range Shots", "Shotguns", "Sniper Rifles", "Sporting Rifles"},
		},
		Page: "132",
	},
	"medicine": {
		Name:       "Medicine",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Biotech"}[0],
		Specs: &Specs{
			Spec: []string{"Cosmetic Surgery", "Extended Care", "Implant Surgery", "Magical Health", "Organ Culture", "Trauma Surgery"},
		},
		Page: "145",
	},
	"nautical_mechanic": {
		Name:       "Nautical Mechanic",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Engineering"}[0],
		Specs: &Specs{
			Spec: []string{"Motorboat", "Sailboat", "Ship", "Submarine"},
		},
		Page: "145",
	},
	"navigation": {
		Name:       "Navigation",
		Attribute:  "INT",
		Category:   "Technical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Outdoors"}[0],
		Specs: &Specs{
			Spec: []string{"Augmented Reality Markers", "Celestial", "Compass", "Maps", "GPS"},
		},
		Page: "145",
	},
	"negotiation": {
		Name:       "Negotiation",
		Attribute:  "CHA",
		Category:   "Social Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Influence"}[0],
		Specs: &Specs{
			Spec: []string{"Bargaining", "Contracts", "Diplomacy"},
		},
		Page: "139",
	},
	"palming": {
		Name:       "Palming",
		Attribute:  "AGI",
		Category:   "Physical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Stealth"}[0],
		Specs: &Specs{
			Spec: []string{"Legerdemain", "Pickpocket", "Pilfering"},
		},
		Page: "133",
	},
	"perception": {
		Name:       "Perception",
		Attribute:  "INT",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Hearing", "Numinous Perception", "Scent", "Searching", "Taste", "Touch", "Visual"},
		},
		Page: "133",
	},
	"performance": {
		Name:       "Performance",
		Attribute:  "CHA",
		Category:   "Social Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Acting"}[0],
		Specs: &Specs{
			Spec: []string{"Acting", "Comedy", "Dance", "Presentation", "[Musical Instrument]"},
		},
		Page: "139",
	},
	"pilot_aerospace": {
		Name:       "Pilot Aerospace",
		Attribute:  "REA",
		Category:   "Vehicle Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Deep Space", "Launch Craft", "Remote Operation", "Semiballistic", "Suborbital"},
		},
		Page: "146",
	},
	"pilot_aircraft": {
		Name:       "Pilot Aircraft",
		Attribute:  "REA",
		Category:   "Vehicle Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Fixed-Wing", "Lighter-Than-Air", "Remote Operation", "Rotary Wing", "Tilt Wing", "Vectored Thrust"},
		},
		Page: "147",
	},
	"pilot_ground_craft": {
		Name:       "Pilot Ground Craft",
		Attribute:  "REA",
		Category:   "Vehicle Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Bike", "Hovercraft", "Remote Operation", "Tracked", "Wheeled"},
		},
		Page: "147",
	},
	"pilot_walker": {
		Name:       "Pilot Walker",
		Attribute:  "REA",
		Category:   "Vehicle Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Biped", "Multiped", "Quadruped", "Remote Operation"},
		},
		Page: "147",
	},
	"pilot_watercraft": {
		Name:       "Pilot Watercraft",
		Attribute:  "REA",
		Category:   "Vehicle Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Hydrofoil", "Motorboat", "Remote Operation", "Sail", "Ship", "Submarine"},
		},
		Page: "147",
	},
	"pistols": {
		Name:       "Pistols",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Firearms"}[0],
		Specs: &Specs{
			Spec: []string{"Holdouts", "Revolvers", "Semi-Automatics", "Tasers"},
		},
		Page: "132",
	},
	"registering": {
		Name:       "Registering",
		Attribute:  "RES",
		Category:   "Resonance Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Tasking"}[0],
		Specs: &Specs{
			Spec: []string{"[Sprite Type]"},
		},
		Page: "143",
	},
	"ritual_spellcasting": {
		Name:       "Ritual Spellcasting",
		Attribute:  "MAG",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Sorcery"}[0],
		Specs: &Specs{
			Spec: []string{"[Keyword]"},
		},
		Page: "142",
	},
	"running": {
		Name:       "Running",
		Attribute:  "STR",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Athletics"}[0],
		Specs: &Specs{
			Spec: []string{"Desert", "Distance", "Sprinting", "Urban", "Wilderness", "[Terrain]"},
		},
		Page:                   "133",
		RequiresGroundMovement: &[]bool{true}[0],
	},
	"sneaking": {
		Name:       "Sneaking",
		Attribute:  "AGI",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Stealth"}[0],
		Specs: &Specs{
			Spec: []string{"Desert", "Jungle", "Urban", "Vehicle", "Wilderness", "[Terrain]"},
		},
		Page: "133",
	},
	"software": {
		Name:       "Software",
		Attribute:  "LOG",
		Category:   "Technical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Electronics"}[0],
		Specs: &Specs{
			Spec: []string{"Data Bombs", "[Complex Form]", "[Program Type]", "[Software Matrix Action]"},
		},
		Page: "145",
	},
	"spellcasting": {
		Name:       "Spellcasting",
		Attribute:  "MAG",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Sorcery"}[0],
		Specs: &Specs{
			Spec: []string{"Combat", "Detection", "Health", "Illusion", "Manipulation"},
		},
		Page: "143",
	},
	"summoning": {
		Name:       "Summoning",
		Attribute:  "MAG",
		Category:   "Magical Active",
		Default:    "False",
		Source:     "SR5",
		SkillGroup: &[]string{"Conjuring"}[0],
		Specs: &Specs{
			Spec: []string{"Spirits of Air", "Spirits of Beasts", "Spirits of Earth", "Spirits of Fire", "Spirits of Man", "Spirits of Water", "Guardian Spirit", "Guidance Spirit", "Plant Spirit", "Task Spirit"},
		},
		Page: "143",
	},
	"survival": {
		Name:       "Survival",
		Attribute:  "WIL",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Outdoors"}[0],
		Specs: &Specs{
			Spec: []string{"Desert", "Forest", "Jungle", "Mountain", "Polar", "Urban", "[Terrain]"},
		},
		Page: "133",
	},
	"swimming": {
		Name:       "Swimming",
		Attribute:  "STR",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Athletics"}[0],
		Specs: &Specs{
			Spec: []string{"Dash", "Long Distance"},
		},
		Page:                 "134",
		RequiresSwimMovement: &[]bool{true}[0],
	},
	"throwing_weapons": {
		Name:       "Throwing Weapons",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Aerodynamic", "Blades", "Non-Aerodynamic"},
		},
		Page: "132",
	},
	"tracking": {
		Name:       "Tracking",
		Attribute:  "INT",
		Category:   "Physical Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Outdoors"}[0],
		Specs: &Specs{
			Spec: []string{"Desert", "Forest", "Jungle", "Mountain", "Polar", "Urban", "[Terrain]"},
		},
		Page: "134",
	},
	"unarmed_combat": {
		Name:       "Unarmed Combat",
		Attribute:  "AGI",
		Category:   "Combat Active",
		Default:    "True",
		Source:     "SR5",
		SkillGroup: &[]string{"Close Combat"}[0],
		Specs: &Specs{
			Spec: []string{"Blocking", "Cyber Implants", "Subduing Combat", "[Martial Art]"},
		},
		Page: "132",
	},
}

// DataKnowledgeSkills contains knowledge skills keyed by their ID (lowercase with underscores)
var DataKnowledgeSkills = map[string]Skill{
	"administration": {
		Name:       "Administration",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Corporate", "Government", "Religious"},
		},
	},
	"alchemy": {
		Name:       "Alchemy",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Combat", "Command", "Contact", "Detection", "Health", "Illusion", "Manipulation", "Time", "[Trigger]"},
		},
	},
	"alcohol": {
		Name:       "Alcohol",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Beers", "Coolers", "Hard Liquor", "Wines", "Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan", "N. America", "S. America", "Central America", "Antarctica", "Africa", "Western Europe", "Eastern Europe", "Northern Europe", "Asia - Pacific", "Asia - Minor", "Middle East", "Australia"},
		},
	},
	"anishinaabe": {
		Name:       "Anishinaabe",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"anatomy": {
		Name:       "Anatomy",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"arabic": {
		Name:       "Arabic",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"architecture": {
		Name:       "Architecture",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Art Nouveau", "Brutalist", "Commercial", "Residential", "Elven", "Orkish", "Medieval", "Gothic", "Renaissance", "Baroque", "Victorian", "Neo-Classical", "Modern", "High-Tech"},
		},
	},
	"area_knowledge_atlanta": {
		Name:       "Area Knowledge: Atlanta",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"area_knowledge_cheyenne": {
		Name:       "Area Knowledge: Cheyenne",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"area_knowledge_chicago": {
		Name:       "Area Knowledge: Chicago",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Chicago Matrix", "Containment Zone", "Matrix Hot Spots", "Safe Houses"},
		},
	},
	"area_knowledge_denver": {
		Name:       "Area Knowledge: Denver",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"area_knowledge_fdc": {
		Name:       "Area Knowledge: FDC",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"area_knowledge_hong_kong": {
		Name:       "Area Knowledge: Hong Kong",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"area_knowledge_la": {
		Name:       "Area Knowledge: LA",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"area_knowledge_manhattan": {
		Name:       "Area Knowledge: Manhattan",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"area_knowledge_neo_tokyo": {
		Name:       "Area Knowledge: Neo-Tokyo",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"area_knowledge_portland": {
		Name:       "Area Knowledge: Portland",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"area_knowledge_seattle": {
		Name:       "Area Knowledge: Seattle",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Auburn", "Bellevue", "Council Island", "Downtown", "Everett", "Fort Lewis", "Matrix Hot Spots", "Puyallup", "Redmond", "Renton", "Safe Houses", "Snohomish", "Outremer", "Seattle Matrix", "Salish-Shide", "Tacoma"},
		},
	},
	"art": {
		Name:       "Art",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Da Vinci", "Monet", "Matisse", "Michelangelo", "Picasso", "Rembrandt", "Van Gogh", "N. America", "S. America", "Central America", "Antarctica", "Africa", "Western Europe", "Eastern Europe", "Northern Europe", "Asia - Pacific", "Asia - Minor", "Middle East", "Australia"},
		},
	},
	"athabaskan": {
		Name:       "Athabaskan",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"bars_and_clubs": {
		Name:       "Bars and Clubs",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Atlanta", "Awakened", "Biker", "Cheyenne", "Chicago", "Corporate", "Denver", "Dwarf", "Elf", "FDC", "Gay", "High-Class", "Hotel", "Jazz", "Hong Kong", "LA", "Low-Class", "Mafia", "Matrix", "Manhattan", "Ork", "Portland", "Piano", "Pubs", "Quebec City", "Rock", "Sacramento", "Saskatoon", "Seattle", "Sports", "Surge", "Triad", "Troll", "Vory", "Yakuza"},
		},
	},
	"bengali": {
		Name:       "Bengali",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"biology": {
		Name:       "Biology",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Anatomy", "Microbiology", "Physiology", "Parazoology"},
		},
	},
	"zoology": {
		Name:       "Zoology",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"black_markets": {
		Name:       "Black Markets",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan"},
		},
	},
	"btls": {
		Name:       "BTLs",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Bunraku", "Calhots", "Crime Fantasy", "Drug Emulation", "Historical Fantasy", "Hot-Sim Pornography", "Mind Control Chips", "Power Fantasy", "Reality Enhancer", "Revenge Fantasy", "Snuff", "Soma Chips", "Synesthesia", "Ultraviolence"},
		},
	},
	"bulgarian": {
		Name:       "Bulgarian",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"business": {
		Name:       "Business",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Budgeting", "Compliance", "Digital Accountancy", "Distribution", "Finance", "Manufacturing", "Megacorp", "People Management", "Project Management", "Reporting", "Retail", "Supply and Demand", "Small Business", "Time Management"},
		},
	},
	"cantonese": {
		Name:       "Cantonese",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"charity_shelters": {
		Name:       "Charity Shelters",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City"},
		},
	},
	"chemistry": {
		Name:       "Chemistry",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Industrial", "Inorganic", "Organic", "Pharmaceuticals"},
		},
	},
	"combat_tactics": {
		Name:       "Combat Tactics",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Ambush", "Guerrilla", "Hostage Rescue", "Magic", "Anti-Magic", "Open Field", "Outer Space", "Terror", "Underwater", "Urban", "Wilderness"},
		},
	},
	"critters": {
		Name:       "Critters",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Alligators", "Barracudas", "Bears", "Boars", "Chimpanzees", "Cockroaches", "Crows", "Deer", "Dogs", "Dolphins", "Domestic Cats", "Eagles", "Elephants", "Ferrets", "Giraffes", "Great Cats", "Horses", "Killer Whales", "Raccoons", "Rats", "Sea Lions", "Sharks", "Snakes", "Spiders", "Squids", "Wolves"},
		},
	},
	"croatian": {
		Name:       "Croatian",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"crook_hangouts": {
		Name:       "Crook Hangouts",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Atlanta", "Cheyenne", "Chicago", "Denver", "FDC", "High-Class", "Hong Kong", "LA", "Low-Class", "Manhattan", "Portland", "Quebec City", "Sacramento", "Seattle"},
		},
	},
	"danish": {
		Name:       "Danish",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"data_havens": {
		Name:       "Data Havens",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Hacking", "Magic", "Matrix", "Shadows", "N. America", "S. America", "Central America", "Antarctica", "Africa", "Western Europe", "Eastern Europe", "Northern Europe", "Asia - Pacific", "Asia - Minor", "Middle East", "Australia"},
		},
	},
	"diy": {
		Name:       "DIY",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Electronics", "Carpentry", "Plumbing", "Sewing"},
		},
	},
	"disease": {
		Name:       "Disease",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"drones": {
		Name:       "Drones",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Wheeled", "Walker", "Hovercraft", "Tracked"},
		},
	},
	"economics": {
		Name:       "Economics",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Micro-economics", "Macro-economics", "Corporate", "Tribal", "Underworld", "Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan", "N. America", "S. America", "Central America", "Antarctica", "Africa", "Western Europe", "Eastern Europe", "Northern Europe", "Asia - Pacific", "Asia - Minor", "Middle East", "Australia"},
		},
	},
	"engineering": {
		Name:       "Engineering",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Chemical", "Civil", "Electrical", "Mechanical", "Nuclear"},
		},
	},
	"english": {
		Name:       "English",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Cityspeak", "Creole", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"eskimo_aleut": {
		Name:       "Eskimo-Aleut",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"fashion": {
		Name:       "Fashion",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Harajuku Scene", "London Scene", "New York Scene", "Paris Scene"},
		},
	},
	"fashion_design": {
		Name:       "Fashion Design",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Harajuku Scene", "London Scene", "New York Scene", "Paris Scene"},
		},
	},
	"firearms": {
		Name:       "Firearms",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Accessories", "Ammunition", "Automatics", "Design", "Heavy Weapons", "History", "Longarms", "Modification", "Pistols"},
		},
	},
	"blade_design": {
		Name:       "Blade Design",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Accessories", "Axes", "Knives", "Swords", "Throwing Weapons", "History", "Modification"},
		},
	},
	"gun_trivia": {
		Name:       "Gun Trivia",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Accessories", "Ammunition", "Automatics", "Design", "Heavy Weapons", "History", "Longarms", "Modification", "Pistols"},
		},
	},
	"french": {
		Name:       "French",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Creole", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"gaming": {
		Name:       "Gaming",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Dawn of Atlantis", "Dark Eye", "Grand Larceny", "Killing Floor", "Paranormal Crisis", "Miracle Shooter", "Spectrum Delta", "SC IV: Protoss Gate", "World of Shadows", "Urban Brawl League 70", "Guild Ages"},
		},
	},
	"gangs": {
		Name:       "Gangs",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Ancients", "Area Boys", "Cirque du Sorciere", "Chaos Engine", "Cocotona", "Comando Verdge", "Cutters", "Desolation Angels", "First Nations", "Ghost Cartels", "Halloweeners", "Hell's Angels", "Iron Crosses", "Los Verdugos", "Los Angeles Ardientes", "Lynch Mob", "Merlyns", "Numbers Gang", "Spikes", "Steppin Wulfs", "Thunder Boys", "Yardies", "Vikings", "Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan"},
		},
	},
	"german": {
		Name:       "German",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"ghost_cartels": {
		Name:       "Ghost Cartels",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Turf", "Politics", "Signs", "History", "Organizations", "Safe Houses"},
		},
	},
	"hebrew": {
		Name:       "Hebrew",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"hindi_urdu": {
		Name:       "Hindi-Urdu",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"history": {
		Name:       "History",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Ancient", "Medieval", "Modern", "Art", "Corporate", "Military", "Political", "Religion", "Social", "Tribal", "Underworld", "Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan", "N. America", "S. America", "Central America", "Antarctica", "Africa", "Western Europe", "Eastern Europe", "Northern Europe", "Asia - Pacific", "Asia - Minor", "Middle East", "Australia"},
		},
	},
	"indonesian": {
		Name:       "Indonesian",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"infected": {
		Name:       "Infected",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"iroquoian": {
		Name:       "Iroquoian",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"italian": {
		Name:       "Italian",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"japanese": {
		Name:       "Japanese",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Cityspeak", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"korean": {
		Name:       "Korean",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"latin": {
		Name:       "Latin",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"literature": {
		Name:       "Literature",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Japanese", "Early Twentieth Century", "Science Fiction", "Poetry", "Fiction", "Romance", "N. America", "S. America", "Central America", "Antarctica", "Africa", "Western Europe", "Eastern Europe", "Northern Europe", "Asia - Pacific", "Asia - Minor", "Middle East", "Australia"},
		},
	},
	"mafia": {
		Name:       "Mafia",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Turf", "Politics", "Signs", "History", "Organizations", "Safe Houses"},
		},
	},
	"magic_traditions": {
		Name:       "Magic Traditions",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Adepts", "Shamans", "Mages", "Mystic Adepts"},
		},
	},
	"magical_theory_academic": {
		Name:       "Magical Theory (Academic)",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Sorcery", "Conjuring", "Enchanting", "Foci", "Astral World", "Metaplanes", "Initiation", "Mentor Spirits"},
		},
	},
	"magical_theory_street": {
		Name:       "Magical Theory (Street)",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Sorcery", "Conjuring", "Enchanting", "Foci", "Astral World", "Metaplanes", "Initiation", "Mentor Spirits"},
		},
	},
	"magical_security": {
		Name:       "Magical Security",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Government", "Military", "Private", "Home", "[Corporation]"},
		},
	},
	"magical_threats": {
		Name:       "Magical Threats",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Blood Magic", "Toxic Magic", "Insect Spirits", "Shadow Spirits"},
		},
	},
	"mandarin": {
		Name:       "Mandarin",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"mathematics": {
		Name:       "Mathematics",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Arithmetic", "Calculus", "Geometry", "Algebra", "Number Theory", "Game Theory", "Graph Theory", "Group Theory", "Combinatorics", "Statistics"},
		},
	},
	"matrix_games": {
		Name:       "Matrix Games",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Astral Dreams: Legend of Tenku", "Awakening: 1949", "Beat the Market", "Dawn of Atlantis III", "Dragon Storm", "Fermat's Last Hermetic Equation", "Galaxy Ten", "Grand Larceny", "Killing Floor", "Life's a Bitch", "Miracle Shooter", "Noir Confidential", "Run, Run Runner", "Shadowrun Online", "The Seelie Court"},
		},
	},
	"mechanics": {
		Name:       "Mechanics",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Automotive", "Aeronautic", "Industrial", "Nautical"},
		},
	},
	"military": {
		Name:       "Military",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Air Force", "Army", "Coast Guard", "Marines", "Military Magic", "Navy", "Special Forces"},
		},
	},
	"foreign_military": {
		Name:       "Foreign Military",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Air Force", "Army", "Coast Guard", "Marines", "Military Magic", "Navy", "Special Forces"},
		},
	},
	"military_vehicles": {
		Name:       "Military Vehicles",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Air Force", "Army", "Coast Guard", "Marines", "Navy", "Special Forces"},
		},
	},
	"mixed_unit_tactics": {
		Name:       "Mixed Unit Tactics",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Aerial/Aircraft", "Armored Infantry", "Artillery", "Naval", "Mechanized Infantry", "Standard Infantry", "[Single Unit Type]"},
		},
	},
	"nan_military": {
		Name:       "NAN Military",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Air Force", "Army", "Coast Guard", "Marines", "Military Magic", "Navy", "Special Forces"},
		},
	},
	"peacekeepers": {
		Name:       "Peacekeepers",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Air Force", "Army", "Coast Guard", "Marines", "Military Magic", "Navy", "Special Forces"},
		},
	},
	"tir_military_vehicles": {
		Name:       "Tir Military Vehicles",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Air Force", "Army", "Coast Guard", "Marines", "Navy", "Special Forces"},
		},
	},
	"club_music": {
		Name:       "Club Music",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Astral Rock", "Electron Wave", "Goblin Rock", "Powernoize", "Rockabilly", "Sinthcore", "Wizpunk", "Trash Metal Troll", "Retro Gothic", "Elven Rap", "Neo-J Pop", "Nova K Rock", "Beatpace", "Bugstomp", "Fractal", "Plex"},
		},
	},
	"national_threats": {
		Name:       "National Threats",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Denver", "Hong Kong", "Seattle", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan"},
		},
	},
	"news": {
		Name:       "News",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Business", "Entertainment", "Health", "Science/Environment", "Sports", "Technology", "Underworld", "Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan", "N. America", "S. America", "Central America", "Antarctica", "Africa", "Western Europe", "Eastern Europe", "Northern Europe", "Asia - Pacific", "Asia - Minor", "Middle East", "Australia"},
		},
	},
	"orzet": {
		Name:       "Or'zet",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"parazoology": {
		Name:       "Parazoology",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Spirits", "N. America", "S. America", "Central America", "Antarctica", "Africa", "Western Europe", "Eastern Europe", "Northern Europe", "Asia - Pacific", "Asia - Minor", "Middle East", "Australia"},
		},
	},
	"persian": {
		Name:       "Persian",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"polish": {
		Name:       "Polish",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"politics": {
		Name:       "Politics",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Corporate", "Military", "Social", "Tribal", "Underworld", "Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan", "N. America", "S. America", "Central America", "Antarctica", "Africa", "Western Europe", "Eastern Europe", "Northern Europe", "Asia - Pacific", "Asia - Minor", "Middle East", "Australia"},
		},
	},
	"portuguese": {
		Name:       "Portuguese",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"punjabi": {
		Name:       "Punjabi",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"religion": {
		Name:       "Religion",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Islam", "Judaism", "Buddhism", "Christianity", "Hinduism", "Zoroastrianism", "Shinto", "Paganism", "Taoism"},
		},
	},
	"russian": {
		Name:       "Russian",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"security_companies": {
		Name:       "Security Companies",
		Attribute:  "LOG",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Lone Star", "Knight Errant", "Hard Corps", "Minutemen Security", "Seattle Sec Corps"},
		},
	},
	"security_design": {
		Name:       "Security Design",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Bank", "Corporate", "Government", "Home", "Public Event", "Vehicle", "VIP"},
		},
	},
	"security_tactics": {
		Name:       "Security Tactics",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Corporate", "Crimson Rush", "Entertainment", "Government", "Security Company", "Rapid Response", "Border Patrol", "Customs", "VIP"},
		},
	},
	"sioux": {
		Name:       "Sioux",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"small_unit_tactics": {
		Name:       "Small Unit Tactics",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Arctic", "Desert", "Forest", "Jungle", "Mountains", "Urban", "[Terrain]"},
		},
	},
	"spanish": {
		Name:       "Spanish",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"sperethiel": {
		Name:       "Sperethiel",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"spirits": {
		Name:       "Spirits",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Beast", "Earth", "Fire", "Guardian", "Guidance", "Man", "Plant", "Task", "Water", "Watcher"},
		},
	},
	"sports": {
		Name:       "Sports",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Baseball", "Basketball", "Boxing", "Combat Biking", "Court Ball", "Drone Racing", "Duello Magicae", "E-Sports", "Football", "Hockey", "Hoverball", "Hurling", "Piloted Racing", "MMA", "Soccer", "Stickball", "UFC", "Underground Fighting", "Urban Brawl", "Wrestling"},
		},
	},
	"sprawl_life": {
		Name:       "Sprawl Life",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Scavenging", "Soup Kitchens", "Squats", "Street Docs", "Street Rumors"},
		},
	},
	"smuggler_routes": {
		Name:       "Smuggler Routes",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan"},
		},
	},
	"smuggler_safe_houses": {
		Name:       "Smuggler Safe Houses",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan"},
		},
	},
	"street_drugs": {
		Name:       "Street Drugs",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Betel", "Binaural Beats", "BTLs", "Cram", "Deepweed", "Novacoke", "Spike", "Tempo"},
		},
	},
	"strategy": {
		Name:       "Strategy",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Logistics", "Reconnaissance", "Offensive", "Defensive"},
		},
	},
	"syndicates": {
		Name:       "Syndicates",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Personalities", "Ghost Cartels", "Mafia", "Triad", "Yakuza", "Vory", "Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan"},
		},
	},
	"thai": {
		Name:       "Thai",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"triads": {
		Name:       "Triads",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Turf", "Politics", "Signs", "History", "Organizations", "Safe Houses"},
		},
	},
	"trids": {
		Name:       "Trids",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Action", "Comedy", "Cop", "Documentary", "Drama", "Fantasy", "Horror", "Rom-Com", "Sci-fi", "Thriller"},
		},
	},
	"trideo_shows": {
		Name:       "Trideo Shows",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Action", "Comedy", "Cop", "Documentary", "Drama", "Fantasy", "Game Shows", "Horror", "Reality Shows", "Rom-Com", "Sci-fi", "Thriller", "BattleRun", "Berlin Nights", "Blood Runners", "The Coffee Clutch", "DASH: Star Loner!", "Debonair Dave", "Desert Wars", "Dessert Wars", "Dis is Uz", "Granny Sweetspell's Magical Kitchen", "Karl Kombatmage", "Reloaded", "The Master Wizard", "Max Wild", "A Murder to Kill For", "Ningyo: The Digital", "Geisha Diaries", "On Point", "Ork and Mindy", "Polar Wars", "Porky's Landing", "Red Samurai Run", "The Runners", "Seas of Death: The Tale of Kane", "Space Fleet", "Street by Street", "Temple Terror", "The Wrong Shift"},
		},
	},
	"turkish": {
		Name:       "Turkish",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"undead": {
		Name:       "Undead",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"underworld": {
		Name:       "Underworld",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Arson", "Black Magic", "Black Market Pipeline", "Blackmail", "BTL", "Counterfeiting", "Drugs", "Drug Dealers", "Fencing", "Financial Crime", "Fixing", "Forgery", "Gambling", "Grifting", "Hijacking", "Illegal Goods", "Kidnapping", "Loansharking", "Local Runners", "Medicine", "Matrix Crime", "Money Laundering", "Organleggers", "Pornography", "Prostitution", "Protection", "Robbery", "Smugglers", "Smuggling", "Talislegger", "Tamanous groups", "White Collar", "Wetwork"},
		},
	},
	"vory": {
		Name:       "Vory",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Turf", "Politics", "Signs", "History", "Organizations", "Safe Houses"},
		},
	},
	"wu": {
		Name:       "Wu",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"xiang": {
		Name:       "Xiang",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"yakuza": {
		Name:       "Yakuza",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Turf", "Politics", "Signs", "History", "Organizations", "Safe Houses"},
		},
	},
	"astronomy": {
		Name:       "Astronomy",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Comets", "Mars", "Moon", "Stars", "[category]"},
		},
	},
	"awakened_hangouts": {
		Name:       "Awakened Hangouts",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan"},
		},
	},
	"city_speak": {
		Name:       "City Speak",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]"},
		},
	},
	"classical_music": {
		Name:       "Classical Music",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Ballet", "Baroque", "Chamber Music", "Medieval", "Opera", "Orchestral", "Renaissance", "[music style]"},
		},
	},
	"codes": {
		Name:       "Codes",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Magical", "Matrix", "Physical", "Mathematical"},
		},
	},
	"connoisseur": {
		Name:       "Connoisseur",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Fine Arts", "Beers", "Cuisines", "Cuisine (Aztlaner)", "Cuisine (French)", "Cuisine (Italian)", "Teas", "Wines", "Wine (Elven)", "[Cuisine, Wine]"},
		},
	},
	"corporation_ares_macrotechnology": {
		Name:       "Corporation: Ares Macrotechnology",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Damien Knight", "Ares Arms", "AresSpace", "Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_aztechnology": {
		Name:       "Corporation: Aztechnology",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_evo": {
		Name:       "Corporation: Evo",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"CrashCart Medical Services", "Red Star Clinics", "Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_horizon_group": {
		Name:       "Corporation: Horizon Group",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_mitsuhama_computer_technologies": {
		Name:       "Corporation: Mitsuhama Computer Technologies",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Magical Goods and Services", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_neonet": {
		Name:       "Corporation: NeoNET",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_renraku_computer_systems": {
		Name:       "Corporation: Renraku Computer Systems",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Haruhiko Nakada", "Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_saeder_krupp": {
		Name:       "Corporation: Saeder-Krupp",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Saeder-Krupp Heavy Industries", "Saeder-Krupp Prime", "Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_shiawase": {
		Name:       "Corporation: Shiawase",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_wuxing_inc": {
		Name:       "Corporation: Wuxing, Inc.",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Magical Goods and Services", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_brackhaven_investments": {
		Name:       "Corporation: Brackhaven Investments",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Kenneth Brackhaven", "Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_docwagon": {
		Name:       "Corporation: DocWagon",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Denny Coleman", "Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_federated_boeing": {
		Name:       "Corporation: Federated-Boeing",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_gaeatronics": {
		Name:       "Corporation: Gaeatronics",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_global_technologies": {
		Name:       "Corporation: Global Technologies",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_knight_errant": {
		Name:       "Corporation: Knight Errant",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Damien Knight", "Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_kong_walmart": {
		Name:       "Corporation: Kong-Walmart",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_lone_star_security_services": {
		Name:       "Corporation: Lone Star Security Services",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Chicago Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_regency_megamedia": {
		Name:       "Corporation: Regency MegaMedia",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_stuffer_shack": {
		Name:       "Corporation: Stuffer Shack",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_telestrian_industries_corporation": {
		Name:       "Corporation: Telestrian Industries Corporation",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_universal_omnitech": {
		Name:       "Corporation: Universal Omnitech",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Ingersoll and Berkley", "Seattle Operations", "Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"corporation_zurich_orbit_gemeinschaft_bank_zog": {
		Name:       "Corporation: Zurich-Orbit Gemeinschaft Bank (ZOG)",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Corporate Finances", "Corporate Politics", "Corporate Rumors", "Corporate Security"},
		},
	},
	"creole": {
		Name:       "Creole",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]"},
		},
	},
	"cybertechnology": {
		Name:       "Cybertechnology",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Cyberware", "Cyberware Design", "SOTA"},
		},
	},
	"entertainment": {
		Name:       "Entertainment",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Classical Music", "Kaiju Monster Movies", "Music", "Neo-Classical Music", "Sports", "[Gambling]", "[Pornography]"},
		},
	},
	"fight_clubs": {
		Name:       "Fight Clubs",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Atlanta", "Cheyenne", "Chicago", "Denver", "Hong Kong", "LA", "Manhattan", "FDC", "Portland", "Seattle", "Saskatoon", "Sacramento", "Quebec City", "Algonkian-Manitou Council", "Athabaskan Council", "Amazonia", "Aztlan", "Caribbean League", "California Free State", "Pueblo Corporate Council", "CAS", "UCAS", "Quebec", "Salish-Shidhe Council", "Sioux", "Tir Tairngire", "Tsimshian Protectorate", "Yucatan"},
		},
	},
	"farming": {
		Name:       "Farming",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Organic", "Factory", "Awakened"},
		},
	},
	"forensics": {
		Name:       "Forensics",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Cleaning", "Thaumaturgic"},
		},
	},
	"foster_system": {
		Name:       "Foster System",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"UCAS", "CAS", "[Jurisdiction]"},
		},
	},
	"journalism": {
		Name:       "Journalism",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Investigative", "Editorial", "Print", "Trid"},
		},
	},
	"megacorp_law_street": {
		Name:       "Megacorp Law (Street)",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Contracts"},
		},
	},
	"law": {
		Name:       "Law",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Contracts"},
		},
	},
	"matrix": {
		Name:       "Matrix",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Host Design", "Host Networking"},
		},
	},
	"matrix_threats": {
		Name:       "Matrix Threats",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Protosapients", "Xenosapients", "Technocritters", "Dissonant Technomancers"},
		},
	},
	"magical_law": {
		Name:       "Magical Law",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Contracts"},
		},
	},
	"metahumans": {
		Name:       "Metahumans",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Dwarves", "Elves", "Humans", "Orks", "Trolls"},
		},
	},
	"medicine": {
		Name:       "Medicine",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Field Medicine", "Medical Advances", "Technology"},
		},
	},
	"psychology": {
		Name:       "Psychology",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Mental Illnesses", "Mental Reprogramming", "Xenosapient"},
		},
	},
	"sociology": {
		Name:       "Sociology",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Cultural", "Medical", "Behavioral", "Matrix", "Political"},
		},
	},
	"philosophy": {
		Name:       "Philosophy",
		Attribute:  "LOG",
		Category:   "Academic",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Christian", "Buddhist", "Taoist", "Confucian", "Kantian", "Socialist", "Fascist", "Utilitarian", "Existentialist", "Rationalist", "Anti-Rationalist"},
		},
	},
	"neo_classical_music": {
		Name:       "Neo-Classical Music",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Rock n Roll", "The (19)60's", "The (19)70's", "Early Millennial", "Mid-century", "[musical era]"},
		},
	},
	"organized_crime_chicago": {
		Name:       "Organized Crime: Chicago",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Turf", "Politics", "Signs", "History", "Organizations", "Safe Houses"},
		},
	},
	"police_procedures_professional": {
		Name:       "Police Procedures (Professional)",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Government", "Military Security Design", "Magical", "Matrix", "Military", "Physical", "Private", "Home", "[Corporation]"},
		},
	},
	"police_procedures_street": {
		Name:       "Police Procedures (Street)",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Government", "Military Security Design", "Magical", "Matrix", "Military", "Physical", "Private", "Home", "[Corporation]"},
		},
	},
	"security_procedures": {
		Name:       "Security Procedures",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Government", "Military Security Design", "Magical", "Matrix", "Military", "Physical", "Private", "Home", "[Corporation]"},
		},
	},
	"law_enforcement_procedures_professional": {
		Name:       "Law Enforcement Procedures (Professional)",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Government", "Magical", "Matrix", "Military", "Physical", "Private", "[Corporation]"},
		},
	},
	"law_enforcement_procedures_street": {
		Name:       "Law Enforcement Procedures (Street)",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Government", "Magical", "Matrix", "Military", "Physical", "Private", "[Corporation]"},
		},
	},
	"government_procedures": {
		Name:       "Government Procedures",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Magical", "Matrix", "Physical", "Bureaucratic"},
		},
	},
	"lone_star_procedures": {
		Name:       "Lone Star Procedures",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Government", "Magical", "Matrix", "Physical", "Home"},
		},
	},
	"politics_ucas": {
		Name:       "Politics: UCAS",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Presidential", "Congressional", "[state, party, lobby group]"},
		},
	},
	"popular_culture": {
		Name:       "Popular Culture",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs:      nil,
	},
	"popular_music": {
		Name:       "Popular Music",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Dwarven Punkbilly", "Modern Punk", "Feathercore", "Beatpace", "Bugstomp", "Fractal", "Plex", "[genre]"},
		},
	},
	"radical_groups": {
		Name:       "Radical Groups",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Alamos 20K", "Ex Pacis", "GreenWar", "Logos", "Neo-Anarchist Movement", "Seed", "TerraFirst!", "[group]"},
		},
	},
	"runner_hangouts": {
		Name:       "Runner Hangouts",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Atlanta", "Cheyenne", "Chicago", "Denver", "FDC", "High-Class", "Hong Kong", "LA", "Low-Class", "Manhattan", "Portland", "Quebec City", "Sacramento", "Seattle"},
		},
	},
	"salish": {
		Name:       "Salish",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"serbo_croatian": {
		Name:       "Serbo-Croatian",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"shadow_community": {
		Name:       "Shadow Community",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Turf", "Politics", "History", "Organizations", "Safe Houses", "News", "Personalities", "Rumors", "Famous Shadowrunners"},
		},
	},
	"aztlaner_spanish": {
		Name:       "Aztlaner Spanish",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"street_gangs_seattle": {
		Name:       "Street Gangs: Seattle",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"405 Hellhounds", "Ancients", "Black Rains", "Blood Mountains Boys", "Bloody Screamers", "Brain Eaters", "Crimson Crush", "Disassemblers", "First Nations", "Forever Tacoma", "Halloweeners", "Kabuki Ronin", "Lake Acids", "Leather Devils", "Night Hunters", "Nova Rich", "Princes", "Reality Hackers", "Red Hot Nukes", "Red Rovers", "Rusted Stilettos", "Scatterbrains", "Spiders", "Spikes", "The Ragers", "Troll Killers"},
		},
	},
	"telesma": {
		Name:       "Telesma",
		Attribute:  "LOG",
		Category:   "Professional",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"[Focus Type]"},
		},
	},
	"tlingit": {
		Name:       "Tlingit",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"triads_hong_kong": {
		Name:       "Triads: Hong Kong",
		Attribute:  "INT",
		Category:   "Street",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Black Chrysanthemums", "Red Dragons", "Yellow Lotus"},
		},
	},
	"tsimshianic": {
		Name:       "Tsimshianic",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"uto_aztecan": {
		Name:       "Uto-Aztecan",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"vehicles": {
		Name:       "Vehicles",
		Attribute:  "INT",
		Category:   "Interest",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Military", "Aircraft", "Bikes", "Boats", "Cars", "Spacecraft", "Trains", "Trucks", "Vintage Cars"},
		},
	},
	"yiddish": {
		Name:       "Yiddish",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
	"zuni": {
		Name:       "Zuni",
		Attribute:  "INT",
		Category:   "Language",
		Default:    "False",
		SkillGroup: nil,
		Specs: &Specs{
			Spec: []string{"Read/Write", "Speak", "[Dialect]", "[Lingo]", "Street", "l33tspeak", "Milspec", "Corp", "Orbital"},
		},
	},
}
