package v5

// DataSpellCategories contains spell categories keyed by their ID (lowercase with underscores)
var DataSpellCategories = map[string]SpellCategory{
	"combat": {
		Name: "Combat", UseSkill: "Spellcasting", AlchemicalSkill: "Alchemy", BarehandedAdeptSkill: "Unarmed Combat",
	},
	"detection": {
		Name: "Detection", UseSkill: "Spellcasting", AlchemicalSkill: "Alchemy", BarehandedAdeptSkill: "Unarmed Combat",
	},
	"health": {
		Name: "Health", UseSkill: "Spellcasting", AlchemicalSkill: "Alchemy", BarehandedAdeptSkill: "Unarmed Combat",
	},
	"illusion": {
		Name: "Illusion", UseSkill: "Spellcasting", AlchemicalSkill: "Alchemy", BarehandedAdeptSkill: "Unarmed Combat",
	},
	"manipulation": {
		Name: "Manipulation", UseSkill: "Spellcasting", AlchemicalSkill: "Alchemy", BarehandedAdeptSkill: "Unarmed Combat",
	},
	"enchantments": {
		Name: "Enchantments", UseSkill: "Artificing",
	},
	"rituals": {
		Name: "Rituals", UseSkill: "Ritual Spellcasting",
	},
}

// DataSpells contains spell records keyed by their ID (lowercase with underscores)
var DataSpells = map[string]Spell{
	"acid_stream": {
		Name:       "Acid Stream",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "283",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
	},
	"toxic_wave": {
		Name:       "Toxic Wave",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "283",
		Damage:     "P",
		Descriptor: "Indirect, Elemental, Area",
	},
	"punch": {
		Name:       "Punch",
		Category:   "Combat",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-6",
		Source:     "SR5",
		Page:       "283",
		Damage:     "S",
		Descriptor: "Indirect",
	},
	"clout": {
		Name:       "Clout",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "284",
		Damage:     "S",
		Descriptor: "Indirect",
	},
	"blast": {
		Name:       "Blast",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F",
		Source:     "SR5",
		Page:       "284",
		Damage:     "S",
		Descriptor: "Indirect, Area",
	},
	"death_touch": {
		Name:       "Death Touch",
		Category:   "Combat",
		Type:       "M",
		Range:      "T",
		Duration:   "I",
		DV:         "F-6",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Direct",
	},
	"manabolt": {
		Name:       "Manabolt",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Direct",
	},
	"manaball": {
		Name:       "Manaball",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Direct, Area",
	},
	"flamethrower": {
		Name:       "Flamethrower",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
	},
	"fireball": {
		Name:       "Fireball",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Indirect, Elemental, Area",
	},
	"lightning_bolt": {
		Name:       "Lightning Bolt",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
	},
	"ball_lightning": {
		Name:       "Ball Lightning",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Indirect, Elemental, Area",
	},
	"shatter": {
		Name:       "Shatter",
		Category:   "Combat",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-6",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Direct",
	},
	"powerbolt": {
		Name:       "Powerbolt",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Direct",
	},
	"powerball": {
		Name:       "Powerball",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F",
		Source:     "SR5",
		Page:       "284",
		Damage:     "P",
		Descriptor: "Direct, Area",
	},
	"knockout": {
		Name:       "Knockout",
		Category:   "Combat",
		Type:       "M",
		Range:      "T",
		Duration:   "I",
		DV:         "F-6",
		Source:     "SR5",
		Page:       "284",
		Damage:     "S",
		Descriptor: "Direct",
	},
	"stunbolt": {
		Name:       "Stunbolt",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "284",
		Damage:     "S",
		Descriptor: "Direct",
	},
	"stunball": {
		Name:       "Stunball",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F",
		Source:     "SR5",
		Page:       "284",
		Damage:     "S",
		Descriptor: "Direct, Area",
	},
	"analyze_device": {
		Name:       "Analyze Device",
		Category:   "Detection",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "285",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"analyze_magic": {
		Name:       "Analyze Magic",
		Category:   "Detection",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "285",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"analyze_truth": {
		Name:       "Analyze Truth",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "286",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"clairaudience": {
		Name:       "Clairaudience",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "286",
		Damage:     "0",
		Descriptor: "Passive, Directional",
	},
	"clairvoyance": {
		Name:       "Clairvoyance",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "286",
		Damage:     "0",
		Descriptor: "Passive, Directional",
	},
	"combat_sense": {
		Name:       "Combat Sense",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F",
		Source:     "SR5",
		Page:       "286",
		Damage:     "0",
		Descriptor: "Passive, Psychic",
	},
	"detect_enemies": {
		Name:       "Detect Enemies",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "286",
		Damage:     "0",
		Descriptor: "Active, Area",
	},
	"detect_enemies_extended": {
		Name:       "Detect Enemies, Extended",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F",
		Source:     "SR5",
		Page:       "286",
		Damage:     "0",
		Descriptor: "Active, Extended Area",
	},
	"detect_individual": {
		Name:       "Detect Individual",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "286",
		Damage:     "0",
		Descriptor: "Active, Area",
	},
	"detect_life": {
		Name:       "Detect Life",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "286",
		Damage:     "0",
		Descriptor: "Active, Area",
	},
	"detect_life_extended": {
		Name:       "Detect Life, Extended",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "286",
		Damage:     "0",
		Descriptor: "Active, Extended Area",
	},
	"detect_life_form": {
		Name:       "Detect [Life Form]",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "287",
		Damage:     "0",
		Descriptor: "Active, Area",
		Bonus:      nil,
	},
	"detect_life_form_extended": {
		Name:       "Detect [Life Form], Extended",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F",
		Source:     "SR5",
		Page:       "287",
		Damage:     "0",
		Descriptor: "Active, Extended Area",
		Bonus:      nil,
	},
	"detect_magic": {
		Name:       "Detect Magic",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "287",
		Damage:     "0",
		Descriptor: "Active, Area",
	},
	"detect_magic_extended": {
		Name:       "Detect Magic, Extended",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F",
		Source:     "SR5",
		Page:       "287",
		Damage:     "0",
		Descriptor: "Active, Extended Area",
	},
	"detect_object": {
		Name:       "Detect [Object]",
		Category:   "Detection",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "287",
		Damage:     "0",
		Descriptor: "Active, Area",
		Bonus:      nil,
	},
	"mindlink": {
		Name:       "Mindlink",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "287",
		Damage:     "0",
		Descriptor: "Active, Psychic",
	},
	"mind_probe": {
		Name:       "Mind Probe",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F",
		Source:     "SR5",
		Page:       "287",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"antidote": {
		Name:     "Antidote",
		Category: "Health",
		Type:     "M",
		Range:    "T",
		Duration: "P",
		DV:       "F-3",
		Source:   "SR5",
		Page:     "288",
		Damage:   "0",
	},
	"awaken": {
		Name:     "Awaken",
		Category: "Health",
		Type:     "M",
		Range:    "T",
		Duration: "S",
		DV:       "F-3",
		Source:   "SG",
		Page:     "109",
		Damage:   "0",
	},
	"cure_disease": {
		Name:       "Cure Disease",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "P",
		DV:         "F-4",
		Source:     "SR5",
		Page:       "288",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"decrease_attribute": {
		Name:       "Decrease [Attribute]",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "288",
		Damage:     "0",
		Descriptor: "Essence",
		Bonus:      nil,
	},
	"detox": {
		Name:     "Detox",
		Category: "Health",
		Type:     "M",
		Range:    "T",
		Duration: "P",
		DV:       "F-6",
		Source:   "SR5",
		Page:     "288",
		Damage:   "0",
	},
	"heal": {
		Name:       "Heal",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "P",
		DV:         "F-4",
		Source:     "SR5",
		Page:       "288",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"increase_attribute": {
		Name:       "Increase [Attribute]",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "288",
		Damage:     "0",
		Descriptor: "Essence",
		Bonus:      nil,
	},
	"increase_reflexes": {
		Name:       "Increase Reflexes",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F",
		Source:     "SR5",
		Page:       "288",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"oxygenate": {
		Name:     "Oxygenate",
		Category: "Health",
		Type:     "P",
		Range:    "T",
		Duration: "S",
		DV:       "F-5",
		Source:   "SR5",
		Page:     "288",
		Damage:   "0",
	},
	"prophylaxis": {
		Name:     "Prophylaxis",
		Category: "Health",
		Type:     "M",
		Range:    "T",
		Duration: "S",
		DV:       "F-4",
		Source:   "SR5",
		Page:     "289",
		Damage:   "0",
	},
	"resist_pain": {
		Name:     "Resist Pain",
		Category: "Health",
		Type:     "M",
		Range:    "T",
		Duration: "P",
		DV:       "F-4",
		Source:   "SR5",
		Page:     "289",
		Damage:   "0",
	},
	"stabilize": {
		Name:     "Stabilize",
		Category: "Health",
		Type:     "M",
		Range:    "T",
		Duration: "P",
		DV:       "F-4",
		Source:   "SR5",
		Page:     "289",
		Damage:   "0",
	},
	"agony": {
		Name:       "Agony",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
	},
	"mass_agony": {
		Name:       "Mass Agony",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
	},
	"bugs": {
		Name:       "Bugs",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"swarm": {
		Name:       "Swarm",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense, Area",
	},
	"chaos": {
		Name:       "Chaos",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"chaotic_world": {
		Name:       "Chaotic World",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense, Area",
	},
	"confusion": {
		Name:       "Confusion",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"mass_confusion": {
		Name:       "Mass Confusion",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense, Area",
	},
	"entertainment": {
		Name:       "Entertainment",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Obvious, Multi-Sense, Area",
	},
	"trid_entertainment": {
		Name:       "Trid Entertainment",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "290",
		Damage:     "0",
		Descriptor: "Obvious, Multi-Sense, Area",
	},
	"improved_invisibility": {
		Name:       "Improved Invisibility",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "291",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
	},
	"invisibility": {
		Name:       "Invisibility",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "291",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
	},
	"mask": {
		Name:       "Mask",
		Category:   "Illusion",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "291",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"physical_mask": {
		Name:       "Physical Mask",
		Category:   "Illusion",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "291",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"phantasm": {
		Name:       "Phantasm",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "291",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense, Area",
	},
	"trid_phantasm": {
		Name:       "Trid Phantasm",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F",
		Source:     "SR5",
		Page:       "291",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense, Area",
	},
	"hush": {
		Name:       "Hush",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "291",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense, Area",
	},
	"silence": {
		Name:       "Silence",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "291",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense, Area",
	},
	"stealth": {
		Name:       "Stealth",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "292",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
	},
	"animate": {
		Name:       "Animate",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "292",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"mass_animate": {
		Name:       "Mass Animate",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SR5",
		Page:       "292",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"armor": {
		Name:       "Armor",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "292",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"control_actions": {
		Name:       "Control Actions",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "292",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"mob_control": {
		Name:       "Mob Control",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SR5",
		Page:       "292",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"control_thoughts": {
		Name:       "Control Thoughts",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "293",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"mob_mind": {
		Name:       "Mob Mind",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SR5",
		Page:       "293",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"fling": {
		Name:       "Fling",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "293",
		Damage:     "0",
		Descriptor: "Physical, Damaging",
	},
	"ice_sheet": {
		Name:       "Ice Sheet",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F",
		Source:     "SR5",
		Page:       "293",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"ignite": {
		Name:       "Ignite",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "P",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "293",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"influence": {
		Name:       "Influence",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "P",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "293",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"levitate": {
		Name:       "Levitate",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "293",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"light": {
		Name:       "Light",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SR5",
		Page:       "293",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"magic_fingers": {
		Name:       "Magic Fingers",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "294",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"mana_barrier": {
		Name:       "Mana Barrier",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "294",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"physical_barrier": {
		Name:       "Physical Barrier",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SR5",
		Page:       "294",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"poltergeist": {
		Name:       "Poltergeist",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SR5",
		Page:       "294",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"shadow": {
		Name:       "Shadow",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SR5",
		Page:       "294",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"curse": {
		Name:       "Curse",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SR5",
		Page:       "297",
		Damage:     "0",
		Descriptor: "Material Link, Spell",
	},
	"prodigal_spell": {
		Name:       "Prodigal Spell",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SR5",
		Page:       "297",
		Damage:     "0",
		Descriptor: "Spell, Spotter",
	},
	"remote_sensing": {
		Name:       "Remote Sensing",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SR5",
		Page:       "297",
		Damage:     "0",
		Descriptor: "Spell, Spotter",
	},
	"ward": {
		Name:       "Ward",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SR5",
		Page:       "297",
		Damage:     "0",
		Descriptor: "Anchored",
	},
	"circle_of_protection": {
		Name:       "Circle of Protection",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SR5",
		Page:       "298",
		Damage:     "0",
		Descriptor: "Anchored",
	},
	"circle_of_healing": {
		Name:       "Circle of Healing",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SR5",
		Page:       "298",
		Damage:     "0",
		Descriptor: "Anchored, Spell",
	},
	"renascence": {
		Name:       "Renascence",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SR5",
		Page:       "298",
		Damage:     "0",
		Descriptor: "Anchored, Spell",
	},
	"watcher": {
		Name:       "Watcher",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SR5",
		Page:       "298",
		Damage:     "0",
		Descriptor: "Minion",
		Bonus:      nil,
	},
	"homunculus": {
		Name:       "Homunculus",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SR5",
		Page:       "298",
		Damage:     "0",
		Descriptor: "Minion",
		Bonus:      nil,
	},
	"corrode_object": {
		Name:       "Corrode [Object]",
		Category:   "Combat",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-5",
		Source:     "SG",
		Page:       "102",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
		Bonus:      nil,
	},
	"melt_object": {
		Name:       "Melt [Object]",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "102",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
		Bonus:      nil,
	},
	"sludge_object": {
		Name:       "Sludge [Object]",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SG",
		Page:       "102",
		Damage:     "P",
		Descriptor: "Indirect, Area, Elemental",
		Bonus:      nil,
	},
	"disrupt_object": {
		Name:       "Disrupt [Object]",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-2",
		Source:     "SG",
		Page:       "102",
		Damage:     "Special",
		Descriptor: "Direct",
		Bonus:      nil,
	},
	"destroy_free_spirit": {
		Name:       "Destroy [Free Spirit]",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "103",
		Damage:     "P",
		Descriptor: "Direct",
		Bonus:      nil,
	},
	"destroy_vehicle": {
		Name:       "Destroy [Vehicle]",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "103",
		Damage:     "P",
		Descriptor: "Direct",
		Bonus:      nil,
	},
	"firewater": {
		Name:       "Firewater",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-2",
		Source:     "SG",
		Page:       "103",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
	},
	"napalm": {
		Name:       "Napalm",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F",
		Source:     "SG",
		Page:       "103",
		Damage:     "P",
		Descriptor: "Indirect, Area, Elemental",
	},
	"insecticide_insect_spirit": {
		Name:       "Insecticide [Insect Spirit]",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F+1",
		Source:     "SG",
		Page:       "103",
		Damage:     "P",
		Descriptor: "Direct, Area",
		Bonus:      nil,
	},
	"ice_spear": {
		Name:       "Ice Spear",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "103",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
	},
	"ice_storm": {
		Name:       "Ice Storm",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F+1",
		Source:     "SG",
		Page:       "103",
		Damage:     "P",
		Descriptor: "Indirect, Area, Elemental",
	},
	"one_less_metatypespecies": {
		Name:       "One Less [Metatype/Species]",
		Category:   "Combat",
		Type:       "M",
		Range:      "T",
		Duration:   "I",
		DV:         "F-6",
		Source:     "SG",
		Page:       "104",
		Damage:     "P",
		Descriptor: "Direct",
		Bonus:      nil,
	},
	"slay_metatypespecies": {
		Name:       "Slay [Metatype/Species]",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-4",
		Source:     "SG",
		Page:       "104",
		Damage:     "P",
		Descriptor: "Direct",
		Bonus:      nil,
	},
	"slaughter_metatypespecies": {
		Name:       "Slaughter [Metatype/Species]",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-2",
		Source:     "SG",
		Page:       "104",
		Damage:     "P",
		Descriptor: "Direct, Area",
		Bonus:      nil,
	},
	"ram_object": {
		Name:       "Ram [Object]",
		Category:   "Combat",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-5",
		Source:     "SG",
		Page:       "104",
		Damage:     "P",
		Descriptor: "Direct",
		Bonus:      nil,
	},
	"wreck_object": {
		Name:       "Wreck [Object]",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "105",
		Damage:     "P",
		Descriptor: "Direct",
		Bonus:      nil,
	},
	"demolish_object": {
		Name:       "Demolish [Object]",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SG",
		Page:       "105",
		Damage:     "P",
		Descriptor: "Direct, Area",
		Bonus:      nil,
	},
	"radiation_beam": {
		Name:       "Radiation Beam",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "105",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
	},
	"radiation_burst": {
		Name:       "Radiation Burst",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SG",
		Page:       "105",
		Damage:     "P",
		Descriptor: "Indirect, Area, Elemental",
	},
	"pollutant_stream": {
		Name:       "Pollutant Stream",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "106",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
	},
	"pollutant_wave": {
		Name:       "Pollutant Wave",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SG",
		Page:       "106",
		Damage:     "P",
		Descriptor: "Indirect, Area, Elemental",
	},
	"shattershield": {
		Name:       "Shattershield",
		Category:   "Combat",
		Type:       "M",
		Range:      "T",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "106",
		Damage:     "P",
		Descriptor: "Direct",
	},
	"astral_message": {
		Name:       "Astral Message",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "106",
		Damage:     "0",
		Descriptor: "Passive, Directional",
	},
	"astral_clairvoyance": {
		Name:       "Astral Clairvoyance",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "106",
		Damage:     "0",
		Descriptor: "Passive, Directional",
	},
	"borrow_sense": {
		Name:       "Borrow Sense",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "106",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"animal_sense": {
		Name:       "Animal Sense",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-5",
		Source:     "SG",
		Page:       "106",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"eyes_of_the_pack": {
		Name:       "Eyes of the Pack",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "106",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"catalog": {
		Name:       "Catalog",
		Category:   "Detection",
		Type:       "P",
		Range:      "T (A)",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "107",
		Damage:     "0",
		Descriptor: "Active, Area",
	},
	"diagnose": {
		Name:       "Diagnose",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "107",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"dragon_astral_signature": {
		Name:       "Dragon Astral Signature",
		Category:   "Detection",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+5",
		Source:     "SG",
		Page:       "107",
		Damage:     "0",
		Descriptor: "Active, Psychic, Area",
	},
	"enhance_aim": {
		Name:       "Enhance Aim",
		Category:   "Detection",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "107",
		Damage:     "0",
		Descriptor: "Passive, Directional",
	},
	"hawkeye": {
		Name:       "Hawkeye",
		Category:   "Detection",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "107",
		Damage:     "0",
		Descriptor: "Passive, Directional",
	},
	"mana_window": {
		Name:       "Mana Window",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "107",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"astral_window": {
		Name:       "Astral Window",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "107",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"mindnet": {
		Name:       "Mindnet",
		Category:   "Detection",
		Type:       "M",
		Range:      "T (A)",
		Duration:   "S",
		DV:         "F",
		Source:     "SG",
		Page:       "108",
		Damage:     "0",
		Descriptor: "Active, Psychic, Area",
	},
	"mindnet_extended": {
		Name:       "Mindnet Extended",
		Category:   "Detection",
		Type:       "M",
		Range:      "T (A)",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SG",
		Page:       "108",
		Damage:     "0",
		Descriptor: "Active, Psychic, Extended Area",
	},
	"night_vision": {
		Name:       "Night Vision",
		Category:   "Detection",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "108",
		Damage:     "0",
		Descriptor: "Passive, Directional",
	},
	"sense_cryptesthesia": {
		Name:       "[Sense] Cryptesthesia",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "108",
		Damage:     "0",
		Descriptor: "Passive, Directional",
		Bonus:      nil,
	},
	"spatial_sense": {
		Name:       "Spatial Sense",
		Category:   "Detection",
		Type:       "P",
		Range:      "T (A)",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "108",
		Damage:     "0",
		Descriptor: "Passive, Area",
	},
	"spatial_sense_extended": {
		Name:       "Spatial Sense, Extended",
		Category:   "Detection",
		Type:       "P",
		Range:      "T (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "108",
		Damage:     "0",
		Descriptor: "Passive, Extended Area",
	},
	"thought_recognition": {
		Name:       "Thought Recognition",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F",
		Source:     "SG",
		Page:       "108",
		Damage:     "0",
		Descriptor: "Active, Psychic, Directional",
	},
	"area_thought_recognition": {
		Name:       "Area Thought Recognition",
		Category:   "Detection",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+2",
		Source:     "SG",
		Page:       "108",
		Damage:     "0",
		Descriptor: "Active, Psychic, Area",
	},
	"translate": {
		Name:       "Translate",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SG",
		Page:       "109",
		Damage:     "0",
		Descriptor: "Active, Psychic, Directional",
	},
	"ambidexterity": {
		Name:       "Ambidexterity",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "109",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"alleviate_addiction": {
		Name:       "Alleviate Addiction",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-6",
		Source:     "SG",
		Page:       "109",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"alleviate_allergy": {
		Name:       "Alleviate [Allergy]",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-6",
		Source:     "SG",
		Page:       "109",
		Damage:     "0",
		Descriptor: "Essence",
		Bonus:      nil,
	},
	"crank": {
		Name:       "Crank",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "109",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"decrease_reflexes": {
		Name:       "Decrease Reflexes",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "P",
		DV:         "F-2",
		Source:     "SG",
		Page:       "110",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"enabler": {
		Name:       "Enabler",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "110",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"fast": {
		Name:       "Fast",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "110",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"forced_defense": {
		Name:       "Forced Defense",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SG",
		Page:       "110",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"increase_inherent_limits": {
		Name:       "Increase Inherent Limits",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "110",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"decrease_inherent_limits": {
		Name:       "Decrease Inherent Limits",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "110",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"camouflage": {
		Name:       "Camouflage",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SG",
		Page:       "111",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
	},
	"physical_camouflage": {
		Name:       "Physical Camouflage",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F",
		Source:     "SG",
		Page:       "111",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
	},
	"decoy": {
		Name:       "Decoy",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "111",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"chaff": {
		Name:       "Chaff",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "111",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense, Area",
	},
	"double_image": {
		Name:       "Double Image",
		Category:   "Illusion",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "111",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"dream": {
		Name:       "Dream",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "111",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"euphoria": {
		Name:       "Euphoria",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "111",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
	},
	"opium_den": {
		Name:       "Opium Den",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "111",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense, Area",
	},
	"foreboding": {
		Name:       "Foreboding",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "112",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense, Area",
	},
	"hot_potato": {
		Name:       "Hot Potato",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "112",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense, Area",
	},
	"sense_removal": {
		Name:       "[Sense] Removal",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "112",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
		Bonus:      nil,
	},
	"mass_sense_removal": {
		Name:       "Mass [Sense] Removal",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "112",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense, Area",
		Bonus:      nil,
	},
	"stink": {
		Name:       "Stink",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "113",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense",
	},
	"stench": {
		Name:       "Stench",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "113",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense, Area",
	},
	"sound_barrier": {
		Name:       "Sound Barrier",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "113",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense, Area",
	},
	"switch_vehicle_signature": {
		Name:       "Switch Vehicle Signature",
		Category:   "Illusion",
		Type:       "P",
		Range:      "T",
		Duration:   "Special",
		DV:         "F+1",
		Source:     "SG",
		Page:       "113",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"vehicle_mask": {
		Name:       "Vehicle Mask",
		Category:   "Illusion",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "113",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"bind": {
		Name:       "Bind",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SG",
		Page:       "113",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"net_bind": {
		Name:       "Net Bind",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "113",
		Damage:     "0",
		Descriptor: "Physical, Area",
	},
	"mana_bind": {
		Name:       "Mana Bind",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SG",
		Page:       "114",
		Damage:     "0",
		Descriptor: "Mana",
	},
	"mana_net": {
		Name:       "Mana Net",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "114",
		Damage:     "0",
		Descriptor: "Mana, Area",
	},
	"bug_zapper": {
		Name:       "Bug Zapper",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SG",
		Page:       "114",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"calm_animal": {
		Name:       "Calm Animal",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "114",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"calm_pack": {
		Name:       "Calm Pack",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "114",
		Damage:     "0",
		Descriptor: "Mental, Area",
	},
	"catfall": {
		Name:       "Catfall",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "114",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"clean_element": {
		Name:       "Clean [Element]",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "P",
		DV:         "F-3",
		Source:     "SG",
		Page:       "114",
		Damage:     "0",
		Descriptor: "Environmental, Area, Elemental",
		Bonus:      nil,
	},
	"compel_truth": {
		Name:       "Compel Truth",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "Special",
		DV:         "F-1",
		Source:     "SG",
		Page:       "114",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"control_animal": {
		Name:       "Control Animal",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "115",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"control_pack": {
		Name:       "Control Pack",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "115",
		Damage:     "0",
		Descriptor: "Mental, Area",
	},
	"deflection": {
		Name:       "Deflection",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "115",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"element_aura": {
		Name:       "[Element] Aura",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SG",
		Page:       "115",
		Damage:     "0",
		Descriptor: "Environmental, Elemental",
		Bonus:      nil,
	},
	"element_wall": {
		Name:       "[Element] Wall",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+2",
		Source:     "SG",
		Page:       "115",
		Damage:     "0",
		Descriptor: "Environmental, Area, Elemental",
		Bonus:      nil,
	},
	"fashion": {
		Name:       "Fashion",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T (A)",
		Duration:   "P",
		DV:         "F-1",
		Source:     "SG",
		Page:       "115",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"fix": {
		Name:       "Fix",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "P",
		DV:         "F",
		Source:     "SG",
		Page:       "116",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"gecko_crawl": {
		Name:       "Gecko Crawl",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "116",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"glue": {
		Name:       "Glue",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "P",
		DV:         "F-3",
		Source:     "SG",
		Page:       "116",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"glue_strip": {
		Name:       "Glue Strip",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "P",
		DV:         "F-1",
		Source:     "SG",
		Page:       "116",
		Damage:     "0",
		Descriptor: "Physical, Area",
	},
	"increase_noise": {
		Name:       "Increase Noise",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "116",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"decrease_noise": {
		Name:       "Decrease Noise",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "116",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"increase_gear_limits": {
		Name:       "Increase Gear Limits",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "116",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"decrease_gear_limits": {
		Name:       "Decrease Gear Limits",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "116",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"interference": {
		Name:       "Interference",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "117",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"lock": {
		Name:       "Lock",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "117",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"mana_static": {
		Name:       "Mana Static",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "P",
		DV:         "F-1",
		Source:     "SG",
		Page:       "117",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"makeover": {
		Name:       "Makeover",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "P",
		DV:         "F-3",
		Source:     "SG",
		Page:       "117",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"mist": {
		Name:       "Mist",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "117",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"offensive_mana_barrier": {
		Name:       "Offensive Mana Barrier",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+3",
		Source:     "SG",
		Page:       "117",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"preserve": {
		Name:       "Preserve",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "117",
		Damage:     "0",
		Descriptor: "Physical, Area",
	},
	"protect_vehicle": {
		Name:       "Protect Vehicle",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "117",
		Damage:     "0",
		Descriptor: "Physical, Area",
	},
	"pulse": {
		Name:       "Pulse",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F+3",
		Source:     "SG",
		Page:       "118",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"reinforce": {
		Name:       "Reinforce",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "118",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"slow_vehicle": {
		Name:       "Slow Vehicle",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SG",
		Page:       "118",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"shape_material": {
		Name:       "Shape [Material]",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SG",
		Page:       "118",
		Damage:     "0",
		Descriptor: "Environmental, Area",
		Bonus:      nil,
	},
	"shapechange": {
		Name:       "Shapechange",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SG",
		Page:       "118",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"critter_form": {
		Name:       "[Critter] Form",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SG",
		Page:       "118",
		Damage:     "0",
		Descriptor: "Physical",
		Bonus:      nil,
	},
	"spirit_barrier": {
		Name:       "Spirit Barrier",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SG",
		Page:       "119",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"spirit_zapper": {
		Name:       "Spirit Zapper",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SG",
		Page:       "119",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"sterilize": {
		Name:       "Sterilize",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-3",
		Source:     "SG",
		Page:       "119",
		Damage:     "0",
		Descriptor: "Physical, Area",
	},
	"turn_to_goo": {
		Name:       "Turn To Goo",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F+3",
		Source:     "SG",
		Page:       "119",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"aspect_mana_line": {
		Name:       "Aspect Mana Line",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "122",
		Damage:     "0",
		Descriptor: "Mana",
		Required:   nil,
	},
	"alarm_ward": {
		Name:       "Alarm Ward",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "122",
		Damage:     "0",
		Descriptor: "Anchored",
	},
	"ally_conjuration": {
		Name:       "Ally Conjuration",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "122",
		Damage:     "0",
		Descriptor: "Minion",
		Bonus:      nil,
		Required:   nil,
	},
	"astral_doppelganger": {
		Name:       "Astral Doppelganger",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "122",
		Damage:     "0",
		Descriptor: "Spotter, Material Link",
	},
	"atonement": {
		Name:       "Atonement",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "123",
		Damage:     "0",
		Descriptor: "Contractual",
	},
	"attune_animal": {
		Name:       "Attune Animal",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "123",
		Damage:     "0",
		Descriptor: "Adept",
		Bonus:      nil,
		Required:   nil,
	},
	"attune_item": {
		Name:       "Attune Item",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "124",
		Damage:     "0",
		Descriptor: "Adept",
		Bonus:      nil,
		Required:   nil,
	},
	"augury_and_sortilege": {
		Name:       "Augury and Sortilege",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "124",
		Damage:     "0",
		Descriptor: "Material Link",
		Required:   nil,
	},
	"blood_bond": {
		Name:       "Blood Bond",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "125",
		Damage:     "0",
		Descriptor: "Material Link",
	},
	"blood_rite": {
		Name:       "Blood Rite",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "125",
		Damage:     "0",
		Descriptor: "Blood, Organic Link",
	},
	"blood_sight": {
		Name:       "Blood Sight",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "125",
		Damage:     "0",
		Descriptor: "Organic Link",
		Required:   nil,
	},
	"calling_spirit_type": {
		Name:       "Calling [Spirit Type]",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "126",
		Damage:     "0",
		Descriptor: "Contractual",
	},
	"charged_ward": {
		Name:       "Charged Ward",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "127",
		Damage:     "0",
		Descriptor: "Anchored",
		Required:   nil,
	},
	"circle_of_cleansing": {
		Name:       "Circle of Cleansing",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "127",
		Damage:     "0",
		Descriptor: "Anchored, Mana",
		Required:   nil,
	},
	"create_ally_spirit": {
		Name:       "Create Ally Spirit",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "127",
		Damage:     "0",
		Descriptor: "Minion",
		Bonus:      nil,
	},
	"death_mark": {
		Name:       "Death Mark",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "127",
		Damage:     "0",
		Descriptor: "Organic Link, Spotter",
		Required:   nil,
	},
	"dispersion_circle": {
		Name:       "Dispersion Circle",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "127",
		Damage:     "0",
		Descriptor: "Anchored",
		Required:   nil,
	},
	"door_wards": {
		Name:       "Door Wards",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "127",
		Damage:     "0",
		Descriptor: "Anchored",
		Required:   nil,
	},
	"empower": {
		Name:       "Empower",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "128",
		Damage:     "0",
		Descriptor: "Adept",
		Required:   nil,
	},
	"grave_binding": {
		Name:       "Grave Binding",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "129",
		Damage:     "0",
		Descriptor: "Anchored, Organic Link",
		Required:   nil,
	},
	"group_bond": {
		Name:       "Group Bond",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "129",
		Damage:     "0",
		Descriptor: "Contractual",
	},
	"imbue_item": {
		Name:     "Imbue Item",
		Category: "Rituals",
		Type:     "M",
		Range:    "Special",
		Duration: "Special",
		DV:       "Special",
		Source:   "SG",
		Page:     "133",
		Damage:   "0",
		Required: nil,
	},
	"kything": {
		Name:       "Kything",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "133",
		Damage:     "0",
		Descriptor: "Anchored",
		Required:   nil,
	},
	"far_sensing": {
		Name:       "Far Sensing",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "133",
		Damage:     "0",
		Descriptor: "Spotter",
		Required:   nil,
	},
	"leeching": {
		Name:       "Leeching",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "133",
		Damage:     "0",
		Descriptor: "Mana",
	},
	"ley_sight": {
		Name:       "Ley Sight",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "134",
		Damage:     "0",
		Descriptor: "Mana",
		Required:   nil,
	},
	"light_of_dharma": {
		Name:       "Light of Dharma",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "134",
		Damage:     "0",
		Descriptor: "Anchored",
		Required:   nil,
	},
	"living_vessel_preparation": {
		Name:       "Living Vessel Preparation",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "135",
		Damage:     "0",
		Descriptor: "Organic Link",
		Required:   nil,
	},
	"inanimate_vessel_preparation": {
		Name:       "Inanimate Vessel Preparation",
		Category:   "Enchantments",
		Type:       "P",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "214",
		Damage:     "0",
		Descriptor: "Organic Link",
		Required:   nil,
	},
	"manifest_sha": {
		Name:       "Manifest Sha",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "135",
		Damage:     "0",
		Descriptor: "Anchored, Mana",
		Required:   nil,
	},
	"masking_ward": {
		Name:       "Masking Ward",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "135",
		Damage:     "0",
		Descriptor: "Anchored",
		Required:   nil,
	},
	"obfuscating_ward": {
		Name:       "Obfuscating Ward",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "135",
		Damage:     "0",
		Descriptor: "Anchored",
		Required:   nil,
	},
	"polarized_ward": {
		Name:       "Polarized Ward",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "136",
		Damage:     "0",
		Descriptor: "Anchored",
	},
	"recharge_reagents": {
		Name:       "Recharge Reagents",
		Category:   "Enchantments",
		Type:       "P",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "136",
		Damage:     "0",
		Descriptor: "Geomancy",
		Required:   nil,
	},
	"shofar": {
		Name:     "Shofar",
		Category: "Enchantments",
		Type:     "P",
		Range:    "Special",
		Duration: "Special",
		DV:       "Special",
		Source:   "SG",
		Page:     "216",
		Damage:   "0",
		Required: nil,
	},
	"ritual_of_change": {
		Name:       "Ritual of Change",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "136",
		Damage:     "0",
		Descriptor: "Minion",
	},
	"smudging": {
		Name:       "Smudging",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "136",
		Damage:     "0",
		Descriptor: "Mana, Material Link",
		Required:   nil,
	},
	"spirit_pact": {
		Name:       "Spirit Pact",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "136",
		Damage:     "0",
		Descriptor: "Contractual",
	},
	"summon_great_form_spirit": {
		Name:       "Summon Great Form Spirit",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "136",
		Damage:     "0",
		Descriptor: "Minion",
		Required:   nil,
	},
	"trap_ward": {
		Name:       "Trap Ward",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "137",
		Damage:     "0",
		Descriptor: "Anchored",
		Required:   nil,
	},
	"whisper_of_bones": {
		Name:       "Whisper of Bones",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SG",
		Page:       "137",
		Damage:     "0",
		Descriptor: "Organic Link",
		Required:   nil,
	},
	"death_replay": {
		Name:       "Death Replay",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "BB",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Active, Directional",
	},
	"incision": {
		Name:       "Incision",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "BB",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"hand_of_glory": {
		Name:     "Hand of Glory",
		Category: "Enchantments",
		Type:     "P",
		Range:    "Special",
		Duration: "Special",
		DV:       "Special",
		Source:   "SG",
		Page:     "213",
		Damage:   "0",
		Required: nil,
	},
	"mortis_optigram": {
		Name:     "Mortis Optigram",
		Category: "Enchantments",
		Type:     "P",
		Range:    "Special",
		Duration: "Special",
		DV:       "Special",
		Source:   "SG",
		Page:     "214",
		Damage:   "0",
		Required: nil,
	},
	"symbolic_link": {
		Name:     "Symbolic Link",
		Category: "Enchantments",
		Type:     "P",
		Range:    "Special",
		Duration: "Special",
		DV:       "Special",
		Source:   "SG",
		Page:     "216",
		Damage:   "0",
		Required: nil,
	},
	"mystic_restraints": {
		Name:     "Mystic Restraints",
		Category: "Enchantments",
		Type:     "P",
		Range:    "Special",
		Duration: "Special",
		DV:       "Special",
		Source:   "SG",
		Page:     "214",
		Damage:   "0",
		Required: nil,
	},
	"paper_lotus": {
		Name:     "Paper Lotus",
		Category: "Enchantments",
		Type:     "P",
		Range:    "Special",
		Duration: "Special",
		DV:       "Special",
		Source:   "SG",
		Page:     "215",
		Damage:   "0",
		Required: nil,
	},
	"govi": {
		Name:     "Govi",
		Category: "Enchantments",
		Type:     "P",
		Range:    "Special",
		Duration: "Special",
		DV:       "Special",
		Source:   "SG",
		Page:     "212",
		Damage:   "0",
		Required: nil,
	},
	"astral_powder": {
		Name:     "Astral Powder",
		Category: "Enchantments",
		Type:     "P",
		Range:    "Special",
		Duration: "Special",
		DV:       "Special",
		Source:   "SG",
		Page:     "212",
		Damage:   "0",
		Required: nil,
	},
	"convince": {
		Name:     "Convince",
		Category: "Manipulation",
		Type:     "P",
		Range:    "LOS",
		Duration: "S",
		DV:       "F-2",
		Source:   "SS",
		Page:     "189",
		Damage:   "0",
	},
	"fashion_1": {
		Name:     "Fashion",
		Category: "Manipulation",
		Type:     "P",
		Range:    "T (A)",
		Duration: "P",
		DV:       "F-1",
		Source:   "SS",
		Page:     "190",
		Damage:   "0",
	},
	"hibernate": {
		Name:     "Hibernate",
		Category: "Manipulation",
		Type:     "M",
		Range:    "T",
		Duration: "P",
		DV:       "F-2",
		Source:   "SS",
		Page:     "190",
		Damage:   "0",
	},
	"interference_1": {
		Name:       "Interference",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SS",
		Page:       "190",
		Damage:     "0",
		Descriptor: "Environmental, Area",
	},
	"intoxication": {
		Name:     "Intoxication",
		Category: "Manipulation",
		Type:     "M",
		Range:    "T",
		Duration: "P",
		DV:       "F-3",
		Source:   "SS",
		Page:     "190",
		Damage:   "0",
	},
	"nutrition": {
		Name:     "Nutrition",
		Category: "Manipulation",
		Type:     "P",
		Range:    "T",
		Duration: "P",
		DV:       "F-3",
		Source:   "SS",
		Page:     "190",
		Damage:   "0",
	},
	"sound_barrier_1": {
		Name:       "Sound Barrier",
		Category:   "Illusion",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SS",
		Page:       "190",
		Damage:     "0",
		Descriptor: "Realistic, Single-Sense, Area",
	},
	"vehicle_mask_1": {
		Name:       "Vehicle Mask",
		Category:   "Illusion",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SS",
		Page:       "190",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"chill": {
		Name:       "Chill",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SSP",
		Page:       "16",
		Damage:     "S",
		Descriptor: "Direct",
	},
	"frigid": {
		Name:       "Frigid",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F+1",
		Source:     "SSP",
		Page:       "16",
		Damage:     "S",
		Descriptor: "Direct, Area",
	},
	"flame_burst": {
		Name:       "Flame Burst",
		Category:   "Combat",
		Type:       "P",
		Range:      "S (A)",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SSP",
		Page:       "16",
		Damage:     "P",
		Descriptor: "Direct, Elemental",
	},
	"magebolt": {
		Name:       "Magebolt",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "17",
		Damage:     "P",
		Descriptor: "Direct",
	},
	"element_grenade": {
		Name:       "[Element] Grenade",
		Category:   "Combat",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SSP",
		Page:       "17",
		Damage:     "P",
		Descriptor: "Indirect, Elemental",
		Bonus:      nil,
	},
	"sunbeam": {
		Name:       "Sunbeam",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-1",
		Source:     "SSP",
		Page:       "17",
		Damage:     "P",
		Descriptor: "Indirect",
	},
	"passenger": {
		Name:       "Passenger",
		Category:   "Detection",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F",
		Source:     "SSP",
		Page:       "18",
		Damage:     "0",
		Descriptor: "Passive, Psychic",
	},
	"recorded_room": {
		Name:       "Recorded Room",
		Category:   "Detection",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F",
		Source:     "SSP",
		Page:       "18",
		Damage:     "0",
		Descriptor: "Passive, Area",
	},
	"secret_handshake": {
		Name:       "Secret Handshake",
		Category:   "Detection",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "18",
		Damage:     "0",
		Descriptor: "Active, Area",
	},
	"broadcast": {
		Name:       "Broadcast",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SSP",
		Page:       "18",
		Damage:     "0",
		Descriptor: "Active, Area",
	},
	"sending": {
		Name:       "Sending",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F+2",
		Source:     "SSP",
		Page:       "18",
		Damage:     "0",
		Descriptor: "Active, Extended Area",
	},
	"sense_link": {
		Name:       "[Sense] Link",
		Category:   "Detection",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SSP",
		Page:       "18",
		Damage:     "0",
		Descriptor: "Passive, Psychic",
		Bonus:      nil,
	},
	"convert_blood_to_ichor": {
		Name:       "Convert Blood to Ichor",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F",
		Source:     "SSP",
		Page:       "18",
		Damage:     "0",
		Descriptor: "Essence, Negative",
	},
	"decontamination": {
		Name:       "Decontamination",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "P",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "18",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"dehydrate": {
		Name:       "Dehydrate",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "18",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"ghoulish_strength": {
		Name:       "Ghoulish Strength",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "19",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"healthy_glow": {
		Name:       "Healthy Glow",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "P",
		DV:         "F-2",
		Source:     "SSP",
		Page:       "19",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"hydrate": {
		Name:       "Hydrate",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "P",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "19",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"inflict_disease": {
		Name:       "Inflict Disease",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "P",
		DV:         "F-3",
		Source:     "SSP",
		Page:       "19",
		Damage:     "0",
		Descriptor: "Negative, Essence",
	},
	"nauseate": {
		Name:       "Nauseate",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "I",
		DV:         "F-2",
		Source:     "SSP",
		Page:       "19",
		Damage:     "0",
		Descriptor: "Negative",
	},
	"alleviate_nausea": {
		Name:       "Alleviate Nausea",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "19",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"personal_warmth": {
		Name:       "Personal Warmth",
		Category:   "Health",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "19",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"rot": {
		Name:       "Rot",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F",
		Source:     "SSP",
		Page:       "20",
		Damage:     "0",
		Descriptor: "Essence, Negative",
	},
	"vampiric_speed": {
		Name:       "Vampiric Speed",
		Category:   "Health",
		Type:       "P",
		Range:      "S (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SSP",
		Page:       "20",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"false_impression": {
		Name:     "False Impression",
		Category: "Illusion",
		Type:     "M",
		Range:    "LOS",
		Duration: "S",
		DV:       "F-4",
		Source:   "SSP",
		Page:     "20",
		Damage:   "0",
	},
	"manascape": {
		Name:     "Manascape",
		Category: "Illusion",
		Type:     "M",
		Range:    "LOS (A)",
		Duration: "S",
		DV:       "F-2",
		Source:   "SSP",
		Page:     "20",
		Damage:   "0",
	},
	"vampiric_stealth": {
		Name:     "Vampiric Stealth",
		Category: "Illusion",
		Type:     "M",
		Range:    "S",
		Duration: "S",
		DV:       "F-3",
		Source:   "SSP",
		Page:     "20",
		Damage:   "0",
	},
	"air_filter": {
		Name:       "Air Filter",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-6",
		Source:     "SSP",
		Page:       "20",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"alter_memory": {
		Name:       "Alter Memory",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "P",
		DV:         "F+1",
		Source:     "SSP",
		Page:       "20",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"alter_temperature": {
		Name:       "Alter Temperature",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SSP",
		Page:       "20",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"astral_armor": {
		Name:       "Astral Armor",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"control_emotions": {
		Name:       "Control Emotions",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"mob_mood": {
		Name:       "Mob Mood",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+1",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"evaporate": {
		Name:       "Evaporate",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"looking_glass": {
		Name:       "Looking Glass",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"insulate": {
		Name:       "Insulate",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Physical, Environmental",
	},
	"napalm_wall": {
		Name:       "Napalm Wall",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Physical, Environmental",
	},
	"petrify": {
		Name:       "Petrify",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"pulse_1": {
		Name:       "Pulse",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Physical, Environmental",
	},
	"radiation_shield": {
		Name:       "Radiation Shield",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-4",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"radiation_barrier": {
		Name:       "Radiation Barrier",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-2",
		Source:     "SSP",
		Page:       "21",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"decrystalize": {
		Name:       "Decrystalize",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SSP",
		Page:       "22",
		Damage:     "0",
		Descriptor: "Material Link, Spotter",
	},
	"mana_flow": {
		Name:       "Mana Flow",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SSP",
		Page:       "22",
		Damage:     "0",
		Descriptor: "Anchored",
	},
	"mana_ebb": {
		Name:       "Mana Ebb",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "SSP",
		Page:       "22",
		Damage:     "0",
		Descriptor: "Anchored",
	},
	"catch": {
		Name:     "Catch",
		Category: "Manipulation",
		Type:     "P",
		Range:    "LOS",
		Duration: "I",
		DV:       "F-2",
		Source:   "HT",
		Page:     "191",
		Damage:   "P",
	},
	"snakeblood": {
		Name:     "Snakeblood",
		Category: "Manipulation",
		Type:     "P",
		Range:    "T",
		Duration: "S",
		DV:       "F-2",
		Source:   "HT",
		Page:     "192",
		Damage:   "0",
	},
	"conceal_scent": {
		Name:       "Conceal Scent",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "S",
		DV:         "F-3",
		Source:     "HT",
		Page:       "191",
		Damage:     "0",
		Descriptor: "Object",
	},
	"recharge_potency": {
		Name:     "Recharge Potency",
		Category: "Manipulation",
		Type:     "M",
		Range:    "T",
		Duration: "S",
		DV:       "F+1",
		Source:   "HT",
		Page:     "192",
		Damage:   "0",
	},
	"manablade": {
		Name:     "Manablade",
		Category: "Combat",
		Type:     "M",
		Range:    "Special",
		Duration: "S",
		DV:       "F-2",
		Source:   "HT",
		Page:     "192",
		Damage:   "P",
	},
	"powerblade": {
		Name:     "Powerblade",
		Category: "Combat",
		Type:     "P",
		Range:    "Special",
		Duration: "S",
		DV:       "F-2",
		Source:   "HT",
		Page:     "192",
		Damage:   "P",
	},
	"corps_cadavre": {
		Name:       "Corps Cadavre",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "HT",
		Page:       "129",
		Damage:     "0",
		Descriptor: "Minion",
		Bonus:      nil,
	},
	"zombie": {
		Name:       "Zombie",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "Special",
		DV:         "Special",
		Source:     "HT",
		Page:       "131",
		Damage:     "0",
		Descriptor: "Minion",
	},
	"incubus": {
		Name:       "Incubus",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-3",
		Source:     "CA",
		Page:       "153",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense",
	},
	"incubus_shroud": {
		Name:       "Incubus Shroud",
		Category:   "Illusion",
		Type:       "M",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F-1",
		Source:     "CA",
		Page:       "153",
		Damage:     "0",
		Descriptor: "Realistic, Multi-Sense, Area",
	},
	"rewind": {
		Name:       "Rewind",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "P",
		DV:         "F",
		Source:     "CA",
		Page:       "153",
		Damage:     "0",
		Descriptor: "Mental",
	},
	"consistency": {
		Name:       "Consistency",
		Category:   "Detection",
		Type:       "M",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "CA",
		Page:       "153",
		Damage:     "0",
		Descriptor: "Psychic",
	},
	"branch": {
		Name:       "Branch",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "FA",
		Page:       "49",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"vines": {
		Name:       "Vines",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "FA",
		Page:       "49",
		Damage:     "0",
		Descriptor: "Physical, Area",
	},
	"thorn": {
		Name:       "Thorn",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F",
		Source:     "FA",
		Page:       "49",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"rosebush": {
		Name:       "Rosebush",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+2",
		Source:     "FA",
		Page:       "49",
		Damage:     "0",
		Descriptor: "Physical, Area",
	},
	"growth": {
		Name:       "Growth",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F+3",
		Source:     "FA",
		Page:       "49",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"lash": {
		Name:       "Lash",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F",
		Source:     "FA",
		Page:       "49",
		Damage:     "0",
		Descriptor: "Indirect",
	},
	"slash": {
		Name:       "Slash",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F+3",
		Source:     "FA",
		Page:       "49",
		Damage:     "0",
		Descriptor: "Indirect, Area",
	},
	"claw": {
		Name:       "Claw",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F",
		Source:     "FA",
		Page:       "50",
		Damage:     "0",
		Descriptor: "Indirect",
	},
	"barrage": {
		Name:       "Barrage",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F+3",
		Source:     "FA",
		Page:       "50",
		Damage:     "0",
		Descriptor: "Indirect, Area",
	},
	"multiply_food": {
		Name:       "Multiply Food",
		Category:   "Health",
		Type:       "P",
		Range:      "T",
		Duration:   "P",
		DV:         "F-2",
		Source:     "FA",
		Page:       "50",
		Damage:     "0",
		Descriptor: "Essence",
	},
	"comet": {
		Name:       "Comet",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F",
		Source:     "FA",
		Page:       "50",
		Damage:     "0",
		Descriptor: "Indirect, Area, Elemental",
	},
	"gravity": {
		Name:       "Gravity",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F+1",
		Source:     "FA",
		Page:       "50",
		Damage:     "0",
		Descriptor: "Physical",
	},
	"gravity_well": {
		Name:       "Gravity Well",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "S",
		DV:         "F+3",
		Source:     "FA",
		Page:       "50",
		Damage:     "0",
		Descriptor: "Physical, Area",
	},
	"evil_eye": {
		Name:       "Evil Eye",
		Category:   "Combat",
		Type:       "M",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "FA",
		Page:       "50",
		Damage:     "0",
		Descriptor: "Direct",
	},
	"alter_ballistics": {
		Name:       "Alter Ballistics",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-2",
		Source:     "FA",
		Page:       "51",
		Damage:     "0",
		Descriptor: "Physical",
		Required:   nil,
	},
	"forest_transformation": {
		Name:       "Forest Transformation",
		Category:   "Rituals",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "Special",
		Source:     "FA",
		Page:       "52",
		Damage:     "0",
		Descriptor: "Anchored",
	},
	"necro_summoning": {
		Name:       "Necro Summoning",
		Category:   "Rituals",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "Special",
		Source:     "FA",
		Page:       "52",
		Damage:     "0",
		Descriptor: "Minion",
		Bonus:      nil,
	},
	"boil_blood": {
		Name:       "Boil Blood",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-2",
		Source:     "FA",
		Page:       "125",
		Damage:     "P",
		Descriptor: "Blood, Direct, Elemental",
		Required:   nil,
	},
	"corpse_explosion": {
		Name:       "Corpse Explosion",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F",
		Source:     "FA",
		Page:       "126",
		Damage:     "P",
		Descriptor: "Blood, Direct, Elemental",
		Required:   nil,
	},
	"embolism": {
		Name:       "Embolism",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-2",
		Source:     "FA",
		Page:       "126",
		Damage:     "P",
		Descriptor: "Blood, Direct",
		Required:   nil,
	},
	"giger_spit": {
		Name:       "Giger Spit",
		Category:   "Combat",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-4",
		Source:     "FA",
		Page:       "126",
		Damage:     "P",
		Descriptor: "Blood, Direct, Elemental",
		Required:   nil,
	},
	"ice_veins": {
		Name:       "Ice Veins",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-3",
		Source:     "FA",
		Page:       "127",
		Damage:     "Special",
		Descriptor: "Blood, Direct",
		Required:   nil,
	},
	"pyrohemetics": {
		Name:       "Pyrohemetics",
		Category:   "Combat",
		Type:       "P",
		Range:      "LOS",
		Duration:   "I",
		DV:         "F-4",
		Source:     "FA",
		Page:       "127",
		Damage:     "P",
		Descriptor: "Blood, Direct, Elemental",
		Required:   nil,
	},
	"rupture": {
		Name:       "Rupture",
		Category:   "Combat",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-6",
		Source:     "FA",
		Page:       "127",
		Damage:     "P",
		Descriptor: "Blood, Direct",
		Required:   nil,
	},
	"clot": {
		Name:       "Clot",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "FA",
		Page:       "127",
		Damage:     "0",
		Descriptor: "Blood, Essence",
		Required:   nil,
	},
	"share_damage": {
		Name:       "Share Damage",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-4",
		Source:     "FA",
		Page:       "127",
		Damage:     "0",
		Descriptor: "Blood",
		Required:   nil,
	},
	"somatic_healing": {
		Name:       "Somatic Healing",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "P",
		DV:         "F-4",
		Source:     "FA",
		Page:       "127",
		Damage:     "0",
		Descriptor: "Blood, Essence",
		Required:   nil,
	},
	"sympathetic_reprisal": {
		Name:       "Sympathetic Reprisal",
		Category:   "Health",
		Type:       "M",
		Range:      "T",
		Duration:   "S",
		DV:         "F-2",
		Source:     "FA",
		Page:       "128",
		Damage:     "0",
		Descriptor: "Blood",
		Required:   nil,
	},
	"blood_puppet": {
		Name:       "Blood Puppet",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-1",
		Source:     "FA",
		Page:       "128",
		Damage:     "0",
		Descriptor: "Blood, Mental",
		Required:   nil,
	},
	"corpse_spikes": {
		Name:       "Corpse Spikes",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F",
		Source:     "FA",
		Page:       "129",
		Damage:     "0",
		Descriptor: "Blood, Environmental, Area",
		Required:   nil,
	},
	"corpse_lash": {
		Name:       "Corpse Lash",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS (A)",
		Duration:   "I",
		DV:         "F-1",
		Source:     "FA",
		Page:       "129",
		Damage:     "0",
		Descriptor: "Blood, Environmental, Area",
		Required:   nil,
	},
	"blood_whip": {
		Name:       "Blood Whip",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-2",
		Source:     "FA",
		Page:       "129",
		Damage:     "0",
		Descriptor: "Blood, Physical",
		Required:   nil,
	},
	"blood_blade": {
		Name:       "Blood Blade",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "T",
		Duration:   "I",
		DV:         "F-1",
		Source:     "FA",
		Page:       "129",
		Damage:     "0",
		Descriptor: "Blood, Physical",
		Required:   nil,
	},
	"viscera_web": {
		Name:       "Viscera Web",
		Category:   "Manipulation",
		Type:       "P",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F+4",
		Source:     "FA",
		Page:       "129",
		Damage:     "0",
		Descriptor: "Blood, Physical, Damaging",
		Required:   nil,
	},
	"blood_bath": {
		Name:       "Blood Bath",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "I",
		DV:         "Special",
		Source:     "FA",
		Page:       "130",
		Damage:     "0",
		Descriptor: "Adept, Blood",
		Required:   nil,
	},
	"blood_oath": {
		Name:       "Blood Oath",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "I",
		DV:         "Special",
		Source:     "FA",
		Page:       "130",
		Damage:     "0",
		Descriptor: "Material Link",
		Required:   nil,
	},
	"death_curse": {
		Name:       "Death Curse",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "I",
		DV:         "Special",
		Source:     "FA",
		Page:       "130",
		Damage:     "0",
		Descriptor: "Material Link",
		Required:   nil,
	},
	"guardian_bond": {
		Name:       "Guardian Bond",
		Category:   "Rituals",
		Type:       "M",
		Range:      "Special",
		Duration:   "I",
		DV:         "Special",
		Source:     "FA",
		Page:       "131",
		Damage:     "0",
		Descriptor: "Material Link",
		Required:   nil,
	},
	"astral_disruption": {
		Name:       "Astral Disruption",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F-2",
		Source:     "BTB",
		Page:       "158",
		Damage:     "0",
		Descriptor: "Mana",
	},
	"mass_astral_disruption": {
		Name:       "Mass Astral Disruption",
		Category:   "Manipulation",
		Type:       "M",
		Range:      "LOS",
		Duration:   "S",
		DV:         "F",
		Source:     "BTB",
		Page:       "158",
		Damage:     "0",
		Descriptor: "Mana, Area",
	},
}
