package v5

// dataSpells contains all spell definitions
var dataSpells = map[string]Spell{
	// Combat Spells
	"acid_stream": {
		Name:     "Acid Stream",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Indirect", "Elemental"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"toxic_wave": {
		Name:     "Toxic Wave",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Indirect", "Elemental", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"punch": {
		Name:     "Punch",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Damage:   damageTypePtr(SpellDamageTypeStun),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -6, Formula: "F-6", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Indirect"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"clout": {
		Name:     "Clout",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Damage:   damageTypePtr(SpellDamageTypeStun),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Indirect"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"blast": {
		Name:     "Blast",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Damage:   damageTypePtr(SpellDamageTypeStun),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Indirect"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"death_touch": {
		Name:     "Death Touch",
		Category: SpellCategoryCombat,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -6, Formula: "F-6", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Direct"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"manabolt": {
		Name:     "Manabolt",
		Category: SpellCategoryCombat,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Direct"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"manaball": {
		Name:     "Manaball",
		Category: SpellCategoryCombat,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Direct"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"flamethrower": {
		Name:     "Flamethrower",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Indirect", "Elemental"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"fireball": {
		Name:     "Fireball",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Indirect", "Elemental"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"lightning_bolt": {
		Name:     "Lightning Bolt",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Indirect", "Elemental"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"ball_lightning": {
		Name:     "Ball Lightning",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Indirect", "Elemental"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"shatter": {
		Name:     "Shatter",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -6, Formula: "F-6", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Direct"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"powerbolt": {
		Name:     "Powerbolt",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Direct"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"powerball": {
		Name:     "Powerball",
		Category: SpellCategoryCombat,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Direct"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"knockout": {
		Name:     "Knockout",
		Category: SpellCategoryCombat,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -6, Formula: "F-6", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Direct"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"stunbolt": {
		Name:     "Stunbolt",
		Category: SpellCategoryCombat,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Direct"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"stunball": {
		Name:     "Stunball",
		Category: SpellCategoryCombat,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Damage:   damageTypePtr(SpellDamageTypePhysical),
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Direct"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	// Detection Spells
	"analyze_device": {
		Name:     "Analyze Device",
		Category: SpellCategoryDetection,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Directional"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"analyze_magic": {
		Name:     "Analyze Magic",
		Category: SpellCategoryDetection,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Directional"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"analyze_truth": {
		Name:     "Analyze Truth",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Directional"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"clairaudience": {
		Name:     "Clairaudience",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Passive", "Directional"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"clairvoyance": {
		Name:     "Clairvoyance",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Passive", "Directional"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"combat_sense": {
		Name:     "Combat Sense",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Passive", "Psychic"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detect_enemies": {
		Name:     "Detect Enemies",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detect_enemies_extended": {
		Name:     "Detect Enemies, Extended",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Extended Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detect_individual": {
		Name:     "Detect Individual",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detect_life": {
		Name:     "Detect Life",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detect_life_extended": {
		Name:     "Detect Life, Extended",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Extended Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detect_life_form": {
		Name:     "Detect [Life Form]",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detect_life_form_extended": {
		Name:     "Detect [Life Form], Extended",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Extended Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detect_object": {
		Name:     "Detect [Object]",
		Category: SpellCategoryDetection,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"mindlink": {
		Name:     "Mindlink",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Psychic"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"mind_probe": {
		Name:     "Mind Probe",
		Category: SpellCategoryDetection,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Active", "Directional"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	// Health Spells
	"antidote": {
		Name:     "Antidote",
		Category: SpellCategoryHealth,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypePermanent,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Source:   &SourceReference{Source: "SR5"},
	},
	"cure_disease": {
		Name:     "Cure Disease",
		Category: SpellCategoryHealth,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypePermanent,
		Drain:    DrainFormula{BaseModifier: -4, Formula: "F-4", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Essence"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"decrease_attribute": {
		Name:     "Decrease [Attribute]",
		Category: SpellCategoryHealth,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Essence"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"detox": {
		Name:     "Detox",
		Category: SpellCategoryHealth,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypePermanent,
		Drain:    DrainFormula{BaseModifier: -6, Formula: "F-6", MinimumDrain: 2},
		Source:   &SourceReference{Source: "SR5"},
	},
	"heal": {
		Name:     "Heal",
		Category: SpellCategoryHealth,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypePermanent,
		Drain:    DrainFormula{BaseModifier: -4, Formula: "F-4", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Essence"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"increase_attribute": {
		Name:     "Increase [Attribute]",
		Category: SpellCategoryHealth,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Essence"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"increase_reflexes": {
		Name:     "Increase Reflexes",
		Category: SpellCategoryHealth,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Essence"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"oxygenate": {
		Name:     "Oxygenate",
		Category: SpellCategoryHealth,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -5, Formula: "F-5", MinimumDrain: 2},
		Source:   &SourceReference{Source: "SR5"},
	},
	"prophylaxis": {
		Name:     "Prophylaxis",
		Category: SpellCategoryHealth,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -4, Formula: "F-4", MinimumDrain: 2},
		Source:   &SourceReference{Source: "SR5"},
	},
	"resist_pain": {
		Name:     "Resist Pain",
		Category: SpellCategoryHealth,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypePermanent,
		Drain:    DrainFormula{BaseModifier: -4, Formula: "F-4", MinimumDrain: 2},
		Source:   &SourceReference{Source: "SR5"},
	},
	"stabilize": {
		Name:     "Stabilize",
		Category: SpellCategoryHealth,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypePermanent,
		Drain:    DrainFormula{BaseModifier: -4, Formula: "F-4", MinimumDrain: 2},
		Source:   &SourceReference{Source: "SR5"},
	},
	// Illusion Spells
	"agony": {
		Name:     "Agony",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -4, Formula: "F-4", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Single-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"mass_agony": {
		Name:     "Mass Agony",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Single-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"bugs": {
		Name:     "Bugs",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"swarm": {
		Name:     "Swarm",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"confusion": {
		Name:     "Confusion",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"mass_confusion": {
		Name:     "Mass Confusion",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"chaos": {
		Name:     "Chaos",
		Category: SpellCategoryIllusion,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"chaotic_world": {
		Name:     "Chaotic World",
		Category: SpellCategoryIllusion,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"entertainment": {
		Name:     "Entertainment",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Obvious", "Multi-Sense", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"trid_entertainment": {
		Name:     "Trid Entertainment",
		Category: SpellCategoryIllusion,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Obvious", "Multi-Sense", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"invisibility": {
		Name:     "Invisibility",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Single-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"improved_invisibility": {
		Name:     "Improved Invisibility",
		Category: SpellCategoryIllusion,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Single-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"mask": {
		Name:     "Mask",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"physical_mask": {
		Name:     "Physical Mask",
		Category: SpellCategoryIllusion,
		Type:     SpellTypePhysical,
		Range:    SpellRangeTouch,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"phantasm": {
		Name:     "Phantasm",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"trid_phantasm": {
		Name:     "Trid Phantasm",
		Category: SpellCategoryIllusion,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Multi-Sense", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"hush": {
		Name:     "Hush",
		Category: SpellCategoryIllusion,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Single-Sense", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"silence": {
		Name:     "Silence",
		Category: SpellCategoryIllusion,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Single-Sense", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"stealth": {
		Name:     "Stealth",
		Category: SpellCategoryIllusion,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Realistic", "Single-Sense"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	// Manipulation Spells
	"animate": {
		Name:     "Animate",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Physical"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"mass_animate": {
		Name:     "Mass Animate",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 1, Formula: "F+1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Physical", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"armor": {
		Name:     "Armor",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Physical"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"control_actions": {
		Name:     "Control Actions",
		Category: SpellCategoryManipulation,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Mental"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"mob_control": {
		Name:     "Mob Control",
		Category: SpellCategoryManipulation,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 1, Formula: "F+1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Mental", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"control_thoughts": {
		Name:     "Control Thoughts",
		Category: SpellCategoryManipulation,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Mental"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"mob_mind": {
		Name:     "Mob Mind",
		Category: SpellCategoryManipulation,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: 1, Formula: "F+1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Mental", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"fling": {
		Name:     "Fling",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Physical", "Damaging"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"ice_sheet": {
		Name:     "Ice Sheet",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeInstantaneous,
		Drain:    DrainFormula{BaseModifier: 0, Formula: "F", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Environmental", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"ignite": {
		Name:     "Ignite",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypePermanent,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Physical"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"influence": {
		Name:     "Influence",
		Category: SpellCategoryManipulation,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypePermanent,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Mental"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"levitate": {
		Name:     "Levitate",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Physical"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"light": {
		Name:     "Light",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -4, Formula: "F-4", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Environmental", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"magic_fingers": {
		Name:     "Magic Fingers",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSight,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Physical"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"mana_barrier": {
		Name:     "Mana Barrier",
		Category: SpellCategoryManipulation,
		Type:     SpellTypeMana,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Environmental", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"physical_barrier": {
		Name:     "Physical Barrier",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -1, Formula: "F-1", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Environmental", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"poltergeist": {
		Name:     "Poltergeist",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -2, Formula: "F-2", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Environmental", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
	"shadow": {
		Name:     "Shadow",
		Category: SpellCategoryManipulation,
		Type:     SpellTypePhysical,
		Range:    SpellRangeLineOfSightArea,
		IsArea:   true,
		Duration: DurationTypeSustained,
		Drain:    DrainFormula{BaseModifier: -3, Formula: "F-3", MinimumDrain: 2},
		Effects: SpellEffect{
			Keywords: []string{"Environmental", "Area"},
		},
		Source: &SourceReference{Source: "SR5"},
	},
}

// damageTypePtr returns a pointer to a SpellDamageType
func damageTypePtr(dt SpellDamageType) *SpellDamageType {
	return &dt
}
