package v5

// DataStreamTradition contains the stream tradition
var DataStreamTradition = StreamTradition{
	ID:      "7a3ecfbe-616e-425d-b204-329de37ffdbb",
	Name:    "Default",
	Drain:   "{WIL} + {RES}",
	Source:  "SR5",
	Page:    "258",
	Spirits: &StreamTraditionSpirits{Spirit: []interface{}{"Courier Sprite", "Crack Sprite", "Data Sprite", "Fault Sprite", "Machine Sprite", "Companion Sprite", "Generalist Sprite"}},
}

// DataStreamSpirits contains stream spirit records keyed by their ID (lowercase with underscores)
var DataStreamSpirits = map[string]StreamSpirit{
	"courier_sprite": {
		ID:     "acf0c123-0881-4f13-8a98-010516e74019",
		Name:   "Courier Sprite",
		Page:   "258",
		Source: "SR5",
		BOD:    "0",
		AGI:    "0",
		REA:    "0",
		STR:    "0",
		CHA:    "F+0",
		INT:    "F+3",
		LOG:    "F+1",
		WIL:    "F+2",
		INI:    "(F*2)+1",
		Powers: &StreamSpiritPowers{Power: []interface{}{"Cookie", "Hash"}},
		Skills: &StreamSpiritSkills{Skill: []interface{}{"Computer", "Hacking"}},
	},
	"crack_sprite": {
		ID:     "610c00a4-7f11-4c88-8074-158f33aeccc0",
		Name:   "Crack Sprite",
		Page:   "258",
		Source: "SR5",
		BOD:    "0",
		AGI:    "0",
		REA:    "0",
		STR:    "0",
		CHA:    "F+0",
		INT:    "F+3",
		LOG:    "F+2",
		WIL:    "F+1",
		INI:    "(F*2)+2",
		Powers: &StreamSpiritPowers{Power: "Suppression"},
		Skills: &StreamSpiritSkills{Skill: []interface{}{"Computer", "Electronic Warfare", "Hacking"}},
	},
	"data_sprite": {
		ID:     "61357134-dd63-442c-b532-355420b30b6e",
		Name:   "Data Sprite",
		Page:   "258",
		Source: "SR5",
		BOD:    "0",
		AGI:    "0",
		REA:    "0",
		STR:    "0",
		CHA:    "F-1",
		INT:    "F+0",
		LOG:    "F+4",
		WIL:    "F+1",
		INI:    "(F*2)+4",
		Powers: &StreamSpiritPowers{Power: []interface{}{"Camouflage", "Watermark"}},
		Skills: &StreamSpiritSkills{Skill: []interface{}{"Computer", "Electronic Warfare"}},
	},
	"fault_sprite": {
		ID:     "c3be27c2-247c-4039-9529-2ff3b2e670ec",
		Name:   "Fault Sprite",
		Page:   "258",
		Source: "SR5",
		BOD:    "0",
		AGI:    "0",
		REA:    "0",
		STR:    "0",
		CHA:    "F+3",
		INT:    "F+0",
		LOG:    "F+1",
		WIL:    "F+2",
		INI:    "(F*2)+1",
		Powers: &StreamSpiritPowers{Power: "Electron Storm"},
		Skills: &StreamSpiritSkills{Skill: []interface{}{"Computer", "Cybercombat", "Hacking"}},
	},
	"machine_sprite": {
		ID:     "80bd0cd6-fcaa-49c2-a88f-c28b4eb28c61",
		Name:   "Machine Sprite",
		Page:   "258",
		Source: "SR5",
		BOD:    "0",
		AGI:    "0",
		REA:    "0",
		STR:    "0",
		CHA:    "F+1",
		INT:    "F+0",
		LOG:    "F+3",
		WIL:    "F+2",
		INI:    "(F*2)+3",
		Powers: &StreamSpiritPowers{Power: []interface{}{"Diagnostics", "Gremlins", "Stability"}},
		Skills: &StreamSpiritSkills{Skill: []interface{}{"Computer", "Electronic Warfare", "Hardware"}},
	},
	"companion_sprite": {
		ID:     "74db183e-2fef-4e6d-84a3-63e641d93bf0",
		Name:   "Companion Sprite",
		Page:   "100",
		Source: "KC",
		BOD:    "0",
		AGI:    "0",
		REA:    "0",
		STR:    "0",
		CHA:    "F-1",
		INT:    "F+1",
		LOG:    "F",
		WIL:    "F+4",
		INI:    "(F*2)",
		Powers: &StreamSpiritPowers{Power: []interface{}{"Bodyguard", "Shield"}},
		Skills: &StreamSpiritSkills{Skill: []interface{}{"Computer", "Electronic Warfare"}},
	},
	"generalist_sprite": {
		ID:             "80788abc-4b14-40b0-8ffd-e36fe60653cb",
		Name:           "Generalist Sprite",
		Page:           "100",
		Source:         "KC",
		BOD:            "0",
		AGI:            "0",
		REA:            "0",
		STR:            "0",
		CHA:            "F+1",
		INT:            "F+1",
		LOG:            "F+1",
		WIL:            "F+1",
		INI:            "(F*2)+1",
		OptionalPowers: &StreamSpiritOptionalPowers{Power: []interface{}{"Cookie", "Hash", "Suppression", "Camouflage", "Watermark", "Electron Storm", "Diagnostics", "Gremlins", "Stability", "Bodyguard", "Shield"}},
		Skills:         &StreamSpiritSkills{Skill: []interface{}{"Computer", "Electronic Warfare", "Hacking"}},
	},
}
