package v5

// DataTraditions contains tradition records keyed by their ID (lowercase with underscores)
var DataTraditions = map[string]Tradition{
	"custom": {
		ID:     "616ba093-306c-45fc-8f41-0b98c8cccb46",
		Name:   "Custom",
		Source: "SR5",
		Page:   "279",
	},
	"hermetic": {
		ID:      "19320625-bc1a-492f-8904-da6a847e5700",
		Name:    "Hermetic",
		Source:  "SR5",
		Page:    "279",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Air", SpiritHealth: "Spirit of Man", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Spirit of Earth"},
	},
	"shamanic": {
		ID:      "8d185e0e-5f49-4992-babd-d1ac9c848f68",
		Name:    "Shamanic",
		Source:  "SR5",
		Page:    "279",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Man"},
	},
	"aztec": {
		ID:      "4fba452f-a240-4530-82b6-5ffd4bb83f28",
		Name:    "Aztec",
		Source:  "SG",
		Page:    "41",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Fire", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Spirit of Beasts"},
	},
	"black_magic": {
		ID:      "66ceefed-2cb1-4027-96ca-756ab4eed7ad",
		Name:    "Black Magic",
		Source:  "SG",
		Page:    "41",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Man"},
	},
	"black_magic_alt": {
		ID:      "09843ed9-6fd1-4c43-9e9f-f6d66493ebdc",
		Name:    "Black Magic [Alt]",
		Source:  "FA",
		Page:    "61",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Man"},
	},
	"buddhism": {
		ID:      "a283220f-2197-4526-b15a-331b9185b326",
		Name:    "Buddhism",
		Source:  "SG",
		Page:    "43",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Air", SpiritDetection: "Guidance Spirit", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Fire", SpiritManipulation: "Spirit of Water"},
	},
	"chaos_magic": {
		ID:      "20b8e39f-a956-49bd-b417-6e1bd4a14604",
		Name:    "Chaos Magic",
		Source:  "SG",
		Page:    "44",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Air", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Man", SpiritManipulation: "Spirit of Water"},
	},
	"christian_theurgy": {
		ID:      "5d98ea69-29b1-4fb4-b9f3-56396d1dce16",
		Name:    "Christian Theurgy",
		Source:  "SG",
		Page:    "44",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Air", SpiritIllusion: "Spirit of Earth", SpiritManipulation: "Guidance Spirit"},
	},
	"druid": {
		ID:      "fb6f9683-47bb-4b04-9d15-4b59a003bf69",
		Name:    "Druid",
		Source:  "SG",
		Page:    "45",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Spirit of Water", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Earth"},
	},
	"hinduism": {
		ID:      "2c924aa1-2298-4b02-b28b-946d0769dbd3",
		Name:    "Hinduism",
		Source:  "SG",
		Page:    "46",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Spirit of Water", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Earth"},
	},
	"islam": {
		ID:      "9acc0a3e-3209-4274-9c98-4cbc42c456a7",
		Name:    "Islam",
		Source:  "SG",
		Page:    "46",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"path_of_the_wheel": {
		ID:      "7f6073fd-e7f3-41f5-a40f-2a5b1cde382e",
		Name:    "Path of the Wheel",
		Source:  "SG",
		Page:    "47",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Earth", SpiritDetection: "Guidance Spirit", SpiritHealth: "Spirit of Air", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Spirit of Fire"},
	},
	"qabbalism": {
		ID:         "c3604051-9f2b-4cc3-9525-f3029c611926",
		Name:       "Qabbalism",
		Source:     "SG",
		Page:       "48",
		Drain:      &[]string{"{WIL} + {LOG}"}[0],
		Spirits:    &TraditionSpirits{SpiritCombat: "Spirit of Air", SpiritDetection: "Spirit of Earth", SpiritHealth: "Spirit of Fire", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Task Spirit"},
		SpiritForm: &[]string{"Possession"}[0],
	},
	"quimbanda": {
		ID:      "93604cb7-2e12-47be-9c2d-4b227439f07b",
		Name:    "Quimbanda",
		Source:  "SFME",
		Page:    "13",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Man"},
	},
	"shinto": {
		ID:      "9abbebc1-48a3-4dde-960a-af565b163a3d",
		Name:    "Shinto",
		Source:  "SG",
		Page:    "48",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Air", SpiritDetection: "Spirit of Water", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Beasts", SpiritManipulation: "Spirit of Man"},
	},
	"sioux": {
		ID:      "e548b126-5df3-4da5-a603-c0b6b252e982",
		Name:    "Sioux",
		Source:  "SG",
		Page:    "49",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Plant Spirit", SpiritHealth: "Spirit of Fire", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Guardian Spirit"},
	},
	"toxic": {
		ID:     "8A0D8BC6-47AC-4043-A916-E2681A4D5BD7",
		Name:   "Toxic",
		Source: "SG",
		Page:   "84",
	},
	"vodou": {
		ID:         "35ecfae9-0c2d-4084-a899-e91c230e209d",
		Name:       "Vodou",
		Source:     "SG",
		Page:       "50",
		Drain:      &[]string{"{WIL} + {CHA}"}[0],
		Spirits:    &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Man", SpiritIllusion: "Guidance Spirit", SpiritManipulation: "Task Spirit"},
		SpiritForm: &[]string{"Possession"}[0],
	},
	"wicca_gardnerian": {
		ID:      "24601762-ef67-44d8-b974-03f626db848a",
		Name:    "Wicca, Gardnerian",
		Source:  "SG",
		Page:    "50",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Earth"},
	},
	"wicca_goddess": {
		ID:      "895b2dd2-f401-477e-9cb5-a5620598582e",
		Name:    "Wicca, Goddess",
		Source:  "SG",
		Page:    "50",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Earth"},
	},
	"wuxing": {
		ID:      "0cd0412c-cba4-4417-bc8f-f785fa5b821d",
		Name:    "Wuxing",
		Source:  "SG",
		Page:    "51",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Guidance Spirit"},
	},
	"zoroastrianism": {
		ID:      "9f4bae13-56fd-43ac-a6aa-8e2384018065",
		Name:    "Zoroastrianism",
		Source:  "SG",
		Page:    "52",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Man", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Fire", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Plant Spirit"},
	},
	"insect_shaman": {
		ID:         "0d13bad3-9fa2-45fb-879c-068916944e1b",
		Name:       "Insect Shaman",
		Source:     "SG",
		Page:       "94",
		Drain:      &[]string{"{WIL} + {INT}"}[0],
		Spirits:    &TraditionSpirits{SpiritCombat: "Soldier Spirit", SpiritDetection: "Scout Spirit", SpiritHealth: "Caretaker Spirit", SpiritIllusion: "Nymph Spirit", SpiritManipulation: "Worker Spirit"},
		SpiritForm: &[]string{"Inhabitation"}[0],
	},
	"aboriginal": {
		ID:      "b8b6ba39-5f5e-4581-9145-6409bd59776c",
		Name:    "Aboriginal",
		Source:  "SSP",
		Page:    "3",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Guidance Spirit", SpiritManipulation: "Spirit of Air"},
	},
	"egyptian": {
		ID:         "30109563-d9cb-4ced-b06b-6c3d0c4f5a34",
		Name:       "Egyptian",
		Source:     "SSP",
		Page:       "3",
		Drain:      &[]string{"{WIL} + {INT}"}[0],
		Spirits:    &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Earth", SpiritHealth: "Spirit of Air", SpiritIllusion: "Guidance Spirit", SpiritManipulation: "Spirit of Water"},
		SpiritForm: &[]string{"Possession"}[0],
	},
	"norse": {
		ID:      "43bc28ad-8818-4062-9b55-317f45d1e04e",
		Name:    "Norse",
		Source:  "SSP",
		Page:    "4",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"psionic": {
		ID:         "cc9f9b43-ef41-4581-8f9c-e1000e5a1578",
		Name:       "Psionic",
		Source:     "SSP",
		Page:       "5",
		Drain:      &[]string{"{WIL} + {INT}"}[0],
		Spirits:    &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Air", SpiritHealth: "Spirit of Man", SpiritIllusion: "Guidance Spirit", SpiritManipulation: "Task Spirit"},
		SpiritForm: &[]string{"Possession"}[0],
	},
	"obeah": {
		ID:      "acbf5a08-cd21-410d-8d04-4e12cca8a927",
		Name:    "Obeah",
		Source:  "HT",
		Page:    "130",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Man", SpiritIllusion: "Guidance Spirit", SpiritManipulation: "Task Spirit"},
	},
	"santeria": {
		ID:         "81789f32-779d-488e-ac76-d1005b5a2d2a",
		Name:       "Santeria",
		Source:     "HT",
		Page:       "130",
		Drain:      &[]string{"{WIL} + {INT}"}[0],
		Spirits:    &TraditionSpirits{SpiritCombat: "Guidance Spirit", SpiritDetection: "Guardian Spirit", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Man", SpiritManipulation: "Spirit of Water"},
		SpiritForm: &[]string{"Possession"}[0],
	},
	"buddhism_traditionalist": {
		ID:      "8b7a391e-8d4c-40e8-93a8-9dd031cce0f5",
		Name:    "Buddhism [Traditionalist]",
		Source:  "FA",
		Page:    "62",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Air", SpiritDetection: "Guidance Spirit", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Fire", SpiritManipulation: "Spirit of Water"},
	},
	"christian_theurgy_traditional": {
		ID:      "dd97bcc9-a731-41fb-a558-9175bc56b587",
		Name:    "Christian Theurgy [Traditional]",
		Source:  "FA",
		Page:    "64",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Air", SpiritIllusion: "Spirit of Earth", SpiritManipulation: "Guidance Spirit"},
	},
	"christian_theurgy_vigila_evangelica": {
		ID:      "ca673acd-961e-4491-8a8d-ddf0c577441b",
		Name:    "Christian Theurgy [Vigila Evangelica]",
		Source:  "FA",
		Page:    "64",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Air", SpiritIllusion: "Spirit of Earth", SpiritManipulation: "Guidance Spirit"},
	},
	"christian_theurgy_westphalian": {
		ID:      "3a7bf066-7b13-4a92-ae31-37a58f84bc8e",
		Name:    "Christian Theurgy [Westphalian]",
		Source:  "FA",
		Page:    "64",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Water", SpiritHealth: "Spirit of Air", SpiritIllusion: "Spirit of Earth", SpiritManipulation: "Guidance Spirit"},
	},
	"cosmic": {
		ID:      "54944188-d58b-4a45-859c-d62be9f966c2",
		Name:    "Cosmic",
		Source:  "FA",
		Page:    "75",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Earth", SpiritDetection: "Guidance Spirit", SpiritHealth: "Spirit of Water", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"draconic": {
		ID:      "9394d173-eee7-4e5a-b520-edfdfac3cf8b",
		Name:    "Draconic",
		Source:  "FA",
		Page:    "76",
		Drain:   &[]string{"{WIL} + {MAG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "All", SpiritDetection: "All", SpiritHealth: "All", SpiritIllusion: "All", SpiritManipulation: "All"},
	},
	"druid_alt": {
		ID:      "a0c2d67d-158a-4fdf-9c45-7f420fbdce8e",
		Name:    "Druid [Alt]",
		Source:  "FA",
		Page:    "65",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Spirit of Water", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Earth"},
	},
	"druid_traditional": {
		ID:      "77288f4d-e262-47b6-aad8-2edff23859cb",
		Name:    "Druid [Traditional]",
		Source:  "FA",
		Page:    "65",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Spirit of Water", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Earth"},
	},
	"elder_god": {
		ID:      "4bbe470b-51a7-494b-8ccf-5c638e141049",
		Name:    "Elder God",
		Source:  "FA",
		Page:    "78",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Task Spirit", SpiritDetection: "Guardian Spirit", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Fire", SpiritManipulation: "Spirit of Water"},
	},
	"green_magic": {
		ID:      "61819d3f-2ca6-4e1e-9d66-5d94c1560733",
		Name:    "Green Magic",
		Source:  "FA",
		Page:    "80",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Plant Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Spirit of Water", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"islam_islamic_alchemist": {
		ID:      "ad6f8984-f0c2-41e9-a2d1-73a719d21a06",
		Name:    "Islam [Islamic Alchemist]",
		Source:  "FA",
		Page:    "69",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"islam_licit_quranic": {
		ID:      "328d6c96-9e10-424f-bbed-b6e1d1035bd2",
		Name:    "Islam [Licit Qur'anic]",
		Source:  "FA",
		Page:    "69",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"missionist": {
		ID:      "b8b93cfb-5bdf-47c6-b773-45c59ef7bd34",
		Name:    "Missionist",
		Source:  "FA",
		Page:    "81",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Man", SpiritDetection: "Spirit of Air", SpiritHealth: "Spirit of Water", SpiritIllusion: "Spirit of Fire", SpiritManipulation: "Spirit of Earth"},
	},
	"necro_magic": {
		ID:      "68a35424-6de8-4922-95ec-eb289838acb2",
		Name:    "Necro Magic",
		Source:  "FA",
		Page:    "82",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Corpse Spirit", SpiritDetection: "Carcass Spirit", SpiritHealth: "Rot Spirit", SpiritIllusion: "Detritus Spirit", SpiritManipulation: "Palefire Spirit"},
	},
	"norse_alt": {
		ID:      "9c211dbe-6a37-4872-80fa-37d845d76668",
		Name:    "Norse [Alt]",
		Source:  "FA",
		Page:    "68",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"norse_godirunemaster": {
		ID:      "2ea02939-030b-407b-b569-c2f39f301999",
		Name:    "Norse [Godi/Runemaster]",
		Source:  "FA",
		Page:    "68",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"norse_cunning_woman": {
		ID:      "fa341243-5134-42ad-9259-454bf18a26fd",
		Name:    "Norse [Cunning Woman]",
		Source:  "FA",
		Page:    "68",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"norse_berserker": {
		ID:      "52668f12-2895-48e1-8b84-2382ef0fcee0",
		Name:    "Norse [Berserker]",
		Source:  "FA",
		Page:    "68",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"norse_seidman": {
		ID:      "990cdff5-2fd1-48aa-b085-a7d0ff183d00",
		Name:    "Norse [Seidman]",
		Source:  "FA",
		Page:    "68",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Earth", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Fire"},
	},
	"olympianism": {
		ID:      "f87723cf-ed66-4372-8064-365151dd1089",
		Name:    "Olympianism",
		Source:  "FA",
		Page:    "84",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Air", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Spirit of Fire"},
	},
	"pariah": {
		ID:     "52348ffc-2d9b-427b-a546-863a9670127e",
		Name:   "Pariah",
		Source: "FA",
		Page:   "85",
		Drain:  &[]string{"{WIL} + {LOG}"}[0],
	},
	"planar_magic": {
		ID:      "eca20088-da31-4b00-bf81-93db882f3575",
		Name:    "Planar Magic",
		Source:  "FA",
		Page:    "87",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Guidance Spirit", SpiritHealth: "Spirit of Water", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Task Spirit"},
	},
	"red_magic": {
		ID:      "a5c6f673-bd53-4e70-a574-af2f5a1c2e60",
		Name:    "Red Magic",
		Source:  "FA",
		Page:    "88",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Spirit of Air", SpiritHealth: "Spirit of Water", SpiritIllusion: "Spirit of Earth", SpiritManipulation: "Spirit of Man"},
	},
	"romani": {
		ID:      "bd5bb80f-d1be-4ec8-b972-af45dc05e0fb",
		Name:    "Romani",
		Source:  "FA",
		Page:    "90",
		Drain:   &[]string{"{WIL} + {WIL}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Air", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Spirit of Earth"},
	},
	"tarot": {
		ID:      "2cd90e8a-3674-470e-b95d-eb80c008fc4a",
		Name:    "Tarot",
		Source:  "FA",
		Page:    "91",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Air", SpiritDetection: "Spirit of Fire", SpiritHealth: "Spirit of Water", SpiritIllusion: "Spirit of Man", SpiritManipulation: "Spirit of Earth"},
	},
	"armanentradition": {
		ID:      "9147b372-b55f-4b4b-8f24-04a4dd05aa1a",
		Name:    "Armanentradition",
		Source:  "SAG",
		Page:    "111",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Guidance Spirit", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Task Spirit"},
	},
	"dianism": {
		ID:      "7d2ee0fa-92ab-4fec-86c9-e2f3964456e7",
		Name:    "Dianism",
		Source:  "SAG",
		Page:    "112",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Spirit of Fire", SpiritHealth: "Spirit of Air", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Spirit of Man"},
	},
	"frisian_magic": {
		ID:      "a8f9687a-0999-4509-87a2-4b122fb2187c",
		Name:    "Frisian Magic",
		Source:  "SAG",
		Page:    "113",
		Drain:   &[]string{"{WIL} + {LOG}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Water", SpiritDetection: "Spirit of Earth", SpiritHealth: "Guidance Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Plant Spirit"},
	},
	"magic_of_roma_and_street_nomads": {
		ID:      "27109795-aead-463c-848c-fa63e5aa11cd",
		Name:    "Magic of Roma and Street Nomads",
		Source:  "SAG",
		Page:    "114",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Beasts", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Man"},
	},
	"svetoid": {
		ID:      "4eaf37d8-1fa9-4ba3-898a-3130a62fe09e",
		Name:    "Svetoid",
		Source:  "SAG",
		Page:    "115",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Earth", SpiritDetection: "Guidance Spirit", SpiritHealth: "Plant Spirit", SpiritIllusion: "Spirit of Man", SpiritManipulation: "Spirit of Water"},
	},
	"troll_shamanism": {
		ID:      "232c8cfe-b70a-4fb8-9dc3-ecc993cf6203",
		Name:    "Troll Shamanism",
		Source:  "SAG",
		Page:    "115",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Earth", SpiritHealth: "Guardian Spirit", SpiritIllusion: "Spirit of Water", SpiritManipulation: "Plant Spirit"},
	},
	"dark_magic": {
		ID:      "66826a89-61fb-4f4d-99d9-d96c0956b83f",
		Name:    "Dark Magic",
		Source:  "DTR",
		Page:    "165",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Earth", SpiritHealth: "Spirit of Water", SpiritIllusion: "Spirit of Air", SpiritManipulation: "Spirit of Man"},
	},
	"dr_singer_school": {
		ID:      "c0405095-5304-4fbd-b955-203a11f88b73",
		Name:    "Dr.-Singer-School",
		Source:  "SHB3",
		Page:    "169",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Beasts", SpiritDetection: "Task Spirit", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Guidance Spirit", SpiritManipulation: "Spirit of Man"},
	},
	"storm_children": {
		ID:      "53a919e6-739d-4418-aaff-79e9df17e3b6",
		Name:    "Storm Children",
		Source:  "SHB3",
		Page:    "169",
		Drain:   &[]string{"{WIL} + {INT}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Spirit of Fire", SpiritDetection: "Spirit of Beasts", SpiritHealth: "Spirit of Earth", SpiritIllusion: "Plant Spirit", SpiritManipulation: "Spirit of Air"},
	},
	"storyteller": {
		ID:      "deea732f-5768-4d13-8796-c93d0000c5c6",
		Name:    "Storyteller",
		Source:  "GE",
		Page:    "68",
		Drain:   &[]string{"{WIL} + {CHA}"}[0],
		Spirits: &TraditionSpirits{SpiritCombat: "Guardian Spirit", SpiritDetection: "Spirit of Beasts", SpiritHealth: "Task Spirit", SpiritIllusion: "Guidance Spirit", SpiritManipulation: "Spirit of Man"},
	},
}

// DataDrainAttributes contains drain attribute records keyed by their ID (lowercase with underscores)
var DataDrainAttributes = map[string]DrainAttribute{
	"wil_cha": {
		ID:   "f10d9639-45c8-4c45-87b9-6af0fef73723",
		Name: "{WIL} + {CHA}",
	},
	"wil_int": {
		ID:   "06b8b7da-1301-4963-aba7-4862024559a8",
		Name: "{WIL} + {INT}",
	},
	"wil_log": {
		ID:   "aca1fd74-0c25-41d5-b621-434c3892cfb3",
		Name: "{WIL} + {LOG}",
	},
	"wil_mag": {
		ID:   "c8adb0ec-7592-4801-b560-94805ef1c13e",
		Name: "{WIL} + {MAG}",
	},
	"wil_wil": {
		ID:   "f59248c7-7843-4b68-9a26-b966c32c8cae",
		Name: "{WIL} + {WIL}",
	},
}
