package v5

// dataVehicles contains all vehicle and drone definitions
var dataVehicles = map[string]Vehicle{
	// Groundcraft - Bikes
	"dodge_scoot": {
		Name:         "Dodge Scoot",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeBike,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 3, MovementType: MovementTypeGround},
		Acceleration: 1,
		Body:         BodyRating{Value: 4},
		Armor:        4,
		Pilot:        1,
		Sensor:       1,
		Seats:        intPtr(1),
		Cost:         3000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"harley_davidson_scorpion": {
		Name:         "Harley-Davidson Scorpion",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeBike,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 4, MovementType: MovementTypeGround},
		Acceleration: 2,
		Body:         BodyRating{Value: 8},
		Armor:        9,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(1),
		Cost:         12000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"yamaha_growler": {
		Name:         "Yamaha Growler",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeBike,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(5)},
		Speed:        SpeedRating{Value: 3, AlternativeSpeed: intPtr(4), MovementType: MovementTypeGround},
		Acceleration: 1,
		Body:         BodyRating{Value: 5},
		Armor:        5,
		Pilot:        1,
		Sensor:       1,
		Seats:        intPtr(1),
		Cost:         5000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"suzuki_mirage": {
		Name:         "Suzuki Mirage",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeBike,
		Handling:     HandlingRating{OnRoad: 5, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 6, MovementType: MovementTypeGround},
		Acceleration: 3,
		Body:         BodyRating{Value: 5},
		Armor:        6,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(1),
		Cost:         8500,
		Source:       &SourceReference{Source: "SR5"},
	},
	// Groundcraft - Cars
	"americar": {
		Name:         "Americar",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeCar,
		Handling:     HandlingRating{OnRoad: 3, OffRoad: intPtr(2)},
		Speed:        SpeedRating{Value: 4, MovementType: MovementTypeGround},
		Acceleration: 2,
		Body:         BodyRating{Value: 8},
		Armor:        6,
		Pilot:        1,
		Sensor:       1,
		Seats:        intPtr(4),
		Cost:         15000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"ford_americar": {
		Name:         "Ford Americar",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeCar,
		Handling:     HandlingRating{OnRoad: 3, OffRoad: intPtr(2)},
		Speed:        SpeedRating{Value: 4, MovementType: MovementTypeGround},
		Acceleration: 2,
		Body:         BodyRating{Value: 8},
		Armor:        6,
		Pilot:        1,
		Sensor:       1,
		Seats:        intPtr(4),
		Cost:         15000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"gmc_bulldog_step_van": {
		Name:         "GMC Bulldog Step-Van",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeCar,
		Handling:     HandlingRating{OnRoad: 2, OffRoad: intPtr(1)},
		Speed:        SpeedRating{Value: 3, MovementType: MovementTypeGround},
		Acceleration: 1,
		Body:         BodyRating{Value: 12},
		Armor:        8,
		Pilot:        1,
		Sensor:       1,
		Seats:        intPtr(2),
		Cost:         25000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"gmc_chameleon": {
		Name:         "GMC Chameleon",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeCar,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 4, MovementType: MovementTypeGround},
		Acceleration: 2,
		Body:         BodyRating{Value: 6},
		Armor:        4,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(4),
		Cost:         18000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"hyundai_shin_hyung": {
		Name:         "Hyundai Shin-Hyung",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeCar,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 4, MovementType: MovementTypeGround},
		Acceleration: 2,
		Body:         BodyRating{Value: 6},
		Armor:        5,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(4),
		Cost:         20000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"mitsubishi_nightsky": {
		Name:         "Mitsubishi Nightsky",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeCar,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 5, MovementType: MovementTypeGround},
		Acceleration: 3,
		Body:         BodyRating{Value: 6},
		Armor:        6,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(4),
		Cost:         35000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"rover_2062": {
		Name:         "Rover 2062",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeCar,
		Handling:     HandlingRating{OnRoad: 3, OffRoad: intPtr(2)},
		Speed:        SpeedRating{Value: 4, MovementType: MovementTypeGround},
		Acceleration: 2,
		Body:         BodyRating{Value: 8},
		Armor:        6,
		Pilot:        1,
		Sensor:       1,
		Seats:        intPtr(4),
		Cost:         18000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"toyota_gopher": {
		Name:         "Toyota Gopher",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeCar,
		Handling:     HandlingRating{OnRoad: 3, OffRoad: intPtr(2)},
		Speed:        SpeedRating{Value: 3, MovementType: MovementTypeGround},
		Acceleration: 1,
		Body:         BodyRating{Value: 8},
		Armor:        5,
		Pilot:        1,
		Sensor:       1,
		Seats:        intPtr(4),
		Cost:         12000,
		Source:       &SourceReference{Source: "SR5"},
	},
	// Groundcraft - Trucks
	"gmc_banshee": {
		Name:         "GMC Banshee",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeTruck,
		Handling:     HandlingRating{OnRoad: 3, OffRoad: intPtr(2)},
		Speed:        SpeedRating{Value: 4, MovementType: MovementTypeGround},
		Acceleration: 2,
		Body:         BodyRating{Value: 10},
		Armor:        8,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(2),
		Cost:         30000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"gmc_phoenix": {
		Name:         "GMC Phoenix",
		Type:         VehicleTypeGroundcraft,
		Subtype:      VehicleSubtypeTruck,
		Handling:     HandlingRating{OnRoad: 3, OffRoad: intPtr(2)},
		Speed:        SpeedRating{Value: 4, MovementType: MovementTypeGround},
		Acceleration: 2,
		Body:         BodyRating{Value: 10},
		Armor:        8,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(2),
		Cost:         35000,
		Source:       &SourceReference{Source: "SR5"},
	},
	// Groundcraft - Other
	"ares_roadmaster": {
		Name:            "Ares Roadmaster",
		Type:            VehicleTypeGroundcraft,
		Subtype:         VehicleSubtypeOtherGroundcraft,
		VehicleTypeName: "Limo",
		Handling:        HandlingRating{OnRoad: 2, OffRoad: intPtr(1)},
		Speed:           SpeedRating{Value: 3, MovementType: MovementTypeGround},
		Acceleration:    1,
		Body:            BodyRating{Value: 14},
		Armor:           12,
		Pilot:           1,
		Sensor:          2,
		Seats:           intPtr(6),
		Cost:            80000,
		Source:          &SourceReference{Source: "SR5"},
	},
	"gmc_armadillo": {
		Name:            "GMC Armadillo",
		Type:            VehicleTypeGroundcraft,
		Subtype:         VehicleSubtypeOtherGroundcraft,
		VehicleTypeName: "Armored Vehicle",
		Handling:        HandlingRating{OnRoad: 2, OffRoad: intPtr(1)},
		Speed:           SpeedRating{Value: 3, MovementType: MovementTypeGround},
		Acceleration:    1,
		Body:            BodyRating{Value: 16},
		Armor:           20,
		Pilot:           1,
		Sensor:          2,
		Seats:           intPtr(2),
		Cost:            120000,
		Source:          &SourceReference{Source: "SR5"},
	},
	// Watercraft
	"horizon_dreamliner": {
		Name:         "Horizon Dreamliner",
		Type:         VehicleTypeWatercraft,
		Handling:     HandlingRating{OnRoad: 2, OffRoad: intPtr(1)},
		Speed:        SpeedRating{Value: 4, MovementType: MovementTypeWater},
		Acceleration: 1,
		Body:         BodyRating{Value: 12},
		Armor:        4,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(8),
		Cost:         45000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"yamaha_rapier": {
		Name:         "Yamaha Rapier",
		Type:         VehicleTypeWatercraft,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 5, MovementType: MovementTypeWater},
		Acceleration: 2,
		Body:         BodyRating{Value: 4},
		Armor:        2,
		Pilot:        1,
		Sensor:       1,
		Seats:        intPtr(1),
		Cost:         8000,
		Source:       &SourceReference{Source: "SR5"},
	},
	// Aircraft
	"ares_dragon": {
		Name:         "Ares Dragon",
		Type:         VehicleTypeAircraft,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 6, MovementType: MovementTypeJet},
		Acceleration: 2,
		Body:         BodyRating{Value: 8},
		Armor:        6,
		Pilot:        1,
		Sensor:       3,
		Seats:        intPtr(2),
		Cost:         150000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"horizon_little_bird": {
		Name:         "Horizon Little Bird",
		Type:         VehicleTypeAircraft,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 5, MovementType: MovementTypePropeller},
		Acceleration: 2,
		Body:         BodyRating{Value: 4},
		Armor:        2,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(1),
		Cost:         25000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"lockheed_optic_x": {
		Name:         "Lockheed Optic-X",
		Type:         VehicleTypeAircraft,
		Handling:     HandlingRating{OnRoad: 5, OffRoad: intPtr(4)},
		Speed:        SpeedRating{Value: 7, MovementType: MovementTypeJet},
		Acceleration: 3,
		Body:         BodyRating{Value: 6},
		Armor:        4,
		Pilot:        1,
		Sensor:       3,
		Seats:        intPtr(1),
		Cost:         200000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"northrup_wasp": {
		Name:         "Northrup Wasp",
		Type:         VehicleTypeAircraft,
		Handling:     HandlingRating{OnRoad: 4, OffRoad: intPtr(3)},
		Speed:        SpeedRating{Value: 6, MovementType: MovementTypeJet},
		Acceleration: 2,
		Body:         BodyRating{Value: 4},
		Armor:        2,
		Pilot:        1,
		Sensor:       2,
		Seats:        intPtr(1),
		Cost:         30000,
		Source:       &SourceReference{Source: "SR5"},
	},
	// Drones - Micro
	"mct_fly_spy": {
		Name:         "MCT Fly-Spy",
		Type:         VehicleTypeDrone,
		Subtype:      VehicleSubtypeMicroDrone,
		Handling:     HandlingRating{OnRoad: 2},
		Speed:        SpeedRating{Value: 1, MovementType: MovementTypeFlight},
		Acceleration: 1,
		Body:         BodyRating{Value: 1},
		Armor:        0,
		Pilot:        1,
		Sensor:       1,
		Cost:         500,
		Source:       &SourceReference{Source: "SR5"},
	},
	"shiawase_kanmushi": {
		Name:         "Shiawase Kanmushi",
		Type:         VehicleTypeDrone,
		Subtype:      VehicleSubtypeMicroDrone,
		Handling:     HandlingRating{OnRoad: 2},
		Speed:        SpeedRating{Value: 1, MovementType: MovementTypeFlight},
		Acceleration: 1,
		Body:         BodyRating{Value: 1},
		Armor:        0,
		Pilot:        1,
		Sensor:       1,
		Cost:         400,
		Source:       &SourceReference{Source: "SR5"},
	},
	// Drones - Mini
	"ares_duellist": {
		Name:         "Ares Duellist",
		Type:         VehicleTypeDrone,
		Subtype:      VehicleSubtypeMiniDrone,
		Handling:     HandlingRating{OnRoad: 3},
		Speed:        SpeedRating{Value: 2, MovementType: MovementTypeGround},
		Acceleration: 1,
		Body:         BodyRating{Value: 2},
		Armor:        0,
		Pilot:        1,
		Sensor:       1,
		Cost:         1200,
		Source:       &SourceReference{Source: "SR5"},
	},
	"mct_nissan_roto_drone": {
		Name:         "MCT-Nissan Roto-Drone",
		Type:         VehicleTypeDrone,
		Subtype:      VehicleSubtypeMiniDrone,
		Handling:     HandlingRating{OnRoad: 3},
		Speed:        SpeedRating{Value: 2, MovementType: MovementTypeGround},
		Acceleration: 1,
		Body:         BodyRating{Value: 2},
		Armor:        0,
		Pilot:        1,
		Sensor:       1,
		Cost:         1000,
		Source:       &SourceReference{Source: "SR5"},
	},
	"steel_lynx": {
		Name:         "Steel Lynx",
		Type:         VehicleTypeDrone,
		Subtype:      VehicleSubtypeMiniDrone,
		Handling:     HandlingRating{OnRoad: 3},
		Speed:        SpeedRating{Value: 3, MovementType: MovementTypeGround},
		Acceleration: 1,
		Body:         BodyRating{Value: 3},
		Armor:        0,
		Pilot:        2,
		Sensor:       2,
		Cost:         8000,
		Source:       &SourceReference{Source: "SR5"},
	},
}
