package v5

// dataWeapons contains all weapon definitions
var dataWeapons = map[string]Weapon{
	// MELEE WEAPONS - BLADES
	"combat_axe": {
		Name:        "Combat Axe",
		Type:        WeaponTypeMeleeBlade,
		Description: "A two-handed tungsten-alloy monster, available single- or double-bladed. A hardened thrusting point can be concealed, spring-loaded, in the handle. While it may seem barbaric or primitive, the physical augmentations of 2075 can make an old-school weapon like a combat axe even deadlier than a firearm in the right hands. So go ahead, go medieval.",
		Skill:       WeaponSkillBlades,
		Accuracy:    4,
		Damage:      "(STR+5)P",
		AP:          -4,
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Reach: 2,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"combat_knife": {
		Name:        "Combat Knife",
		Type:        WeaponTypeMeleeBlade,
		Description: "A long, KA-BAR-style fighting knife with a blacked-out blade and a chisel point for punching through armor.",
		Skill:       WeaponSkillBlades,
		Accuracy:    6,
		Damage:      "(STR+2)P",
		AP:          -3,
		Range:       "Reach",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"forearm_snap_blades": {
		Name:        "Forearm Snap-Blades",
		Type:        WeaponTypeMeleeBlade,
		Description: "These are essentially like spurs, only they're external—painless to install or remove. A forearm sheath conceals three blades that can be extended or retracted via wireless link or muscle movement commands.",
		Skill:       WeaponSkillBlades,
		Accuracy:    4,
		Damage:      "(STR+2)P",
		AP:          -2,
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Retractable: true,
		},
		WirelessBonus: &WirelessBonus{
			ActionChange: "Free Action instead of Simple Action",
			Description:  "Readying the forearm snap blades is a Free Action instead of a Simple Action.",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"katana": {
		Name:        "Katana",
		Type:        WeaponTypeMeleeBlade,
		Description: "The legendary two-handed sword of the samurai. The katana has become synonymous not just with street samurai, but with shadowrunners in general, at least in the trids; they've got everyone packing a katana, from the decker to the mage. But being a silly cliché doesn't make this blade any less dangerous, or less helpful in a fight.",
		Skill:       WeaponSkillBlades,
		Accuracy:    7,
		Damage:      "(STR+3)P",
		AP:          -3,
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Reach: 1,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"knife": {
		Name:        "Knife",
		Type:        WeaponTypeMeleeBlade,
		Description: "Your basic, all-purpose street cutter. It comes in a bewildering array of styles, colors, and flavors, but the statistics don't vary from one to the next. Ordinary knives are used by the poor, the desperate, or the cautious as backup weapons.",
		Skill:       WeaponSkillBlades,
		Accuracy:    5,
		Damage:      "(STR+1)P",
		AP:          -1,
		Range:       "Reach",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"pole_arm": {
		Name:        "Pole Arm",
		Type:        WeaponTypeMeleeBlade,
		Description: "This is, at its very essence, a blade on the end of a very long stick. It usually features an axe-head, glaive, spear point, or similar maiming implement. It's not easy to handle and it's just about impossible to conceal, but it's popular both with trolls and with melee combatants looking to safely keep said large trolls at more than arm's length.",
		Skill:       WeaponSkillBlades,
		Accuracy:    5,
		Damage:      "(STR+3)P",
		AP:          -2,
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Reach: 3,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"survival_knife": {
		Name:        "Survival Knife",
		Type:        WeaponTypeMeleeBlade,
		Description: "A fine quality blade—smooth on one edge, serrated on the other—with several accessories, including a GPS monitor, mini-multitool, micro-lighter, and a hidden compartment in the handle. The sides of the steel are coated with a non-toxic chemical that blacks out the blade when inert to prevent unwanted reflection, but can be activated to provide two hours of phosphorescent light. All knives can cut flesh, but a survival knife is better at cutting rope and wood, or otherwise being used as a tool. The survival knife is the kind of gadget that no professional should be without.",
		Skill:       WeaponSkillBlades,
		Accuracy:    5,
		Damage:      "(STR+2)P",
		AP:          -1,
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			BuiltInFeatures: []string{"GPS monitor", "mini-multitool", "micro-lighter", "hidden compartment", "phosphorescent light"},
		},
		WirelessBonus: &WirelessBonus{
			Description: "The knife displays an ARO of local maps, your GPS position, and can be used to make commcalls.",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"sword": {
		Name:        "Sword",
		Type:        WeaponTypeMeleeBlade,
		Description: "It's sharp, it's heavy, and it will fragging cut you wide open. Available in a wide variety of styles (wakizashi, seax, scimitar, jian, machete, and so on and so forth), this one-handed blade is not as formidable as a katana but is substantially easier to hide.",
		Skill:       WeaponSkillBlades,
		Accuracy:    6,
		Damage:      "(STR+3)P",
		AP:          -2,
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Reach: 1,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	// MELEE WEAPONS - CLUBS
	"club": {
		Name:        "Club",
		Type:        WeaponTypeMeleeClub,
		Description: "The weapon they named the skill after. These stats represent a range of objects, including an axe handle, baseball bat, wrench, crowbar, a tire iron, and a two-by-four with a rusty nail in it. There is a price listed, but it's not overly difficult to find one for free if you know where to look.",
		Skill:       WeaponSkillClubs,
		Accuracy:    4,
		Damage:      "(STR+3)P",
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Reach: 1,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"extendable_baton": {
		Name:        "Extendable Baton",
		Type:        WeaponTypeMeleeClub,
		Description: "This telescoping club can be collapsed, and it can be extended with a sharp flick of the wrist or a wireless signal. When retracted, it's more easily concealed (Concealability Modifier 0 when retracted, +2 when extended).",
		Skill:       WeaponSkillClubs,
		Accuracy:    5,
		Damage:      "(STR+2)P",
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Retractable:                         true,
			Reach:                               1,
			ConcealabilityModifierWhenRetracted: 0,
			ConcealabilityModifierWhenExtended:  2,
		},
		WirelessBonus: &WirelessBonus{
			ActionChange: "Free Action instead of Simple Action",
			Description:  "Readying the extendable baton is a Free Action instead of a Simple Action.",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"sap": {
		Name:        "Sap",
		Type:        WeaponTypeMeleeClub,
		Description: "Also called a blackjack, this is a small, springy club, or a flat piece of iron in a flexible leather covering. It's specially designed for concealment (Concealability Modifier –2).",
		Skill:       WeaponSkillClubs,
		Accuracy:    5,
		Damage:      "(STR+2)P",
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			ConcealabilityModifier: -2,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"staff": {
		Name:        "Staff",
		Type:        WeaponTypeMeleeClub,
		Description: "This large, heavy stick is popular with magicians going for that traditional look. Available in composite, hardwood, high-carbon steel, and other materials.",
		Skill:       WeaponSkillClubs,
		Accuracy:    6,
		Damage:      "(STR+3)P",
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Reach: 2,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"stun_baton": {
		Name:        "Stun Baton",
		Type:        WeaponTypeMeleeClub,
		Description: "A standard riot-control weapon, viewed as a tool and symbol of corporate-government oppressors but pragmatically useful to runners. It has ten charges and regains one charge per ten seconds when plugged in.",
		Skill:       WeaponSkillClubs,
		Accuracy:    4,
		Damage:      "9S(e)",
		AP:          -5,
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Reach:   1,
			Charges: "10 charges, regains 1 charge per 10 seconds when plugged in",
		},
		WirelessBonus: &WirelessBonus{
			Description: "The stun baton recharges by induction, regaining one charge per full hour of wireless-enabled time.",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	"telescoping_staff": {
		Name:        "Telescoping Staff",
		Type:        WeaponTypeMeleeClub,
		Description: "This is a metal and composite staff that can telescope down to a reasonable size, one that can be concealed about as easily as a stun baton or a sword. It can be extended and locked in place by whirling it at the correct speed and angle and twisting the grip, or via a wireless signal.",
		Skill:       WeaponSkillClubs,
		Accuracy:    4,
		Damage:      "(STR+2)P",
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Retractable: true,
			Reach:       2,
		},
		WirelessBonus: &WirelessBonus{
			ActionChange: "Free Action instead of Simple Action",
			Description:  "Readying the telescoping staff is a Free Action instead of a Simple Action.",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "421",
		},
	},
	// MELEE WEAPONS - OTHER
	"knucks": {
		Name:        "Knucks",
		Type:        WeaponTypeMeleeOther,
		Description: "These may be traditional fist-load weapons like brass knuckles, or modern \"Hardliner gloves\" with a thin layer of densiplast located along the knuckles and the edge of the hand. Either way they substantially boost the impact of a punch, making it potentially deadly. Attacks with knucks use the Unarmed Combat skill.",
		Skill:       WeaponSkillUnarmedCombat,
		Accuracy:    0, // Physical attribute
		Damage:      "(STR+1)P",
		Range:       "Reach",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"monofilament_whip": {
		Name:            "Monofilament Whip",
		Type:            WeaponTypeMeleeOther,
		Description:     "Iconic. Terrifying. Deadly. Few weapons on the street are more feared. This monofilament line can cut through bone and armor like hot butter. The line extends out to two meters, and retracts into the weapon's handle when not in use. The whip action, the weighted tip, and the deadly thread of the monofilament line itself make this weapon a potential danger to it's wielder. On a glitch, you catch the weighted tip on something nearby and need to disentangle it before you make another proper attack with it. On a critical glitch, you hit yourself with the whip and take its base damage (resisted normally). A monofilament whip requires the Exotic Melee Weapon (Monofilament Whip) skill to use.",
		Skill:           WeaponSkillExoticMeleeWeapon,
		ExoticSkillName: "Monofilament Whip",
		Accuracy:        5, // 7 with wireless
		Damage:          "12P",
		AP:              -8,
		Range:           "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Retractable:           true,
			Reach:                 2,
			GlitchEffects:         "catch the weighted tip on something nearby and need to disentangle it before making another proper attack",
			CriticalGlitchEffects: "hit yourself with the whip and take its base damage (resisted normally)",
		},
		WirelessBonus: &WirelessBonus{
			ActionChange: "Free Action instead of Simple Action",
			LimitBonus:   2,
			Description:  "The whip can be readied with a Free Action, rather than a Simple Action, and the whip's built-in safety system retracts automatically instead of getting you entangled on a glitch. The Accuracy is also increased by 2.",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"shock_gloves": {
		Name:        "Shock Gloves",
		Type:        WeaponTypeMeleeOther,
		Description: "These electrically insulated gloves have a wire mesh that discharges electric current with a punch or a simple touch. The gloves deal electricity damage (p. 170) and are good for ten charges before they need to be plugged in and recharged (at a rate of one charge per ten seconds). Attacks with shock gloves use the Unarmed Combat skill.",
		Skill:       WeaponSkillUnarmedCombat,
		Accuracy:    0, // Physical attribute
		Damage:      "8S(e)",
		AP:          -5,
		Range:       "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Charges: "10 charges, regains 1 charge per 10 seconds when plugged in",
		},
		WirelessBonus: &WirelessBonus{
			Description: "The shock gloves recharge by induction, regaining one charge per full hour of wireless-enabled time.",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	// PROJECTILE AND THROWING WEAPONS
	"bows": {
		Name:        "Bows",
		Type:        WeaponTypeThrowing,
		Description: "This could be a traditional longbow of fiberglass or wood, or possibly a modern compound-and-pulley bow. Both are archaic and rare weapons on the streets of 2075, and both have the advantage of being hacker-proof. Reloading a bow takes a Simple Action (Ready Weapon, p. 165). Bows have ratings that indicate the minimum Strength you need to use that weapon. When attacking with a bow, a character whose Strength is less than the Strength minimum suffers a –3 dice pool modifier per point below the minimum; this penalty reflects the difficulty they have in pulling the bow and nocking an arrow. The weapon's Rating is also used to determine its range and damage (maximum Rating is 10). Use the lowest value of your Strength, the bow's rating, or the arrow Rating for range and damage when attacking a target, because your average Rating 10 titanium-sheathed beryllium-alloy bow tends to turn wood or fiberglass arrows into powder when they hit a target.",
		Skill:       WeaponSkillArchery,
		Accuracy:    6,
		Damage:      "(Rating+2)P",
		AP:          0, // -(Rating/4), varies by rating
		ReloadTime:  "Simple Action",
		SpecialProperties: &WeaponSpecialProperty{
			MaxRating:    10,
			SpecialRules: "Rating indicates minimum Strength required; use lowest of Strength, bow rating, or arrow rating for range and damage; AP = -(Rating/4)",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"light_crossbow": {
		Name:             "Light Crossbow",
		Type:             WeaponTypeThrowing,
		Description:      "Modern crossbows are equipped with automatic reloading devices, so unless you're using a museum piece, reloading doesn't require a Ready Weapon action. Crossbows have internal magazines (m) holding up to 4 bolts. Crossbows are available in Light, Medium, and Heavy sizes.",
		Skill:            WeaponSkillArchery,
		Accuracy:         7,
		Damage:           "5P",
		AP:               -1,
		MagazineCapacity: "4(m)",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"medium_crossbow": {
		Name:             "Medium Crossbow",
		Type:             WeaponTypeThrowing,
		Description:      "Modern crossbows are equipped with automatic reloading devices, so unless you're using a museum piece, reloading doesn't require a Ready Weapon action. Crossbows have internal magazines (m) holding up to 4 bolts. Crossbows are available in Light, Medium, and Heavy sizes.",
		Skill:            WeaponSkillArchery,
		Accuracy:         6,
		Damage:           "7P",
		AP:               -2,
		MagazineCapacity: "4(m)",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"heavy_crossbow": {
		Name:             "Heavy Crossbow",
		Type:             WeaponTypeThrowing,
		Description:      "Modern crossbows are equipped with automatic reloading devices, so unless you're using a museum piece, reloading doesn't require a Ready Weapon action. Crossbows have internal magazines (m) holding up to 4 bolts. Crossbows are available in Light, Medium, and Heavy sizes.",
		Skill:            WeaponSkillArchery,
		Accuracy:         5,
		Damage:           "10P",
		AP:               -3,
		MagazineCapacity: "4(m)",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"injection_arrow_bolt": {
		Name:        "Injection Arrow/Bolt",
		Type:        WeaponTypeThrowing,
		Description: "An injection bolt causes the same damage as a regular arrow or bolt, but also includes a payload of one dose of a drug or toxin. Effects depend on the drug payload, but to successfully deliver it, the attack must deal at least one box of damage after the Damage Resistance Test. This is an injection vector toxin attack.",
		Skill:       WeaponSkillArchery,
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"throwing_knife": {
		Name:        "Throwing Knife",
		Type:        WeaponTypeThrowing,
		Description: "A wide variety of shapes and sizes of aerodynamically balanced, specially weighted, muscle-powered throwing weapons are available, from throwing spikes to darts to kunai and shuriken. A character can ready (Agility ÷ 2) of these knives with one Ready Weapon action.",
		Skill:       WeaponSkillArchery,
		Accuracy:    0, // Physical attribute
		Damage:      "(STR+1)P",
		AP:          -1,
		SpecialProperties: &WeaponSpecialProperty{
			SpecialRules: "Can ready (Agility ÷ 2) knives with one Ready Weapon action",
		},
		WirelessBonus: &WirelessBonus{
			Description: "If all the throwing knives or shuriken you throw in a single Combat Turn are wireless and you have a smartlink system, each knife you throw receives a +1 dice pool bonus per knife thrown that Combat Turn at your current target, as the knives inform and adjust for wind and other atmospheric conditions. So you'd get no bonus on the first throw, a +1 bonus on the second throw, a +2 bonus on the third throw, etc. (assuming you aimed all three knives at the same target).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"shuriken": {
		Name:        "Shuriken",
		Type:        WeaponTypeThrowing,
		Description: "A wide variety of shapes and sizes of aerodynamically balanced, specially weighted, muscle-powered throwing weapons are available, from throwing spikes to darts to kunai and shuriken. A character can ready (Agility ÷ 2) of these knives with one Ready Weapon action.",
		Skill:       WeaponSkillArchery,
		Accuracy:    0, // Physical attribute
		Damage:      "(STR+1)P",
		AP:          -1,
		SpecialProperties: &WeaponSpecialProperty{
			SpecialRules: "Can ready (Agility ÷ 2) knives with one Ready Weapon action",
		},
		WirelessBonus: &WirelessBonus{
			Description: "If all the throwing knives or shuriken you throw in a single Combat Turn are wireless and you have a smartlink system, each knife you throw receives a +1 dice pool bonus per knife thrown that Combat Turn at your current target, as the knives inform and adjust for wind and other atmospheric conditions. So you'd get no bonus on the first throw, a +1 bonus on the second throw, a +2 bonus on the third throw, etc. (assuming you aimed all three knives at the same target).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	// TASERS
	"defiance_ex_shocker": {
		Name:             "Defiance EX Shocker",
		Type:             WeaponTypeTaser,
		Description:      "This heavy-duty taser fires up to 4 darts that trail wires up to 20 meters long. The wired connection to the battery allows for a more powerful shock. Most modern tasers use wireless darts, so the Defiance EX Shocker is an exception. It also features contacts that allow it to be used as a stun weapon in melee (Accuracy 3, DV 8S(e), Reach 0).",
		Skill:            WeaponSkillPistols,
		Accuracy:         4,
		Damage:           "9S(e)",
		AP:               -5,
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "4(m)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories: true,
			MeleeMode: &MeleeMode{
				Accuracy: 3,
				Damage:   "8S(e)",
				Reach:    0,
			},
		},
		WirelessBonus: &WirelessBonus{
			Description: "A successful hit informs you of the status of the target's basic health (and Condition Monitors).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "424",
		},
	},
	"yamaha_pulsar": {
		Name:             "Yamaha Pulsar",
		Type:             WeaponTypeTaser,
		Description:      "The darts of this taser contain wireless capacitors, meaning that the Pulsar eliminates the need for cumbersome wires. As a trade-off, it is slightly less powerful than the EX Shocker, although it can fire faster. It lacks the EX Shocker's melee contacts.",
		Skill:            WeaponSkillPistols,
		Accuracy:         5,
		Damage:           "7S(e)",
		AP:               -5,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "4(m)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories: true,
		},
		WirelessBonus: &WirelessBonus{
			Description: "A successful hit informs you of the status of the target's basic health (and Condition Monitors).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "424",
		},
	},
	// HOLD-OUTS
	"fichetti_tiffani_needler": {
		Name:             "Fichetti Tiffani Needler",
		Type:             WeaponTypeHoldOut,
		Description:      "Designed to appeal to social climbers and debutantes, the Tiffani Needler is available in a wide variety of colors and styles. It also has a special color-changing coating that can be manipulated via wireless signal. This is useful to make sure your gun matches with your shoes or your handbag. The Needler can only fire flechette rounds (already factored into its damage code).",
		Skill:            WeaponSkillPistols,
		Accuracy:         5,
		Damage:           "8P(f)",
		AP:               5,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "4(c)",
		SpecialProperties: &WeaponSpecialProperty{
			AmmoTypeRestriction: "flechette rounds only",
			ColorChangeable:     true,
		},
		WirelessBonus: &WirelessBonus{
			ActionChange: "Simple Action",
			Description:  "You can change the color of the Tiffani Needler with a Simple Action.",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "424",
		},
	},
	"streetline_special": {
		Name:             "Streetline Special",
		Type:             WeaponTypeHoldOut,
		Description:      "Popular among society's dregs, the Streetline Special is a small, lightweight weapon made of composite materials. Magnetic Anomaly Detectors (see MAD Scanner, p. 446) suffer a –2 dice pool modifier to detect it.",
		Skill:            WeaponSkillPistols,
		Accuracy:         4,
		Damage:           "6P",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "6(c)",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "424",
		},
	},
	"walther_palm_pistol": {
		Name:             "Walther Palm Pistol",
		Type:             WeaponTypeHoldOut,
		Description:      "This is a classic double-barreled derringer in an over-under barrel combination. It packs a punch for its size, but on the downside it has one of the most diminutive \"magazine\" capacities on the market—just one bullet per barrel. Both barrels can be fired at once as a short burst (see Not Enough Bullets, p. 180).",
		Skill:            WeaponSkillPistols,
		Accuracy:         4,
		Damage:           "7P",
		FireModes:        []FireMode{FireModeSS, FireModeBF},
		MagazineCapacity: "2(b)",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "424",
		},
	},
	// LIGHT PISTOLS
	"ares_light_fire_75": {
		Name:             "Ares Light Fire 75",
		Type:             WeaponTypeLightPistol,
		Description:      "Designed based on one of the most common pistols on the market, the Light Fire is a weapon for special operators, not commonly available through legal channels. A special barrel-mounted silencer developed exclusively for the Light Fire comes attached, applying an additional –1 dice pool modifier to the modifier usually provided by silencers. In addition to its integral silencer, the Ares Light Fire 75 includes a smartgun system.",
		Skill:            WeaponSkillPistols,
		Accuracy:         6, // 8 with smartgun
		Damage:           "6P",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "16(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"integral silencer", "smartgun system"},
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "425",
		},
	},
	"ares_light_fire_70": {
		Name:             "Ares Light Fire 70",
		Type:             WeaponTypeLightPistol,
		Description:      "The Ares Light Fire 70 is one of the most common pistols on the market. A special barrel-mounted silencer developed exclusively for the Light Fire 70 is available that gives you an additional –1 dice pool modifier to the usual –4 (for a total of –5); this silencer costs 750¥.",
		Skill:            WeaponSkillPistols,
		Accuracy:         7,
		Damage:           "8P",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "16(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "425",
		},
	},
	"beretta_201t": {
		Name:             "Beretta 201T",
		Type:             WeaponTypeLightPistol,
		Description:      "This light sidearm is used by many security professionals. It is capable of burst fire. Since the 201T is classified as a light pistol without further limitations, it is quite popular with security agencies in countries where heavy pistols and machine pistols are hard to come by legally. Semi-automatic bursts using the Beretta 201T require a Simple Action. The weapon includes a detachable shoulder stock.",
		Skill:            WeaponSkillPistols,
		Accuracy:         6,
		Damage:           "6P",
		FireModes:        []FireMode{FireModeSA, FireModeBF},
		MagazineCapacity: "21(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"detachable shoulder stock"},
			RecoilCompensation:        1, // With stock
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "425",
		},
	},
	"colt_america_l36": {
		Name:             "Colt America L36",
		Type:             WeaponTypeLightPistol,
		Description:      "A venerable pistol with a great reputation. This basic firearm is cheap, easily concealed, and nearly ubiquitous. A perfect throwaway weapon.",
		Skill:            WeaponSkillPistols,
		Accuracy:         7,
		Damage:           "7P",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "11(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "425",
		},
	},
	"fichetti_security_600": {
		Name:             "Fichetti Security 600",
		Type:             WeaponTypeLightPistol,
		Description:      "A light sidearm for security forces, this weapon's highly efficient feeding mechanism allows it a thirty-round magazine. The Fichetti Security 600 comes with a detachable folding stock and laser sight.",
		Skill:            WeaponSkillPistols,
		Accuracy:         6, // 7 with laser sight
		Damage:           "7P",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "30(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"detachable folding stock", "laser sight"},
			RecoilCompensation:        1, // With stock
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "425",
		},
	},
	"taurus_omni_6_light": {
		Name:             "Taurus Omni-6 (Light Pistol Rounds)",
		Type:             WeaponTypeLightPistol,
		Description:      "This reliable, rugged revolver is specially designed to handle a wide variety of ammunition. Popular with hobbyists and hand-loaders, the Omni-6 comes with some interchangeable cylinders so it can take either cased or caseless, light pistol or heavy pistol ammo. When firing light pistol rounds, the Omni-6 is semi-automatic (SA) and has a base DV of 6P, and when it fires heavy pistol ammo it has only single shot mode (SS), and a base DV of 7P and –1 AP. The Omni-6 includes an integral laser sight.",
		Skill:            WeaponSkillPistols,
		Accuracy:         5, // 6 with laser sight
		Damage:           "6P",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "6(cy)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"integral laser sight"},
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "425",
		},
	},
	"taurus_omni_6_heavy": {
		Name:             "Taurus Omni-6 (Heavy Pistol Rounds)",
		Type:             WeaponTypeHeavyPistol,
		Description:      "This reliable, rugged revolver is specially designed to handle a wide variety of ammunition. Popular with hobbyists and hand-loaders, the Omni-6 comes with some interchangeable cylinders so it can take either cased or caseless, light pistol or heavy pistol ammo. When firing light pistol rounds, the Omni-6 is semi-automatic (SA) and has a base DV of 6P, and when it fires heavy pistol ammo it has only single shot mode (SS), and a base DV of 7P and –1 AP. The Omni-6 includes an integral laser sight.",
		Skill:            WeaponSkillPistols,
		Accuracy:         5, // 6 with laser sight
		Damage:           "7P",
		AP:               -1,
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "6(cy)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"integral laser sight"},
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "425",
		},
	},
	// HEAVY PISTOLS
	"ares_predator_v": {
		Name:             "Ares Predator V",
		Type:             WeaponTypeHeavyPistol,
		Description:      "The newest iteration of the most popular handgun in the world, especially with mercenaries and shadowrunners. Upgraded with improved ergonomics and handling features, the Ares Predator V includes a smartgun system. Some say that the Ares Predator V isn't better than other guns in its class, but no one can argue that it has better brand recognition.",
		Skill:            WeaponSkillPistols,
		Accuracy:         5, // 7 with smartgun
		Damage:           "8P",
		AP:               -1,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "15(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"smartgun system"},
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "426",
		},
	},
	"ares_viper_slivergun": {
		Name:             "Ares Viper Slivergun",
		Type:             WeaponTypeHeavyPistol,
		Description:      "The sleek Slivergun pairs the undeniably winning combo of burst-fire capability and built-in sound suppression (an integral silencer, p. 432) with its large magazine capacity. It fires metal slivers that count as flechette ammunition, which is factored into the weapon's damage code.",
		Skill:            WeaponSkillPistols,
		Accuracy:         4,
		Damage:           "9P(f)",
		AP:               4,
		FireModes:        []FireMode{FireModeSA, FireModeBF},
		MagazineCapacity: "30(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"integral silencer"},
			AmmoTypeRestriction:       "flechette ammunition",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "426",
		},
	},
	"browning_ultra_power": {
		Name:             "Browning Ultra-Power",
		Type:             WeaponTypeHeavyPistol,
		Description:      "This venerable sidearm is the Ares Predator's primary competition as the world's toughest heavy pistol. It offers a built-in top-mounted laser sight and is slightly cheaper.",
		Skill:            WeaponSkillPistols,
		Accuracy:         5, // 6 with laser sight
		Damage:           "8P",
		AP:               -1,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "10(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"top-mounted laser sight"},
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "426",
		},
	},
	"colt_government_2066": {
		Name:             "Colt Government 2066",
		Type:             WeaponTypeHeavyPistol,
		Description:      "This government-issue weapon, styled after the legendary Colt M1911a1, uses an electrically induced spark to detonate the bullet's propellants. The removal of most moving parts from the firing mechanism gives this weapon a reputation for being exceptionally reliable.",
		Skill:            WeaponSkillPistols,
		Accuracy:         6,
		Damage:           "7P",
		AP:               -1,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "14(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "426",
		},
	},
	"remington_roomsweeper": {
		Name:             "Remington Roomsweeper",
		Type:             WeaponTypeHeavyPistol,
		Description:      "This is really more of a short-barreled shotgun than a pistol. When loaded with shot rounds (flechette) rather than solid slugs, it uses Heavy Pistol ranges but shotgun rules (Shotguns, p. 180).",
		Skill:            WeaponSkillPistols,
		Accuracy:         4,
		Damage:           "7P",
		AP:               -1,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "8(m)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			SpecialRules:              "Uses shotgun rules when loaded with shot rounds (flechette)",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "426",
		},
	},
	"ruger_super_warhawk": {
		Name:             "Ruger Super Warhawk",
		Type:             WeaponTypeHeavyPistol,
		Description:      "This revolver is as loud as a jet liner and twice as shiny. It's also one of the scariest handguns in the world. The cased ammo variant is popular for the sheer thrill of swinging open the cylinder gate one handed and dumping spent brass.",
		Skill:            WeaponSkillPistols,
		Accuracy:         5,
		Damage:           "9P",
		AP:               -2,
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "6(cy)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "426",
		},
	},
	// MACHINE PISTOLS
	"ares_crusader_ii": {
		Name:             "Ares Crusader II",
		Type:             WeaponTypeMachinePistol,
		Description:      "A large magazine and easy handling make the Ares Crusader II one of the most popular weapons of its class. It features an integral barrel-mounted gas-vent 2 recoil compensation system and comes with an integral smartgun system.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         5, // 7 with smartgun
		Damage:           "7P",
		FireModes:        []FireMode{FireModeSA, FireModeBF},
		MagazineCapacity: "40(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"gas-vent 2 system", "smartgun system"},
			RecoilCompensation:        2,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "427",
		},
	},
	"ceska_black_scorpion": {
		Name:             "Ceska Black Scorpion",
		Type:             WeaponTypeMachinePistol,
		Description:      "This classic machine pistol provides concealable burst-fire capability. It comes equipped with an integral folding stock.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         5,
		Damage:           "6P",
		FireModes:        []FireMode{FireModeSA, FireModeBF},
		MagazineCapacity: "35(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"integral folding stock"},
			RecoilCompensation:        1, // With stock
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "427",
		},
	},
	"steyr_tmp": {
		Name:             "Steyr TMP",
		Type:             WeaponTypeMachinePistol,
		Description:      "This lightweight polymer-frame pistol is capable of full autofire, but its light weight makes it hard to control when firing on full auto. It comes equipped with a built-in top-mounted laser sight.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         4,
		Damage:           "7P",
		FireModes:        []FireMode{FireModeSA, FireModeBF, FireModeFA},
		MagazineCapacity: "30(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"top-mounted laser sight"},
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "427",
		},
	},
	// SUBMACHINE GUNS
	"colt_cobra_tz_120": {
		Name:             "Colt Cobra TZ–120",
		Type:             WeaponTypeSubmachineGun,
		Description:      "With its unique design and wide range of accessories, the Colt Cobra series is quite popular both among security forces the world over and on the trids. The TZ–120 comes with a folding stock, top-mounted laser sight, and a barrel-mounted gas-vent 2 system.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         4, // 5 with laser sight
		Damage:           "7P",
		FireModes:        []FireMode{FireModeSA, FireModeBF, FireModeFA},
		MagazineCapacity: "32(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"folding stock", "top-mounted laser sight", "gas-vent 2 system"},
			RecoilCompensation:        2, // 3 with stock
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "427",
		},
	},
	"fn_p93_praetor": {
		Name:             "FN P93 Praetor",
		Type:             WeaponTypeSubmachineGun,
		Description:      "This bullpup submachine gun was purpose-built for Corporate Court-controlled Interpol fast-response teams. Its special chamber system provides 1 point of Recoil Compensation, it has an integrated rigid stock, and a flashlight that can be used to reduce darkness penalties by one step (Environmental Modifiers, p. 173). Possession of the FN P93 while not a legitimate member of a Corporate Court force is a crime in most jurisdictions.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         6,
		Damage:           "8P",
		FireModes:        []FireMode{FireModeSA, FireModeBF, FireModeFA},
		MagazineCapacity: "50(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"integrated rigid stock", "flashlight"},
			RecoilCompensation:        1, // 2 with stock
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "427",
		},
	},
	"hk_227": {
		Name:             "HK–227",
		Type:             WeaponTypeSubmachineGun,
		Description:      "The SMG of choice for many corporate and military security forces, the HK–227 boasts a retractable stock, smartgun system, and integral sound suppressor.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         5, // 7 with smartgun
		Damage:           "7P",
		FireModes:        []FireMode{FireModeSA, FireModeBF, FireModeFA},
		MagazineCapacity: "28(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"retractable stock", "smartgun system", "integral sound suppressor"},
			RecoilCompensation:        1, // With stock
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "427",
		},
	},
	"ingram_smartgun_x": {
		Name:             "Ingram Smartgun X",
		Type:             WeaponTypeSubmachineGun,
		Description:      "Grade-A bang bang. Famous as the weapon of choice for many legendary street samurai since the 2050s, the Ingram Smartgun comes tricked out with a gas-vent 2 system, a smartgun system, and an integral sound suppressor.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         4, // 6 with smartgun
		Damage:           "8P",
		FireModes:        []FireMode{FireModeBF, FireModeFA},
		MagazineCapacity: "32(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"gas-vent 2 system", "smartgun system", "integral sound suppressor"},
			RecoilCompensation:        2,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "427",
		},
	},
	"sck_model_100": {
		Name:             "SCK Model 100",
		Type:             WeaponTypeSubmachineGun,
		Description:      "Shin Chou Kyogo is synonymous with Japanese corporate security. Nearly every Japanacorp's security forces are issued the SCK 100, including Renraku's infamous Red Samurai. The SCK 100 features an internal smartgun system and a folding stock.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         5, // 7 with smartgun
		Damage:           "8P",
		FireModes:        []FireMode{FireModeSA, FireModeBF},
		MagazineCapacity: "30(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"internal smartgun system", "folding stock"},
			RecoilCompensation:        1, // With stock
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "427",
		},
	},
	"uzi_iv": {
		Name:             "Uzi IV",
		Type:             WeaponTypeSubmachineGun,
		Description:      "This aging submachine gun is a worthy descendant of the famous Israeli weapon. The SMG features an integral folding stock and built-in top-mounted laser sight.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         4, // 5 with laser sight
		Damage:           "7P",
		FireModes:        []FireMode{FireModeBF},
		MagazineCapacity: "24(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"integral folding stock", "top-mounted laser sight"},
			RecoilCompensation:        1, // With stock
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "427",
		},
	},
	// ASSAULT RIFLES
	"ak_97": {
		Name:             "AK-97",
		Type:             WeaponTypeAssaultRifle,
		Description:      "The AK-97 is a legendary weapon with storied reliability—you can bury it for ten years, dig it up, and fire it immediately without a single problem. When all of the nano-fabricated AK–174s melted to slag, the AK-97s kept functioning just fine.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         4,
		Damage:           "10P",
		AP:               -2,
		FireModes:        []FireMode{FireModeSA, FireModeBF, FireModeFA},
		MagazineCapacity: "38(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "428",
		},
	},
	"ares_alpha": {
		Name:             "Ares Alpha",
		Type:             WeaponTypeAssaultRifle,
		Description:      "Specially designed for Ares Firewatch special forces, the Alpha has since become a multi-platinum best-selling success the world over, seeing use with UCAS Special Forces. In part, this is due to its exceptional brand awareness, and also because of its underbarrel grenade launcher, smartgun system, and an expensive chamber design that provides 2 points of Recoil Compensation.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         5, // 7 with smartgun
		Damage:           "11P",
		AP:               -2,
		FireModes:        []FireMode{FireModeSA, FireModeBF, FireModeFA},
		MagazineCapacity: "42(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"underbarrel grenade launcher", "smartgun system"},
			RecoilCompensation:             2,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "428",
		},
	},
	"colt_m23": {
		Name:             "Colt M23",
		Type:             WeaponTypeAssaultRifle,
		Description:      "This cheap, mass-produced, no-frills assault rifle is loved both by the gangbangers and pirates who can manage to get their hands on one and by the pros who are looking for something to modify from the ground up.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         4,
		Damage:           "9P",
		AP:               -2,
		FireModes:        []FireMode{FireModeSA, FireModeBF, FireModeFA},
		MagazineCapacity: "40(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "428",
		},
	},
	"fn_har": {
		Name:             "FN HAR",
		Type:             WeaponTypeAssaultRifle,
		Description:      "This assault rifle is supremely popular with private security forces and corporate threat-response teams. It features a laser sight and a gas-vent 2 system.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         5, // 6 with laser sight
		Damage:           "10P",
		AP:               -2,
		FireModes:        []FireMode{FireModeSA, FireModeBF, FireModeFA},
		MagazineCapacity: "35(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"laser sight", "gas-vent 2 system"},
			RecoilCompensation:             2,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "428",
		},
	},
	"yamaha_raiden": {
		Name:             "Yamaha Raiden",
		Type:             WeaponTypeAssaultRifle,
		Description:      "This electronic-firing assault rifle is state-of-the-art. The Raiden is very accurate and is quickly being adopted by japanacorp security forces and the Japanese Imperial Marines. It features an integral sound suppressor and smartgun system, and the electronic firing mechanism and design provides 1 point of Recoil Compensation.",
		Skill:            WeaponSkillAutomatics,
		Accuracy:         6, // 8 with smartgun
		Damage:           "11P",
		AP:               -2,
		FireModes:        []FireMode{FireModeBF, FireModeFA},
		MagazineCapacity: "60(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"integral sound suppressor", "smartgun system"},
			RecoilCompensation:             1,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "428",
		},
	},
	// SNIPER RIFLES
	"ares_desert_strike": {
		Name:             "Ares Desert Strike",
		Type:             WeaponTypeSniperRifle,
		Description:      "This combat-hardened sniper rifle is intended for long-range shooting in harsh environments. That means it was built without materials or technologies prone to failure. It comes equipped with a rigid stock with shock pad and a detachable imaging scope.",
		Skill:            WeaponSkillLongarms,
		Accuracy:         7,
		Damage:           "13P",
		AP:               -4,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "14(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"rigid stock with shock pad", "detachable imaging scope"},
			RecoilCompensation:             1, // With shock pad
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "429",
		},
	},
	"cavalier_arms_crockett_ebr": {
		Name:             "Cavalier Arms Crockett EBR",
		Type:             WeaponTypeSniperRifle,
		Description:      "Straddling the line between assault rifle and sniper rifle, the Crockett EBR features a burst fire mode. While it lacks the magazine capacity of a true assault rifle, and lacks the precision of a true marksman's weapon, it makes up for this in versatility, being able to switch fluidly between a sniping role and a combat role as easy as flipping a switch. It comes equipped with a rigid stock with shock pad and a detachable imaging scope.",
		Skill:            WeaponSkillLongarms,
		Accuracy:         6,
		Damage:           "12P",
		AP:               -3,
		FireModes:        []FireMode{FireModeSA, FireModeBF},
		MagazineCapacity: "20(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"rigid stock with shock pad", "detachable imaging scope"},
			RecoilCompensation:             1, // With shock pad
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "429",
		},
	},
	"ranger_arms_sm_5": {
		Name:             "Ranger Arms SM–5",
		Type:             WeaponTypeSniperRifle,
		Description:      "A legendary assassin's weapon, this sniper rifle features a silencer, an imaging scope, and a rigid stock with shock pad. The SM–5 disassembles completely in order to fit into a standard briefcase; setting it up or breaking it down takes an Extended Firearms + Logic [Mental] (6, Complex Action) Test. While deadly, the SM–5 is fragile. At the end of every Combat Turn in which the weapon is used in a running firefight, reduce its Accuracy by 1 (to a minimum of 3). If the weapon is used in combat as a melee weapon or to defend from a melee attack, reduce its Accuracy by 2 (again to a minimum of 3). Recalibrating the weapon (a one-hour job) returns its Accuracy to normal.",
		Skill:            WeaponSkillLongarms,
		Accuracy:         8,
		Damage:           "14P",
		AP:               -5,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "15(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"silencer", "imaging scope", "rigid stock with shock pad"},
			Disassemblable:                 true,
			DisassemblyTime:                "Extended Firearms + Logic [Mental] (6, Complex Action) Test",
			Fragile:                        true,
			FragilityRules:                 "At end of Combat Turn in running firefight, reduce Accuracy by 1 (min 3). If used in melee or to defend from melee, reduce Accuracy by 2 (min 3). Recalibrating (1 hour) returns Accuracy to normal.",
			RecoilCompensation:             1, // With shock pad
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "429",
		},
	},
	"remington_950": {
		Name:             "Remington 950",
		Type:             WeaponTypeSniperRifle,
		Description:      "This high-powered bolt-action hunting rifle features classic wooden furniture and a top-mounted imaging scope that have kept it popular with hunters for several decades. It cannot mount underbarrel accessories.",
		Skill:            WeaponSkillLongarms,
		Accuracy:         7,
		Damage:           "12P",
		AP:               -4,
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "5(m)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:    true,
			CanMountBarrelAccessories: true,
			BuiltInFeatures:           []string{"top-mounted imaging scope"},
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "429",
		},
	},
	"ruger_100": {
		Name:             "Ruger 100",
		Type:             WeaponTypeSniperRifle,
		Description:      "This futuristic-looking gas-operated sporting rifle is the favorite weapon for many professional hunters and hobbyists. It features a built-in imaging scope and a rigid stock with shock pad.",
		Skill:            WeaponSkillLongarms,
		Accuracy:         6,
		Damage:           "11P",
		AP:               -3,
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "8(m)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"built-in imaging scope", "rigid stock with shock pad"},
			RecoilCompensation:             1, // With shock pad
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "429",
		},
	},
	// SHOTGUNS
	"defiance_t_250": {
		Name:             "Defiance T–250",
		Type:             WeaponTypeShotgun,
		Description:      "A common sight on the mean streets when things escalate beyond pistols and knives, this semi-automatic shotgun is available in either a normal-length or short-barreled version. It is gas operated, but also features a secondary pump action for situations where preventing jams is more important than quickly firing a second shot. The short-barreled version has the Concealability of +4, the range of a heavy pistol, and a damage code of 9P.",
		Skill:            WeaponSkillLongarms,
		Accuracy:         4,
		Damage:           "10P",
		AP:               -1,
		FireModes:        []FireMode{FireModeSS, FireModeSA},
		MagazineCapacity: "5(m)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			SpecialRules:                   "Short-barreled version: Concealability +4, Heavy Pistol range, 9P damage",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"defiance_t_250_short": {
		Name:             "Defiance T–250 (Short-barreled)",
		Type:             WeaponTypeShotgun,
		Description:      "A common sight on the mean streets when things escalate beyond pistols and knives, this semi-automatic shotgun is available in either a normal-length or short-barreled version. The short-barreled version has the Concealability of +4, the range of a heavy pistol, and a damage code of 9P.",
		Skill:            WeaponSkillLongarms,
		Accuracy:         4,
		Damage:           "9P",
		AP:               -1,
		FireModes:        []FireMode{FireModeSS, FireModeSA},
		MagazineCapacity: "5(m)",
		Range:            "Heavy Pistol ranges",
		Concealability:   4,
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"enfield_as_7": {
		Name:             "Enfield AS-7",
		Type:             WeaponTypeShotgun,
		Description:      "This military assault shotgun provides its user with massive firepower. As a close-quarters weapon and general combat gun, it is universally feared. It can either be loaded with ten-round ammo clips or a special twenty-four-round drum. The Enfield AS-7 comes equipped with a built-in, top-mounted laser sight.",
		Skill:            WeaponSkillLongarms,
		Accuracy:         4, // 5 with laser sight
		Damage:           "13P",
		AP:               -1,
		FireModes:        []FireMode{FireModeSA, FireModeBF},
		MagazineCapacity: "10(c) or 24(d)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"top-mounted laser sight"},
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"pjss_model_55": {
		Name:             "PJSS Model 55",
		Type:             WeaponTypeShotgun,
		Description:      "This is a weapon of classic style for a classic sport. Produced only in small numbers, it's renowned among European hunters and trap shooters as a precise and prestigious weapon. The weapon's rigid stock comes equipped with an integrated shock pad. Both barrels can be shot at once as a short burst (see Not Enough Bullets, p. 180).",
		Skill:            WeaponSkillLongarms,
		Accuracy:         6,
		Damage:           "11P",
		AP:               -1,
		FireModes:        []FireMode{FireModeSS, FireModeBF},
		MagazineCapacity: "2(b)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"rigid stock with integrated shock pad"},
			RecoilCompensation:             1, // With shock pad
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	// SPECIAL WEAPONS
	"ares_s_iii_super_squirt": {
		Name:             "Ares S-III Super Squirt",
		Type:             WeaponTypeSpecialWeapon,
		Description:      "This popular non-lethal weapon fires DMSO gel packs. The dimethyl sulfoxide forces the skin to absorb the chemicals the operator wishes to deliver. The attack itself causes no damage, but when the target is hit successfully, the DMSO delivers the substance directly into the target's bloodstream as a Contact vector toxin (Toxins, Drugs, and BTLs, p. 408). The Super Squirt uses Light Pistol ranges and can accept top- and underbarrel-mounted accessories",
		Skill:            WeaponSkillExoticRangedWeapon,
		Accuracy:         3,
		Damage:           "Chemical",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "20(c)",
		Range:            "Light Pistol ranges",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			SpecialRules:                   "No damage, delivers Contact vector toxin on hit",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"fichetti_pain_inducer": {
		Name:        "Fichetti Pain Inducer",
		Type:        WeaponTypeSpecialWeapon,
		Description: "For a non-lethal weapon, the Fichetti Pain Inducer is not very humane. It makes someone feel like they are in a microwave, roasting from the inside out. Treat this as a toxin attack with a Power of 8 and a speed of Immediate. The target resists with Body + Willpower. If the modified Power exceeds the target's Mental limit, the target must spend his next Action Phase doing whatever it takes to run away from the pain. The attacker can continue to hold her beam on a target with a Complex Action unless the gamemaster deems the target has dodged away or found cover. If the target cannot get out of the beam, he is incapacitated with pain, suffering a dice pool modifier equal to the modified Power on all tests for as long as the beam is trained on him. The Pain Inducer uses SMG ranges and can take top and underbarrel accessories. It has ten charges; when attached to a power point, it reloads one charge every ten seconds.",
		Skill:       WeaponSkillExoticRangedWeapon,
		Accuracy:    3,
		Damage:      "Spec.",
		FireModes:   []FireMode{FireModeSS},
		Range:       "SMG ranges",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			Charges:                        "10 charges, regains 1 charge per 10 seconds when plugged in",
			SpecialRules:                   "Toxin attack: Power 8, Immediate speed, resisted with Body + Willpower",
		},
		WirelessBonus: &WirelessBonus{
			Description: "The Pain Inducer recharges by induction at a rate of 1 charge per hour.",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"parashield_dart_pistol": {
		Name:             "Parashield Dart Pistol",
		Type:             WeaponTypeSpecialWeapon,
		Description:      "The industry standard dart pistol, this fires injection darts (p. 434) with narcoject or another payload. The Parashield dart pistol uses Heavy Pistol ranges and can take top-mounted accessories.",
		Skill:            WeaponSkillExoticRangedWeapon,
		Accuracy:         5,
		Damage:           "Drug/Toxin",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "5(c)",
		Range:            "Heavy Pistol ranges",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories: true,
		},
		WirelessBonus: &WirelessBonus{
			Description: "The dart reports whether or not it has struck home and successfully injected. It may also report any gross physical anomalies in the target's tissue, although its medical sensors are not very sophisticated (Device Rating of 1 for the dart).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"parashield_dart_rifle": {
		Name:             "Parashield Dart Rifle",
		Type:             WeaponTypeSpecialWeapon,
		Description:      "Originally designed to non-lethally take down large game animals at long ranges, the Parashield dart rifle uses compressed air cartridges to fire injection darts. This weapon includes a top-mounted imaging scope. It uses sporting rifle ranges and can mount top and underbarrel accessories.",
		Skill:            WeaponSkillExoticRangedWeapon,
		Accuracy:         6,
		Damage:           "Drug/Toxin",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "6(m)",
		Range:            "sporting rifle ranges",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"top-mounted imaging scope"},
		},
		WirelessBonus: &WirelessBonus{
			Description: "The dart reports whether or not it has struck home and successfully injected. It may also report any gross physical anomalies in the target's tissue, although its medical sensors are not very sophisticated (Device Rating of 1 for the dart).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	// MACHINE GUNS
	"ingram_valiant": {
		Name:             "Ingram Valiant",
		Type:             WeaponTypeMachineGun,
		Description:      "This legendary light machine gun is popular with mercenary units the world over. It comes with a rigid stock with shock pad, a laser sight, and a barrel-mounted gas-vent 2 system.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         5, // 6 with laser sight
		Damage:           "9P",
		AP:               -2,
		FireModes:        []FireMode{FireModeBF, FireModeFA},
		MagazineCapacity: "50(c) or 100(belt)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"rigid stock with shock pad", "laser sight", "gas-vent 2 system"},
			RecoilCompensation:             2, // 3 with stock
			DoubleRecoilPenalty:            true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"stoner_ares_m202": {
		Name:             "Stoner-Ares M202",
		Type:             WeaponTypeMachineGun,
		Description:      "This MMG packs a tremendous punch into a relatively lightweight framework made of extra-durable compounds. Due to its relatively small size, it's a very popular secondary weapon for heavy military vehicles. Trolls with no concept of subtlety sometimes deck them out with accessories for use as personal weapons.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         5,
		Damage:           "10P",
		AP:               -3,
		FireModes:        []FireMode{FireModeFA},
		MagazineCapacity: "50(c) or 100(belt)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			DoubleRecoilPenalty:            true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"rpk_hmg": {
		Name:             "RPK HMG",
		Type:             WeaponTypeMachineGun,
		Description:      "This heavy Russian machine gun is used by the militaries of several eastern European and Near East countries, primarily as a vehicle-mounted support weapon. Equipped with a detachable tripod, the RPK is usually fired from a prone, sitting, or kneeling position when not mounted on a vehicle.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         5,
		Damage:           "12P",
		AP:               -4,
		FireModes:        []FireMode{FireModeFA},
		MagazineCapacity: "50(c) or 100(belt)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountBarrelAccessories:      true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"detachable tripod"},
			RecoilCompensation:             6, // With tripod
			DoubleRecoilPenalty:            true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	// CANNONS & LAUNCHERS
	"ares_antioch_2": {
		Name:             "Ares Antioch–2",
		Type:             WeaponTypeCannonLauncher,
		Description:      "The Antioch–2 features a classic grenade launcher design combined with an integral smartlink system. It is one of the more affordable grenade launchers on the market.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         4, // 6 with smartlink
		Damage:           "Grenade",
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "8(m)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"integral smartlink system"},
			DoubleRecoilPenalty:            true,
		},
		WirelessBonus: &WirelessBonus{
			Description: "You can use the wireless link trigger for your grenades, even if you don't have DNI (Direct Neural Interface sidebar, p. 222).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"armtech_mgl_12": {
		Name:             "ArmTech MGL–12",
		Type:             WeaponTypeCannonLauncher,
		Description:      "This bullpup-configuration grenade launcher is popular, since it can fire in semi-auto mode and carries substantially more minigrenades than its competitors.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         4,
		Damage:           "Grenade",
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "12(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			DoubleRecoilPenalty:            true,
		},
		WirelessBonus: &WirelessBonus{
			Description: "You can use the wireless link trigger for your grenades, even if you don't have DNI (Direct Neural Interface sidebar, p. 222).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"aztechnology_striker": {
		Name:             "Aztechnology Striker",
		Type:             WeaponTypeCannonLauncher,
		Description:      "The Striker is an extremely light disposable launcher—perfect when you want to deliver a punch and make a quick, unencumbered getaway.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         5,
		Damage:           "Missile",
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "2(ml)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			DoubleRecoilPenalty:            true,
		},
		WirelessBonus: &WirelessBonus{
			Description: "You can use the wireless link trigger for your missiles, even if you don't have DNI (Direct Neural Interface sidebar, p. 222).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"krime_cannon": {
		Name:             "Krime Cannon",
		Type:             WeaponTypeCannonLauncher,
		Description:      "Krime may be a small-time manufacturer, but their assault cannon, simply called the Cannon, is a cheap heavy weapon big on attitude and firepower. It comes standard with modification for trolls, and so is the first weapon in the Sixth World to be intended for larger customers.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         4,
		Damage:           "16P",
		AP:               -6,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "6(m)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			RecoilCompensation:             1, // With stock
			DoubleRecoilPenalty:            true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"onotari_interceptor": {
		Name:             "Onotari Interceptor",
		Type:             WeaponTypeCannonLauncher,
		Description:      "This Saeder-Krupp-developed military missile launcher is designed to fire rockets or guided missiles, of any type. It has two separate barrels and firing chambers, and can load up to two missiles at once, which need not be of the same type. Due to back-blast issues, it is not capable of \"giving 'em both barrels.\" It features an internal smartgun system.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         4, // 6 with smartgun
		Damage:           "Missile",
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "2(ml)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"internal smartgun system"},
			DoubleRecoilPenalty:            true,
		},
		WirelessBonus: &WirelessBonus{
			Description: "You can use the wireless link trigger for your missiles, even if you don't have DNI (Direct Neural Interface sidebar, p. 222).",
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"panther_xxl": {
		Name:             "Panther XXL",
		Type:             WeaponTypeCannonLauncher,
		Description:      "This huge fragging gun is an assault cannon that uses ammunition similar to the primary weapon in many small tanks. It comes with a built-in smartgun system.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         5, // 7 with smartgun
		Damage:           "17P",
		AP:               -6,
		FireModes:        []FireMode{FireModeSA},
		MagazineCapacity: "15(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			BuiltInFeatures:                []string{"built-in smartgun system"},
			DoubleRecoilPenalty:            true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	"ares_alpha_grenade_launcher": {
		Name:             "Ares Alpha (Grenade Launcher)",
		Type:             WeaponTypeCannonLauncher,
		Description:      "The underbarrel grenade launcher integrated into the Ares Alpha assault rifle.",
		Skill:            WeaponSkillHeavyWeapons,
		Accuracy:         4, // 6 with smartlink
		Damage:           "Grenade",
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "6(c)",
		SpecialProperties: &WeaponSpecialProperty{
			CanMountTopAccessories:         true,
			CanMountUnderbarrelAccessories: true,
			DoubleRecoilPenalty:            true,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "430",
		},
	},
	// MISSING WEAPONS FROM TABLE
	"monofilament_chainsaw": {
		Name:            "Monofilament Chainsaw",
		Type:            WeaponTypeMeleeOther,
		Description:     "A chainsaw with a monofilament cutting edge.",
		Skill:           WeaponSkillExoticMeleeWeapon,
		ExoticSkillName: "Monofilament Chainsaw",
		Accuracy:        3,
		Damage:          "8P",
		AP:              -6,
		Range:           "Reach",
		SpecialProperties: &WeaponSpecialProperty{
			Reach: 1,
		},
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"plasteel_toe_boots": {
		Name:        "Plasteel Toe Boots",
		Type:        WeaponTypeMeleeOther,
		Description: "Boots with reinforced plasteel toes for kicking.",
		Skill:       WeaponSkillUnarmedCombat,
		Accuracy:    0, // Physical attribute
		Damage:      "(STR+1)P",
		Range:       "Reach",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
	"grapple_gun": {
		Name:             "Grapple Gun",
		Type:             WeaponTypeThrowing,
		Description:      "A gun that fires a grappling hook for climbing and movement.",
		Skill:            WeaponSkillArchery,
		Accuracy:         3,
		Damage:           "7S",
		AP:               -2,
		FireModes:        []FireMode{FireModeSS},
		MagazineCapacity: "1(ml)",
		Source: &SourceReference{
			Source: "SR5",
			Page:   "422",
		},
	},
}
