package v5

// dataWeaponConsumables contains all weapon consumable definitions
var dataWeaponConsumables = map[string]WeaponConsumable{
	// Ammunition
	"apds": {
		Name:                "APDS",
		Category:            "Ammunition",
		ModifierAP:          "-4",
		Availability:        "12F",
		Cost:                "120",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"assault_cannon": {
		Name:                "Assault Cannon",
		Category:            "Ammunition",
		Availability:        "12F",
		Cost:                "400",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"explosive_rounds": {
		Name:                "Explosive Rounds",
		Category:            "Ammunition",
		ModifierDV:          "+1",
		ModifierAP:          "-1",
		Availability:        "9F",
		Cost:                "80",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"flechette_rounds": {
		Name:                "Flechette Rounds",
		Category:            "Ammunition",
		ModifierDV:          "+2",
		ModifierAP:          "+5",
		Availability:        "6R",
		Cost:                "65",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"gel_rounds": {
		Name:                "Gel Rounds",
		Category:            "Ammunition",
		ModifierDV:          "+0S",
		ModifierAP:          "+1",
		Availability:        "2R",
		Cost:                "25",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"hollow_points": {
		Name:                "Hollow Points",
		Category:            "Ammunition",
		ModifierDV:          "+1",
		ModifierAP:          "+2",
		Availability:        "4F",
		Cost:                "70",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"injection_darts": {
		Name:                "Injection Darts",
		Category:            "Ammunition",
		Availability:        "4R",
		Cost:                "75",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"regular_ammo": {
		Name:                "Regular Ammo",
		Category:            "Ammunition",
		Availability:        "2R",
		Cost:                "20",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"stick_n_shock": {
		Name:                "Stick-n-Shock",
		Category:            "Ammunition",
		ModifierDV:          "-2S(e)",
		ModifierAP:          "-5",
		Availability:        "6R",
		Cost:                "80",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"taser_dart": {
		Name:                "Taser Dart",
		Category:            "Ammunition",
		Availability:        "3",
		Cost:                "50",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	"tracer": {
		Name:                "Tracer",
		Category:            "Ammunition",
		Availability:        "6R",
		Cost:                "60",
		QuantityPerPurchase: 10,
		UnitType:            "rounds",
		Source: &SourceReference{Source: "SR5"},
	},
	// Ballistic Projectile Consumables
	"arrow": {
		Name:                "Arrow",
		Category:            "Ballistic Projectile",
		Availability:        "Rating",
		Cost:                "Rating*2",
		QuantityPerPurchase: 1,
		UnitType:            "arrow",
		Source: &SourceReference{Source: "SR5"},
	},
	"bolt": {
		Name:                "Bolt",
		Category:            "Ballistic Projectile",
		Availability:        "2",
		Cost:                "5",
		QuantityPerPurchase: 1,
		UnitType:            "bolt",
		Source: &SourceReference{Source: "SR5"},
	},
	"injection_arrow": {
		Name:                "Injection Arrow",
		Category:            "Ballistic Projectile",
		Availability:        "(Rating+2)R",
		Cost:                "Rating*20",
		QuantityPerPurchase: 1,
		UnitType:            "arrow",
		Source: &SourceReference{Source: "SR5"},
	},
	"injection_bolt": {
		Name:                "Injection Bolt",
		Category:            "Ballistic Projectile",
		Availability:        "8R",
		Cost:                "50",
		QuantityPerPurchase: 1,
		UnitType:            "bolt",
		Source: &SourceReference{Source: "SR5"},
	},
	"mono_tip": {
		Name:                "Mono Tip",
		Category:            "Ballistic Projectile",
		BaseAP:              "-2",
		Availability:        "8R",
		Cost:                "Rating*30",
		QuantityPerPurchase: 1,
		UnitType:            "tip",
		Source: &SourceReference{Source: "SR5:HT"},
	},
	"seeker_shafts": {
		Name:                "Seeker Shafts",
		Category:            "Ballistic Projectile",
		Availability:        "12F",
		Cost:                "45",
		QuantityPerPurchase: 1,
		UnitType:            "shaft",
		Source: &SourceReference{Source: "SR5:HT"},
	},
	// Grenades
	"flash_bang": {
		Name:                "Flash-Bang",
		Category:            "Grenade",
		DV:                  "10S",
		AP:                  "-4",
		Blast:               "10 m radius",
		Availability:        "6R",
		Cost:                "100",
		QuantityPerPurchase: 1,
		UnitType:            "grenade",
		Source: &SourceReference{Source: "SR5"},
	},
	"flash_pak": {
		Name:                "Flash-Pak",
		Category:            "Grenade",
		DV:                  "Spec.",
		Blast:               "Spec.",
		Availability:        "4",
		Cost:                "125",
		QuantityPerPurchase: 1,
		UnitType:            "grenade",
		Source: &SourceReference{Source: "SR5"},
	},
	"fragmentation": {
		Name:                "Fragmentation",
		Category:            "Grenade",
		DV:                  "18P(f)",
		AP:                  "+5",
		Blast:               "-1/m",
		Availability:        "11F",
		Cost:                "100",
		QuantityPerPurchase: 1,
		UnitType:            "grenade",
		Source: &SourceReference{Source: "SR5"},
	},
	"gas": {
		Name:                "Gas",
		Category:            "Grenade",
		DV:                  "Chemical",
		Blast:               "10 m radius",
		Availability:        "Chemical+2",
		Cost:                "Chemical+40",
		QuantityPerPurchase: 1,
		UnitType:            "grenade",
		Source: &SourceReference{Source: "SR5"},
	},
	"high_explosive": {
		Name:                "High Explosive",
		Category:            "Grenade",
		DV:                  "16P",
		AP:                  "-2",
		Blast:               "-2/m",
		Availability:        "11F",
		Cost:                "100",
		QuantityPerPurchase: 1,
		UnitType:            "grenade",
		Source: &SourceReference{Source: "SR5"},
	},
	"smoke": {
		Name:                "Smoke",
		Category:            "Grenade",
		Blast:               "10 m radius",
		Availability:        "4R",
		Cost:                "40",
		QuantityPerPurchase: 1,
		UnitType:            "grenade",
		Source: &SourceReference{Source: "SR5"},
	},
	"thermal_smoke": {
		Name:                "Thermal Smoke",
		Category:            "Grenade",
		Blast:               "10 m radius",
		Availability:        "6R",
		Cost:                "40",
		QuantityPerPurchase: 1,
		UnitType:            "grenade",
		Source: &SourceReference{Source: "SR5"},
	},

	// Rockets & Missiles
	"anti_vehicle_rocket": {
		Name:                "Anti-Vehicle Rocket",
		Category:            "Rocket & Missile",
		DV:                  "24P",
		AP:                  "-4 / -10",
		Blast:               "-4/m",
		Availability:        "18F",
		Cost:                "2,800",
		QuantityPerPurchase: 1,
		UnitType:            "rocket",
		Source: &SourceReference{Source: "SR5"},
	},
	"fragmentation_rocket": {
		Name:                "Fragmentation Rocket",
		Category:            "Rocket & Missile",
		DV:                  "23P(f)",
		AP:                  "+5",
		Blast:               "-1/m",
		Availability:        "12F",
		Cost:                "2,000",
		QuantityPerPurchase: 1,
		UnitType:            "rocket",
		Source: &SourceReference{Source: "SR5"},
	},
	"high_explosive_rocket": {
		Name:                "High-Explosive Rocket",
		Category:            "Rocket & Missile",
		DV:                  "21P",
		AP:                  "-2",
		Blast:               "-2/m",
		Availability:        "18F",
		Cost:                "2,100",
		QuantityPerPurchase: 1,
		UnitType:            "rocket",
		Source: &SourceReference{Source: "SR5"},
	},
	"missile": {
		Name:                "Missile",
		Category:            "Rocket & Missile",
		DV:                  "Rocket",
		AP:                  "+4",
		Cost:                "+Sensor*500",
		QuantityPerPurchase: 1,
		UnitType:            "missile",
		Source: &SourceReference{Source: "SR5"},
	},
}
