package v5

import "shadowmaster/pkg/shadowrun/edition/v5/common"

// Code generated from weapons.xml. DO NOT EDIT.

var weaponsData = &WeaponsChummer{
	Categories: []WeaponCategories{
		{
			Category: []WeaponCategory{
				{
					Content: "Blades",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("melee"),
				},
				{
					Content: "Clubs",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("melee"),
				},
				{
					Content: "Improvised Weapons",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("melee"),
				},
				{
					Content: "Exotic Melee Weapons",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("melee"),
				},
				{
					Content: "Exotic Ranged Weapons",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("exotic"),
				},
				{
					Content: "Bio-Weapon",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("melee"),
				},
				{
					Content: "Cyberweapon",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("melee"),
				},
				{
					Content: "Unarmed",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("melee"),
				},
				{
					Content: "Bows",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("bow"),
				},
				{
					Content: "Crossbows",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("crossbow"),
				},
				{
					Content: "Tasers",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Energy"),
					Type: stringPtr("taser"),
				},
				{
					Content: "Holdouts",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Light Pistols",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Heavy Pistols",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Machine Pistols",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Submachine Guns",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Assault Rifles",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Carbines",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Sporting Rifles",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Sniper Rifles",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Shotguns",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Light Machine Guns",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Medium Machine Guns",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Heavy Machine Guns",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Underbarrel Weapons",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Micro-Drone Weapons",
					Blackmarket: stringPtr("Weapons"),
					Type: stringPtr("gun"),
				},
				{
					Content: "Assault Cannons",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Ballistic"),
					Type: stringPtr("cannon"),
				},
				{
					Content: "Flamethrowers",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Energy"),
					Type: stringPtr("flame"),
				},
				{
					Content: "Laser Weapons",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Energy"),
					Type: stringPtr("energy"),
				},
				{
					Content: "Grenade Launchers",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Artillery"),
					Type: stringPtr("glauncher"),
				},
				{
					Content: "Missile Launchers",
					Blackmarket: stringPtr("Weapons"),
					Gunneryspec: stringPtr("Rocket"),
					Type: stringPtr("mlauncher"),
				},
			},
		},
	},
	Weapons: []Weapons{
		{
			Weapon: []Weapon{
				// 632 weapons omitted (complex nested structure)
			},
		},
	},
	Accessories: []WeaponAccessoryItems{
		{
			Accessory: []WeaponAccessoryItem{
				{
					ID: "d34a93a8-b695-4c46-8e34-0948df68d44f",
					Name: "Silencer (Ares Light Fire 70)",
					Mount: "Barrel",
					Avail: "6F",
					Cost: "750",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "425",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "4026650e-ecd3-4514-b2c6-d03dc1d466b5",
					Name: "Silencer (Ares Light Fire 75)",
					Mount: "Barrel",
					Avail: "6F",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "425",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "294a6b30-6e1c-4b7d-8e93-10964647c2dd",
					Name: "Airburst Link",
					Mount: "",
					Avail: "6R",
					Cost: "600",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "431",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "6e06df00-95b8-450f-9f2a-4a86c582d342",
					Name: "Bipod",
					Mount: "Under",
					Avail: "2",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "431",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("2"),
					RCGroup: intPtr(1),
				},
				{
					ID: "7f66a669-917a-4423-bd83-cf0e0a1fb2a8",
					Name: "Concealable Holster",
					Mount: "",
					Avail: "2",
					Cost: "150",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "431",
					},
					Conceal: stringPtr("-1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "f46b623b-75b5-4947-a3e4-baa2930749bf",
					Name: "Gas-Vent 1 System",
					Mount: "Barrel",
					Avail: "3R",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "431",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
				},
				{
					ID: "b3827611-f631-461e-8660-e744593ba2d2",
					Name: "Gas-Vent 2 System",
					Mount: "Barrel",
					Avail: "6R",
					Cost: "400",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "431",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("2"),
				},
				{
					ID: "6b06cf52-04fa-4034-bb10-2bcdd58c4bfb",
					Name: "Gas-Vent 3 System",
					Mount: "Barrel",
					Avail: "9R",
					Cost: "600",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "431",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("3"),
				},
				{
					ID: "baecb236-6b4a-4f7d-b9c4-25212f115d4a",
					Name: "Gyro Mount",
					Mount: "Under",
					Avail: "7",
					Cost: "1400",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "432",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("6"),
					RCGroup: intPtr(1),
				},
				{
					ID: "7ca0c689-a05e-4377-ae44-3dc15abe2ee2",
					Name: "Hidden Gun Arm Slide",
					Mount: "",
					Avail: "4R",
					Cost: "350",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "432",
					},
					Conceal: stringPtr("-1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "2905095e-937e-4dbc-aa56-3b66676e1559",
					Name: "Imaging Scope",
					Mount: "Top",
					Avail: "2",
					Cost: "300",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "432",
					},
					Rating: stringPtr("0"),
					AllowGear: &AllowGear{
						GearCategory: []string{
							"Vision Enhancements",
							"Custom",
						},
					},
					Gears: &WeaponGears{
						UseGear: []WeaponUseGear{
							// 2 items omitted
						},
					},
				},
				{
					ID: "521f9c2e-dfb2-42a6-b707-9808ae4885de",
					Name: "Laser Sight",
					Mount: "Top/Under",
					Avail: "2",
					Cost: "125",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "432",
					},
					Accuracy: stringPtr("1"),
					Rating: stringPtr("0"),
				},
				{
					ID: "12e3bb7f-0058-4c9f-ba36-3a865d52b5a0",
					Name: "Periscope",
					Mount: "Top",
					Avail: "3",
					Cost: "70",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "432",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "18e18bbc-f287-4455-bedf-ba349779a4cb",
					Name: "Quick-Draw Holster",
					Mount: "",
					Avail: "4",
					Cost: "175",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "432",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "46596db4-6f25-4990-80cc-c4102eaf80f7",
					Name: "Shock Pad",
					Mount: "",
					Avail: "2",
					Cost: "50",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "432",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					RCDeployable: stringPtr("True"),
					RCGroup: intPtr(2),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "0da6149e-982f-4051-825b-52c1b79c7e52",
					Name: "Silencer/Suppressor",
					Mount: "Barrel",
					Avail: "9F",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "432",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "3c329adb-7c13-4d2c-b25c-49be89173fa1",
					Name: "Sound Suppressor",
					Mount: "Barrel",
					Avail: "9F",
					Cost: "500",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "432",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "5D5D9FC6-9CB9-40A4-8185-891E29DAECC5",
					Name: "External Clip Port",
					Mount: "",
					Avail: "0",
					Cost: "1000",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "458",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "7e25eb59-3ce1-44d8-8367-527fd8c8bc1d",
					Name: "Smart Firing Platform",
					Mount: "Under",
					Avail: "12F",
					Cost: "2000",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "433",
					},
					Rating: stringPtr("0"),
					AllowGear: &AllowGear{
						GearCategory: []string{
							"Autosofts",
							"Custom",
						},
					},
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "d57d2c64-1f61-4f5f-a465-8ce0dfacec6a",
					Name: "Smartgun System, Internal",
					Mount: "",
					Avail: "+2R",
					Cost: "Weapon Cost",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "433",
					},
					Accuracy: stringPtr("2"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Gears: &WeaponGears{
						UseGear: []WeaponUseGear{
							// 2 items omitted
						},
					},
				},
				{
					ID: "b3562903-b1c6-4300-9f6e-25e0102aa69b",
					Name: "Smartgun System, External",
					Mount: "Top/Under",
					Avail: "4R",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "433",
					},
					Accuracy: stringPtr("2"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Gears: &WeaponGears{
						UseGear: []WeaponUseGear{
							// 2 items omitted
						},
					},
				},
				{
					ID: "4ed24342-276e-4455-acba-22b551e4d775",
					Name: "Spare Clip",
					Mount: "",
					Avail: "4",
					Cost: "5",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "433",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "20f3fdc1-6652-4619-a606-1a3d7bad1296",
					Name: "Spare Clip (Hammerli Gemini)",
					Mount: "",
					Avail: "4",
					Cost: "10",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "31",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "6763996b-0458-46ee-a6a5-f50255ace664",
					Name: "Belt-Feed, 100-round",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "417",
					},
					AmmoReplace: stringPtr("100(belt)"),
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "61ddc4d3-25fd-405c-af5d-2455efff2509",
					Name: "Drum Magazine, 24-round",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "417",
					},
					AmmoReplace: stringPtr("24(d)"),
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "d45c3b70-0e12-48b5-9c69-9f86f14d593b",
					Name: "Drum Magazine, 32-round",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "417",
					},
					AmmoReplace: stringPtr("32(d)"),
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "6598e5fa-f2d0-4c5c-a773-570cd9d16300",
					Name: "External Power Source",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "417",
					},
					AmmoReplace: stringPtr("External Source"),
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "4c47baf0-6b34-4e00-8627-a0f605f84ba0",
					Name: "Speed Loader",
					Mount: "",
					Avail: "2",
					Cost: "25",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "433",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "28936368-9e16-498f-b028-92ec31e89a00",
					Name: "Tripod",
					Mount: "Under",
					Avail: "4",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "433",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("6"),
					RCDeployable: stringPtr("True"),
					RCGroup: intPtr(1),
				},
				{
					ID: "06e128ee-00fd-4992-8bf5-4be35815fd11",
					Name: "Advanced Safety System, Basic",
					Mount: "",
					Avail: "4",
					Cost: "600",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "50",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "7898e7dc-3ee6-46a9-83d7-d3ec54a456fb",
					Name: "Silencer (PSK-3 Collapsible Heavy Pistol)",
					Mount: "Barrel",
					Avail: "6F",
					Cost: "700",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "32",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "90804D8B-16CA-4A6F-81E6-454F71768DCE",
					Name: "Collapsed Frame",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "34",
					},
					Conceal: stringPtr("-6"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "b895c431-3fb0-49b7-a3fc-ddb4e54b69ee",
					Name: "Extra Case, Ares Executioner",
					Mount: "",
					Avail: "0",
					Cost: "400",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "35",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "2fa27223-dd56-4520-b26b-a112e8733320",
					Name: "Vindicator 200-Round Belt",
					Mount: "",
					Avail: "4",
					Cost: "100",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "42",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "fad8757c-622f-41ce-8412-8bbb6fbf6445",
					Name: "Advanced Safety System, Immobilization",
					Mount: "",
					Avail: "6",
					Cost: "700",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "50",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "c9739e50-bbaf-47e7-a19b-c3d7fd2b95af",
					Name: "Advanced Safety System, Self Destruct",
					Mount: "",
					Avail: "6",
					Cost: "800",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "50",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "25b695f8-ed5a-4b75-baf0-164dcde74f2d",
					Name: "Advanced Safety System, Explosive Self Destruct",
					Mount: "",
					Avail: "11F",
					Cost: "1000",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "50",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "b64d5256-0c24-4842-b05d-25ee735c9b6a",
					Name: "Advanced Safety System, Electro Shocker",
					Mount: "",
					Avail: "6R",
					Cost: "950",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "50",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "dc859601-1271-4f5d-ac37-e389c95f052a",
					Name: "Bayonet",
					Mount: "Top/Under",
					Avail: "4R",
					Cost: "50",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "50",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "ea64527d-0e1e-4248-957b-7c02d79dad30",
					Name: "Concealed Quick-Draw Holster",
					Mount: "",
					Avail: "6",
					Cost: "275",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "51",
					},
					Conceal: stringPtr("-1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "381dd922-19af-46fd-9999-0202c85574de",
					Name: "Extreme Environment Modification",
					Mount: "",
					Avail: "8",
					Cost: "Rating * 1500",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "51",
					},
					Rating: stringPtr("2"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "41ca17be-6fe4-469f-9a66-7345263c4733",
					Name: "Flashlight, Standard",
					Mount: "Top/Under/Side",
					Avail: "2",
					Cost: "50",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "51",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "487ae8d8-f45b-4133-a79f-c831a6b6a651",
					Name: "Flashlight, Low Light",
					Mount: "Top/Under/Side",
					Avail: "4",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "51",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "fa873465-a678-4077-888f-f7a1fb792d47",
					Name: "Flashlight, Infrared",
					Mount: "Top/Under/Side",
					Avail: "6",
					Cost: "400",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "51",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "f8090e1f-424a-4298-a5d9-f2e6d650ef39",
					Name: "Folding Stock",
					Mount: "Stock",
					Avail: "2",
					Cost: "30",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "51",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					RCDeployable: stringPtr("True"),
					RCGroup: intPtr(2),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "27de824f-d5e4-43fd-abaa-e42da6023569",
					Name: "Stock",
					Mount: "Stock",
					Avail: "2",
					Cost: "30",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "51",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					RCGroup: intPtr(2),
				},
				{
					ID: "8eec5df1-88e2-4822-b156-9c2340a33efc",
					Name: "Foregrip",
					Mount: "Under/Barrel",
					Avail: "2",
					Cost: "100",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Conceal: stringPtr("1"),
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					RCGroup: intPtr(1),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "627f212a-ac15-4739-afbc-f44676dfe508",
					Name: "Gecko Grip (for Weapon with No Stock Slot)",
					Mount: "",
					Avail: "6",
					Cost: "100",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "bf18c385-77bf-4f45-a51c-c17fd702526f",
					Name: "Gecko Grip",
					Mount: "Stock",
					Avail: "6",
					Cost: "100",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "9a27efa9-f3f4-4e47-9165-76e8adbad4ba",
					Name: "Guncam",
					Mount: "Top/Under/Barrel/Side/Internal",
					Avail: "4",
					Cost: "350",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "71a37dd2-d162-4829-a233-5afdd954691d",
					Name: "Hip Pad Bracing System",
					Mount: "Stock",
					Avail: "4",
					Cost: "250",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					RCGroup: intPtr(2),
				},
				{
					ID: "21bc8b85-3fd7-4bde-ac8d-35e1fa099f21",
					Name: "Improved Range Finder",
					Mount: "Top/Under/Barrel/Side/Internal",
					Avail: "6",
					Cost: "2000",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "06af1f95-772c-457d-9287-489cf1b0286d",
					Name: "Peak-Discharge Battery Pack, Power Clip",
					Mount: "",
					Avail: "14F",
					Cost: "400",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					AmmoReplace: stringPtr("10"),
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "dda0b64a-6fa5-4e61-8631-f662f7066756",
					Name: "Peak-Discharge Battery Pack, Satchel Power Pack",
					Mount: "",
					Avail: "16F",
					Cost: "900",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					AmmoReplace: stringPtr("20"),
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "5a7459f5-2d95-4866-a855-110c0bc4f158",
					Name: "Peak-Discharge Battery Pack, Power Backpack",
					Mount: "",
					Avail: "20F",
					Cost: "2500",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					AmmoReplace: stringPtr("30"),
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "51740a3d-4464-4a38-8e2e-8858b3c1481e",
					Name: "Safe Target System, Base",
					Mount: "Top/Under/Barrel/Side/Internal",
					Avail: "6",
					Cost: "750",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "fbf1ac2e-b131-499c-809e-c2c93c5ec286",
					Name: "Safe Target System, Additional set of RFID or GPS data (10 data sets)",
					Mount: "",
					Avail: "6",
					Cost: "25",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "9147a5ee-fba6-4915-9123-709df5835998",
					Name: "Safe Target System, Image Recognition Capabilities",
					Mount: "",
					Avail: "8",
					Cost: "300",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "69e7431a-cf62-4712-8e71-728297385d20",
					Name: "Safe Target System, Extra image profiles (10 profiles)",
					Mount: "",
					Avail: "8",
					Cost: "25",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "de62b79f-2864-4023-a286-6c1f270aade3",
					Name: "Slide Mount",
					Mount: "Top/Under/Side",
					Avail: "4",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "a1865555-8ad5-43ec-a30e-b7d77e804fab",
					Name: "Sling",
					Mount: "",
					Avail: "0",
					Cost: "15",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "52",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "324ee965-d210-4768-a282-aa3180588fc7",
					Name: "Tracker",
					Mount: "",
					Avail: "4",
					Cost: "150",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "53",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "dd786d50-9f42-406e-82d6-359213c086cc",
					Name: "Underbarrel Bola Launcher",
					Mount: "Under",
					Avail: "8R",
					Cost: "350",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "53",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "2ce42c74-5129-4b33-b829-aa392c8eb392",
					Name: "Underbarrel Chainsaw",
					Mount: "Under",
					Avail: "10R",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "53",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "c0191eaa-058c-437c-9e10-141785fc7bc8",
					Name: "Underbarrel Flamethrower",
					Mount: "Under",
					Avail: "2",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "53",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "b479bb05-3b39-4d1f-a4b2-65da27335f18",
					Name: "Underbarrel Grapple Gun",
					Mount: "Under",
					Avail: "8R",
					Cost: "600",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "53",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "25691076-94be-4869-a067-34e7657285b7",
					Name: "Underbarrel Grenade Launcher",
					Mount: "Under",
					Avail: "10F",
					Cost: "3500",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "53",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "9dc660bb-a0b2-4b14-8c43-f5893b174265",
					Name: "Underbarrel Weight",
					Mount: "Under",
					Avail: "4R",
					Cost: "50",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "53",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					RCGroup: intPtr(1),
				},
				{
					ID: "6c703f4e-fade-4045-9d88-ea636e1266f6",
					Name: "Weapon Commlink",
					Mount: "",
					Avail: "0",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "53",
					},
					Rating: stringPtr("0"),
					AllowGear: &AllowGear{
						GearCategory: []string{
							"Commlinks",
							"Custom",
						},
					},
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "e09095d7-72b5-44ef-b52a-aa2de172da2f",
					Name: "Weapon Personality",
					Mount: "",
					Avail: "8",
					Cost: "250",
					SourceReference: common.SourceReference{
						Source: "RG",
						Page: "53",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "4821b29d-55cd-4cb1-a6e2-c51e9d3a95a1",
					Name: "Vintage",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "GH3",
						Page: "3",
					},
					AccessoryCostMultiplier: stringPtr("2"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "ca3f4cb7-6c0e-4736-8a7c-339d00f03567",
					Name: "Cyberimplanted",
					Mount: "",
					Avail: "+4",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "CF",
						Page: "90",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "0c315fd8-3a1a-4748-8359-cb6a04436fbd",
					Name: "Ammo Skip",
					Mount: "Under",
					Avail: "8R",
					Cost: "250",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "5157f235-47c7-4121-aebb-d76709c4b6f8",
					Name: "Explosive Magazine",
					Mount: "",
					Avail: "2F",
					Cost: "20",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					AmmoBonus: stringPtr("-2"),
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "d40d2fc6-3aad-4793-843d-20e3597b2365",
					Name: "Extended Clip",
					Mount: "",
					Avail: "6R",
					Cost: "35",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					AmmoBonus: stringPtr("50 * Rating"),
					Conceal: stringPtr("Rating"),
					Rating: stringPtr("2"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "5f672085-49f9-4fed-9a1f-4bebfea82e8d",
					Name: "Extended Clip (Large Ammo Firearms)",
					Mount: "",
					Avail: "6R",
					Cost: "35",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					AmmoBonus: stringPtr("50"),
					Conceal: stringPtr("2"),
					Rating: stringPtr("1"),
					Required: &common.Required{},
				},
				{
					ID: "5d819147-d262-48c2-bb0e-80e0049c67ed",
					Name: "Ceramic/Plasteel Components",
					Mount: "",
					Avail: "12 + Rating",
					Cost: "Weapon Cost * Rating",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					Rating: stringPtr("6"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "5cc39a55-3973-4368-81ee-c7a5c0432323",
					Name: "Chameleon Coating (Pistol)",
					Mount: "Side",
					Avail: "10R",
					Cost: "1000",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					Conceal: stringPtr("-2"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "98c9ed33-2636-40bb-a455-334e8fb8e65f",
					Name: "Chameleon Coating (Rifle)",
					Mount: "Side",
					Avail: "10R",
					Cost: "1000",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					Conceal: stringPtr("-1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "4e54b271-2617-44b5-a70f-ab389890dda8",
					Name: "Holographic Sight",
					Mount: "Top",
					Avail: "2",
					Cost: "125",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "181",
					},
					Accuracy: stringPtr("1"),
					Rating: stringPtr("0"),
				},
				{
					ID: "d5abeadd-fba4-47f9-ac35-bfbb31ce34be",
					Name: "Long Barrel",
					Mount: "Barrel",
					Avail: "8R",
					Cost: "Weapon Cost",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "181",
					},
					Accuracy: stringPtr("1"),
					Conceal: stringPtr("+1"),
					Rating: stringPtr("0"),
				},
				{
					ID: "806bfacc-095e-448d-a5b2-c271c569ae51",
					Name: "Melee Hardening",
					Mount: "",
					Avail: "6",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "181",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "83902f51-5f87-444f-a3ff-a74ce865e1af",
					Name: "Easy Breakdown (Unpowered)",
					Mount: "Side",
					Avail: "8R",
					Cost: "750",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "f27402fa-2845-4314-a97d-2747b3263e0d",
					Name: "Easy Breakdown (Powered)",
					Mount: "Side",
					Avail: "10R",
					Cost: "1250",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "2da4f104-cf0c-4e0c-a001-4a6da4c2b46b",
					Name: "Electronic Firing",
					Mount: "Barrel",
					Avail: "10R",
					Cost: "1000",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "a2e4fcc6-cc21-4fc8-bbdf-efb489e9c377",
					Name: "Mounted Crossbow",
					Mount: "Under/Barrel",
					Avail: "8R",
					Cost: "1000",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					ExtraMount: stringPtr("Under/Barrel"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "b83d5f60-7be2-4991-a518-775f6ae49207",
					Name: "Underbarrel Laser",
					Mount: "Under",
					Avail: "16F",
					Cost: "22000",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					ExtraMount: stringPtr("Side"),
					Rating: stringPtr("0"),
				},
				{
					ID: "13d90aa2-6a67-47e5-a211-89aabea5f837",
					Name: "Underbarrel Shotgun",
					Mount: "Under",
					Avail: "5R",
					Cost: "600",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					Rating: stringPtr("0"),
					AddUnderbarrels: &AddUnderbarrels{
						Weapon: []string{
							"Underbarrel Shotgun",
						},
					},
					Required: &common.Required{},
				},
				{
					ID: "b8c019cc-5772-43b0-8ba8-a08581bab406",
					Name: "Overclocked",
					Mount: "",
					Avail: "6F",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					Damage: stringPtr("-2"),
					DamageType: stringPtr("P"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "b83bfd3a-8011-4a8e-8e76-033dbd6a79c1",
					Name: "Retractable Bayonet",
					Mount: "Under",
					Avail: "6R",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "d67f3194-61f3-4440-b02c-e5f173532b01",
					Name: "Custom Look",
					Mount: "",
					Avail: "2",
					Cost: "300",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "180",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "225d5411-953e-4537-9e97-40bced059bd3",
					Name: "Sawed Off/Shortbarrel",
					Mount: "Barrel",
					Avail: "4R",
					Cost: "20",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					Conceal: stringPtr("-1"),
					Damage: stringPtr("-1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "88d0e08b-1ac2-442e-8f2f-dfaeb9cda9ab",
					Name: "Stock Removal",
					Mount: "Stock",
					Avail: "2",
					Cost: "20",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					Conceal: stringPtr("-1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "01bb2926-c25f-4eba-acfc-aa4b14019607",
					Name: "Sawed Off/Shortbarrel and Stock Removal",
					Mount: "Stock",
					Avail: "2",
					Cost: "20",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					ExtraMount: stringPtr("Barrel"),
					Accuracy: stringPtr("-1"),
					Conceal: stringPtr("-2"),
					Damage: stringPtr("-1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "f2eee4ed-d0cb-4163-84d9-91e537cd13d9",
					Name: "Trigger Removal",
					Mount: "",
					Avail: "2",
					Cost: "50",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					Accuracy: stringPtr("1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "85b01b5c-c788-4b43-8190-9e0c18391436",
					Name: "Personalized Grip",
					Mount: "",
					Avail: "2",
					Cost: "100",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "182",
					},
					Accuracy: stringPtr("1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "f277db83-e5f0-47c8-a465-e0307105796f",
					Name: "Collapsible Traditional Bow",
					Mount: "",
					Avail: "0",
					Cost: "Rating * 50",
					SourceReference: common.SourceReference{
						Source: "HT",
						Page: "197",
					},
					Rating: stringPtr("10"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "0c2e21a0-4f1d-409d-a33e-cb3d5f0b0897",
					Name: "Tripod (2050)",
					Mount: "Under",
					Avail: "10",
					Cost: "600",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "186",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("6"),
					RCDeployable: stringPtr("True"),
					RCGroup: intPtr(1),
				},
				{
					ID: "ec157e2d-5868-4652-8cf0-8e30e46fb130",
					Name: "Spare Clip (2050)",
					Mount: "",
					Avail: "2",
					Cost: "5",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "e632b766-55fb-42bf-8bd3-6c9c46830a29",
					Name: "Gas-Vent 2 System (2050)",
					Mount: "Barrel",
					Avail: "2R",
					Cost: "450",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("2"),
				},
				{
					ID: "9998a80c-6452-4fcb-9508-66da27eea850",
					Name: "Gas-Vent 3 System (2050)",
					Mount: "Barrel",
					Avail: "2R",
					Cost: "700",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("2"),
				},
				{
					ID: "ac1e63bd-4cce-44c4-ac65-71831ebaa1d4",
					Name: "Grenade Launcher (2050)",
					Mount: "Under",
					Avail: "8F",
					Cost: "1700",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "e6b1550c-c392-4e85-b618-04f8a09b8020",
					Name: "Gyro Mount, default (2050) ",
					Mount: "Under",
					Avail: "4",
					Cost: "2500",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("5"),
					RCGroup: intPtr(1),
				},
				{
					ID: "6ed9f566-4696-4436-9d79-4e807fbb2a1f",
					Name: "Gyro Mount, Deluxe (2050) ",
					Mount: "Under",
					Avail: "4",
					Cost: "6000",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("6"),
					RCGroup: intPtr(1),
				},
				{
					ID: "1bf98490-9642-436b-9b7c-fdbd6d5a65f1",
					Name: "Laser Sight (2050)",
					Mount: "Top/Under",
					Avail: "6",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Accuracy: stringPtr("1"),
					Rating: stringPtr("0"),
				},
				{
					ID: "dd5a1cf9-38a6-49a6-9ed5-c7ee79670e4e",
					Name: "Silencer (2050)",
					Mount: "Barrel",
					Avail: "9F",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "57651486-8344-4b4b-af96-780e99cfb015",
					Name: "Speed Loader (2050)",
					Mount: "",
					Avail: "2",
					Cost: "10",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "1c8c3432-315b-4365-8a15-31e9427cbff9",
					Name: "Shock Pad (2050)",
					Mount: "",
					Avail: "2",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					RCDeployable: stringPtr("True"),
					RCGroup: intPtr(2),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "e62964cd-767f-4b10-b456-d87f5a04b64e",
					Name: "Smartgun System, Internal (2050)",
					Mount: "",
					Avail: "+2R",
					Cost: "Weapon Cost",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Accuracy: stringPtr("2"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "e6058e8b-c4b5-422f-aa2f-d0f23769b094",
					Name: "Smartgun System, External (2050)",
					Mount: "Top/Under",
					Avail: "4R",
					Cost: "600",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Accuracy: stringPtr("2"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "a465112e-b597-4b39-b2c3-19d1b2fafb09",
					Name: "Concealable Holster (2050)",
					Mount: "",
					Avail: "2",
					Cost: "100",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Conceal: stringPtr("-2"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "97de111c-4cf2-4a45-963f-14349b3b9c38",
					Name: "Imaging Scope (2050)",
					Mount: "Top",
					Avail: "3",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Rating: stringPtr("0"),
					AllowGear: &AllowGear{
						GearCategory: []string{
							"Vision Enhancements",
							"Custom",
						},
					},
					Gears: &WeaponGears{
						UseGear: []WeaponUseGear{
							// 1 items omitted
						},
					},
				},
				{
					ID: "605c079d-baeb-422d-9653-9efe595d9dc2",
					Name: "Bipod (2050)",
					Mount: "Under",
					Avail: "2",
					Cost: "400",
					SourceReference: common.SourceReference{
						Source: "2050",
						Page: "189",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("2"),
					RCGroup: intPtr(1),
				},
				{
					ID: "75cf7909-ac1b-4659-977a-371a950fcda9",
					Name: "Silencer (HK Urban Fighter)",
					Mount: "",
					Avail: "16F",
					Cost: "1000",
					SourceReference: common.SourceReference{
						Source: "SAG",
						Page: "21",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "ff48f23d-e503-4487-b743-c01b4b4edae8",
					Name: "Spare Clip (HK Urban Fighter)",
					Mount: "",
					Avail: "16F",
					Cost: "150",
					SourceReference: common.SourceReference{
						Source: "SAG",
						Page: "21",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "b9f06e3e-5ed3-433e-9017-5f7e4ed35b3d",
					Name: "Glock MP Custodes Briefcase",
					Mount: "",
					Avail: "0",
					Cost: "0",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "SAG",
						Page: "25",
					},
					Conceal: stringPtr("-6"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "9adeccb8-63d0-45df-a854-db2cd33ccd26",
					Name: "Folding Stock (Glock MP Custodes)",
					Mount: "Stock",
					Avail: "2",
					Cost: "50",
					SourceReference: common.SourceReference{
						Source: "SAG",
						Page: "25",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					RCDeployable: stringPtr("True"),
					RCGroup: intPtr(2),
					Required: &common.Required{},
				},
				{
					ID: "04eedb80-cde8-4a87-bf31-b68b62513f33",
					Name: "HK 223C Colt Magazine",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "SAG",
						Page: "26",
					},
					AmmoReplace: stringPtr("40(c)"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "5a097359-670b-4685-95be-c762d6c44c79",
					Name: "Spare Clip (HK Urban Enforcer)",
					Mount: "",
					Avail: "20F",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "SAG",
						Page: "27",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "3dca3546-5b96-4a37-890e-1a84a20f5f89",
					Name: "Spare Clip (HK Urban Striker)",
					Mount: "",
					Avail: "18F",
					Cost: "200",
					SourceReference: common.SourceReference{
						Source: "SAG",
						Page: "33",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "112122f6-71de-43fd-b4bf-7db2e309590e",
					Name: "Silencer (Onotari Arms Pressure KS-X)",
					Mount: "Barrel",
					Avail: "14F",
					Cost: "900",
					SourceReference: common.SourceReference{
						Source: "SAG",
						Page: "35",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "c50723ab-8354-4b32-a1a8-b3720df0dd2d",
					Name: "Survival Knife Bonuses",
					Mount: "",
					Avail: "0",
					Cost: "0",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "422",
					},
					Rating: stringPtr("0"),
					Gears: &WeaponGears{
						UseGear: []WeaponUseGear{
							// 5 items omitted
						},
					},
				},
				{
					ID: "471d2d54-34cc-493c-b888-e27498b28e39",
					Name: "Survival Knife Wireless Bonuses",
					Mount: "",
					Avail: "0",
					Cost: "0",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "422",
					},
					Rating: stringPtr("0"),
					Gears: &WeaponGears{
						UseGear: []WeaponUseGear{
							// 2 items omitted
						},
					},
				},
				{
					ID: "5fac79b3-5eff-44f8-a13c-e1eba38df873",
					Name: "Silencer (Terracotta Arms Pup)",
					Mount: "",
					Avail: "+2F",
					Cost: "400",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "27",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "6f84482e-5a9d-4fb3-bad3-4fbbfa569919",
					Name: "Spare Clip (HK Urban Fighter)",
					Mount: "",
					Avail: "10F",
					Cost: "100",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "45",
					},
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "d2a1cc9b-72e3-49df-957c-8ed6fb47a813",
					Name: "Additional Clip/Magazine",
					Mount: "Side",
					Avail: "10R",
					Cost: "Weapon Cost",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "45",
					},
					AmmoSlots: stringPtr("1"),
					Conceal: stringPtr("+2"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "20d18222-448c-47f8-bb4e-be307a0cd995",
					Name: "Additional Clip/Magazine (Pistol)",
					Mount: "Side",
					Avail: "10R",
					Cost: "Weapon Cost",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "45",
					},
					AmmoSlots: stringPtr("1"),
					Conceal: stringPtr("+2"),
					ModifyAmmoCapacity: stringPtr("* 3 div 4"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "37d3ffa9-b33e-4280-845c-bee0d063f193",
					Name: "Krime Pack",
					Mount: "",
					Avail: "14R",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "45",
					},
					AmmoReplace: stringPtr("2500(belt)"),
					AmmoSlots: stringPtr("1"),
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "f52db08a-a2f5-482b-8cd0-4cf3045e0d60",
					Name: "Krime Stun-O-Net",
					Mount: "Under",
					Avail: "10R",
					Cost: "800",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "46",
					},
					Rating: stringPtr("0"),
					AddUnderbarrels: &AddUnderbarrels{
						Weapon: []string{
							"Krime Stun-O-Net",
						},
					},
					Required: &common.Required{},
				},
				{
					ID: "7629baa4-2240-45f3-b3d5-066dfc536877",
					Name: "Narcoject Dazzler",
					Mount: "Top",
					Avail: "15R",
					Cost: "1000",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "46",
					},
					Rating: stringPtr("0"),
					Required: &common.Required{},
				},
				{
					ID: "a16a52a9-3b57-4e3c-96f6-564616bcd576",
					Name: "Red Dot Sight",
					Mount: "Top",
					Avail: "4",
					Cost: "75",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "47",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "861819f2-827e-444b-ae6c-33eb161a14dc",
					Name: "Standard Maker Mag",
					Mount: "",
					Avail: "18R",
					Cost: "100 * Rating",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "76",
					},
					AmmoBonus: stringPtr("-50"),
					AmmoSlots: stringPtr("1"),
					Conceal: stringPtr("0"),
					Rating: stringPtr("1000"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "c455e976-a3b8-4c45-8777-6814f14c295b",
					Name: "Extended Maker Mag",
					Mount: "",
					Avail: "18R",
					Cost: "150 * Rating",
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "76",
					},
					AmmoBonus: stringPtr("-25"),
					AmmoSlots: stringPtr("1"),
					Conceal: stringPtr("1"),
					Rating: stringPtr("1000"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "91d1b0c0-3146-4435-b2ef-322e80dbbb59",
					Name: "Breeching Teeth",
					Mount: "",
					Avail: "0",
					Cost: "0",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "131",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "2eea1d98-8c6f-4f59-a8e8-e39b17c60869",
					Name: "Modified Pump Handle",
					Mount: "",
					Avail: "0",
					Cost: "0",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "SL",
						Page: "131",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "b741b729-106e-46f2-9143-0f745fd48789",
					Name: "Special Modification: Improved AP",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "BTB",
						Page: "161",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "56b17280-27c6-414a-9957-f628ae5efefa",
					Name: "Special Modification: Improved Accuracy",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "BTB",
						Page: "161",
					},
					Accuracy: stringPtr("1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "9084d801-c654-4eec-960e-4186a6de81d6",
					Name: "Special Modification: Improved Ammunition Capacity",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "BTB",
						Page: "161",
					},
					ModifyAmmoCapacity: stringPtr("+(Weapon * 0.5)"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "93be91c1-3f77-4e7b-9ac2-eb349b76d017",
					Name: "Special Modification: Improved Concealment",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "BTB",
						Page: "161",
					},
					Conceal: stringPtr("-1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "3c82e17b-76cd-47b9-9bda-c3131a64e0ee",
					Name: "Special Modification: Damage",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "BTB",
						Page: "161",
					},
					Damage: stringPtr("1"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "15d159e8-d3db-4cf3-8964-0eb2235ed6c2",
					Name: "Special Modification: Improved Reach",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "BTB",
						Page: "161",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "09abdea8-df9a-4e74-86aa-0f79ce96f422",
					Name: "Special Modification: Improved Recoil Comp",
					Mount: "",
					Avail: "0",
					Cost: "0",
					SourceReference: common.SourceReference{
						Source: "BTB",
						Page: "161",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("1"),
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
				},
				{
					ID: "2d5cd697-4754-420c-ba11-27cf957a4d09",
					Name: "Maker Mag",
					Mount: "",
					Avail: "18R",
					Cost: "1000",
					SourceReference: common.SourceReference{
						Source: "SOTG",
						Page: "12",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "63a4c7fe-847e-46e6-a99d-da0f39e63b8a",
					Name: "Plastic Components",
					Mount: "",
					Avail: "18R",
					Cost: "1000",
					SourceReference: common.SourceReference{
						Source: "SOTG",
						Page: "12",
					},
					Rating: stringPtr("6"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "ba6a4f69-bdfa-4fcf-82ac-81c64aa99114",
					Name: "HK Puncheon Booster",
					Mount: "",
					Avail: "9R",
					Cost: "250",
					SourceReference: common.SourceReference{
						Source: "SLG2",
						Page: "1",
					},
					AddMount: stringPtr("Under"),
					Accuracy: stringPtr("2"),
					Conceal: stringPtr("+2"),
					Rating: stringPtr("0"),
					ReplaceRange: stringPtr("Heavy Pistols"),
					Required: &common.Required{},
				},
				{
					ID: "610dffea-8295-434f-b279-5327adbefd59",
					Name: "Metahuman Adaptation",
					Mount: "",
					Avail: "0",
					Cost: "0",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "KK",
						Page: "0",
					},
					Rating: stringPtr("0"),
				},
				{
					ID: "1c70c3bf-9a59-45d9-bb3e-4569a2a624d6",
					Name: "Matrix Signal Scanner",
					Mount: "",
					Avail: "0",
					Cost: "0",
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					SourceReference: common.SourceReference{
						Source: "KK",
						Page: "18",
					},
					Rating: stringPtr("0"),
					Gears: &WeaponGears{
						UseGear: []WeaponUseGear{
							// 1 items omitted
						},
					},
				},
				{
					ID: "aefc5dd2-4b2d-4662-99d6-3bddc8db026e",
					Name: "Krime Dual-Mode External Smartgun Link",
					Mount: "Top/Under",
					Avail: "7R",
					Cost: "500",
					SourceReference: common.SourceReference{
						Source: "KK",
						Page: "22",
					},
					Accuracy: stringPtr("2"),
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
					Gears: &WeaponGears{
						UseGear: []WeaponUseGear{
							// 2 items omitted
						},
					},
				},
				{
					ID: "502c319a-68a9-4e89-8521-e4e535738890",
					Name: "Krime Explosive Securing Tripod",
					Mount: "Under",
					Avail: "12",
					Cost: "1000",
					SourceReference: common.SourceReference{
						Source: "KK",
						Page: "23",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("6"),
					RCDeployable: stringPtr("True"),
					RCGroup: intPtr(1),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "9b09fc1e-cb5b-473f-83a5-6f23a7524012",
					Name: "Krime Offline Support Solutions",
					Mount: "",
					Avail: "0",
					Cost: "25",
					SourceReference: common.SourceReference{
						Source: "KK",
						Page: "23",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "3e048d18-3011-4e43-a557-0696c4c09042",
					Name: "Krime Loudener",
					Mount: "Barrel",
					Avail: "0",
					Cost: "250",
					SourceReference: common.SourceReference{
						Source: "KK",
						Page: "23",
					},
					Rating: stringPtr("0"),
					RC: stringPtr("2"),
					Forbidden: &common.Forbidden{},
				},
				{
					ID: "a869d692-db53-4b31-847a-5216d9e48c0e",
					Name: "Krime Keeper",
					Mount: "",
					Avail: "0",
					Cost: "50",
					SourceReference: common.SourceReference{
						Source: "KK",
						Page: "23",
					},
					Rating: stringPtr("0"),
					Forbidden: &common.Forbidden{},
				},
			},
		},
	},
}

// GetWeaponsData returns the loaded weapons data.
func GetWeaponsData() *WeaponsChummer {
	return weaponsData
}

// GetAllWeaponAccessories returns all weapon accessories.
func GetAllWeaponAccessories() []WeaponAccessoryItem {
	if len(weaponsData.Accessories) == 0 {
		return []WeaponAccessoryItem{}
	}
	return weaponsData.Accessories[0].Accessory
}

// GetWeaponAccessoryByID returns the weapon accessory with the given ID, or nil if not found.
func GetWeaponAccessoryByID(id string) *WeaponAccessoryItem {
	accessories := GetAllWeaponAccessories()
	for i := range accessories {
		if accessories[i].ID == id {
			return &accessories[i]
		}
	}
	return nil
}

// GetAllWeaponMods returns all weapon mods.
func GetAllWeaponMods() []WeaponModItem {
	if len(weaponsData.Mods) == 0 {
		return []WeaponModItem{}
	}
	return weaponsData.Mods[0].Mod
}

// GetWeaponModByName returns the weapon mod with the given name, or nil if not found.
func GetWeaponModByName(name string) *WeaponModItem {
	mods := GetAllWeaponMods()
	for i := range mods {
		if mods[i].Name == name {
			return &mods[i]
		}
	}
	return nil
}
