package common

// BaseBonus contains all common bonus fields that are shared across different bonus types
// This struct is generated from bonuses.xsd and contains all 282 top-level bonus elements
// This can be embedded in specific bonus structures like BiowareBonus, CyberwareBonus, etc.
type BaseBonus struct {
	Actiondicepool                                 []Actiondicepool                                 `xml:"actiondicepool,omitempty" json:"actiondicepool,omitempty"`
	Activeskillkarmacost                           []Activeskillkarmacost                           `xml:"activeskillkarmacost,omitempty" json:"activeskillkarmacost,omitempty"`
	Activeskillkarmacostmultiplier                 []Activeskillkarmacostmultiplier                 `xml:"activeskillkarmacostmultiplier,omitempty" json:"activeskillkarmacostmultiplier,omitempty"`
	Activeskillpointcost                           []Activeskillpointcost                           `xml:"activeskillpointcost,omitempty" json:"activeskillpointcost,omitempty"`
	Activeskillpointcostmultiplier                 []Activeskillpointcostmultiplier                 `xml:"activeskillpointcostmultiplier,omitempty" json:"activeskillpointcostmultiplier,omitempty"`
	Activesoft                                     []Activesoft                                     `xml:"activesoft,omitempty" json:"activesoft,omitempty"`
	Addcontact                                     *Addcontact                                      `xml:"addcontact,omitempty" json:"addcontact,omitempty"`
	Addgear                                        []Addgear                                        `xml:"addgear,omitempty" json:"addgear,omitempty"`
	Addlimb                                        []Addlimb                                        `xml:"addlimb,omitempty" json:"addlimb,omitempty"`
	Addmetamagic                                   []Addmetamagic                                   `xml:"addmetamagic,omitempty" json:"addmetamagic,omitempty"`
	Addqualities                                   *Addqualities                                    `xml:"addqualities,omitempty" json:"addqualities,omitempty"`
	Qualitylevel                                   *Qualitylevel                                    `xml:"qualitylevel,omitempty" json:"qualitylevel,omitempty"`
	Pushtextforqualitygroup                        *Pushtextforqualitygroup                         `xml:"pushtextforqualitygroup,omitempty" json:"pushtextforqualitygroup,omitempty"`
	Addspell                                       []Addspell                                       `xml:"addspell,omitempty" json:"addspell,omitempty"`
	Addspirit                                      []Addspirit                                      `xml:"addspirit,omitempty" json:"addspirit,omitempty"`
	Addsprite                                      []Addsprite                                      `xml:"addsprite,omitempty" json:"addsprite,omitempty"`
	Addware                                        []Addware                                        `xml:"addware,omitempty" json:"addware,omitempty"`
	Addweapon                                      []Addweapon                                      `xml:"addweapon,omitempty" json:"addweapon,omitempty"`
	Armor                                          *Armor                                           `xml:"armor,omitempty" json:"armor,omitempty"`
	Attributekarmacost                             []Attributekarmacost                             `xml:"attributekarmacost,omitempty" json:"attributekarmacost,omitempty"`
	Attributekarmacostmultiplier                   []Attributekarmacostmultiplier                   `xml:"attributekarmacostmultiplier,omitempty" json:"attributekarmacostmultiplier,omitempty"`
	Attributepointcost                             []Attributepointcost                             `xml:"attributepointcost,omitempty" json:"attributepointcost,omitempty"`
	Attributepointcostmultiplier                   []Attributepointcostmultiplier                   `xml:"attributepointcostmultiplier,omitempty" json:"attributepointcostmultiplier,omitempty"`
	Availability                                   []Availability                                   `xml:"availability,omitempty" json:"availability,omitempty"`
	Basiclifestylecost                             []Basiclifestylecost                             `xml:"basiclifestylecost,omitempty" json:"basiclifestylecost,omitempty"`
	Blockskilldefaulting                           []Blockskilldefaulting                           `xml:"blockskilldefaulting,omitempty" json:"blockskilldefaulting,omitempty"`
	Conditionmonitor                               *Conditionmonitor                                `xml:"conditionmonitor,omitempty" json:"conditionmonitor,omitempty"`
	Critterpowers                                  *Critterpowers                                   `xml:"critterpowers,omitempty" json:"critterpowers,omitempty"`
	Cyberlimbattributebonus                        []Cyberlimbattributebonus                        `xml:"cyberlimbattributebonus,omitempty" json:"cyberlimbattributebonus,omitempty"`
	Dealerconnection                               *Dealerconnection                                `xml:"dealerconnection,omitempty" json:"dealerconnection,omitempty"`
	Drainvalue                                     []Drainvalue                                     `xml:"drainvalue,omitempty" json:"drainvalue,omitempty"`
	Disabletab                                     *Disabletab                                      `xml:"disabletab,omitempty" json:"disabletab,omitempty"`
	Enableattribute                                *Enableattribute                                 `xml:"enableattribute,omitempty" json:"enableattribute,omitempty"`
	Enabletab                                      *Enabletab                                       `xml:"enabletab,omitempty" json:"enabletab,omitempty"`
	Fadingvalue                                    []Fadingvalue                                    `xml:"fadingvalue,omitempty" json:"fadingvalue,omitempty"`
	Focusbindingkarmacost                          []Focusbindingkarmacost                          `xml:"focusbindingkarmacost,omitempty" json:"focusbindingkarmacost,omitempty"`
	Focusbindingkarmamultiplier                    []Focusbindingkarmamultiplier                    `xml:"focusbindingkarmamultiplier,omitempty" json:"focusbindingkarmamultiplier,omitempty"`
	Freespells                                     *Freespells                                      `xml:"freespells,omitempty" json:"freespells,omitempty"`
	Hardwires                                      *Hardwires                                       `xml:"hardwires,omitempty" json:"hardwires,omitempty"`
	Initiative                                     *Initiative                                      `xml:"initiative,omitempty" json:"initiative,omitempty"`
	Initiativepass                                 *Initiativepass                                  `xml:"initiativepass,omitempty" json:"initiativepass,omitempty"`
	Knowledgeskillkarmacost                        []Knowledgeskillkarmacost                        `xml:"knowledgeskillkarmacost,omitempty" json:"knowledgeskillkarmacost,omitempty"`
	Knowledgeskillkarmacostmin                     []Knowledgeskillkarmacostmin                     `xml:"knowledgeskillkarmacostmin,omitempty" json:"knowledgeskillkarmacostmin,omitempty"`
	Knowledgeskillkarmacostmultiplier              []Knowledgeskillkarmacostmultiplier              `xml:"knowledgeskillkarmacostmultiplier,omitempty" json:"knowledgeskillkarmacostmultiplier,omitempty"`
	Knowledgeskillpointcost                        []Knowledgeskillpointcost                        `xml:"knowledgeskillpointcost,omitempty" json:"knowledgeskillpointcost,omitempty"`
	Knowledgeskillpointcostmultiplier              []Knowledgeskillpointcostmultiplier              `xml:"knowledgeskillpointcostmultiplier,omitempty" json:"knowledgeskillpointcostmultiplier,omitempty"`
	Knowledgeskillpoints                           *Knowledgeskillpoints                            `xml:"knowledgeskillpoints,omitempty" json:"knowledgeskillpoints,omitempty"`
	Lifestylecost                                  []Lifestylecost                                  `xml:"lifestylecost,omitempty" json:"lifestylecost,omitempty"`
	Limitmodifier                                  []Limitmodifier                                  `xml:"limitmodifier,omitempty" json:"limitmodifier,omitempty"`
	Limitspellcategory                             []Limitspellcategory                             `xml:"limitspellcategory,omitempty" json:"limitspellcategory,omitempty"`
	Limitspiritcategory                            *Limitspiritcategory                             `xml:"limitspiritcategory,omitempty" json:"limitspiritcategory,omitempty"`
	Livingpersona                                  *Livingpersona                                   `xml:"livingpersona,omitempty" json:"livingpersona,omitempty"`
	Matrixinitiativedice                           *Matrixinitiativedice                            `xml:"matrixinitiativedice,omitempty" json:"matrixinitiativedice,omitempty"`
	Movementreplace                                []Movementreplace                                `xml:"movementreplace,omitempty" json:"movementreplace,omitempty"`
	Newspellkarmacost                              *Newspellkarmacost                               `xml:"newspellkarmacost,omitempty" json:"newspellkarmacost,omitempty"`
	Nuyenamt                                       *Nuyenamt                                        `xml:"nuyenamt,omitempty" json:"nuyenamt,omitempty"`
	Optionalpowers                                 *Optionalpowers                                  `xml:"optionalpowers,omitempty" json:"optionalpowers,omitempty"`
	Penaltyfreesustain                             []Penaltyfreesustain                             `xml:"penaltyfreesustain,omitempty" json:"penaltyfreesustain,omitempty"`
	Replaceattributes                              *Replaceattributes                               `xml:"replaceattributes,omitempty" json:"replaceattributes,omitempty"`
	Restrictedgear                                 []Restrictedgear                                 `xml:"restrictedgear,omitempty" json:"restrictedgear,omitempty"`
	Runmultiplier                                  []Runmultiplier                                  `xml:"runmultiplier,omitempty" json:"runmultiplier,omitempty"`
	Selectattribute                                *Selectattribute                                 `xml:"selectattribute,omitempty" json:"selectattribute,omitempty"`
	Selectattributes                               *Selectattributes                                `xml:"selectattributes,omitempty" json:"selectattributes,omitempty"`
	Selectcontact                                  *Selectcontact                                   `xml:"selectcontact,omitempty" json:"selectcontact,omitempty"`
	Selectexpertise                                []Selectexpertise                                `xml:"selectexpertise,omitempty" json:"selectexpertise,omitempty"`
	Selectpowers                                   *Selectpowers                                    `xml:"selectpowers,omitempty" json:"selectpowers,omitempty"`
	Selectquality                                  *Selectquality                                   `xml:"selectquality,omitempty" json:"selectquality,omitempty"`
	Selectskill                                    *Selectskill                                     `xml:"selectskill,omitempty" json:"selectskill,omitempty"`
	Selectskillgroup                               *Selectskillgroup                                `xml:"selectskillgroup,omitempty" json:"selectskillgroup,omitempty"`
	Selectweapon                                   *Selectweapon                                    `xml:"selectweapon,omitempty" json:"selectweapon,omitempty"`
	Skillarticulation                              *Skillarticulation                               `xml:"skillarticulation,omitempty" json:"skillarticulation,omitempty"`
	Skillattribute                                 []Skillattribute                                 `xml:"skillattribute,omitempty" json:"skillattribute,omitempty"`
	Skillcategory                                  []Skillcategory                                  `xml:"skillcategory,omitempty" json:"skillcategory,omitempty"`
	Skillcategorykarmacost                         []Skillcategorykarmacost                         `xml:"skillcategorykarmacost,omitempty" json:"skillcategorykarmacost,omitempty"`
	Skillcategorykarmacostmultiplier               []Skillcategorykarmacostmultiplier               `xml:"skillcategorykarmacostmultiplier,omitempty" json:"skillcategorykarmacostmultiplier,omitempty"`
	Skillcategorypointcost                         []Skillcategorypointcost                         `xml:"skillcategorypointcost,omitempty" json:"skillcategorypointcost,omitempty"`
	Skillcategorypointcostmultiplier               []Skillcategorypointcostmultiplier               `xml:"skillcategorypointcostmultiplier,omitempty" json:"skillcategorypointcostmultiplier,omitempty"`
	Skillcategoryspecializationkarmacost           []Skillcategoryspecializationkarmacost           `xml:"skillcategoryspecializationkarmacost,omitempty" json:"skillcategoryspecializationkarmacost,omitempty"`
	Skillcategoryspecializationkarmacostmultiplier []Skillcategoryspecializationkarmacostmultiplier `xml:"skillcategoryspecializationkarmacostmultiplier,omitempty" json:"skillcategoryspecializationkarmacostmultiplier,omitempty"`
	Skillgroup                                     []Skillgroup                                     `xml:"skillgroup,omitempty" json:"skillgroup,omitempty"`
	Skillgroupcategorykarmacost                    []Skillgroupcategorykarmacost                    `xml:"skillgroupcategorykarmacost,omitempty" json:"skillgroupcategorykarmacost,omitempty"`
	Skillgroupcategorykarmacostmultiplier          []Skillgroupcategorykarmacostmultiplier          `xml:"skillgroupcategorykarmacostmultiplier,omitempty" json:"skillgroupcategorykarmacostmultiplier,omitempty"`
	Skillgroupcategorypointcost                    []Skillgroupcategorypointcost                    `xml:"skillgroupcategorypointcost,omitempty" json:"skillgroupcategorypointcost,omitempty"`
	Skillgroupcategorypointcostmultiplier          []Skillgroupcategorypointcostmultiplier          `xml:"skillgroupcategorypointcostmultiplier,omitempty" json:"skillgroupcategorypointcostmultiplier,omitempty"`
	Skillgroupkarmacost                            []Skillgroupkarmacost                            `xml:"skillgroupkarmacost,omitempty" json:"skillgroupkarmacost,omitempty"`
	Skillgroupkarmacostmultiplier                  []Skillgroupkarmacostmultiplier                  `xml:"skillgroupkarmacostmultiplier,omitempty" json:"skillgroupkarmacostmultiplier,omitempty"`
	Skillgrouplevel                                []Skillgrouplevel                                `xml:"skillgrouplevel,omitempty" json:"skillgrouplevel,omitempty"`
	Skillgrouppointcost                            []Skillgrouppointcost                            `xml:"skillgrouppointcost,omitempty" json:"skillgrouppointcost,omitempty"`
	Skillgrouppointcostmultiplier                  []Skillgrouppointcostmultiplier                  `xml:"skillgrouppointcostmultiplier,omitempty" json:"skillgrouppointcostmultiplier,omitempty"`
	Skilllinkedattribute                           []Skilllinkedattribute                           `xml:"skilllinkedattribute,omitempty" json:"skilllinkedattribute,omitempty"`
	Skillsoft                                      []Skillsoft                                      `xml:"skillsoft,omitempty" json:"skillsoft,omitempty"`
	Skillsoftaccess                                *Skillsoftaccess                                 `xml:"skillsoftaccess,omitempty" json:"skillsoftaccess,omitempty"`
	Skillwire                                      *Skillwire                                       `xml:"skillwire,omitempty" json:"skillwire,omitempty"`
	Specificattribute                              []Specificattribute                              `xml:"specificattribute,omitempty" json:"specificattribute,omitempty"`
	Specificpower                                  []Specificpower                                  `xml:"specificpower,omitempty" json:"specificpower,omitempty"`
	Specificskill                                  []Specificskill                                  `xml:"specificskill,omitempty" json:"specificskill,omitempty"`
	Spellcategory                                  []Spellcategory                                  `xml:"spellcategory,omitempty" json:"spellcategory,omitempty"`
	Spellcategorydamage                            []Spellcategorydamage                            `xml:"spellcategorydamage,omitempty" json:"spellcategorydamage,omitempty"`
	Spellcategorydrain                             []Spellcategorydrain                             `xml:"spellcategorydrain,omitempty" json:"spellcategorydrain,omitempty"`
	Spelldescriptordamage                          []Spelldescriptordamage                          `xml:"spelldescriptordamage,omitempty" json:"spelldescriptordamage,omitempty"`
	Spelldescriptordrain                           []Spelldescriptordrain                           `xml:"spelldescriptordrain,omitempty" json:"spelldescriptordrain,omitempty"`
	Spelldicepool                                  []Spelldicepool                                  `xml:"spelldicepool,omitempty" json:"spelldicepool,omitempty"`
	Sprintbonus                                    []Sprintbonus                                    `xml:"sprintbonus,omitempty" json:"sprintbonus,omitempty"`
	Swapskillattribute                             *Swapskillattribute                              `xml:"swapskillattribute,omitempty" json:"swapskillattribute,omitempty"`
	Swapskillspecattribute                         *Swapskillspecattribute                          `xml:"swapskillspecattribute,omitempty" json:"swapskillspecattribute,omitempty"`
	Unlockskills                                   []Unlockskills                                   `xml:"unlockskills,omitempty" json:"unlockskills,omitempty"`
	Walkmultiplier                                 []Walkmultiplier                                 `xml:"walkmultiplier,omitempty" json:"walkmultiplier,omitempty"`
	Weaponcategorydv                               *Weaponcategorydv                                `xml:"weaponcategorydv,omitempty" json:"weaponcategorydv,omitempty"`
	Weaponcategorydice                             *Weaponcategorydice                              `xml:"weaponcategorydice,omitempty" json:"weaponcategorydice,omitempty"`
	Weaponaccuracy                                 []Weaponaccuracy                                 `xml:"weaponaccuracy,omitempty" json:"weaponaccuracy,omitempty"`
	Weaponrangemodifier                            []Weaponrangemodifier                            `xml:"weaponrangemodifier,omitempty" json:"weaponrangemodifier,omitempty"`
	Weaponskillaccuracy                            []Weaponskillaccuracy                            `xml:"weaponskillaccuracy,omitempty" json:"weaponskillaccuracy,omitempty"`
	Acidarmor                                      []bool                                           `xml:"acidarmor,omitempty" json:"acidarmor,omitempty"`
	Adapsin                                        []bool                                           `xml:"adapsin,omitempty" json:"adapsin,omitempty"`
	Addesstophysicalcmrecovery                     []bool                                           `xml:"addesstophysicalcmrecovery,omitempty" json:"addesstophysicalcmrecovery,omitempty"`
	Addesstostuncmrecovery                         []bool                                           `xml:"addesstostuncmrecovery,omitempty" json:"addesstostuncmrecovery,omitempty"`
	Adeptlinguistics                               []bool                                           `xml:"adeptlinguistics,omitempty" json:"adeptlinguistics,omitempty"`
	Adeptpowerpoints                               []bool                                           `xml:"adeptpowerpoints,omitempty" json:"adeptpowerpoints,omitempty"`
	Allowspellcategory                             []bool                                           `xml:"allowspellcategory,omitempty" json:"allowspellcategory,omitempty"`
	Allowspelldescriptor                           []bool                                           `xml:"allowspelldescriptor,omitempty" json:"allowspelldescriptor,omitempty"`
	Allowspellrange                                []bool                                           `xml:"allowspellrange,omitempty" json:"allowspellrange,omitempty"`
	Allowspritefettering                           []bool                                           `xml:"allowspritefettering,omitempty" json:"allowspritefettering,omitempty"`
	Ambidextrous                                   []bool                                           `xml:"ambidextrous,omitempty" json:"ambidextrous,omitempty"`
	Armorencumbrancepenalty                        []bool                                           `xml:"armorencumbrancepenalty,omitempty" json:"armorencumbrancepenalty,omitempty"`
	Basicbiowareessmultiplier                      []bool                                           `xml:"basicbiowareessmultiplier,omitempty" json:"basicbiowareessmultiplier,omitempty"`
	Biowareessmultiplier                           []string                                         `xml:"biowareessmultiplier,omitempty" json:"biowareessmultiplier,omitempty"`
	Biowaretotalessmultiplier                      []bool                                           `xml:"biowaretotalessmultiplier,omitempty" json:"biowaretotalessmultiplier,omitempty"`
	Blockskillgroupdefaulting                      []bool                                           `xml:"blockskillgroupdefaulting,omitempty" json:"blockskillgroupdefaulting,omitempty"`
	Blockskillcategorydefaulting                   []string                                         `xml:"blockskillcategorydefaulting,omitempty" json:"blockskillcategorydefaulting,omitempty"`
	Biowareessmultipliernonretroactive             []bool                                           `xml:"biowareessmultipliernonretroactive,omitempty" json:"biowareessmultipliernonretroactive,omitempty"`
	Biowaretotalessmultipliernonretroactive        []bool                                           `xml:"biowaretotalessmultipliernonretroactive,omitempty" json:"biowaretotalessmultipliernonretroactive,omitempty"`
	Blackmarketdiscount                            []bool                                           `xml:"blackmarketdiscount,omitempty" json:"blackmarketdiscount,omitempty"`
	Blockskillcategoryspecializations              []bool                                           `xml:"blockskillcategoryspecializations,omitempty" json:"blockskillcategoryspecializations,omitempty"`
	Blockskillspecializations                      []bool                                           `xml:"blockskillspecializations,omitempty" json:"blockskillspecializations,omitempty"`
	Blockspelldescriptor                           []string                                         `xml:"blockspelldescriptor,omitempty" json:"blockspelldescriptor,omitempty"`
	Bornrich                                       []bool                                           `xml:"bornrich,omitempty" json:"bornrich,omitempty"`
	Burnoutsway                                    []bool                                           `xml:"burnoutsway,omitempty" json:"burnoutsway,omitempty"`
	Coldarmor                                      []string                                         `xml:"coldarmor,omitempty" json:"coldarmor,omitempty"`
	Complexformlimit                               []bool                                           `xml:"complexformlimit,omitempty" json:"complexformlimit,omitempty"`
	Composure                                      []bool                                           `xml:"composure,omitempty" json:"composure,omitempty"`
	Concealability                                 []bool                                           `xml:"concealability,omitempty" json:"concealability,omitempty"`
	Contactkarma                                   []string                                         `xml:"contactkarma,omitempty" json:"contactkarma,omitempty"`
	Contactkarmaminimum                            []string                                         `xml:"contactkarmaminimum,omitempty" json:"contactkarmaminimum,omitempty"`
	Cyberseeker                                    []string                                         `xml:"cyberseeker,omitempty" json:"cyberseeker,omitempty"`
	Cyberwareessmultiplier                         []bool                                           `xml:"cyberwareessmultiplier,omitempty" json:"cyberwareessmultiplier,omitempty"`
	Cyberwaretotalessmultiplier                    []string                                         `xml:"cyberwaretotalessmultiplier,omitempty" json:"cyberwaretotalessmultiplier,omitempty"`
	Cyberwareessmultipliernonretroactive           []bool                                           `xml:"cyberwareessmultipliernonretroactive,omitempty" json:"cyberwareessmultipliernonretroactive,omitempty"`
	Cyberwaretotalessmultipliernonretroactive      []bool                                           `xml:"cyberwaretotalessmultipliernonretroactive,omitempty" json:"cyberwaretotalessmultipliernonretroactive,omitempty"`
	Damageresistance                               []string                                         `xml:"damageresistance,omitempty" json:"damageresistance,omitempty"`
	Decreaseagiresist                              []bool                                           `xml:"decreaseagiresist,omitempty" json:"decreaseagiresist,omitempty"`
	Decreasebodresist                              []bool                                           `xml:"decreasebodresist,omitempty" json:"decreasebodresist,omitempty"`
	Decreasecharesist                              []bool                                           `xml:"decreasecharesist,omitempty" json:"decreasecharesist,omitempty"`
	Decreaseintresist                              []string                                         `xml:"decreaseintresist,omitempty" json:"decreaseintresist,omitempty"`
	Decreaselogresist                              []string                                         `xml:"decreaselogresist,omitempty" json:"decreaselogresist,omitempty"`
	Decreaserearesist                              []bool                                           `xml:"decreaserearesist,omitempty" json:"decreaserearesist,omitempty"`
	Decreasestrresist                              []bool                                           `xml:"decreasestrresist,omitempty" json:"decreasestrresist,omitempty"`
	Decreasewilresist                              []bool                                           `xml:"decreasewilresist,omitempty" json:"decreasewilresist,omitempty"`
	Detectionspellresist                           []string                                         `xml:"detectionspellresist,omitempty" json:"detectionspellresist,omitempty"`
	Drainresist                                    []string                                         `xml:"drainresist,omitempty" json:"drainresist,omitempty"`
	Disablebioware                                 []bool                                           `xml:"disablebioware,omitempty" json:"disablebioware,omitempty"`
	Disablebiowaregrade                            []string                                         `xml:"disablebiowaregrade,omitempty" json:"disablebiowaregrade,omitempty"`
	Disablecyberware                               []bool                                           `xml:"disablecyberware,omitempty" json:"disablecyberware,omitempty"`
	Dodge                                          []string                                         `xml:"dodge,omitempty" json:"dodge,omitempty"`
	Directmanaspellresist                          []bool                                           `xml:"directmanaspellresist,omitempty" json:"directmanaspellresist,omitempty"`
	Directphysicalspellresist                      []bool                                           `xml:"directphysicalspellresist,omitempty" json:"directphysicalspellresist,omitempty"`
	Disablecyberwaregrade                          []string                                         `xml:"disablecyberwaregrade,omitempty" json:"disablecyberwaregrade,omitempty"`
	Electricityarmor                               []string                                         `xml:"electricityarmor,omitempty" json:"electricityarmor,omitempty"`
	Erased                                         []bool                                           `xml:"erased,omitempty" json:"erased,omitempty"`
	Essencemax                                     []string                                         `xml:"essencemax,omitempty" json:"essencemax,omitempty"`
	Essencepenalty                                 []bool                                           `xml:"essencepenalty,omitempty" json:"essencepenalty,omitempty"`
	Essencepenaltydeponlyt100                      []bool                                           `xml:"essencepenaltydeponlyt100,omitempty" json:"essencepenaltydeponlyt100,omitempty"`
	Essencepenaltymagonlyt100                      []bool                                           `xml:"essencepenaltymagonlyt100,omitempty" json:"essencepenaltymagonlyt100,omitempty"`
	Essencepenaltyresonlyt100                      []bool                                           `xml:"essencepenaltyresonlyt100,omitempty" json:"essencepenaltyresonlyt100,omitempty"`
	Essencepenaltyt100                             []bool                                           `xml:"essencepenaltyt100,omitempty" json:"essencepenaltyt100,omitempty"`
	Excon                                          []bool                                           `xml:"excon,omitempty" json:"excon,omitempty"`
	Fadingresist                                   []bool                                           `xml:"fadingresist,omitempty" json:"fadingresist,omitempty"`
	Fallingarmor                                   []bool                                           `xml:"fallingarmor,omitempty" json:"fallingarmor,omitempty"`
	Fame                                           []bool                                           `xml:"fame,omitempty" json:"fame,omitempty"`
	Fatigueresist                                  []string                                         `xml:"fatigueresist,omitempty" json:"fatigueresist,omitempty"`
	Firearmor                                      []string                                         `xml:"firearmor,omitempty" json:"firearmor,omitempty"`
	Freenegativequalities                          []bool                                           `xml:"freenegativequalities,omitempty" json:"freenegativequalities,omitempty"`
	Freepositivequalities                          []bool                                           `xml:"freepositivequalities,omitempty" json:"freepositivequalities,omitempty"`
	Freespiritpowerpoints                          []bool                                           `xml:"freespiritpowerpoints,omitempty" json:"freespiritpowerpoints,omitempty"`
	Friendsinhighplaces                            []bool                                           `xml:"friendsinhighplaces,omitempty" json:"friendsinhighplaces,omitempty"`
	Genetechcostmultiplier                         []string                                         `xml:"genetechcostmultiplier,omitempty" json:"genetechcostmultiplier,omitempty"`
	Genetechessmultiplier                          []string                                         `xml:"genetechessmultiplier,omitempty" json:"genetechessmultiplier,omitempty"`
	Ignorecmpenaltyphysical                        []bool                                           `xml:"ignorecmpenaltyphysical,omitempty" json:"ignorecmpenaltyphysical,omitempty"`
	Ignorecmpenaltystun                            []bool                                           `xml:"ignorecmpenaltystun,omitempty" json:"ignorecmpenaltystun,omitempty"`
	Infirm                                         []bool                                           `xml:"infirm,omitempty" json:"infirm,omitempty"`
	Initiativepassadd                              []bool                                           `xml:"initiativepassadd,omitempty" json:"initiativepassadd,omitempty"`
	Judgeintentions                                []string                                         `xml:"judgeintentions,omitempty" json:"judgeintentions,omitempty"`
	Judgeintentionsdefense                         []string                                         `xml:"judgeintentionsdefense,omitempty" json:"judgeintentionsdefense,omitempty"`
	Judgeintentionsoffense                         []string                                         `xml:"judgeintentionsoffense,omitempty" json:"judgeintentionsoffense,omitempty"`
	Liftandcarry                                   []bool                                           `xml:"liftandcarry,omitempty" json:"liftandcarry,omitempty"`
	Lightningreflexes                              []bool                                           `xml:"lightningreflexes,omitempty" json:"lightningreflexes,omitempty"`
	Limitcritterpowercategory                      []bool                                           `xml:"limitcritterpowercategory,omitempty" json:"limitcritterpowercategory,omitempty"`
	Limitspelldescriptor                           []bool                                           `xml:"limitspelldescriptor,omitempty" json:"limitspelldescriptor,omitempty"`
	Limitspellrange                                []bool                                           `xml:"limitspellrange,omitempty" json:"limitspellrange,omitempty"`
	Mademan                                        []bool                                           `xml:"mademan,omitempty" json:"mademan,omitempty"`
	Magicianswaydiscount                           []bool                                           `xml:"magicianswaydiscount,omitempty" json:"magicianswaydiscount,omitempty"`
	Manaillusionresist                             []string                                         `xml:"manaillusionresist,omitempty" json:"manaillusionresist,omitempty"`
	Martialart                                     []string                                         `xml:"martialart,omitempty" json:"martialart,omitempty"`
	Matrixinitiative                               []bool                                           `xml:"matrixinitiative,omitempty" json:"matrixinitiative,omitempty"`
	Matrixinitiativediceadd                        []bool                                           `xml:"matrixinitiativediceadd,omitempty" json:"matrixinitiativediceadd,omitempty"`
	Memory                                         []string                                         `xml:"memory,omitempty" json:"memory,omitempty"`
	Mentallimit                                    []string                                         `xml:"mentallimit,omitempty" json:"mentallimit,omitempty"`
	Mentalmanipulationresist                       []string                                         `xml:"mentalmanipulationresist,omitempty" json:"mentalmanipulationresist,omitempty"`
	Metageniclimit                                 []string                                         `xml:"metageniclimit,omitempty" json:"metageniclimit,omitempty"`
	Nativelanguagelimit                            []bool                                           `xml:"nativelanguagelimit,omitempty" json:"nativelanguagelimit,omitempty"`
	Newaiadvancedprogramkarmacost                 []string                                         `xml:"newaiadvancedprogramkarmacost,omitempty" json:"newaiadvancedprogramkarmacost,omitempty"`
	Newaiadvancedprogramkarmacostmultiplier       []string                                         `xml:"newaiadvancedprogramkarmacostmultiplier,omitempty" json:"newaiadvancedprogramkarmacostmultiplier,omitempty"`
	Newaiprogramkarmacost                         []string                                         `xml:"newaiprogramkarmacost,omitempty" json:"newaiprogramkarmacost,omitempty"`
	Newaiprogramkarmacostmultiplier               []string                                         `xml:"newaiprogramkarmacostmultiplier,omitempty" json:"newaiprogramkarmacostmultiplier,omitempty"`
	Newcomplexformkarmacost                         []string                                         `xml:"newcomplexformkarmacost,omitempty" json:"newcomplexformkarmacost,omitempty"`
	Newcomplexformkarmacostmultiplier               []string                                         `xml:"newcomplexformkarmacostmultiplier,omitempty" json:"newcomplexformkarmacostmultiplier,omitempty"`
	Newspellkarma[]string                                           `xml:"newspellkarmacostmultiplier,omitempty" json:"newspellkarmacostmultiplier,omitempty"`
	Notoriety                                      []string                                         `xml:"notoriety,omitempty" json:"notoriety,omitempty"`
	Nuyenmaxbp                                     []string                                         `xml:"nuyenmaxbp,omitempty" json:"nuyenmaxbp,omitempty"`
	Overclocker                                    []bool                                           `xml:"overclocker,omitempty" json:"overclocker,omitempty"`
	Pathogencontactimmune                          []bool                                           `xml:"pathogencontactimmune,omitempty" json:"pathogencontactimmune,omitempty"`
	Pathogencontactresist                          []string                                         `xml:"pathogencontactresist,omitempty" json:"pathogencontactresist,omitempty"`
	Pathogeningestionimmune                        []bool                                           `xml:"pathogeningestionimmune,omitempty" json:"pathogeningestionimmune,omitempty"`
	Pathogeningestionresist                        []string                                         `xml:"pathogeningestionresist,omitempty" json:"pathogeningestionresist,omitempty"`
	Pathogeninhalationimmune                       []bool                                           `xml:"pathogeninhalationimmune,omitempty" json:"pathogeninhalationimmune,omitempty"`
	Pathogeninhalationresist                       []string                                         `xml:"pathogeninhalationresist,omitempty" json:"pathogeninhalationresist,omitempty"`
	Pathogeninjectionimmune                        []bool                                           `xml:"pathogeninjectionimmune,omitempty" json:"pathogeninjectionimmune,omitempty"`
	Pathogeninjectionresist                        []string                                         `xml:"pathogeninjectionresist,omitempty" json:"pathogeninjectionresist,omitempty"`
	Physicalcmrecovery                             []string                                         `xml:"physicalcmrecovery,omitempty" json:"physicalcmrecovery,omitempty"`
	Physicalillusionresist                         []string                                         `xml:"physicalillusionresist,omitempty" json:"physicalillusionresist,omitempty"`
	Physicallimit                                  []string                                         `xml:"physicallimit,omitempty" json:"physicallimit,omitempty"`
	Physicalmanipulationresist                     []bool                                           `xml:"physicalmanipulationresist,omitempty" json:"physicalmanipulationresist,omitempty"`
	Physiologicaladdictionalreadyaddicted          []string                                         `xml:"physiologicaladdictionalreadyaddicted,omitempty" json:"physiologicaladdictionalreadyaddicted,omitempty"`
	Physiologicaladdictionfirsttime                []string                                         `xml:"physiologicaladdictionfirsttime,omitempty" json:"physiologicaladdictionfirsttime,omitempty"`
	Prototypetranshuman                            []string                                         `xml:"prototypetranshuman,omitempty" json:"prototypetranshuman,omitempty"`
	Psychologicaladdictionalreadyaddicted          []string                                         `xml:"psychologicaladdictionalreadyaddicted,omitempty" json:"psychologicaladdictionalreadyaddicted,omitempty"`
	Psychologicaladdictionfirsttime                []string                                         `xml:"psychologicaladdictionfirsttime,omitempty" json:"psychologicaladdictionfirsttime,omitempty"`
	Publicawareness                                []string                                         `xml:"publicawareness,omitempty" json:"publicawareness,omitempty"`
	Quickeningmetamagic                            []bool                                           `xml:"quickeningmetamagic,omitempty" json:"quickeningmetamagic,omitempty"`
	Radiationresist                                []string                                         `xml:"radiationresist,omitempty" json:"radiationresist,omitempty"`
	Reach                                          []string                                         `xml:"reach,omitempty" json:"reach,omitempty"`
	Reflexrecorderoptimization                     []bool                                           `xml:"reflexrecorderoptimization,omitempty" json:"reflexrecorderoptimization,omitempty"`
	Selectarmor                                    []bool                                           `xml:"selectarmor,omitempty" json:"selectarmor,omitempty"`
	Selectinherentaiprogram                        []bool                                           `xml:"selectinherentaiprogram,omitempty" json:"selectinherentaiprogram,omitempty"`
	Selectmentorspirit                             []bool                                           `xml:"selectmentorspirit,omitempty" json:"selectmentorspirit,omitempty"`
	Selectparagon                                  []bool                                           `xml:"selectparagon,omitempty" json:"selectparagon,omitempty"`
	Selectrestricted                               []bool                                           `xml:"selectrestricted,omitempty" json:"selectrestricted,omitempty"`
	Selectside                                     []bool                                           `xml:"selectside,omitempty" json:"selectside,omitempty"`
	Selectspell                                    []bool                                           `xml:"selectspell,omitempty" json:"selectspell,omitempty"`
	Selectsprite                                   []bool                                           `xml:"selectsprite,omitempty" json:"selectsprite,omitempty"`
	Selecttext                                     []Selecttext                                     `xml:"selecttext,omitempty" json:"selecttext,omitempty"`
	Selecttradition                                []bool                                           `xml:"selecttradition,omitempty" json:"selecttradition,omitempty"`
	Sensitivesystem                                []bool                                           `xml:"sensitivesystem,omitempty" json:"sensitivesystem,omitempty"`
	Skilldisable                                   []string                                         `xml:"skilldisable,omitempty" json:"skilldisable,omitempty"`
	Skillgroupcategorydisable                      []string                                         `xml:"skillgroupcategorydisable,omitempty" json:"skillgroupcategorydisable,omitempty"`
	Skillgroupdisable                              []string                                         `xml:"skillgroupdisable,omitempty" json:"skillgroupdisable,omitempty"`
	Smartlink                                      []bool                                           `xml:"smartlink,omitempty" json:"smartlink,omitempty"`
	Sociallimit                                    []string                                         `xml:"sociallimit,omitempty" json:"sociallimit,omitempty"`
	Softweave                                      []bool                                           `xml:"softweave,omitempty" json:"softweave,omitempty"`
	Sonicresist                                    []bool                                           `xml:"sonicresist,omitempty" json:"sonicresist,omitempty"`
	Specialattburnmultiplier                       []bool                                           `xml:"specialattburnmultiplier,omitempty" json:"specialattburnmultiplier,omitempty"`
	Specialatttotalburnmultiplier                  []bool                                           `xml:"specialatttotalburnmultiplier,omitempty" json:"specialatttotalburnmultiplier,omitempty"`
	Specialmodificationlimit                       []bool                                           `xml:"specialmodificationlimit,omitempty" json:"specialmodificationlimit,omitempty"`
	Spelllimit                                     []bool                                           `xml:"spelllimit,omitempty" json:"spelllimit,omitempty"`
	Spellresistance                                []string                                         `xml:"spellresistance,omitempty" json:"spellresistance,omitempty"`
	Streetcredmultiplier                           []string                                         `xml:"streetcredmultiplier,omitempty" json:"streetcredmultiplier,omitempty"`
	Stuncmrecovery                                 []string                                         `xml:"stuncmrecovery,omitempty" json:"stuncmrecovery,omitempty"`
	Surprise                                       []string                                         `xml:"surprise,omitempty" json:"surprise,omitempty"`
	Throwrange                                     []bool                                           `xml:"throwrange,omitempty" json:"throwrange,omitempty"`
	Throwrangestr                                  []string                                         `xml:"throwrangestr,omitempty" json:"throwrangestr,omitempty"`
	Throwstr                                       []bool                                           `xml:"throwstr,omitempty" json:"throwstr,omitempty"`
	Toxincontactimmune                             []bool                                           `xml:"toxincontactimmune,omitempty" json:"toxincontactimmune,omitempty"`
	Toxincontactresist                             []string                                         `xml:"toxincontactresist,omitempty" json:"toxincontactresist,omitempty"`
	Toxiningestionimmune                           []bool                                           `xml:"toxiningestionimmune,omitempty" json:"toxiningestionimmune,omitempty"`
	Toxiningestionresist                           []string                                         `xml:"toxiningestionresist,omitempty" json:"toxiningestionresist,omitempty"`
	Toxininhalationimmune                          []bool                                           `xml:"toxininhalationimmune,omitempty" json:"toxininhalationimmune,omitempty"`
	Toxininhalationresist                          []string                                         `xml:"toxininhalationresist,omitempty" json:"toxininhalationresist,omitempty"`
	Toxininjectionimmune                           []bool                                           `xml:"toxininjectionimmune,omitempty" json:"toxininjectionimmune,omitempty"`
	Toxininjectionresist                           []string                                         `xml:"toxininjectionresist,omitempty" json:"toxininjectionresist,omitempty"`
	Trustfund                                      []bool                                           `xml:"trustfund,omitempty" json:"trustfund,omitempty"`
	Unarmedap                                      []string                                         `xml:"unarmedap,omitempty" json:"unarmedap,omitempty"`
	Unarmeddv                                      []string                                         `xml:"unarmeddv,omitempty" json:"unarmeddv,omitempty"`
	Unarmeddvphysical                              []bool                                           `xml:"unarmeddvphysical,omitempty" json:"unarmeddvphysical,omitempty"`

	// Unique identifier attribute
	Unique      string   `xml:"unique,attr,omitempty" json:"+@unique,omitempty"`
	UseSelected *Boolean `xml:"useselected,attr,omitempty" json:"+@useselected,omitempty"`
}
