package v5

import "shadowmaster/pkg/shadowrun/edition/v5/common"

// Code generated from critterpowers.xml. DO NOT EDIT.

var critterPowersData = &CritterPowersChummer{
	Categories: []CritterPowerCategories{
		{
			Category: []CritterPowerCategory{
				{
					Content: "Drake",
				},
				{
					Content: "Emergent",
				},
				{
					Content: "Free Spirit",
				},
				{
					Content: "Infected",
				},
				{
					Content: "Mundane",
				},
				{
					Content: "Paranormal",
				},
				{
					Content: "Toxic Critter Powers",
				},
				{
					Content: "Weakness",
				},
				{
					Content: "Chimeric Modification",
				},
			},
		},
	},
	Powers: []CritterPowerItems{
		{
			Power: []CritterPowerItem{
				{
					ID: "57dd33b3-7fea-421e-bcf3-336d56ea08b5",
					Name: "Combat Skill",
					Category: "Paranormal",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "130",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					Bonus: &common.BaseBonus{
						Selectskill: &common.Selectskill{},
					},
					Karma: stringPtr(""),
				},
				{
					ID: "a3f11764-2569-48a1-8eb8-8cdae58b23e8",
					Name: "Physical Skill",
					Category: "Paranormal",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "133",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					Bonus: &common.BaseBonus{
						Selectskill: &common.Selectskill{},
					},
					Karma: stringPtr(""),
				},
				{
					ID: "410c17d0-0490-4e67-b2ca-4ad5e2feb016",
					Name: "Social Skill",
					Category: "Paranormal",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "137",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					Bonus: &common.BaseBonus{
						Selectskill: &common.Selectskill{},
					},
					Karma: stringPtr(""),
				},
				{
					ID: "07229dc9-3b46-4843-a30a-7b7c4c144ea0",
					Name: "Technical Skill",
					Category: "Paranormal",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "143",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					Bonus: &common.BaseBonus{
						Selectskill: &common.Selectskill{},
					},
					Karma: stringPtr(""),
				},
				{
					ID: "bb55305e-0c6f-47bd-a92f-ce85df478096",
					Name: "Vehicle Skill",
					Category: "Paranormal",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "146",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					Bonus: &common.BaseBonus{
						Selectskill: &common.Selectskill{},
					},
					Karma: stringPtr(""),
				},
				{
					ID: "d9e0cc36-3183-4fa6-b9a6-b7e62d7d72fc",
					Name: "Sense Link",
					Category: "Mundane",
					Type: "M",
					Action: "Simple",
					Range: "MAG x 50",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "198",
					},
				},
				{
					ID: "99af5d63-9f6a-4a32-9bf6-9b8500a3c64c",
					Name: "Accident",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "394",
					},
				},
				{
					ID: "1814f970-111f-4d56-9402-f584daa02663",
					Name: "Animal Control",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "394",
					},
					Toxic: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "0ea84be4-a293-44bf-bc60-52314495cc9a",
					Name: "Astral Form",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "394",
					},
				},
				{
					ID: "aca5b1a9-6b7f-49fa-aee4-ba20b4ee2f26",
					Name: "Binding",
					Category: "Mundane",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
				},
				{
					ID: "f6631c45-a705-434c-b4a6-ba2a889d38ff",
					Name: "Compulsion",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
				},
				{
					ID: "1898d408-116a-4f98-b413-939660692ce7",
					Name: "Concealment",
					Category: "Paranormal",
					Type: "P",
					Action: "Simple",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
				},
				{
					ID: "4517126f-6dcf-4c73-b7f5-cac77532c1f5",
					Name: "Confusion",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "1ddf4e08-8249-477c-ba8b-1b910428bf45",
					Name: "Corrosive Spit",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "6ca4a4af-7da0-4cc2-b545-0fe0396cfb46",
					Name: "Dual Natured",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
					Bonus: &common.BaseBonus{
						Unlockskills: []common.Unlockskills{
							// 2 items omitted
						},
					},
				},
				{
					ID: "37e62625-1099-426f-94c9-2750aaa9902b",
					Name: "Elemental Attack",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "396",
					},
					Toxic: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "37bc7c80-beb9-424d-a4b4-db8d3a31612c",
					Name: "Energy Aura",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "396",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "b289f6de-dc68-49a2-9d08-a9dcafdf9bac",
					Name: "Enhanced Senses",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "396",
					},
					Toxic: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "24455a2c-c98c-4748-a720-1403a726fd57",
					Name: "Essence Drain",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Permanent",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "396",
					},
				},
				{
					ID: "953d3e23-cba0-440d-bab4-4234f1090ac5",
					Name: "Fear",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "397",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "13dc5c5d-ef46-433e-b27b-5775a57035a8",
					Name: "Guard",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "397",
					},
				},
				{
					ID: "08b3b1bd-94cc-4468-a61f-31baade2a08e",
					Name: "Hardened Armor",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "397",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
				},
				{
					ID: "c8ad6b5e-5520-4ea6-a472-a1fa51634c74",
					Name: "Immunity",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "397",
					},
					Toxic: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "951cb295-b6c6-4ff2-9a9e-2a49cc047fd1",
					Name: "Infection",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Touch",
					Duration: "Permanent",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "398",
					},
				},
				{
					ID: "e8013773-9497-472e-b2af-e96e49405290",
					Name: "Influence",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "398",
					},
				},
				{
					ID: "fe38ce43-3cf2-456d-aec2-0029e0bf173f",
					Name: "Innate Spell",
					Category: "Paranormal",
					Type: "As Spell",
					Action: "Complex",
					Range: "Per Spell",
					Duration: "Per Spell",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "398",
					},
					Bonus: &common.BaseBonus{
						Enabletab: &common.Enabletab{},
						Selectspell: []bool{
							// 1 items omitted
						},
					},
				},
				{
					ID: "43ff8bf8-a5e5-424c-9dc8-a5229eeea62f",
					Name: "Magic Resistance",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "76",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Spellresistance: []string{
							// 1 items omitted
						},
					},
				},
				{
					ID: "bf6c7543-0fa6-4297-8690-8230db5e46a8",
					Name: "Materialization",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "398",
					},
				},
				{
					ID: "c5ecc4fa-3f9d-49da-ad63-3ee35843ca17",
					Name: "Manifest",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "314",
					},
				},
				{
					ID: "153bc9aa-1a5e-41ac-877d-751470624bc7",
					Name: "Mimicry",
					Category: "Paranormal",
					Type: "P",
					Action: "Simple",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "398",
					},
				},
				{
					ID: "b43373c3-5006-4396-bbbb-a154b8c92eae",
					Name: "Mist Form",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "398",
					},
				},
				{
					ID: "5090e9d2-07ba-4fb0-965c-5d5de29062b7",
					Name: "Movement",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "399",
					},
				},
				{
					ID: "aa886ded-bf17-43e6-a7b5-82d77ed96a9c",
					Name: "Mystic Armor",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "399",
					},
					Rating: stringPtr("True"),
				},
				{
					ID: "9fc065db-9d63-4e8b-aba9-e19dfba07652",
					Name: "Natural Weapon",
					Category: "Mundane",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "399",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "4709630d-f2d0-40cc-915b-4f41eb8a4092",
					Name: "Noxious Breath",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "399",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "f2c04372-d264-42fa-b0b4-534035888ad7",
					Name: "Paralyzing Howl",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "399",
					},
				},
				{
					ID: "46ee1218-4b63-458d-b9b9-ec5b2bb607f0",
					Name: "Psychokinesis",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "400",
					},
				},
				{
					ID: "244ccf0f-fc77-4690-9441-1cfeb7a6dc2a",
					Name: "Regeneration",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "400",
					},
					Bonus: &common.BaseBonus{
						Disablebiowaregrade: []string{
							// 12 items omitted
						},
						Disablecyberwaregrade: []string{
							// 12 items omitted
						},
					},
				},
				{
					ID: "4f694634-7c91-4534-a9ff-7f8ae3002a1e",
					Name: "Search",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "400",
					},
				},
				{
					ID: "bd881fa0-89e4-4734-816f-7ffe7cf5f35f",
					Name: "Sapience",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "400",
					},
				},
				{
					ID: "5e45dcc0-ec66-4bd5-a855-d3ce577dd2b4",
					Name: "Venom",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "401",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "8b460350-fca3-427d-90af-4648666e8723",
					Name: "Weather Control",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "401",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "5dad2b71-d7b0-443f-9871-ea01a381b9d0",
					Name: "Astral Gateway",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "LOS (A)",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "194",
					},
				},
				{
					ID: "89ad414a-9854-44b0-b505-ad0186ccb29f",
					Name: "Aura Masking",
					Category: "Paranormal",
					Type: "M",
					Action: "Free",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "194",
					},
				},
				{
					ID: "ae00c4e4-c036-44b2-894b-1a5cd3fc8fae",
					Name: "Banishing Resistance",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "194",
					},
				},
				{
					ID: "c3e2ee0c-7c4d-479f-997d-7079cb4dee7a",
					Name: "Desire Reflection",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "194",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "cf03e546-90d9-4c3d-8246-19bf57821731",
					Name: "Divining",
					Category: "Paranormal",
					Type: "M",
					Action: "Special",
					Range: "Special",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "194",
					},
				},
				{
					ID: "de152825-2002-4a58-b2a7-08247aae72be",
					Name: "Endowment",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "Touch",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "195",
					},
				},
				{
					ID: "d10138cc-924a-4f2b-a59b-44e0611fb019",
					Name: "Energy Drain",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "Touch or LOS",
					Duration: "Permanent",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "195",
					},
				},
				{
					ID: "f6fb5ceb-91f8-418b-99ee-413e8c16230e",
					Name: "Engulf",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "396",
					},
				},
				{
					ID: "79317297-becf-4c68-9778-6f00fd955a13",
					Name: "Hemorrhage",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "MAG",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "91",
					},
				},
				{
					ID: "30918b00-6dae-4989-9b6e-219c4bd6ac7e",
					Name: "Inhabitation",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "195",
					},
				},
				{
					ID: "f5a654a0-91e3-4555-aa22-792d012348b8",
					Name: "Magical Guard",
					Category: "Paranormal",
					Type: "M",
					Action: "Free",
					Range: "LOS",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "196",
					},
					Bonus: &common.BaseBonus{
						Unlockskills: []common.Unlockskills{
							// 1 items omitted
						},
					},
				},
				{
					ID: "033185f0-bade-4824-8569-8604a734e02b",
					Name: "Mind Link",
					Category: "Paranormal",
					Type: "M",
					Action: "Simple",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "196",
					},
				},
				{
					ID: "a142b612-2f4c-4c97-8b1b-fd15c9f68866",
					Name: "Possession",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "197",
					},
				},
				{
					ID: "21768675-ea17-48f4-abdc-301c3441bf8c",
					Name: "Quake",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "197",
					},
				},
				{
					ID: "2381a322-1b0c-4282-b3af-b28828cdf786",
					Name: "Realistic Form",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "198",
					},
				},
				{
					ID: "c9045794-c7f7-4517-9156-b74438a2d5f1",
					Name: "Shadow Cloak",
					Category: "Paranormal",
					Type: "P",
					Action: "Free",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "198",
					},
				},
				{
					ID: "4881c2cc-1e45-43ad-89df-9e5b264648f2",
					Name: "Silence",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "199",
					},
				},
				{
					ID: "ea7d01c8-50f5-4d2a-9fac-a750b189ca36",
					Name: "Storm",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "199",
					},
				},
				{
					ID: "f1750d16-5dc2-4c4e-afae-1ad86c520fc6",
					Name: "Astral Projection",
					Category: "Free Spirit",
					Type: "M",
					Action: "Complex",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "204",
					},
				},
				{
					ID: "189ab2b7-9688-414b-b8ec-35a01db372d4",
					Name: "Mutable Form",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "204",
					},
				},
				{
					ID: "37a152ee-83ce-4a32-b81b-31e79b42c970",
					Name: "Personal Domain",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "205",
					},
				},
				{
					ID: "8e1d96d9-53c9-4924-855c-059815ef973c",
					Name: "Spirit Pact",
					Category: "Free Spirit",
					Type: "M",
					Action: "Special",
					Range: "Special",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "205",
					},
				},
				{
					ID: "e6add326-0ed1-41bd-9d00-40ad5b17a35d",
					Name: "Hidden Life",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Permanent",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "205",
					},
				},
				{
					ID: "9942f3f2-b486-44ff-ad34-c56fd9453d41",
					Name: "Vessel Trading",
					Category: "Free Spirit",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "205",
					},
				},
				{
					ID: "ad40556c-6632-4287-bd69-94ff25c7280e",
					Name: "Wealth",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "205",
					},
				},
				{
					ID: "44dd8deb-891e-4361-bc0c-47c4258ea6fd",
					Name: "Anaphylaxis",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "193",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "3c6b961c-cac8-4e45-91ec-03cf612ac3c3",
					Name: "Mutagen",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "196",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "e525a62b-5762-477d-b242-6e166fdcd6e9",
					Name: "Devouring",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "194",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "ea6c345d-1df6-42b9-92bb-b94fef3360f7",
					Name: "Hive Mind",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Special",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "195",
					},
				},
				{
					ID: "ecbab218-1ba9-41b6-9add-897ccbbf1d52",
					Name: "Pestilence",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "197",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "e5859447-89ad-40f1-aea0-8c5f1e53e9de",
					Name: "Reinforcement",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "198",
					},
				},
				{
					ID: "d9fdc768-9ce4-4c19-8744-b46833349cea",
					Name: "Sonic Projection",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "199",
					},
				},
				{
					ID: "94e58008-2ab1-41ed-886c-74773ec60067",
					Name: "Gestalt Consciousness",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "192",
					},
				},
				{
					ID: "c5a7a660-a036-4b52-a8ab-1e9d7705e65d",
					Name: "Gills",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "192",
					},
				},
				{
					ID: "224f6093-af49-4fd4-a30a-b0c38673ffb7",
					Name: "Secretion/Substance Extrusion",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "193",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "7cdbe90b-b16a-43c0-a20e-b4a54b83c6ed",
					Name: "Wall Walking",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "194",
					},
				},
				{
					ID: "7f98220b-95c4-4b76-aca7-6f0308cf25a7",
					Name: "Adaptive Coloration",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "188",
					},
				},
				{
					ID: "71a78fd2-c75a-46a8-a0f3-320e268a9b4d",
					Name: "Binding",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "73b0e681-fa65-4253-9010-4bac1f7c3179",
					Name: "Control Focus",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Special",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "188",
					},
				},
				{
					ID: "f654869b-d381-4f90-82d6-835f5a4aa0ab",
					Name: "Deathly Aura",
					Category: "Paranormal",
					Type: "P",
					Action: "Simple",
					Range: "Special",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "194",
					},
				},
				{
					ID: "6bd7dbfd-1603-4333-86aa-b4b798caf9d1",
					Name: "Dragonspeech",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "LOS",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
				},
				{
					ID: "8df0b8ba-ef4e-41ea-a571-8c21f221cfde",
					Name: "Empathy",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "190",
					},
				},
				{
					ID: "ca80b896-a524-435f-a787-8df807567de8",
					Name: "Fey Glamour",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "Special",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "191",
					},
				},
				{
					ID: "e36812c9-c918-4d38-a71f-79f04a77a924",
					Name: "Magic Sense",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "193",
					},
					Toxic: stringPtr("True"),
				},
				{
					ID: "525746a4-bd59-4150-8861-2eb2fc7665ac",
					Name: "Metahuman Form",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "RF",
						Page: "213",
					},
				},
				{
					ID: "39442943-8367-4322-b7d2-3575061df3fa",
					Name: "Paralyzing Touch",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "400",
					},
				},
				{
					ID: "90c79eb4-665a-4844-90f3-e495f8cd3e61",
					Name: "Petrification",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "400",
					},
				},
				{
					ID: "2cadebe7-a32d-4852-ac94-e8b86ca3619a",
					Name: "Spirit Pact",
					Category: "Paranormal",
					Type: "M",
					Action: "Special",
					Range: "Special",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "205",
					},
				},
				{
					ID: "a8090271-057c-41d5-bd68-df117ea15b7d",
					Name: "Vanishing",
					Category: "Paranormal",
					Type: "M",
					Action: "Free",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "194",
					},
				},
				{
					ID: "bfe55ba6-5625-425d-ad5c-08dd84ef07ca",
					Name: "AR-Parallelism",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "194",
					},
				},
				{
					ID: "818bf01a-b959-4bb9-b202-45efd3b9819b",
					Name: "Blend",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "194",
					},
				},
				{
					ID: "5aa8f042-2180-43f9-8f46-7053a20cbe45",
					Name: "Cozenge",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "194",
					},
				},
				{
					ID: "b561f86f-683c-4ae3-b867-9c628d5f8953",
					Name: "Diagnostics",
					Category: "Emergent",
					Type: "",
					Action: "Simple",
					Range: "",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "257",
					},
				},
				{
					ID: "4dc7af87-675c-4014-aa05-de6246fc8c14",
					Name: "E-Hive",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "195",
					},
				},
				{
					ID: "f8ae2d3f-cd93-47d3-bf4c-652464a871ba",
					Name: "Gremlins (Sprite)",
					Category: "Emergent",
					Type: "Device",
					Action: "Complex",
					Range: "",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "257",
					},
				},
				{
					ID: "b947d60a-8ac6-4185-8a5c-fc7a24ef69eb",
					Name: "Gremlins",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "195",
					},
				},
				{
					ID: "f66e1630-7b3a-4595-868a-9143b372e6f4",
					Name: "Holographic Concealment",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "195",
					},
				},
				{
					ID: "f861c488-9818-4a40-a985-0138d3f164d5",
					Name: "Resonance Feed",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "195",
					},
				},
				{
					ID: "cf509fe7-6b69-4996-8e79-8105e02c2855",
					Name: "Spraying",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "195",
					},
				},
				{
					ID: "f4026d71-afcb-430f-9336-56a280a77d36",
					Name: "Suppression",
					Category: "Emergent",
					Type: "Host",
					Action: "Complex",
					Range: "",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "257",
					},
				},
				{
					ID: "1629d45d-f64e-4a39-a2d4-a07f7844f1e4",
					Name: "Traceroute",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "195",
					},
				},
				{
					ID: "7a2a318f-4c30-46e0-9603-7b58dcb48150",
					Name: "Tunnel",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "195",
					},
				},
				{
					ID: "e08eeffc-6350-4e4d-9365-6f8530801d12",
					Name: "Venomous Code",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "195",
					},
				},
				{
					ID: "67e02cc6-5099-473d-b185-3cd357af3e6f",
					Name: "Allergy",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "401",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "f4de6eca-de5c-436b-955d-b322a9ce1a08",
					Name: "Dietary Requirement",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "401",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "f4865138-c3f0-46e8-8010-6003b1491b96",
					Name: "Essence Loss",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "401",
					},
				},
				{
					ID: "95dcc093-88b8-4182-b62a-575428b84c84",
					Name: "Evanescence",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "101",
					},
				},
				{
					ID: "031c2ae5-80d4-4cda-a2ce-65525970f281",
					Name: "Fragile",
					Category: "Weakness",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "192",
					},
					Rating: stringPtr("20"),
					Bonus: &common.BaseBonus{
						Conditionmonitor: &common.Conditionmonitor{},
					},
				},
				{
					ID: "e44f268f-de46-4a03-93e8-69570dd7a2eb",
					Name: "Reduced Senses",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "401",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "a38a6e6e-c8be-477b-91a9-f285ec1941fa",
					Name: "Uneducated",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "401",
					},
				},
				{
					ID: "cc5d600e-c1fd-47d2-affd-38a939cc21ab",
					Name: "Vulnerability",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "401",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "83289bc7-6c5d-4782-9523-bc8e08b0f521",
					Name: "Camouflage",
					Category: "Emergent",
					Type: "File",
					Action: "Complex",
					Range: "",
					Duration: "Permanent",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "256",
					},
				},
				{
					ID: "fc132915-118e-4fd2-a443-2f9799a83b4a",
					Name: "Cookie",
					Category: "Emergent",
					Type: "Persona",
					Action: "Complex",
					Range: "",
					Duration: "Predetermined by Sprite",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "256",
					},
				},
				{
					ID: "db290d50-c208-4de6-ad30-85b1b078370c",
					Name: "Electron Storm",
					Category: "Emergent",
					Type: "Persona",
					Action: "Complex",
					Range: "",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "257",
					},
				},
				{
					ID: "93507c52-d8fc-4b03-9e27-b24048d87526",
					Name: "Hash",
					Category: "Emergent",
					Type: "File",
					Action: "Special",
					Range: "",
					Duration: "F x 10 Combat Turns",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "257",
					},
				},
				{
					ID: "b733200f-9911-489d-b555-ebacd16110b0",
					Name: "Stability",
					Category: "Emergent",
					Type: "Persona or Device",
					Action: "Complex",
					Range: "",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "257",
					},
				},
				{
					ID: "c8840b92-07ae-40a3-bd04-20152bae16b8",
					Name: "Watermark",
					Category: "Emergent",
					Type: "Icon",
					Action: "Complex",
					Range: "",
					Duration: "Permanent",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "257",
					},
				},
				{
					ID: "a94dba2a-7699-4eb4-80a8-862f07beb6f6",
					Name: "Shift (Metahuman Form)",
					Category: "Shapeshifter",
					Type: "M",
					Action: "Complex",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "RF",
						Page: "123",
					},
					Required: &common.Required{},
				},
				{
					ID: "14d33e71-88c5-4fdb-8456-0b61ab70e8f4",
					Name: "Shift (Dracoform)",
					Category: "Drake",
					Type: "M",
					Action: "Complex",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "194",
					},
				},
				{
					ID: "2c0e624f-b1e7-4519-ab11-509406e53b19",
					Name: "Induced Dormancy",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "401",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "df67deb5-91e4-47bc-9af8-baf60fc2311d",
					Name: "Concealment (Self Only)",
					Category: "Paranormal",
					Type: "P",
					Action: "Simple",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
				},
				{
					ID: "d6729bdf-9300-40fe-97a8-9966d295af33",
					Name: "Armor",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "394",
					},
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
				},
				{
					ID: "28e8f9d8-6e2d-4bbe-bba3-e7195508a027",
					Name: "Hardened Mystic Armor",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "397",
					},
					Rating: stringPtr("True"),
				},
				{
					ID: "276b92d9-efcd-447d-a86d-8a141058615e",
					Name: "Vestigial Wings",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
				},
				{
					ID: "98928dbd-5b79-4dde-bc92-56dc317e293b",
					Name: "Underwater Adaptation",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Bonus: &common.BaseBonus{
						Specificskill: []common.Specificskill{
							// 1 items omitted
						},
					},
				},
				{
					ID: "64437e82-ac50-40f3-8916-751c124e5676",
					Name: "Alienate",
					Category: "Paranormal",
					Type: "P",
					Action: "None",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "188",
					},
				},
				{
					ID: "adf34ad4-0040-49df-a6dd-bde198c44a44",
					Name: "Astral Venom",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "188",
					},
				},
				{
					ID: "2cf990bd-f80b-4e56-803d-b8595ef96244",
					Name: "Brachiation",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "188",
					},
				},
				{
					ID: "6bd03b55-d6fb-4ecb-a098-1c01017bc81c",
					Name: "Create Alchera",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "189",
					},
				},
				{
					ID: "8af6b45a-ed52-4063-a60e-7428a818a7ab",
					Name: "Darkness",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "189",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "4b017336-7806-4905-a1ca-f540cf88b7b9",
					Name: "Deathlock",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "190",
					},
				},
				{
					ID: "d769a388-1f25-4ec0-9a7f-9bd37585723b",
					Name: "Dive Attack",
					Category: "Mundane",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "190",
					},
				},
				{
					ID: "faf2f307-c094-4139-ab88-e06f0804d282",
					Name: "Entropic Aura",
					Category: "Paranormal",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "190",
					},
				},
				{
					ID: "9c80e4ad-5999-4795-a890-0d6a1e5b542e",
					Name: "Extra Fragile",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "191",
					},
					Bonus: &common.BaseBonus{
						Conditionmonitor: &common.Conditionmonitor{},
					},
				},
				{
					ID: "ce067614-a47e-4536-a13d-09d02b918d3a",
					Name: "Flay Touch",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "191",
					},
				},
				{
					ID: "685c4e5c-d21a-4485-aa12-7deb3377d0c5",
					Name: "Ghost Chain",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Special",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "192",
					},
				},
				{
					ID: "fa15d90c-5e9d-4c3f-b92a-b9cd772091b6",
					Name: "Haunt",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Special",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "192",
					},
				},
				{
					ID: "9c04aead-af8d-4b17-a6b3-016c855db186",
					Name: "Innate Ritual",
					Category: "Paranormal",
					Type: "As ritual",
					Action: "As ritual",
					Range: "As ritual",
					Duration: "As ritual",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "193",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "5edec7e8-281d-46f8-bb06-c332e8b1ba59",
					Name: "Manipulate Magic",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Touch",
					Duration: "Permanent",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "193",
					},
				},
				{
					ID: "9c59fb9c-85b4-449a-978a-a07d6ccf31a2",
					Name: "Pounce",
					Category: "Mundane",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "193",
					},
				},
				{
					ID: "fc522b4a-e281-4de0-a824-b1d636fff59b",
					Name: "Toughness",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "194",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Conditionmonitor: &common.Conditionmonitor{},
					},
				},
				{
					ID: "6be87e77-1073-47fd-a137-b536a8700009",
					Name: "Domesticated",
					Category: "Mundane",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "186",
					},
				},
				{
					ID: "fbeb215d-fb20-4151-9fd1-4d3259db9402",
					Name: "Gliding",
					Category: "Mundane",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "186",
					},
					Bonus: &common.BaseBonus{
						Specificskill: []common.Specificskill{
							// 1 items omitted
						},
					},
				},
				{
					ID: "f5515a8b-4c5e-4917-881a-363777ba03e9",
					Name: "Critter Cyberpsychosis",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "186",
					},
				},
				{
					ID: "bfa9a7ec-f184-44cb-8599-96c5c7787595",
					Name: "CI3D (Critter Implant Induced Immune Deficiency)",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "186",
					},
				},
				{
					ID: "03c9acab-d172-4633-8dbf-23ec3b7faf7e",
					Name: "CTLE-X (Critter Temporal Lobe Epilepsy)",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "186",
					},
				},
				{
					ID: "f1a36576-1664-413b-a65f-e3b6115c266e",
					Name: "Precarious Physiology",
					Category: "Weakness",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "186",
					},
					Bonus: &common.BaseBonus{
						Cyberwaretotalessmultiplier: []string{
							// 1 items omitted
						},
						Disablebioware: []bool{
							// 1 items omitted
						},
					},
				},
				{
					ID: "31ad1e6d-3e95-42cc-af61-5b59c8e745e6",
					Name: "Dracoform Mastery",
					Category: "Drake",
					Type: "P",
					Action: "Special",
					Range: "Self",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "190",
					},
					Karma: stringPtr("50"),
				},
				{
					ID: "dafb81bd-7b92-487a-a739-465c69bcefcd",
					Name: "Adaptive Coloration",
					Category: "Drake",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "edd8b53d-ada6-4106-b8ef-111b5cb1fb40",
					Name: "Natural Weapon",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
				},
				{
					ID: "185aa4ff-7975-4d06-8fbc-52a07caeb9e2",
					Name: "Animal Control",
					Category: "Drake",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "79bb0c32-985c-47c8-a6ba-a9666884599f",
					Name: "Compulsion",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "afa7c218-9171-4354-b694-14b1cecd93ff",
					Name: "Corrosive Spit",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "4aef932e-2d0f-4226-b00e-19c5398641bd",
					Name: "Dragonspeech",
					Category: "Drake",
					Type: "M",
					Action: "Auto",
					Range: "LOS",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "dba6b163-0466-4fa1-998a-0a5ac74edba9",
					Name: "Enhanced Sense (Wide-Band Hearing)",
					Category: "Drake",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("3"),
				},
				{
					ID: "27488146-76d0-454c-b375-a63ccc492b70",
					Name: "Enhanced Sense (Low-Light Vision)",
					Category: "Drake",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("3"),
				},
				{
					ID: "0ed08f78-92bc-4cb3-94aa-10311b65edd4",
					Name: "Enhanced Sense (Smell)",
					Category: "Drake",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("3"),
				},
				{
					ID: "ba3c227f-5436-45a7-97b3-8a56e010902a",
					Name: "Enhanced Sense (Thermographic Vision)",
					Category: "Drake",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("3"),
				},
				{
					ID: "dd6b0eda-44a9-4411-b471-d78e76f495fb",
					Name: "Fear",
					Category: "Drake",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "eda3036b-441c-45bf-9e97-aac7cdd87054",
					Name: "Flight",
					Category: "Drake",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Bonus: &common.BaseBonus{
						Movementreplace: []common.Movementreplace{
							// 3 items omitted
						},
					},
					Forbidden: &common.Forbidden{},
					Required: &common.Required{},
					Karma: stringPtr("14"),
				},
				{
					ID: "1c2b88fd-d2bb-4a82-ad8f-a51164ad34c9",
					Name: "Additional Natural Weapon (Claws)",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("5"),
				},
				{
					ID: "b5dfe517-a722-4503-be5d-9fdd7a5653c4",
					Name: "Additional Natural Weapon (Fangs)",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("5"),
				},
				{
					ID: "82fea3f7-8e46-4a6a-a7fd-f5dc74046dac",
					Name: "Additional Natural Weapon (Tail)",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("5"),
				},
				{
					ID: "c8384789-1127-4846-bc28-3a6922b825a9",
					Name: "Additional Natural Weapon (Horns)",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "164",
					},
					Karma: stringPtr("5"),
				},
				{
					ID: "947047a8-632f-4d05-84a0-873e994be07c",
					Name: "Heavy Scales",
					Category: "Drake",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "165",
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "aebc05d5-43a8-4710-884e-feafa108d4c2",
					Name: "Improved Natural Armor",
					Category: "Drake",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "165",
					},
					Karma: stringPtr("16"),
				},
				{
					ID: "276c718b-7176-403a-9452-48e58b1f29e3",
					Name: "Magical Flight",
					Category: "Drake",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "165",
					},
					Bonus: &common.BaseBonus{
						Movementreplace: []common.Movementreplace{
							// 3 items omitted
						},
					},
					Required: &common.Required{},
					Karma: stringPtr("14"),
				},
				{
					ID: "dfb8200f-709c-4208-a72f-5a08de55de40",
					Name: "Influence",
					Category: "Drake",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "165",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "61a58161-f28d-49fb-b24d-e04588f6cdd5",
					Name: "Noxious Breath",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "165",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "a28ec7c9-809e-48cc-8c28-c90634754842",
					Name: "Resistance to Pathogens and Toxins",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "165",
					},
					Bonus: &common.BaseBonus{
						Pathogencontactresist: []string{
							// 1 items omitted
						},
						Pathogeningestionresist: []string{
							// 1 items omitted
						},
						Pathogeninhalationresist: []string{
							// 1 items omitted
						},
						Pathogeninjectionresist: []string{
							// 1 items omitted
						},
						Toxincontactresist: []string{
							// 1 items omitted
						},
						Toxiningestionresist: []string{
							// 1 items omitted
						},
						Toxininhalationresist: []string{
							// 1 items omitted
						},
						Toxininjectionresist: []string{
							// 1 items omitted
						},
					},
					Karma: stringPtr("8"),
				},
				{
					ID: "283f5a56-3d53-4155-8a85-63248e4d7cdc",
					Name: "Tail Stinger",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "165",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "5a08fa16-afcb-4fc9-b772-12a8f3dc96a8",
					Name: "Transcend Form",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "165",
					},
					Karma: stringPtr("25"),
				},
				{
					ID: "96eab5ca-4d3b-4b5a-a8dd-5430c0513d31",
					Name: "Venom",
					Category: "Drake",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "165",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "7a2d7ea2-7460-4d76-be08-dfbf5653ec7d",
					Name: "Resonance Hosting",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "168",
					},
				},
				{
					ID: "1dcf3b40-9846-44bf-93d5-f70fc47ea975",
					Name: "Astral Perception",
					Category: "Paranormal",
					Type: "",
					Action: "Simple",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "309",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					Bonus: &common.BaseBonus{
						Unlockskills: []common.Unlockskills{
							// 1 items omitted
						},
					},
					Karma: stringPtr(""),
				},
				{
					ID: "65dd2042-b786-471b-ac26-d6cc8cd16a58",
					Name: "Shift",
					Category: "Free Spirit",
					Type: "M",
					Action: "Complex",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "AET",
						Page: "38",
					},
					Karma: stringPtr(""),
				},
				{
					ID: "3243aece-a356-4e46-bd4c-af04cfc2a306",
					Name: "Skill",
					Category: "Free Spirit",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "AET",
						Page: "38",
					},
					Karma: stringPtr(""),
				},
				{
					ID: "5aa4a4c2-d27f-416a-976b-330bc878539c",
					Name: "Transfer Energy (Essence)",
					Category: "Free Spirit",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Permanent",
					SourceReference: common.SourceReference{
						Source: "AET",
						Page: "38",
					},
					Karma: stringPtr(""),
				},
				{
					ID: "1ad48bb5-2f28-4076-8f4b-185c02f85456",
					Name: "Vanishing",
					Category: "Free Spirit",
					Type: "M",
					Action: "Free",
					Range: "Self",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "AET",
						Page: "39",
					},
					Karma: stringPtr(""),
				},
				{
					ID: "a3651bf9-dda2-4bf0-8c95-8c44bd8ae83b",
					Name: "Korrigan Pact",
					Category: "Free Spirit",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "AET",
						Page: "39",
					},
					Karma: stringPtr(""),
				},
				{
					ID: "3fe334d3-f0e3-4bd7-ac39-57fa395ce0be",
					Name: "Animal Control (Insect Type)",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "394",
					},
					Toxic: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Selecttext: nil, // Omitted complex structure
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "4d923896-aabb-45fe-9708-85438a75c4a3",
					Name: "Compulsion",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "ed387fd9-5fa3-4f5d-9e97-a9a97ad17b94",
					Name: "Confusion",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "395",
					},
					Toxic: stringPtr("True"),
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "ac9855da-519a-44ac-b120-a605c20450e6",
					Name: "Enhanced Senses (Ultrasound)",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "396",
					},
					Toxic: stringPtr("True"),
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "fc4ca556-2d13-409b-824d-a4a8a16fc0ee",
					Name: "Fear",
					Category: "Paranormal",
					Type: "M",
					Action: "Complex",
					Range: "LOS",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "397",
					},
					Toxic: stringPtr("True"),
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "f986602a-464a-4c8b-aacc-508469401256",
					Name: "Search",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Special",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "400",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "6414b273-897d-451a-839a-4d530f1baaab",
					Name: "Anchored Resident",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "49",
					},
				},
				{
					ID: "9ae68e9e-65dc-49a0-bf06-72054396d371",
					Name: "Shell Game",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "49",
					},
				},
				{
					ID: "5fca2f99-9b2a-4fb0-b5b3-dd0626b8ed39",
					Name: "Superior Banishing Resistance",
					Category: "Paranormal",
					Type: "M",
					Action: "Simple",
					Range: "Self",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "50",
					},
				},
				{
					ID: "6d43c580-0285-4d93-bd43-b4edfa091c0e",
					Name: "Superior Regeneration",
					Category: "Paranormal",
					Type: "M",
					Action: "Simple",
					Range: "Self",
					Duration: "Permanent",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "49",
					},
				},
				{
					ID: "d0615070-d0c7-4c8b-ae02-442cadd1f38d",
					Name: "Wounded Fury",
					Category: "Paranormal",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "49",
					},
				},
				{
					ID: "9163fb4f-0531-4f11-8894-ed681306ebfd",
					Name: "Amphibious",
					Category: "Infected",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "156",
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "c330495b-c6af-4744-b399-c6e068864a8d",
					Name: "Astral Brute",
					Category: "Infected",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "157",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "c788063f-8daa-4e32-8017-9562513541a0",
					Name: "Bacchanal",
					Category: "Infected",
					Type: "P",
					Action: "Complex",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "157",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "f79f9ee8-f5db-4673-9225-e6a375aed465",
					Name: "Bone Spikes",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "157",
					},
					Bonus: &common.BaseBonus{
						Unarmeddv: []string{
							// 1 items omitted
						},
						Unarmeddvphysical: []bool{
							// 1 items omitted
						},
					},
					Required: &common.Required{},
					Karma: stringPtr("5"),
				},
				{
					ID: "363c3991-5d17-4ca7-963f-e3f2ef395fda",
					Name: "Calcified Hide",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "157",
					},
					Required: &common.Required{},
					Karma: stringPtr("5"),
				},
				{
					ID: "ea3a7442-477a-440f-adcd-4b5050c67b52",
					Name: "Corrosive Spit (Infected)",
					Category: "Infected",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "159",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "090c0194-3ac9-4ed8-8e82-7a60f18853e8",
					Name: "Deathlock Venom",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "159",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "6cbf07be-1491-46c1-ab67-d5f1dd4aa709",
					Name: "Digitigrade Legs",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "159",
					},
					Bonus: &common.BaseBonus{
						Movementreplace: []common.Movementreplace{
							// 1 items omitted
						},
						Sprintbonus: []common.Sprintbonus{
							// 1 items omitted
						},
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "00461512-b49c-4759-bc91-e41167682f22",
					Name: "Drag Down",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "159",
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "dc0d00da-1d10-42b2-a57a-c336da372df7",
					Name: "Dread Feast",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "159",
					},
					Required: &common.Required{},
					Karma: stringPtr("12"),
				},
				{
					ID: "9a4bde71-3d1b-4852-a613-5a7a8b1898ee",
					Name: "Dual Concealment",
					Category: "Infected",
					Type: "M",
					Action: "Simple",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "160",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "a9809219-9291-4efe-8f74-23a58e144d73",
					Name: "Evolved Reflexes",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "160",
					},
					Required: &common.Required{},
					Karma: stringPtr("12"),
				},
				{
					ID: "3f607df5-a2af-4fc7-b1ae-9ae2de40964f",
					Name: "Feral Dash",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "160",
					},
					Required: &common.Required{},
					Karma: stringPtr("5"),
				},
				{
					ID: "cd9ffa1a-d300-4650-8127-4f27fce3a14b",
					Name: "Gnashing Teeth",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "160",
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "4FEE3C62-36E4-41C5-AD87-28256AE53CFC",
					Name: "Immunity (Cold)",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "160",
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "53a990fc-ed69-44eb-98d5-5363bf9139f7",
					Name: "Metahuman Masque",
					Category: "Infected",
					Type: "M",
					Action: "Complex",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "160",
					},
					Required: &common.Required{},
					Karma: stringPtr("12"),
				},
				{
					ID: "67B58736-8BD3-4C88-9310-5051C8683966",
					Name: "Mimicry",
					Category: "Infected",
					Type: "P",
					Action: "Simple",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "398",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "09fb492d-0aa0-4a2e-8542-53e2cf97f432",
					Name: "Morningstar Fall",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "161",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "b1cef6fe-aa5f-4b12-a621-a3eb24568dbf",
					Name: "Mystic Armor (Infected)",
					Category: "Infected",
					Type: "M",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "161",
					},
					Rating: stringPtr("True"),
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "53dfd3bb-8c93-4d28-a88f-646c187f7940",
					Name: "Plague Bearer",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "161",
					},
					Required: &common.Required{},
					Karma: stringPtr("12"),
				},
				{
					ID: "CE10BCD4-EDEE-42F4-A5EE-06647D7A8492",
					Name: "Pounce (Infected)",
					Category: "Infected",
					Type: "P",
					Action: "Complex",
					Range: "Touch",
					Duration: "Instant",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "193",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "f61e6df3-bd1a-4ce8-9c75-b49df275cfb3",
					Name: "Predator's Glamour",
					Category: "Infected",
					Type: "M",
					Action: "Complex",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "161",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "3714CACF-7D91-4E38-8898-365A53E98108",
					Name: "Psychokinesis (Infected)",
					Category: "Paranormal",
					Type: "P",
					Action: "Complex",
					Range: "LOS",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "400",
					},
					Karma: stringPtr("9"),
				},
				{
					ID: "80d692d9-6f13-4148-b346-bb8fc7b78d34",
					Name: "Rat King",
					Category: "Infected",
					Type: "M",
					Action: "Auto",
					Range: "MAG x 25 m",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "162",
					},
					Required: &common.Required{},
					Karma: stringPtr("12"),
				},
				{
					ID: "0daa8f5c-f4de-4558-aca8-82354eecb941",
					Name: "Scythe Claws",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "162",
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "CA353685-D829-49F4-9023-1551398C31F6",
					Name: "Secretion/Substance Extrusion (Anti-Coagulant)",
					Category: "Mundane",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "193",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "CBE25F51-67D5-49EF-BC48-13CB376E6E39",
					Name: "Silence",
					Category: "Infected",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "SG",
						Page: "199",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "F713F6DD-C932-405A-9EA3-A410A1516A92",
					Name: "Tunneling Claws",
					Category: "Infected",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "96ce4db8-74c5-47ea-8305-1096858ba8ee",
					Name: "Sonic Shriek",
					Category: "Infected",
					Type: "P",
					Action: "Complex",
					Range: "Special",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "162",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "a2346acb-c604-4c9d-83b6-e374348f1749",
					Name: "Spines",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "162",
					},
					Required: &common.Required{},
					Karma: stringPtr("6"),
				},
				{
					ID: "9b2033d3-be97-440e-a5f4-f9d8a230c09c",
					Name: "Stupefying Miasma",
					Category: "Infected",
					Type: "P",
					Action: "Simple",
					Range: "Self",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "162",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "5589e7d4-0573-40c4-9798-eb6b604ef82c",
					Name: "Terrorscape",
					Category: "Infected",
					Type: "M",
					Action: "Complex",
					Range: "Special",
					Duration: "Sustained",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "162",
					},
					Required: &common.Required{},
					Karma: stringPtr("12"),
				},
				{
					ID: "97829992-2433-463d-8df7-d8ef0db20e00",
					Name: "Traceless Walk",
					Category: "Infected",
					Type: "P",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "DTR",
						Page: "163",
					},
					Required: &common.Required{},
					Karma: stringPtr("9"),
				},
				{
					ID: "765bf1cb-2e4b-46e8-aee4-f19004f031f3",
					Name: "Bodyguard",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "100",
					},
				},
				{
					ID: "d8e72e33-d70e-4fd5-8ca2-b6cb7da87a96",
					Name: "Shield",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "100",
					},
				},
				{
					ID: "3873ed1d-9f98-4a68-bccd-012d237a2522",
					Name: "Active Analytics",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "101",
					},
				},
				{
					ID: "5455b362-4c9d-4841-8069-230f44a4a3f0",
					Name: "Borrowed IP",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "101",
					},
				},
				{
					ID: "ad1c42e7-315b-4c6b-ae49-856b274a129b",
					Name: "Decompiling Resistance",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "101",
					},
				},
				{
					ID: "68bcb1c1-581c-4756-9856-690a5c3a5397",
					Name: "Enhance",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "101",
					},
				},
				{
					ID: "8e7e1bb4-ad16-4195-aef8-dd5b4c701603",
					Name: "Navi",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "101",
					},
				},
				{
					ID: "67ec3e9a-3e21-4906-9d90-1255f6086ce7",
					Name: "Resilient Code",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "101",
					},
				},
				{
					ID: "91a4d3a9-bf11-4080-94aa-37e462436b12",
					Name: "Resonance Spooling",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "101",
					},
				},
				{
					ID: "1749d122-8d63-4790-ba8b-974b500d5bab",
					Name: "Resonance Hosting",
					Category: "Emergent",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "KC",
						Page: "168",
					},
				},
				{
					ID: "227fa369-eaf5-400f-ab50-eb6e095684f7",
					Name: "All-Around Sight",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
				},
				{
					ID: "1aa8fb12-6f00-42df-96c9-3c5b60ddf9b3",
					Name: "Aquatic Adaptation",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Bonus: &common.BaseBonus{
						Specificskill: []common.Specificskill{
							// 1 items omitted
						},
					},
				},
				{
					ID: "24d6d5c2-8459-4f9e-8a76-dd9a07a49f9c",
					Name: "Attribute Enhancement (Body)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Specificattribute: []common.Specificattribute{
							// 1 items omitted
						},
					},
				},
				{
					ID: "78be96f2-43e5-444a-b255-0e7528813b4a",
					Name: "Attribute Enhancement (Agility)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Specificattribute: []common.Specificattribute{
							// 1 items omitted
						},
					},
				},
				{
					ID: "95240c3e-99c1-43d9-adf0-6a83b792091b",
					Name: "Attribute Enhancement (Reaction)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Specificattribute: []common.Specificattribute{
							// 1 items omitted
						},
					},
				},
				{
					ID: "26ad4ce7-439b-48d1-a870-bb1e2b2a54ad",
					Name: "Attribute Enhancement (Strength)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Specificattribute: []common.Specificattribute{
							// 1 items omitted
						},
					},
				},
				{
					ID: "81aab9fb-30ef-4c91-b296-b85dc2860fee",
					Name: "Attribute Enhancement (Charisma)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Specificattribute: []common.Specificattribute{
							// 1 items omitted
						},
					},
				},
				{
					ID: "cf88125a-c129-4e77-8813-cc4d2368e077",
					Name: "Attribute Enhancement (Intuition)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Specificattribute: []common.Specificattribute{
							// 1 items omitted
						},
					},
				},
				{
					ID: "7af7bc12-b671-4dbf-bfb7-fb58e9ee28a4",
					Name: "Attribute Enhancement (Logic)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Specificattribute: []common.Specificattribute{
							// 1 items omitted
						},
					},
				},
				{
					ID: "95307494-6a99-4b66-aaaf-a417fa607632",
					Name: "Attribute Enhancement (Willpower)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Specificattribute: []common.Specificattribute{
							// 1 items omitted
						},
					},
				},
				{
					ID: "9c315cb9-5962-44e6-ba2a-0be99cbd48ea",
					Name: "Balance Tail",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
					Bonus: &common.BaseBonus{
						Specificskill: []common.Specificskill{
							// 2 items omitted
						},
					},
				},
				{
					ID: "ef6fd1c5-3403-46eb-910a-5130e2c5bca9",
					Name: "Bioluminescence",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
				},
				{
					ID: "97dd1f9c-22fa-4b2c-b10c-626c7db026c2",
					Name: "Biotoxin Alteration (Anesthetic)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
				},
				{
					ID: "a429197f-d371-4190-b43b-53fda9d5764e",
					Name: "Biotoxin Alteration (Formic Acid)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
				},
				{
					ID: "73880be6-7395-4d27-8511-3d3722ab2865",
					Name: "Biotoxin Alteration (Hallucinogen)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
				},
				{
					ID: "f7cf732c-40f6-4f4f-8e5a-316cef4f5ac8",
					Name: "Biotoxin Alteration (Nauseating)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "170",
					},
				},
				{
					ID: "c74444bf-7707-4eb2-b076-ccb883bd2344",
					Name: "Camouflage",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "d0f88641-ff0f-448f-93d3-0d67068939c2",
					Name: "Celerity",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
					Bonus: &common.BaseBonus{
						Runmultiplier: []common.Runmultiplier{
							// 1 items omitted
						},
						Sprintbonus: []common.Sprintbonus{
							// 1 items omitted
						},
						Walkmultiplier: []common.Walkmultiplier{
							// 1 items omitted
						},
					},
				},
				{
					ID: "411964a6-09c3-40c1-be47-5a4627532071",
					Name: "Climate Adaptation",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "2d89a28c-d407-4a0e-a636-0a44359e523c",
					Name: "Defensive Secretion",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "c666f1f1-f157-4a95-a22d-10e962cfc90c",
					Name: "Dynamic Coloration",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "f53310ed-9c07-4813-910e-5384cfaeaa43",
					Name: "Echolocation",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "3d6429c4-fe8e-4d2b-ba47-2ac1fa0d65b0",
					Name: "Electrocytes",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "Touch",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "048c7ca6-d626-415e-baae-80246091b8e1",
					Name: "Enhanced Sense (Low-Light Vision)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "383f5fa7-b15c-4cc9-bac8-d125df72df19",
					Name: "Enhanced Sense (Thermographic Vision)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "691aa349-e936-4352-9901-f119d07893a5",
					Name: "Enhanced Sense (Scent)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "faa6681f-04e2-4065-82c5-bb90ad2d3b7c",
					Name: "Enhanced Sense (Broadened Auditory Spectrum)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "171",
					},
				},
				{
					ID: "be0645f8-7a50-416e-82cb-2ed73b86a78a",
					Name: "Extra Head",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
					Rating: stringPtr("2"),
					Bonus: &common.BaseBonus{
						Conditionmonitor: &common.Conditionmonitor{},
						Specificskill: []common.Specificskill{
							// 1 items omitted
						},
					},
				},
				{
					ID: "5a3ac03e-dd4a-441e-83b0-194af9f6e594",
					Name: "Frog Tongue",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "717db6d5-fb7c-405c-aa9c-ab4ad5388c19",
					Name: "Gills",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "dfc5c73c-fd31-476f-9d68-78ac9a9f57e3",
					Name: "Gliding",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
					Bonus: &common.BaseBonus{
						Specificskill: []common.Specificskill{
							// 1 items omitted
						},
					},
				},
				{
					ID: "c34c4c75-fdd2-4fa3-9e62-e37f2f57ea36",
					Name: "Ink Extrusion",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "30123d64-845f-4375-9b2a-87c9a3a44c74",
					Name: "Magnetoception",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "f91bb1fa-3bb6-448d-b7e4-98d4473d5a12",
					Name: "Natural Weapon (Bite)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "dd7e6d25-53f1-41bb-8626-ef7413e9c3b6",
					Name: "Natural Weapon (Claws)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "fb8f1a20-892b-4946-a4c8-5cc817e55167",
					Name: "Natural Weapon (Horns)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "6ff500ab-0691-4310-8e42-65623e289739",
					Name: "Natural Weapon (Tail)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "c004510b-b5a8-4a34-b442-7353ef4599b5",
					Name: "Natural Weapon (Tusk)",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "4f261e65-bd90-400c-92d7-97b1dd0135ca",
					Name: "Proboscis",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "c704a705-ac65-4659-b555-babdc1edc7af",
					Name: "Potent Venom",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "4eeb2045-6690-470a-8926-4626ba0317eb",
					Name: "Quills",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "172",
					},
				},
				{
					ID: "2689dca6-ad15-46df-a2b0-fa9cb342cff2",
					Name: "Scent Spray",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
				},
				{
					ID: "2e9dcaba-10e6-4ed1-b5b4-aba4a7a99a47",
					Name: "Skill Enhancement",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
					Bonus: &common.BaseBonus{
						Selectskill: &common.Selectskill{},
					},
				},
				{
					ID: "eba7c531-84ab-477a-86f1-69400f2deb22",
					Name: "Sturdiness",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
					Bonus: &common.BaseBonus{
						Physicallimit: []string{
							// 1 items omitted
						},
					},
				},
				{
					ID: "e2036d44-b991-4339-a1ae-108272d405db",
					Name: "Thermosense",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
				},
				{
					ID: "3d4dec14-3a44-41b6-9f78-1d6bd42e15fe",
					Name: "Thicker Hide",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
					Rating: stringPtr("True"),
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
				},
				{
					ID: "e0b4c953-efef-4162-bd92-4ee8988c6853",
					Name: "Venom",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
				},
				{
					ID: "0b2e5718-908e-4301-b185-71371d8bb184",
					Name: "Vestigial Wings",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
					Bonus: &common.BaseBonus{
						Specificskill: []common.Specificskill{
							// 1 items omitted
						},
					},
				},
				{
					ID: "221bd655-f6a4-4b41-9f53-c147fff93e40",
					Name: "Wall Climbing",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
				},
				{
					ID: "65f530b0-c124-483d-a18a-a1cf8cbebf9b",
					Name: "Web Extrusion",
					Category: "Chimeric Modification",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "173",
					},
				},
				{
					ID: "e16964a0-5a6e-47ef-8f04-d3ee81ceb411",
					Name: "Evasion",
					Category: "Paranormal",
					Type: "",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "FA",
						Page: "180",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					Rating: stringPtr("True"),
				},
				{
					ID: "fe3beeae-0b61-4fd1-9c6d-1b47c98ce20d",
					Name: "Maneuvering",
					Category: "Paranormal",
					Type: "",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "FA",
						Page: "180",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					Rating: stringPtr("True"),
				},
				{
					ID: "d3cbc66d-1586-4e86-ab0c-6287506dbd74",
					Name: "Stealth",
					Category: "Paranormal",
					Type: "",
					Action: "Auto",
					Range: "Self",
					Duration: "Always",
					SourceReference: common.SourceReference{
						Source: "FA",
						Page: "180",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
					Rating: stringPtr("True"),
				},
				{
					ID: "93484499-4977-45b7-a722-1b58157d7708",
					Name: "Fold Perception",
					Category: "Free Spirit",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "120",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
				},
				{
					ID: "6c915799-73ba-470a-b333-b8808127415e",
					Name: "Agonizing Pain",
					Category: "Free Spirit",
					Type: "",
					Action: "",
					Range: "",
					Duration: "",
					SourceReference: common.SourceReference{
						Source: "HS",
						Page: "132",
					},
					Visibility: common.Visibility{
						Hide: stringPtr(""),
					},
				},
			},
		},
	},
}

// GetCritterPowersData returns the loaded critter powers data.
func GetCritterPowersData() *CritterPowersChummer {
	return critterPowersData
}

// GetAllCritterPowers returns all critter powers.
func GetAllCritterPowers() []CritterPowerItem {
	if len(critterPowersData.Powers) == 0 {
		return []CritterPowerItem{}
	}
	return critterPowersData.Powers[0].Power
}

// GetCritterPowerByID returns the critter power with the given ID, or nil if not found.
func GetCritterPowerByID(id string) *CritterPowerItem {
	powers := GetAllCritterPowers()
	for i := range powers {
		if powers[i].ID == id {
			return &powers[i]
		}
	}
	return nil
}
