package v5

import "shadowmaster/pkg/shadowrun/edition/v5/common"

// Code generated from vessels.xml. DO NOT EDIT.

var vesselsData = &VesselsChummer{
	Categories: []VesselCategories{
		{
			Category: []common.CategoryBase{
				{
					Content: "Inanimate Vessels",
				},
			},
		},
	},
	Metatypes: []VesselMetatypes{
		{
			Metatype: []VesselMetatype{
				{
					ID: "3E980802-7A90-49D2-B878-12983BB4B62F",
					Name: "Fragile Material",
					Category: stringPtr("Inanimate Vessels"),
					BP: stringPtr("0"),
					BodMin: "1",
					BodMax: "1",
					BodAug: "1",
					AgiMin: "0",
					AgiMax: "0",
					AgiAug: "0",
					ReaMin: "0",
					ReaMax: "0",
					ReaAug: "0",
					StrMin: "0",
					StrMax: "0",
					StrAug: "0",
					ChaMin: "0",
					ChaMax: "0",
					ChaAug: "0",
					IntMin: "0",
					IntMax: "0",
					IntAug: "0",
					LogMin: "0",
					LogMax: "0",
					LogAug: "0",
					WilMin: "0",
					WilMax: "0",
					WilAug: "0",
					IniMin: "0",
					IniMax: "0",
					IniAug: "0",
					EdgMin: "0",
					EdgMax: "0",
					EdgAug: "0",
					MagMin: "0",
					MagMax: "0",
					MagAug: "0",
					ResMin: "0",
					ResMax: "0",
					ResAug: "0",
					EssMin: "0",
					EssMax: "0",
					EssAug: "0",
					Movement: "",
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "298",
					},
				},
				{
					ID: "712889BF-CD58-425C-8D14-0E9720B2C713",
					Name: "Cheap Material",
					Category: stringPtr("Inanimate Vessels"),
					BP: stringPtr("0"),
					BodMin: "2",
					BodMax: "2",
					BodAug: "2",
					AgiMin: "0",
					AgiMax: "0",
					AgiAug: "0",
					ReaMin: "0",
					ReaMax: "0",
					ReaAug: "0",
					StrMin: "0",
					StrMax: "0",
					StrAug: "0",
					ChaMin: "0",
					ChaMax: "0",
					ChaAug: "0",
					IntMin: "0",
					IntMax: "0",
					IntAug: "0",
					LogMin: "0",
					LogMax: "0",
					LogAug: "0",
					WilMin: "0",
					WilMax: "0",
					WilAug: "0",
					IniMin: "0",
					IniMax: "0",
					IniAug: "0",
					EdgMin: "0",
					EdgMax: "0",
					EdgAug: "0",
					MagMin: "0",
					MagMax: "0",
					MagAug: "0",
					ResMin: "0",
					ResMax: "0",
					ResAug: "0",
					EssMin: "0",
					EssMax: "0",
					EssAug: "0",
					Movement: "",
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "298",
					},
				},
				{
					ID: "AF455A22-2B54-469A-9A08-A029473282B3",
					Name: "Average Material",
					Category: stringPtr("Inanimate Vessels"),
					BP: stringPtr("0"),
					BodMin: "4",
					BodMax: "4",
					BodAug: "4",
					AgiMin: "0",
					AgiMax: "0",
					AgiAug: "0",
					ReaMin: "0",
					ReaMax: "0",
					ReaAug: "0",
					StrMin: "0",
					StrMax: "0",
					StrAug: "0",
					ChaMin: "0",
					ChaMax: "0",
					ChaAug: "0",
					IntMin: "0",
					IntMax: "0",
					IntAug: "0",
					LogMin: "0",
					LogMax: "0",
					LogAug: "0",
					WilMin: "0",
					WilMax: "0",
					WilAug: "0",
					IniMin: "0",
					IniMax: "0",
					IniAug: "0",
					EdgMin: "0",
					EdgMax: "0",
					EdgAug: "0",
					MagMin: "0",
					MagMax: "0",
					MagAug: "0",
					ResMin: "0",
					ResMax: "0",
					ResAug: "0",
					EssMin: "0",
					EssMax: "0",
					EssAug: "0",
					Movement: "",
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "298",
					},
				},
				{
					ID: "E1556535-CC23-401A-9635-01AC2D640BEC",
					Name: "Heavy Material",
					Category: stringPtr("Inanimate Vessels"),
					BP: stringPtr("0"),
					BodMin: "6",
					BodMax: "6",
					BodAug: "6",
					AgiMin: "0",
					AgiMax: "0",
					AgiAug: "0",
					ReaMin: "0",
					ReaMax: "0",
					ReaAug: "0",
					StrMin: "0",
					StrMax: "0",
					StrAug: "0",
					ChaMin: "0",
					ChaMax: "0",
					ChaAug: "0",
					IntMin: "0",
					IntMax: "0",
					IntAug: "0",
					LogMin: "0",
					LogMax: "0",
					LogAug: "0",
					WilMin: "0",
					WilMax: "0",
					WilAug: "0",
					IniMin: "0",
					IniMax: "0",
					IniAug: "0",
					EdgMin: "0",
					EdgMax: "0",
					EdgAug: "0",
					MagMin: "0",
					MagMax: "0",
					MagAug: "0",
					ResMin: "0",
					ResMax: "0",
					ResAug: "0",
					EssMin: "0",
					EssMax: "0",
					EssAug: "0",
					Movement: "",
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "298",
					},
				},
				{
					ID: "2CC51D65-54DA-4FDA-AEF5-B641D4C9ED5F",
					Name: "Reinforced Material",
					Category: stringPtr("Inanimate Vessels"),
					BP: stringPtr("0"),
					BodMin: "8",
					BodMax: "8",
					BodAug: "8",
					AgiMin: "0",
					AgiMax: "0",
					AgiAug: "0",
					ReaMin: "0",
					ReaMax: "0",
					ReaAug: "0",
					StrMin: "0",
					StrMax: "0",
					StrAug: "0",
					ChaMin: "0",
					ChaMax: "0",
					ChaAug: "0",
					IntMin: "0",
					IntMax: "0",
					IntAug: "0",
					LogMin: "0",
					LogMax: "0",
					LogAug: "0",
					WilMin: "0",
					WilMax: "0",
					WilAug: "0",
					IniMin: "0",
					IniMax: "0",
					IniAug: "0",
					EdgMin: "0",
					EdgMax: "0",
					EdgAug: "0",
					MagMin: "0",
					MagMax: "0",
					MagAug: "0",
					ResMin: "0",
					ResMax: "0",
					ResAug: "0",
					EssMin: "0",
					EssMax: "0",
					EssAug: "0",
					Movement: "",
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "298",
					},
				},
				{
					ID: "39B667F0-48AB-41D6-8FB9-54F3B34D42AC",
					Name: "Structural Material",
					Category: stringPtr("Inanimate Vessels"),
					BP: stringPtr("0"),
					BodMin: "10",
					BodMax: "10",
					BodAug: "10",
					AgiMin: "0",
					AgiMax: "0",
					AgiAug: "0",
					ReaMin: "0",
					ReaMax: "0",
					ReaAug: "0",
					StrMin: "0",
					StrMax: "0",
					StrAug: "0",
					ChaMin: "0",
					ChaMax: "0",
					ChaAug: "0",
					IntMin: "0",
					IntMax: "0",
					IntAug: "0",
					LogMin: "0",
					LogMax: "0",
					LogAug: "0",
					WilMin: "0",
					WilMax: "0",
					WilAug: "0",
					IniMin: "0",
					IniMax: "0",
					IniAug: "0",
					EdgMin: "0",
					EdgMax: "0",
					EdgAug: "0",
					MagMin: "0",
					MagMax: "0",
					MagAug: "0",
					ResMin: "0",
					ResMax: "0",
					ResAug: "0",
					EssMin: "0",
					EssMax: "0",
					EssAug: "0",
					Movement: "",
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "298",
					},
				},
				{
					ID: "2ACF277D-76BF-45B7-BC85-FD084D1D7027",
					Name: "Heavy Structural Material",
					Category: stringPtr("Inanimate Vessels"),
					BP: stringPtr("0"),
					BodMin: "12",
					BodMax: "12",
					BodAug: "12",
					AgiMin: "0",
					AgiMax: "0",
					AgiAug: "0",
					ReaMin: "0",
					ReaMax: "0",
					ReaAug: "0",
					StrMin: "0",
					StrMax: "0",
					StrAug: "0",
					ChaMin: "0",
					ChaMax: "0",
					ChaAug: "0",
					IntMin: "0",
					IntMax: "0",
					IntAug: "0",
					LogMin: "0",
					LogMax: "0",
					LogAug: "0",
					WilMin: "0",
					WilMax: "0",
					WilAug: "0",
					IniMin: "0",
					IniMax: "0",
					IniAug: "0",
					EdgMin: "0",
					EdgMax: "0",
					EdgAug: "0",
					MagMin: "0",
					MagMax: "0",
					MagAug: "0",
					ResMin: "0",
					ResMax: "0",
					ResAug: "0",
					EssMin: "0",
					EssMax: "0",
					EssAug: "0",
					Movement: "",
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "298",
					},
				},
				{
					ID: "6B7BDAA6-99A5-4FB2-9648-E1E0E9568E30",
					Name: "Armored/Reinforced Material",
					Category: stringPtr("Inanimate Vessels"),
					BP: stringPtr("0"),
					BodMin: "14",
					BodMax: "14",
					BodAug: "14",
					AgiMin: "0",
					AgiMax: "0",
					AgiAug: "0",
					ReaMin: "0",
					ReaMax: "0",
					ReaAug: "0",
					StrMin: "0",
					StrMax: "0",
					StrAug: "0",
					ChaMin: "0",
					ChaMax: "0",
					ChaAug: "0",
					IntMin: "0",
					IntMax: "0",
					IntAug: "0",
					LogMin: "0",
					LogMax: "0",
					LogAug: "0",
					WilMin: "0",
					WilMax: "0",
					WilAug: "0",
					IniMin: "0",
					IniMax: "0",
					IniAug: "0",
					EdgMin: "0",
					EdgMax: "0",
					EdgAug: "0",
					MagMin: "0",
					MagMax: "0",
					MagAug: "0",
					ResMin: "0",
					ResMax: "0",
					ResAug: "0",
					EssMin: "0",
					EssMax: "0",
					EssAug: "0",
					Movement: "",
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "298",
					},
				},
				{
					ID: "2643B4A2-05C6-47FF-8E15-FC094415FE44",
					Name: "Hardened Material",
					Category: stringPtr("Inanimate Vessels"),
					BP: stringPtr("0"),
					BodMin: "16",
					BodMax: "16",
					BodAug: "16",
					AgiMin: "0",
					AgiMax: "0",
					AgiAug: "0",
					ReaMin: "0",
					ReaMax: "0",
					ReaAug: "0",
					StrMin: "0",
					StrMax: "0",
					StrAug: "0",
					ChaMin: "0",
					ChaMax: "0",
					ChaAug: "0",
					IntMin: "0",
					IntMax: "0",
					IntAug: "0",
					LogMin: "0",
					LogMax: "0",
					LogAug: "0",
					WilMin: "0",
					WilMax: "0",
					WilAug: "0",
					IniMin: "0",
					IniMax: "0",
					IniAug: "0",
					EdgMin: "0",
					EdgMax: "0",
					EdgAug: "0",
					MagMin: "0",
					MagMax: "0",
					MagAug: "0",
					ResMin: "0",
					ResMax: "0",
					ResAug: "0",
					EssMin: "0",
					EssMax: "0",
					EssAug: "0",
					Movement: "",
					Bonus: &common.BaseBonus{
						Armor: &common.Armor{},
					},
					SourceReference: common.SourceReference{
						Source: "SR5",
						Page: "298",
					},
				},
			},
		},
	},
}

// GetVesselsData returns the loaded vessels data.
func GetVesselsData() *VesselsChummer {
	return vesselsData
}

// GetAllVesselMetatypes returns all vessel metatypes.
func GetAllVesselMetatypes() []VesselMetatype {
	if len(vesselsData.Metatypes) == 0 {
		return []VesselMetatype{}
	}
	return vesselsData.Metatypes[0].Metatype
}

// GetVesselMetatypeByID returns the vessel metatype with the given ID, or nil if not found.
func GetVesselMetatypeByID(id string) *VesselMetatype {
	metatypes := GetAllVesselMetatypes()
	for i := range metatypes {
		if metatypes[i].ID == id {
			return &metatypes[i]
		}
	}
	return nil
}
