#!/usr/bin/env python3
"""Generate weapons.go from weapons.xsd"""

import xml.etree.ElementTree as ET
import re
import os

NS = {'xs': 'http://www.w3.org/2001/XMLSchema'}

def generate_weapons():
    """Generate weapons.go from weapons.xsd"""
    
    tree = ET.parse('data/chummerxml/weapons.xsd')
    root = tree.getroot()
    
    os.makedirs('pkg/shadowrun/edition/v5', exist_ok=True)
    
    # Generate the Go code
    with open('pkg/shadowrun/edition/v5/weapons.go', 'w', encoding='utf-8') as f:
        f.write('package v5\n\n')
        f.write('import "shadowmaster/pkg/shadowrun/edition/v5/common"\n\n')
        f.write('// This file contains weapon structures generated from weapons.xsd\n\n')
        
        # Generate WeaponCategory struct
        f.write('// WeaponCategory represents a weapon category\n')
        f.write('type WeaponCategory struct {\n')
        f.write('\tContent string `xml:",chardata" json:"+content,omitempty"`\n')
        f.write('\tBlackmarket *string `xml:"blackmarket,attr,omitempty" json:"+@blackmarket,omitempty"`\n')
        f.write('\tGunneryspec *string `xml:"gunneryspec,attr,omitempty" json:"+@gunneryspec,omitempty"`\n')
        f.write('\tType *string `xml:"type,attr,omitempty" json:"+@type,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponCategories struct
        f.write('// WeaponCategories represents a collection of weapon categories\n')
        f.write('type WeaponCategories struct {\n')
        f.write('\tCategory []WeaponCategory `xml:"category,omitempty" json:"category,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponUseGearName struct (for usegear within weapon accessories)
        f.write('// WeaponUseGearName represents a usegear name\n')
        f.write('type WeaponUseGearName struct {\n')
        f.write('\tContent string `xml:",chardata" json:"+content,omitempty"`\n')
        f.write('\tSelect *string `xml:"select,attr,omitempty" json:"+@select,omitempty"`\n')
        f.write('\tCreateChildren *string `xml:"createchildren,attr,omitempty" json:"+@createchildren,omitempty"`\n')
        f.write('\tAddImprovements *string `xml:"addimprovements,attr,omitempty" json:"+@addimprovements,omitempty"`\n')
        f.write('\tQty *string `xml:"qty,attr,omitempty" json:"+@qty,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponGears struct (recursive - for weapons.xsd gears element)
        f.write('// WeaponGears represents a gears container for weapons (recursive)\n')
        f.write('type WeaponGears struct {\n')
        f.write('\tUseGear []WeaponUseGear `xml:"usegear,omitempty" json:"usegear,omitempty"`\n')
        f.write('\tStartCollapsed *string `xml:"startcollapsed,attr,omitempty" json:"+@startcollapsed,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponUseGear struct
        f.write('// WeaponUseGear represents a usegear element for weapons\n')
        f.write('type WeaponUseGear struct {\n')
        f.write('\tName WeaponUseGearName `xml:"name" json:"name"`\n')
        f.write('\tCategory string `xml:"category" json:"category"`\n')
        f.write('\tRating *int `xml:"rating,omitempty" json:"rating,omitempty"`\n')
        f.write('\tCapacity *int `xml:"capacity,omitempty" json:"capacity,omitempty"`\n')
        f.write('\tPage *int `xml:"page,omitempty" json:"page,omitempty"`\n')
        f.write('\tSource *int `xml:"source,omitempty" json:"source,omitempty"`\n')
        f.write('\tGears *WeaponGears `xml:"gears,omitempty" json:"gears,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponAccessory struct (for accessories within weapon)
        f.write('// WeaponAccessory represents a weapon accessory\n')
        f.write('type WeaponAccessory struct {\n')
        f.write('\tName []string `xml:"name" json:"name"`\n')
        f.write('\tMount []string `xml:"mount,omitempty" json:"mount,omitempty"`\n')
        f.write('\tRating []string `xml:"rating,omitempty" json:"rating,omitempty"`\n')
        f.write('\tGears *WeaponGears `xml:"gears,omitempty" json:"gears,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponAccessories struct
        f.write('// WeaponAccessories represents a collection of weapon accessories\n')
        f.write('type WeaponAccessories struct {\n')
        f.write('\tAccessory []WeaponAccessory `xml:"accessory" json:"accessory"`\n')
        f.write('}\n\n')
        
        # Generate AccessoryMounts struct
        f.write('// AccessoryMounts represents accessory mounts\n')
        f.write('type AccessoryMounts struct {\n')
        f.write('\tMount []string `xml:"mount" json:"mount"`\n')
        f.write('}\n\n')
        
        # Generate AllowGear struct
        f.write('// AllowGear represents allowed gear categories\n')
        f.write('type AllowGear struct {\n')
        f.write('\tGearCategory []string `xml:"gearcategory,omitempty" json:"gearcategory,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate AlternateRange struct
        f.write('// AlternateRange represents an alternate range\n')
        f.write('type AlternateRange struct {\n')
        f.write('\tContent string `xml:",chardata" json:"+content,omitempty"`\n')
        f.write('\tMultiply *string `xml:"multiply,attr,omitempty" json:"+@multiply,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate DoubledCostAccessoryMounts struct
        f.write('// DoubledCostAccessoryMounts represents doubled cost accessory mounts\n')
        f.write('type DoubledCostAccessoryMounts struct {\n')
        f.write('\tMount []string `xml:"mount" json:"mount"`\n')
        f.write('}\n\n')
        
        # Generate WeaponMod struct (for mods within weapon)
        f.write('// WeaponMod represents a weapon mod\n')
        f.write('type WeaponMod struct {\n')
        f.write('\tContent string `xml:",chardata" json:"+content,omitempty"`\n')
        f.write('\tRating *string `xml:"rating,attr,omitempty" json:"+@rating,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponMods struct (for mods within weapon)
        f.write('// WeaponMods represents a collection of weapon mods\n')
        f.write('type WeaponMods struct {\n')
        f.write('\tMod []WeaponMod `xml:"mod" json:"mod"`\n')
        f.write('}\n\n')
        
        # Generate WeaponRange struct
        f.write('// WeaponRange represents a weapon range\n')
        f.write('type WeaponRange struct {\n')
        f.write('\tContent string `xml:",chardata" json:"+content,omitempty"`\n')
        f.write('\tMultiply *string `xml:"multiply,attr,omitempty" json:"+@multiply,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate Underbarrels struct
        f.write('// Underbarrels represents underbarrel weapons\n')
        f.write('type Underbarrels struct {\n')
        f.write('\tUnderbarrel []string `xml:"underbarrel" json:"underbarrel"`\n')
        f.write('}\n\n')
        
        # Generate WirelessWeaponBonus struct
        f.write('// WirelessWeaponBonus represents wireless weapon bonuses\n')
        f.write('type WirelessWeaponBonus struct {\n')
        f.write('\tAccuracy *string `xml:"accuracy,omitempty" json:"accuracy,omitempty"`\n')
        f.write('\tAccuracyReplace *string `xml:"accuracyreplace,omitempty" json:"accuracyreplace,omitempty"`\n')
        f.write('\tAP *string `xml:"ap,omitempty" json:"ap,omitempty"`\n')
        f.write('\tAPReplace *string `xml:"apreplace,omitempty" json:"apreplace,omitempty"`\n')
        f.write('\tDamage *string `xml:"damage,omitempty" json:"damage,omitempty"`\n')
        f.write('\tDamageReplace *string `xml:"damagereplace,omitempty" json:"damagereplace,omitempty"`\n')
        f.write('\tDamageType *string `xml:"damagetype,omitempty" json:"damagetype,omitempty"`\n')
        f.write('\tMode *string `xml:"mode,omitempty" json:"mode,omitempty"`\n')
        f.write('\tModeReplace *string `xml:"modereplace,omitempty" json:"modereplace,omitempty"`\n')
        f.write('\tPool *string `xml:"pool,omitempty" json:"pool,omitempty"`\n')
        f.write('\tRangeBonus *int `xml:"rangebonus,omitempty" json:"rangebonus,omitempty"`\n')
        f.write('\tRC *string `xml:"rc,omitempty" json:"rc,omitempty"`\n')
        f.write('\tSmartlinkPool *string `xml:"smartlinkpool,omitempty" json:"smartlinkpool,omitempty"`\n')
        f.write('\tUseRange *string `xml:"userange,omitempty" json:"userange,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate Weapon struct (main element)
        f.write('// Weapon represents a weapon definition\n')
        f.write('type Weapon struct {\n')
        f.write('\tID string `xml:"id" json:"id"`\n')
        f.write('\tName string `xml:"name" json:"name"`\n')
        f.write('\tCategory string `xml:"category" json:"category"`\n')
        f.write('\tType string `xml:"type" json:"type"`\n')
        f.write('\tConceal int `xml:"conceal" json:"conceal"`\n')
        f.write('\tAccuracy string `xml:"accuracy" json:"accuracy"`\n')
        f.write('\tReach string `xml:"reach" json:"reach"`\n')
        f.write('\tDamage string `xml:"damage" json:"damage"`\n')
        f.write('\tAP string `xml:"ap" json:"ap"`\n')
        f.write('\tMode string `xml:"mode" json:"mode"`\n')
        f.write('\tRC string `xml:"rc" json:"rc"`\n')
        f.write('\tAmmo string `xml:"ammo" json:"ammo"`\n')
        f.write('\tAvail string `xml:"avail" json:"avail"`\n')
        f.write('\tCost string `xml:"cost" json:"cost"`\n')
        f.write('\tcommon.SourceReference\n')
        f.write('\tAccessories *WeaponAccessories `xml:"accessories,omitempty" json:"accessories,omitempty"`\n')
        f.write('\tAccessoryMounts *AccessoryMounts `xml:"accessorymounts,omitempty" json:"accessorymounts,omitempty"`\n')
        f.write('\tAddWeapon []string `xml:"addweapon,omitempty" json:"addweapon,omitempty"`\n')
        f.write('\tAllowAccessory *string `xml:"allowaccessory,omitempty" json:"allowaccessory,omitempty"`\n')
        f.write('\tAllowGear *AllowGear `xml:"allowgear,omitempty" json:"allowgear,omitempty"`\n')
        f.write('\tAllowMod *string `xml:"allowmod,omitempty" json:"allowmod,omitempty"`\n')
        f.write('\tAllowFullBurst *string `xml:"allowfullburst,omitempty" json:"allowfullburst,omitempty"`\n')
        f.write('\tAllowLongBurst *string `xml:"allowlongburst,omitempty" json:"allowlongburst,omitempty"`\n')
        f.write('\tAllowShortBurst *string `xml:"allowshortburst,omitempty" json:"allowshortburst,omitempty"`\n')
        f.write('\tAllowSingleShot *string `xml:"allowsingleshot,omitempty" json:"allowsingleshot,omitempty"`\n')
        f.write('\tAllowSuppressive *string `xml:"allowsuppressive,omitempty" json:"allowsuppressive,omitempty"`\n')
        f.write('\tAlternateRange []AlternateRange `xml:"alternaterange,omitempty" json:"alternaterange,omitempty"`\n')
        f.write('\tAmmoCategory *string `xml:"ammocategory,omitempty" json:"ammocategory,omitempty"`\n')
        f.write('\tAmmoSlots *int `xml:"ammoslots,omitempty" json:"ammoslots,omitempty"`\n')
        f.write('\tCyberware *string `xml:"cyberware,omitempty" json:"cyberware,omitempty"`\n')
        f.write('\tDoubledCostAccessoryMounts *DoubledCostAccessoryMounts `xml:"doubledcostaccessorymounts,omitempty" json:"doubledcostaccessorymounts,omitempty"`\n')
        f.write('\tExtraMount *string `xml:"extramount,omitempty" json:"extramount,omitempty"`\n')
        f.write('\tForbidden *common.Forbidden `xml:"forbidden,omitempty" json:"forbidden,omitempty"`\n')
        f.write('\tFullBurst *int `xml:"fullburst,omitempty" json:"fullburst,omitempty"`\n')
        f.write('\tcommon.Visibility\n')
        f.write('\tLongBurst *int `xml:"longburst,omitempty" json:"longburst,omitempty"`\n')
        f.write('\tMods *WeaponMods `xml:"mods,omitempty" json:"mods,omitempty"`\n')
        f.write('\tMount *string `xml:"mount,omitempty" json:"mount,omitempty"`\n')
        f.write('\tRange []WeaponRange `xml:"range,omitempty" json:"range,omitempty"`\n')
        f.write('\tRequireAmmo *string `xml:"requireammo,omitempty" json:"requireammo,omitempty"`\n')
        f.write('\tRequired *common.Required `xml:"required,omitempty" json:"required,omitempty"`\n')
        f.write('\tSingleShot *int `xml:"singleshot,omitempty" json:"singleshot,omitempty"`\n')
        f.write('\tSizeCategory *string `xml:"sizecategory,omitempty" json:"sizecategory,omitempty"`\n')
        f.write('\tShortBurst *int `xml:"shortburst,omitempty" json:"shortburst,omitempty"`\n')
        f.write('\tSpec *string `xml:"spec,omitempty" json:"spec,omitempty"`\n')
        f.write('\tSpec2 *string `xml:"spec2,omitempty" json:"spec2,omitempty"`\n')
        f.write('\tSuppressive *int `xml:"suppressive,omitempty" json:"suppressive,omitempty"`\n')
        f.write('\tUnderbarrels *Underbarrels `xml:"underbarrels,omitempty" json:"underbarrels,omitempty"`\n')
        f.write('\tUseSkill *string `xml:"useskill,omitempty" json:"useskill,omitempty"`\n')
        f.write('\tUseSkillSpec *string `xml:"useskillspec,omitempty" json:"useskillspec,omitempty"`\n')
        f.write('\tWeaponType *string `xml:"weapontype,omitempty" json:"weapontype,omitempty"`\n')
        f.write('\tWirelessWeaponBonus *WirelessWeaponBonus `xml:"wirelessweaponbonus,omitempty" json:"wirelessweaponbonus,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate Weapons struct (container)
        f.write('// Weapons represents a collection of weapons\n')
        f.write('type Weapons struct {\n')
        f.write('\tWeapon []Weapon `xml:"weapon,omitempty" json:"weapon,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponAccessoryItem struct (standalone accessory)
        f.write('// WeaponAccessoryItem represents a standalone weapon accessory\n')
        f.write('type WeaponAccessoryItem struct {\n')
        f.write('\tID string `xml:"id" json:"id"`\n')
        f.write('\tName string `xml:"name" json:"name"`\n')
        f.write('\tMount string `xml:"mount" json:"mount"`\n')
        f.write('\tExtraMount *string `xml:"extramount,omitempty" json:"extramount,omitempty"`\n')
        f.write('\tAddMount *string `xml:"addmount,omitempty" json:"addmount,omitempty"`\n')
        f.write('\tAvail string `xml:"avail" json:"avail"`\n')
        f.write('\tCost string `xml:"cost" json:"cost"`\n')
        f.write('\tcommon.SourceReference\n')
        f.write('\tAccessoryCostMultiplier *string `xml:"accessorycostmultiplier,omitempty" json:"accessorycostmultiplier,omitempty"`\n')
        f.write('\tAccuracy *string `xml:"accuracy,omitempty" json:"accuracy,omitempty"`\n')
        f.write('\tAddUnderbarrels *AddUnderbarrels `xml:"addunderbarrels,omitempty" json:"addunderbarrels,omitempty"`\n')
        f.write('\tAllowGear *AllowGear `xml:"allowgear,omitempty" json:"allowgear,omitempty"`\n')
        f.write('\tAmmoBonus *string `xml:"ammobonus,omitempty" json:"ammobonus,omitempty"`\n')
        f.write('\tAmmoReplace *string `xml:"ammoreplace,omitempty" json:"ammoreplace,omitempty"`\n')
        f.write('\tAmmoSlots *string `xml:"ammoslots,omitempty" json:"ammoslots,omitempty"`\n')
        f.write('\tConceal *string `xml:"conceal,omitempty" json:"conceal,omitempty"`\n')
        f.write('\tDamage *string `xml:"damage,omitempty" json:"damage,omitempty"`\n')
        f.write('\tDamageType *string `xml:"damagetype,omitempty" json:"damagetype,omitempty"`\n')
        f.write('\tDicePool *int `xml:"dicepool,omitempty" json:"dicepool,omitempty"`\n')
        f.write('\tForbidden *common.Forbidden `xml:"forbidden,omitempty" json:"forbidden,omitempty"`\n')
        f.write('\tGears *WeaponGears `xml:"gears,omitempty" json:"gears,omitempty"`\n')
        f.write('\tcommon.Visibility\n')
        f.write('\tModifyAmmoCapacity *string `xml:"modifyammocapacity,omitempty" json:"modifyammocapacity,omitempty"`\n')
        f.write('\tRating *string `xml:"rating,omitempty" json:"rating,omitempty"`\n')
        f.write('\tRC *string `xml:"rc,omitempty" json:"rc,omitempty"`\n')
        f.write('\tRCDeployable *string `xml:"rcdeployable,omitempty" json:"rcdeployable,omitempty"`\n')
        f.write('\tRCGroup *int `xml:"rcgroup,omitempty" json:"rcgroup,omitempty"`\n')
        f.write('\tReplaceRange *string `xml:"replacerange,omitempty" json:"replacerange,omitempty"`\n')
        f.write('\tRequired *common.Required `xml:"required,omitempty" json:"required,omitempty"`\n')
        f.write('\tWirelessWeaponBonus *WirelessWeaponBonus `xml:"wirelessweaponbonus,omitempty" json:"wirelessweaponbonus,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate AddUnderbarrels struct
        f.write('// AddUnderbarrels represents additional underbarrel weapons\n')
        f.write('type AddUnderbarrels struct {\n')
        f.write('\tWeapon []string `xml:"weapon" json:"weapon"`\n')
        f.write('}\n\n')
        
        # Generate WeaponAccessoryItems struct (container)
        f.write('// WeaponAccessoryItems represents a collection of standalone weapon accessories\n')
        f.write('type WeaponAccessoryItems struct {\n')
        f.write('\tAccessory []WeaponAccessoryItem `xml:"accessory,omitempty" json:"accessory,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate ModName struct (for mods)
        f.write('// ModName represents a mod name\n')
        f.write('type ModName struct {\n')
        f.write('\tContent string `xml:",chardata" json:"+content,omitempty"`\n')
        f.write('\tRating *string `xml:"rating,attr,omitempty" json:"+@rating,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate ModsContainer struct (for standalone mods)
        f.write('// ModsContainer represents a mods container\n')
        f.write('type ModsContainer struct {\n')
        f.write('\tName []ModName `xml:"name,omitempty" json:"name,omitempty"`\n')
        f.write('\tHide *string `xml:"hide,omitempty" json:"hide,omitempty"`\n')
        f.write('\tAddSlots *string `xml:"addslots,omitempty" json:"addslots,omitempty"`\n')
        f.write('\tMod []WeaponModItem `xml:"mod,omitempty" json:"mod,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponModItem struct (standalone mod)
        f.write('// WeaponModItem represents a standalone weapon mod\n')
        f.write('type WeaponModItem struct {\n')
        f.write('\tName string `xml:"name" json:"name"`\n')
        f.write('\tCategory string `xml:"category" json:"category"`\n')
        f.write('\tRating string `xml:"rating" json:"rating"`\n')
        f.write('\tcommon.Visibility\n')
        f.write('\tSlots string `xml:"slots" json:"slots"`\n')
        f.write('\tAvail string `xml:"avail" json:"avail"`\n')
        f.write('\tCost string `xml:"cost" json:"cost"`\n')
        f.write('\tcommon.SourceReference\n')
        f.write('\tAccessoryCostMultiplier *string `xml:"accessorycostmultiplier,omitempty" json:"accessorycostmultiplier,omitempty"`\n')
        f.write('\tAddMode *string `xml:"addmode,omitempty" json:"addmode,omitempty"`\n')
        f.write('\tAmmoBonus *string `xml:"ammobonus,omitempty" json:"ammobonus,omitempty"`\n')
        f.write('\tAmmoReplace *string `xml:"ammoreplace,omitempty" json:"ammoreplace,omitempty"`\n')
        f.write('\tAPBonus *int `xml:"apbonus,omitempty" json:"apbonus,omitempty"`\n')
        f.write('\tConceal *int `xml:"conceal,omitempty" json:"conceal,omitempty"`\n')
        f.write('\tDicePool *string `xml:"dicepool,omitempty" json:"dicepool,omitempty"`\n')
        f.write('\tDVBonus *int `xml:"dvbonus,omitempty" json:"dvbonus,omitempty"`\n')
        f.write('\tFullBurst *int `xml:"fullburst,omitempty" json:"fullburst,omitempty"`\n')
        f.write('\tModCostMultiplier *string `xml:"modcostmultiplier,omitempty" json:"modcostmultiplier,omitempty"`\n')
        f.write('\tRangeBonus *int `xml:"rangebonus,omitempty" json:"rangebonus,omitempty"`\n')
        f.write('\tRC *string `xml:"rc,omitempty" json:"rc,omitempty"`\n')
        f.write('\tRCGroup *int `xml:"rcgroup,omitempty" json:"rcgroup,omitempty"`\n')
        f.write('\tSuppressive *int `xml:"suppressive,omitempty" json:"suppressive,omitempty"`\n')
        f.write('\tGears *WeaponGears `xml:"gears,omitempty" json:"gears,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponModItems struct (container)
        f.write('// WeaponModItems represents a collection of standalone weapon mods\n')
        f.write('type WeaponModItems struct {\n')
        f.write('\tMod []WeaponModItem `xml:"mod,omitempty" json:"mod,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponMountMods struct
        f.write('// WeaponMountMods represents weapon mount mods\n')
        f.write('type WeaponMountMods struct {\n')
        f.write('\tName []ModName `xml:"name,omitempty" json:"name,omitempty"`\n')
        f.write('\tHide *string `xml:"hide,omitempty" json:"hide,omitempty"`\n')
        f.write('\tAddSlots *string `xml:"addslots,omitempty" json:"addslots,omitempty"`\n')
        f.write('\tMod []WeaponModItem `xml:"mod,omitempty" json:"mod,omitempty"`\n')
        f.write('}\n\n')
        
        # Generate WeaponsChummer struct (root element)
        f.write('// WeaponsChummer represents the root chummer element for weapons\n')
        f.write('type WeaponsChummer struct {\n')
        f.write('\tVersion *string `xml:"version,omitempty" json:"version,omitempty"`\n')
        f.write('\tCategories []WeaponCategories `xml:"categories,omitempty" json:"categories,omitempty"`\n')
        f.write('\tWeapons []Weapons `xml:"weapons,omitempty" json:"weapons,omitempty"`\n')
        f.write('\tAccessories []WeaponAccessoryItems `xml:"accessories,omitempty" json:"accessories,omitempty"`\n')
        f.write('\tMods []ModsContainer `xml:"mods,omitempty" json:"mods,omitempty"`\n')
        f.write('}\n\n')
    
    print("Generated weapons.go")

if __name__ == '__main__':
    print("Generating weapons from weapons.xsd...")
    generate_weapons()
    print("Done!")

